### ISSUE TITLE
左侧发起项目   滚动条区域太小了

### ISSUE THREAD

**Issue by hein2016** [thx/iconfont-plus#1]
新本iconfont 左侧发起项目   滚动条区域太小了 显示很不方便

**Comment by donfo** [comment]
因项目太多，项目管理支持分组就更好了

**Comment by donfo** [comment]
添加项目成员最好能把历史项目已有的成员直接显示可点选，不用每次都搜索

**Comment by Muqing1221** [comment]
一楼同学： 之后我们会考虑，让上下区间比例可调~~拿出小本子记下了~多谢~~

二楼/三楼同学：谢谢你的建议~~我们会认真考虑的~~
