### ISSUE TITLE
登录方式多样化一些，能支持公司组件库共同使用就好了

### ISSUE THREAD

**Issue by flrainbow** [thx/iconfont-plus#1004]
公司的组件库好多人都要上传使用下载什么的，但是登录方式没有可以让我们公用的，希望更加完善一些，邮箱啊什么的登录方式加上就好了

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖三方登录。如果需要找回老账号遇到问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
