### ISSUE TITLE
每次都要更新代码

### ISSUE THREAD

**Issue by yimobing** [thx/iconfont-plus#1007]
添加了一个新图标，每次要使用这个新图标都要更新一下代码，实在是。。。

**Comment by imouou** [comment]
这个我也是...

**Comment by gongeek** [comment]
1.更新地址是方便清缓存。
2.如果是一个地址，直接在iconfont的项目管理删除图标，就会直接影响到线上，是不是更新图标还是交给项目代码决定。

**Comment by imouou** [comment]
其实如果按iconfont 下载下来的样式文件去引入更新, 代码更新是没有影响的, 糟糕就糟糕在图标可能是从几个不同项目中添加进来合并成一个项目, 所以需要重新规范样式名, 所以我的做法是把图标的unicode编码, 写在自己的样式文件里, 这样就造成每次加入新的图标, unicode编码更新, 我的样式文件就全部乱了. 相信这种情况应该很常见.
