### ISSUE TITLE
想要追加新的图标一直是个大问题

### ISSUE THREAD

**Issue by hubangmao** [thx/iconfont-plus#1012]
加入购物车也是本地的清除后就没有了 ,o(╥﹏╥)o o(╥﹏╥)o

**Comment by duanxiansheng** [comment]
追加问题解决了么？

**Comment by hubangmao** [comment]
> 追加问题解决了么？
创建一个项目,将图标加入项目中保存,能解决历史储存图标问题

**Comment by gongeek** [comment]
项目也有直接上传图标的快捷入口了，欢迎使用
![image](https://user-images.githubusercontent.com/3911824/47897519-24a06500-dead-11e8-910a-88781044950e.png)
