### ISSUE TITLE
老版本的部分图标显示不了

### ISSUE THREAD

**Issue by doramart** [thx/iconfont-plus#102]
![qq 20161101203644](https://cloud.githubusercontent.com/assets/11911066/19890113/a61f3022-a073-11e6-8fae-b49e653aae75.jpg)

**Comment by doramart** [comment]
老版本正常
![20161101204454](https://cloud.githubusercontent.com/assets/11911066/19890187/18180f0a-a074-11e6-8272-4f29fce54a01.png)

**Comment by Muqing1221** [comment]
这些铁蛋是多色图标~老版本不支持，所以....

**Comment by Muqing1221** [comment]
亲能说一下是搜索哪个关键词后出现的么，有链接地址可以回复一下么~

**Comment by doramart** [comment]
是我自己上传的图标 没有颜色的 我说的是老版本上可以显示  新版本无法正常显示  在新版本上重新上传还会报错

**Comment by Muqing1221** [comment]
@gongeek

**Comment by gongeek** [comment]
@doramart  出问题的图标的源文件能否给我一份? gongweiqm@qq.com

**Comment by purplebamboo** [comment]
这个问题  有点奇怪，是这样的亲，
* 老版本是单色所以把svg里面所有path合在一起展示的。
* 新版里面因为需要支持多色了，所以要分path去展示。

我排查了下  发现你这个svg有点奇怪，如果是合成一个path，就正常，如果分path展示，就会是黑乎乎的一块，具体原因我还要继续排查，不过其实不影响生成字体，因为生成字体的时候会变成一个path生成字体的哈。

**Comment by doramart** [comment]
但是我传到新版里面 就不正常了 我需要怎么调整？

**Comment by purplebamboo** [comment]
亲  你是前端吗？ 如果是前端，那么把svg里面所有的path里面的路径合起来。

**Comment by purplebamboo** [comment]
比如 
```
<svg class="icon" style="" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="1229" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200">
<path d="1111"></path>
<path d="222"></path>
</svg>

```
你变成：

```
<svg class="icon" style="" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="1229" xmlns:xlink="http://www.w3.org/1999/xlink" width="200" height="200">
<path d="1111222"></path>

</svg>

```
再上传就可以了。。。

**Comment by purplebamboo** [comment]
如果你是 设计师，在ai里面  合并所有路径哈。
