### ISSUE TITLE
搜索不能跳转到某图标的作者，该作者的系列坐标更具有统一性

### ISSUE THREAD

**Issue by FunzoCheng** [thx/iconfont-plus#1020]

**Comment by smile-magic** [comment]
同建议,搜索出来的点击图标可以跳转这个图标所有图标页.

**Comment by LuckWolf** [comment]
可以的
![image](https://user-images.githubusercontent.com/11513716/46989325-4cfb3600-d12f-11e8-9fed-c9a782480f93.png)

**Comment by FunzoCheng** [comment]
> 可以的，点击下载，在下载界面上
> ![image](https://user-images.githubusercontent.com/11513716/46989325-4cfb3600-d12f-11e8-9fed-c9a782480f93.png)

感谢回答。借楼回复一下其他有相同困扰的使用者。可能和我的情况一样
<img width="1229" alt="2018-10-16 10 42 50" src="https://user-images.githubusercontent.com/33441468/46989844-51c0e980-d131-11e8-9ced-e2da86f30906.png">
搜索特定词后出现的 icon，鼠标移过去有三个入口，点击下载不会直接下载，会跳出 LuckWolf 示意的界面，再选择创作者就可以跳转了。

**Comment by FunzoCheng** [comment]
只能说埋得有点深了ヾ(･ε･｀*)，鼠标触发图标后的三个入口，和跳转创作者的页面中间有一个默认的操作：就是使用者知道下载入口不会直接下载，而是有细化页面可以二次操作。但事实是很多使用者都会有这样的下载前提：这个图标很好看，但我要全套，如果没有全套，这个单个的好看图标可能没有意义。然后就选择不下载，也就看不到下载入口后面的页面。

**Comment by PeggyWeb** [comment]
现在点击进去作者的图标库是空的

**Comment by yisibl** [comment]
如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)

后续我们会考虑优化交互，减少入口深度，感谢大家的支持。
