### ISSUE TITLE
微博账号无法登录，请求转到Github账号里来

### ISSUE THREAD

**Issue by Svmtimend** [thx/iconfont-plus#1022]
不知道是不是微博账号异常的事儿，网页现在一直有二维码弹窗，无法输入密码登录，扫描登录也没有任何反应。原有账号已经有大量图标和项目，希望全部转到这个Github账号里来。谢谢！微博账号fangya1990@qq.com

**Comment by Svmtimend** [comment]
客服看一眼好吗？好多项目的图标都在那个帐号上呢……

**Comment by Svmtimend** [comment]
……HELP

**Comment by Svmtimend** [comment]
HELP

**Comment by Svmtimend** [comment]
请管理员看一眼啊，谢谢！

**Comment by yisibl** [comment]
Duplicate of #1718
