### ISSUE TITLE
icon生成的class 数字被去除了。

### ISSUE THREAD

**Issue by Async-Lee** [thx/iconfont-plus#1026]

**Comment by ZBUR** [comment]
这个的确蛋疼，虽然class的名称第一个字不能为数字，但连中间或最后的数字都去掉了，这有点坑

**Comment by yisibl** [comment]
是名称过长导致的吗？

**Comment by Async-Lee** [comment]
@yisibl  不是。ui取名的时候icon包含数字，生成class的时候数字直接被去掉了

**Comment by ZBUR** [comment]
@yisibl 不是，虽然默认限制20个字符长度（上传后再编辑无限制长度），但就是很短的名称只要有数字就会去除

**Comment by yisibl** [comment]
操作步骤和截图麻烦提供一下

**Comment by ZBUR** [comment]
上传图标数字去除问题：
以上传一个包含数字短名称和一个包含数字长名称的svg为例
![defee81ab8a35b8997c6cf9e3ab64d09](https://user-images.githubusercontent.com/37613475/53172026-4883e400-361f-11e9-9f83-55c35c603d65.png)
![8efffbaa5d8b69d0deca92354214d0e5](https://user-images.githubusercontent.com/37613475/53172054-58032d00-361f-11e9-9dd7-114fec31424f.png)
上传是以下这样的：
![7cb02c61c7550719fd55c6e8e8a23fa3](https://user-images.githubusercontent.com/37613475/53172095-749f6500-361f-11e9-9508-68baff213553.png)
![2218a6104824b4cc5af0bd6042fdd48c](https://user-images.githubusercontent.com/37613475/53172115-808b2700-361f-11e9-8cbb-bda50999fb97.png)
上图出现字符长度的限制（20位），当上传大量图标时需改动较麻烦
上传后打开编辑是以下这样的：
![558b4041f4a7488ddca416f77972f972](https://user-images.githubusercontent.com/37613475/53172158-9ef12280-361f-11e9-81bf-0c09608c2006.png)
可以看到上图的class没有和名称保持一致，数字被过滤掉了，需后期修改较耗时
![c24102b3d1c0cdb0333377555ec1fbbd](https://user-images.githubusercontent.com/37613475/53172210-bcbe8780-361f-11e9-88f9-ac745d27269b.png)
在编辑模式里改动是可保存的，包括长名称和加数字（看下图为更改保存后再打开编辑模式），即要自己手动补齐缺失的字母数字，而且改完一个保存自动刷新耗时间较长，当要修改大量图标时耗时可观（我之前上传2千~3千多个图标就改class都花了我两天了）
![990e15f6e3674d65a2ea2020181f4811](https://user-images.githubusercontent.com/37613475/53172326-00b18c80-3620-11e9-8e9f-251925f9ec5c.png)
建议：
1.上传时不限制字符长度
2.上传后的Font Class/Symbol最好能和Icon Name保持一致（关于class首字不能为数字，由于项目设置可加前缀，建议不要自动过滤掉Font Class/Symbol首字带数字）
3.上传时的界面里建议除了原来“名称”、“标签”外，加多个“Font Class/Symbol”input项，可以在提交前自定义修改
4.可以的话，有没好的方案解决后期如果需要编辑大量的图标的Icon Name/Tags/Font Class/Symbol，由于弹窗保存刷新显示一套下来太耗时间，比如加个功能模式可以在修改完多个图标后只需一次性保存

**Comment by dingyanhe** [comment]
@yisibl 小弟遇到了同样的问题，原来的项目是用 [sjy/symbols4sketch](https://github.com/sjy/symbols4sketch) 这个库生成的字体。

1、 字体在sketch里的名字就是icon的名字：eg. `icon-001-home` => `icon-001-home`

2、 对应的`unicode`码是`\F000`

项目越来越多后出现字体维护太费力了，发现iconfont很不错，想转过来。

问题一：上传成功后遇到了和 @Async-Lee 一样的问题，数字被屏蔽了

```
icon-001-home => icon--home
```

问题二：想自定义字体的`unicode`码，

>  \F000 => \e601

上面两个问题意味着，每传一个`icon`都要单独修改它的`unicode`码和它的icon名称，还是比较麻烦的。

想加个建议:
上传时`unicode`码可以自定义。

**Comment by SolidZORO** [comment]
今天同遇到了问题，上传十几个 filename 带数字的 svg……最后一个个命名太酸爽了。看来隔了那么久时间，这个 bug 估计没人修了，主要是人肉改吧，每改好一个 List 还自动刷一次，改完 50 花了 2 小时……

**Comment by yisibl** [comment]
很抱歉，让各位久等了，现在图标名称已经支持数字，名称最长 50 个字符。后续有其他问题可以加钉钉群讨论（群号 : 21791453）

@D3III 的很多建议非常好，我们会讨论后根据优先级考虑是否支持。
