### ISSUE TITLE
搜索功能无法找到该icon属于哪个分类

### ISSUE THREAD

**Issue by SouthWindYin** [thx/iconfont-plus#1029]
希望可以根据搜索到的icon找到他属于哪个项目或者类别的功能，经常会需要同一风格的icon，搜索却不好找

**Comment by yisibl** [comment]
如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)
