### ISSUE TITLE
搜索到一个好看的图标之后，往往想要获取该图标对应的一套图标

### ISSUE THREAD

**Issue by segry** [thx/iconfont-plus#1033]
当前没有这样的入口，加上就棒棒哒

**Comment by LuckWolf** [comment]
有间接入口的，点击下载，在下载界面有from地址

**Comment by Tiff-wyr** [comment]
楼上说的对

**Comment by YvesChen** [comment]
![cba4856c-40e7-483b-bf4c-c27da3042c35](https://user-images.githubusercontent.com/5573829/48460225-d8d4b080-e808-11e8-8842-b3e999c2e735.png)
![25bbee03-9e16-42df-ba5a-f58856174ddd](https://user-images.githubusercontent.com/5573829/48460227-dc683780-e808-11e8-8e86-7fb864c5ea3a.png)
