### ISSUE TITLE
建议能够在搜索的时候提示下是哪一套图标

### ISSUE THREAD

**Issue by Xavier0818** [thx/iconfont-plus#1036]
通常在搜索左右箭头的时候，搜到了心仪的左箭头，却不知道右箭头怎么匹配，没有提示归属字体库，找不到匹配的右箭头

**Comment by gongeek** [comment]
功能是有的 你得筛选下精选图标 点击下载 查看From来着哪个图标库 具体请参考这里   https://github.com/thx/iconfont-plus/issues/797
