### ISSUE TITLE
设计师上传icon报500上传失败，麻烦看下是什么原因

### ISSUE THREAD

**Issue by lanfengZhou** [thx/iconfont-plus#1037]
[操作笔记.svg.zip](https://github.com/thx/iconfont-plus/files/2487187/svg.zip)

**Comment by gongeek** [comment]
看了下是因为图标使用了渐变填充 目前暂时不支持渐变的解析 后续会考虑支持

**Comment by yisibl** [comment]
支持渐变图标请关注：https://github.com/thx/iconfont-plus/issues/1938
