### ISSUE TITLE
搜索时小骷髅的动效建议保留

### ISSUE THREAD

**Issue by GentlemanLuLu** [thx/iconfont-plus#104]
旧版在搜索是小骷髅的眼睛会睁大，建议新版保留，这个效果很可爱亲切。

**Comment by Muqing1221** [comment]
已经是第N+1次听到这样的呼声了
我们决定
集齐9个
就召唤回小小骷髅~~哈哈
（讲真，恩，情感化的互动，我们慢慢憋大招...慢慢....）
