### ISSUE TITLE
按分类或关键字搜索图标

### ISSUE THREAD

**Issue by ChowinlI** [thx/iconfont-plus#1042]
有时候需要某一类的图标，但搜索只支持按图标名称或作者名称搜索，这样很不方便

**Comment by JsckChin** [comment]
同样

**Comment by Gensp** [comment]
同求，项目列表一多，每次添加图标找项目，找半天

**Comment by pzjzeason** [comment]
2019年了，怎么还没有人管管这个问题啊
@yisibl

**Comment by yisibl** [comment]
如果是项目维度的图标分类，请关注这个问题：Duplicate of #1496
