### ISSUE TITLE
iOS图标不支持彩色嘛

### ISSUE THREAD

**Issue by snowalfra** [thx/iconfont-plus#105]
请问iOS图标不支持彩色嘛？

**Comment by Muqing1221** [comment]
http://www.iconfont.cn/plus/help/detail?helptype=code
可以的啊，看教程~

**Comment by snowalfra** [comment]
不可以啊，iOS开发不支持的

**Comment by Muqing1221** [comment]
完了，你这是刁难一个设计汪，我呼唤开发同学来支援了
@gongeek

**Comment by snowalfra** [comment]
你怎么知道我是设计汪的。。。。。

**Comment by Muqing1221** [comment]
我说我...

**Comment by snowalfra** [comment]
哦，我也是设计汪。。。。。。

**Comment by purplebamboo** [comment]
是这样的  字体肯定是不支持彩色的。如果你用png，svg，啥的都是支持彩色的。或者使用最新的symbol的引入方式，不过这种方式应该有web里面可以用。

**Comment by snowalfra** [comment]
谢谢你，我是个小设计师，哈哈
