### ISSUE TITLE
微博账号异常无法登陆

### ISSUE THREAD

**Issue by starzyj** [thx/iconfont-plus#106]
好多项目图标在里面，改东西都改不了了，坑死我了。账号13545342241

**Comment by Muqing1221** [comment]
现在很多用户都遇到了这个问题，我们在紧张的修复哈~亲别急
@purplebamboo

**Comment by starzyj** [comment]
为什么改版之后都变成英文了。 没读过书的不让用吗

**Comment by DreamCapriccio** [comment]
哈哈。我也奇怪，为什么要在英文网站上交流中文，欺负我这看不懂英文的

**Comment by purplebamboo** [comment]
额。。右上角  有个中英文切换的。。而且默认是中文的呀，是不是你们 不小心切换了。。＝ ＝

**Comment by DreamCapriccio** [comment]
表示很少登录这个网站，反正进来就是英文，没看到有中文切换

**Comment by purplebamboo** [comment]
![wangwang20161102125240](https://cloud.githubusercontent.com/assets/1409611/19917138/653e460a-a0fb-11e6-846e-4db38723ca50.png)

这里哈

**Comment by DreamCapriccio** [comment]
尴尬，我以为说的是github这个网站，iconfont 木有问题，就是中文

**Comment by purplebamboo** [comment]
哈  github可能设计师用的不多，这个我们用来反馈问题的，中英文我们是没办法的哈。

**Comment by starzyj** [comment]
这个个人中心是我见过最难用的。弄个账号太麻烦。

**Comment by purplebamboo** [comment]
@starzyj   sorry  因为自建登陆体系比较麻烦，所以直接用第三方登陆，亲  这样  你用github登陆，把用户id。或者账户名发给我，我再去帮你找下 之前微博的那个账号，帮你把项目都转过去。

微博登陆的问题，我们也很无奈，不是太稳定，我们再试试联系微博那边的人试试。
