### ISSUE TITLE
界面颜色太暗，很累眼睛。

### ISSUE THREAD

**Issue by beibeidi** [thx/iconfont-plus#107]
还是觉得之前的颜色很好，很舒服~简洁又直观。建议变成浅色。

**Comment by Muqing1221** [comment]
不过我倒是觉得或许以后我们可以搞个深色版本和浅色版本哦~~哈哈
亲们按需索取~
我mark啦，谢谢建议

**Comment by purplebamboo** [comment]
后续我们内部先讨论下 ，我们先记录下来
