### ISSUE TITLE
登录功能问题反馈

### ISSUE THREAD

**Issue by qfxiongbin** [thx/iconfont-plus#1070]
提示先登录 第一次选择用GITHUB登陆  

点击图标，下载 又跳转到请登录界面

第二次 微博扫码登录

点击图标 下载，又跳转到登陆界面

我确定登录成功了 ，可是系统没有记录我得会话吧？

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖微博的三方登录。如果遇到问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
