### ISSUE TITLE
给非员工可以使用吗

### ISSUE THREAD

**Issue by ByronLYX** [thx/iconfont-plus#1078]
这个icon图库可以给非阿里员工使用吗？尽量可以吧，我不商用，只是用来学习，技术本来就应该相互学习，资源共享，共同进步，更何况，这些既然可以被我们看到，就不是很机密的东西，为什么不给我们使用一下呢，况且还让我们提建议，一不给用，怎么提建议，二，既然利用我们使产品优化，那为什么不给我们使用呢，只让我们花时间，让你们变好，对我们没有好处，这是不对等，不公平

**Comment by cricy** [comment]
亲，可以学习使用的。
