### ISSUE TITLE
icon项目被成员批量删除了 如何恢复，求救

### ISSUE THREAD

**Issue by GrootLw** [thx/iconfont-plus#1079]
icon项目被项目成员手动批量删除了  请问能恢复吗？

**Comment by yisibl** [comment]
我们已经上线了项目成员权限管理功能，目前只有超级管理员和管理员可以删除、添加成员了，所以为了更加安全的管理项目，建议把无关人员设置为只读成员。https://www.yuque.com/u7268/iconfont/vkneb9
