### ISSUE TITLE
报告管理员，前方发现bug一只，求消灭

### ISSUE THREAD

**Issue by DreamCapriccio** [thx/iconfont-plus#108]
![qq 20161102134954](https://cloud.githubusercontent.com/assets/21968015/19918029/4875ac0e-a103-11e6-9078-6e14f0aefd19.jpg)
在图标管理页面，点击到我的项目页面，然后再点击我的收藏和我的图标，会发现无法切换了，用的是火狐浏览器，试了好多次都是这样，测试谷歌貌似也是一样的结局。

**Comment by Muqing1221** [comment]
我也发现了
@gongeek @purplebamboo （我用微博账号测试有问题的，aone提了对应bug）

**Comment by gongeek** [comment]
已修复
