### ISSUE TITLE
官网图标编辑，图标命名输入框，选中颜色为白色，导致看不见选中文字

### ISSUE THREAD

**Issue by RoamIn** [thx/iconfont-plus#1080]
如图下所示，`Control + A` 或者 `Command + A` 选中编辑文字，颜色变白，导致不知道选中的文字是什么。
![bug](https://user-images.githubusercontent.com/11537595/48396071-30fdab00-e754-11e8-939e-9aacc710baf3.gif)

**Comment by yisibl** [comment]
感谢反馈，我们尽快修复。

**Comment by yisibl** [comment]
已经修复。
