### ISSUE TITLE
找到一个合适的图标，然后想看它所在的图组，现在这个功能又没了

### ISSUE THREAD

**Issue by oveui** [thx/iconfont-plus#1082]
找到一个合适的图标，然后想看它所在的图组，现在这个功能又没了，用这个功能主要想找到一些风格统一的图标

**Comment by wonderffee** [comment]
很需要这个功能+1

**Comment by ahdung** [comment]
+1，正想提这个问题，图标的配对非常重要，比如勾/叉，展开/收起，正序/倒序，没有这功能只能靠感觉和不断的试错才能找到也许是“一对”的两个图标。

**Comment by songtaste95** [comment]
+1可能是作者设置了保护隐私，不让访客看吧

**Comment by oveui** [comment]
> +1可能是作者设置了保护隐私，不让访客看吧

不是的，是这个功能被去掉了

**Comment by gongeek** [comment]
功能还在的 不是所有的图标都来自图标库的 你需要在搜索结果点下筛选 "精选"图标  点开下载页 找到Form的图标库  具体请见这里=> https://github.com/thx/iconfont-plus/issues/1097
