### ISSUE TITLE
字体文件名能不能与字体名称一致?

### ISSUE THREAD

**Issue by ProgrammerHuang** [thx/iconfont-plus#1086]
字体文件名能不能与字体名称一致?

如果两个项目, 同时使用, 字体文件名都叫iconfont容易冲突.

**Comment by cricy** [comment]
在编辑项目里提供了 Font Family 修改的功能。
字体文件名现在是按时间动态生成，不适合用于Font Family。

**Comment by ProgrammerHuang** [comment]
字体文件名, 没有按时间生成呀, 都是iconfont.* 这个文件名呀.

![image](https://user-images.githubusercontent.com/9100279/49120845-53adc900-f2e9-11e8-9e51-0ef2b0dfa139.png)

如果我在一个页面中, 同时使用了两套的图标(不同主题风格), 那不是冲突了.
这样的话, 是不是要分不同的目录来存放?

现在很多人使用LESS和SASS, 能不能生成一个这样的库文件, 我们可以import这些库文件, 调用函数或@mix 这样的东西, 把样式前缀什么的, 自己传入, 也可以打包在自己的样式文件中去.

> 字体文件名现在是按时间动态生成，不适合用于Font Family。
最后, 文件名, 为什么非要按时间呢? 使用Font Family为什么不行呢? 或者使用前缀也可以呀?
