### ISSUE TITLE
为什么我将自己的SVG上传到里面全是空白

### ISSUE THREAD

**Issue by xiaojiu411** [thx/iconfont-plus#1087]
为什么我将自己的SVG上传到里面全是空白?自己从PSD上导出的SVG，上传到iconfont，没有颜色，只是空白的，而且我自己用浏览器打开SVG就没有问题

**Comment by gongeek** [comment]
图标源文件的svg code 可以贴出来下吗？

**Comment by 082530** [comment]
因为你的不是真正的矢量图，所以不显示，你可以打开你的svg文件看源码，里面要有path标签才是真正的矢量图

**Comment by tangshuimei** [comment]
查了有path标签的，但是还是不行

**Comment by yisibl** [comment]
统一到 https://github.com/thx/iconfont-plus/issues/1937 回复
