### ISSUE TITLE
请求恢复eps格式！！！

### ISSUE THREAD

**Issue by chris573** [thx/iconfont-plus#109]
现在网站下载svg是svg格式，下载ai也是svg格式。我的ai软件用不了，eps可以直接植入ps，很方便。希望可以恢复eps格式。  please provide .eps file for download, we need this format

**Comment by Muqing1221** [comment]
啊哈，我们是祖国的团队....祖国的....中文就好

eps在多色渲染上现在存在丢丢问题，我们可能要稍晚些才有资源修复...如果亲对于.eps是刚需，可能要多等一段时间了
因为svg也是矢量，所以暂时都走svg了，亲说的不能直接植入ps...确实...但是亲可以先用ai打开，然后在拖进ps...

只能先麻烦亲下个AI了...

**Comment by chris573** [comment]
谢谢回复；
是这样，手上的本本因为是几年的渣渣本，显卡老旧，AI软件复制图层、另存为矢量格式都卡死；
  新的本本物色中。会恢复最好，不然我也只能等换个本本。目前可以先用png丢ps里先。 谢谢你们，谢谢好用的平台[cid:_Foxmail.1@000a98b3-0f70-958b-9172-3a51727eb932]

________________________________
qi573@live.cn

发件人： Muqing1221<mailto:notifications@github.com>
发送时间： 2016-11-02 17:03
收件人： thx/iconfont-plus<mailto:iconfont-plus@noreply.github.com>
抄送： chris573<mailto:qi573@live.cn>; Author<mailto:author@noreply.github.com>
主题： Re: [thx/iconfont-plus] 请求恢复eps格式！！！ (#109)

啊哈，我们是祖国的团队....祖国的....中文就好

eps在多色渲染上现在存在丢丢问题，我们可能要稍晚些才有资源修复...如果亲对于.eps是刚需，可能要多等一段时间了
因为svg也是矢量，所以暂时都走svg了，亲说的不能直接植入ps...确实...但是亲可以先用ai打开，然后在拖进ps...

只能先麻烦亲下个AI了...

**Comment by purplebamboo** [comment]
目前彩色图标 eps的转换还有点问题 ，我们忙完双十一会努力去攻克的哈。请 亲再等一段时间。
