### ISSUE TITLE
建议增加添加好友功能

### ISSUE THREAD

**Issue by aquadan** [thx/iconfont-plus#1091]
每次新建一个项目icon，都要重新添加一次项目成员，而且以前添加项目成员也没记录，每次就要再问一次账号名称再添加，特别麻烦。希望有好友功能或者项目成员邀请功能。

**Comment by cricy** [comment]
以前的项目中已经会有相关成员信息，在那边应该可以查找得到。
不过你说的添加好友功能，我们后面也会考虑。
谢谢你的提议！
