### ISSUE TITLE
报错报错

### ISSUE THREAD

**Issue by qihong1983** [thx/iconfont-plus#1099]
Icon.createFromIconfontCN antd design  编译 的时候报错  

Line 1:      Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions
  Line 1:  Expected an assignment or function call and instead saw an expression  no-unused-expressions

**Comment by gongeek** [comment]
请反馈到维护这个工具的地方 这个应该不是我们维护的
