### ISSUE TITLE
用户注册

### ISSUE THREAD

**Issue by Quaximodo** [thx/iconfont-plus#1102]

**Comment by Quaximodo** [comment]
为什么不能够直接用邮箱注册，为什么一定要微博之类的注册？为什么我注册完GitHub，怎样都无法验证我的邮箱？难道有人不喜欢玩微博都不行吗？这是一间大公司为人服务的精神就这样？如果不想为更多的用户服务，请你继续刁难用户里

**Comment by ntfs32** [comment]
开源精神，谁服务谁？凭什么？ 那么大意见
