### ISSUE TITLE
转让项目选错人员，选中了不在项目中的人员，求救

### ISSUE THREAD

**Issue by anyuankeji** [thx/iconfont-plus#1104]
转让是输入用户ID，输入后还有联想搜索，由于网络延迟，点击确定的时候才刷新出搜索列表，选中了第二个ID，导致转让项目给项目外的人员，求助可以协助找回吗

**Comment by gongeek** [comment]
项目id是多少知道吗？你的用户id是多少？你转错的用户是什么名字？

**Comment by anyuankeji** [comment]
我的用户ID“颠小疯”，本来要转到“anyuankeji”，错转到了“轩辕可鉴007”，请问项目ID在哪查看，目前我能看到项目名称“字体图标”，FontClass/Symbol 前缀“icon”，Font Family“iconfont”

**Comment by anyuankeji** [comment]
> 项目id是多少知道吗?你的用户id是多少?你转错的用户是什么名字?

我的用户ID”颠小疯”,本来要转到“anyuankeji”,错转到了“轩辕可鉴007”,请问项目ID在哪查看,目前我能看到项目名称“字体图标”,FontClass /符号前缀“图标”,字体“iconfont”

**Comment by gongeek** [comment]
项目Id可以在css代码里面看到 就是这个注释里面
![image](https://user-images.githubusercontent.com/3911824/49427607-b0741c80-f7de-11e8-86fe-d6c2481682c5.png)

**Comment by anyuankeji** [comment]
请问可以协助将项目转回吗 :)

**Comment by gongeek** [comment]
稍等 给您看下

**Comment by anyuankeji** [comment]
好的，麻烦了

**Comment by gongeek** [comment]
已转回给你了

**Comment by anyuankeji** [comment]
太感谢了
