### ISSUE TITLE
用font-class这种方式，下载的css文件有bug

### ISSUE THREAD

**Issue by wuyonglv** [thx/iconfont-plus#1107]
css返回的结果如下：
`@font-face {
    font-family: "anticon";
    src: url('//at.alicdn.com/t/font_621650_zurhgwosi2s.eot?t=1544078446228');
    ...
}

.anticon {
    font-family: "anticon" !important;
    font-size: 16px;
    font-style: normal;
    -webkit-font-smoothing: antialiased;
    -moz-osx-font-smoothing: grayscale;
}
.anticon-xxxx:before {}`
============================
虽然类anticon设置了font-family: "anticon" !important;
但是.anticon:before并不会继承这个font-family: "anticon" !important;
字体图标会显示不出来

**Comment by gongeek** [comment]
font-class 的正确用法是  clas="antion antion-xxx" 2个类都要写上.
不知道怎么用的话 点下下面的这个按钮 下载到本地 里面有个文件 demo_fontclass.html 会告诉你怎么用
![image](https://user-images.githubusercontent.com/3911824/49570056-91a58f80-f970-11e8-8408-20e471bfbbd8.png)
