### ISSUE TITLE
页面中使用base标签，xlink:href不能正确引用sprite

### ISSUE THREAD

**Issue by 5468sun** [thx/iconfont-plus#111]
<base href="/uc/" />

<svg class="icon" aria-hidden="true">
                        <use xlink:href="#icon-mendian"></use>
                    </svg>

**Comment by 5468sun** [comment]
找到一个polyfill，但是感觉不是很理想。
https://gist.github.com/leonderijke/c5cf7c5b2e424c0061d2

**Comment by purplebamboo** [comment]
这个我们也不是很清楚哎，好像场景很特殊呀。

现在还有人用  base的？

**Comment by 5468sun** [comment]
angularjs url 改写 时用到哦

**Comment by smart-dream** [comment]
@5468sun 亲，你解决了吗？

**Comment by smart-dream** [comment]
@5468sun  亲 你是怎么解决这个问题的呢？求指教。
