### ISSUE TITLE
github无法登陆

### ISSUE THREAD

**Issue by jingxiawl** [thx/iconfont-plus#1111]
登陆输入用户名密码后跳转这个页面，后面不管怎么点击github登陆都直接进入这个页面了
![image](https://user-images.githubusercontent.com/11657532/49785092-5503da80-fd5a-11e8-8106-4ef86f6392ff.png)

**Comment by cricy** [comment]
#1109

**Comment by xiaotian000** [comment]
同问题  如何处理？

**Comment by jingxiawl** [comment]
@xiaotian000 就他指向的按个问题。改地址了https://www.iconfont.cn/
