### ISSUE TITLE
几个建议或者说是期望吧

### ISSUE THREAD

**Issue by ydq** [thx/iconfont-plus#112]
- 添加woff2格式的支持
- 添加色系搜索和筛选
- 账号支持更换绑定或者添加绑定（防止微博账号被封导致无法登陆）

**Comment by Muqing1221** [comment]
收到，谢谢亲的建议，后期我们会考虑的~

**Comment by purplebamboo** [comment]
这里统一讨论哈：
https://github.com/thx/iconfont-plus/issues/139
