### ISSUE TITLE
能否可以生成一个固定一个链接？？？

### ISSUE THREAD

**Issue by liub1934** [thx/iconfont-plus#1120]
[#891](https://github.com/thx/iconfont-plus/issues/891)的我看过了，并没有卵用，每次改了图标后就得重新生成连接，重新发布，归根结底还是固定连接浏览器缓存的问题，不知道能不能参考unpkg的做法，固定连接永久指向最新版本，如unpkg上的jquery文件来说，地址固定地址是：https://unpkg.com/jquery ，最终打开访问后的其实是最新的这个地址https://unpkg.com/jquery@3.3.1/dist/jquery.js 。
-----------------------------------------------------------------
其实我还有个和unpkg类似的法子，利用的自己的服务器，弄一个固定的地址，如icon.xxx.com/project,project指的的项目名称，指向该project的实际icon的文件地址，然后这个地址就是固定的了，每次icon有更新后手动获取到最新的地址，然后把指向该project的实际icon的文件地址替换成新的地址
不知道这法子可行不

**Comment by yisibl** [comment]
非常感谢您的建议，我们研究一下

**Comment by ziyunfei** [comment]
Duplicate of #1331
