### ISSUE TITLE
Iconfonter：一键生成小程序 CSS 的 Chrome 插件

### ISSUE THREAD

**Issue by fjc0k** [thx/iconfont-plus#1121]
- 一键生成项目图标名称的 TypeScript 类型定义
- 一键生成小程序 CSS
- 一键打包下载项目 SVG 图标

![image](https://user-images.githubusercontent.com/13151189/50135110-fe544e80-02cd-11e9-9289-8e21176c1c2e.png)

**Comment by fjc0k** [comment]
欢迎试用：https://chrome.google.com/webstore/detail/iconfonter/kapkopnmjlcoahndiemkoihfpecikdgc?utm_source=chrome-ntp-icon

**Comment by yisibl** [comment]
这里是用来反馈 iconfont 问题的，请不要发其他内容哦。
