### ISSUE TITLE
增加支付宝、淘宝、微信等方式登录

### ISSUE THREAD

**Issue by c998877** [thx/iconfont-plus#1127]
建议增加支付宝、淘宝、微信等方式登录

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖三方登录。如果需要找回老账号遇到问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
