### ISSUE TITLE
iOS 调用多套字体，ttf 名如何修改

### ISSUE THREAD

**Issue by Jack-Feng** [thx/iconfont-plus#1136]

**Comment by yisibl** [comment]
暂时可以用第三方的字体编辑工具，比如 fontlab 来修改一下字体名称。后续 iconfont 平台考虑可以自定义字体名称。

**Comment by cricy** [comment]
你得在： 更多操作 -〉 编辑项目 里的，修改 Font Family 这个默认值。

**Comment by Jack-Feng** [comment]
我明白您的回答，这样确实可以修改。
这里需要重新描述一下，项目创建者已消失，我只是参与者。无法修改font family 这个值。
需要的是如何有其他方法，修改内部的font family 这个值。
第三方软件？还是什么操作?
