### ISSUE TITLE
下载代码功能报Error

### ISSUE THREAD

**Issue by zhao812** [thx/iconfont-plus#1137]
下载代码功能报Error
https://www.iconfont.cn/api/project/download.zip?ids=7322375|-1,7322374|-1,7322373|-1,7322372|-1,7322371|-1,7322370|-1,7322369|-1,7322368|-1,7322367|-1,7322366|-1,7322365|-1,7299556|-1,7299451|-1,7299441|-1&ctoken=Q5vU3Z9i0LFP6NtZIQjRyMn3

{"message":"Error"}

**Comment by yisibl** [comment]
在哪里点击的下载？

**Comment by zhao812** [comment]
![error](https://user-images.githubusercontent.com/19986834/50675832-7e4b1a00-102b-11e9-9315-3357fa1a2757.jpg)

**Comment by yisibl** [comment]
已经修复，请验证一下。

**Comment by zhao812** [comment]
ok
