### ISSUE TITLE
下载代码报错

### ISSUE THREAD

**Issue by jinhuang3115** [thx/iconfont-plus#1138]
![image](https://user-images.githubusercontent.com/3615077/50678430-975ac780-1039-11e9-8299-beaf07be74a2.png)
![image](https://user-images.githubusercontent.com/3615077/50678452-af324b80-1039-11e9-836a-63a8ef813eac.png)
![image](https://user-images.githubusercontent.com/3615077/50678455-b5c0c300-1039-11e9-8391-b1bc1b36a399.png)

**Comment by yisibl** [comment]
重复 #1137
