### ISSUE TITLE
点击 "下方新 icon 来袭，点击更新代码，更新后将支持 WOFF2 格式" bug，页面提示： Error

### ISSUE THREAD

**Issue by mydorothy** [thx/iconfont-plus#1139]
![image](https://user-images.githubusercontent.com/20217501/50682783-e9f0af80-104a-11e9-9270-8eef17fc06bd.png)

**Comment by saberLian** [comment]
我也会，后台出错了吗

**Comment by saberLian** [comment]
现在好了

**Comment by chengzhixuan** [comment]
刚刚刷新了下  现在好了
