### ISSUE TITLE
希望能够批量删除项目图标, 以及批量给图标命名

### ISSUE THREAD

**Issue by pollux2015** [thx/iconfont-plus#114]
希望多以项目图标批量的操作, 能够批量删除, 给图标命名, 以及给图标批量命名font class name

**Comment by Muqing1221** [comment]
收到~~
慢慢考虑哈

**Comment by purplebamboo** [comment]
额。。批量删除功能是有的哦。批量命名可以考虑，等我们忙完双十一这段时间哈，需要做个交互才行。
我们记一下，算是优化点，后期会加上去。

**Comment by purplebamboo** [comment]
https://github.com/thx/iconfont-plus/issues/139
