### ISSUE TITLE
能否添加自定义首页背景功能？

### ISSUE THREAD

**Issue by lvsen** [thx/iconfont-plus#115]
工作比较急的时候，内心有点烦躁，希望可以自定义浅色背景

**Comment by Muqing1221** [comment]
哈哈哈，我还以为星空可以降温呢

是的，我们的深色/浅色版本的呼声还蛮高的；我们之后会考虑的哈

**Comment by purplebamboo** [comment]
感觉不是高频需求，亲可以在这里提一下：

https://github.com/thx/iconfont-plus/issues/139
