### ISSUE TITLE
登陆个网站怎么这么艰难？

### ISSUE THREAD

**Issue by sunjianfenggit** [thx/iconfont-plus#1166]
github登陆 让我授权 授权界面又点击不了   微博登陆点击了登陆又回到未登录界面 这真是我见过最坑的一个和阿里相关的产品 不想让我下载就直接屏蔽掉

**Comment by yisibl** [comment]
Duplicate of #1718

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖微博的三方登录。如果遇到问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
