### ISSUE TITLE
github帐号删除后重新注册，关联登录iconfont成新账号

### ISSUE THREAD

**Issue by suwei0708** [thx/iconfont-plus#1167]
github帐号删除后重新注册，关联登录iconfont的成新账号，怎么找回以前的 ，好多项目图标都是以前的帐号里，要是有多账号关联就好了……

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖三方登录。如果需要找回老账号遇到问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
