### ISSUE TITLE
svg上传失败

### ISSUE THREAD

**Issue by IKKITRANCY** [thx/iconfont-plus#1168]
如题，20个图标都上传失败，谁能帮忙看下是什么问题
[01-口红.zip](https://github.com/thx/iconfont-plus/files/2786264/01-.zip)

**Comment by suwei0708** [comment]
svg图标不支持渐变色，上传页面下拉的图标制作说明第四点有说明

**Comment by IKKITRANCY** [comment]
> svg图标不支持渐变色，上传页面下拉的图标制作说明第四点有说明

谢谢，已经修改上传了

**Comment by yisibl** [comment]
支持渐变图标请关注：https://github.com/thx/iconfont-plus/issues/1938
