### ISSUE TITLE
无法修改项目内的图标名称

### ISSUE THREAD

**Issue by ryan0562** [thx/iconfont-plus#117]
老版本是可以修改的

**Comment by Muqing1221** [comment]
项目内的图标名称，新旧版本似乎都不支持修改~
“我上传的图标”的名称，是可以修改的~

**Comment by purplebamboo** [comment]
亲  老版本也不可以哦，是这样的  项目里的图标可以理解为是   上传图标的 一个克隆，会有自己独立的图形，fontclass，unicode等等，但是名字是没有的啊，名字是跟着它的源来的哈。
