### ISSUE TITLE
请愿增加批量修改模式

### ISSUE THREAD

**Issue by D3III** [thx/iconfont-plus#1171]
1. 在批量修改模式下修改想要修改的图标名称/标签/ Font Class / Symbol后，一次性修改提交（单个修改弹窗刷新耗时间，要修改数量多的图标时太蛋疼了）
2. 第一点如果做不到的话，也可以在上传图标时增加个修改 Font Class / Symbol的功能

**Comment by yisibl** [comment]
统一到这个 issue 中回复：https://github.com/thx/iconfont-plus/issues/1499
