### ISSUE TITLE
搜索优化

### ISSUE THREAD

**Issue by luneice** [thx/iconfont-plus#1173]
Iconfont 确实是一个非常榜的项目，拥有大量高质量 icon ，但是搜索功能有一定的局限性。在使用 icon 时，需要使用一组 icon 但是不能保证每次搜索的 icon 在主题上是一致的。因此不得不从大量 icon 中挨个挨个找下去。而图标库里面有相同主题的图标，却无法搜索。

**Comment by gongeek** [comment]
参考这里 目前可以这种方式找主题一致的
https://github.com/thx/iconfont-plus/issues/797
另外搜索功能也会优化方便找风格一样的，敬请期待
