### ISSUE TITLE
下载文件名字后缀增加颜色Tag以及大小Tag

### ISSUE THREAD

**Issue by Marspu** [thx/iconfont-plus#118]
使用Chrome浏览器下载多个不同颜色不同Size的图标后，会得到很多相同名字的图标文件，当无法预览的时候，只能挨个点开看是哪个颜色哪个SIZE的了。所以建议图标文字后面增加图标颜色以及Size的Tag

**Comment by Muqing1221** [comment]
哈~~好的，算作优化建议~
（目测开发GG的内心是流泪的...）

**Comment by purplebamboo** [comment]
这是个好建议，但是我们得评估下，因为万一有人不喜欢呢。哈 如果要改的话 我明天改好。改动比较小。

**Comment by purplebamboo** [comment]
统一在这里：
https://github.com/thx/iconfont-plus/issues/139
