### ISSUE TITLE
字体font class 在拷贝的时候发现Symbol 前缀出来了，以前没有的。

### ISSUE THREAD

**Issue by SwordSealCity** [thx/iconfont-plus#1189]
比如Symbol 前缀 是iconfont，字体名字是pinyin，然后在选择font class选项时，字体名字变成了iconfontpinyin，中间是少了个 - 字符？
麻烦修改下这个问题。

**Comment by zjfjiayou** [comment]
我也遇到了，麻烦修复一下

**Comment by lsc121547** [comment]
我也遇到了, 麻烦修复一下,  比较急

**Comment by forgxq** [comment]
急，项目明天要上线

**Comment by zjfjiayou** [comment]
好巧啊，我们也要上线

**Comment by zjfjiayou** [comment]
@forgxq

**Comment by bunane** [comment]
我们也遇到了呦

**Comment by Crain927** [comment]
我也遇到了，麻烦修复一下，虽然我明天不上线

**Comment by zjsyxrf** [comment]
是啊，导致我ios8.1.1 微信6.7.4小程序下的图标都没有了

**Comment by yisibl** [comment]
这个问题已经修复了，现在前缀可以自行定义了，不再固定为连字符 `-`，以便更加灵活的配置 Class。

![image](https://user-images.githubusercontent.com/2784308/53216324-2629af00-368f-11e9-8596-bb80c1e6450d.png)

**Comment by zjsyxrf** [comment]
请问你们的可以正常使用了么，怎么我的5s还是不行
