### ISSUE TITLE
旧版点击“AI下载”收到eps文件，用新版却只收到svg没有eps文件

### ISSUE THREAD

**Issue by ycyyqy** [thx/iconfont-plus#119]
旧版点击“AI下载”收到eps文件，可以批量丢入同一个AI画板，编辑很方便。
用新版点击"AI下载”和点击"svg下载“结果一样，只收到svg，用AI软件每打开一个svg就新建一页画板，要放到一起去就得隔页拖动，超级超级不方便。

还有，给你们提个意见怎么就这么难，还要注册个我设计师用不上的GitHub账号，我验证了好多次才顺利通过。
谢谢！

**Comment by Muqing1221** [comment]
抱歉给亲带来的不便，现在因为ai格式对多色图标的渲染有点问题，为了先能保证正常使用，所以暂时均用svg替代；我们的技术同学已经在紧急寻找解决方案了~见谅~

关于Github的问题，恩....抱歉again...同为被虐的设计狗...
微博登录不稳定我们也很无奈，现在还没有做单独的账户体系，所以...

以后的以后...我们尽量表现的更好更稳定更阔爱~~哈哈

**Comment by purplebamboo** [comment]
eps目前的确有点问题，抱歉带来了不好的体验，我们还在研究解决。
最新进度看这里：
https://github.com/thx/iconfont-plus/issues/139
