### ISSUE TITLE
icon名称缺少-

### ISSUE THREAD

**Issue by liub1934** [thx/iconfont-plus#1190]
如图 icon后面都少了横杠，但不影响使用，影响复制粘贴
![image](https://user-images.githubusercontent.com/29849550/53138753-4f303e00-35c2-11e9-8e0a-07c73553241f.png)
![image](https://user-images.githubusercontent.com/29849550/53138805-76870b00-35c2-11e9-8059-95b8ecf1e8e5.png)

**Comment by yisibl** [comment]
这个问题已经修复了，现在前缀可以自行定义了，不再固定为连字符 `-`，以便更加灵活的配置 Class。

![image](https://user-images.githubusercontent.com/2784308/53216324-2629af00-368f-11e9-8596-bb80c1e6450d.png)
