### ISSUE TITLE
cionfont 中间-没了 ,急急急

### ISSUE THREAD

**Issue by haoguoshuai** [thx/iconfont-plus#1191]
cionfont 中间-没了 ,急急急

**Comment by yisibl** [comment]
这个问题已经修复了，现在前缀可以自行定义了，不再固定为连字符 `-`，以便更加灵活的配置 Class。

![image](https://user-images.githubusercontent.com/2784308/53216324-2629af00-368f-11e9-8596-bb80c1e6450d.png)
