### ISSUE TITLE
坐等官方解决少一个'-’的问题

### ISSUE THREAD

**Issue by zjsyxrf** [thx/iconfont-plus#1193]
昨天晚上临近下班发现在我的ios8.1.1手机，微信6.7.4的两个小程序上，一个有图标，一个没有了，但其他手机有，快发布了，官方快解决把

**Comment by moory** [comment]
看样子已经修复了

**Comment by zjsyxrf** [comment]
> 看样子已经修复了

是哦，好快~哈哈哈

**Comment by yisibl** [comment]
这个问题已经修复了，现在前缀可以自行定义了，不再固定为连字符 `-`，以便更加灵活的配置 Class。

![image](https://user-images.githubusercontent.com/2784308/53216324-2629af00-368f-11e9-8596-bb80c1e6450d.png)

**Comment by zjsyxrf** [comment]
可是我这边使用新的iconfont.css还是不能正常显示，是红框框

**Comment by yisibl** [comment]
@zjsyxrf 项目 ID 提供一下，我看看。

**Comment by zjsyxrf** [comment]
> @zjsyxrf 项目 ID 提供一下，我看看。

1015879

**Comment by yisibl** [comment]
@zjsyxrf 我这边看该项目是正常的，请在使用的项目中重新更新一下 iconfont.css。

**Comment by zjsyxrf** [comment]
> @zjsyxrf 我这边看该项目是正常的，请在使用的项目中重新更新一下 iconfont.css。

我已经重新更新了

我使用的是微信小程序，别的手机都可以的，只有ios8.1.1，微信版本6.7.4手机不可以

**Comment by yisibl** [comment]
那是另外的问题了，iOS 8.1.1 不支持 woff2 格式导致的，该版本太旧了，请升级到 iOS 10 以上。
https://caniuse.com/#search=woff2
![image](https://user-images.githubusercontent.com/2784308/53219865-b15d7180-369c-11e9-9074-54898d576239.png)

**Comment by zjsyxrf** [comment]
> @zjsyxrf 我这边看该项目是正常的，请在使用的项目中重新更新一下 iconfont.css。



> https://caniuse.com/#search=woff2

哦哦，我看到区别了，谢谢
后面如果更新图标后，都只是用woff2，woff了？

**Comment by zjsyxrf** [comment]
> 那是另外的问题了，iOS 8.1.1 不支持 woff2 格式导致的，该版本太旧了，请升级到 iOS 10 以上。
> https://caniuse.com/#search=woff2
> ![image](https://user-images.githubusercontent.com/2784308/53219865-b15d7180-369c-11e9-9074-54898d576239.png)

哦哦，我看到区别了

所以后面如果更新图标的话，都是用的woff2吗？不用woff了?

**Comment by yisibl** [comment]
是的，优先使用 woff2，体积更小，加载相对更快。

**Comment by liwenda122** [comment]
“这个问题已经修复了，现在前缀可以自行定义了，不再固定为连字符 -，以便更加灵活的配置 Class”
修复你妹，典型的解决一个BUG引入更大的BUG，前缀是可以自定义了，但是之前没有前缀的会被自动加上一个icon-, 而且前缀不能设置为空，这尼玛是何等卧槽
