### ISSUE TITLE
您好，我对您这边的登陆系统有一个小小的意见（笑

### ISSUE THREAD

**Issue by 1090017765** [thx/iconfont-plus#1194]
我不用微博，然后除了某同性交友论坛以外的那个阿里登陆没有办法登陆，我不想暴露自己的性取向，所以我希望通过阿里域账号登陆（我参加过阿里巴巴2018年11月11号的一个2135亿人民币的项目）

**Comment by a77uu** [comment]
So 你的性取向是啥 好希望是1？

**Comment by liub1934** [comment]
github登陆

**Comment by 1090017765** [comment]
> 所以你的性取向是啥好希望是1？

小可爱你是0吗，我超甜的

**Comment by 1090017765** [comment]
> github上登陆

这不就暴露了嘛

**Comment by liub1934** [comment]
> > github上登陆
> 
> 这不就暴露了嘛
github和性取向有啥关系？？？

**Comment by 1090017765** [comment]
> > > GitHub的上登陆
> > 
> > 
> > 这不就暴露了嘛
> > github上和性取向有啥关系???

github是全世界最大的码农同性交友网站，超甜的 ( ˘ ³˘)♥

**Comment by a77uu** [comment]
> > 所以你的性取向是啥好希望是1？
> 
> 小可爱你是0吗，我超甜的

我我我...耶？你甜么？
