### ISSUE TITLE
希望开设“失效/问题icon”一键反馈功能

### ISSUE THREAD

**Issue by ycyyqy** [thx/iconfont-plus#120]
我有两三次下载到过图形错位变形没法用的文件，希望有直接的反馈通道，好让发布者完善一下文件。

**Comment by Muqing1221** [comment]
是呢~这个报错功能之前考虑过的，包括对于不合格图标的举报或者抄袭icon的举报等等~
不过由于资源问题，这个功能还木有上线，之后我们会在合适的时候，优化更新的哈

**Comment by purplebamboo** [comment]
这里统一讨论吧：
https://github.com/thx/iconfont-plus/issues/139
