### ISSUE TITLE
所有最新下载的字体图标在移动端显示都会往上跑，PC没有任何问题

### ISSUE THREAD

**Issue by ly272864** [thx/iconfont-plus#121]
最近因为项目有修改，又多了几个图标，让UI改成SVG导入到原本的项目上面以后，将相关文件下载到了本地，覆盖了之前的文件，PC上模拟的手机看没问题，之后自己用手机看了下发现所有字体图标都往上跑了，之后用在图标上加了一个背景，发现都是长度大于宽度的，都顶到正确位置的上边去了，换成之前图标字体文件的就不会有问题

**Comment by purplebamboo** [comment]
亲  项目id给我下？  然后新增的图标跟我说下，我去排查下哈。

**Comment by ly272864** [comment]
项目id = 99015， 新增图标“扫一扫”、“确认”

**Comment by purplebamboo** [comment]
亲 排查了下 是你项目里面的  e622 这个图标  叫做订单的。这个icon有问题会导致整个字体撑开。


![wangwang20161115133601](https://cloud.githubusercontent.com/assets/1409611/20294385/ca681096-ab38-11e6-93c1-c9834a53e8e1.png)

右下角多了个点。。。导致全部撑开。

你删除这个图标重新生成字体就行了哈。

**Comment by ly272864** [comment]
公司UI没时间整这些，AI我又只是个半吊子，由于我的不仔细导致的这个问题，让你花费时间去排查问题源，由衷的抱歉加感激

**Comment by purplebamboo** [comment]
没事  解决就好。。
