### ISSUE TITLE
建议显示图标的系列

### ISSUE THREAD

**Issue by 002269** [thx/iconfont-plus#1214]
搜索到某个图标后，希望可以点击图标看到该图标所处的系列，这样在该系列中跟该图标相关的图标可以一并选取。例如，上下左右，开关闭合等等，这些图标往往是处于一个系列中的，最好能同时选取。或者能显示该图标作者的其它所有图标，可以在统一风格下一并选取图标。

**Comment by yisibl** [comment]
已经增加查看所在图标库的功能了
