### ISSUE TITLE
IE11 HTTPS

### ISSUE THREAD

**Issue by IM-DIVA** [thx/iconfont-plus#1215]
下载至本地后采用font-class 在所有ie的https上，图标文件获取到了，但是全部不显示，改成http就好了
![image](https://user-images.githubusercontent.com/19405605/54022885-7b58db00-41ce-11e9-91d3-940b392bdab8.png)

**Comment by yisibl** [comment]
如果是 https 地址，本地需要启动一个 https 的服务才行
