### ISSUE TITLE
带带爱空风特

### ISSUE THREAD

**Issue by wannn910** [thx/iconfont-plus#1216]
我佛了，登陆后加到购物车里的图标全没了，从项目转到购物车再转到项目的图标也没了，这加到购物车的图标就不能一直保存🐎？？？老子一关浏览器再登全没了，哪个🐉鸣写的玩意，体验极差。垃圾图标太多了，给👴把所有不是一个图标库的散图标都删了，图标不是一个图标库的你有个🔨用？搜索图标库的条件最好可以是里面图标的名字。

**Comment by yisibl** [comment]
很抱歉，购物车目前是存储在浏览器缓存里的，后续我们会考虑优化。
