### ISSUE TITLE
新版系统里 不能下载到本地,也不能生成在线链接

### ISSUE THREAD

**Issue by kufufu9** [thx/iconfont-plus#122]
点下载到本地  会调到淘宝的error页面 http://err.taobao.com/error2.html
项目ID 136625

**Comment by purplebamboo** [comment]
你好 亲  我排查了下   是因为你项目里有个图标的unicode有问题，太大了。

是这个图标  tt_author_2  表现是个作者的样子。我帮你修改了。

你现在下载应该正常了。

**Comment by purplebamboo** [comment]
你好 亲  我排查了下   是因为你项目里有个图标的unicode有问题，太大了。

是这个图标  tt_author_2  表现是个作者的样子。我帮你修改了。

你现在下载应该正常了。

**Comment by kufufu9** [comment]
非常感谢.
