### ISSUE TITLE
找回账号

### ISSUE THREAD

**Issue by JustinYi922** [thx/iconfont-plus#1221]
您好。由于公司小，维护者马虎，现在使用的iconfont的账号已经不记得了，只有代码里使用的url。能帮忙找回账号吗？

**Comment by yisibl** [comment]
代码里使用的url 发一下

**Comment by yisibl** [comment]
请加一下钉钉答疑群

![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
