### ISSUE TITLE
symbol引用下 修改color无效

### ISSUE THREAD

**Issue by LuxPax** [thx/iconfont-plus#123]
把项目下载到本地后使用symbol引用，修改 .icon 里的 color 和 fill 属性 svg 颜色不改变

**Comment by purplebamboo** [comment]
是这样的，symbol本质上是svg，如果是单色的图标，那么是可以通过 color来改变颜色的。

而多色的本身已经有颜色了，也就是每个path上面都有颜色了，所以设置了color也是会被覆盖的。

具体可以看这里  https://github.com/thx/iconfont-plus/issues/13

**Comment by LuxPax** [comment]
@purplebamboo 明白了  非常感谢
