### ISSUE TITLE
chrome浏览器弹出的下载边框会挡住图片选择的按钮

### ISSUE THREAD

**Issue by scarqin** [thx/iconfont-plus#127]
如图
![image](https://cloud.githubusercontent.com/assets/15225835/19999677/ba7973c4-a2ae-11e6-9615-49e7f8280c13.png)

**Comment by Muqing1221** [comment]
亲的屏幕尺寸是？

**Comment by purplebamboo** [comment]
会做优化，这里统一讨论
https://github.com/thx/iconfont-plus/issues/139

**Comment by scarqin** [comment]
15.6英寸1366x768
