### ISSUE TITLE
希望可以直接复制svg的代码

### ISSUE THREAD

**Issue by 95junminhuang** [thx/iconfont-plus#1278]

**Comment by nickolboy** [comment]
https://axhub.im/icons/

**Comment by 95junminhuang** [comment]
> https://axhub.im/icons/

感谢，最近已经安装了他

**Comment by 95junminhuang** [comment]
感谢，最近已经安装了他

> https://axhub.im/icons/

**Comment by yisibl** [comment]
iconfont 平台现在默认已经支持直接复制 svg 代码了

https://weibo.com/1397442732/HzNN7sWUs
