### ISSUE TITLE
 Can't resolve 'iconfont.eot' 下载导出资源引用路径问题 【bug】

### ISSUE THREAD

**Issue by mycoin** [thx/iconfont-plus#1286]
下载导出的资源路径类似：
![image](https://user-images.githubusercontent.com/1845440/57756527-04881300-7726-11e9-82a8-23709964c6ee.png)

建议统一修改为 "./iconfont.eot" 采用相对路径，否则直接复制到文件夹不加修改的化导致错误：
![image](https://user-images.githubusercontent.com/1845440/57756615-3ac59280-7726-11e9-8bf8-5b9a00761a62.png)

**Comment by cricy** [comment]
这个是为了解决ie 7 8的问题。

**Comment by mycoin** [comment]
"./iconfont.eot" 在IE7，8也是没有问题的！
