### ISSUE TITLE
symbol引用中，通过一些技巧，如何像字体那样使用font-size,color来调整样式

### ISSUE THREAD

**Issue by menghuan758** [thx/iconfont-plus#13]
您好，请问怎样通过font-size和color调整彩图的颜色，经过试验大小只能通过width和height调，颜色暂时没找到方法。

**Comment by gongeek** [comment]
1.font-size 可用

![font-szie](http://img.alicdn.com/tps/TB1akx7NVXXXXbvapXXXXXXXXXX-1583-826.png)

2.如果要改多色图标的颜色，找到你down下来的iconfont.js 文件，找到对应的symbol 直接改svg对应path的颜色,（另外也可以dom操作找到节点的fill属性进行修改颜色）

![color](http://img.alicdn.com/tps/TB1zFWlNVXXXXbhXVXXXXXXXXXX-1370-701.png)

![code](http://img.alicdn.com/tps/TB1emOuNVXXXXceXFXXXXXXXXXX-1637-378.png)

**Comment by purplebamboo** [comment]
关于这个  可以看这里https://zhuanlan.zhihu.com/p/20753791?refer=FrontendMagazine

通过平台里面的样式，可以直接用   css的  color和  font-size来修改的

**Comment by menghuan758** [comment]
@gongeek @purplebamboo  多谢了。
`font-size`改不了是我设置的问题，`width:1em;height:1em;`类似的方式实现`font-size`控制。
`color`上面使用`currentColor`获取继承颜色的方法还是不行。
图标我使用`<svg class="icon" aria-hidden="true"><use xlink:href="#icon-xxx"></use></svg>`这种方式引用，无法使用css设置颜色吗。
现在使用另外一种方案，就是在库里修改颜色生成副本引入，但感觉做法不太好。

**Comment by menghuan758** [comment]
@purplebamboo 多谢 在您的链接中找到了`color`不生效的原因。
是因为iconfont源码中，单色图标没有添加`fill`属性。

**Comment by purplebamboo** [comment]
再补充一下：  多色图标我们是不建议使用  color来改颜色的，因为既然是多色，本身就是有颜色语义在里面的。设计师就是期望这个多色图标长这样。如果非要修改，可以使用平台的编辑功能。

**Comment by DX-WEB** [comment]
非常感谢说明，只是希望正式版可以添加一个帮助链接方便查看。
