### ISSUE TITLE
新版，我的项目，代码更新不了，提示error错误！

### ISSUE THREAD

**Issue by huangyu-snail** [thx/iconfont-plus#130]
新版，我的项目，代码更新不了，提示error错误！

**Comment by purplebamboo** [comment]
亲  项目id发给我下。我去排查下。

**Comment by huangyu-snail** [comment]
<div class="nav-item current" mx-click="changeProject(24656)" p-id="2263" id="mx_n_1478328650947"><span p-id="2264">QH_icon</span></div>
不知道项目id在哪，上面的应该有id吧，还有项目里面的“下载到本地”也报错了；

**Comment by purplebamboo** [comment]
是这样的亲，你项目里有一个icon。名字交  tishi的。你的unicode设置的是0。所以生成字体会出错，其实在老平台也是一样的不可用的，只是老平台没有提示错误。

我帮你改了下，把这个icon改成了 e500了，现在已经好了哈。


以后遇到这种问题，可以优先查看是否有特殊的unicode哈。另外用二分法，一次加一半图标到另一个项目，生成字体看会不会报错，也是可以慢慢排查出有问题的图标的。
