### ISSUE TITLE
阿里巴巴-普惠体有 '因 '部首的时候显示有问题.

### ISSUE THREAD

**Issue by rolitter** [thx/iconfont-plus#1301]
阿里巴巴-普惠体-Medium
阿里巴巴-普惠体-Bold
例如: 恩、烟、洇、栶、铟、氤 、因
![image](https://user-images.githubusercontent.com/27326998/59016161-3bf46600-8873-11e9-92c1-ceef127d8eb3.png)

**Comment by yisibl** [comment]
已经无法复现
