### ISSUE TITLE
英文状态下，www.iconfont.cn网站导航栏样式错位

### ISSUE THREAD

**Issue by Groverjun** [thx/iconfont-plus#1302]
![image](https://user-images.githubusercontent.com/29271134/59016412-c046e900-8873-11e9-9cf5-ffd9a869fe1b.png)

**Comment by Urielye** [comment]
在中文格式下，也错位了😢

**Comment by XProfessorJ** [comment]
开发者模式找到class="clearfix"  元素加上display:none. 就好了。

**Comment by XProfessorJ** [comment]
鼠标放到楼主圈出来的地方就能找到。

**Comment by Groverjun** [comment]
![image](https://user-images.githubusercontent.com/29271134/59024236-0efc7f00-8884-11e9-82da-e4c3fedf8f81.png)
把logo的margin-right设为0就可以了，建议开发者尽快修复

**Comment by XProfessorJ** [comment]
高手




在2019年06月06日 17:56，Groverjun 写道：


把logo的margin-right设为0就可以了，建议开发者尽快修复

**Comment by fredstonet** [comment]
同样的问题ing

**Comment by yisibl** [comment]
点击中英文切换图标会复现，我们尽快修复，感谢反馈。
