### ISSUE TITLE
希望能支持更多正常登陆方式,保护用户隐私!

### ISSUE THREAD

**Issue by kongtir** [thx/iconfont-plus#1304]
强烈建议下架微博登陆,目前微博登陆强行要求手机扫码,属于霸权行为,对贵司形象不利.

**Comment by yisibl** [comment]
微博登陆默认应该是输入用户名密码登陆的呀？
![image](https://user-images.githubusercontent.com/2784308/59402570-845ed700-8dd1-11e9-903a-0ccc44785c24.png)

**Comment by kongtir** [comment]
> 微博登陆默认应该是输入用户名密码登陆的呀？
> ![图片](https://user-images.githubusercontent.com/2784308/59402570-845ed700-8dd1-11e9-903a-0ccc44785c24.png)

是这样的.在我输入完密码后,他就弹出要求手机扫码了,幸亏有github账户.

有可能是因为前段时间手机下载使用了一会儿微博客户端,最初也不是必须在输入密码后强行手机扫码的.

**Comment by zuibunan** [comment]
@yisibl Github和微博不能关联同一个账号吗？

**Comment by yisibl** [comment]
目前不能关联同一个账号。

Duplicate of #1718

**Comment by yisibl** [comment]
我们正在考虑实现新的账户系统
