### ISSUE TITLE
我用的微博登陆的，我微博修改了手机号登陆，里面的项目全没啦！！！

### ISSUE THREAD

**Issue by 136170746** [thx/iconfont-plus#131]
救救我吧，旧版的时候我是用微博登陆的，微博绑定是以前的手机号，这两天我更换了手机号，但是登陆到iconfont新版，以前的项目不见了。帮我弄回来吧

**Comment by purplebamboo** [comment]
亲  以前的微博账号，还有后面的手机号都发给我看下。我帮你处理下。

**Comment by 136170746** [comment]
以前的微博账号好像和现在的一样吧，阿扎东 ，现在的手机号是 18605768610 以前的是 15112570772

**Comment by 136170746** [comment]
不过我的那个iconfont里面的昵称好像一直都是 汉易网

**Comment by purplebamboo** [comment]
用手机找不到用户。用汉易网只能找到你新的用户名，也就是一个项目图标都没的这个。

亲，你还记得以前的用户名吗？或者说记不记得你以前那个账号里面的 项目的名称。这样我才能找到。

**Comment by 136170746** [comment]
以前的用户名，阿扎东 试试看，项目名里面有：gaming、gamingWeb、 agent 这个你试试看

**Comment by 136170746** [comment]
src: url('//at.alicdn.com/t/font_1476524565_318245.eot'); /* IE9*/
  src: url('//at.alicdn.com/t/font_1476524565_318245.eot?#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('//at.alicdn.com/t/font_1476524565_318245.woff') format('woff'), /* chrome、firefox */
  url('//at.alicdn.com/t/font_1476524565_318245.ttf') format('truetype'), /* chrome、firefox、opera、Safari, Android, iOS 4.2+*/
  url('//at.alicdn.com/t/font_1476524565_318245.svg#iconfont') format('svg'); /* iOS 4.1- */

**Comment by purplebamboo** [comment]
是不是  叫    `扎西爷爷`

通过 gaming 搜出来的。

**Comment by purplebamboo** [comment]
应该是了，你下面的那个项目cdn我反查了下，就是 gaming这个项目的。

那我把你新的 `汉易网`  这个登陆，转到`扎西爷爷`这个下面吗？

或者  我直接去把  `扎西爷爷`下面的项目  转让给你 是不是更合适一点。

**Comment by 136170746** [comment]
你转让过来吧，扎西爷爷 这个我也登陆不上了呀

**Comment by purplebamboo** [comment]
好了 哈  ，全都转让过去了。你可以直接用汉易网这个账号
