### ISSUE TITLE
请问设计软件 Figma 上传的 SVG 为什么都是错误的图标啊？

### ISSUE THREAD

**Issue by lijxse** [thx/iconfont-plus#1315]
我的图都是用 Figma 设计的，但是上传以后图标显示不正确，如图：
![image](https://user-images.githubusercontent.com/20184046/59672368-ebc1c000-91f1-11e9-99b0-8e8602d6f0e6.png)
![image](https://user-images.githubusercontent.com/20184046/59672377-f0867400-91f1-11e9-930d-57605d8be6b5.png)

我确认我的图标都是转曲的。
我不确定是 IconFont 的问题还是 figma 的问题，所以来问问。
开发们对 iconfont 的字体文件需求很响亮。

----
PS：
Figma 是直追 Sketch 的一款设计软件，硅谷很多公司都在用了，听说Airbnb全队转到 Figma 了。

**Comment by yisibl** [comment]
请提供一下 Figma 源文件或者分享一下链接。

**Comment by lijxse** [comment]
感谢回复，东西在这⤵️


[SVG_ICON.zip](https://github.com/thx/iconfont-plus/files/3332741/SVG_ICON.zip)

Figma Link:
https://www.figma.com/file/ZylimfzBG2kYDVao5B1CyG6k/C%E3%80%82ICON-and-LOGO?node-id=314%3A0

**Comment by yisibl** [comment]
Figma 中我没有找到类似 Sketch 中修改填充模式的方式，iconfont 中的图标填充模式必须是「非零」才可以。

以你的图标为例，在 Sketch 中我们可以通过以下方法修改：

1.选中最外层图层，点击齿轮图标，填充模式由默认的「奇偶」改为「非零」。
![image](https://user-images.githubusercontent.com/2784308/60408256-b903c880-9bf0-11e9-8c41-5dc0724b5cff.png)
此时图标会变成实心的，也就是上传到 iconfont 时的效果：
![image](https://user-images.githubusercontent.com/2784308/60408310-f7998300-9bf0-11e9-8829-f935c64a4e4d.png)
2. 选中所有形状，使用布尔运算工具中的「差集」
![image](https://user-images.githubusercontent.com/2784308/60408345-1c8df600-9bf1-11e9-879a-432914769495.png)  
![image](https://user-images.githubusercontent.com/2784308/60408474-a5a52d00-9bf1-11e9-9ec7-0e0d6fb130a3.png)
3. 使用「路径合并」命令，使当前图标变成一个「非零」填充的路径，这样上传到 iconfont 就没有问题了。

最终导出的 SVG 是这样的：
```svg
<svg width="214px" height="173px" viewBox="0 0 214 173" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g fill="#4A6CC5" fill-rule="nonzero">
            <path d="M45.7053008,10.1637608 C49.6512927,3.84101087 56.5713542,0 64.0165691,0 L192.406523,0 C204.331521,0 214,9.68184769 214,21.625 L214,151.375 C214,163.318488 204.331521,173 192.406523,173 L64.0165691,173 C56.5713542,173 49.6512927,169.1594 45.7053008,162.83625 L1.64112313,92.230625 C-0.547041042,88.7244556 -0.547041042,84.2755444 1.64112313,80.769375 L45.7053008,10.1637608 Z M64.0165691,16.21875 C62.1552114,16.21875 60.42525,17.1790081 59.438752,18.7596875 L17.1627193,86.5 L59.438752,154.240313 C60.42525,155.8211 62.1552114,156.78125 64.0165691,156.78125 L192.406523,156.78125 C195.387503,156.78125 197.804892,154.360331 197.804892,151.375 L197.804892,21.625 C197.804892,18.6392362 195.387503,16.21875 192.406523,16.21875 L64.0165691,16.21875 Z M82.5311399,63.6194525 C80.4229688,61.5082038 80.4229688,58.0850744 82.5311399,55.9738256 L86.3483268,52.1510662 C88.4566059,50.0398175 91.8746373,50.0398175 93.9828085,52.1510662 L116.830434,75.0316137 L139.677412,52.1510662 C141.784936,50.0398175 145.203183,50.0398175 147.311786,52.1510662 L151.128433,55.9738256 C153.237036,58.0850744 153.237036,61.5082038 151.128433,63.6194525 L128.281455,86.5 L151.128433,109.380331 C153.237036,111.492013 153.237036,114.91525 151.128433,117.02585 L147.311786,120.84915 C145.203183,122.95975 141.784936,122.95975 139.677412,120.84915 L116.830434,97.9683863 L93.9828085,120.84915 C91.8746373,122.95975 88.4566059,122.95975 86.3483268,120.84915 L82.5311399,117.02585 C80.4229688,114.91525 80.4229688,111.492013 82.5311399,109.380331 L105.378334,86.5 L82.5311399,63.6194525 Z"></path>
        </g>
    </g>
</svg>
```

**Comment by lijxse** [comment]
我从 Figma 方便找找原因，现在的问题是 Figma 的 flatten 功能在代码中是失效的。
