### ISSUE TITLE
上传100多个图标，申请图标库被拒，原因是风格不统一？？？

### ISSUE THREAD

**Issue by musongtao** [thx/iconfont-plus#1316]
抱着学习的心态过来请教，为什么风格不统一呢？

<img width="945" alt="屏幕快照 2019-06-14 上午7 58 43" src="https://user-images.githubusercontent.com/34263325/59734391-d7c69e80-9283-11e9-8903-874c3086ce09.png">

**Comment by musongtao** [comment]
虚心请教...

![流程列表ICON ](https://user-images.githubusercontent.com/34263325/59830728-cf995c80-9372-11e9-84d0-c6aef8533949.png)

**Comment by yisibl** [comment]
你好用户名称提供一下。

**Comment by musongtao** [comment]
> 你好用户名称提供一下。

musongtao

**Comment by yisibl** [comment]
后台没有看到申请的图标库，新建一个图标库重新上传一下，下周一审核，

**Comment by musongtao** [comment]
好的

**Comment by yisibl** [comment]
我们会尽快审核，有时候审核同学忙不过来，请谅解哈。
