### ISSUE TITLE
我项目里面的收集的图标都不见了，自己上传的也不见了，这是为什么？？？求回复，在线等急急急

### ISSUE THREAD

**Issue by kaneki9** [thx/iconfont-plus#1318]

**Comment by yisibl** [comment]
用户 ID 发来看一下

**Comment by lizehao1888** [comment]
我的也是一样的 今天重新登录就啥都没了

**Comment by yisibl** [comment]
> 我的也是一样的 今天重新登录就啥都没了

请提供 iconfont 用户名

**Comment by yisibl** [comment]
如果需要找回老账号遇到问题，请加一下钉钉答疑群

![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
