### ISSUE TITLE
希望在将图标加入项目前,检测当前项目是否有重名的标class

### ISSUE THREAD

**Issue by lifetin** [thx/iconfont-plus#132]
希望在将图标加入项目前,检测当前项目是否有重名的class
比喻我在昨天加入了一个icon-aaa,icon-bbb
今天又搜了几个图标,遇到有一个是icon-aaa的,结果导至一个项目中有两个icon-aaa,这样在使用时就会有问题了.可以考虑在加入项前进行自动重名命后再加入进项目.可以直接将后加入的命令为icon-aaa1,icon-aaa2这样的依次类推.
希望更人性化一点.谢谢.

**Comment by lifetin** [comment]
![66](https://cloud.githubusercontent.com/assets/10474968/20027427/71d2cdea-a34f-11e6-99b2-cfc4110b2b3f.png)

这样就出了问题.都是手动一个个修改的.因为一个项目不止一个人使用.也不可能只有一个项目使用.
如果可以,另外可以考虑增加项目复制的功能.

**Comment by purplebamboo** [comment]
* 重复的问题，的确应该处理，其实在下载字体，或者生成cdn的时候我们会做这种处理的（亲可以试下，下载到本地，font-class会自动有123区分的），只是加入到项目的时候不会。当然感谢建议，我已经处理了，双十一要封网，所以等双十一后我会把这个功能上线的。
* 这个问题，项目复制其实不是高频需求，后期我们会提供一个项目里批量操作一键全选的功能，这样你直接项目图标全部加入购物车，生成新项目就可以了哈。＝ ＝我们主要不想功能点太多。用户反而会晕的。

**Comment by lifetin** [comment]
另外问一下,项目重新生成后,之前的会不会失效呢? 
如果不会失效,那会不会同步新加的图标了?

**Comment by purplebamboo** [comment]
cdn里面的地址永远都是你`生成时`的图标集合。不会被覆盖的。

也就是说项目重新生成后,之前的不会失效的，新旧会同时存在的。

如果你新加了图标，那么平台会提示你更新cdn的。cdn里面的内容是你点击生成时，当前项目里已有的内容哈，你加了图标原来的是不影响的，你如果要用最新的，那么就需要更新cdn哦。

**Comment by lifetin** [comment]
能不能共用一份图标呢?在新加后,可以一键刷新以前旧的CDN内容?这样旧的就自动加入了新图标.
这样避免每次生成的都是一份独立的.

**Comment by purplebamboo** [comment]
我理解你是说  cdn地址不要变，每次更新都用最新的是吧，这个会有缓存问题的，详情见这里的讨论：

https://github.com/thx/iconfont-plus/issues/94

**Comment by lifetin** [comment]
基本上明白了,顺便问一下,
cdn的缓存,你们不可以控制刷新吗?或是给缓存加个过期时间

**Comment by purplebamboo** [comment]
可以的，但是还是达不到目的呀，我们需要的是立即生效。

* 虽然理论上我们有一些方法更新cdn的缓存。但是很多手机浏览器有强缓存，更新不了。
* 如果我们设置缓存时间，用户在项目里改了图标，很容易影响到线上，＝ ＝为了线上的稳定，这么做是很不合适的。

**Comment by purplebamboo** [comment]
这个 issue我先关闭了哈。有问题  可以继续提issue。
