### ISSUE TITLE
阿里字体收费吗？

### ISSUE THREAD

**Issue by fanzengfeng** [thx/iconfont-plus#1320]
阿里字段是否支持商业使用？

**Comment by yisibl** [comment]
哪一款字体？

**Comment by fanzengfeng** [comment]
不好意思，没讲清楚，分别是：阿里巴巴-普惠体-Light，阿里巴巴-普惠体-Heavy，阿里巴巴-普惠体-Medium，阿里巴巴-普惠体-Bold，阿里巴巴-普惠体-Regular

**Comment by yisibl** [comment]
请参考底部的版权说明：
https://alibabafont.taobao.com/wow/alibabafont/act/alifont?spm=a213iq.12741207.2438956849.1.11c2461d2P6MzG&wh_biz=tm&acm=lb-zebra-476210-6318664.1003.4.5749054&scm=1003.4.lb-zebra-476210-6318664.OTHER_15543390589341_5749054
