### ISSUE TITLE
上传到图标库中的图标，审核失败，风格不统一

### ISSUE THREAD

**Issue by zhangxiumei3686** [thx/iconfont-plus#1323]
请问一下，上传的图标为什么审核不通过，说风格不统一
![image](https://user-images.githubusercontent.com/18474260/59998455-054f8580-9692-11e9-9e84-eb5bdc9b66b1.png)

**Comment by yisibl** [comment]
请去掉实心填充的图标或者重新绘制。

**Comment by zhangxiumei3686** [comment]
但是我看别人的图标库实心的和空心的也都存在，这个是有什么方式可以让实心的和空心的一起上传吗
下面是我在其他图标库找到的
![image](https://user-images.githubusercontent.com/18474260/60063830-d0464000-9730-11e9-9d23-729c568e6aed.png)

**Comment by yisibl** [comment]
图标库我们需要原创图标才行。

**Comment by zhangxiumei3686** [comment]
嗯，这些图标都是我们公司的设计做的，都是原创的
