### ISSUE TITLE
下载出错 502 Bad Gateway

### ISSUE THREAD

**Issue by shifawe** [thx/iconfont-plus#133]
URL:	http://wenda.taobao.com/?spm=1.7156474.1997481305.1.icnWiz
Server:	aserver011131225240.et2
Date:	2016/11/05 12:28:21

**Comment by purplebamboo** [comment]
奇怪，这个是哪里的url，我们平台应该不会有这种情况才对。

能再说具体的场景吗？比如是下载项目还是在购物车下载的。

同时提供下项目id，或者购物车中的图标。
