### ISSUE TITLE
下载到本地，提示 ：亲，访问受限了

### ISSUE THREAD

**Issue by 136170746** [thx/iconfont-plus#134]
http://www.iconfont.cn/api/project/download.zip?pid=175185&ctoken=y5UVMgfHZQe4KwgerPB5icon-font
跳转到 http://err.taobao.com/error2.html 这里了
操作系统：macOs
浏览器：Chrome 版本 48.0.2564.97 (64-bit)

**Comment by purplebamboo** [comment]
是因为这些多色图标，细节太多。我们有个库叫ttfautohint,用来优化曲线的，这种情况下耗时太长。

导致达到请求的超时上线了。

我修改了超时时间，现在可以下载了。
