### ISSUE TITLE
新功能建议-项目图标添加排序功能

### ISSUE THREAD

**Issue by zhangxinjie2017** [thx/iconfont-plus#1341]
项目中把同类的图标放在一起；项目中新增图标无法放到想放到的位置

**Comment by zhangxinjie2017** [comment]
![image](https://user-images.githubusercontent.com/28778058/61262585-4a119c80-a7b8-11e9-9196-f0055f826e99.png)

**Comment by zhangxinjie2017** [comment]
- `[](url)`

**Comment by zhangxinjie2017** [comment]
是

**Comment by yisibl** [comment]
请统一关注 https://github.com/thx/iconfont-plus/issues/1496
