### ISSUE TITLE
建议增加下载的svg编辑功能

### ISSUE THREAD

**Issue by yangyxd** [thx/iconfont-plus#1356]
https://icomoon.io/app/#/select
这个网站可以把iconfont下载的字体中的svg拖上去重新增删改，重新生成字体图标。
建议iconfont官方也能加上类似功能。因为有时候并没有将图标加项目中直接下载使用了，后来想加减图标，发现无法实现。

**Comment by yisibl** [comment]
SVG 更复杂的编辑功能建议使用本地矢量设计软件，例如 Sketch。
