### ISSUE TITLE
项目图标分类功能

### ISSUE THREAD

**Issue by vikki-v11** [thx/iconfont-plus#1357]
建议增加一个项目里再分组的功能。
当项目为多人协作，且svg数量变多之后，项目组成员容易忽略原来已经有类似的svg，且会造成混乱。建议增加一个分组的功能，那么就可以按照【基础icon】【设备icon】这样来进行划分，以更好的进行项目写作。
谢谢聆听建议！

**Comment by DWYW** [comment]
+1

**Comment by yisibl** [comment]
Duplicate of https://github.com/thx/iconfont-plus/issues/1496
