### ISSUE TITLE
不能切换账号

### ISSUE THREAD

**Issue by wuxiaoli111** [thx/iconfont-plus#1359]
登录了账号后退出再登录直接登录原账号了，不能登录其他账号

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖三方登录。如果账号遇到问题，请加一下钉钉答疑群

![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
