### ISSUE TITLE
审核需要多久

### ISSUE THREAD

**Issue by BruceJson** [thx/iconfont-plus#136]
多彩图标库审核需要多久，如果审核不通过有那些原因

**Comment by purplebamboo** [comment]
这个需要我们的设计师回答你哈。

审核主要是  muqing在做。原则上，多彩图标库不要出现单色的，另外不要有违反国家法律法规的图标哈。

更具体的等我们设计师回答你哈。

**Comment by Muqing1221** [comment]
来了来了

审核一般1-2个工作日(不过如果我忙暴毙，望谅解...)

审核不通过的原因可能是：
1.单色图标与多色图标混合在一个图标库内
2.没有符合绘制规则，（参照帮助中心，\[绘制规则](http://www.iconfont.cn/plus/help/detail?helptype=draw))
3.图标质量实在辣眼睛
4.抄袭Iconfont线上已有多色图标
5.更多详情，多多关注帮助中心的最新公告，一些小News小Tips，我们会不定期更新在那里~ \[相关文章]（http://www.iconfont.cn/plus/help/detail?helptype=article）
