### ISSUE TITLE
项目里搜图标的体验太差了，项目中图标只有一个名称还不能修改，应该允许用户给图标设置多个关键字

### ISSUE THREAD

**Issue by pzjzeason** [thx/iconfont-plus#1362]
如题。现在项目里搜图标的体验太差了。
项目中图标只有一个名称，应该允许用户给图标设置多个关键字

**Comment by pzjzeason** [comment]
@yisibl

**Comment by yisibl** [comment]
是指给图标增加备注吗？

**Comment by pzjzeason** [comment]
> 是指给图标增加备注吗？

差不多，就是可以让用户更快的搜到图标

**Comment by dantinajia** [comment]
图标的原中文名称不能修改，只能修改图标的英文 name，希望中文名称也能修改编辑

**Comment by wang12124468** [comment]
请问一下，能添加给图标加备注的功能么？很多时候，名字并不能很好的表述图标具体作用。另外，如果提供，什么时候能够提供呢？

**Comment by yisibl** [comment]
感谢建议，修改项目图标名称功能请关注：https://github.com/thx/iconfont-plus/issues/2054
