### ISSUE TITLE
能开发一个 Figma Plugin 吗

### ISSUE THREAD

**Issue by PHenryy** [thx/iconfont-plus#1363]
昨天Figma Plugin上线了，能做个Figma的插件吗，实现图标搜索插入功能，或者提供API让我们这些开发者自己实现也行

**Comment by ziyunfei** [comment]
初始版本 https://www.figma.com/c/plugin/739031549389439337/IconfontDone

**Comment by yisibl** [comment]
等待审核通过后即可安装。

**Comment by PHenryy** [comment]
链接失效了，是没通过审核吗？

**Comment by ziyunfei** [comment]
官方拒绝了。1、说 iconfont 网速太慢，国外访问当然慢了，这个没办法；2、说交互不好，放一个搜索框不知道该干啥；3、说 icon 的版权没说明。

放弃了。
