### ISSUE TITLE
项目中的权限控制

### ISSUE THREAD

**Issue by medisean** [thx/iconfont-plus#1367]
iconfont 中项目中所有成员都有删除，更改图标的权限，删除也没有提示或者二次确认，非常容易误删，希望可以增加权限控制

**Comment by yisibl** [comment]
我们在考虑调整项目成员权限了。

**Comment by lxang** [comment]
项目成员管理十分不方便，只有管理者能添加成员， 没有主动申请能力。权限也没有分级

**Comment by yisibl** [comment]
项目成员多角色管理功能已经上线，后续其他相关问题，请统一关注或回复： Duplicate of #1512
