### ISSUE TITLE
无法下载代码....

### ISSUE THREAD

**Issue by monsterLin** [thx/iconfont-plus#137]
点击下载代码后，网页无响应

**Comment by purplebamboo** [comment]
可以说明下更具体的场景吗？比如 如果是下载的项目，提供下项目id，如果是 直接购物车下载的，提供下选择的图标哈，我排查下。

**Comment by monsterLin** [comment]
@purplebamboo 当把图标添加到购物车后，里面有下载代码等选项，当点击下载代码后，弹出的网页无响应...(我的浏览器为chrome)
---
![](http://images.cnblogs.com/cnblogs_com/boy1025/689108/o_QQ%E6%88%AA%E5%9B%BE20161106115240.png)

**Comment by purplebamboo** [comment]
嗯  明白，我这边试了下是好的。
你这个场景下是已经登陆了吗？
你是所有的图标都不能下载吗？

如果只是图中的图标不能下载，那么麻烦你收藏下这个图标，这样  我可以定位试试这个图标是否有问题。

**Comment by monsterLin** [comment]
@purplebamboo 
- 我已经登录了，可是还是不能下载，所有图标的下载代码都不行，下载素材可以的
- 我把图片添加到项目中，然后下载也不行
- 我觉得应该是点击下载代码后，网页的重定向无响应造成的吧- -#

**Comment by purplebamboo** [comment]
我特地去你项目看了下，是叫  FirstProject 这个项目吗？

我这边下载是ok的，里面有三个图标，包括你上面的那个安卓。＝ ＝好奇怪。

那么只能怀疑是不是环境问题了，亲你可以尝试在你朋友或者同事电脑上试一下吗？

**Comment by monsterLin** [comment]
@purplebamboo  

- 恩，这个我为了试试在项目中能不能下载 - -

---
- 刚才拿了我朋友的电脑试了下，可以下载代码（朋友的浏览器：360极速浏览器- -）
- 在我的电脑的浏览器中就不行，（chrome- -）

**Comment by monsterLin** [comment]
@purplebamboo 

-  试了下windows edge可以进行登录界面，并且授权，但是授权后，还是需要用户登录
-  ie 11直接无法调到github的登录界面

**Comment by purplebamboo** [comment]
可是我用的也是chrome。。我理解你朋友的360也是chrome的内核。

所以是不是你电脑哪里有特殊设置。比如装了什么插件，比如是否开了代理，等等。

囧.....edge我明天去公司找个pc机器试下，是登陆的github？

**Comment by monsterLin** [comment]
@purplebamboo 

- 恩，这么说，估计是我的chrome的问题，也可能是我的chrome的插件的问题
- 你测试下edge和ie11的github登录是否正常..我在我的机器测试，是不正常的- -##

**Comment by purplebamboo** [comment]
好的  我明天去公司测试下。
兼容性我们可能考虑的不多，ie不是太想管，
不过edge我们还是会考虑兼容下的。

**Comment by monsterLin** [comment]
@purplebamboo 
恩，好的 ![emoji](http://qzonestyle.gtimg.cn/qzone/em/e7009.gif?max_age=2592000)

**Comment by andypan312** [comment]
情况好像还是跟账号有关，以前的项目都是无法生成在线链接，下载下来是空的字体文件，新建的项目没有问题，我现在正打算把原先项目内所有的图标全部重新搜索一下组成一个新的项目，虽然麻烦但急着用也是没有办法

**Comment by purplebamboo** [comment]
@andypan312  亲  你是不是回错issue了。你把用户给我下，还有有问题的项目id给下，我去排查下哈。

**Comment by gongeek** [comment]
@monsterLin
下面的这个网站edge github也登入不了，需要手动刷新才能登入。应该不是个例，浏览器的问题
 https://ruby-china.org/account/sign_in
