### ISSUE TITLE
官网 法律声明 那里报错 403

### ISSUE THREAD

**Issue by moocherabc** [thx/iconfont-plus#1373]
![QQ截图20190812173634](

![](https://user-images.githubusercontent.com/31909570/62856762-49035a80-bce5-11e9-9705-bceb2c95ce9a.jpg)
)
![QQ截图20190812173659](https://user-images.githubusercontent.com/31909570/62856765-4acd1e00-bce5-11e9-9bb0-2da30ddf1035.jpg)

已登录情况

**Comment by yisibl** [comment]
法律声明现在打开新窗口
