### ISSUE TITLE
icon-zhinengshebei 导致的下载和生成在线链接出错问题！

### ISSUE THREAD

**Issue by andypan312** [thx/iconfont-plus#138]
只要项目里包含 icon-zhinengshebei（搜索智能设备，第五个！） 就会出错~移除之后就可以正常下载了~是什么问题呢？？
![image](https://cloud.githubusercontent.com/assets/22565392/20039668/a47133c0-a482-11e6-9c99-41d6c36b5b4b.png)

**Comment by purplebamboo** [comment]
因为平台里 某些图标是有问题的。我们控制不了用户上传的图标质量。后续可能会出一个`举报`的功能靠大家来标记出这些有问题的图标。

**Comment by purplebamboo** [comment]
见这里： https://github.com/thx/iconfont-plus/issues/139
