### ISSUE TITLE
 "demo_index"这个文件有病毒，导致我们开发人

### ISSUE THREAD

**Issue by nemocat** [thx/iconfont-plus#1380]
为什么直接下载下来的代码会有病毒啊？
 "demo_index"这个文件有病毒，我们开发人员说直接放进去就闪退，我用杀毒软件查了一下，果然是有病毒，而且是每一次下载下来，这个文件都会有病毒。
搞什么啊

**Comment by vipsunwei** [comment]
什么情况就关闭了？ 也没解释一下？
