### ISSUE TITLE
能把页码加大一点吗

### ISSUE THREAD

**Issue by Lilyxlp** [thx/iconfont-plus#1382]
数字页码太小，不易于点击，页码的使用率较高，可以做成方框的页码，希望建议能得到采纳并改善，谢谢~~

**Comment by yisibl** [comment]
抱歉久等了，已经优化，稍晚发布

* 增加 hover 背景色
* 增加禁用按钮鼠标形状为 cursor: not-allowed;

![image](https://user-images.githubusercontent.com/2784308/65151437-ae6f0780-da58-11e9-8c9a-34803d624c82.png)

**Comment by yisibl** [comment]
https://github.com/thx/iconfont-plus/issues/755
