### ISSUE TITLE
搜索出来的单个图标能否查找与之配套的图标库

### ISSUE THREAD

**Issue by Loren1999** [thx/iconfont-plus#1383]
如题，通过搜索功能查找出的图标，是否可以匹配与之配套的图标库

**Comment by yisibl** [comment]
如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)
