### ISSUE TITLE
反向查找图标库

### ISSUE THREAD

**Issue by xiaoyuebao** [thx/iconfont-plus#1385]
搜索出图标后,通过选择喜欢的图标,反向跳转到改图标所在的图标库,
例如:我找到了喜欢的左箭头,再找配套的右箭头,上下箭头,很费劲.再例如找国旗,好到了一个喜欢的国旗类型,再找同类型的其他国家国旗也很费劲

**Comment by ziyunfei** [comment]
点击下载按钮出现的对话框里会有它所属的图标库的链接

**Comment by adoin** [comment]
资瓷

**Comment by yisibl** [comment]
如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)
