### ISSUE TITLE
【新版优化点】关于新版的建议，都统一在这里讨论

### ISSUE THREAD

**Issue by purplebamboo** [thx/iconfont-plus#139]
新版上线，肯定有一些不足，有很多人给了不错的建议，我们会罗列在这里，大家一起讨论。

等我们忙完这段时间会做一次优化。目前收集到的需求有下面这些：

* 字体woff2： 添加woff2格式的支持
* 批量操作的功能：目前加入购物车不那么方便，需要提供批量添加，删除，重命名等等功能
* 搜索优化：搜索图标区分多色单色
* eps的下载：目前eps对多色的支持有点问题，所以我们直接换成了svg，都是矢量，需要用户去ai自己转换。带来不便。
* 账户体系优化： 平台目前没有自己的账户体系，依赖微博，github这些第三方登陆，微博不是太稳定，github有时被墙比较慢。
* 图标举报机制： 平台无法控制用户上传图标的质量，有些图标引入到项目里会出现问题，需要有个机制标记出来。
* <del>帮助中心常见问题解答：用户经常遇到的问题，应该罗列下。</del>
* 增加ttf编辑器，导入ttf查看图形。
* 下载文件名字后缀增加颜色Tag以及大小Tag 
* 关注功能：目前只有对图标的收藏，后面是否可以收藏图标库，关注设计师。
* 图标排序功能： 希望在图标库详情页增加按名称，时间等排序功能。
* 界面相关：
    - <del>下载代码的框在某些浏览器下被挡住</del>
    - 下载图标时记住尺寸、颜色
    - 下载弹框，增加收藏功能
    - 缩放当前页面图标slider
    - 关联某个图标所在的图标库

**Comment by DreamCapriccio** [comment]
希望能改善图标的标准大小，并不是尺寸，比如下载的是100*100的图标，但是有些图标实际是95*95的，四周有空白的，这样就导致每个图标都需要单独控制，增加了太多不便，比如我想给每个导航增加一个不同图标，如果遇到大小不统一的图标，那真的是太壮观了~~~ 我的项目就是遇到这个情况，没办法只能统一替换成一个圆点了。。。

**Comment by purplebamboo** [comment]
@DreamCapriccio   图标大小都是用户自己上传时画布就决定的。我们其实很难操作。

针对你这个场景，其实你加入到项目里后可以编辑图标，针对这个图标在这个画布里面是可以放大缩小的哦。比如这种实际是95x95的图标，你可以放大一下，放到顶到边框。这样跟其他图标大小就会差不多。

另外，不同图标库的图标肯定不成体系，如果是导航这种场景，应该用同一个图标库的图标。比如搜索到了一个图标，点击下载，里面有这个图标所属的图标库的哈，你应该选一个图标库，全部用这个图标库里面的图标。

**Comment by minwoobobo** [comment]
现有的图标列表默认显示大小不是我最常用的尺寸，我需要点击某个图标后在弹窗里选择尺寸后才能预览到这个图标是否符合我想要的视觉效果，然后再下载。希望在所有图标列表页面都可以添加一个默认显示尺寸（甚至更多参数）的选项，方便预览，甚至可以省去弹窗，直接在列表页直接下载自己喜欢的图标。

ps：我记得旧版某个页面是可以选择图标显示大小的，新版好像连那个页面都没有了。

**Comment by purplebamboo** [comment]
@minwoobobo   明白，之前有一个缩放的小效果，这个我们可以考虑后面加上去，我加到需求列表评估下。

**Comment by lmm1990** [comment]
chrome 54图标锯尺严重

**Comment by JigsawLee** [comment]
编辑图标的时候只能 旋转，可以弄个镜面对称的

**Comment by purplebamboo** [comment]
@JigsawLee   如果这个需求高的话，我们可以考虑加上的。

**Comment by xiemin2161** [comment]
关于图标排序，不光是图标详情页需要排序，下载下来的demo.html更需要排序，因为本地用的时候，主要还是demo文件来查看。

**Comment by xiemin2161** [comment]
同时希望能够多库下载并自动分类，如下图
![iconfont](https://cloud.githubusercontent.com/assets/23207744/20338907/99138368-ac14-11e6-8113-56fdff60e150.png)

**Comment by xiemin2161** [comment]
还有在上传的时候，也需要排序，我制作的图标都有编号，但是拖上去之后，就发现所有图标已经是乱序，不是按照编号顺序显示的
![2](https://cloud.githubusercontent.com/assets/23207744/20339095/75d20e1e-ac15-11e6-8a59-ad7bc25651d6.png)

**Comment by purplebamboo** [comment]
@xiemin2161  下载自动排序我们需要评估下哈，感觉比较特殊的需求，而且好像对现有东西冲击比较大。


至于第二个，上传的时候排序，是想按照 文件名排序吗？这个倒是不难办到，上传后前端做个排序就可以。

**Comment by benzlee** [comment]
很多图标在icomoon里上传都是完全没问题的（例如material design图标），但是到了iconfont里面上传就会变成黑色块，不可能每个图标都手动处理，能否解决一下这些问题，非常感谢！

**Comment by purplebamboo** [comment]
@benzlee   图标发给我们下哈，我们测试下，尽量兼容。

发到我这个邮箱哈   xhzhuweikang@163.com

**Comment by benzlee** [comment]
@purplebamboo 已经发送邮件，感谢您的测试！

**Comment by benzlee** [comment]
@purplebamboo 问题已解决，感谢贵团队的热心支持与快速响应！点赞👍👍

**Comment by purplebamboo** [comment]
@benzlee  解决就好

**Comment by mxfc** [comment]
现在下载下来的同样的文件大小是之前的2倍左右

**Comment by purplebamboo** [comment]
@mxfc   是什么文件？ png还是其他的？  是新版相对于旧版两倍？ 还是说  新版最近相对于之前？

另外是用的什么浏览器下载的哈，最好都阐述清楚哈。

**Comment by mxfc** [comment]
突然看到项目大了点，看了下发现.eot和.ttf的文件大小  是之前的2倍左右   之前是9k  现在是19k   只是改了两个图标的大小及位置，应该不至于发生这么大的变化，所以推测是不是你们的版本更新导致生成的字体文件变大了😄

**Comment by purplebamboo** [comment]
额。。没有哎，新版旧版的字体生成都是一致的哎。用的都是一套环境，都是使用的一个c库 fontforge来生成的。

**Comment by mxfc** [comment]
哦哦  那好吧，我以为是新加了彩色字体  会导致每一个文件里面多一些对彩色相关的描述，这样的文件我怎么压缩  可以像html那样删除换行之类的吗

**Comment by purplebamboo** [comment]
你说字体文件？这个不行的哈。他们是二进制的。除了.svg的是xml格式的。

**Comment by mxfc** [comment]
好的谢谢

**Comment by pfan123** [comment]
想问一下，之前直接用ai导出来的svg图标带有很多杂七杂八的代码，可以上传成功，现在好像不可以了，然后，我对比了上传图标去掉颜色，操作上会先把svg 中style样式类联到标签、带有transform的转换为不带的path、svg基本图形也全部转换为path了，然后合并所有的path，请问一下，这些优化有依托svgo处理吗， 但是据我使用svgo发现有许多问题，文档api也不够详情，可以共享一下，你们的方案吗

**Comment by purplebamboo** [comment]
上传问题 可以把 svg发给我们哈。

亲研究的很细致，我们的确会处理标签，因为字体里面只能使用path，并且是一个path。

我们会使用svgo做处理，处理失败也会继续分析。

svgo不会进行svg基本图形全部转换为path。

我们的字体相关技术其实都有开源。

可以看看  https://github.com/purplebamboo/font-carrier

目前平台的上传用的是  @gongeek  写的模块  https://www.npmjs.com/package/svg-simple

**Comment by wudilige** [comment]
我第一次使用iconfont，想在【项目】中添加图标，尝试了很久没有找到途径。后来在文档里面找到购物车的说明，原来是要先添加到购物车才可以添加到项目，我感觉这个流程很隐晦，初学者很难理解，是否可以多一点提示之类的。

**Comment by purplebamboo** [comment]
@wudilige  感谢反馈，后期我们在帮助中心，个人引导上会再做一些改造。

**Comment by mda07022** [comment]
建议图标库打开的时候默认在新页面打开，不然返回的时候还要再加载数据，也不能同时浏览多个图标库。

**Comment by mda07022** [comment]
建议项目可以分组，项目一多列表太长了，不利于维护。
建议项目可以复制或继承，新建项目的时候可以直接继承或复制已有的基础图标。

**Comment by ZTfer** [comment]
建议增加拖动排序，图标乱成一套不爽啊。。。

**Comment by purplebamboo** [comment]
@ZTfer  目前来说拖动排序有点难办， 后期我们可以尝试提供排序功能，按名称 unicode啥的排序

**Comment by ZTfer** [comment]
那可不可以自动去除某些个前缀名字，按照前缀名字来排序，这些前缀在下载下来后会自动去除，这样分类管理就方便些了

**Comment by Liliandl** [comment]
css content 获取图标？？

**Comment by Leelina** [comment]
希望能增加项目中得图标可以移动拖拽换位置

**Comment by HADB** [comment]
图标的大小以及要处于什么样的位置，在和文字混排的时候才会和文字完全对齐？有标准的参考值吗？

**Comment by purplebamboo** [comment]
@HADB   看下这个文章，http://www.iconfont.cn/plus/help/article_detail?article_id=1

搜索 字体基线的问题

目前来说  你撑满整个 舞台画框就可以。

**Comment by xiemin2161** [comment]
新版中加入了排序功能，但是似乎还是有点小问题
按照文件名排序不知道是按照什么规则排的
好像没起作用
如图
我对图标都有编号
但是仍然好像是乱序
![default](https://cloud.githubusercontent.com/assets/23207744/21600784/a8f4dbd8-d1bc-11e6-97a8-e9df6a8ecc25.png)

**Comment by purplebamboo** [comment]
@xiemin2161   的确有问题，这就修复。 之前是按照首字母排序的，我今晚换成按  windows下面的文件名称的排序规则。

**Comment by xiemin2161** [comment]
今天看了，已经将文件名排序功能修复，在线查看能正常排序了，如图
![2](https://cloud.githubusercontent.com/assets/23207744/21632830/001ad1e2-d285-11e6-95bd-88f3dc7f7383.png)
但是，下载到本地的文件并没有按照新的排序排列，依然是乱序，如图
![1](https://cloud.githubusercontent.com/assets/23207744/21632857/25a39782-d285-11e6-8908-24b7e2110c48.png)
希望能早点修复！辛苦了！

**Comment by purplebamboo** [comment]
@xiemin2161  亲啊 下载下来的也要排序啊？  囧 这个就有点麻烦了。

平台上的是 直接前端js排序的。下载下来也要排序的话，需要改造不少东西，我后续优化下。

为什么要下载下来呢，直接在平台上对照不行吗？

**Comment by ZTfer** [comment]
最好是下载下来的也能排序好，有时候网速不是很好，访问项目的时候打开会遇到问题，项目部公开的时候能给开发看吗？因为不希望有人随意动库里的文件，所以....

**Comment by purplebamboo** [comment]
@ZTfer   明白了。。

如果不希望有人随意动库里的文件 是可以解决的，项目创建者在批量操作里，可以锁定当前图标的，这个时候其他的协作者是改不了的。

当然，这个需求有点道理，不过改起来没那么快哈。我先记一下，等有空了就改。

**Comment by xiemin2161** [comment]
当然希望下载下来的也能排好了，因为有很多公司开发环境是不连接互联网的，仅在公司内部网络使用，所以不能在线查看。还有即使连接互联网开发，我觉得考虑到有时候网速不好的话，我也会情愿调用本地文件，这样更保险一点。

**Comment by xiemin2161** [comment]
关于图标批量下载的问题，如图
![a](https://cloud.githubusercontent.com/assets/23207744/21666614/c799c4a0-d32d-11e6-8c5f-6b694cce9996.png)
![b](https://cloud.githubusercontent.com/assets/23207744/21666620/d34c1f78-d32d-11e6-9134-da048c3d76d1.png)
下载后没有文件后缀名
手动添加rar后缀名后能够打开
希望及时修复

**Comment by xiemin2161** [comment]
怎么突破20个图标下载限制呢

**Comment by purplebamboo** [comment]
@xiemin2161   https://github.com/thx/iconfont-plus/issues/209

可以做chrome工具，暂时还没有计划。

**Comment by purplebamboo** [comment]
@xiemin2161 下载文件名问题，我会尽快修复哈

**Comment by motorguo** [comment]
@purplebamboo 生成的文件顺序能否按照 Sort 的设定排序

**Comment by mengyubo** [comment]
能否做成和谷歌图标一样的功能，支持识别文字
<i class="material-icons">remove_circle</i>
可以设置为可选项，对应只支持高级浏览器的用户的一个优化（icomoon那种可选项的下载）

**Comment by 378406712** [comment]
后期增加一些图标怎么引入

**Comment by YiPianZhou** [comment]
怎么往导出的文件包中添加图标？
希望有一个可以把导出的包重新导入的功能
