### ISSUE TITLE
修改图标的中文名称

### ISSUE THREAD

**Issue by sushuier** [thx/iconfont-plus#1393]
可以修改class名字，为什么不能修改图标本身的中文名字，有时候设计师并不知道该图标与实际业务中的按钮的对应关系，他图标名字随意命名，导致查找起来不方便，想要统一管理，就需要改中文名字；

**Comment by yuanguandong** [comment]
我也遇到了同样的问题，希望官方能支持下，感谢啊，现在名字太乱了

**Comment by yisibl** [comment]
请统一在 #1500 回复并关注该 issue。
