### ISSUE TITLE
图标添加到项目的时候，不跳转到项目列表了，而且再购物车的图标也不消失，是什么问题

### ISSUE THREAD

**Issue by Zero-Freely** [thx/iconfont-plus#1400]
图标加入购物车，再添加到项目的时候，不跳转到项目列表了，而且再购物车的图标也不消失，是什么问题？
![WeChat83aa7db004ebd5a1b4fb0635092dbd8d](https://user-images.githubusercontent.com/54424597/64581467-d9a08980-d3bc-11e9-87c7-68c7e6a17b3a.png)
![WeChat71af5740fbbcb37b65a4f2cb1b6def6f](https://user-images.githubusercontent.com/54424597/64581471-dc02e380-d3bc-11e9-9911-d94aa989cd6d.png)

**Comment by xiaoJianXue** [comment]
这样 好难受啊，感觉，一开始以为卡掉了，页面 跟没反应一样，去项目里看，发现 已经有了刚才添加的，但是购物车里还是在，好难受啊，好 难受

**Comment by DaikonX** [comment]
> 这样 好难受啊，感觉，一开始以为卡掉了，页面 跟没反应一样，去项目里看，发现 已经有了刚才添加的，但是购物车里还是在，好难受啊，好 难受

我也是这样 ，但是已经添加成功了，可以在图标管理下载

**Comment by jserweb** [comment]
页面报错了

**Comment by popdo** [comment]
这个问题好久了  也没见修复哦

**Comment by vipsunwei** [comment]
项目也进不去了  没有入口啊， 现在只能直接找到想用的icon直接下载 啊。  

是关闭了吗？什么时候才能修改好这个问题啊？

**Comment by yisibl** [comment]
已经修复了，抱歉给大家带来的不便。
