### ISSUE TITLE
2019.9.16 项目图标代码生成不了？

### ISSUE THREAD

**Issue by popdo** [thx/iconfont-plus#1406]
项目图标代码生成不了，

点击生成代码  弹出提示 “正在努力生成最新代码中~~” 然后就再弹出一个粉红色的!感叹号 没有任何文字提示。。。

chrome和safari浏览器都试过 都无法生成，无论生成UnicodeFont 、class 还是Symbol都是一样无法生成。

**Comment by yisibl** [comment]
已经恢复了。
