### ISSUE TITLE
[求助]项目管理权限转移错误 如何更换项目管理者？

### ISSUE THREAD

**Issue by jb20190524** [thx/iconfont-plus#1410]
本人用户id 浩男呐
问题是这样的
ID为915005的上一任项目管理员联系不上
需要将项目管理权限转移我名下
由管理者Liao123变成浩男呐

联系客服邮箱没有回复 求大神帮忙

**Comment by yisibl** [comment]
项目 ID 915005 的管理员已经由 Liao123 改为了 浩男呐
