### ISSUE TITLE
搜索到一个图标后，由某个图标可以找到它所属的一整个系列的图标

### ISSUE THREAD

**Issue by CecilyCc** [thx/iconfont-plus#142]
希望可以增加一个功能，在首页搜索框中，搜索关键字后，在搜索结果页中，选中某一个图标，可以由这个图标找到它所属于的那个系列的图标。

**Comment by Muqing1221** [comment]
下载详情页，左上角，如果该icon属于某个公开的图标库，是可以查看它所归属的图标库的；如果不属于的话...就不可以

**Comment by purplebamboo** [comment]
其实是有的哈，只不过入口有点深，不那么明显。我们后期会优化这一块的。
