### ISSUE TITLE
Symbol 类型的 js 文件访问在线地址时出现 ERR_EMPTY_RESPONSE

### ISSUE THREAD

**Issue by vimcaw** [thx/iconfont-plus#1422]
![image](https://user-images.githubusercontent.com/21964227/65736245-f5ba5f80-e10c-11e9-8201-5955a080eb7f.png)
![image](https://user-images.githubusercontent.com/21964227/65736381-5ea1d780-e10d-11e9-883d-dd5f89817472.png)

地址为：http://at.alicdn.com/t/font_1177242_f3jnd3a9vbk.js

经测试，我的任何项目的 Symbol 类型 js 文件都是这样，都访问不了，希望官方能查看一下

通过修改一些东西刷新 url 也还是一样

**Comment by yisibl** [comment]
只有 js  打不开吗？理论上 CDN 上的文件不会打不开。

**Comment by vimcaw** [comment]
@yisibl css 的也是打不开，你们都是正常吗

**Comment by yisibl** [comment]
是的，我访问正常。你试试手机切换到 4G 能不能这个文件？

**Comment by vimcaw** [comment]
现在可以了，谢谢，刚刚可能是一些网络问题影响了 😂

**Comment by yisibl** [comment]
嗯 遇到类似的问题先用其他的网络环境（比如 4G）排查一下吧。
