### ISSUE TITLE
操作失误，将所有 iconfont 项目转给了同名的另一个人。

### ISSUE THREAD

**Issue by snowlyg** [thx/iconfont-plus#1426]
操作失误，将所有 iconfont 项目转给了同名的另一个人。很多项目都在用这些图标，不知道能不能把项目转回来 @yisibl

**Comment by snowlyg** [comment]
@cricy 有没有人回复一下，现在很多项目都在用这些图标。有没有类似撤销转让项目的功能。

**Comment by yisibl** [comment]
请提供一下项目id 或者链接以及需要转交给的正确用户名

**Comment by yisibl** [comment]
后续使用中遇到的问题可以加钉钉群咨询，群号 : 21791453

**Comment by snowlyg** [comment]
@yisibl 项目比较多，给个邮箱给我发发邮件给你。
