### ISSUE TITLE
提两个功能建议

### ISSUE THREAD

**Issue by DragonDean** [thx/iconfont-plus#1428]
1.搜索到图标之后，查看该图标所属的项目。
2.项目根据主色调分类，用户根据主色调筛选

**Comment by DragonDean** [comment]
还有一个就是创建项目的时候提供一个版权声明，需要授权的则提供联系方式或者在线购买授权

**Comment by hxyrkcy** [comment]
查看图标所在项目很重要，可以找一些图标相关的图标

**Comment by yisibl** [comment]
如果是指查看图标所在图标库功能已经有了

**Comment by yisibl** [comment]
项目图标分类请关注和回复：Duplicate of https://github.com/thx/iconfont-plus/issues/1496
