### ISSUE TITLE
在本地调试时有时可以修改字体图标的颜色和大小，有时候又不行是怎么回事？

### ISSUE THREAD

**Issue by inJonathan** [thx/iconfont-plus#143]
我使用的是symbol方式来引入图标，我发现有些项目我用css控制svg标签的color和fontsize是可以起到效果的，但是有时候在别的项目里面又无效，我就只能到线上修改然后更新js地址。请问这是怎么回事呢？

**Comment by purplebamboo** [comment]
是这样的亲，通过一些手段，的确可以达到用color 与fontsize来控制颜色的目的。

但是如果这个svg本身的path里面已经有颜色值了，（设计师上传选择了按多色图标处理）。那么用color是无法覆盖这个样式的。

具体可以参考：
https://github.com/thx/iconfont-plus/issues/13

**Comment by purplebamboo** [comment]
不过  目前的确有点问题，因为大部分设计师上传图标直接默认按多色处理。

这会导致这些图标在symbol的引用方式下，无法用color覆盖样式。

**Comment by purplebamboo** [comment]
是否可以这么做，在项目里编辑图标的时候，可以选择去掉这个icon附带的颜色，这样就可以用color覆盖了。我们再评估下。

**Comment by purplebamboo** [comment]
目前在项目里新增了去颜色的功能哈。

如果你希望 可以通过样式color修改颜色，那么就针对一些图标去除颜色哈。

方式为：批量操作-》选择一些图标-》批量去色

这时重新生成字体，就可以了哈。
