### ISSUE TITLE
github账号没法登录www.iconfont.cn了么？

### ISSUE THREAD

**Issue by misscx** [thx/iconfont-plus#1440]
我用github登录，登录后一直停在Authorize iconfont页面，没法登录么？

**Comment by yisibl** [comment]
可以的，可能是墙的问题，再试试。

**Comment by yisibl** [comment]
GitHub 由于墙的问题会不太稳定，不过我们现在已经支持手机登录了，不再依赖三方登录。如果需要找回老账号遇到问题，请加一下钉钉答疑群

![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
