### ISSUE TITLE
图标管理-我的项目，能设置上传权限吗？

### ISSUE THREAD

**Issue by mmingji** [thx/iconfont-plus#1445]
项目图标，能设置成员的权限吗，偶有成员上传图标扰乱节奏。

**Comment by yisibl** [comment]
近期会有较大的权限调整。

**Comment by yisibl** [comment]
项目成员多角色管理功能已经上线，后续其他相关问题，请统一关注或回复： Duplicate of #1512
介绍文章：https://www.yuque.com/u7268/iconfont/vkneb9

**Comment by mmingji** [comment]
已经感受了一段时间的权限管理功能了。感谢感谢。


---原始邮件---
发件人: &quot;一丝&quot;<notifications@github.com&gt;
发送时间: 2020年1月19日(周日) 下午3:52
收件人: &quot;thx/iconfont-plus&quot;<iconfont-plus@noreply.github.com&gt;;
抄送: &quot;Author&quot;<author@noreply.github.com&gt;;&quot;mmingji&quot;<407476587@qq.com&gt;;
主题: Re: [thx/iconfont-plus] 图标管理-我的项目，能设置上传权限吗？ (#1445)



项目成员多角色管理功能已经上线，后续其他相关问题，请统一关注或回复： Duplicate of #1512
 介绍文章：https://www.yuque.com/u7268/iconfont/vkneb9
 
&mdash;
