### ISSUE TITLE
iconfont是否具有仅在企业内共享对外密保的功能，以后考虑做吗？哪怕要收费也希望可以有啊

### ISSUE THREAD

**Issue by yiwuguanwu** [thx/iconfont-plus#145]
读免责申明，看到iconfont的目标客户很明确。但是还是好奇是否具有隐藏的比较深的密保工作，使得图标仅在企业里共享，企业外的人搜icon一模一样的名字不会出现对应的企业内icon（做了测试，传上去的icon任意账户搜名字也能搜到,哪怕是存在组建的项目里把我上传的图标里删掉，甚至项目里的也删掉依旧可以被搜到）？因为是免费的并且iconfont的目标客户与客户目标读着其实很明确了，不做这功能绝对无可厚非。但是还是忍不住有一丝期冀，毕竟这是主流方向，企业们绝对需要iconfont，但是很多企业由于考虑到密保性问题就不得不停下跃跃欲试的脚步，哪怕要收费也愿意啊，

**Comment by Muqing1221** [comment]
宝贵、深沉、严肃、有意义、有价值、把人从晨困中叫醒的建议...

亲说的问题我们后期会认真考虑的，谢谢~

**Comment by purplebamboo** [comment]
亲  密保的问题我们后续会考虑，我们其实是支持私有图标库的。
只不过如你所说所有图标都可以搜索到，后续可以收紧，只搜索公开库里面的图标。
