### ISSUE TITLE
关于我的项目模块下，搜索框显示问题

### ISSUE THREAD

**Issue by feimiaomiao** [thx/iconfont-plus#1452]
**1. 在搜索框输入内容**

![image](https://user-images.githubusercontent.com/38873438/68084068-b0a3ee80-fe6b-11e9-997e-2a1d665c2fa5.png)

**2. 在不点击关闭的情况下,按Esc键，接着在空白任意位置点击会出现下面这种情况**

![image](https://user-images.githubusercontent.com/38873438/68084050-691d6280-fe6b-11e9-8fb1-0a5eff560445.png)

**Comment by yisibl** [comment]
项目成员管理近期会有较大的改版。
