### ISSUE TITLE
谷歌浏览器突然下载不了svg格式

### ISSUE THREAD

**Issue by 15876560420** [thx/iconfont-plus#1455]

**Comment by yisibl** [comment]
请提供操作系统、浏览器版本号

**Comment by 15876560420** [comment]
Windows10家庭中文版，Google Chrome 已是最新版本
版本 78.0.3904.87（正式版本） （64 位）




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "一丝"<notifications@github.com&gt;; 
发送时间: 2019年11月6日(星期三) 下午3:19
收件人: "thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;; 
抄送: "∝丽*-*"<770398606@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thx/iconfont-plus] 谷歌浏览器突然下载不了svg格式 (#1455)




请提供操作系统、浏览器版本号

**Comment by 15876560420** [comment]
处理器：Intel（R）Core（TM）i5-7500 CPU@3.40GHz 3.41 GHz已安装的内存（RAM）：16.0GB（15.9GB可用）系统类型：64位操作系统，基于×64的处理器




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "一丝"<notifications@github.com&gt;; 
发送时间: 2019年11月6日(星期三) 下午3:19
收件人: "thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;; 
抄送: "∝丽*-*"<770398606@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thx/iconfont-plus] 谷歌浏览器突然下载不了svg格式 (#1455)




请提供操作系统、浏览器版本号

**Comment by yisibl** [comment]
下载地址提供一下

**Comment by 15876560420** [comment]
没事了，我找到原因了，我卸载掉大作的插件，一个图片采集器，就可以下载svg格式了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "一丝"<notifications@github.com&gt;; 
发送时间: 2019年11月22日(星期五) 下午3:18
收件人: "thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;; 
抄送: "∝丽*-*"<770398606@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thx/iconfont-plus] 谷歌浏览器突然下载不了svg格式 (#1455)




下载地址提供一下
