### ISSUE TITLE
性能反不如旧版

### ISSUE THREAD

**Issue by seekerzhang** [thx/iconfont-plus#146]
性能反不如旧版

**Comment by Muqing1221** [comment]
亲指的哪方面的性能呢

**Comment by purplebamboo** [comment]
新版使用  node重写，后端性能肯定远超过以前的  rails的哈。

是这样的新版变成了单页应用，以前的是静态页面。初次渲染，如果是弱网的话，单页应用是纯前端渲染感觉会不如静态页面。
但是后续的切换，比如项目里的切换体验肯定远胜过静态页面的哈。
