### ISSUE TITLE
在线链接，能否一个项目，固定一个链接

### ISSUE THREAD

**Issue by cmdparkour** [thx/iconfont-plus#1464]
在项目中，因为存在频繁的更换图标，每更换一次图标，就得重新换一次链接，能否让链接是固定的，只是纯粹的内容变化

**Comment by sytana** [comment]
用脚本，
![image](https://user-images.githubusercontent.com/11701135/69206362-65861d00-0b87-11ea-8bb6-3815122b9b1f.png)

**Comment by ziyunfei** [comment]
Duplicate of #1331
