### ISSUE TITLE
希望可以从图标进入该图标所属图标库

### ISSUE THREAD

**Issue by Jinming-D** [thx/iconfont-plus#1471]
很多时候需要找相关联的一系列图标，类似序号或者前进/后退这种
只通过肉眼去分辨图标大小、线粗等等是否一致一来不准确，二来很耗时
最好可以通过图标进入对应图标库，同一图标库内的图标基本是固定规范的，找起来效率会高不少

**Comment by yisibl** [comment]
图标详情中已经有了：
![image](https://user-images.githubusercontent.com/2784308/69405583-02d58280-0d3b-11ea-8fcf-7d950ff20b11.png)

**Comment by yisibl** [comment]
我们近期会优化图标库来源的视觉设计，以便更加醒目

**Comment by Jinming-D** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        不知是否有可能把复制SVG功能放到悬停菜单当中呢，就像Axhub插件一样，有的时候用没有插件的浏览器下载图标，需要点进去还是挺麻烦的
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                MrDong
                            
                    
                        
                            
                                    
                                    jinming.d@foxmail.com
                                    
                                    
                                    
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2019年12月3日 15:07，一丝<notifications@github.com> 写道： 


我们近期会优化图标库来源的视觉设计，以便更加醒目



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
