### ISSUE TITLE
希望在编辑图标的时候支持去色

### ISSUE THREAD

**Issue by cherislive** [thx/iconfont-plus#1472]
在Ant Design Icon 设置 createFromIconfontCN 方法，项目中有些图标不能设置颜色。
重新下载、去色上传后才可以；能否在编辑图标的时候 加入去色功能。

**Comment by yisibl** [comment]
是希望在我的项目内去色还是哪里呢？

**Comment by cherislive** [comment]
> 是希望在我的项目内去色还是哪里呢？

你好：
希望在项目内 编辑图标的时候增加去色功能。
因为项目搭配 Ant Design 中 Icon 组件 一起使用（设置 Icon 组件方法： createFromIconfontCN，调用 iconfont.cn 上的项目图标），然而 Ant Design 在 3.9.0 之后 使用了 SVG 图标替换了原先的 font 图标，这时使用 iconfont 会经常遇到设置颜色无效的情况，并且在编辑图标时，设置了一个灰色，同样会使图标变成灰色的有色图标，对其设置 color 无效。
目前的解决方案是：下载原有图标然后重新上传。
如果在编辑图标时，增加去色功能，会方便很多，谢谢！

**Comment by WchenE** [comment]
臣复议！
上传时，选择了【去除颜色并提交】
单个【点击上传替换icon】时，却不能去色，默认带出了sketch里的颜色/编辑时选择的颜色
导致代码更新时多出了串色值

**Comment by yisibl** [comment]
项目中可以批量去色：
![image](https://user-images.githubusercontent.com/2784308/146758094-6070736d-ef1e-4e0e-958f-39a94dc3a7bd.png)
