### ISSUE TITLE
平台生成的 font class 方式引入命名变了

### ISSUE THREAD

**Issue by WangLeto** [thx/iconfont-plus#1475]
![image](https://user-images.githubusercontent.com/25009314/69617167-cd020800-1072-11ea-9f20-2119878f80d0.png)
之前都是有中划线的吧，为什么现在在 icon 和 name 之间没有连字符了

**Comment by WangLeto** [comment]
@yisibl

**Comment by yisibl** [comment]
设置里面可以修改。
