### ISSUE TITLE
移动端首次打开页面，无法显示图标，刷新后能显示

### ISSUE THREAD

**Issue by wyy9630** [thx/iconfont-plus#148]
移动端首次打开页面，无法显示图标，刷新后能显示

**Comment by Muqing1221** [comment]
@gongeek

**Comment by wyy9630** [comment]
@purplebamboo 没什么场景，就是正常的手机网页首次打开无法显示图标

**Comment by wyy9630** [comment]
@purplebamboo ios 端

**Comment by purplebamboo** [comment]
项目地址给我们下？

**Comment by wyy9630** [comment]
@purplebamboo http://m.alltuu.com

**Comment by purplebamboo** [comment]
网站不错，不过我说的是  你在iconfont上面的项目哈，我测试下你这个项目。

或者你有单独测试我们的下载下来的demo不？

另外  你用的是  普通的unicode使用方式吗/?  这些场景都要告诉我们下  我们才好排查。

**Comment by popoAOAOgroan** [comment]
同样的问题！ react项目下index引用css文件，在ios和safari中第一次进入时不显示图标，在刷新后才出现

**Comment by zyz0810** [comment]
同样的问题，IOS第一次进入时不显示图标，刷新后出现

**Comment by wanganb** [comment]
同样的问题，IOS第一次进入时不显示图标，刷新后出现

**Comment by wyy9630** [comment]
我估计是某些不规范的图标引起的问题，建议排查下这个问题大概是什么时候出现的，然后删掉那个时候添加的图标试下
