### ISSUE TITLE
mac中图标显示正常 window中图标没有轮廓

### ISSUE THREAD

**Issue by ZeroJsus** [thx/iconfont-plus#1482]
问题描述：
同样的一个图标，在网站上传展示之后和mac中预览的时候是正常的 在windows中使用的时候 不能正常的展示icon中的轮廓

![Uploading image.png…](这是window10中 对应的图标从官网上下载下来的样式)
![Uploading image.png…](这是mac下 对应的图标展示的样式)

**Comment by ZeroJsus** [comment]
解决了
原因是因为 上传iconfont中的图标不能有边框 需要一个path画完对应的图形 对svg设计更加严格

**Comment by yisibl** [comment]
相关问题： https://github.com/thx/iconfont-plus/issues/1937
