### ISSUE TITLE
【建议】搜索单个图标，查看详情希望能有看到关联的图标库（所属图标库）

### ISSUE THREAD

**Issue by gybin02** [thx/iconfont-plus#1484]
有时候需要一组风格一致的图标，但是通过当个图标搜索无法实现

**Comment by lizy0329** [comment]
支持，现在的管理功能是十分稀烂

而且，支持加入反馈功能，有一些 icon 明显就制作十分劣质，基线都错误，最好可以拉黑

**Comment by yisibl** [comment]
如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)

**Comment by lizy0329** [comment]
> 如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
> ![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)

那么这个问题又会变成：
我想寻找有“所属图标库”的指定 icon，但网页里没有这个筛选项
