### ISSUE TITLE
原来用其他登录方式的账号已经不能用了，我是管理员。现在我也无法登录到那个账号了，开发同事加不进去

### ISSUE THREAD

**Issue by Deer321** [thx/iconfont-plus#1487]
老的账号好像是微信登陆的不确定啦，就记得账号名是Deer 项目是Saas移动版。能帮我找回吗，着急啊。我现在的账号是指鹿为马的鸣

**Comment by yisibl** [comment]
请确认一下是不是下面这个项目？
项目名称：saas移动版，项目 ID  1200416

用户 Deer 下还有另外一个项目，微信小程序，1156759

这两个项目需要把管理员转交给哪个用户？

**Comment by Rickmoti** [comment]
这个可以商用吗

**Comment by Deer321** [comment]
你好，我回来了。是的 把Deer所有项目的管理员都转交到“指鹿为马的鸣”吧！

**Comment by Deer321** [comment]
十分的感谢你们

**Comment by Deer321** [comment]
其实这两个账号都是我

**Comment by Deer321** [comment]
> 请确认一下是不是下面这个项目？
> 项目名称：saas移动版，项目ID 1200416
> 
> 用户Deer下还有另外一个项目，微信小程序，1156759
> 
> 这两个项目需要把管理员转交给这位用户？

是的

**Comment by Deer321** [comment]
@yisibl  辛苦啦

**Comment by yisibl** [comment]
转让好了。

**Comment by Deer321** [comment]
收到了，感谢
