### ISSUE TITLE
上传图片失败!!!

### ISSUE THREAD

**Issue by MingLiuHN** [thx/iconfont-plus#1489]
![image](https://user-images.githubusercontent.com/34367398/71142618-db4ada80-2252-11ea-92d0-a80bda9ec3a6.png)

**Comment by yisibl** [comment]
请提供一下上传的文件

**Comment by MingLiuHN** [comment]
[Uploading 资源-svg.zip…]()

谢谢了.

**Comment by yisibl** [comment]
文件上传失败了吧，加一下 钉钉群：群号 : 21791453，发我
