### ISSUE TITLE
“下载图标”的体验感觉不如以前，希望能优化一下

### ISSUE THREAD

**Issue by chan0925** [thx/iconfont-plus#149]
1. 新的下载方式（阴影遮盖的）看不见当前需要下载的目标，没有之前的清晰明了；
2. 选择下载后的弹窗界面，操作重心是左边的内容，但现在视觉焦点感觉是偏右的（不知道其他用户感受怎样），可能设计意图更倾向于收藏或查看图集，但个人觉得iconfont最主要的功能还是icon的下载，社交是附加功能，现在有点喧宾夺主？旧版的功能就很明确，点击“下载”后就是选择颜色和尺寸，然后下载。
3. 不知道是不是浏览器的原因：（MacOS Capitan／ Safari）旧版选png下载时，是另开一个浏览器窗口的，我可以直接拖动图标到设计软件中，很方便。但新版的下载png是直接将图标下载到电脑“我的下载”中，这样我就需要先打开文件夹，找到新下载的图标，然后才能拖进设计软件。这比之前多了两步操作，感觉体验变得不好了。

**Comment by purplebamboo** [comment]
哈  亲，重口难调。作为程序猿，我在不专业的角度一一解答下：

1. 这个阴影覆盖是hover上去才有，我理解只有你有了操作的想法才会去hover，这个时候应该专注在上面的操作按钮上。
2. 这个我不好回答，其实你说的对，新版我们是想更多的做关注，不想iconfont只是个工具网站，他应该有更多的活跃度，是一个设计师前端的交流平台，当然由于时间的问题，现在关注做的有点不上不下，我们后面会慢慢完善。
3. 旧版其实是个bug＝ ＝。这么说吧chrome下我们直接用的 浏览器下载，而safari不支持这个技术，会直接打开不是下载。以前我们一直没时间修复，也被不少吐槽。新版我们做了优化，chrome下面还是直接用这个新技术，safari下面直接调用的服务器下载，这个才是正常的。所以比较囧，亲你这个需求应该才是比较特殊的，他不符合正常的逻辑来着。误打误撞了。
