### ISSUE TITLE
彩色图标下载时变换颜色整个图标都变色了

### ISSUE THREAD

**Issue by jadegazzz** [thx/iconfont-plus#15]
<img width="498" alt="2016-10-19 22 02 11" src="https://cloud.githubusercontent.com/assets/22937746/19521819/ba4daf14-9647-11e6-8113-904894070fc1.png">
<img width="482" alt="2016-10-19 22 02 15" src="https://cloud.githubusercontent.com/assets/22937746/19521818/b9d58958-9647-11e6-8620-2f83d3988870.png">
<img width="487" alt="2016-10-19 22 02 20" src="https://cloud.githubusercontent.com/assets/22937746/19521820/babfee26-9647-11e6-9f45-7afdaa5baad6.png">

**Comment by Muqing1221** [comment]
`https://img.alicdn.com/tps/TB1UdKmNVXXXXXYXVXXXXXXXXXX-494-529.jpg`

在问过我们的视觉同学后，给予的答复如下：
如果要对彩色图标进行颜色变化，在图标上面点击后选中要变色的区域，再点击颜色。如果不选择区域，就会使整个图标进行变色。

**Comment by Muqing1221** [comment]
在问过我们的视觉同学后，给予的答复如下：
如果要对彩色图标进行颜色变化，在图标上面点击后选中要变色的区域，再点击颜色。如果不选择区域，就会使整个图标进行变色
![菠萝](https://img.alicdn.com/tps/TB1UdKmNVXXXXXYXVXXXXXXXXXX-494-529.jpg)
