### ISSUE TITLE
AI格式的文件无法下载，总是导向svg格式，很苦恼，不如旧版好用，翻页也不会刷新

### ISSUE THREAD

**Issue by comonlee** [thx/iconfont-plus#150]
AI格式的文件无法下载，总是导向svg格式，很苦恼，不如旧版好用，翻页也不会刷新

**Comment by Muqing1221** [comment]
svg下载问题之后修复

翻页不会刷新是？

**Comment by purplebamboo** [comment]
ai 格式现在有点问题，只支持单色，这个还在想办法解决，最近太忙。稍微给我们点时间哈。

翻页不刷新，有可能是网络问题，或者正好遇上流量峰值服务器挂掉之类的。多试几次哈。


有关ai的问题，见这里哈：

https://github.com/thx/iconfont-plus/issues/139
