### ISSUE TITLE
图标有没有1024PX的？

### ISSUE THREAD

**Issue by liunanxun** [thx/iconfont-plus#1502]
图标有没有1024像素的？  或者怎么设置成1024像素的

**Comment by yisibl** [comment]
请下载矢量的 SVG 格式，可以自由缩放。

**Comment by liunanxun** [comment]
好的 谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "一丝"<notifications@github.com&gt;; 
发送时间: 2020年1月7日(星期二) 晚上6:30
收件人: "thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;; 
抄送: "刘南巡"<296003112@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thx/iconfont-plus] 图标有没有1024PX的？ (#1502)




请下载矢量的 SVG 格式，可以自由缩放。
