### ISSUE TITLE
vue项目中，字体图标偶尔会显示乱码

### ISSUE THREAD

**Issue by JonSnow-JY** [thx/iconfont-plus#1506]
![image](https://user-images.githubusercontent.com/23466087/72118225-679c7900-338b-11ea-81a1-74fa7e5494fa.png)
刷新下就好了，但是为啥会出新乱码呢？

**Comment by yisibl** [comment]
图标的字体文件可能没有加载，就会出现这样的情况。

**Comment by tianyongchao** [comment]
怎么解决的啊
