### ISSUE TITLE
无法上传文件

### ISSUE THREAD

**Issue by L1cardo** [thx/iconfont-plus#1507]
无法上传此图标
[youtu.zip](https://github.com/thx/iconfont-plus/files/4058185/youtu.zip)
<img width="1595" alt="image" src="https://user-images.githubusercontent.com/33802186/72328723-68683e80-36ee-11ea-888d-dd99ae0ae5c7.png">

**Comment by yisibl** [comment]
iconfont 目前不支持渐变。

**Comment by yisibl** [comment]
支持渐变图标请关注：https://github.com/thx/iconfont-plus/issues/1938
