### ISSUE TITLE
下载记录的问题

### ISSUE THREAD

**Issue by renxiaomeng** [thx/iconfont-plus#1508]
在公司下载的图标，回到家再看的时候，没有了（不同电脑）
后来我又试了下，同一个账号，比如在Chrome下载的历史记录，换为另一个浏览器，相同的帐号登录成功后，在历史记录就没有了，而Chrome的历史记录还是存在的
难道是存在浏览器的本地环境？

**Comment by yisibl** [comment]
下载记录是浏览器的行为。
