### ISSUE TITLE
希望可以推出SVG动画，图标已经不足以满足当今网站了

### ISSUE THREAD

**Issue by Xiangjiakang** [thx/iconfont-plus#1517]
希望可以推出### **SVG动画**，图标已经不足以满足当今网站了
最好是可编辑性强的动画，让我们的### 静态变动态，推动互联网发展

**Comment by yisibl** [comment]
很抱歉 目前没有这方面的计划。

**Comment by meijuji202** [comment]
想要SVG 动画图标，目前symbol引用方式是能支持SVG动画的。不需要全部模式都需要动画，至少可以实现的先实现。
