### ISSUE TITLE
SVG文件无法上传

### ISSUE THREAD

**Issue by yhjyang1** [thx/iconfont-plus#1518]
有个svg文件没法上传，帮忙看看，谢谢

[console-icon-gentoo.svg.zip](https://github.com/thx/iconfont-plus/files/4146251/console-icon-gentoo.svg.zip)

**Comment by yisibl** [comment]
很抱歉 iconfont 目前不支持渐变。

**Comment by yisibl** [comment]
支持渐变图标请关注：https://github.com/thx/iconfont-plus/issues/1938
