### ISSUE TITLE
能否对搜到的图标加入返回到专辑的链接？

### ISSUE THREAD

**Issue by yuzhigang** [thx/iconfont-plus#152]
iconfont的搜索很方便，图标丰富性已经很大程度满足了。但是风格一致问题却很难解决。比如有时候搜的满意图标是线性的，有的不是。如果**能给搜到的图标加入一个返回到该专辑的链接**，就能很容易找到风格类似的图标。

iconfont目前支持关键字搜人和图标，改版后非常期待能加入搜索专辑的功能，因为能在一个专辑里找到风格一致的图标，然后并没有。

谢谢。

**Comment by Muqing1221** [comment]
![真的有的，我很冤](http://tuku02-qn.icp114.cn/public/16-11-9/98519237.jpg)
![骗你是狗](http://tuku02-qn.icp114.cn/public/16-11-9/92739538.jpg)

**Comment by purplebamboo** [comment]
参考上面的哈，这个入口可能有点深，我们后续再看看能不能优化下。
