### ISSUE TITLE
之前用微博账号登录的，但是微博账号注销了，怎么破？

### ISSUE THREAD

**Issue by larryspace** [thx/iconfont-plus#1523]
RT，里面有几个项目的图标

**Comment by yisibl** [comment]
用户名或者项目 id 还记得吗？

**Comment by JounQin** [comment]
+1，现在也没办法把多种登录方式绑定起来，容易忘了用的哪个账号注册的。

**Comment by ElvaChan0211** [comment]
同样的问题，怎么破呢？项目id是那么吗？ 有一个叫wealth，可以帮忙找回账户吗～ 不知道怎么找回账户。

**Comment by rppig42** [comment]
@yisibl 同样的问题，项目ID还有，能够找回么

**Comment by yisibl** [comment]
Duplicate of #1718

**Comment by sinsy** [comment]
怎么才能找回呢，项目经过很多人的手，现在图标库的账号密码没了，怎么办

**Comment by yisibl** [comment]
我们正在考虑实现新的账户系统
