### ISSUE TITLE
为啥不能直接下载png了啊

### ISSUE THREAD

**Issue by DillonPu** [thx/iconfont-plus#1525]

**Comment by yisibl** [comment]
具体是哪个图标，请发一下链接。

**Comment by DillonPu** [comment]
https://www.iconfont.cn/search/index?searchType=icon&q=discover，我试了很多个图标，点击PNG下载都没反应

**Comment by yisibl** [comment]
可以下载，请检查一下网络。

**Comment by DillonPu** [comment]
可能是我电脑上的迅雷有点问题，点击下载png时，唤起了迅雷，但是没下载，我把迅雷卸载了，然后再点击下载png的时候，就可以用浏览器自带的下载器进行下载了。
