### ISSUE TITLE
项目库突然都没了

### ISSUE THREAD

**Issue by a394867798as** [thx/iconfont-plus#1529]
账号:a394867798as(github登录)
昵称：赵广来wolfcub
请帮忙解决，谢谢

**Comment by yisibl** [comment]
目前查到只有这一个项目
![image](https://user-images.githubusercontent.com/2784308/74900765-bfdb8780-53db-11ea-9631-9e909e82d2c4.png)

之前还有哪些项目，记得项目 id 或者项目名称吗？

**Comment by eir-kun** [comment]
> 目前查到只有这一个项目
> ![image](https://user-images.githubusercontent.com/2784308/74900765-bfdb8780-53db-11ea-9631-9e909e82d2c4.png)
> 
> 之前还有哪些项目，记得项目 id 或者项目名称吗？

我的也是github登录的，里面的项目和其它东西都没了。这是昵称：fly丶知秋

**Comment by a394867798as** [comment]
> 目前查到只有这一个项目
> ![image](https://user-images.githubusercontent.com/2784308/74900765-bfdb8780-53db-11ea-9631-9e909e82d2c4.png)
> 
> 之前还有哪些项目，记得项目 id 或者项目名称吗？

at.alicdn.com/t/font_1264974

> 目前查到只有这一个项目
> ![图片](https://user-images.githubusercontent.com/2784308/74900765-bfdb8780-53db-11ea-9631-9e909e82d2c4.png)
> 
> 之前还有一些项目，记得项目id或项目名称吗？

//at.alicdn.com/t/font_1264974

**Comment by a394867798as** [comment]
> 目前查到只有这一个项目
> ![图片](https://user-images.githubusercontent.com/2784308/74900765-bfdb8780-53db-11ea-9631-9e909e82d2c4.png)
> 
> 之前还有一些项目，记得项目id或项目名称吗？

//at.alicdn.com/t/font_1264974  我原来有这个地址的项目。

**Comment by yisibl** [comment]
如果需要找回老账号遇到问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
