### ISSUE TITLE
多色图标为什么上传不了呢？

### ISSUE THREAD

**Issue by DR1001** [thx/iconfont-plus#153]
本地是多色的，但是传上来就成了单色了，我有点搞不懂啊！

**Comment by Muqing1221** [comment]
上传页面，亲是否勾选了“按多色图标处理”呢

**Comment by gongeek** [comment]
svg图标代码贴出来看看？或者传给我 gongweiqm@qq.com

**Comment by Muqing1221** [comment]
![看这里](http://tuku02-qn.icp114.cn/public/16-11-9/54433595.jpg)
