### ISSUE TITLE
上传文件名带数字的图标，生成的名称会把数字丢掉

### ISSUE THREAD

**Issue by fengtianze** [thx/iconfont-plus#1532]
如上传 close_8_s, 生成的代码为 prefix-close__s

![image](https://user-images.githubusercontent.com/16134228/75140281-84b5bd00-5729-11ea-9cb2-ac9b1b18a9e6.png)

辛苦解决一下，谢谢

**Comment by Hishengs** [comment]
![image](https://user-images.githubusercontent.com/8407978/78888594-839bdd80-7a94-11ea-9efe-b44852926ad1.png)

同样的问题为什么历经一年还没修复呢？ @yisibl

**Comment by yisibl** [comment]
很抱歉，久等了，现在图标名称已经支持数字。后续有其他问题可以加钉钉群讨论（群号 : 21791453）
