### ISSUE TITLE
项目库不见了

### ISSUE THREAD

**Issue by niesk** [thx/iconfont-plus#1536]
1个多月未登录，所有项目库突然不见了
昵称：niesk
github登录
请帮忙解决，谢谢
我记得几个项目名称：嘉瑞百合缘、非戈相亲角

**Comment by niesk** [comment]
可能是我改了ID的缘故，以前的ID是：nie55352177，请帮忙查询一下

**Comment by yisibl** [comment]
换了登陆方式等同于两个完全不同的账号了，如果需要转移到新账号，请提供iconfont 的账号昵称，niesk 查不到。
![image](https://user-images.githubusercontent.com/2784308/78004943-6e74cf80-736d-11ea-88c6-171a20e16c8a.png)

**Comment by nie55352177** [comment]
昵称是：niesk.

**Comment by yisibl** [comment]
如果需要找回老账号遇到问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
