### ISSUE TITLE
批量下载图标打不开。

### ISSUE THREAD

**Issue by YaweiWang** [thx/iconfont-plus#154]

**Comment by Muqing1221** [comment]
方便描述详细点么？
批量下载的那种格式的icon打不开啊

**Comment by YaweiWang** [comment]
我选择多张图片，然后点击png下载，下载后是一个downloadIcon文件，不能解压也打不开，但是如果只下载一张的话就没问题了。详情见截图
![qq 20161109100152](https://cloud.githubusercontent.com/assets/9461271/20124770/e3eacf9c-a663-11e6-8f2e-0dbeac8ff25c.jpg)
![qq 20161109100207](https://cloud.githubusercontent.com/assets/9461271/20124771/e422ff7a-a663-11e6-82e3-4de4973192c5.jpg)

**Comment by Muqing1221** [comment]
我刚才试了一下，是ok的诶，OS sierra  Chrome，亲要不换个浏览器试试？

**Comment by YaweiWang** [comment]
找到原因了，我的解压软件bandzip解压不了这个文件，换个解压软件就好了。谢谢，麻烦了。

**Comment by Muqing1221** [comment]
嫑客气~
