### ISSUE TITLE
关于增加图标渐变的功能

### ISSUE THREAD

**Issue by fengchuanBIG** [thx/iconfont-plus#1541]
希望可以增加渐变的功能，这样引用的时候更巴适一点，现在已经支持彩色了，希望可以考虑考虑，还有就是解决图标不居中的问题，也就是字体基线的问题，一直得不到解决希望一并考虑一下

**Comment by yisibl** [comment]
暂时没有考虑哦

**Comment by yisibl** [comment]
请关注：https://github.com/thx/iconfont-plus/issues/1938
