### ISSUE TITLE
请问下是否有打算给 “图标管理 - 我的项目” 里面的图标增加排序功能？

### ISSUE THREAD

**Issue by mmingji** [thx/iconfont-plus#1543]
项目的图标是不断积累出来的，多个项目也可以复用。
现在默认是按照上传时间排序，用的时候，找图标就比较麻烦。
所以，请问下是否有打算增加手动排序功能，或者按照首字母排序？

**Comment by yisibl** [comment]
Duplicate of #1496，请关注这个问题，统一到那里回复。
