### ISSUE TITLE
【紧急】github授权登录报错

### ISSUE THREAD

**Issue by topin** [thx/iconfont-plus#1548]
github 授权登录后返回错误
`{
code: "ECONNREFUSED"
message: "Error"
}`

**Comment by dearzoe** [comment]
我也遇到这个问题，让别人去选择图标，然后我再登录就会有这个问题

**Comment by gongeek** [comment]
@topin 遇到这种情况麻烦重试下  github不太稳定 登入支持更多其他方式在我们需求计划之中
