### ISSUE TITLE
友情链接打不开

### ISSUE THREAD

**Issue by muzidx** [thx/iconfont-plus#155]
淘宝UED 天猫UED 的链接都不太对呀，跳到爱逛街去了呢？

**Comment by Muqing1221** [comment]
@gongeek

**Comment by gongeek** [comment]
天猫UED淘宝UED的网站都挂了...
所以跳转跳不过去是他们网站的问题。
跳到爱逛街是先到淘宝错误页，如何淘宝错误页定时调到爱逛节了...

后面考虑下掉这2个链接。
