### ISSUE TITLE
账号密码遗忘了

### ISSUE THREAD

**Issue by hdgevfyaw** [thx/iconfont-plus#1552]
去年的时候上传了一批图标，因为时间有点长了，账号密码忘记了···请问如何找回账号和密码

目前我只知道以下内容：
1.用户名：小桔车服图标管理员
2.两个图标库的链接
https://www.iconfont.cn/collections/detail?cid=15424
https://www.iconfont.cn/collections/detail?cid=15425
3.图标库的密码：xiaojuchefu

希望管理员大大能看到我的问题，并帮忙解决，谢谢啦！

**Comment by gongeek** [comment]
查看了下 小桔车服图标管理员 是微博注册的
应该是这个微博账号 https://weibo.com/u/3736766241 
用这个账号用微博账号能登入
