### ISSUE TITLE
能不能把我的收藏这个图标放出来，不好找

### ISSUE THREAD

**Issue by laiyiwen12306** [thx/iconfont-plus#1554]
能不能把我的收藏这个图标放出来，不好找，太难找了

**Comment by yisibl** [comment]
具体指哪个图标？

**Comment by laiyiwen12306** [comment]
就是找不到我的收藏在哪





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"一丝"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 下午4:26
收件人:&nbsp;"thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;;
抄送:&nbsp;"□梦境中人"<pc663416@QQ.COM&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 能不能把我的收藏这个图标放出来，不好找 (#1554)





 
具体指哪个图标？

**Comment by yisibl** [comment]
![image](https://user-images.githubusercontent.com/2784308/78153021-348af280-746d-11ea-9dcc-b687952bf6d8.png)

**Comment by laiyiwen12306** [comment]
好的。

**Comment by laiyiwen12306** [comment]
好的，谢谢老哥





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"一丝"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月1日(星期三) 晚上11:05
收件人:&nbsp;"thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;;
抄送:&nbsp;"□梦境中人"<pc663416@QQ.COM&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 能不能把我的收藏这个图标放出来，不好找 (#1554)





 
Closed #1554.
