### ISSUE TITLE
多色图标库的搜索太差

### ISSUE THREAD

**Issue by kingsjl** [thx/iconfont-plus#156]
多色图标库的搜索太差，基本搜索不了！

**Comment by purplebamboo** [comment]
额。。亲  你是指搜索体验不好？

**Comment by JigsawLee** [comment]
对啊   比如搜到某一个图标  可以查看这个图标所在的项目，在这个项目中再查看其他图标

**Comment by Muqing1221** [comment]
啊，老梗...看来要出专门的说明页了...

如果该图标隶属于某个公共图标库，是可以在下载浮层看到具体归属信息的，如果不隶属于，就不可以...

原因是，在查询单个图标的时候，结果页的源数据是全部用户上传的图标；Mr.J提到的项目有私密属性，不可能被非项目成员看到（虽然支持共享，但也保护隐私~）；图标库的概念是，用户可以将一组相关图标申请为公共图标库，即默认他人可以搜索到这样一整套图标，申请图标库即给这一组图标公共属性；

综上，能否从单个图标追溯会图标库以及作者，主要取决于，人家作者乐不乐意~~

当然，为了所谓“设计的民主”，我们期待呼吁且相信，大家在上传图标时麻烦认真命名；将一系列相关图标申请公共库，且认真命名~
予人玫瑰，手有余香~~

之后酌情出详细说明页~

**Comment by purplebamboo** [comment]
项目是私密的，按理说就是不可以追溯到的。

图标库如果是公开图标库那么是可以追溯到的，而我们其实也是提供了这个功能的。点击图标下载，可以在下载面板看到它所属的图标库的。

当然这个入口目前有点深，我们会继续优化的。

具体可以关注优化需求 https://github.com/thx/iconfont-plus/issues/139
