### ISSUE TITLE
我创建的项目中没有我自己怎么办？

### ISSUE THREAD

**Issue by tianyan314** [thx/iconfont-plus#1561]
以前我在iconfont上为公司创建了一个项目，项目名称叫友房公盘PC，且管理员是我自己，但是最近发现登录以后看不到这个项目了，但其他同事都是正常的，而且通过同事的账号可以看到我依然是管理员，请问这种情况应该怎么处理？

下图是其他同事登录后
![image](https://user-images.githubusercontent.com/62637554/77506988-3b7c9880-6ea2-11ea-8d4a-b6ffbec48579.png)
![image](https://user-images.githubusercontent.com/62637554/77507016-518a5900-6ea2-11ea-9dc7-1e4d79fd1d98.png)

下图是我自己账户登录后看不到项目
![image](https://user-images.githubusercontent.com/62637554/77507043-6ff05480-6ea2-11ea-82c8-f4bbd59881ee.png)

**Comment by yisibl** [comment]
这个项目目前的超级管理员是：tianyan314，亲的用户名是什么，期望在该项目中是什么角色？

**Comment by tianyan314** [comment]
我就是超级管理员tianyan314，但是我登录以后看不到我这个项目，请见上面的截图。

**Comment by tianyan314** [comment]
或者你帮我把成员揭大飞改设为超级管理员也可以，这样剩下的问题我们团队就可以自己操作了。

**Comment by yisibl** [comment]
> 或者你帮我把成员揭大飞改设为超级管理员也可以，这样剩下的问题我们团队就可以自己操作了
已经把「揭大飞」设置为超级管理员。

你应该是用了两个不同的微博登陆了 iconfont，所以现在有两个 tianyan314 这个用户。
