### ISSUE TITLE
github崩了，能多加点登陆方式吗？

### ISSUE THREAD

**Issue by qinjieheyang** [thx/iconfont-plus#1565]
github崩了，能多加点登陆方式吗？我进去后也没找到用github登陆的怎么关联新浪微博账号。希望改善

**Comment by yisibl** [comment]
考虑增加更多的登陆方式。

**Comment by necfol** [comment]
github登陆不了啊，我账号废了？

**Comment by qiubishi** [comment]
github 登录经常出问题

**Comment by yisibl** [comment]
我们正在考虑实现新的账户系统

Duplicate of #1718
