### ISSUE TITLE
请问一下，我们公司自己画了一套icon，只供自己商用，想上传到阿里压缩ttf。会不会被盗去商用。如被侵权，该怎么办

### ISSUE THREAD

**Issue by Donwy** [thx/iconfont-plus#1567]

**Comment by yisibl** [comment]
目前可以选择为私有图标，这样不会在搜索中被索引到，如果新建图标库 可以加密码。

**Comment by Donwy** [comment]
好的，谢谢你




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"一丝"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月31日(星期二) 下午3:13
收件人:&nbsp;"thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;;
抄送:&nbsp;"Donvy_y"<572419921@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 请问一下，我们公司自己画了一套icon，只供自己商用，想上传到阿里压缩ttf。会不会被盗去商用。如被侵权，该怎么办 (#1567)





 
目前可以选择为私有图标，这样不会在搜索中被索引到，如果新建图标库 可以加密码。

**Comment by yisibl** [comment]
https://www.iconfont.cn/manage/index?spm=a313x.7781069.1998910419.d15d5f6f4&manage_type=myicons 这里选中相应的图标，批量私有
![image](https://user-images.githubusercontent.com/2784308/78002179-6155e180-7369-11ea-9e39-b0f4ef48478d.png)

**Comment by Donwy** [comment]
真的谢谢你，Thanks♪(･ω･)ﾉ




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "一丝"<notifications@github.com&gt;; 
发送时间: 2020年3月31日(星期二) 下午4:05
收件人: "thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;; 
抄送: "Donvy_y"<572419921@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thx/iconfont-plus] 请问一下，我们公司自己画了一套icon，只供自己商用，想上传到阿里压缩ttf。会不会被盗去商用。如被侵权，该怎么办 (#1567)





 
https://www.iconfont.cn/manage/index?spm=a313x.7781069.1998910419.d15d5f6f4&amp;manage_type=myicons 这里选中相应的图标，批量私有
 
 
&mdash;
