### ISSUE TITLE
在引用iconfont时第一次加载不出来，刷新之后才能出来

### ISSUE THREAD

**Issue by 4869z** [thx/iconfont-plus#1570]
在引用iconfont时第一次加载不出来，刷新之后才能出来

**Comment by yisibl** [comment]
可以提供一个可以复现的demo地址吗？

**Comment by 4869z** [comment]
一个vue的demo
引用在 index.html里
使用在 HelloWorld.vue里
https://github.com/4869z/icon_test

**Comment by 4869z** [comment]
原先 因为 使用display: none; 隐藏 所以首次加载页面会出现方框的情况
现在换了一个 隐藏原始图标的方式 就好了

**Comment by yisibl** [comment]
是的某些浏览器中，display: none 的元素不会请求字体加载
