### ISSUE TITLE
在非主页页面上使用Github登录时会遇到ECONNREFUSED

### ISSUE THREAD

**Issue by sinloss** [thx/iconfont-plus#1573]
在下载素材时，遇到要求登录的弹框，在选择了`Github`后，页面跳至错误页面，错误信息为
```json
{"code":"ECONNREFUSED","message":"Error"}
```
经过若干种尝试后发现，当在主页第一屏时，点击右上角的登录按钮，选择`Github`登录，则可以正常登录。
而只要不在主页第一屏，通过`Github`登录就会遇到上述报错信息。

* 随便选取主页推送图标组，尝试以`Github`登录，报错；
* 在购物车，尝试以`Github`登录，报错；
* 点击`ICONFONT`logo进入主页，尝试以`Github`登录，**成功登录**

**Comment by sinloss** [comment]
再次尝试，该状况已无法复现

**Comment by guzhangyu** [comment]
还是会发生。

**Comment by sinloss** [comment]
Reopen this issue due to the occasional occurrence as per the comment from @guzhangyu

**Comment by yisibl** [comment]
GitHub 由于墙的问题会不太稳定，不过我们现在已经支持手机登录了，不再依赖三方登录。如果需要找回老账号遇到问题，请加一下钉钉答疑群

![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
