### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by ty2014** [thx/iconfont-plus#1575]
三种方式都登录不了，提示错误

**Comment by luckyloong** [comment]
是啊，GITHUB登录不了了啊！官方快解决额！

**Comment by yisibl** [comment]
GitHub 由于墙的问题会不太稳定，不过我们现在已经支持手机登录了，不再依赖三方登录。如果需要找回老账号遇到问题，请加一下钉钉答疑群

![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
