### ISSUE TITLE
快捷登录方式,为什么不支持钉钉登录呢?

### ISSUE THREAD

**Issue by wsnsnsns** [thx/iconfont-plus#1576]
RT

**Comment by yisibl** [comment]
考虑中。

**Comment by 512084028** [comment]
good idea

**Comment by wsnsnsns** [comment]
还没有好啊... @yisibl

**Comment by yisibl** [comment]
我们现在已经支持手机登录了，不再依赖三方登录。如果需要找回老账号遇到问题，请加一下钉钉答疑群

![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
