### ISSUE TITLE
无法上传svg，读取的svg内容错误

### ISSUE THREAD

**Issue by xiaoxintang** [thx/iconfont-plus#1578]
![image](https://user-images.githubusercontent.com/24927686/78965643-2c4b4b00-7b30-11ea-8521-8176a2ae1e86.png)
所有上传的svg都会变成这样

**Comment by yisibl** [comment]
请在这里上传一下 svg 源文件

**Comment by xiaoxintang** [comment]
> 请在这里上传一下 svg 源文件

这里如何能上svg传源文件

**Comment by xiaoxintang** [comment]
> 请在这里上传一下 svg 源文件

只能给你个源码了
```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="14px" height="14px" viewBox="0 0 14 14" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 60 (88103) - https://sketch.com -->
    <title>编组 2</title>
    <desc>Created with Sketch.</desc>
    <g id="页面-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="定时任务" transform="translate(-24.000000, -298.000000)">
            <rect fill="#FFFFFF" x="0" y="0" width="1440" height="900"></rect>
            <g id="编组" transform="translate(0.000000, 54.000000)">
                <rect id="Sidebar" fill="#F0F1F2" x="0" y="0" width="220" height="846"></rect>
                <g id="编组-2备份" transform="translate(24.000000, 240.000000)" fill-rule="nonzero">
                    <g id="编组-32" transform="translate(0.000000, 4.000000)">
                        <g id="appstore-add">
                            <rect id="矩形" fill="#000000" opacity="0" x="0" y="0" width="14" height="14"></rect>
                            <path d="M6.34375,1.96875 L2.1875,1.96875 C2.0671875,1.96875 1.96875,2.0671875 1.96875,2.1875 L1.96875,6.34375 C1.96875,6.4640625 2.0671875,6.5625 2.1875,6.5625 L6.34375,6.5625 C6.4640625,6.5625 6.5625,6.4640625 6.5625,6.34375 L6.5625,2.1875 C6.5625,2.0671875 6.4640625,1.96875 6.34375,1.96875 Z M5.6328125,5.6328125 L2.8984375,5.6328125 L2.8984375,2.8984375 L5.6328125,2.8984375 L5.6328125,5.6328125 Z M11.8125,1.96875 L7.65625,1.96875 C7.5359375,1.96875 7.4375,2.0671875 7.4375,2.1875 L7.4375,6.34375 C7.4375,6.4640625 7.5359375,6.5625 7.65625,6.5625 L11.8125,6.5625 C11.9328125,6.5625 12.03125,6.4640625 12.03125,6.34375 L12.03125,2.1875 C12.03125,2.0671875 11.9328125,1.96875 11.8125,1.96875 Z M11.1015625,5.6328125 L8.3671875,5.6328125 L8.3671875,2.8984375 L11.1015625,2.8984375 L11.1015625,5.6328125 Z M11.8125,7.4375 L7.65625,7.4375 C7.5359375,7.4375 7.4375,7.5359375 7.4375,7.65625 L7.4375,11.8125 C7.4375,11.9328125 7.5359375,12.03125 7.65625,12.03125 L11.8125,12.03125 C11.9328125,12.03125 12.03125,11.9328125 12.03125,11.8125 L12.03125,7.65625 C12.03125,7.5359375 11.9328125,7.4375 11.8125,7.4375 Z M11.1015625,11.1015625 L8.3671875,11.1015625 L8.3671875,8.3671875 L11.1015625,8.3671875 L11.1015625,11.1015625 Z M5.796875,9.734375 L4.046875,9.734375 L4.046875,7.984375 C4.046875,7.92421875 3.99765625,7.875 3.9375,7.875 L3.28125,7.875 C3.22109375,7.875 3.171875,7.92421875 3.171875,7.984375 L3.171875,9.734375 L1.421875,9.734375 C1.36171875,9.734375 1.3125,9.78359375 1.3125,9.84375 L1.3125,10.5 C1.3125,10.5601562 1.36171875,10.609375 1.421875,10.609375 L3.171875,10.609375 L3.171875,12.359375 C3.171875,12.4195312 3.22109375,12.46875 3.28125,12.46875 L3.9375,12.46875 C3.99765625,12.46875 4.046875,12.4195312 4.046875,12.359375 L4.046875,10.609375 L5.796875,10.609375 C5.85703125,10.609375 5.90625,10.5601562 5.90625,10.5 L5.90625,9.84375 C5.90625,9.78359375 5.85703125,9.734375 5.796875,9.734375 Z" id="形状" fill="#212327"></path>
                        </g>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>
```

**Comment by gongeek** [comment]
> > 请在这里上传一下 svg 源文件
> 
> 只能给你个源码了
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <svg width="14px" height="14px" viewBox="0 0 14 14" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
>     
>     <title>编组 2</title>
>     <desc>Created with Sketch.</desc>
>     <g id="页面-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
>         <g id="定时任务" transform="translate(-24.000000, -298.000000)">
>             <rect fill="#FFFFFF" x="0" y="0" width="1440" height="900"></rect>
>             <g id="编组" transform="translate(0.000000, 54.000000)">
>                 <rect id="Sidebar" fill="#F0F1F2" x="0" y="0" width="220" height="846"></rect>
>                 <g id="编组-2备份" transform="translate(24.000000, 240.000000)" fill-rule="nonzero">
>                     <g id="编组-32" transform="translate(0.000000, 4.000000)">
>                         <g id="appstore-add">
>                             <rect id="矩形" fill="#000000" opacity="0" x="0" y="0" width="14" height="14"></rect>
>                             <path d="M6.34375,1.96875 L2.1875,1.96875 C2.0671875,1.96875 1.96875,2.0671875 1.96875,2.1875 L1.96875,6.34375 C1.96875,6.4640625 2.0671875,6.5625 2.1875,6.5625 L6.34375,6.5625 C6.4640625,6.5625 6.5625,6.4640625 6.5625,6.34375 L6.5625,2.1875 C6.5625,2.0671875 6.4640625,1.96875 6.34375,1.96875 Z M5.6328125,5.6328125 L2.8984375,5.6328125 L2.8984375,2.8984375 L5.6328125,2.8984375 L5.6328125,5.6328125 Z M11.8125,1.96875 L7.65625,1.96875 C7.5359375,1.96875 7.4375,2.0671875 7.4375,2.1875 L7.4375,6.34375 C7.4375,6.4640625 7.5359375,6.5625 7.65625,6.5625 L11.8125,6.5625 C11.9328125,6.5625 12.03125,6.4640625 12.03125,6.34375 L12.03125,2.1875 C12.03125,2.0671875 11.9328125,1.96875 11.8125,1.96875 Z M11.1015625,5.6328125 L8.3671875,5.6328125 L8.3671875,2.8984375 L11.1015625,2.8984375 L11.1015625,5.6328125 Z M11.8125,7.4375 L7.65625,7.4375 C7.5359375,7.4375 7.4375,7.5359375 7.4375,7.65625 L7.4375,11.8125 C7.4375,11.9328125 7.5359375,12.03125 7.65625,12.03125 L11.8125,12.03125 C11.9328125,12.03125 12.03125,11.9328125 12.03125,11.8125 L12.03125,7.65625 C12.03125,7.5359375 11.9328125,7.4375 11.8125,7.4375 Z M11.1015625,11.1015625 L8.3671875,11.1015625 L8.3671875,8.3671875 L11.1015625,8.3671875 L11.1015625,11.1015625 Z M5.796875,9.734375 L4.046875,9.734375 L4.046875,7.984375 C4.046875,7.92421875 3.99765625,7.875 3.9375,7.875 L3.28125,7.875 C3.22109375,7.875 3.171875,7.92421875 3.171875,7.984375 L3.171875,9.734375 L1.421875,9.734375 C1.36171875,9.734375 1.3125,9.78359375 1.3125,9.84375 L1.3125,10.5 C1.3125,10.5601562 1.36171875,10.609375 1.421875,10.609375 L3.171875,10.609375 L3.171875,12.359375 C3.171875,12.4195312 3.22109375,12.46875 3.28125,12.46875 L3.9375,12.46875 C3.99765625,12.46875 4.046875,12.4195312 4.046875,12.359375 L4.046875,10.609375 L5.796875,10.609375 C5.85703125,10.609375 5.90625,10.5601562 5.90625,10.5 L5.90625,9.84375 C5.90625,9.78359375 5.85703125,9.734375 5.796875,9.734375 Z" id="形状" fill="#212327"></path>
>                         </g>
>                     </g>
>                 </g>
>             </g>
>         </g>
>     </g>
> </svg>
> ```
1. 使用sketch 绘制的图标 使用 fill-rule="evenodd" 这个属性时不支持解析，
2.  然后再就是你这个svg请删除无用的编组，只导出svg部分即可，如下图导出后可正常上传。
![image](https://user-images.githubusercontent.com/3911824/78975379-8eaf4600-7b46-11ea-8a36-0595a391afc7.png)
![image](https://user-images.githubusercontent.com/3911824/78975467-b9999a00-7b46-11ea-9e3c-1150a491bdfa.png)
正常导出后的图形SVG源码如下：
```html
<svg width="14px" height="14px" viewBox="0 0 14 14" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 60 (88103) - https://sketch.com -->
    <title>编组 2</title>
    <desc>Created with Sketch.</desc>
        <g id="定时任务" transform="translate(-24.000000, -298.000000)">
            <rect fill="#FFFFFF" x="0" y="0" width="1440" height="900"></rect>
            <g id="编组" transform="translate(0.000000, 54.000000)">
                <rect id="Sidebar" fill="#F0F1F2" x="0" y="0" width="220" height="846"></rect>
                <g id="编组-2备份" transform="translate(24.000000, 240.000000)" fill-rule="nonzero">
                    <g id="编组-32" transform="translate(0.000000, 4.000000)">
                        <g id="appstore-add">
                            <rect id="矩形" fill="#000000" opacity="0" x="0" y="0" width="14" height="14"></rect>
                            <path d="M6.34375,1.96875 L2.1875,1.96875 C2.0671875,1.96875 1.96875,2.0671875 1.96875,2.1875 L1.96875,6.34375 C1.96875,6.4640625 2.0671875,6.5625 2.1875,6.5625 L6.34375,6.5625 C6.4640625,6.5625 6.5625,6.4640625 6.5625,6.34375 L6.5625,2.1875 C6.5625,2.0671875 6.4640625,1.96875 6.34375,1.96875 Z M5.6328125,5.6328125 L2.8984375,5.6328125 L2.8984375,2.8984375 L5.6328125,2.8984375 L5.6328125,5.6328125 Z M11.8125,1.96875 L7.65625,1.96875 C7.5359375,1.96875 7.4375,2.0671875 7.4375,2.1875 L7.4375,6.34375 C7.4375,6.4640625 7.5359375,6.5625 7.65625,6.5625 L11.8125,6.5625 C11.9328125,6.5625 12.03125,6.4640625 12.03125,6.34375 L12.03125,2.1875 C12.03125,2.0671875 11.9328125,1.96875 11.8125,1.96875 Z M11.1015625,5.6328125 L8.3671875,5.6328125 L8.3671875,2.8984375 L11.1015625,2.8984375 L11.1015625,5.6328125 Z M11.8125,7.4375 L7.65625,7.4375 C7.5359375,7.4375 7.4375,7.5359375 7.4375,7.65625 L7.4375,11.8125 C7.4375,11.9328125 7.5359375,12.03125 7.65625,12.03125 L11.8125,12.03125 C11.9328125,12.03125 12.03125,11.9328125 12.03125,11.8125 L12.03125,7.65625 C12.03125,7.5359375 11.9328125,7.4375 11.8125,7.4375 Z M11.1015625,11.1015625 L8.3671875,11.1015625 L8.3671875,8.3671875 L11.1015625,8.3671875 L11.1015625,11.1015625 Z M5.796875,9.734375 L4.046875,9.734375 L4.046875,7.984375 C4.046875,7.92421875 3.99765625,7.875 3.9375,7.875 L3.28125,7.875 C3.22109375,7.875 3.171875,7.92421875 3.171875,7.984375 L3.171875,9.734375 L1.421875,9.734375 C1.36171875,9.734375 1.3125,9.78359375 1.3125,9.84375 L1.3125,10.5 C1.3125,10.5601562 1.36171875,10.609375 1.421875,10.609375 L3.171875,10.609375 L3.171875,12.359375 C3.171875,12.4195312 3.22109375,12.46875 3.28125,12.46875 L3.9375,12.46875 C3.99765625,12.46875 4.046875,12.4195312 4.046875,12.359375 L4.046875,10.609375 L5.796875,10.609375 C5.85703125,10.609375 5.90625,10.5601562 5.90625,10.5 L5.90625,9.84375 C5.90625,9.78359375 5.85703125,9.734375 5.796875,9.734375 Z" id="形状" fill="#212327"></path>
                        </g>
                    </g>
                </g>
            </g>
        </g>
</svg>
```

**Comment by xiaoxintang** [comment]
这是蓝狐上面下载下来的svg

**Comment by xiaoxintang** [comment]
> > > 请在这里上传一下 svg 源文件
> > 
> > 
> > 只能给你个源码了
> > ```
> > <?xml version="1.0" encoding="UTF-8"?>
> > <svg width="14px" height="14px" viewBox="0 0 14 14" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
> >     
> >     <title>编组 2</title>
> >     <desc>Created with Sketch.</desc>
> >     <g id="页面-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
> >         <g id="定时任务" transform="translate(-24.000000, -298.000000)">
> >             <rect fill="#FFFFFF" x="0" y="0" width="1440" height="900"></rect>
> >             <g id="编组" transform="translate(0.000000, 54.000000)">
> >                 <rect id="Sidebar" fill="#F0F1F2" x="0" y="0" width="220" height="846"></rect>
> >                 <g id="编组-2备份" transform="translate(24.000000, 240.000000)" fill-rule="nonzero">
> >                     <g id="编组-32" transform="translate(0.000000, 4.000000)">
> >                         <g id="appstore-add">
> >                             <rect id="矩形" fill="#000000" opacity="0" x="0" y="0" width="14" height="14"></rect>
> >                             <path d="M6.34375,1.96875 L2.1875,1.96875 C2.0671875,1.96875 1.96875,2.0671875 1.96875,2.1875 L1.96875,6.34375 C1.96875,6.4640625 2.0671875,6.5625 2.1875,6.5625 L6.34375,6.5625 C6.4640625,6.5625 6.5625,6.4640625 6.5625,6.34375 L6.5625,2.1875 C6.5625,2.0671875 6.4640625,1.96875 6.34375,1.96875 Z M5.6328125,5.6328125 L2.8984375,5.6328125 L2.8984375,2.8984375 L5.6328125,2.8984375 L5.6328125,5.6328125 Z M11.8125,1.96875 L7.65625,1.96875 C7.5359375,1.96875 7.4375,2.0671875 7.4375,2.1875 L7.4375,6.34375 C7.4375,6.4640625 7.5359375,6.5625 7.65625,6.5625 L11.8125,6.5625 C11.9328125,6.5625 12.03125,6.4640625 12.03125,6.34375 L12.03125,2.1875 C12.03125,2.0671875 11.9328125,1.96875 11.8125,1.96875 Z M11.1015625,5.6328125 L8.3671875,5.6328125 L8.3671875,2.8984375 L11.1015625,2.8984375 L11.1015625,5.6328125 Z M11.8125,7.4375 L7.65625,7.4375 C7.5359375,7.4375 7.4375,7.5359375 7.4375,7.65625 L7.4375,11.8125 C7.4375,11.9328125 7.5359375,12.03125 7.65625,12.03125 L11.8125,12.03125 C11.9328125,12.03125 12.03125,11.9328125 12.03125,11.8125 L12.03125,7.65625 C12.03125,7.5359375 11.9328125,7.4375 11.8125,7.4375 Z M11.1015625,11.1015625 L8.3671875,11.1015625 L8.3671875,8.3671875 L11.1015625,8.3671875 L11.1015625,11.1015625 Z M5.796875,9.734375 L4.046875,9.734375 L4.046875,7.984375 C4.046875,7.92421875 3.99765625,7.875 3.9375,7.875 L3.28125,7.875 C3.22109375,7.875 3.171875,7.92421875 3.171875,7.984375 L3.171875,9.734375 L1.421875,9.734375 C1.36171875,9.734375 1.3125,9.78359375 1.3125,9.84375 L1.3125,10.5 C1.3125,10.5601562 1.36171875,10.609375 1.421875,10.609375 L3.171875,10.609375 L3.171875,12.359375 C3.171875,12.4195312 3.22109375,12.46875 3.28125,12.46875 L3.9375,12.46875 C3.99765625,12.46875 4.046875,12.4195312 4.046875,12.359375 L4.046875,10.609375 L5.796875,10.609375 C5.85703125,10.609375 5.90625,10.5601562 5.90625,10.5 L5.90625,9.84375 C5.90625,9.78359375 5.85703125,9.734375 5.796875,9.734375 Z" id="形状" fill="#212327"></path>
> >                         </g>
> >                     </g>
> >                 </g>
> >             </g>
> >         </g>
> >     </g>
> > </svg>
> > ```
> 
> 1. 使用sketch 绘制的图标 使用 fill-rule="evenodd" 这个属性时不支持解析，
> 2. 然后再就是你这个svg请删除无用的编组，只导出svg部分即可，如下图导出后可正常上传。
>    ![image](https://user-images.githubusercontent.com/3911824/78975379-8eaf4600-7b46-11ea-8a36-0595a391afc7.png)
>    ![image](https://user-images.githubusercontent.com/3911824/78975467-b9999a00-7b46-11ea-9e3c-1150a491bdfa.png)
>    正常导出后的图形SVG源码如下：
> 
> ```
> <svg width="14px" height="14px" viewBox="0 0 14 14" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
>     
>     <title>编组 2</title>
>     <desc>Created with Sketch.</desc>
>         <g id="定时任务" transform="translate(-24.000000, -298.000000)">
>             <rect fill="#FFFFFF" x="0" y="0" width="1440" height="900"></rect>
>             <g id="编组" transform="translate(0.000000, 54.000000)">
>                 <rect id="Sidebar" fill="#F0F1F2" x="0" y="0" width="220" height="846"></rect>
>                 <g id="编组-2备份" transform="translate(24.000000, 240.000000)" fill-rule="nonzero">
>                     <g id="编组-32" transform="translate(0.000000, 4.000000)">
>                         <g id="appstore-add">
>                             <rect id="矩形" fill="#000000" opacity="0" x="0" y="0" width="14" height="14"></rect>
>                             <path d="M6.34375,1.96875 L2.1875,1.96875 C2.0671875,1.96875 1.96875,2.0671875 1.96875,2.1875 L1.96875,6.34375 C1.96875,6.4640625 2.0671875,6.5625 2.1875,6.5625 L6.34375,6.5625 C6.4640625,6.5625 6.5625,6.4640625 6.5625,6.34375 L6.5625,2.1875 C6.5625,2.0671875 6.4640625,1.96875 6.34375,1.96875 Z M5.6328125,5.6328125 L2.8984375,5.6328125 L2.8984375,2.8984375 L5.6328125,2.8984375 L5.6328125,5.6328125 Z M11.8125,1.96875 L7.65625,1.96875 C7.5359375,1.96875 7.4375,2.0671875 7.4375,2.1875 L7.4375,6.34375 C7.4375,6.4640625 7.5359375,6.5625 7.65625,6.5625 L11.8125,6.5625 C11.9328125,6.5625 12.03125,6.4640625 12.03125,6.34375 L12.03125,2.1875 C12.03125,2.0671875 11.9328125,1.96875 11.8125,1.96875 Z M11.1015625,5.6328125 L8.3671875,5.6328125 L8.3671875,2.8984375 L11.1015625,2.8984375 L11.1015625,5.6328125 Z M11.8125,7.4375 L7.65625,7.4375 C7.5359375,7.4375 7.4375,7.5359375 7.4375,7.65625 L7.4375,11.8125 C7.4375,11.9328125 7.5359375,12.03125 7.65625,12.03125 L11.8125,12.03125 C11.9328125,12.03125 12.03125,11.9328125 12.03125,11.8125 L12.03125,7.65625 C12.03125,7.5359375 11.9328125,7.4375 11.8125,7.4375 Z M11.1015625,11.1015625 L8.3671875,11.1015625 L8.3671875,8.3671875 L11.1015625,8.3671875 L11.1015625,11.1015625 Z M5.796875,9.734375 L4.046875,9.734375 L4.046875,7.984375 C4.046875,7.92421875 3.99765625,7.875 3.9375,7.875 L3.28125,7.875 C3.22109375,7.875 3.171875,7.92421875 3.171875,7.984375 L3.171875,9.734375 L1.421875,9.734375 C1.36171875,9.734375 1.3125,9.78359375 1.3125,9.84375 L1.3125,10.5 C1.3125,10.5601562 1.36171875,10.609375 1.421875,10.609375 L3.171875,10.609375 L3.171875,12.359375 C3.171875,12.4195312 3.22109375,12.46875 3.28125,12.46875 L3.9375,12.46875 C3.99765625,12.46875 4.046875,12.4195312 4.046875,12.359375 L4.046875,10.609375 L5.796875,10.609375 C5.85703125,10.609375 5.90625,10.5601562 5.90625,10.5 L5.90625,9.84375 C5.90625,9.78359375 5.85703125,9.734375 5.796875,9.734375 Z" id="形状" fill="#212327"></path>
>                         </g>
>                     </g>
>                 </g>
>             </g>
>         </g>
> </svg>
> ```

按照你的源码拿去试了，还是一样的并不可以

**Comment by yisibl** [comment]
用这个就好了，去除掉无用的图层。

```svg
<?xml version="1.0" encoding="UTF-8"?>
<svg width="384px" height="376px" viewBox="0 0 384 376" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <!-- Generator: Sketch 63.1 (92452) - https://sketch.com -->
    <title>appstore-add</title>
    <desc>Created with Sketch.</desc>
    <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g fill="#212327" fill-rule="nonzero">
            <g>
                <g transform="translate(0.000000, -0.000000)">
                    <g>
                        <g>
                            <path d="M180.5625,0.3125 L32.125,0.3125 C27.828125,0.3125 24.3125,3.828125 24.3125,8.125 L24.3125,156.5625 C24.3125,160.859375 27.828125,164.375 32.125,164.375 L180.5625,164.375 C184.859375,164.375 188.375,160.859375 188.375,156.5625 L188.375,8.125 C188.375,3.828125 184.859375,0.3125 180.5625,0.3125 Z M155.171875,131.171875 L57.515625,131.171875 L57.515625,33.515625 L155.171875,33.515625 L155.171875,131.171875 Z M375.875,0.3125 L227.4375,0.3125 C223.140625,0.3125 219.625,3.828125 219.625,8.125 L219.625,156.5625 C219.625,160.859375 223.140625,164.375 227.4375,164.375 L375.875,164.375 C380.171875,164.375 383.6875,160.859375 383.6875,156.5625 L383.6875,8.125 C383.6875,3.828125 380.171875,0.3125 375.875,0.3125 Z M350.484375,131.171875 L252.828125,131.171875 L252.828125,33.515625 L350.484375,33.515625 L350.484375,131.171875 Z M375.875,195.625 L227.4375,195.625 C223.140625,195.625 219.625,199.140625 219.625,203.4375 L219.625,351.875 C219.625,356.171875 223.140625,359.6875 227.4375,359.6875 L375.875,359.6875 C380.171875,359.6875 383.6875,356.171875 383.6875,351.875 L383.6875,203.4375 C383.6875,199.140625 380.171875,195.625 375.875,195.625 Z M350.484375,326.484375 L252.828125,326.484375 L252.828125,228.828125 L350.484375,228.828125 L350.484375,326.484375 Z M161.03125,277.65625 L98.53125,277.65625 L98.53125,215.15625 C98.53125,213.007812 96.7734375,211.25 94.625,211.25 L71.1875,211.25 C69.0390625,211.25 67.28125,213.007812 67.28125,215.15625 L67.28125,277.65625 L4.78125,277.65625 C2.6328125,277.65625 0.875,279.414062 0.875,281.5625 L0.875,305 C0.875,307.148436 2.6328125,308.90625 4.78125,308.90625 L67.28125,308.90625 L67.28125,371.40625 C67.28125,373.554686 69.0390625,375.3125 71.1875,375.3125 L94.625,375.3125 C96.7734375,375.3125 98.53125,373.554686 98.53125,371.40625 L98.53125,308.90625 L161.03125,308.90625 C163.179688,308.90625 164.9375,307.148436 164.9375,305 L164.9375,281.5625 C164.9375,279.414062 163.179688,277.65625 161.03125,277.65625 Z"></path>
                        </g>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>
```

**Comment by xiaoxintang** [comment]
> 用这个就好了，去除掉无用的图层。
> 
> ```
> <?xml version="1.0" encoding="UTF-8"?>
> <svg width="384px" height="376px" viewBox="0 0 384 376" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
>     
>     <title>appstore-add</title>
>     <desc>Created with Sketch.</desc>
>     <g stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
>         <g fill="#212327" fill-rule="nonzero">
>             <g>
>                 <g transform="translate(0.000000, -0.000000)">
>                     <g>
>                         <g>
>                             <path d="M180.5625,0.3125 L32.125,0.3125 C27.828125,0.3125 24.3125,3.828125 24.3125,8.125 L24.3125,156.5625 C24.3125,160.859375 27.828125,164.375 32.125,164.375 L180.5625,164.375 C184.859375,164.375 188.375,160.859375 188.375,156.5625 L188.375,8.125 C188.375,3.828125 184.859375,0.3125 180.5625,0.3125 Z M155.171875,131.171875 L57.515625,131.171875 L57.515625,33.515625 L155.171875,33.515625 L155.171875,131.171875 Z M375.875,0.3125 L227.4375,0.3125 C223.140625,0.3125 219.625,3.828125 219.625,8.125 L219.625,156.5625 C219.625,160.859375 223.140625,164.375 227.4375,164.375 L375.875,164.375 C380.171875,164.375 383.6875,160.859375 383.6875,156.5625 L383.6875,8.125 C383.6875,3.828125 380.171875,0.3125 375.875,0.3125 Z M350.484375,131.171875 L252.828125,131.171875 L252.828125,33.515625 L350.484375,33.515625 L350.484375,131.171875 Z M375.875,195.625 L227.4375,195.625 C223.140625,195.625 219.625,199.140625 219.625,203.4375 L219.625,351.875 C219.625,356.171875 223.140625,359.6875 227.4375,359.6875 L375.875,359.6875 C380.171875,359.6875 383.6875,356.171875 383.6875,351.875 L383.6875,203.4375 C383.6875,199.140625 380.171875,195.625 375.875,195.625 Z M350.484375,326.484375 L252.828125,326.484375 L252.828125,228.828125 L350.484375,228.828125 L350.484375,326.484375 Z M161.03125,277.65625 L98.53125,277.65625 L98.53125,215.15625 C98.53125,213.007812 96.7734375,211.25 94.625,211.25 L71.1875,211.25 C69.0390625,211.25 67.28125,213.007812 67.28125,215.15625 L67.28125,277.65625 L4.78125,277.65625 C2.6328125,277.65625 0.875,279.414062 0.875,281.5625 L0.875,305 C0.875,307.148436 2.6328125,308.90625 4.78125,308.90625 L67.28125,308.90625 L67.28125,371.40625 C67.28125,373.554686 69.0390625,375.3125 71.1875,375.3125 L94.625,375.3125 C96.7734375,375.3125 98.53125,373.554686 98.53125,371.40625 L98.53125,308.90625 L161.03125,308.90625 C163.179688,308.90625 164.9375,307.148436 164.9375,305 L164.9375,281.5625 C164.9375,279.414062 163.179688,277.65625 161.03125,277.65625 Z"></path>
>                         </g>
>                     </g>
>                 </g>
>             </g>
>         </g>
>     </g>
> </svg>
> ```
是的，可以了，不过我现在有个疑问，是蓝湖改了东西还是你们改了东西还是我们的ui改了东西，之前在蓝湖上面下载的是可以上传的，现在不能直接上传了，哈哈

**Comment by yisibl** [comment]
蓝湖是什么？

**Comment by xiaoxintang** [comment]
> 蓝湖是什么？iconfont 上的图标制作需要一定规则，请参考：https://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.15&helptype=draw

这就是蓝湖[点我点我](https://sos.lanhuapp.com/lan-hu-gong-neng-gai-lan.html#%E5%8A%9F%E8%83%BD%E6%A6%82%E8%A7%88)
