### ISSUE TITLE
想将icon添加至已有项目时，加入项目边栏页没显示项目名称，希望能解决下

### ISSUE THREAD

**Issue by 17khba** [thx/iconfont-plus#158]
![qq 20161110114926](https://cloud.githubusercontent.com/assets/7893589/20164017/21389086-a73c-11e6-8376-d67fc97aae42.png)
### 类似这样的，看不到已有的项目名称

**Comment by Muqing1221** [comment]
系统和浏览器是？

**Comment by 17khba** [comment]
系统：win10-64位  浏览器：chrome
旧版没有这个问题，我暂时用回旧版了

**Comment by 17khba** [comment]
尝试清理了下缓存，问题就存在了，还是谢谢你

**Comment by Muqing1221** [comment]
Have a nice weekday~
