### ISSUE TITLE
选中图标下载Svg文件，Svg的尺寸过大

### ISSUE THREAD

**Issue by mingyec** [thx/iconfont-plus#1583]
现在选择任意（包括自上传）的图标，点击选择下载，Svg文件类型，下载下来有**90kb+**的尺寸，这貌似有点不合理。
时间节点放在一两个月前，好像并不会这样，下载下来的图标一般只有1~2kb+的尺寸

**Comment by yisibl** [comment]
哪个图标呢？

**Comment by mingyec** [comment]
![image](https://user-images.githubusercontent.com/15625058/79196828-53bd5300-7e63-11ea-8498-ddede060367c.png)
![image](https://user-images.githubusercontent.com/15625058/79196854-633c9c00-7e63-11ea-80b0-2422185139fd.png)
![image](https://user-images.githubusercontent.com/15625058/79196901-7485a880-7e63-11ea-9ac1-b7909dede128.png)
![image](https://user-images.githubusercontent.com/15625058/79196926-7e0f1080-7e63-11ea-81c2-6af48f5ed910.png)

**Comment by mingyec** [comment]
> 哪个图标呢？请提供一下链接。

任意一个都会如此，如上图

**Comment by yisibl** [comment]
下载的时候是通过 base64 方式来做的，所以 Chrome 这里看到的大小要比实际大小大。
![image](https://user-images.githubusercontent.com/2784308/79199286-5e79e700-7e67-11ea-82ed-5b5698176924.png)

**Comment by mingyec** [comment]
我不这么认为，在windows下的显示如下图
![image](https://user-images.githubusercontent.com/15625058/79199572-c3cdd800-7e67-11ea-9768-357cf4820e73.png)

**Comment by mingyec** [comment]
而且打开这个svg文件，会发现里面多了一串base64？这个是在之前没有的
![image](https://user-images.githubusercontent.com/15625058/79199722-f972c100-7e67-11ea-85c3-cc9a8ed02f35.png)

**Comment by yisibl** [comment]
浏览器和版本号多少？我看看能不能复现

**Comment by mingyec** [comment]
系统：windows 10
浏览器：Chrome
浏览器版本号：80.0.3987.163（正式版本） （64 位）

**Comment by mingyec** [comment]
@yisibl 抱歉，我发现这个问题可能是由浏览器插件影响的，理由如下：
- 在edge浏览器下在Svg图标大小是正常的（2kb左右）
- 在chrome无痕模式下下载Svg图标大小也是正常的

**Comment by yisibl** [comment]
嗯 我在 windows 下也无法复现，试试看是什么插件导致的

**Comment by mingyec** [comment]
@yisibl 印象笔记chrome插件有毒=_=!

**Comment by radiorz** [comment]
冒昧问一下 印象笔记为什么会导致 svg 图片变大???
禁用印象笔记之后果然变小了@ @yisibl  @mingyec
