### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by BuCai** [thx/iconfont-plus#159]
Can you add Frame Animation as a new icon classification?
Sometimes we need Frame Animation in our project.

**Comment by Muqing1221** [comment]
Wow, I feel very honored to receive one advice written by English , you know, non-Chinese user is one kind of encouragement.
As for your suggest, it's worthy and useful but not easy to realize, we have take it as our goal in the following stage, please stay tuned. 
Thank you very much.

（如果你是祖国同胞，请嫑老考验我蹩脚的英文~~阿里嘎多~~）
