### ISSUE TITLE
希望搜索出来图标后，能转到这个图标所属的项目（所属图库）

### ISSUE THREAD

**Issue by yuanshukun** [thx/iconfont-plus#1591]
希望搜索出来图标后，能转到这个图标所属的项目（所属图库）

**Comment by yisibl** [comment]
如果图标有图标库，会展示在右侧

https://www.iconfont.cn/search/index?q=%E9%A3%9E%E6%9C%BA

![image](https://user-images.githubusercontent.com/2784308/79857261-17a86600-8400-11ea-9c21-cb9a92ab6c5b.png)
