### ISSUE TITLE
微博登录问题

### ISSUE THREAD

**Issue by czkjserver** [thx/iconfont-plus#1597]
iconfont微博登录想换一个微博登录，但是每次点击微博直接就登陆原来的了

**Comment by yisibl** [comment]
Duplicate of #1718

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖微博的三方登录。如果需要找回老账号遇到问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
