### ISSUE TITLE
为什么阿里旗下的服务，没有支持支付宝登录

### ISSUE THREAD

**Issue by wf1205952124** [thx/iconfont-plus#1599]
为什么阿里旗下的服务，没有支持支付宝登录

**Comment by mumaxiansheng** [comment]
github  登录老是失败

**Comment by yisibl** [comment]
我们现在已经支持手机登录了，不再依赖微博的三方登录。如果需要找回老账号遇到问题，请加一下钉钉答疑群

![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
