### ISSUE TITLE
建议添加全选 多选功能

### ISSUE THREAD

**Issue by lulei90** [thx/iconfont-plus#16]
每次一个个点的太蛋疼了

**Comment by Muqing1221** [comment]
哪个页面让亲受累了~哈哈~
现在只有项目内有批量操作功能~~我们也还在尝试~看看广大同学对批量操作的需求集中在哪些场景，以及，频次有多高频~~

**Comment by purplebamboo** [comment]
是这样的  亲，
* 项目里操作比较高频改，我们提供了批量操作的功能。
* 添加图标到购物车，本身就是再批量的一个个加入呀。
* 我上传的图标部分，因为是个人自己的，而且可能被别人应用，我们不建议大量修改，所以不提供批量处理。

我估计  亲主要说的是  添加到购物车吧，这个因为本身添加就是批量的。

试想下，如果提供批量选中，也是要一个个去选择的。全选也没有啥意义，不可能所有图标你都要。

**Comment by lulei90** [comment]
之前想把手机淘宝的图标库全部下载下来 后来发现你们没有全选功能 只能一个个点

**Comment by purplebamboo** [comment]
你要把图标库全部下载下来？这个场景比较特殊，原则上我们是不打算提供这个功能的，亲。

后续我们商量下，如果没有啥版权的风险，可以考虑加一个 全选按钮。
