### ISSUE TITLE
购物车 新建项目保持时无项目名称

### ISSUE THREAD

**Issue by zoubingquan** [thx/iconfont-plus#160]
购物车 > 添加至项目 > 新建项目, 输入项目名称点击确定后图标保持至项目中, 在左侧项目库中没有显示项目名称

**Comment by purplebamboo** [comment]
亲  你是指创建了项目，结果看不到这个项目？
可以提供更具体的场景吗？ 我这边试了下这个链路没有问题啊。


点击确定后会跳到项目管理页面，左侧会显示新的项目的呀。
