### ISSUE TITLE
【功能请求】希望增加文件夹功能，管理图标。

### ISSUE THREAD

**Issue by koibi2** [thx/iconfont-plus#1604]
项目使用 Iconfont 有一段时间了。
图标越来越多，都放在一个目录下难以管理！
希望支持文件夹。A页面的图标可以放在A文件夹里。

![image](https://user-images.githubusercontent.com/34370367/80577810-1bf50480-8a3a-11ea-8178-7ecd2f9b9a28.png)

**Comment by yisibl** [comment]
亲项目 ID 多少？

**Comment by koibi2** [comment]
> 亲项目ID 多少？

1196713
