### ISSUE TITLE
我不知道我哪里出了问题，我的网页里不显示图标

### ISSUE THREAD

**Issue by Sleepy2Conscious** [thx/iconfont-plus#1606]
我试着分别用了Unicode和font-class，前者只显示了几个方块，后者什么也没显示，请问是否有具体的示例可以让我对比学习？
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
<link rel="stylesheet" href="../css/practise.css" type="text/css">

<title>login</title>
</head>
<body>
	<div class="form-wrapper">
		<div class="header">
			login
		</div>
		<div class="input-wrapper">
			<div class="border-wrapper">
				<input type="text" name="username" placeholder="username" class="border-item"/>
			</div>
			<div class="border-wrapper">
				<input type="password" name="password" placeholder="password" class="border-item"/>
			</div>
		</div>
		<div class="action">
			<div class="bin">login</div>
		</div>
		<div class="action">
			<div class="bin">no account?sign in</div>
		</div>
		<div class="icon-wraper">
			<i class="iconfont">&#xe603;</i>
			<i class="iconfont">&#xe603;</i>
            <i class="iconfont">&#xe603;</i>
            
		</div>
	</div>
</body>
</html>
![1589207458(1)](https://user-images.githubusercontent.com/57907150/81573486-266ab300-93d7-11ea-99de-f40743ec1d04.png)

![1589207513(1)](https://user-images.githubusercontent.com/57907150/81573587-400bfa80-93d7-11ea-9b97-9eb16fa6789b.png)

**Comment by yisibl** [comment]
请上传具体的demo链接，暂时关闭了。
