### ISSUE TITLE
我发起的项目, 我参与的项目 宽度太小了

### ISSUE THREAD

**Issue by nailao** [thx/iconfont-plus#161]
弄大点吧，项目名现在看到的字数太少了，最少看10个字吧！！！

**Comment by Muqing1221** [comment]
亲，你的建议我们会考虑，不过，首先我们能唠唠，你到底都是给项目起了什么名字啊，要10个字辣么长~~

方便举个例子么？因为就算不能显示10+个字的话，我们可以考虑展示关键部分关键信息。

**Comment by nailao** [comment]
其实我这边就是几个项目才超出字数，不过从整个界面来看，那地方宽度确实小了点
举个栗子：触屏版{项目名}1.0，
我自己改了下：
.page-manage-container .page-manage-left {width: 200px;}
.page-manage-container .page-manage-right {width: 232px;}
.page-manage-container .page-manage-left .block-left-nav .nav-container .nav-lists .nav-item {width: 135px;}
因为我的情况是发起的项目多，参与项目少的情况，所以我把高度也调整了下：
.page-manage-container .page-manage-left .block-left-nav .nav-container .nav-lists {max-height: 350px;}
我只是建议哦，希望Iconfont越办越好！ヾ(o◕∀◕)ﾉヾ          d(ﾟ∀ﾟd)点赞!

**Comment by Muqing1221** [comment]
谢谢亲~反正就是有大家的支持，我们才想把这个纯属为了有意思的事情坚持下去~~

很多时候，因为各种原因，我们对于大家的使用场景什么的，并不是炒鸡熟悉和兼顾（你懂的，用户style千千万~）希望亲持续反馈、吐槽和随便扯扯；怎么说我们都相信iconfont发展到最后是一个共建的社区平台...

跑题太远，总结下~~双十一忙完我们可以把日常优化提上议程了哦，我会好好考虑亲的痛点的，thank you again~~

**Comment by purplebamboo** [comment]
已加入我们的优化需求中
可以关注   https://github.com/thx/iconfont-plus/issues/139
