### ISSUE TITLE
无法上传镂空svg文件

### ISSUE THREAD

**Issue by junlvxin** [thx/iconfont-plus#1616]
![屏幕快照 2020-05-22 下午5 56 17](https://user-images.githubusercontent.com/26790556/82655981-8d992a80-9c55-11ea-9f38-f4d8d26ccafe.png)
无法上传同类型svg文件，镂空部分直接消失

**Comment by yisibl** [comment]
这是填充模式的问题，请提供 SVG 文件，统一到 https://github.com/thx/iconfont-plus/issues/1937 回复
