### ISSUE TITLE
上传svg是空白的?

### ISSUE THREAD

**Issue by chendeedee** [thx/iconfont-plus#1618]
sketch不管是切png还是svg上传到蓝湖,再下载svg,有些上传iconfont是可以的,有些上传却是空白的,到底是什么原因?
<img width="425" alt="WeChatadf8d4e746efc480b188f2c5f713d606" src="https://user-images.githubusercontent.com/65950082/82886431-175c3700-9f79-11ea-8d25-c47a8fed6ae7.png">

**Comment by ice-kylin** [comment]
同问

**Comment by jia1231** [comment]
同问。而且每次点上传第一遍是上传不了的，图标预览区一直在转圈，要刷新后再上传才能成功，然后再上传又转圈，再刷新，再转圈，再刷新，反正就是间隔一次再上传才成功

**Comment by CNCCAV1** [comment]
用AI弄，不要加任何效果

**Comment by yisibl** [comment]
统一到 https://github.com/thx/iconfont-plus/issues/1937 回复
