### ISSUE TITLE
为什么字体在ie8以下没法显示了

### ISSUE THREAD

**Issue by piaer** [thx/iconfont-plus#162]
@font-face {
  font-family: 'iconfont';  /* project id："180014" */
  src: url('//at.alicdn.com/t/font_527y8uxkw5h1if6r.eot');
  src: url('//at.alicdn.com/t/font_527y8uxkw5h1if6r.eot') format('embedded-opentype'),
  url('//at.alicdn.com/t/font_527y8uxkw5h1if6r.woff') format('woff'),
  url('//at.alicdn.com/t/font_527y8uxkw5h1if6r.ttf') format('truetype'),
  url('//at.alicdn.com/t/font_527y8uxkw5h1if6r.svg#iconfont') format('svg');
}
  

.iconfont {
    font-family: "iconfont";
    font-style: normal;
    cursor: default;
    -webkit-font-smoothing: antialiased;
}

之前不会呀，不知道为什么现在在ie8里面是空白的

**Comment by purplebamboo** [comment]
亲 我试了下  这个字体没问题啊，试了可以正常用的。

我怀疑你是不是本地跑demo直接用的这个cdn地址？那样的话记得把 `//`改成 `http://`。不然不会出来的哦。

如果本地跑demo，记得自己起一个服务器哈。不然就算你改了`http://`在ie9下也是会受eot同源策略影响导致不出来的。

**Comment by piaer** [comment]
之前的：![6b1eb529-718d-4faf-971a-92ad2e389d95](https://cloud.githubusercontent.com/assets/5241323/20291161/6173d106-ab1f-11e6-8610-ab5a05973e7b.png)

**Comment by piaer** [comment]
之前的：![6b1eb529-718d-4faf-971a-92ad2e389d95](https://cloud.githubusercontent.com/assets/5241323/20291165/6d9cd252-ab1f-11e6-8045-999eba72adbd.png)
现在的：
![273be75e-2a26-48f5-bb43-b4e09eb628f7](https://cloud.githubusercontent.com/assets/5241323/20291176/77d81ab0-ab1f-11e6-9a95-c84525c8d56a.png)
ie8的：
![360741bf428ed5bbff9818fe7d04133f](https://cloud.githubusercontent.com/assets/5241323/20291188/83d67fbe-ab1f-11e6-8182-54516a0131a4.jpg)
谷歌的：
![08647e13-7d4c-480c-a23c-e9dc1ce7503f](https://cloud.githubusercontent.com/assets/5241323/20291193/8dbad8a4-ab1f-11e6-88c7-28300c327159.png)
@purplebamboo

**Comment by purplebamboo** [comment]
你说的  之前的，应该是新平台生成的，现在的应该是老平台生成的吧。

现在是新平台生成的有问题是吗？

**Comment by FElxy** [comment]
今天我遇见了这个问题，解决方式是加上了?#iefix

**Comment by piaer** [comment]
的确，加多?#iefix这个就好了
![image](https://cloud.githubusercontent.com/assets/5241323/20291315/48008006-ab20-11e6-912e-e2f76f7e105e.png)

**Comment by purplebamboo** [comment]
sorry。这是个bug,感谢反馈，我这就去修复。项目里生成的unicode方式被转义漏掉这个了。

而生成font_class的引入css是正常的，我这就去修复。

**Comment by purplebamboo** [comment]
已经修复  感谢反馈～～ @piaer
