### ISSUE TITLE
微博和 Github 都无法登录

### ISSUE THREAD

**Issue by acathur** [thx/iconfont-plus#1628]
Github 授权后回调返回：

```json
{
  "code": "ECONNREFUSED",
  "message": "Error"
}
```

**Comment by shenxingchao** [comment]
对，登录不了

**Comment by zhhoo** [comment]
我也是无法登录

**Comment by clgg** [comment]
这么严重的问题居然这么久了还没修复

**Comment by rainvalley** [comment]
7月3日，仍然授权失败。

**Comment by QCChou** [comment]
昨天也是

**Comment by changlin93** [comment]
8月2日了依然授权失败，这是怎么回事

**Comment by shikelong** [comment]
无法登录+1. 这么明显的问题。 iconfont 是放弃外部用户了么？

**Comment by gggogogo** [comment]
+1

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖微博的三方登录。如果需遇到问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
