### ISSUE TITLE
使用symbol生成的js，报内存泄漏错误

### ISSUE THREAD

**Issue by cdZuo** [thx/iconfont-plus#163]
使用symbol生成的js，报内存泄漏错误

**Comment by purplebamboo** [comment]
亲 项目id给我下？  我排查下哈。

**Comment by moki0084** [comment]
http://www.iconfont.cn/plus/collections/detail?cid=1895
全部引入的时候,会报内存泄漏错误

**Comment by purplebamboo** [comment]
亲 你是说  把这个公共库里所有的  icon加到一个项目，再生成一个symbol。来使用会有内存泄漏？

**Comment by moki0084** [comment]
是的, chrome 版本 54.0.2840.99 m (64-bit)

**Comment by purplebamboo** [comment]
亲  我全部加入到项目测试了下。没有问题呀。

挨个加入购物车-》 生成项目-》 下载demo-》查看demo_symbol.html  

正常打开，正常使用呀。

**Comment by purplebamboo** [comment]
或者你把你使用的场景，也就是   项目当前的url  给我发一下。我查看下。

**Comment by moki0084** [comment]
当前项目是内网的,而且我升级了chrome,就不会再报错了,
chrome 版本 54.0.2840.99 m (64-bit) 和 手机uc国际版 demo_symbol.html就会报错的.
![](http://ww1.sinaimg.cn/large/0060lm7Tgw1fa7xeetwtlj30u01hc0yu.jpg)

**Comment by moki0084** [comment]
uc  国际版 版本号 11.0.5.850

**Comment by purplebamboo** [comment]
奥奥  因为symbol的方式是弄成一个字符串 通过js去写到页面里面的，估计图标多了会超出内存限制。

这个我优化下，还是改成异步加载文件吧，用js  异步的再发一次请求，请求一个svg集合。

本周应该可以优化完哈。

**Comment by lijunboy** [comment]
咋最后没有优化啊

**Comment by lijunboy** [comment]
像这个引用时还是内存泄漏啊[文件](http://at.alicdn.com/t/font_aqipmuflko2h85mi.js)
