### ISSUE TITLE
登录出问题

### ISSUE THREAD

**Issue by jie121** [thx/iconfont-plus#1632]
![image](https://user-images.githubusercontent.com/22954297/84341040-c2edc400-abd4-11ea-8476-94222badbad1.png)

**Comment by StringKe** [comment]
@purplebamboo github快捷登陆无法登陆

**Comment by qrqhuang** [comment]
同问

**Comment by edwardzhong** [comment]
邮箱也无法登录

**Comment by yisibl** [comment]
GitHub 由于墙的问题会不太稳定，不过我们现在已经支持手机登录了，不再依赖微博的三方登录。

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
