### ISSUE TITLE
Font class 模式下图标 css 命名空间的问题

### ISSUE THREAD

**Issue by sun-sheng** [thx/iconfont-plus#1634]
![image](https://user-images.githubusercontent.com/7367266/84730145-00cd5c80-afc8-11ea-8d42-113fe1a522b9.png)

图标的 css 类名都没有命名空间；为什么不用 ` .icon-font.danger:before` 的方式来声明呢

感觉这个比用字体项目设置里提供的 FontClass 前缀的方式更安全些

**Comment by yisibl** [comment]
我的项目→更多操作→编辑项目 中设置
![image](https://user-images.githubusercontent.com/2784308/84730812-d8466200-afc9-11ea-89c4-f8dbbed835b0.png)
