### ISSUE TITLE
编辑项目中的GUID怎么使用

### ISSUE THREAD

**Issue by guanjp** [thx/iconfont-plus#1636]
在编辑项目信息中，有个生成GUID，具体怎么用，没有找到文档

**Comment by yisibl** [comment]
通过 GUID 可以获取项目详情，这个目前是对内使用的，暂不对外开放。

**Comment by lichangwei** [comment]
@yisibl 能不能通过GUID提供一个无需登录就可以下载字体文件包的接口？这样就可以通过npm scripts下载字体文件了。

**Comment by Mjingling** [comment]
@yisibl 有同样的需求

**Comment by Laev** [comment]
私有化部署一个图标管理平台可能会是更好的方案，
但同时希望能够推出npm集成包或者开放GUID的使用，方便灵活更新部署图标

**Comment by cuihp** [comment]
> @yisibl 能不能通过GUID提供一个无需登录就可以下载字体文件包的接口？这样就可以通过npm scripts下载字体文件了。

vscode  插件 搜索  iconfont sync  可一键同步字体文件

**Comment by Mjingling** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
