### ISSUE TITLE
微博无法登陆，可以关联项目图标到github帐户上吗？

### ISSUE THREAD

**Issue by zhou-yg** [thx/iconfont-plus#164]
用户名：54雯子
微博帐户：349947775@qq.com

这个是我们设计用的帐户，现在微博不能登陆，可以关联一份到我当前这个github帐号上？

**Comment by Muqing1221** [comment]
@purplebamboo

**Comment by purplebamboo** [comment]
亲  zhou-yg  这个账号昵称我搜索不到。你新的github账号的昵称是什么，我可以帮你把项目全部转让过去。

**Comment by zhou-yg** [comment]
是不是我要先用github账号登陆了才能搜索到？ @purplebamboo

我刚刚才用github登陆了。😢

**Comment by purplebamboo** [comment]
项目已经都转让过去了哈，上传的图标暂时不能转哈，
