### ISSUE TITLE
由于之前微博帐号太久没有登录，现在登录后收是被收回了，iconfont里的项目帮忙转新注册的github里

### ISSUE THREAD

**Issue by wuyuliuhuan** [thx/iconfont-plus#1643]
@purplebamboo
由于之前的微博号太久没登录，被回收了，需要换到我新注册的github里，谢谢。
微博账号：332575132@qq.com 昵称：蓝枫-blue
github昵称：wuyuliuhuan
麻烦帮我把原先微博里面的项目关联到github 里

**Comment by yisibl** [comment]
Duplicate of #1718

**Comment by yisibl** [comment]
我们正在考虑实现新的账户系统

**Comment by yisibl** [comment]
请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
