### ISSUE TITLE
之前的微博无法登陆，可以关联项目图标到github帐户上吗？

### ISSUE THREAD

**Issue by wx302559815** [thx/iconfont-plus#165]
微博账号：wx302559815@sina.cn
github昵称：勿忘我
麻烦帮我把原先微博里面的项目关联到github 里

**Comment by Muqing1221** [comment]
@purplebamboo

**Comment by wx302559815** [comment]
@purplebamboo 
微博账号：wx302559815@sina.cn  昵称： wx302559815
github昵称：勿忘我
麻烦帮我把原先微博里面的项目关联到github 里

**Comment by purplebamboo** [comment]
可以的，我这就给你操作。

**Comment by purplebamboo** [comment]
属于你创建的项目，我已经全部转让给你新账号。“勿忘我”了。

剩下的一些项目不是你本人创建的，你让项目所有者添加你的新账号为协作者哈。

**Comment by wx302559815** [comment]
@purplebamboo  
谢谢啦

**Comment by wuyuliuhuan** [comment]
@purplebamboo
由于之前的微博号太久没登录，被回收了，需要换到我新注册的github里，谢谢。
微博账号：332575132@qq.com 昵称： 蓝枫-blue
github昵称：wuyuliuhuan
麻烦帮我把原先微博里面的项目关联到github 里
