### ISSUE TITLE
github账号丢失，阿里库无法登陆，里面上百个项目咋办

### ISSUE THREAD

**Issue by DUOFRIEND** [thx/iconfont-plus#1653]
**github账号丢失，阿里库无法登陆，里面上百个项目咋办**

**Comment by yisibl** [comment]
如果需要找回老账号遇到问题，请加一下钉钉答疑群

![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
