### ISSUE TITLE
XXX Github 登录失败 求解决

### ISSUE THREAD

**Issue by DevLive2016** [thx/iconfont-plus#1654]
在线等 =>急

**Comment by DevSoft2016** [comment]
{"code":"ECONNREFUSED","message":"Error"}

**Comment by yisibl** [comment]
GitHub 由于墙的问题会不太稳定，不过我们现在已经支持手机登录了，不再依赖微博的三方登录。

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
