### ISSUE TITLE
图标过多的时候，一直提示下载失败

### ISSUE THREAD

**Issue by lzxb** [thx/iconfont-plus#166]

**Comment by Muqing1221** [comment]
@purplebamboo

**Comment by purplebamboo** [comment]
亲  场景能更清楚点不，是项目纬度下下载字体吗？

如果是项目的场景，提供下项目id。或者地址哈。

**Comment by lzxb** [comment]
抱歉！系统繁忙，
暂时无法处理您的请求……

**Comment by lzxb** [comment]
/plus/manage/index?manage_type=myprojects&projectId=181010

**Comment by purplebamboo** [comment]
亲  你好，排查了下，不是图标多了下载不了，而是你项目里有个icon（html5）的unicode被你设置为了 1.

这不是个合法的unicode。所以生成字体出错，我帮你设置为了e600哈。现在可以使用了。

unicode设置是有讲究的，尽量设置为e600及以上哈。

**Comment by lzxb** [comment]
谢谢亲
