### ISSUE TITLE
账号丢失

### ISSUE THREAD

**Issue by junlvxin** [thx/iconfont-plus#1675]
微博账号无法登陆需要扫描二维码登陆，因为之前微博注销过，使用二维码登录后是全新的用户属性，之前建立的项目都丢失了，希望可以帮忙解决。

iconfont账户名称：CCxiiiiiiii

**Comment by qxsung** [comment]
我的也是，用的github帐号

**Comment by qxsung** [comment]
不过在资源管理-我的项目 里面可以找到

**Comment by wurina92** [comment]
您好。我的微博账号不用了。微博授权登录的。所以现在账号登不上去了怎么办呀

**Comment by minthan** [comment]
使用公司邮箱，现在邮箱被注销了，项目还在但是无法进去管理了

**Comment by yisibl** [comment]
Duplicate of #1718
