### ISSUE TITLE
上传svg报错啊

### ISSUE THREAD

**Issue by jiangwei1995** [thx/iconfont-plus#1676]
![image](https://user-images.githubusercontent.com/9276313/88543491-9c7fcd00-d04a-11ea-9d3e-e07dfadf6645.png)

**Comment by yisibl** [comment]
请提供一下出错的 svg 文件

**Comment by mjiang1000** [comment]
昨天开始就上传图标就失败了。插画可以。

**Comment by mjiang1000** [comment]
附件文件上传失败

**Comment by mjiang1000** [comment]
昨天开始就上传图标就失败了。插画可以。

**Comment by yisibl** [comment]
麻烦再试一下，修复了

**Comment by jdh8088** [comment]
可以了 辛苦@伊西卜

**Comment by jiangwei1995** [comment]
好的，UI试了一下，昨天上传不了的都可以了 @yisibl
