### ISSUE TITLE
上传svg图标，多个出现报错或者显示不出来的情况

### ISSUE THREAD

**Issue by Lydiaaaa** [thx/iconfont-plus#1677]
sketch导出的svg图标，今天上传时候，很多出现报错或者显示空白、显示不出来的状态。
所有轮廓化过的单色闭合图形，上传后变成空白，甚至我用两个圆形合并后的图形上传也显示不出来；
复合颜色的图标上传全都报错。

前两天可以正常上传的图标，再次上传时也出现有的正常有的报错有的空白的情况，麻烦是否可以尽快看下

**Comment by yisibl** [comment]
请提供一下出错的 svg 文件

**Comment by Lydiaaaa** [comment]
您好，这三个图标中，icon1正常，icon2提示报错，icon3显示空白。其中1和2都是之前的老图标，之前上传都是正常的
[icon.zip](https://github.com/thx/iconfont-plus/files/4982753/icon.zip)

**Comment by yisibl** [comment]
好的 我看一下

**Comment by iHaPBoy** [comment]
@yisibl 同遇到这个问题，从7月27日开始，SVG上传大部分文件都出错或空白，包括以前上传成功的老文件，现在上传都出错或空白了。

**Comment by shinian156** [comment]
同上

**Comment by Free-aiqian7** [comment]
同上，草图上传空白，出错

**Comment by jdh8088** [comment]
同上

**Comment by vesionbook** [comment]
同上，sketch文件导出的svg，拖入AI后，另存为svg可以解决，但这个办法增加了很多没必要的工作量

**Comment by jdh8088** [comment]
直接用AI做的icon导出来都是错误的，看到你的解决方法我急忙导出来有放进去重新导一遍，结果还是一样❗

**Comment by yisibl** [comment]
感谢大家的反馈，正在解决

**Comment by yisibl** [comment]
麻烦再试一下，修复了
