### ISSUE TITLE
项目协作功能中搜索的用户是外星人吧 ..  -_-|| 

### ISSUE THREAD

**Issue by raisezhang** [thx/iconfont-plus#168]
Hi  @Muqing1221  帐号已经尝试过 weibo  和 github 的， 在项目中添加成员一直搜索不到...  

求救~        
 
![image](https://cloud.githubusercontent.com/assets/1481983/20264196/4834f7f8-aaa5-11e6-9fdb-cd83a629c63c.png)

**Comment by Muqing1221** [comment]
你是要加小伙伴，然后加不了？
你要搜索的是小伙伴用的nickname哦

**Comment by purplebamboo** [comment]
把昵称提供下？  我们看看是不是 真的搜不到哈。

**Comment by raisezhang** [comment]
哦     weibo的一直不成功（帐号：zhangqian_css），    github 的有延时，差不多1小时左右手贱又试了下，竟然搜到了...      

建议把 昵称这个词换成 用户名吧...

**Comment by purplebamboo** [comment]
我这边搜了下  weibo的也可以搜索到哎，是不是亲  网速不好？

**Comment by raisezhang** [comment]
@purplebamboo   饿    刚刚又试了下我自己的weibo号，发现可以了      尝试我们设计同学的微博帐号，还是搜不到...    

![image](https://cloud.githubusercontent.com/assets/1481983/20294453/36109db8-ab39-11e6-8c19-05b7d8fab85f.png)

是不是你偷偷加的我帐号 -_- 
![image](https://cloud.githubusercontent.com/assets/1481983/20294409/f99b09c2-ab38-11e6-9cb5-37a9ec6d1884.png)

**Comment by purplebamboo** [comment]
真没有，是不是你们设计师没登陆过，我们搜索的是登陆后的账号哈。让他先登陆下，还搜不到，就取一个特殊的昵称好了。

**Comment by raisezhang** [comment]
好吧 ~    多谢了   不纠结了 ...
