### ISSUE TITLE
图标改色后”复制SVG“功能，颜色无效，依然是原色

### ISSUE THREAD

**Issue by TangTank** [thx/iconfont-plus#1682]
今天使用时，发现复制SVG不论修改什么颜色，都是图标原色，最近Iconfont有更新吗？

**Comment by yisibl** [comment]
麻烦再试一下，修复了

**Comment by yisibl** [comment]
感谢反馈，我看一下。

**Comment by zhangliganggm** [comment]
是的，我也遇到了， 所有元素都没fill了。 都是我手动自己加fill="#ffffff"，，，求速度修复

**Comment by wenyixinn** [comment]
bug还在= =

**Comment by TangTank** [comment]
临时解决办法，复制SVG后，在path标签中增加属性 style="fill:你要的颜色"

**Comment by TangTank** [comment]
> bug还在= =
临时解决办法，复制SVG后，在path标签中增加属性 style="fill:你要的颜色"

**Comment by yisibl** [comment]
已修复，感谢反馈。

**Comment by vincentw3** [comment]
替换 icon 后的 SVG 颜色还是无法更改，还是带有 fill  求修复
