### ISSUE TITLE
上传的图形圆角弧度自动发生改变

### ISSUE THREAD

**Issue by yitao2020** [thx/iconfont-plus#1687]
#832 
<img width="444" alt="截屏2020-07-31 上午10 05 50" src="https://user-images.githubusercontent.com/68892089/88992282-9113f680-d315-11ea-92d1-9ec30c939cb9.png">
![截屏2020-07-31 上午10 05 35](https://user-images.githubusercontent.com/68892089/88992292-95d8aa80-d315-11ea-8fcc-466569a60949.png)

**Comment by JULYsun** [comment]
楼上，你在制作图标的时候需要把路径拼合。图标缩放时 radius 你可能设置为了不跟随缩放

**Comment by JULYsun** [comment]
> #832
> <img alt="截屏2020-07-31 上午10 05 50" width="444" src="https://user-images.githubusercontent.com/68892089/88992282-9113f680-d315-11ea-92d1-9ec30c939cb9.png">
> ![截屏2020-07-31 上午10 05 35](https://user-images.githubusercontent.com/68892089/88992292-95d8aa80-d315-11ea-8fcc-466569a60949.png)

你在制作图标的时候需要把路径拼合。图标缩放时 radius 你可能设置为了不跟随缩放

**Comment by yitao2020** [comment]
> 楼上，你在制作图标的时候需要把路径拼合。图标缩放时 radius 你可能设置为了不跟随缩放

我使用sketch制作的。请问radius这个参数在哪里设置？

**Comment by yisibl** [comment]
请提供源文件

**Comment by JULYsun** [comment]
图层-路径-拼合

**Comment by EWL0829** [comment]
请问楼主在进行拼合之后，这个问题有解决掉吗？
