### ISSUE TITLE
微博账号登录 希望可以在设置中关联 github账号，这样可以多种方式登录，避开微博的限制

### ISSUE THREAD

**Issue by xflihaibo** [thx/iconfont-plus#1689]

**Comment by yisibl** [comment]
手机注册登录功能已经上线，详见：
https://mp.weixin.qq.com/s?__biz=Mzg5OTUzNjQ0Mg==&mid=2247483866&idx=1&sn=e6d02ca84cba8157c8f90d072db66bbf&chksm=c050828ff7270b99b00d784681a47fb4d1063a9139732075dc84d8da4ad77d446df386384acc&token=1155149842&lang=zh_CN#rd

相关 issue：#1718
