### ISSUE TITLE
关于图标的排序问题强烈希望改进

### ISSUE THREAD

**Issue by xiemin2161** [thx/iconfont-plus#169]
由于没有图标排序功能，功能相近的图标不能靠在一起显示，完全乱序显示了，导致找图标的时候很累，举例：我有一整套图标，找到其中的开关打开按钮图标，但是发现开关关闭按钮并不在其左边或者右边，要找到开关关闭按钮需要重新搜索，或者重新翻找，很是麻烦，特别是一个库有上千图标的时候，找起来就不用说了。强烈要求增加图标按名称排序功能，比如我事先在图标前面编号，这样找图标的时候，相似功能或者同一类图标就会出现在一起，这样找起来就很方便了。

**Comment by purplebamboo** [comment]
嗯  明白，这个可以有。亲的场景主要是 图标库详情页吗？

我们可以做个功能，在图标库详情，根据 时间，或者名称排序。

**Comment by purplebamboo** [comment]
这个 我先记下来，在我们的优化需求里，讨论下。

https://github.com/thx/iconfont-plus/issues/139
