### ISSUE TITLE
【功能请求】希望增加通过搜索到的图标，查看所属图标库的功能

### ISSUE THREAD

**Issue by OrdarkYin** [thx/iconfont-plus#1695]
原因：一般开发中都需要用到的是一整套一致性的图标库 而不是某一个图标
现状：只能搜索图标库的名称 || 只能搜索单个图标
诉求：希望能够在搜索单个图标的结果集中，展示或者可进入其所属的图标库

**Comment by Jitlee** [comment]
+1

----
阿里帝国

**Comment by Wangnov** [comment]
目前可以通过点击下载按钮，在下载页内查看到单个图标所属的图标库
