### ISSUE TITLE
github登录失败

### ISSUE THREAD

**Issue by JackyQ-developer** [thx/iconfont-plus#1698]
{"code":"ECONNREFUSED","message":"Error"}

**Comment by got991** [comment]
我也一样

**Comment by idzyr** [comment]
我也是

**Comment by shijue98** [comment]
我也是, 一样, 现在项目都进不去了,

**Comment by idzyr** [comment]
> 我也是，一样，现在项目都进不去了，

多试几次就好了。我这边就是这样的情况。

**Comment by yisibl** [comment]
GitHub 由于墙的问题会不太稳定，不过我们现在已经支持手机登录了，不再依赖微博的三方登录。如果需要找回老账号遇到问题，请加一下钉钉答疑群

![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
