### ISSUE TITLE
希望个人主页可以再丰富一点和加上关注别人的功能

### ISSUE THREAD

**Issue by suhehe** [thx/iconfont-plus#17]
好像甚至没有个人主页这个概念？只有xx的图标。感觉加上会更好，还有增加关注别人的功能。反正就是增加类似dribbble站酷这类作品展示平台的社交功能，但是作品只能是矢量图标

**Comment by Muqing1221** [comment]
谢谢亲的建议~关于follow others这个功能，我们在计划中呢~~期待不久之后上线~把互动分享交流的精神贯彻到底~~
