### ISSUE TITLE
well...when i login in github with iconfont,that print in screen {"code":"ECONNREFUSED","message":"Error"}(This issue be used for chat,Chinese please send 1,English please send 2)

### ISSUE THREAD

**Issue by got991** [thx/iconfont-plus#1711]
<img width="919" alt="github1" src="https://user-images.githubusercontent.com/67494671/90201215-c720a280-de0c-11ea-83d1-b85f465ad678.PNG">
<img width="338" alt="github2" src="https://user-images.githubusercontent.com/67494671/90201267-f8996e00-de0c-11ea-8cbe-3309818e24ed.PNG">
then  {"code":"ECONNREFUSED","message":"Error"}

**Comment by got991** [comment]
so why?

**Comment by got991** [comment]
well...i'm restart the Microsoft Edge and it's fixed,but why?????

**Comment by got991** [comment]
好吧，为什么？？？？？

**Comment by got991** [comment]
good bye

**Comment by got991** [comment]
Close issue

**Comment by got991** [comment]
And Reopen

**Comment by got991** [comment]
中文请发1
英文请发2
Chinese please send 1
English please send 2

**Comment by got991** [comment]
1

**Comment by yisibl** [comment]
之前的 GitHub 等三方登录会偶尔被墙，现在我们支持直接手机登录了。

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
