### ISSUE TITLE
登录账号绑定github或手机号码

### ISSUE THREAD

**Issue by zyp1573** [thx/iconfont-plus#1712]
由于微博修改了网页登录的流程，以至于每次登录都推荐扫码来登录，虽仍可以点击图标来进行账号密码登录，但刚刚反复多次输入账号密码时仍跳回扫码页，不能正常登录，因为微博客户端广告繁多且集成很多我用不到的功能，所以我使用的是微博国际版手机客户端，该手机客户端不能扫码登录到本站，所以希望在微博登录后可以在个人中心进行账号绑定其他登录方式，如github账号或手机号码。

**Comment by yisibl** [comment]
手机注册登录功能已经上线，[点击查看](https://mp.weixin.qq.com/s?__biz=Mzg5OTUzNjQ0Mg==&mid=2247483866&idx=1&sn=e6d02ca84cba8157c8f90d072db66bbf&chksm=c050828ff7270b99b00d784681a47fb4d1063a9139732075dc84d8da4ad77d446df386384acc&token=1155149842&lang=zh_CN#rd)

相关 issue：#1718

**Comment by zyp1573** [comment]
已经绑定啦，好棒！
