### ISSUE TITLE
关于 添加 相同 icon 后 ， code 码变化的问题

### ISSUE THREAD

**Issue by zhaoyangsoft** [thx/iconfont-plus#172]
从A项目添加一个 icon i1  到B 项目； 再次 同样的步骤，i1 在B 项目中的 code码会变的不一样, 第三次 同样的步骤  则会变成第一次的code 码
![image](https://cloud.githubusercontent.com/assets/1456421/20331768/8325e686-abe2-11e6-98e2-a4016bb3824a.png)

**Comment by purplebamboo** [comment]
这是个bug。

目前iconfont的项目code逻辑是。
* 添加icon，优先尝试用自己的code
    * 如果发现项目里没有图标，那么直接用这个unicode
    * 发现项目里有这个unicode，那么就自己不停加1，一直到没有冲突为止。

发生上面的问题是因为：
* 第一次加入用自己的unicode，比如是 e71d,正常。
* 第二次加入，发现已经有e71d，就会加1变为e71e。
* 第三次，又发现不会冲突，会再次变成e71d。

主要的问题，是项目里已有的icon不应该改变unicode。这个icon只要在项目里，就不应该再次修改unicode。而再次添加的图形什么的都应该按照最新的来。


这个bug，我今天晚上修复哈。


感谢反馈。

**Comment by purplebamboo** [comment]
已经改成  已有icon不会被修改unicode了哈。

**Comment by zhaoyangsoft** [comment]
ok, 多谢
