### ISSUE TITLE
能不能增加其他的登录方式？微博太恶心了

### ISSUE THREAD

**Issue by ctocode** [thx/iconfont-plus#1722]
微博登录，还一定要客户端扫码，我不玩微博登录都不行吗？github那么慢，登录个锤子

**Comment by ctocode** [comment]
微博登录，还一定要客户端扫码，我不玩微博登录都不行吗？github那么多，登录个锤子

**Comment by makuntech** [comment]
这个我反映多次了，在他们的公众号下也说过，没人鸟。估计这个就是他们内部的一个产品，主要给阿里内部用

**Comment by yisibl** [comment]
我们正在考虑实现新的账户系统

Duplicate of #1718
