### ISSUE TITLE
iconfont 改版后之前创建项目数据丢失

### ISSUE THREAD

**Issue by also1024** [thx/iconfont-plus#1748]
我的收藏。我的项目数据全部丢失，只能看到下载历史，所以其他的项目文件去哪了？

iconfont昵称：全栈Dev

登录方式： 微博

**Comment by ctforcp** [comment]
官方有人来不 愁死我了 我的线上项目图标丢失了好多个，能不能帮忙恢复下

**Comment by yisibl** [comment]
@also1024 丢失的项目 id 或者名称发一下

**Comment by also1024** [comment]
@yisibl  所有项目都不在了，这个我肯定不知道项目ID和名称的。

**Comment by also1024** [comment]
@ctforcp  看来不是只有我一个人丢失项目的图标，真是服气了~

**Comment by yisibl** [comment]
Duplicate of #1718
