### ISSUE TITLE
强烈建议增加多库下载自动分类功能

### ISSUE THREAD

**Issue by xiemin2161** [thx/iconfont-plus#175]
现在想下载多个库的文件，需要把所有文件放到我的1个项目中，然后下载至本地
这样图标无法做到分类，很不明了，而且上次也提过了，图标没有排序，所有图标都是乱序排列的
这样下载下来的文件，图标很乱，找个图标要找半天
希望增加多库下载自动分类功能
举个例子
比如我有2个库
1个是箭头类图标库
1个是天气类图标库
我同时选中2个库（类似于直接选择文件夹，而不是进入库后一个一个选图标），点击下载至本地，这时需要下载的2个库的所有图标会合并成1个svg，并且demo.html中会对2个库的文件分类显示，分别显示2个库的图标
最后再提一点，现在下载一个库到本地很累，因为我要收集一整套图标可能有好几百甚至上千，现在需要一个一个加入购物车，然后在生成，如果增加整库添加就会方便很多，同时希望增加鼠标框选添加功能，就是对鼠标框选住的图标添加到购物车
我想上面2个功能实现后，网站使用将会大大提高效率，强烈希望能采纳。

**Comment by Muqing1221** [comment]
谢谢亲的建议

只是产品就是产品，不是dream-maker，我们了解了您的需求，在以后的日常优化中，会考虑的，谢谢。

**Comment by purplebamboo** [comment]
统一在这里吧，我们需要先评估下哈。建议很好，感谢。

https://github.com/thx/iconfont-plus/issues/139
