### ISSUE TITLE
建议增加自己的用户体系

### ISSUE THREAD

**Issue by Taihuiliu** [thx/iconfont-plus#1755]
垃圾微博，无缘无故就把账号给封停了，还没地方申诉。以前的项目就都找不到了，非常麻烦。

**Comment by yisibl** [comment]
考虑中

**Comment by yisibl** [comment]
感谢您的建议，使用手机注册登录的自有账户体系已经上线，[点击查看](https://mp.weixin.qq.com/s?__biz=Mzg5OTUzNjQ0Mg==&mid=2247483866&idx=1&sn=e6d02ca84cba8157c8f90d072db66bbf&chksm=c050828ff7270b99b00d784681a47fb4d1063a9139732075dc84d8da4ad77d446df386384acc&token=1155149842&lang=zh_CN#rd)

相关 issue：#1718
