### ISSUE TITLE
为什么不能新建图标库了？好多天了

### ISSUE THREAD

**Issue by haimianz** [thx/iconfont-plus#1756]
点击新建图标库之后一直是等待状态，但是首页有当天更新的图标库，是不是这个功能对阿里内部开放了？

**Comment by jdh8088** [comment]
已经发现很久了，自从图标库改版增加插画功能以来就动不动出BUG了，应该是所用过阿里产品用户体验相对较弱的一款产品了，期待改进

**Comment by yisibl** [comment]
已经修复。感谢对 iconfont 的支持，我们一定努力做的更好。
