### ISSUE TITLE
使用affinity designer 导出SVG后 显示错误

### ISSUE THREAD

**Issue by nujiakk** [thx/iconfont-plus#1763]
使用affinity designer 输出的SVG上传后 部分无法正常显示.可以识别到轮廓,但是全部填充了背景色
![111](https://user-images.githubusercontent.com/24282937/93868724-777fa180-fcfd-11ea-93de-3fbdc3b9ddc4.png)
![222](https://user-images.githubusercontent.com/24282937/93868737-7b132880-fcfd-11ea-8aef-06f7af904c7c.png)
![333](https://user-images.githubusercontent.com/24282937/93868744-7e0e1900-fcfd-11ea-87aa-4ef90981f644.png)
![444](https://user-images.githubusercontent.com/24282937/93868747-7fd7dc80-fcfd-11ea-9c17-b7ab6a487a3e.png)

**Comment by nujiakk** [comment]
这个是错误的SVG

[用户.zip](https://github.com/thx/iconfont-plus/files/5260575/default.zip)

**Comment by iceyu-zy** [comment]
看了下你的源文件，发现导出的svg打开来就是被填充了颜色的，应该是你输出svg文件的时候就出错了

**Comment by nujiakk** [comment]
[用户22.zip](https://github.com/thx/iconfont-plus/files/5283926/22.zip)


> 看了下你的源文件，发现导出的svg打开来就是被填充了颜色的，应该是你输出svg文件的时候就出错了

我又重新导出了一次   重新上传  依然是错误的.  用affinity designer打开是正常的  没有多余的颜色填充. 
如果是导出的文件有问题  为什么另外那个提包的就显示正常

**Comment by yisibl** [comment]
字体图标中需要对路径进行路径合并的布尔操作，例如在 Sketch 中，我们选中需要合并的图层，点击「减去顶层」即可。

![image](https://user-images.githubusercontent.com/2784308/100301887-224d5e00-2fd4-11eb-8c10-71cf50b48510.png)

Affinity designer 中是否支持或者如何操作需要您自己尝试哈。推荐使用 AI 或者 Sketch 制作字体图标。

**Comment by nujiakk** [comment]
> 字体图标中需要对路径进行路径合并的布尔操作，例如在 Sketch 中，我们选中需要合并的图层，点击「减去顶层」即可。
> 
> ![image](https://user-images.githubusercontent.com/2784308/100301887-224d5e00-2fd4-11eb-8c10-71cf50b48510.png)
> 
> Affinity designer 中是否支持或者如何操作需要您自己尝试哈。推荐使用 AI 或者 Sketch 制作字体图标。
> 
> [修复后@2x.svg.zip](https://github.com/thx/iconfont-plus/files/5600165/%402x.svg.zip)

那个手提包的  做法跟另外两个是一样的,那个是正常的.  我就是好奇这个啊.

**Comment by yisibl** [comment]
检查路径，按照上述操作应该就不会有问题了。
