### ISSUE TITLE
下载需要微博登录时，选择密码登录后还是需要扫码

### ISSUE THREAD

**Issue by yoiyoi95** [thx/iconfont-plus#1765]
下载需要微博登录时，选择密码登录后还是需要扫码，觉得很不方便，既然填写已经填写密码登录了，还要扫码，在手机不在身边时很不方便，希望能直接登录

**Comment by kinseydesign** [comment]
dui ,很傻屌的操作，能不能正常点

**Comment by yisibl** [comment]
Duplicate of #1718
