### ISSUE TITLE
时间：2016-11-16，不能更新外链地址，一直提示error

### ISSUE THREAD

**Issue by zhaozailin** [thx/iconfont-plus#177]
http://www.iconfont.cn/api/project/cdn.json 请求302

**Comment by purplebamboo** [comment]
服务器出了点问题，应该已经恢复了哈。

**Comment by zhaozailin** [comment]
现在下午7点39分了，仍然报错，已清理缓存、重新登录

**Comment by purplebamboo** [comment]
项目id 给我下？

**Comment by zhaozailin** [comment]
http://www.iconfont.cn/plus/manage/index?manage_type=myprojects&projectId=60260

**Comment by purplebamboo** [comment]
亲 看一下你最新加入的一个  icon.叫做 凭证模板的。他的unicode怎么是nan？ 这是不合法的unicode。你把这个删除就可以了哈。
后续，我们考虑错误提示信息丰富点。

**Comment by zhaozailin** [comment]
多谢了！
