### ISSUE TITLE
不能下载字体文件了啊！！！

### ISSUE THREAD

**Issue by hmczju** [thx/iconfont-plus#178]

**Comment by purplebamboo** [comment]
是什么场景？ 如果是  项目的话  提供下项目id哈。

**Comment by hmczju** [comment]
项目ID哪里看？我就是项目图标不可以下载，其他都可以下载

**Comment by purplebamboo** [comment]
把 当前url地址整个复制过来。

**Comment by hmczju** [comment]
projectId=175242我的链接中有这个参数

**Comment by hmczju** [comment]
http://www.iconfont.cn/plus/manage/index?manage_type=myprojects&projectId=175242&keyword=

**Comment by purplebamboo** [comment]
项目里有个icon  是收藏  未收藏  这个icon的unicode被你设置成了  7哈。这不是个合法的unicode，生成字体的时候会有问题的，你把它删除，或者修改下修改成  e601之类的。

**Comment by purplebamboo** [comment]
后续  我们还是加一些   提示吧，可能普通用户不是太清楚  unicode的设置范围。

你这个unicode是你自己设置的吗？

**Comment by hmczju** [comment]
这个Unicode不是我设置的，我没有设置过，我就是添加到项目操作，然后点下载下载不了，我现在删除重新添加了一下，下载好了，谢谢了

**Comment by purplebamboo** [comment]
解决就好，那就是原始图标有问题，这个我去排查下。看源头是哪里。

**Comment by purplebamboo** [comment]
我这边处理下，如果是 有问题的unicode  加入到项目后会给一个默认的值，今晚上线哈。
