### ISSUE TITLE
账号

### ISSUE THREAD

**Issue by 13068240601** [thx/iconfont-plus#1780]
登陆新浪之后能不能绑定github,新浪账号经常忘记密码

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖三方登录。如果需要找回老账号遇到问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
