### ISSUE TITLE
新版问题一堆，项目转让，直接整个项目消失了！！！

### ISSUE THREAD

**Issue by zqjilove** [thx/iconfont-plus#179]
1、项目转让，项目直接消失，项目管理里没有显示出来

这种BUG，，真是无语啊

**Comment by purplebamboo** [comment]
亲 不要急。  

项目id给我下，我看下问题。或者项目名称。

项目转让直接消失是指？

转让后会出现在  我转让的项目   这个下面哈。

最多只能添加两个人？ 这也不应该啊，这些功能我们都测试过的。

应该是你这边的个例。你可以尝试下同事的电脑？

**Comment by zqjilove** [comment]
项目ID没有记住。项目名称为game  ，项目转让者的用户名为：秋天里的阿农。 

由于项目消失，已经重建了这个项目。不知道现在还能否查询，或者已经覆盖了信息。

**Comment by zqjilove** [comment]
没结果？ 整个项目的图标，几十个，加到吐血，包括自己上传的。也没看到我转让的项目里有信息。

**Comment by purplebamboo** [comment]
sorry 亲，iconfont比较是我们业余时间搞的，我们还是要以本职工作为主。

我排查了下，项目还在的哈，不要担心，我已经帮你弄到  秋天里的阿农 这个昵称下面了。

要添加协作者的话，可以在这个下面添加。

然后就是，能复述下的你的操作路径吗？有没有特殊的操作，或者是不是有同时两个人在操作。

现在看数据比较怪，项目其实正常转过去了，但是添加的中间协作者有问题。出现了脏数据。

**Comment by zqjilove** [comment]
首先表示感谢，已经找回项目了。操作路径没什么特别的，就是添加协作成员没成功，选择了项目转让，之后就出问题了。没办法完全还原操作情景，抱歉。

**Comment by purplebamboo** [comment]
好的  我再想想  可能是比较隐蔽的bug。这个issue我就先关掉了。

**Comment by asd123456987** [comment]
我的也是，项目丢失了
