### ISSUE TITLE
快醒醒，你们的网站挂了，下载的字体都是小方块

### ISSUE THREAD

**Issue by godRetr** [thx/iconfont-plus#1793]
快醒醒，你们的网站挂了，下载的字体都是小方块

**Comment by godRetr** [comment]
我新加了几个图标，下载后所有的图标都变成小方块，我试了下把新加的删了，重新再来又变正常了

**Comment by godRetr** [comment]
![企业微信截图_16052347222537](https://user-images.githubusercontent.com/27680656/99022414-a566c100-259d-11eb-93c6-0a116545c950.png)

**Comment by yisibl** [comment]
请重新检查图标是否没问题。
