### ISSUE TITLE
账户问题

### ISSUE THREAD

**Issue by Ehzuiq** [thx/iconfont-plus#1797]
能不增加个修改账号登陆方式的功能，绑定的微博账号已经停用了

**Comment by 404com** [comment]
是的，非常刚需这个功能，实在不想用微博登录，太恶心微博这个软件了，手机实在不想留

**Comment by yy641956686** [comment]
我的微博账号已经用不了了，我之前使用的iconfont找不到了。有什么方法可以找回之前的iconfont吗？

**Comment by huaigit** [comment]
同求，微博账号突然被锁住了，之前的所有iconfont 都找不到了！！！

**Comment by yisibl** [comment]
Duplicate of #1718

**Comment by yisibl** [comment]
我们正在考虑实现新的账户系统
