### ISSUE TITLE
其中一个项目的字体包下不下来！急！在线等！

### ISSUE THREAD

**Issue by shenjiejun** [thx/iconfont-plus#180]

**Comment by purplebamboo** [comment]
项目id给我下

亲  可以先尝试自己排查下，这种情况应该是其中某些icon不规范导致的。
可以尝试删除最新加入的几个icon。

**Comment by shenjiejun** [comment]
我删掉了最近添加的，再下载，还是不行
http://www.iconfont.cn/plus/manage/index?manage_type=myprojects&projectId=13256&keyword=

**Comment by shenjiejun** [comment]
我删掉了最近添加的，再下载，还是不行
http://www.iconfont.cn/plus/manage/index?manage_type=myprojects&projectId=13256&keyword=

2016-11-17 10:43 GMT+08:00 purplebamboo <notifications@github.com>:

**Comment by purplebamboo** [comment]
排查了下  ，项目里有个图标icon_wallet   用的unicode有问题哈。是非法的unicode。

我帮你修改了哈，已经可以了。


是这样的亲，unicode我们建议是用e600这样往后排的哦。项目里的unicode是你们自己设置的吗？因为经常会出现非法的unicode。

稍后我们会把报错信息提供出来，让用户更方便排查哈。


以后遇到这种问题，可以直接把前xx个图标添加到一个新项目看看是不是有问题，就可以排查出这个问题图标了。

**Comment by shenjiejun** [comment]
这样啊 那我想问一下 您说的非法unicode是指？什么算非法？

**Comment by purplebamboo** [comment]
unicode 倒也不是非法不非法的问题。
iconfont平台也是依赖的第三方的c库 fontforge来生成字体的，如果unicode不符合规范，它会报错的。
主要有些unicode是不能有文字的。

关于具体的unicode的知识特别多。其实unicode是有几个平面给用户用的。

具体参考这里：https://en.wikipedia.org/wiki/Private_Use_Areas

unicode其实没有特别的规定。

字体有几个私有平面:
![ddd](http://alp.alicdn.com/1471381668684.png)

很早以前我们使用的五位数的，结果现在chrome支持不太好，后面建议大家使用第一个平面里的。

这样用的好处是，字体没有加载的时候，显示的是一个框 口。而不是乱码。

我们平台建议的unicode是   e600往后排，足够用户使用了。基本不会有问题。

**Comment by shenjiejun** [comment]
好的~我知道啦！非常感谢！
