### ISSUE TITLE
关于Affinity Designer导出的SVG上传不正常的问题

### ISSUE THREAD

**Issue by nujiakk** [thx/iconfont-plus#1800]
前段时间已经提交了两次ISSUE,今天又试了一下 还是没解决
![003](https://user-images.githubusercontent.com/24282937/100301009-2d9f8a00-2fd2-11eb-9b1c-35974fa29cb8.png)
这个是Affinity Designer源图↑
![001](https://user-images.githubusercontent.com/24282937/100301038-414af080-2fd2-11eb-8aa0-33240f1c06d3.png)
这个是在CHROME下打开的样子 ↑
![002](https://user-images.githubusercontent.com/24282937/100301062-4f990c80-2fd2-11eb-831d-86c7a5ab65cf.png)
这个是上传后的样子 ↑

[无题.zip](https://github.com/thx/iconfont-plus/files/5600119/default.zip)
附:导出的svg

**Comment by yisibl** [comment]
请不要重复提交问题，在 #1763  下统一处理。
