### ISSUE TITLE
ICON网格大小职能固定的16-64，为什么不能自由调整

### ISSUE THREAD

**Issue by XYFZ-G** [thx/iconfont-plus#1805]

**Comment by yisibl** [comment]
网格只是辅助作用，通常图标是 16x16px，所以以这个为基础。

**Comment by XYFZ-G** [comment]
> 网格只是辅助作用，通常图标是16x16px，所以以这个为基础。

你是官方人员吗····网格可不是辅助这么简单，是决定字体图标缩放比例和模糊度的一个重要工具，官方给出16-64估计是按照N.5的倍数来或者其他缩放倍率规则制定。但是并不能覆盖所有，当按照16PX绘制图标或者按照官方给出的模板绘制时！由于显示器机制的原因，都会出现图标模糊不精致的情况！所以还是希望开发网格的制定的功能，而且既然是恒定网格大小，官方界面为了好看做成滑条的样式也是很诡异的！
