### ISSUE TITLE
账号问题，微博账号突然提示长时间未使用，处于保护状态，我的iconfont里面还有几个项目，并且只有我一个人有权限

### ISSUE THREAD

**Issue by yy641956686** [thx/iconfont-plus#1808]
账号问题，微博账号突然提示长时间未使用，处于保护状态，我的iconfont里面还有几个项目，并且只有我一个人有权限，现在登录不了了，几个项目的iconfont找不回来了。急急急！！！
丢失的微博登录账号：641956686@qq.com

可以帮我把里面的项目转到新账号里面来吗？
新的github账号：yy641956686

**Comment by yisibl** [comment]
我们正在考虑实现新的账户系统

**Comment by yisibl** [comment]
Duplicate of #1718
