### ISSUE TITLE
无法上传带渐变的ICON

### ISSUE THREAD

**Issue by lockmet** [thx/iconfont-plus#1809]
平台是不是不能上传带渐变带ICON？
刚才试了不能上传，最简单带渐变矩形都上传失败
ICON是用Sketch导出的SVG文件

**Comment by yisibl** [comment]
很抱歉，目前不支持渐变

**Comment by yisibl** [comment]
支持渐变图标请关注：https://github.com/thx/iconfont-plus/issues/1938
