### ISSUE TITLE
icon不能下载，点下载就跳到错误页面

### ISSUE THREAD

**Issue by weijingqi** [thx/iconfont-plus#181]

**Comment by purplebamboo** [comment]
亲  麻烦场景提供下

什么浏览器，下载什么图标。

**Comment by jiangyo** [comment]
safari浏览器也是这样，测试了很多图标，都下不了

**Comment by purplebamboo** [comment]
chrome浏览器是直接在前端下载的。而safari，edge等等都是降级到 服务端下载的。

查看了下后台日志，应该是命名的问题。

你们下载的文件是不是  名称里面有 '.'  这个字符。这样好像有问题。


如果是这个问题我待会儿修复下，亲们可以先用chrome下载哈。

**Comment by purplebamboo** [comment]
已经修复了哈，如果还有问题，可以继续提issue哈。
