### ISSUE TITLE
网页登录方式，微博登录，为啥一定要扫码

### ISSUE THREAD

**Issue by csckz** [thx/iconfont-plus#1810]
网页登录方式，微博登录，为啥一定要扫码，不能用微博的账号密码登录吗，我不用微博，为了使用微博登录还特意下载了个微博手机版？

**Comment by yisibl** [comment]
这是微博控制的，后续 iconfont 会实现独立的账户体系，直接使用手机号+密码即可登陆，彻底解决三方登陆不好用的问题。
