### ISSUE TITLE
搜索出来结果没有分页

### ISSUE THREAD

**Issue by y284663247** [thx/iconfont-plus#182]
搜索出来结果没有分页，我现在怀疑测试过没有，直接返回旧版本了

**Comment by purplebamboo** [comment]
是搜图标？ 是搜索的什么词？
亲我们毕竟没有专门的测试人员哈，如果有遗漏的还请见谅哈。。

场景再描述一下？

**Comment by y284663247** [comment]
在“我的项目”页面，使用右上角的搜索功能


原始邮件
发件人:purplebamboonotifications@github.com
收件人:thx/iconfont-plusiconfont-plus@noreply.github.com
抄送:rickeryulhyfe1987@163.com; Authorauthor@noreply.github.com
发送时间:2016年11月17日(周四) 21:10
主题:Re: [thx/iconfont-plus] 搜索出来结果没有分页 (#182)


是搜图标？ 是搜索的什么词？
 亲我们毕竟没有专门的测试人员哈，如果有遗漏的还请见谅哈。。
场景再描述一下？

**Comment by purplebamboo** [comment]
亲啊  项目里本来就不用分页啊

**Comment by y284663247** [comment]
错了，先搜索一个关键字，不够一页比如“测评”，显示50个不够一页，在搜索其他就没有分页


原始邮件
发件人:purplebamboonotifications@github.com
收件人:thx/iconfont-plusiconfont-plus@noreply.github.com
抄送:rickeryulhyfe1987@163.com; Authorauthor@noreply.github.com
发送时间:2016年11月17日(周四) 21:10
主题:Re: [thx/iconfont-plus] 搜索出来结果没有分页 (#182)


是搜图标？ 是搜索的什么词？
 亲我们毕竟没有专门的测试人员哈，如果有遗漏的还请见谅哈。。
场景再描述一下？

**Comment by purplebamboo** [comment]
你是指  最上面的 搜索框

还是指 那个圆圆的图标呢。

上面的搜索框会到搜索结果页

而圆圆的图标是提供的当前的局部搜索肯定没分页的哈

**Comment by y284663247** [comment]
原始邮件
发件人:purplebamboonotifications@github.com
收件人:thx/iconfont-plusiconfont-plus@noreply.github.com
抄送:rickeryulhyfe1987@163.com; Authorauthor@noreply.github.com
发送时间:2016年11月17日(周四) 21:18
主题:Re: [thx/iconfont-plus] 搜索出来结果没有分页 (#182)


你是指 最上面的 搜索框
还是指 那个圆圆的图标呢。
上面的搜索框会到搜索结果页
而圆圆的图标是提供的当前的局部搜索肯定没分页的哈

**Comment by purplebamboo** [comment]
的确是个bug。
需要先搜索一个结果不足一页的，之后再搜索多的，分页就有问题。已经修复了哈。

之前其实很难发现，因为搜索结果之前会很多，这几天我们改进了引擎，把结果更精确了，所以搜索的结果会少点。

感谢反馈，毕竟精力有限，我们也只能用业余时间来开发iconfont。而且不是专业的测试，难免会遗漏一些小点。给亲带来了不便还请见谅哈。
回想起以前我开发旧版的时候，也是一个个bug修复过来的。

有问题在这里提，我们会第一时间修复的哈。

**Comment by y284663247** [comment]
好的，嘿嘿


发自网易邮箱大师
在2016年11月17日 22:22，purplebamboo 写道:

的确是个bug。
需要先搜索一个结果不足一页的，之后再搜索多的，分页就有问题。已经修复了哈。

之前其实很难发现，因为搜索结果之前会很多，这几天我们改进了引擎，把结果更精确了，所以搜索的结果会少点。

感谢反馈，毕竟精力有限，我们也只能用业余时间来开发iconfont。而且不是专业的测试，难免会遗漏一些小点。给亲带来了不便还请见谅哈。
回想起以前我开发旧版的时候，也是一个个bug修复过来的。

有问题在这里提，我们会第一时间修复的哈。

**Comment by y284663247** [comment]
个人建议啊也是我现在切回到旧版本的原因
1.鼠标放上去，就看不到图标了，想在看一下必须要离开鼠标，旧版本在下面直接就能看到
2.默认中间的是收藏 ，我放小车里面多，所有每次都要在移动到上面的小车


就是原来有些一目了然的操作变得隐藏起来了，新版本界面变酷了但操作变麻烦了


原始邮件
发件人:purplebamboonotifications@github.com
收件人:thx/iconfont-plusiconfont-plus@noreply.github.com
抄送:rickeryulhyfe1987@163.com; Authorauthor@noreply.github.com
发送时间:2016年11月18日(周五) 09:49
主题:Re: [thx/iconfont-plus] 搜索出来结果没有分页 (#182)


Closed #182.

**Comment by purplebamboo** [comment]
明白  我去反馈给我们设计师，考虑做点改造。
