### ISSUE TITLE
微博账号被冻结，无法登陆iconfont，请求转移账号

### ISSUE THREAD

**Issue by MARC0000001** [thx/iconfont-plus#1821]
一直使用微博账号登录，但是最近微博账号被无故封禁，各种渠道投诉无果。

导致项目中无法上传新图标，影响了项目进度。
请工程师帮我把之前的项目转移到新账号上

**Comment by yisibl** [comment]
请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
