### ISSUE TITLE
项目下的icon希望可以拖动排序

### ISSUE THREAD

**Issue by vini123** [thx/iconfont-plus#183]
本人有强迫症。添加好icon到项目下，没办法改变位置。因为图标是不定期，不定时加入，希望有的图标靠在一起。或靠前或靠后排版。但是，网站不提供拖动功能。死死的。这点不好。

**Comment by Muqing1221** [comment]
Get~拖动虽然目测短期不好实现，但亲的需求是整理图标嘛，或许我们之后可以选择别的方式来解决亲的问题
