### ISSUE TITLE
使用新浪账号登录，最近新浪账号因为长期没登录导致保护状态

### ISSUE THREAD

**Issue by gong-de-ming** [thx/iconfont-plus#1835]
使用新浪账号登录，最近新浪账号因为长期没登录导致保护状态，新浪那边不能登录了，导致现在呢iconfont不能用了

**Comment by jianguiweilai** [comment]
同样的问题，希望能加个账号的申诉，把无法使用的第三方账号数据可以找回
可以通过项目命名，参与项目的人 等进行人工申诉，或者有偿申诉

**Comment by pgfeng** [comment]
号被盗，找回来已被冻结，同求。

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖微博的三方登录。如果需要找回老账号遇到问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
