### ISSUE TITLE
上传svg超出大小 提示信息有误

### ISSUE THREAD

**Issue by CLgang** [thx/iconfont-plus#1836]
![698882AB-21E0-4886-B271-ECD7951CC729](https://user-images.githubusercontent.com/26788675/104423124-a5dd0180-55b8-11eb-840d-5faa2d9ee9a3.png)
应该是限制40960B，也就是40kb，因为我超过40KB的svg格式的图标都上传不了。但是提示的却是不超过40960KB。

**Comment by yisibl** [comment]
请在这里打包上传一下 svg 文件

**Comment by yisibl** [comment]
感谢反馈，已修复
