### ISSUE TITLE
希望可以关联账号

### ISSUE THREAD

**Issue by AlMiraiABC** [thx/iconfont-plus#1838]
希望可以通过不同的社交方式登陆同一个账号
新浪微博登和GITHUB的账号是两个账号，不能合并，也不能添加其他登陆方式

**Comment by yisibl** [comment]
手机注册登录功能已经上线，[点击查看](https://mp.weixin.qq.com/s?__biz=Mzg5OTUzNjQ0Mg==&mid=2247483866&idx=1&sn=e6d02ca84cba8157c8f90d072db66bbf&chksm=c050828ff7270b99b00d784681a47fb4d1063a9139732075dc84d8da4ad77d446df386384acc&token=1155149842&lang=zh_CN#rd)

相关 issue：#1718
