### ISSUE TITLE
淘宝账号无法登录！项目怎么办啊！登录问题！急啊！

### ISSUE THREAD

**Issue by yunshitech** [thx/iconfont-plus#184]
淘宝选项是黑白色，无法选择这个账户登录！我的项目都在淘宝号啊！

**Comment by purplebamboo** [comment]
亲  iconfont真的从来没有支持过 淘宝账号登陆啊。

你可以提供下  项目名称，或者  用户昵称，我可以尝试帮你找找。

**Comment by yunshitech** [comment]
用户昵称我忘了   项目名字是好工匠

**Comment by yunshitech** [comment]
我之前打开的是旧版。旧版点登陆有三个选项， 域账号，新浪账号，淘宝账号

**Comment by purplebamboo** [comment]
亲  查了下  ，你用的是微博账号登陆的。

Vanessa女郎888  昵称是这个哈，你用微博登陆看看吧。
