### ISSUE TITLE
微博账号从个人转为企业时，用的同一个手机号码，导致必须先注销个人账号，再申请企业账号，申请完了后，登陆iconfont，竟然没有项目了，项目丢失啊，急急急，损失惨重

### ISSUE THREAD

**Issue by zhang1395hao** [thx/iconfont-plus#1843]
请问，怎么解决啊，怎么申诉啊？ 求入口？？？
急急急，在线等

**Comment by zhang1395hao** [comment]
没人解决的啊？？？ 求官方联系方式

**Comment by yisibl** [comment]
请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
