### ISSUE TITLE
如果无法登录，能根据 project id 找到之前的项目吗？

### ISSUE THREAD

**Issue by erhu1999** [thx/iconfont-plus#1845]

**Comment by yisibl** [comment]
可以的
请提供： project id、无法登陆的账户名、需要转移的用户名

**Comment by erhu1999** [comment]
@

> 可以的
> 请提供： project id、无法登陆的账户名、需要转移的用户名

@yisibl 我原来的登录账号是 wangxiaoshuang@up72.com ，现在的账号是 erhu1999 ，如果可以转移整个账号下的全部项目，请把 wangxiaoshuang@up72.com 下的项目转移到 erhu1999 下，如果不能整体转移的话，请帮忙转移以下两个项目，project id为：
2310039
1919927

**Comment by yisibl** [comment]
可以了

**Comment by erhu1999** [comment]
好的，谢谢，麻烦了。
