### ISSUE TITLE
给项目添加成员，总是提示【成功登录后的账号才能被搜索到哦~】，这个账号是存在的

### ISSUE THREAD

**Issue by D8D-MIke** [thx/iconfont-plus#1850]
给项目添加成员，总是提示【成功登录后的账号才能被搜索到哦~】，这个账号是存在的

**Comment by junshang329** [comment]
对哦，我也是这个问题，是不是出bug了今天

**Comment by creatsoftdev** [comment]
我也是这个问题，待解决啊

**Comment by creatsoftdev** [comment]
我也是这个问题，待解决啊

**Comment by xiaojinsongwusha** [comment]
昨晚遇到这个问题了，今早试了还是不行，上面一直提示成功登录的账号才能被搜索到，确定的是成员是在线状态的
![image](https://user-images.githubusercontent.com/42968878/106223537-8f6fb080-621c-11eb-92be-b941317350e0.png)

**Comment by yangxialei** [comment]
https://www.iconfont.cn/api/common/suggest.json?q=yxl&t=1611887311244&ctoken=T40v81DGjb3w9IlJ42H5ZtE2

**Comment by yangxialei** [comment]
https://www.iconfont.cn/api/common/suggest.json?q=yxl&t=1611887311244&ctoken=T40v81DGjb3w9IlJ42H5ZtE2
这个接口有问题

**Comment by xiaojinsongwusha** [comment]
> https://www.iconfont.cn/api/common/suggest.json?q=yxl&t=1611887311244&ctoken=T40v81DGjb3w9IlJ42H5ZtE2
> 这个接口有问题

啊哈哈哈，你改一下？

**Comment by yangxialei** [comment]
> > https://www.iconfont.cn/api/common/suggest.json?q=yxl&t=1611887311244&ctoken=T40v81DGjb3w9IlJ42H5ZtE2
> > 这个接口有问题
> 
> 啊哈哈哈，你改一下？

我也想啊...

**Comment by laochake** [comment]
+1

**Comment by yisibl** [comment]
现在可以了，麻烦再试一下，感谢反馈。
