### ISSUE TITLE
为什么微博登录改二维码了？

### ISSUE THREAD

**Issue by qq2386322565** [thx/iconfont-plus#1859]
为什么微博登录改二维码了？我微博账号冻结了，手机号也换了，现在登录不了，里面还有很多项目

**Comment by Lili99999** [comment]
![image](https://user-images.githubusercontent.com/70736197/106869953-7890f880-670b-11eb-98d7-737ba9fafbc4.png)
可以使用账号登录的

**Comment by qq2386322565** [comment]
你好，我账号被冻结了，登录不了微博，原来iconfont官网是可以直接微博账号登录的。现在改二维码扫码了。我里面的项目泡汤了啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月4日(星期四) 下午5:08
收件人:&nbsp;"thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;;
抄送:&nbsp;"2386322565"<2386322565@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 为什么微博登录改二维码了？ (#1859)





 

 可以使用账号登录的

**Comment by Lili99999** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Jason"<notifications@github.com&gt;; 
发送时间: 2021年2月4日(星期四) 下午5:10
收件人: "thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;; 
抄送: "何来亏欠™"<169758991@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [thx/iconfont-plus] 为什么微博登录改二维码了？ (#1859)





 你好，我账号被冻结了，登录不了微博，原来iconfont官网是可以直接微博账号登录的。现在改二维码扫码了。我里面的项目泡汤了啊 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2021年2月4日(星期四) 下午5:08 
 收件人:&amp;nbsp;"thx/iconfont-plus"<iconfont-plus@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"2386322565"<2386322565@qq.com&amp;gt;;"Author"<author@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [thx/iconfont-plus] 为什么微博登录改二维码了？ (#1859) 
 
 
 
 
 
   
 
  可以使用账号登录的

**Comment by yisibl** [comment]
新浪微博是三方平台，他们的登录方式我们无法控制的。不过现在iconfont 支持手机+密码登录了，不再依赖三方登录。

如果还有问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
