### ISSUE TITLE
图标库审核拒绝

### ISSUE THREAD

**Issue by maokedongwu** [thx/iconfont-plus#186]
我新开了一个图标库，拉进去一百多个图标，都被审核拒绝了，不知道是哪里的问题。

**Comment by Muqing1221** [comment]
有重复图标（多到我无法手动剔除），或者单多色混合，可以看下常见问题~http://www.iconfont.cn/plus/help/article_detail?article_id=4

**Comment by purplebamboo** [comment]
再次 编辑那个图标库，在审核拒绝的图标那边，是可以看到被拒绝的原因的哈。
