### ISSUE TITLE
图标搜索结果展示页面，切换筛选区域的图标类型，JS报错，页面无限loading

### ISSUE THREAD

**Issue by Lishanming** [thx/iconfont-plus#1867]
[https://www.iconfont.cn/search/index?searchType=icon&q=%E5%88%A0%E9%99%A4](比如说搜索删除icon)
此时切换头部靠下的filter区域的图标类型select，seajs报错：
magix.js:1 Uncaught TypeError: Cannot read property '' of null

似乎是尝试修改头部的搜索类型select（图标，插画，用户）部分的代码出了问题。

**Comment by TomWangKing** [comment]
一样出问题
https://www.iconfont.cn/search/index?searchType=1&q=%E9%93%BE%E6%8E%A5

**Comment by yisibl** [comment]
已经修复，感谢反馈。
