### ISSUE TITLE
单色图表搜索报错

### ISSUE THREAD

**Issue by Akihi-Lee** [thx/iconfont-plus#1868]
![image](https://user-images.githubusercontent.com/48084355/108583277-5df98900-7373-11eb-9cd9-74fcf395b646.png)
![image](https://user-images.githubusercontent.com/48084355/108583285-69e54b00-7373-11eb-8a9f-ffcb46cc435b.png)
一直处于loading状态

**Comment by yisibl** [comment]
已经修复了，清一下浏览器缓存再试试
