### ISSUE TITLE
我的iconfong 新浪帐号 所有的项目  图标被清空了

### ISSUE THREAD

**Issue by 474366498** [thx/iconfont-plus#1870]
我的iconfong 新浪帐号 所有的项目  图标被清空了 怎么办了

**Comment by 474366498** [comment]
我原来的帐号 呢称  叫奋斗青年彬哥哥 上面有好几个项目 一过完年回来 用新浪邮箱登录 结果就成了新用户*********  项目 图标一个都没有了

**Comment by yisibl** [comment]
换了账户登陆的确是新的 账号了，请使用原来的登陆方式。

**Comment by 474366498** [comment]
那是不是 我以前用的新浪邮箱的那个帐号就没有了&nbsp; &nbsp;里面的图标&nbsp; 项目也就没有了呢？？



&nbsp;&nbsp;&nbsp; 
 &nbsp;
 &nbsp;
 &nbsp;
 &nbsp;
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 蒋彬


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月22日(星期一) 下午2:46
收件人:&nbsp;"thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;;
抄送:&nbsp;"獨箛勼汎"<474366498@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 我的iconfong 新浪帐号 所有的项目  图标被清空了 (#1870)





 
换了账户登陆的确是新的 账号了，请使用原来的登陆方式。

**Comment by yisibl** [comment]
都还在的，你用原来的账号登陆就可以了。

**Comment by 474366498** [comment]
呢称都变了 哪里还是原来的帐号嘛 我用的 auqsse474366498@sina.com&nbsp; 原来的呢称是个中文 现在全都变了
&nbsp;&nbsp;&nbsp; 
 &nbsp;
 &nbsp;
 &nbsp;
 &nbsp;
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 蒋彬


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月22日(星期一) 下午3:29
收件人:&nbsp;"thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;;
抄送:&nbsp;"獨箛勼汎"<474366498@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 我的iconfong 新浪帐号 所有的项目  图标被清空了 (#1870)





 
都还在的，你用原来的账号登陆就可以了。

**Comment by 474366498** [comment]
呢称都变了 哪里还是原来的帐号嘛 我用的&nbsp;auqsse474366498@sina.com&nbsp; 原来的呢称是个中文 现在全都变了
&nbsp;&nbsp;&nbsp; 
 &nbsp;
 &nbsp;
 &nbsp;
 &nbsp;
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 蒋彬


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月22日(星期一) 下午3:29
收件人:&nbsp;"thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;;
抄送:&nbsp;"獨箛勼汎"<474366498@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 我的iconfong 新浪帐号 所有的项目  图标被清空了 (#1870)





 
都还在的，你用原来的账号登陆就可以了。

**Comment by 474366498** [comment]
![image](https://user-images.githubusercontent.com/38313177/108792294-e23e4d00-75bb-11eb-9819-026dd4f44a67.png)
原来我是这个帐号  现在是一个新号  什么图标 收藏都没有了  原来那个帐号用了好多年了  上面有很多以前的项目 图标  怎么办了？可以转到新的帐号上面嘛？

**Comment by yisibl** [comment]
请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092

**Comment by jxzlhy** [comment]
搞什么鬼东西啊，产品是吃屎的？
