### ISSUE TITLE
能否支付宝扫码登录

### ISSUE THREAD

**Issue by Mick-tracy** [thx/iconfont-plus#1872]
新浪微博登录每次都提示错误，实在太麻烦了，能够支付宝扫码登录啊

**Comment by yisibl** [comment]
现在有独立的手机注册登录功能，[点击查看](https://mp.weixin.qq.com/s?__biz=Mzg5OTUzNjQ0Mg==&mid=2247483866&idx=1&sn=e6d02ca84cba8157c8f90d072db66bbf&chksm=c050828ff7270b99b00d784681a47fb4d1063a9139732075dc84d8da4ad77d446df386384acc&token=1155149842&lang=zh_CN#rd)，不再强依赖三方登录。

相关 issue：#1718
