### ISSUE TITLE
搜索结果前10页都是一样的图标

### ISSUE THREAD

**Issue by liorliwd** [thx/iconfont-plus#1874]
不知道啥时候开始，阿里巴巴图标库搜索至少前10页都是一样的结果，只是颜色不同而已，请问都没有管理员出来清理一下的么，一直重复的内容还要什么搜索

**Comment by yisibl** [comment]
搜索的关键词和链接发一下

**Comment by liorliwd** [comment]
感谢管理的回复！回答您的问题，之前搜的关键词：首页、分类、购物车、我的。这几个关键词都是一样的情况，下方是截图：






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "一丝"<notifications@github.com&gt;; 
发送时间: 2021年2月24日(星期三) 下午2:42
收件人: "thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;; 
抄送: "Lior"<258357523@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [thx/iconfont-plus] 搜索结果前10页都是一样的图标 (#1874)





 
搜索的关键词和链接发一下

**Comment by yisibl** [comment]
没看到截图

**Comment by liorliwd** [comment]
打包发给您，请查看附件。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月25日(星期四) 下午4:39
收件人:&nbsp;"thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;;
抄送:&nbsp;"Lior"<258357523@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 搜索结果前10页都是一样的图标 (#1874)





 
没看到截图

**Comment by yisibl** [comment]
这里切换成 精选图标试试
![image](https://user-images.githubusercontent.com/2784308/109129010-16b43380-778b-11eb-86b8-5eee8ffd76b7.png)

**Comment by liorliwd** [comment]
完美解决，感谢官方大佬的帮助！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月25日(星期四) 下午5:01
收件人:&nbsp;"thx/iconfont-plus"<iconfont-plus@noreply.github.com&gt;;
抄送:&nbsp;"Lior"<258357523@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 搜索结果前10页都是一样的图标 (#1874)





 
这里切换成 精选图标试试
