### ISSUE TITLE
symbol 链接是否可以固定不变

### ISSUE THREAD

**Issue by BigGoblin** [thx/iconfont-plus#1877]
重新上传图标后，生成的symbol链接能不能不需要重新生成。

**Comment by MyCupOfTeaOo** [comment]
同问

**Comment by yisibl** [comment]
不可以，会有缓存

**Comment by MyCupOfTeaOo** [comment]
> 不可以，会有缓存

主要每次添加图标都要重新编译下项目
虽然确实可用通过其他办法实现管理新的脚本,比如 google analysis插入脚本
