### ISSUE TITLE
图标在https的请求方式下 页面显示全是叉叉

### ISSUE THREAD

**Issue by feiyangchen** [thx/iconfont-plus#188]
图标在https的请求方式下 页面显示全是叉叉，求解决

**Comment by purplebamboo** [comment]
提供下项目id？

是怎么使用的，用的我们的cdn地址？

**Comment by feiyangchen** [comment]
我们是在工作项目中用的 主要是这样的 我们在页面中引用你们的图标cdn 在手机的浏览器中没有问题 app调用我们的h5页面也没有问题 但是app讲请求我们页面的方式改成https 就出现图标无法正常显示 出现叉叉


发自我的 iPhone

**Comment by purplebamboo** [comment]
不是太明白  我们的cdn支持https的

你们直接在手机浏览器中使用https试过不？

app调用是什么意思  是指用webview加载h5页面吗？

**Comment by feiyangchen** [comment]
是的
是华为一款分屏手机中出现的

发自我的 iPhone

**Comment by purplebamboo** [comment]
场景不是太清楚，如果浏览器里没问题，只是app的问题我们可能也无法提供解决办法哈。

**Comment by feiyangchen** [comment]
嗯嗯 好的 app的人也在看

发自我的 iPhone
