### ISSUE TITLE
搜索不好用了

### ISSUE THREAD

**Issue by yushengzhen** [thx/iconfont-plus#1882]
搜索不好用了，怎么回事

**Comment by yisibl** [comment]
发一下搜索后的链接和问题描述

**Comment by reknown** [comment]
资源管理下任意一个栏目，搜索点击或者回车都是无效的，其他栏目下没有问题

**Comment by reknown** [comment]
除了首页和搜索结果页面的搜索是有效的，其他栏目下搜索点击或者回车都是无效的
https://www.iconfont.cn/manage/index?spm=a313x.7781069.1998910419.9&q=%E4%BC%9A%E5%91%98&page=1&searchType=icon&fromCollection=-1&fills=&tag=

**Comment by yisibl** [comment]
已修复，感谢反馈
