### ISSUE TITLE
about sign in

### ISSUE THREAD

**Issue by Du-sAan** [thx/iconfont-plus#1883]
登录选项，链接github错误，而且为什么不添加其它的第三方登录呢

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖微博的三方登录。

![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
