### ISSUE TITLE
github、阿里云、微博账号无法关联同一个账号

### ISSUE THREAD

**Issue by gx-yy** [thx/iconfont-plus#1886]
在个人设置中添加关联其他平台账号的设置，这样不管用哪个平台登录都是进入的同一个账号

**Comment by yisibl** [comment]
手机注册登录功能已经上线，可以在同一个手机关联不同的三方账号。[点击查看](https://mp.weixin.qq.com/s?__biz=Mzg5OTUzNjQ0Mg==&mid=2247483866&idx=1&sn=e6d02ca84cba8157c8f90d072db66bbf&chksm=c050828ff7270b99b00d784681a47fb4d1063a9139732075dc84d8da4ad77d446df386384acc&token=1155149842&lang=zh_CN#rd)

相关 issue：#1718
