### ISSUE TITLE
微博注销了，账号管理着很多个项目，可以帮转移项目的管理权吗？

### ISSUE THREAD

**Issue by kencc12** [thx/iconfont-plus#1887]

**Comment by yisibl** [comment]
请提供一下原有账号和新账号名称。

**Comment by yisibl** [comment]
请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
