### ISSUE TITLE
微博注销了，账号管理着很多个项目，可以帮转移项目到新的gitlab帐号上嘛

### ISSUE THREAD

**Issue by 474366498** [thx/iconfont-plus#1888]
原来的帐号是用微博邮箱注册的 ，不知道怎么回事 新年第一天来 直接原帐号就没有了 现在就只有个帐号名了 ![图片](https://user-images.githubusercontent.com/38313177/110054321-dad62b00-7d95-11eb-8805-d90c22d5c968.png) 
正在可不可以把我原来帐号下的所有项目 图标 收藏....转移到新的gitlab 帐号下了   gitlab 474366498@qq.com 呢称 474366498

**Comment by yisibl** [comment]
图标 收藏 暂时不太好转移

**Comment by 474366498** [comment]
&nbsp;&nbsp;&nbsp; 那请问你什么好移了 ？&nbsp; 那你要不帮我随便移点什么在新的github帐号上去嘛&nbsp; 至少留点东西痕迹在新帐号上了
 &nbsp;
 &nbsp;
 &nbsp;
 &nbsp;
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 蒋彬







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月16日(星期二) 上午10:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 微博注销了，账号管理着很多个项目，可以帮转移项目到新的gitlab帐号上嘛 (#1888)





 
图标 收藏 暂时不太好转移

**Comment by yisibl** [comment]
请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
