### ISSUE TITLE
为什么旧版中的有些图标在新版中搜不到

### ISSUE THREAD

**Issue by deguo** [thx/iconfont-plus#189]
例如：搜索“S 字符串“
旧版：
![image](https://cloud.githubusercontent.com/assets/12880699/20425271/db86b4e4-adb4-11e6-9aad-bdc14654b9cc.png)
新版：
![image](https://cloud.githubusercontent.com/assets/12880699/20425298/fba3c83e-adb4-11e6-8047-a4c37981f480.png)
明显不是一个图标

> ps：不知道能不能增加个图片搜索图片的功能

**Comment by Muqing1221** [comment]
@purplebamboo

**Comment by purplebamboo** [comment]
其实是同一个，只是旧版所有path都合在一起。新版是分path展现的。

当有奇偶path时，分path展现有问题，而老版本是误打误撞。

我做了个兼容哈。已经会保持一致了。
