### ISSUE TITLE
最垃圾的登录方式，没有之一！

### ISSUE THREAD

**Issue by Mick-tracy** [thx/iconfont-plus#1890]
最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！

**Comment by 776261616** [comment]
最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！

**Comment by Sharonxue1986** [comment]
最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！最垃圾的登录方式，没有之一！
