### ISSUE TITLE
登陆不进去

### ISSUE THREAD

**Issue by XIAO751208540** [thx/iconfont-plus#1893]
![image](https://user-images.githubusercontent.com/64509177/110722051-9989c380-824c-11eb-9042-754abd89567f.png)
使用github登陆报错，怎么解决？

**Comment by George-Miao** [comment]
同样的问题

**Comment by easyfrog** [comment]
怎么办呀？ 有官方的同志给个解决方案吗？？

**Comment by yiaiyohei** [comment]
同样的问题

**Comment by easyfrog** [comment]
今天试了试， 已经 可以了。 ~看来官方大大在暗自努力 🤞

**Comment by aj054** [comment]
同样的问题

**Comment by vanilla110** [comment]
同上

**Comment by yisibl** [comment]
请勿重复提交，统一在这里回复：#1898
