### ISSUE TITLE
图标搜索问题

### ISSUE THREAD

**Issue by zptlhy** [thx/iconfont-plus#1894]
首页的大搜索框，搜索图标，出来是所有图标的搜索结果，但内页顶部的搜索框搜索出来，默认的是精选图标的搜索结果，按道理最顶部的搜索框是全站搜索，默认应该搜索关键词，首先出来的是所有图标！

**Comment by zmlstc** [comment]
强烈同意，最不能接受的是 我选了全部图标，下一次又变成了精选图标。每次搜索都要手动改回去。

**Comment by yisibl** [comment]
感谢建议，现在右上角图标搜索框可以记住搜索类型选择了。
