### ISSUE TITLE
GitHub登录接口报错

### ISSUE THREAD

**Issue by wenkeming** [thx/iconfont-plus#1896]
如题：
![image](https://user-images.githubusercontent.com/8252267/111156241-79516000-85d0-11eb-8f96-7813bd601af3.png)

**Comment by charles0122** [comment]
同款报错

**Comment by wuxj** [comment]
同款报错

**Comment by yisibl** [comment]
感谢反馈，正在排查中

**Comment by maochong513** [comment]
![image](https://user-images.githubusercontent.com/16568747/111729577-5235af80-88aa-11eb-91ba-9bc46602085a.png)
类似同款报错

**Comment by yisibl** [comment]
请勿重复提交，统一在这里回复：#1898
