### ISSUE TITLE
您的浏览器版本过低不支持自动复制【chrome  89.0.4389.82（正式版本） （64 位）】

### ISSUE THREAD

**Issue by huanshiwushuang** [thx/iconfont-plus#1897]
![image](https://user-images.githubusercontent.com/18592659/111246600-80fd1d00-8641-11eb-8279-43d3fb43bbd5.png)

**Comment by yisibl** [comment]
我这边无法复现，请看一下控制台是否有报错。

**Comment by huanshiwushuang** [comment]
> 我这边无法复现，请看一下控制台是否有报错。

sorry  我的问题   tampermonkey 注入的js 影响到了
