### ISSUE TITLE
github账号登录总是返回一个JSON,有什么办法解决吗.上梯子也是这样.

### ISSUE THREAD

**Issue by maxbad** [thx/iconfont-plus#1898]
{
"code": "ECONNRESET",
"message": "Error"
}
总返回这个!

**Comment by wuxj** [comment]
同款报错

**Comment by wbewang** [comment]
一样

**Comment by sunwenxu1997** [comment]
求解决，登不上去了

**Comment by xiaohangDAD** [comment]
现在也没好

**Comment by landv** [comment]
完犊子，根本不让登陆

**Comment by MaksLife** [comment]
烦死了，github登录不上 微博又不玩 又不是内部员工，只能干看着了

**Comment by landv** [comment]
> 烦死了，github登录不上 微博又不玩 又不是内部员工，只能干看着了

嘿嘿，我刚找回微博的密码🌝🌝ᥬ😂᭄

**Comment by TomWangKing** [comment]
github登录不上

**Comment by yisibl** [comment]
感谢反馈，正在排查中

**Comment by samhzx** [comment]
同款报错+1

**Comment by H-Haynes** [comment]
目前还是这样，没人维护？

**Comment by JayChen1195** [comment]
同款报错+1，望速度解决啊

**Comment by myweb2019** [comment]
都2天了，都还没解决，我离职交接项目这咋个搞，望速度解决

**Comment by yisibl** [comment]
GitHub 登陆最近国内访问经常失败，非常不稳定。我们正在研究方案，会尽快上线。

**Comment by Chase-Dream-Ls** [comment]
github就算了，用个微博账户还非要扫码登陆，还非要去下个微博，歧视腾讯没有qq登陆就算了，还非要拿微博客户端登陆，咋的阿里没人了

**Comment by luck2011** [comment]
使用微博登录是不可能的

**Comment by yisibl** [comment]
已经修复了一波，请再试试
