### ISSUE TITLE
登录之后下载图标，返回500错误

### ISSUE THREAD

**Issue by HenryYong** [thx/iconfont-plus#190]
{
code: 500,
message: "LOGIN REQUIRED"
}

**Comment by purplebamboo** [comment]
亲 这种情况代表没有登陆成功

平台目前 chrome下是直接浏览器下载
其他不支持新特性的 浏览器会通过后端下载

你这种情况用的应该是后端下载了。

麻烦提供下更具体的场景，比如什么浏览器。什么操作步骤哈。

我刚试了下，safari下 登陆状态下可以下载的

**Comment by HenryYong** [comment]
浏览器：chrome 54.0.2840.71 (64-bit)
账户：微博登录

**Comment by purplebamboo** [comment]
我刚用chrome试了下  没问题的呀。。

亲 你是下载单个图标吗？
你看看右上角有没有头像的 你确定你登陆成功了吗？

**Comment by HenryYong** [comment]
![image](https://cloud.githubusercontent.com/assets/7967105/20463876/97a0b40e-af77-11e6-95b3-7107dac7430f.png)
这样应该是登录成功了吧？我刚用safari试了下也是这个错，可能是网络不稳定么。。应该可以忽略这个issue了。。

**Comment by purplebamboo** [comment]
额 亲 现在下载呢？你这个截图里面应该是已经登陆好了，这时候就可以下载了。

这个跟网络没有关系的，都有login required的提示了，证明就是没有登陆成功

登陆成功后就可以下载的，而且chrome不会有这种提示，因为直接是浏览器下载的都没有请求的。

亲是不是哪里没操作对

**Comment by HenryYong** [comment]
应该没有操作问题呀。。微博登录-图标管理-我的项目-下载到本地。刚换了github登录也不行。。

**Comment by purplebamboo** [comment]
奥奥 你是说 下载项目是吗？ 好的 我明天去排查下哈。。我这边暂时没发现这个问题。

**Comment by purplebamboo** [comment]
或者亲 试试 关掉代理 关掉插件 还有是不是禁止了cookie之内的

**Comment by HenryYong** [comment]
好像都没有用，safari，FF都试过了，cookie缓存也都清了还是报错。。

**Comment by purplebamboo** [comment]
好的 我明早拍查下。。亲 你是下载的哪个项目
把当然项目的  浏览器里的当前地址贴出来哈 我明天去查

**Comment by purplebamboo** [comment]
我也是  mac下面的   chrome 54.

我进到你的页面 ，把所有项目都挨个点了下，都可以正常下载哎。

是不是你电脑哪里的环境问题呢，你有尝试过用同事的电脑是试一下不？

**Comment by HenryYong** [comment]
换了公司的wifi可以下载。。应该是网络环境的问题了。

**Comment by purplebamboo** [comment]
额。。好吧
