### ISSUE TITLE
web component 组件中如何应用svg图标

### ISSUE THREAD

**Issue by Forever17s** [thx/iconfont-plus#1900]
**应用场景:** Web 端使用 -> symbol 引用

![image](https://user-images.githubusercontent.com/35524901/111721421-d1bb8280-889a-11eb-8c5d-9abe92407461.png)

作为项目的前端使用，我按照文档引入 iconfont.js后，发现svg图片是直接被插入到了document中。
![image](https://user-images.githubusercontent.com/35524901/111721576-28c15780-889b-11eb-8cea-0e760e268a45.png)

项目中使用的是 web component，读取不到这个svg节点，图标也就没渲染出来。请问这种情况该如何使用iconfont...

**Comment by Jimco** [comment]
请问有解决方案吗？目前在做一个微前端项目，采用 shadow dom 做样式隔离，然而在 shadow dom 中使用 `use` 访问不到外部 svg 中的目标节点

**Comment by Forever17s** [comment]
目前将svg内容拆分成了key value的映射存到了json文件中，key表示标签名称，value表示svg真正需要插入的内容，然后innerHTML插入到svg标签中。没有使用推荐的use标签，因为获取不到body下的文档流

**Comment by Forever17s** [comment]
> 请问有解决方案吗？目前在做一个微前端项目，采用 shadow dom 做样式隔离，然而在 shadow dom 中使用 `use` 访问不到外部 svg 中的目标节点

目前将svg内容拆分成了key value的映射存到了json文件中，key表示标签名称，value表示svg真正需要插入的内容，然后innerHTML插入到svg标签中。没有使用推荐的use标签，因为获取不到body下的文档流

**Comment by mib008** [comment]
> 档

在不设置  sandbox.strictStyleIsolation = false 的情况下，我用了一个蠢方法：

`useEffect(() => {
    const iconSource = document.getElementById(iconId);

    let parent;

    if(ref && ref.current){
      parent = ref.current.parentNode;
      parent.appendChild(iconSource);
    }
  }, []);

  return (
    <svg ref={ref} aria-hidden="true">
      <use xlinkHref={`#${iconId}`}></use>
    </svg>
  );
`

**Comment by yisibl** [comment]
现在项目中重新生成 CDN 文件后，可以通过 `window._iconfont_svg_string_项目id` 来获取 SVG 的 string，以便在 Shadow DOM 调用。
