### ISSUE TITLE
新版无法上传图标

### ISSUE THREAD

**Issue by rilara** [thx/iconfont-plus#191]
在新版中无法上传单色svg文件，报错“Validation error：Validation is failed”。

但是转回旧版可以成功上传

**Comment by purplebamboo** [comment]
亲  svg  发出来一下？

可以发到这个邮箱：xhzhuweikang@163.com

**Comment by purplebamboo** [comment]
看到你发给我的svg了哈。

主要问题很简单，只是文件名称的问题哈。因为名称里有 .  % _这种特殊字符。

新版没有针对这种情况做特殊处理，这个我今天会修复掉哈。

你可以先改下文件名，就可以上传了哈。

**Comment by purplebamboo** [comment]
已经修复了哈。

**Comment by rilara** [comment]
感谢～真速度
