### ISSUE TITLE
以前账号登录不了了

### ISSUE THREAD

**Issue by fkini** [thx/iconfont-plus#1915]
删裤了吗？也没看见公告。

**Comment by yisibl** [comment]
提供一下账户名和登陆方式。

**Comment by 474366498** [comment]
auqsse474366498@sina.com    sina邮箱  可以帮我试试嘛

**Comment by yisibl** [comment]
需要 iconfont 的用户名，然后确保这个新浪微博账号还可以登录。

**Comment by fkini** [comment]
记不清是哪个账号了，提供曾经使用过的项目链接可以查到吗？
http://at.alicdn.com/t/font_2082151_gey5cu3o2q4.css
