### ISSUE TITLE
提供一下账户名和登陆方式。

### ISSUE THREAD

**Issue by 474366498** [thx/iconfont-plus#1916]
提供一下账户名和登陆方式。

auqsse474366498@sina.com    sina邮箱

**Comment by yinjisong** [comment]
顶啊！！！！每次都用微博登，GitHub又慢，微博都不敢卸载！！！！

**Comment by yisibl** [comment]
手机注册登录功能已经上线，[点击查看](https://mp.weixin.qq.com/s?__biz=Mzg5OTUzNjQ0Mg==&mid=2247483866&idx=1&sn=e6d02ca84cba8157c8f90d072db66bbf&chksm=c050828ff7270b99b00d784681a47fb4d1063a9139732075dc84d8da4ad77d446df386384acc&token=1155149842&lang=zh_CN#rd)

相关 issue：#1718
