### ISSUE TITLE
FontClass/Symbol明明是可选项为何要必填

### ISSUE THREAD

**Issue by sitengli** [thx/iconfont-plus#1919]
![image](https://user-images.githubusercontent.com/45628131/113377810-fab63a00-93a7-11eb-82dc-f1041995a2cb.png)

**Comment by iblackly** [comment]
+1

**Comment by yisibl** [comment]
现在用户不填写会使用用默认值。
![image](https://user-images.githubusercontent.com/2784308/118213964-8b049600-b4a1-11eb-81dc-06babe3708fc.png)
