### ISSUE TITLE
请问以后可以把用户须知放在官网首页的底部和帮助中心吗

### ISSUE THREAD

**Issue by wr131** [thx/iconfont-plus#1920]
这样子可以方便我们搞清楚版权许可
可以花更少的时间来弄清版权
减少很多时间花费在版权问题上

**Comment by yisibl** [comment]
现在下载图标时会有版权提示了。
![image](https://user-images.githubusercontent.com/2784308/117935105-f6315980-b335-11eb-998f-487718d8c347.png)
