### ISSUE TITLE
4月5日图标上传异常，无法上传图标

### ISSUE THREAD

**Issue by erichDuanET** [thx/iconfont-plus#1922]
![image](https://user-images.githubusercontent.com/20224790/113550709-1af32c80-9626-11eb-8619-bdf58dad5c21.png)

**Comment by erichDuanET** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<svg width="24px" height="24px" viewBox="0 0 24 24" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>icon/办事大厅/当事人诉讼服务</title>
    <defs>
        <linearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="linearGradient-1">
            <stop stop-color="#E4D59C" offset="0%"></stop>
            <stop stop-color="#C5AA63" offset="100%"></stop>
        </linearGradient>
        <linearGradient x1="50%" y1="0%" x2="50%" y2="100%" id="linearGradient-2">
            <stop stop-color="#E4D59C" offset="0%"></stop>
            <stop stop-color="#C5AA63" offset="100%"></stop>
        </linearGradient>
    </defs>
    <g id="页面-1" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="首页/办事大厅备份-2" transform="translate(-344.000000, -626.000000)">
            <g id="编组" transform="translate(320.000000, 250.000000)">
                <g id="编组-7备份" transform="translate(16.000000, 368.000000)">
                    <g id="icon/办事大厅/当事人诉讼服务" transform="translate(7.000000, 7.000000)">
                        <rect id="矩形备份-2" opacity="0.193064135" x="0" y="0" width="26" height="26"></rect>
                        <path d="M21,21 C21,21.5522847 21.4477153,22 22,22 L23,22 L23,22 L23,24 L3,24 L3,22 L4,22 C4.55228475,22 5,21.5522847 5,21 C5,20.4477153 5.44771525,20 6,20 L20,20 C20.5522847,20 21,20.4477153 21,21 Z" id="路径" fill="url(#linearGradient-1)"></path>
                        <path d="M8.06771726,3.88676862 L8.06771726,4.88676862 L20.0677173,4.88676862 L20.0677173,3.88676862 L21.0677173,3.88676862 L21.0677173,11.8867686 L20.0677173,11.8867686 L20.0677173,10.8867686 L15.0676478,10.8864466 L15.0677173,18.9578364 C15.0677173,19.5101212 14.620002,19.9578364 14.0677173,19.9578364 C13.5154325,19.9578364 13.0677173,19.5101212 13.0677173,18.9578364 L13.0676478,10.8864466 L8.06771726,10.8867686 L8.06771726,11.8867686 L7.06771726,11.8867686 L7.06771726,3.88676862 L8.06771726,3.88676862 Z" id="形状结合" fill="url(#linearGradient-2)" transform="translate(13.877648, 12.146447) rotate(-45.000000) translate(-13.877648, -12.146447) "></path>
                    </g>
                </g>
            </g>
        </g>
    </g>
</svg>

**Comment by yisibl** [comment]
图标目前不支持渐变哦。

**Comment by yisibl** [comment]
支持渐变图标请关注：https://github.com/thx/iconfont-plus/issues/1938
