### ISSUE TITLE
最近没咋用，今天打开网站发现让重新登录，用github和微博都登录了，里面都没有找到之前的项目，啥情况啊，急！

### ISSUE THREAD

**Issue by yinhexi** [thx/iconfont-plus#1925]
好久没有重新登陆过，记不清是用的哪个账号（github是jvjishou2007@163.com，微博是比帧网），但我创建的项目ID有记录的，我提供几个，麻烦咱们工作人员帮我查下这几个项目是在哪个账号下面，谢谢！！！
项目名：wxiconfont，项目ID：1834448
项目名：iconfont，项目ID：1732620
项目名：iconfont2，项目ID：1732693
项目名：iconfont3，项目ID：1738669
项目名：iconfont4，项目ID：1775225
项目名：iconfont5，项目ID：1779976

**Comment by yisibl** [comment]
都是用这个微博账号创建的，请使用该微博登陆 iconfont https://weibo.com/u/7271299624

**Comment by yinhexi** [comment]
@yisibl 找回来了，谢谢

**Comment by yisibl** [comment]
现在已经支持手机登录，最好还是尽快绑定一下手机。

相关 issue：#1718

**Comment by yinhexi** [comment]
你好，重装了系统，浏览器重新登录，发现使用该微博账号登陆 iconfont https://weibo.com/u/7271299624后，发现里面我的项目又是空的，啥也没有。麻烦再帮我看下啥情况，谢谢。里面部分项目ID如下：
项目名：wxiconfont，项目ID：1834448
项目名：iconfont，项目ID：1732620
项目名：iconfont2，项目ID：1732693
项目名：iconfont3，项目ID：1738669
项目名：iconfont4，项目ID：1775225
项目名：iconfont5，项目ID：1779976
