### ISSUE TITLE
多色、多 path 的 svg 上传失败或显示空白

### ISSUE THREAD

**Issue by xm-c** [thx/iconfont-plus#1928]
如下文件是我这边的两个 icon，其中第一个 icon 上传失败，第二个显示空白，请问这是什么原因造成，svg 需要改成什么格式才能满足。
[icon.zip](https://github.com/thx/iconfont-plus/files/6310551/icon.zip)

**Comment by yisibl** [comment]
目前不支持描边，图形的填充模式需要改成 非零（nonzero)

**Comment by xm-c** [comment]
之后会提供这类的支持吗？

**Comment by yisibl** [comment]
可能会考虑。目前请将描边转换为 outline。
