### ISSUE TITLE
亲，访问受限了

### ISSUE THREAD

**Issue by terrilltang** [thx/iconfont-plus#193]
自己的图标项目，下载时提示受限，但其它的图标项目则不会
下载时会跳转到 http://err.taobao.com/error2.html 这个URL

**Comment by purplebamboo** [comment]
一般来说  都是项目里  某个icon有问题哈，删掉这个就行了。

具体参考这里： http://www.iconfont.cn/plus/help/article_detail?article_id=4

里面的，为什么下载字体，更新cdn都会提示error

**Comment by terrilltang** [comment]
@purplebamboo 谢谢，按照你的办法解决了！
可否提个建议？在上传的时候就报错，这样不会在批量上传后一半一半的去排查。

**Comment by purplebamboo** [comment]
不是的  这个我们检测不出来的。

因为有很多可能，比如unicode不规范，或者path不规范。但是普通的svg展示是没问题的。只有生成字体后才有可能会发现。

不过我们可以想办法，让error页面 错误信息更明显点。这个  我们再想想看哈。
