### ISSUE TITLE
图标编辑报错

### ISSUE THREAD

**Issue by yolinsoft** [thx/iconfont-plus#1942]
编辑弹窗空白，提示“找不到这个图标”

**Comment by yisibl** [comment]
请提供用户名、图标名称或链接

**Comment by Clago** [comment]
解决了吗，我现在也是这个问题。创建项目的没有问题。额外加入的就是这个提示。

**Comment by hhsunxuan** [comment]
同样的问题
code: 404
message: "找不到这个图标"
是个bug

**Comment by Clago** [comment]
> 请提供用户名、图标名称或链接

Clago
https://www.iconfont.cn/api/icon/iconInfo.json?id=21680533&pid=2274015&cid=&t=1626156884022&ctoken=FCAegmbDwqDayyKn0SAZeaiB

这个没人管了吗，就特定一个项目下面突然找不到图标了，其他正常。

**Comment by yolinsoft** [comment]
好像老项目都有问题
