### ISSUE TITLE
从项目中下载Symbol到本地没有eot和svg文件

### ISSUE THREAD

**Issue by FengChengHou** [thx/iconfont-plus#1945]
![QQ图片20210430105343](https://user-images.githubusercontent.com/50071436/116642891-6937e900-a9a2-11eb-9668-6cfae6f1a651.png)

**Comment by yisibl** [comment]
现在默认已经不生成 eot 和 svg 字体了，如果需要请在「更多操作」→「编辑项目」的字体格式中勾选。
