### ISSUE TITLE
能不能提供删除所有上传图标的按钮？几百个 坑死我了 谢谢

### ISSUE THREAD

**Issue by whatwewant** [thx/iconfont-plus#195]
能不能提供删除所有上传图标的按钮？几百个 坑死我了 谢谢

**Comment by purplebamboo** [comment]
可以考虑的，主要之前讨论觉得，上传的图标有可能会在公共库里有引用，不是太建议大规模删除的。删除了，公共库里的也会没了。

我们再考虑下哈。

**Comment by whatwewant** [comment]
* 首先
  * 这种删除不是删除引用 只是删除用户和这个资源的关系 肯定不能说用户删除了就把整个资源删掉了 那就会爆发之前npm作者事件 npm pip 之类的仓库都是这么做的
* 其次
  * 设计整个App的时候不考虑垃圾箱机制？可以找回，作资源标记等方式

**Comment by whatwewant** [comment]
@purplebamboo 现在只有你在维护iconfont.cn吗？如何参与维护

**Comment by purplebamboo** [comment]
先回答问题：

* 公共库的概念是，从你上传的图标里面选一部分作为一个集合公开出去。所以如果你上传的图标都删除了，那么就也不应该存在公共库里了哈。不然你编辑公共库，做增加修改啥的逻辑也会很混乱。
* 项目的概念是，从若干集合里面拿出一些图标，自己用。自己保存了副本，自己可以设置unicode，设置形状，颜色等等等。

综上，项目里的图标随便怎么动，完全是一份新的。公共库里的是根据作者上传的来的，是联动的。

当然我们其实做了软删除哈，你删除了图标其实还是在的。但是公共库里的引用我们肯定得删除掉。

垃圾箱的机制，以目前的情况是可以做的，但是不是特别必要。可以考虑下。



最后维护的事情：
目前基本是  我还有  @gongeek  在维护。然后有个设计师妹子 @Muqing1221 。
iconfont.cn 几乎没有超过三个人以上维护过。所以精力有限，很多功能没有时间去做。（毕竟我们还有本职工作）
我们也考虑过开源，但是目前还不可行，一个是刚起步代码质量还不够，另一个iconfont依赖太多阿里集团内部的模块，还没想好怎么开源，目前还在梳理中。

**Comment by Muqing1221** [comment]
看到楼上的回复内心OS无数感动...

我理解应该你或许是希望借由批量操作而达到快捷操作、效率提升等诉求；我们在之后的优化中会尝试寻找合适的解决方案（技术限制内），力求能够最大程度的接近你期望的理想状态~

谢谢亲的关注，保持~~

**Comment by whatwewant** [comment]
@purplebamboo 
@Muqing1221 
@gongeek 
感谢 其实我对这些事有些想法的 最近也在做个图床的网站 功能其实和iconfont类似 希望有机会和各位合作 设计师妹纸 求合作 我是前端er

**Comment by purplebamboo** [comment]
暂时木有合作计划，实在没那么多精力。

批量的问题，我们到时考虑下哈。

**Comment by limingxuan960824** [comment]
上传的图标  能不能一次性全部删除啊？乱死了  一页一页删除
