### ISSUE TITLE
无法进入登录界面一直显示错误

### ISSUE THREAD

**Issue by yangshengmei** [thx/iconfont-plus#1952]

**Comment by yisibl** [comment]
请提供操作系统、浏览器版本以及报错页面截图

**Comment by chenmeizhu** [comment]
使用github无法登陆，页面报错
![1623290586(1)](https://user-images.githubusercontent.com/52400665/121453206-5bc74300-c9d3-11eb-9fb0-043b8ccf15b6.jpg)

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖三方登录。

![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
