### ISSUE TITLE
上传的图标无法下载

### ISSUE THREAD

**Issue by liuyepiaoxiang** [thx/iconfont-plus#1955]
上传图标之后共享给对方，在已经给对方权限的情况下，对方点击下载，显示“找不到这个插画”

**Comment by yisibl** [comment]
请提供一下插画链接

**Comment by ChaoQunPeng** [comment]
我也碰到了这个问题 , 地址是这个吗 https://www.iconfont.cn/api/svg/svgInfo.json?id=62649&pid=&t=1620375429281&ctoken=f_aDJVuZqM0UPeWPmgWDUf2o

**Comment by yisibl** [comment]
修复了一下，请再试一下
