### ISSUE TITLE
使用新浪微博账号突然无法登陆。

### ISSUE THREAD

**Issue by HRan** [thx/iconfont-plus#1957]
<img width="521" alt="微信截图_20210508162129" src="https://user-images.githubusercontent.com/8706737/117532326-865f5e00-b019-11eb-874d-994287a33853.png">

<img width="223" alt="微信截图_20210508162136" src="https://user-images.githubusercontent.com/8706737/117532333-92e3b680-b019-11eb-9868-8c93822e4ca0.png">

**Comment by yutent** [comment]
同样微博账号无法登录了

**Comment by yisibl** [comment]
请再尝试几次

**Comment by yutent** [comment]
> 请再尝试几次

尝试一千次也没用。'iconfont又不解绑, 又不支持找回, 我现在只能放弃原来的号了。

**Comment by yisibl** [comment]
现在支持注销账号，解绑微博，如果还有问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092

**Comment by yutent** [comment]
登录不了, 注销个毛线

一丝 ***@***.***> 于2021年9月24日周五 下午3:26写道：

**Comment by yisibl** [comment]
@yutent 请加钉钉群，提供一些账号相关信息后，可以协助找回账号。

**Comment by llukall** [comment]
微博登录不了
加载失败，请重试！（c-1202）
请问现在是海外用户直接给ban了吗
