### ISSUE TITLE
图标库本地下载缺失svg文件

### ISSUE THREAD

**Issue by 963761491** [thx/iconfont-plus#1962]
你好：在今天更新图标库的时候，我需要下载图标库更新到仓库，但是下载下来的文件解压之后确实了iconfont.svg文件，导致新增的图标无法显示，请问这个问题是官方有新的改动吗？还是说已经不需要该文件，如是，请告知

**Comment by yisibl** [comment]
没有 iconfont.svg 文件请参阅：https://github.com/thx/iconfont-plus/issues/1948，图标无法显示请提供项目链接（id）并把下载的 zip 文件传到这里。
