### ISSUE TITLE
使用Font class  下载到本地 iconfont.css文件缺少最长的那行url

### ISSUE THREAD

**Issue by kongKhuai** [thx/iconfont-plus#1963]
@font-face {
  font-family: "custom-icon"; /* Project id 2339279 */
  src: url('iconfont.woff2?t=1620878336363') format('woff2'),
       url('iconfont.woff?t=1620878336363') format('woff'),
       url('iconfont.ttf?t=1620878336363') format('truetype');
}

**Comment by yisibl** [comment]
请参阅置顶的第一个 issue



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月13日(周四) 中午12:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [thx/iconfont-plus] 使用Font class  下载到本地 iconfont.css文件缺少最长的那行url (#1963)




 
@font-face {
 font-family: "custom-icon"; /* Project id 2339279 */
 src: url('iconfont.woff2?t=1620878336363') format('woff2'),
 url('iconfont.woff?t=1620878336363') format('woff'),
 url('iconfont.ttf?t=1620878336363') format('truetype');
 }

**Comment by kongKhuai** [comment]
十分感谢！   在更多操作-编辑项目中 增加base64的 字体格式就可以了

**Comment by kongKhuai** [comment]
感谢！问题已经解决         


| |
16651618507
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年5月13日 ***@***.***> 写道：

请参阅置顶的第一个 issue



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年5月13日(周四) 中午12:02
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [thx/iconfont-plus] 使用Font class 下载到本地 iconfont.css文件缺少最长的那行url (#1963)





@font-face {
font-family: "custom-icon"; /* Project id 2339279 */
src: url('iconfont.woff2?t=1620878336363') format('woff2'),
url('iconfont.woff?t=1620878336363') format('woff'),
url('iconfont.ttf?t=1620878336363') format('truetype');
}
