### ISSUE TITLE
图标下载代码，代码包里面的iconfont.css不完整，导致小程序无法显示图标

### ISSUE THREAD

**Issue by xps2561774680** [thx/iconfont-plus#1965]
![QQ浏览器截图20210513172120](https://user-images.githubusercontent.com/49774491/118106043-c191d080-b40f-11eb-9eb1-a10ac2473c76.png)
![QQ浏览器截图20210513172200](https://user-images.githubusercontent.com/49774491/118106052-c48cc100-b40f-11eb-9bac-67350e3e5f8a.png)
那个记事本里面的css和之前的完全不一样了，之前的在小程序里面可以正常引用，现在就不可以了。

**Comment by yisibl** [comment]
请参阅这个：https://github.com/thx/iconfont-plus/issues/1948，然后提交 issue 请按照模板来。
