### ISSUE TITLE
希望可以增加 Gitee 账户授权登录[FR]

### ISSUE THREAD

**Issue by xiaochuan1719** [thx/iconfont-plus#1969]
## 需求背景

对于个人而言，现在使用的是 Github 账户授权登录的，但是 Github 有个问题就是经常性抽风，而且现在这种情况太严重，科学上网也不太适合所有人操作，希望可以更加方便容易登录的使用 iconfont 

## 解决方案

建议增加使用 Gitee 账户授权登录

**Comment by yisibl** [comment]
后面考虑使用手机号登陆，不考虑使用 Gitee 登陆。
