### ISSUE TITLE
能搞个以图搜图吗

### ISSUE THREAD

**Issue by he426100** [thx/iconfont-plus#197]
有时候光靠名字很难搜的出来， 而且太多图标大同小异很难筛选， 眼睛都看花了

**Comment by purplebamboo** [comment]
＝ ＝，暂时很难办。图像识别啥的不是那么容易搞的。尴尬.jpg。

关于筛选的问题，选择一个图标后，可以点击下载可以看到它所属的库，可以追进去，只用这个库的图标。

也可以直接在公共库列表页面，直接选择自己满意的公共库使用。
