### ISSUE TITLE
无法设置icon的前缀为空

### ISSUE THREAD

**Issue by KimQueen** [thx/iconfont-plus#1970]
## 问题描述
iconfont 再没有填写（即不需要前缀的时候），会设置默认的前缀为icon-，然而我们之前是去掉了前缀的

## 重现步骤
1. 打开： 编辑项目
2. 设置FontClass/Symbol 前缀为空
3. 出现：返回还是带有这个值

## 期望结果

可以设置空的前缀
## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
不再支持前缀为空，默认推荐都设置前缀，因为考虑到后面我们可能会开启使用前缀的属性选择器来选择图标。

**Comment by KimQueen** [comment]
> 不再支持前缀为空，默认推荐都设置前缀，因为考虑到后面我们可能会开启使用前缀的属性选择器来选择图标。

之前的项目是去掉了前缀，在项目中已经开始使用，现在重新编辑的过程中，在勾选默认文件的时候，勾选了一下 之前的项目都加上前缀，这样的话之前项目中使用的icon 都有问题，可以提供的一个方案让我们对之前的项目做一下兼容吗

**Comment by liuxinqiong** [comment]
这顶不住哇，图标库可能被多个项目用到，现在要全部改过来……

**Comment by fengchuanBIG** [comment]
> 这顶不住哇，图标库可能被多个项目用到，现在要全部改过来……

表示一样，我们也是去掉了前缀的  囧  你们现在怎么处理的呢

**Comment by xiehangyi** [comment]
出一个兼容的方案吧，我们项目很大，icon改起来很麻烦

**Comment by Jelly-Bee** [comment]
同上，能不能给个兼容方案

**Comment by kilosangma** [comment]
> 不再支持前缀为空，默认推荐都设置前缀，因为考虑到后面我们可能会开启使用前缀的属性选择器来选择图标。

能不能改回来 净添乱

**Comment by liwenda122** [comment]
卧槽，你这个修改完全没考虑到之前前缀为空的大量用户吧，不声不响就改了，那么多项目，全部改一遍，工资你出？还记得你们antD那个圣诞节彩蛋吗，这个比那更恶劣。

**Comment by yisibl** [comment]
感谢反馈，我们将重新考虑实现可选前缀，并且前缀必须符合 CSS class name 语法规则：

 * CSS Spec: http://www.w3.org/TR/CSS21/grammar.html#scanner
 * 必须是字母、连字符、下划线开头，且后面只能是数字、连字符、下划线，- 后面第一个字符不能是数字。

**Comment by yisibl** [comment]
前缀现在可以为空了
