### ISSUE TITLE
windows 微信小程序pc端的问题

### ISSUE THREAD

**Issue by MrsunJ** [thx/iconfont-plus#1971]
## 在windows 微信小程序pc端中大部分图标没有展示

![image](https://user-images.githubusercontent.com/38372294/118913400-f8aa3980-b95b-11eb-96d9-e74702e44cde.png)
## 相关信息
- 用户昵称：kb_jerry
- ID：a65b71c5f2f9-2209725
- ProjectId :2209725
## 相关文件
https://at.alicdn.com/t/font_2209725_jjce240grmo.css?spm=a313x.7781069.1998910419.44&file=font_2209725_jjce240grmo.css
## 平台/浏览器版本
- 操作系统及版本：pc端微信小程序

**Comment by yisibl** [comment]
先试一下这个是否可以：https://at.alicdn.com/t/project/2209725/f2cd21dc-979a-4b07-ac67-d700aea7c70b.html

**Comment by MrsunJ** [comment]
> 先试一下这个是否可以：https://at.alicdn.com/t/project/2209725/f2cd21dc-979a-4b07-ac67-d700aea7c70b.html

在网页中使用是没问题的，现在是window上的微信小程序引入https://at.alicdn.com/t/font_2209725_jjce240grmo.css?spm=a313x.7781069.1998910419.44&file=font_2209725_jjce240grmo.css这种格式的文件使用不行

**Comment by MrsunJ** [comment]
> 先试一下这个是否可以：https://at.alicdn.com/t/project/2209725/f2cd21dc-979a-4b07-ac67-d700aea7c70b.html

在网页中使用是没问题的，现在是window上的微信小程序引入https://at.alicdn.com/t/font_2209725_jjce240grmo.css?spm=a313x.7781069.1998910419.44&file=font_2209725_jjce240grmo.css这种格式的文件使用不行

**Comment by yisibl** [comment]
请在项目设置的字体格式中勾选 base64重新生成，再试一下。参考：https://github.com/thx/iconfont-plus/issues/1948#user-content-base64

**Comment by MrsunJ** [comment]
> 请在项目设置的字体格式中勾选 base64重新生成，再试一下。参考：[#1948 (comment)](https://github.com/thx/iconfont-plus/issues/1948#user-content-base64)

可以了！感谢🙏
