### ISSUE TITLE
[Help]找不到原来的登录账号了，只记得用户名叫“低俗幽默”，能查到原来账号吗

### ISSUE THREAD

**Issue by EasonGG** [thx/iconfont-plus#1975]

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖微博的三方登录。如果需要找回老账号遇到问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
