### ISSUE TITLE
购物车内icon下载代码 解压后无 svg 文件

### ISSUE THREAD

**Issue by WynnLin** [thx/iconfont-plus#1976]
前置条件
1. 已在设置中 设置勾选 svg 的选项
2. 整个项目的 ”下载到本地“ 按钮 下载的zip包内包含了svg

问题复现步骤：
1. 选择多个icon到购物车（资源库）
2. 点击下载代码
3. 下载的zip包内 无 svg 文件
如下图所示
<img src="https://user-images.githubusercontent.com/26760434/119478066-13c4e100-bd82-11eb-8ccc-e19564e58265.png" width="200" />

**Comment by WynnLin** [comment]
请问 修复的时间点？

**Comment by yisibl** [comment]
推荐添加到一个新的项目中使用，购物车中目前不再支持 ttf 之外的字体格式。

**Comment by yisibl** [comment]
请点击下载素材，选择 SVG。
