### ISSUE TITLE
紧急，上传图标失败，出现黑色方块

### ISSUE THREAD

**Issue by yifeng0212** [thx/iconfont-plus#1978]
## 问题描述
svg文件上传单色图标时失败，出现黑色方块，一直上传失败

## 相关截图
![9951622169331_ pic](https://user-images.githubusercontent.com/84950019/119924436-2ae41880-bfa6-11eb-9ca7-d10aca731298.jpg)

**Comment by yisibl** [comment]
请提供一个上传失败的 SVG 源文件

**Comment by yisibl** [comment]
必须按照绘制规则绘制图标：https://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.16&helptype=draw

**Comment by yifeng0212** [comment]
https://sh-obs.obs.cn-north-4.myhuaweicloud.com/%E8%A7%92%E8%89%B2%E7%AE%A1%E7%90%86.svg

**Comment by yisibl** [comment]
> https://sh-obs.obs.cn-north-4.myhuaweicloud.com/%E8%A7%92%E8%89%B2%E7%AE%A1%E7%90%86.svg

不支持蒙版、滤镜，所有描边也需要转曲。

**Comment by yisibl** [comment]
参考这个图标：https://www.iconfont.cn/search/index?searchType=icon&q=%E7%94%A8%E6%88%B7%E8%AE%BE%E7%BD%AE&page=1&fromCollection=-1&fills=&tag=
![image](https://user-images.githubusercontent.com/2784308/119953414-8fb46880-bfd0-11eb-8288-12e531555776.png)
