### ISSUE TITLE
希望修改已上传的图标名称

### ISSUE THREAD

**Issue by khkja** [thx/iconfont-plus#1979]
图标名称是中文时，已上传后，命名错误时，需要修改，当前是如果错误，只能删掉重新上传。比较麻烦。

**Comment by PineSongCN** [comment]
+10010；

**Comment by yisibl** [comment]
在「我上传的icon」中可以修改。http://localhost:4000/manage/index?spm=a313x.7781069.1998910419.10&manage_type=myicons&icontype=uploads&keyword=&page=1&icon_page_type=all

**Comment by PineSongCN** [comment]
能否增加个入口呢？

**Comment by PineSongCN** [comment]
> 在「我上传的icon」中可以修改。https://www.iconfont.cn/manage/index?spm=a313x.7781069.1998910419.10&manage_type=myicons&icontype=uploads&keyword=&page=1&icon_page_type=all

能否增加个入口呢？

**Comment by yisibl** [comment]
入口在：
![image](https://user-images.githubusercontent.com/2784308/124061187-0675d300-da61-11eb-90c3-82d72e6fa102.png)
