### ISSUE TITLE
下载png格式，png图片失真很严重

### ISSUE THREAD

**Issue by lwdillon** [thx/iconfont-plus#198]
下载png格式，png图片失真很严重

**Comment by purplebamboo** [comment]
额。。是所有图片都很失真？ 亲 可以描述的更具体点吗？

或者说下是哪个icon有问题。

亲可以收藏这个icon，然后把用户名发给我哈，我去看下。


另外你用的是什么浏览器呢？

**Comment by lwdillon** [comment]
对，我下的都失真，边缘很模糊，有的边缘甚至显示不全，http://www.iconfont.cn/plus/collections/detail?cid=24这下的的16*16失真严重，加油！

**Comment by purplebamboo** [comment]
可我看着还好呀。＝ ＝  可能程序猿要求比较低。

亲  你试过chrome吗？ chrome可能效果会更好点。
