### ISSUE TITLE
微信小程序中如何引入阿里图标

### ISSUE THREAD

**Issue by mitangjie** [thx/iconfont-plus#1980]
**阿里图标库的引用代码变了，以前可以直接将下载的iconfont.css代码后粘贴到小程序CSS中使用，现在不得行了，以前iconfont.css的头部代码是这样子的：**
@font-face {font-family: "iconfont";
  src: url('iconfont.eot?t=1619688076892'); /* IE9 */
  src: url('iconfont.eot?t=1619688076892#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('data:application/x-font-woff2;charset=utf-8;base64,d09GMgABAAAAABXkAAsAAAAAKSgAABWVAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHEIGVgCJEAq6cK4oATYCJAOBJAtUAAQgBYRtB4NsG8YhVQQ2DoCg2dclolITyP7/mNwYUypQ+f9gCChY7DTOV3JyKFXlCfmiOYQGdzR4oN8g4oJ1SC8yfdpDyD21LG53CVBiK5f0o/fuBn8MGp5EwJWHhw2lJKjWsvceA0hVKY+gUxGSwGgEJyLVhGQsgcDcBlhR9+MP/DZ7/39EotQhYkzMRB0miIQ2OjBrUWawclHObaeg3s2tcRW3qZNFu8gQWSWDOVMpKUqBguGOBwcjAtk+4AaK7I/8lb+WnHDbhV2EwBgC31GZoxdAQAC0+fnA/xxw+UfYBjIq7TwFt12cHbWmCRIkssHHd+v5AkUSUWu0gDFnf2Y65Npqm5pf86UPG8OSVm9P9rrmMBYgB0um6Bs8fDf53gG1xL5AQ/GosSlOxwYupigsgl6ACWP/N1Wp1DF3FjYgHQuHoAJ4X3JsnZUlZ55n5ExlX6fUNQYfCxBdttJlZS6UssKU9RX1lcAAxAo1bTlBEp9Cl3rVy4ex5d+DVXDGYc6hYhRW7KfXJKg0+Ii1jfcIINCwowTp9Ci+DAi+khahJVZiCE7zhfTAiJVdZiOAe/59+sI/ARk9h93a3H89AgSxZjXlP83Occr8KjycIQeTkEf2IqzTHcz2J3noiMa4tA0sXd9ghMCzJVjGs+PIhRt/QXjCRfvARz6lm7dF1E4NY/GdbT6JO9itFj+13RLO0scKI/XSbFHbIUxK7IUQIhlrxUv0kkn5k0CfzeRUygxCM4tNo+sJHsMuVykEXKvE4bJwKCmfKRJrdfoPT2rUSEVsXQ3SD20mEHgCfQgCDCOI0I8whTEEK8Cj8YBmhF0gGDkC6hDOgajIBYEyIjcEEPkA8ghftQQiP0APwh8SIgiqETwoIsJgBBEOLQgptCOioRWRCLUIGVQhJsIQQgGNiFQYReTAOKIIBhElUImYDjnEEDQhxqAG8QlKeLOFerz5QAPeoqALbyLoxptYiaIq5DJEA4BOvFuUytYx2J/FFnAGFXNUvZJCacqiSIpGiSTMFLVdunxEsihivo7ecpe92BXHu5xbqyfICHnZ7IWgQITcoYcvaZLRDGMz/Ymet29v0CP22PQqlkRGCrG2/iwR03R48239HRTCWVfilHJJ3w+G6Euk8gCoDR+a+obIy33ryrhaG6aJ1jTNqGyPuPaibrxA9Oc08vwWpujC8mxZM1y7SqWIg6a7t949jN6ldTbiFGoptbfrb0vSXrWONNtwi8mE1G5uX9uQrvVejHkE8Grkw/FQ59V6v9H99HafzvNwnqlcVuJuuZikoYhzuZZT42a7E6mj5ojDapZqVME6ymmFKbPulaxEnKs51cwcioCCELcu6fGSauslWvyGTRDwIX8ABv3YZz5gI2FkOuKI5vnVF11qwuXnOZegaXfWaZRpzNOsKAbzYPoNtoEtECRgy0yMzY7G053FHDXK5bDrWkLReFdP3UQhdr2vjUov3C35so3Hw9dao37FuzTlOFJICMVfHP8uCu+8Xhxka+XJD67+qqRYn/PzY9YCwaRu/zmSNgzXxWGby1pnyPxufgDhh+X8gC5KiEmk+sOQqk2gQqWPOJIuECtIJJEdfx+A9wqZfo0Xsa0ayewmqxjb3qDhqhrHdlk10rnniIN6mEiFsc4kDkLZFCilCUWgCtVQusWjWoqrto5PLU/aCuYZ0XJxXDZcjN/lEpE5lSSNx7rV7tS3vuOz3pvf6PYT7V1sQhcSKVy9ebZkyFTN5W9NZqIZ6Vv2jcpRsla8kc2UDp9aplJYYHXXKmPESWRsne0jiapqlO1xjXsDeipPtdyEXqopztCYIlKqcbZrFDeEvWe8mJWcNsmADqR9Toha2sOdGH9Ft0Y/6z3I2uTvqa2HL52+XsqjDWJSn/MQSRxpZSPRBXOorCGzjGMM0DAeiQHltgshHk4VQWzzdQgZFvxiVEBLdVWoetY9ChSKtwk3P5juvrHha/rpGZlHI4BKjgSlCr37Zeic0yDReX3jdxlI5RRBAgHn5oilplXVG3Rh7h6lZt2reqOWklq6IAYEzN+SN7o3hqmUkKRKnwOyd8tVete0bIjKyQ/wfg4y1yd08tE5J86/ixdEmy9vfrzAZALOIoU6jjMcQUWYsFz8DAuTSkptVtAotA3zfz2Jr/wxDDK/zzgVAGhVxmVvEE49JYqG45/CtDeJi9V+kKjoAMMt8jA92SBZHceuB6FVU3bBvjKzImo5TzXdYjUpHXUq25end5iRWHdArefKbfVW70nbs2roa57qPhNpfBUw2mrctWpsFhUL+dGIVWgV43yhIh4c18YiFPknMUCiIIED2L0yDAZsOFKKfhA42ccxRKykwH2YXxuFSKMJiezfCDY0VKjXjWso5ZY6n9QkEIM9wW35trWbOrDBKdDiwLWibJViLCEBnrTTKhSpOdZtst0Bl2CPapbTSkrvRCinGmlyvPjF8In6mJMA2U4IQwOG4WbTammAVlCI1SC81rP8BLQ8HLarAFxuU+logXkHxHReKPU5mQA8Om3xPQvjRygzQ6B3wVbNAKtlxAWflVbI+2X3D6+zKcI6I5B7QWuiWObl+hCXiWCSPvHTm+zGUxpdrtNGr7UAKINjW9XGfGbD9jLla61uc4zrIj0ZnpTjB/HRgqILuCOkceDT/JZ6QH8xGnnhyAuR6Iv67KfL7n9bHnb+JweOhiGoUjPgt26y68AXYKfpGRz00Rv2LegP2uess6ZupEtjY0Qvhaj9GnF6hz1paEXbs8xVvDMWmjpEqKvXadaqTOduXsThK707vccu+ZL2oD/FCJ+8zNy9sWxNbCjQLVCku4wkJSCyke++Efia4aStiZSVVsM8OQn9Cxo/ZCnEBITWGP+6HQE4/okpvr6rDnyZ3x8LdKUnCIYSaENAR1qQNue37nXL2ILcy9cigcJ8EGNAX4E7fzxYjkyjZDUYZpWdNpkNF3uRjIVKPUqWmVImRhs39t/j8L3Bd6L9Glpyjg+RsH8djm0OwBYX433sL3PNJ/aidMtu0DprbrEnW8REpxoI9aNWney8Hv6ue+ye6u72ngxeuZv3Bwpj6XsPhUrNgdXp1jBaN/pBoFAHgDZwECTqs2CCHQKh5alaLfGuOikqapnSTJt5pH04v2p8Vdx6TgjCB8XBibZeGDuVdstq7rbwAxOvd9iP2H3Eh/N/Lad/s5f+cgv6c3++CUGUfZet0cK1LkJGZneqVpNyNWnGzMZ63PXrM1u1ubyZMxDKak13J4u6Zo1y9dif3t3JrcmQk1yerFttSHn95sGb14Ef6En22IGBszR1U+MiK65VV3Gx7vNWqwArtRFJRRPG7kFpV7y2u+1YzOtJ/S9FFtwwt6bNQp7/T+PGsowm+Rxzl9KqKeWOfoslC+Jq6Q6drmveHlAj+QqXG4sOLzxZ7AW2nwRD2O8/qwZxQ79/NyThHCANvqJqYHy+slUJykglGFoBd4fDuYOEs5twd9xxcbvxoP1C+/OK1CFYCOfvJk+WFlGrAyerpw2iB+y2q6YCB1PKO8G65atWaTiltv0qNdvHRmGzdcaMW3RIn66+Uzdl+uiUzgcQhihxwz9/tiThHOB2yVrbPew1VWwuW2VB0iKV/+bNGqipRB5RLc8/hB0BN2+A5CMqm+sTvL25Wnl3t4gmFjWdfOrUX78euyy6oqSIAGyfWStW8WfO4q/W8NfMnLlKoEnUSwRrNILVH02s4sudsteJ6+rF6w6J14NO76G+Z249tw4h/MZiadhH7VLIF7Ed2Cp+eDhfZX1mkULutAHe7tr11+LvLnezic0j9uMVkoFCHjOA6VoBGn5Ce6exzYgfquMUcnSoH7J5bNZism5X4S4d2WzL5U8xXJxjtP/n5xJ/o3GxXAGm3dJ8RYHqvfWoaM8eEWrIIOvRx79saq0Tg7uQKiwAV4yAGIJam18QVJC41ISxlDa5Q1I/YyeDvEpoeesWURr4U7BM9jYQhLXQchXJZOcMSf2qydSlDJOl1HjzGpr/Za+PtLx9kxgd+NZ8GfPXZfrLM3oy499mccO6yTWKQkrEOGkObV4Zqyk5zFr8Mq3nFt3qmPC2NAcORpSKG7K6YkJIFHMKaU7vyhp9knY07vTwmD14apfJapi7KSVm5JjgrlS6FMnNRTRPmpuXLkFcdHW5EieZRMpktkyZgOthhDCOoJadPElXgveEGDvb9Nuom+sNmreUwm3sK9Pje1aleaWt6unTr4z/6ULKXbWhqV7jZdPPKJuqe/DQZHlcj/Kl/zaLjzsHmuof7LO32cZY/00ls3C2UMte7eVYb7Pf+6CpfnAtso3t/0IZ17McaoSEwgO1WS5JbN+b9DqzugM7e/2WOMYTy30/7pSnzGbESAOReJutEdLSDH/2fC1K4tCijL5yRBFurJUg5eXM8S2qTP5Iz7Jkp9lfIiWaq/An+FNuhcd2Nc2c+4W3pXJVLU9cLF/9xy2lHbaX1LBKm1hrS811rJrcvAlknbmOnJeUt3aUNbo2rxUprXfoRyQjPSE/H2AS0yKTRTBdFigCUa+iRwyiwGWmBBb/sO4b3tgx60TYPqcsFstYp+FLcE77KnoUvXKR092P1+iMWSynrH1hJxyzjPHfdIeDe1Sqdp4VHuNeUDjlEojkIQfggsMQmUjIcVZc4GJG1ryV/n2u1kaYwwVFUMLT9O3c6dzt0xIDm3DA8FauwMEiBnG/fq2SNOgAt6vD1yb0YbduYUh9BjiJVmNHIRkZCFKUAdw0CAb+xnXKJgZEh5+FrsNu38YkrXOAm5oDz24xRUfGus6d7cQCmTnWRdaxdGTcjlevd2Ag0JFP1ok07dd+GTRksuKD2YoOd5vsNTMfHKLmc/G9eG4+t+Da6ktMek1K9FRQQK9eT/7PbNl9vBn+vgwfXy4xyzYzWZkmSTaFmnbsQFoYBnP5edm5BZ94CPGlX7L/jZOK7AQzLjNXeYGZV5CXbXUPeLPLiwqzM8UxqFYokYoGooUqSxV9ot1lmr21PY2Ty2nNkjwiyZMVGcgHea69fUWZykpV36Cy5FpqXJqb0Q8ffCXKgWf2x4/9Bb7tR+Q2Vx94lRHtfcOF88GuRfghCK4i865eh2wXceJotNdXN7ZMaIFxzzh7lUDYSwAlzz3/fu96R/NRwXVyi3cEdw5OS7eka03H5XOoesooRW/pGG5OBeooFdiXpHmagJDy56Q22j80lf6tXrU1yqgl9F82Z7yr/tlP/sbCbMPtKk+RFf1OG/M883+9pG04KLYwLzfsN729Pbdkenq6vqamrC5QmejT00pm5BqV4tlNNSrzLwPYRFCW9nWaBd6fVia4c4lrxZcCD1VyaCbWJjTzFup/nqszCI/N0yoVBC1BoeTvfR1BM6Fp9WuD0G5NQFNgEMjuPev2Wa/f3BZKhYGofoTAmqJ4ZerUPSCEfiBYTJG/NKXufeuKcACoIT19xy/DIEQOALSeePV32whoYGTb3i01vffUSP1Bmto86PS9NKK1KrOWmAay1tevL5izggugnAz06Bbwl7fhHyLsX5QnUzozM+/pYLH8/XuNtcha/ZJgNZE0d7apLwQkH6JQ2HRfOvv2qt5Xz37TwN93y1VW+thD70G3eHru42tXIzTmaQgMm+GFgKv5YbYgNJOQ2q1o9EmuXq5hppjk1MFdNLOCRLpdm6tXRs9UwVemunjtZU3lefKmTvDMZIHi706e6zlXZ+GcZdQyWhKtjCoTVgsnztqQs0FS+MUAFf7oE/YT7YjWHP2jzWNS6Zib7uyZUWYeeZRcyNSdPq1zu2gICjp8KBWCj1snb/15N7nCWKQ8ViY3fmQsL+tmKOzk+u5oJD8fkT5K1APRyDFfdyp8og7PwwD0WzgSR5dKENmJTSpNxHYiRh80jhgq4a5xFY9rNOg54jHiObh0nHMkPNop8NW4anwRFbiGGBfeYnTx2+OTLPcT4+PXTl+roSTuJyUktV/33lmEdxBx7qL7sTFGFkVHmUfpTiHcY4xh+9G7HIZrDG1hRHCLcuzH02V246Nt53VFqBgQMGeo8pRc1Je+5ppkIsJcU6HQrt3OFFOC3eIH9gP56WUDo4V3tY2Z9v3329uBSCBCO7cumLiLa3XYKsB64gwi2PUd5k5JQwPV5HJkti+uwthNbxK+yCbCSIR8ys8oYrqAl5XDmh1BHCB64B1LNsdEtwfFSfJtlPFxxEMEtzYjPCKM9BvWqwUqwVaBxtxCb2KBbyh/KZ90et5p960p6mN4dD45mPanPKp8dC3X6pAxN398Ptf4B/sHccBsgFha0jnTLjUSBokwP9ocAe5Kf8BmoxWdXYkBD9PR2lpE9hL2onAQWncBQadt1f61/GsxMpPikai1z182NO75A8Mfqo5toNLAZlJoFcZCOw0vV+LI2BoAg9YwFslRXCqAU1R21CAmTEOq0XiUPXYU4/jnt2Is7YsejITah7CLmMBgAIAD9Ct9dBjj5yX3cHzML4jKhnB5WDT8RzBRnpP75KNpg4+tJf5hNIUvqETHVqLb0M5Jc/IxLXoGC3vR9f5W1AAWF+0HMHRiV7Gqy/of5qLf8bO6T7SdL0N2+U84oSI+WSc+1P/WWZUqDmCrsNgzwrqAOAf9m0cP+0Ig/y+x6P6u7qVc7MYJeeI/wgUWQADO/xTc7gjui/vdRTPdcK+g32R46Z4reOTxNMOi67U7/fmAWOOAGxw7JRLVwqTrTQDngWFTeEhSmNLO09QUputHwfiMTmAVGBDAkfC4yZ4xRkCGgBg8EIAfQwIPkH6dDGZQARggOCIAuMP8SwwCDNgZgwINhmMwYMAFHjf5QYwRmMNoDB4YCBZDglTELEoyOCMZ/3lUAl2gVtVJoWGymV3m1sGf4CTo5HXxdb+QMhap26ubr5UfQJDysMh7d1eKVTZxq94v7YMQWHWJGzDlypfSvV1fW5HlleG2N49KoIuZsFaqkyMaJvv4Mg/8+U9wEnSKOO2b4y+kjB+v3LpyI8F/yCR12roY897dKYRYpR+buFXeCYFwLWOlE9fWgClXfAqte3NNLmdl5avyU9p5JTP6zsh+2btUVE1I3TAt23E9fzyZzuaL5Wq92e72h+PpfLne7o/n6/3RVx5nZzyJptunUxbMHmfGAznH5MZG+CAXLsJGhRNs3WWDen6CfJkh9GVwRmzr5jolPlzWbdjookZNnUyyh7PHu1n2LEaTux03aIHmJxYvGPNLn9TgI588pW5H/2BFoLCX9UyKNJ69TLPmExrNTyAdAFt9YeSImjdZgu6QAkLlV9cJ7b12AIqiAJ6GeTBHvCsMqmykwvLnRVeBRM7CkYljkUtZPu11abg7DRtaZgJn8AqZUWS83F2UpFKDq0bhrui93aXRqYyoZ+UFS6g1FfDCyj8ii1qj+pQXvp3UoaCotwcA') format('woff2'),
  url('iconfont.woff?t=1619688076892') format('woff'),
  url('iconfont.ttf?t=1619688076892') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+ */
  url('iconfont.svg?t=1619688076892#iconfont') format('svg'); /* iOS 4.1- */
}

**现在是这样子的：**

@font-face {
  font-family: "iconfont"; /* Project id 2224009 */
  src: url('iconfont.woff2?t=1622214619278') format('woff2'),
       url('iconfont.woff?t=1622214619278') format('woff'),
       url('iconfont.ttf?t=1622214619278') format('truetype');
}

**照搬以前方法直接粘贴进入，根本就不得行了，那位大神告诉下，现在在小程序中该怎么使用？**

**Comment by yisibl** [comment]
参见置顶 issue：https://github.com/thx/iconfont-plus/issues/1948
