### ISSUE TITLE
iconfont项目不见了

### ISSUE THREAD

**Issue by wky0527** [thx/iconfont-plus#1981]
登入账号，发现以前所有建立的iconfont项目都没有了，求助啊，怎么维护以后

**Comment by yisibl** [comment]
是不是登陆了其他的账号了？换个微博或 github 试试？

**Comment by wky0527** [comment]
你好 我想问一下 如何查自己所有的github账号呢 我只记得两个 登入都没有


| |
王可妤
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年06月1日 ***@***.***> 写道：

是不是登陆了其他的账号了？换个微博或 github 试试？

**Comment by yisibl** [comment]
之前的项目 CSS 链接或者项目 id 还有吗，我可以查一下

**Comment by wky0527** [comment]
有呢 2518613 谢谢啦
| |
王可妤
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年06月1日 ***@***.***> 写道：

之前的项目 CSS 链接或者项目 id 还有吗，我可以查一下

**Comment by Nixiak-nan** [comment]
我的项目也消失了。现在只剩下代码链接，能查出事哪个账号的吗？https://at.alicdn.com/t/font_2308396_zp6gvfzw87q.js

**Comment by yisibl** [comment]
@wky0527 是 王可妤， 3800113552 这个微博登陆的

**Comment by wky0527** [comment]
收到 感谢感谢


| |
王可妤
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年06月3日 ***@***.***> 写道：

@wky0527 是 王可妤， 3800113552 这个微博登陆的
