### ISSUE TITLE
[Help] 请问下这个SVG上传的时候报error，是因为什么问题呢？

### ISSUE THREAD

**Issue by sunningoo** [thx/iconfont-plus#1982]
## 问题描述
当前svg无法上传。因为github的编辑也没法把源SVG文件上传上来，所以截图如下
![image](https://user-images.githubusercontent.com/30685817/120174100-4d409500-c237-11eb-980e-095ca1b8771c.png)

## 相关截图
curl 'https://www.iconfont.cn/api/uploadIcons.json?ctoken=NAMCJysxSDdxLMC-fDpccd2V&_csrf=NAMCJysxSDdxLMC-fDpccd2V' \
  -H 'authority: www.iconfont.cn' \
  -H 'sec-ch-ua: " Not A;Brand";v="99", "Chromium";v="90", "Google Chrome";v="90"' \
  -H 'accept: */*' \
  -H 'x-csrf-token: NAMCJysxSDdxLMC-fDpccd2V' \
  -H 'x-requested-with: XMLHttpRequest' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36' \
  -H 'content-type: multipart/form-data; boundary=----WebKitFormBoundary1K3sNnxxyft8DnKH' \
  -H 'origin: https://www.iconfont.cn' \
  -H 'sec-fetch-site: same-origin' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://www.iconfont.cn/icons/upload?spm=a313x.7781069.1998910419.d7543c323&projectId=1511895' \
  -H 'accept-language: zh-CN,zh;q=0.9,en;q=0.8' \
  -H 'cookie: cna=HkkxGLXGkGQCAbaWFlkrVg2E; EGG_SESS_ICONFONT=U8AXvqwdm-42-umGXGwgKq_Emj2wuVCkA87TjZ3dn6xm2T4whio3sIKoy4kjkuBSusLMQ-0MhcjWBE1FwhfGmMbpO9xPCEANAHIhoET_7kLMg-qVGhDYJaXU8YYDzntA36gDZGVLVGzr3YlM1x0N9yz0erhpKP9313YD2HeosAT4Ps_XtnRobU8gSMs09ePqgLG9ZkcahifMx1y6DV2YG2aWvmjl_Vw78RKbna5VemSkzHIEgQaJjP9IpPGUKxUujqkf2NyIblEbq2nunPap9X7ykxPOvlaJsyzmFpV-AiHv76mqH2BqauojdnC56wEOPrY-L3wq_NX9kEnwekW2rvejkRUZFpROTW4pkjJ059u4-l7ejU-hTmGwxDZHhTtiXYb04H3br3UVOmO77eugtrY9Bi7NhTPZleYdKr-4UAIstEn6R2IRNJ85ygxeiyB6Txd4EjvpcEeIgoIr7v8UY44WhViHUqWY6dGOKxzV81L6iWEqsVv2tGN9XWKMXCct2U68aAWw5NAtb5ARLHmsvvisfXxVpjhQmFQWHToQsoJ-_kWC2v6o5D9UPzabTsJODVz0B3pYGUOYcyE6oC7yygDF8d3H6i4oHP6d-g555fHmvnvCmrop2r_131rNUCPZaUCe8VFh4mar30vS1DORvCgJAxLTE94DHrq2XDInL0xqvRHm8nlJA_9mTtRoHYMLeS9I7L3-kcCu3Id_hbzGo1lUi99JPhMzQBrGuuR2FwLCJJYuPXveNgswoKj8aDzsaQuak1Rm0URe_lSqrZId6cN2dEDsTFLHNo-KaNdyo3zdbiB9Bz_GC3mSW0y-7ZB_0bIcS__3Cf6XjMn09XHMjlru3bpn0aZvsCqzMSUdlJS7D9zbJ7iq-zQqgifrovqxqwfeMDImKuzMW0TZTjcwv8I0tpqtKELnonFHgfuk8JYfHSL4YwoJdxeyjWx6TwqceiN_3fwcG8c-n7FFdLlT2G_v9zbjNmIJN9FcKpqdUxVF0duKm9i7ezWJ6YnL9AUlewz_bCER1XTe8bMahLDbuW2AOgrrmKBk9KAyRbel4NjlsagNW3M4UsvyTy1naKU6OQd2KNezHMkLWZQ4Y9qUN3tbrIOh3Qg1E71vK8qaGx_8KW9j0itcLLHsI5iD-rra0vmIDM-PUk4pukbTRrgA-vEbQUgupd3bRN-hXSCiIYF1u1PnYZb2CNqAvnJpSv7q7JFIr33QzJCWCXT1HYN2j-d_uGlKNc9NF-5KuHCEZ_p8tcQ_0JOkLNwVjL-4n6G4f5uePaWuqnjXJ4gAkQWdiCtO-8EsH0SnICo6ZU7IpSHgDAUDHK965_tNqS0lGTOkF6iIe5WwM8xiAH3_6x82aiqUHoeqcnpUvNUDoonzKFY=; trace=AQAAADmWeCpnXg0AWRaWtmpxL5t2Xc56; ctoken=NAMCJysxSDdxLMC-fDpccd2V; u=16828; u.sig=pFp09oSU3WGX4BWPihDk40olwDC_FKYdEt7y7bL56Wc; xlly_s=1; locale=zh-cn; isg=BGtrNqZYjwZEAOzLMCXAvDZh-olVgH8CNjSict3pIKosfIjeZFBdU5Oa1rwS3Nf6' \
  --data-raw $'------WebKitFormBoundary1K3sNnxxyft8DnKH\r\nContent-Disposition: form-data; name="icons[]"; filename="icp.svg"\r\nContent-Type: image/svg+xml\r\n\r\n\r\n------WebKitFormBoundary1K3sNnxxyft8DnKH--\r\n' \
  --compressed
![image](https://user-images.githubusercontent.com/30685817/120173409-96441980-c236-11eb-947c-36f96603c6cf.png)

**Comment by sunningoo** [comment]
是因为不支持渐变格式的svg吗？我试了很多渐变色的svg，都没法上传

**Comment by sunningoo** [comment]
无

**Comment by yisibl** [comment]
字体图标里暂时不支持渐变，请关注：https://github.com/thx/iconfont-plus/issues/1938

**Comment by sunningoo** [comment]
感谢哦，后来看到文档里面的描述，所以关闭了问题了。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 一丝 ***@***.***&gt;
发送时间: 2021年5月31日 18:01
收件人: thx/iconfont-plus ***@***.***&gt;
抄送: sunningoo ***@***.***&gt;, State change ***@***.***&gt;
主题: 回复：[thx/iconfont-plus] [Help] 请问下这个SVG上传的时候报error，是因为什么问题呢？ (#1982)





 
字体图标里暂时不支持渐变，请关注：#1938
