### ISSUE TITLE
生成的链接，如果换了能够维持多久

### ISSUE THREAD

**Issue by 2395000206** [thx/iconfont-plus#1986]
![image](https://user-images.githubusercontent.com/58016208/120302993-0028f580-c301-11eb-98fd-6f4403a306f1.png)

**Comment by yisibl** [comment]
每次生成的地址理论上都是长期有效的，这是存储在阿里CDN上的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月1日(周二) 下午5:44
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [thx/iconfont-plus] 生成的链接，如果换了能够维持多久 (#1986)
