### ISSUE TITLE
请求Bug

### ISSUE THREAD

**Issue by dxxinliao** [thx/iconfont-plus#1987]
## 问题描述
请求添加新项目文件夹时报错，创建新项目文件夹报错，状态码403

## 截图

![image](https://user-images.githubusercontent.com/49810561/120409437-7ec67700-c383-11eb-8333-9d9394fe49d0.png)
![image](https://user-images.githubusercontent.com/49810561/120409466-8ede5680-c383-11eb-8a62-73f4b67b7ea3.png)
![image](https://user-images.githubusercontent.com/49810561/120409515-a61d4400-c383-11eb-977c-a5ced3131632.png)
![image](https://user-images.githubusercontent.com/49810561/120409530-af0e1580-c383-11eb-8743-b159b8bcef95.png)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
无法复现

**Comment by dxxinliao** [comment]
我这边网还好好的，就是创建项目的时候弹出error提示



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月7日(周一) 晚上8:34
收件人: ***@***.***&gt;;
抄送: "廖 ***@***.******@***.***&gt;;
主题: Re: [thx/iconfont-plus] 请求Bug (#1987)




 
Closed #1987.
