### ISSUE TITLE
在旧版上传的图标， 新版网站看不到了， 同时新版再重新上传图标，也无法查看

### ISSUE THREAD

**Issue by youyouku** [thx/iconfont-plus#199]
在旧版上传的图标， 新版网站看不到了， 同时新版再重新上传图标，也无法查看

**Comment by Muqing1221** [comment]
亲，麻烦提供下id
@purplebamboo

**Comment by purplebamboo** [comment]
亲  看不到是指什么意思。是说上传后在  待上传界面看不到？

还是说 是点击完成上传  到了我上传的图标的界面看不到？

如果有问题的话，可以把svg发给我们，我们查看下。

发到邮箱  xhzhuweikang@163.com

**Comment by youyouku** [comment]
在旧版网站看可以看到上传的图标，新版看不到，且上新上传也传也看不到图片 
![qq 20161123132447](https://cloud.githubusercontent.com/assets/23650241/20551923/92abcff0-b180-11e6-904f-de5c35bb226c.png)
旧版  
![qq 20161123132729](https://cloud.githubusercontent.com/assets/23650241/20551948/b5008cb2-b180-11e6-8019-122f14a183e6.png)

**Comment by purplebamboo** [comment]
是因为第一个图标  015_mifa放大镜  这个图标的path有点问题哈，有非法的闭合标签。

新版校验会更严格一点，已经帮你删掉了哈。已经可以了

**Comment by youyouku** [comment]
感谢
