### ISSUE TITLE
最新的iconfont ttf与woff文件下载以后在android的浏览器上图标不显示

### ISSUE THREAD

**Issue by qiugc** [thx/iconfont-plus#1990]
最新的iconfont ttf与woff文件下载以后在android的浏览器上图标不显示，老版本的文件在android的浏览器上可以显示，最版本的在pc的浏览器上可以显示但是在android的浏览器上就不显示

**Comment by yisibl** [comment]
请按照格式提交 issue

**Comment by kilosangma** [comment]
> 请按照格式提交 issue
我也遇到了这个问题

**Comment by yisibl** [comment]
请按照格式重新提交问题，否则无法排查
