### ISSUE TITLE
下载本地是否支持项目下的部分图标下载

### ISSUE THREAD

**Issue by trust-font-end** [thx/iconfont-plus#1991]
![C0BDBBFA-C572-4654-88C3-BAA8CA0A668E](https://user-images.githubusercontent.com/85279034/120612735-144b2f00-c488-11eb-990a-8b227898463e.png)
如题，请教下

**Comment by yisibl** [comment]
不支持哦



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月3日(周四) 下午4:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [thx/iconfont-plus] 下载本地是否支持项目下的部分图标下载 (#1991)




 

 如题，请教下
