### ISSUE TITLE
[Help]帐号不见了

### ISSUE THREAD

**Issue by mixice** [thx/iconfont-plus#1992]
## 我之前好像是用QQ快速登录的，但现在没有这个登录入口了，现在帐号退出了，再也登陆不进去了，其他登陆方式登进去没有我的项目【十万火急】现在该怎么办？

相关信息：
https://at.alicdn.com/t/project/2580699/4d1c4e68-ed35-444b-83ad-857b3ca88398.html?spm=a313x.7781069.1998910419.67
这是我之前的项目地址

mixice
这是之前的昵称

**Comment by mixice** [comment]
通过搜索找到了我的UID是7683515，但我现在怎么登陆进去呢？以前是QQ注册还是淘宝注册记不得了，你们现在都没有这两个通道登陆口了

**Comment by yisibl** [comment]
1178715667 这个微博

**Comment by yisibl** [comment]
如果还有问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

https://github.com/thx/iconfont-plus/issues/2092
