### ISSUE TITLE
[Help]iconfont项目不见了

### ISSUE THREAD

**Issue by iimeepo** [thx/iconfont-plus#1995]
账号有段时间没登录了，现在登录之后发现之前的项目都不见了，求助呀！！
登录的账号是微博：ever_befour@sina.cn

**Comment by Liuescn** [comment]
同问，感觉莫名其妙...突然登录就失效了，然后登陆上去项目就不见了，无语

**Comment by missjixiang** [comment]
同问，项目中的图标不是最终的图标库

**Comment by yisibl** [comment]
请提供微博昵称或 iconfont 的项目 id

**Comment by yisibl** [comment]
如果需要找回老账号遇到问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
