### ISSUE TITLE
github快捷登录{"code":"404","message":"failure"}

### ISSUE THREAD

**Issue by wxthahha** [thx/iconfont-plus#1996]

**Comment by wxthahha** [comment]
![image](https://user-images.githubusercontent.com/31772481/121455962-e3af4c00-c9d7-11eb-83a4-635dff0da7ec.png)

**Comment by wxthahha** [comment]
![image](https://user-images.githubusercontent.com/31772481/121456036-fc1f6680-c9d7-11eb-878b-d6ab5929e1ca.png)

**Comment by wxthahha** [comment]
救救我 救救我 等着改图标上线呢

**Comment by dyyliao123** [comment]
等着用了，麻烦处理一下

**Comment by loofk** [comment]
求尽快处理

**Comment by dyyliao123** [comment]
授权失败了

**Comment by yisibl** [comment]
收到，请稍等。

**Comment by fangxu864** [comment]
加油

**Comment by wxthahha** [comment]
加油 感谢

**Comment by sunshine-fr** [comment]
害怕

**Comment by MarkGor** [comment]
我也是...无法登陆.....
在下拖了后腿，至今没开通微博账号...
至于阿里域账号，更是没有....
一直只能使用github进行......
希望官方可以增加gitee的授权，
或者增加支付宝/淘宝等的授权，
qq/微信，自有账号体系等的授权....
哪一天github被ban了，我也有个底.........

**Comment by MarkGor** [comment]
我也是...无法登陆.....
在下拖了后腿，至今没开通微博账号...
至于阿里域账号，更是没有....
一直只能使用github进行......
希望官方可以增加gitee的授权，
或者增加支付宝/淘宝等的授权，
qq/微信，自有账号体系等的授权....
哪一天github被ban了，我也有个底.........

**Comment by yisibl** [comment]
> 我也是...无法登陆.....
> 在下拖了后腿，至今没开通微博账号...
> 至于阿里域账号，更是没有....
> 一直只能使用github进行......
> 希望官方可以增加gitee的授权，
> 或者增加支付宝/淘宝等的授权，
> qq/微信，自有账号体系等的授权....
> 哪一天github被ban了，我也有个底.........

自建的账户体系已经在做了，后面直接统一用手机号登陆

**Comment by yisibl** [comment]
GitHub 登陆 API 变了，我们已经调整。请再试一下

**Comment by wxthahha** [comment]
希望能增加关联账号，比如github和微博关联，这样能同时登入

**Comment by wxthahha** [comment]
谢谢 辛苦了

**Comment by MarkGor** [comment]
> > 我也是...无法登陆.....
> > 在下拖了后腿，至今没开通微博账号...
> > 至于阿里域账号，更是没有....
> > 一直只能使用github进行......
> > 希望官方可以增加gitee的授权，
> > 或者增加支付宝/淘宝等的授权，
> > qq/微信，自有账号体系等的授权....
> > 哪一天github被ban了，我也有个底.........
> 
> 自建的账户体系已经在做了，后面直接统一用手机号登陆

已经正常了，谢谢
自建账号体系希望能考虑绑定现有的账号，加油
