### ISSUE TITLE
iOS集成图标数量太多的iconfont直接闪退

### ISSUE THREAD

**Issue by SongJasper** [thx/iconfont-plus#1997]
iOS经测试 iconfont数量100以下可以正常使用 超过300加载时会出现以下问题
![image](https://user-images.githubusercontent.com/18087591/121458854-b9ac5880-c9dc-11eb-965b-207b6b251a26.png)

**Comment by yisibl** [comment]
用的什么格式的字体文件？

**Comment by SongJasper** [comment]
下载下来原封不动的加载的    所有的代码都是按照教程来的  少于一百的都正常显示图标了  后来数量多了  就直接加载不了了

**Comment by yisibl** [comment]
请提供项目 id，以及字体文件

**Comment by SongJasper** [comment]
[download(6).zip](https://github.com/thx/iconfont-plus/files/6628140/download.6.zip)


projectid 965988

**Comment by yisibl** [comment]
TTF 字体看起来没有问题，请尝试以下方法：

1. iOS 中换一种方式加载和使用 iconfont（我不是 iOS 开发，请尝试 Google 搜索）
2. 把图标拆分成两个以上的项目，加载多个字体，然后分别用不同的 font-family 试试。

**Comment by SongJasper** [comment]
Apple官方只有一种加载方式 
https://developer.apple.com/documentation/uikit/text_display_and_fonts/adding_a_custom_font_to_your_app

拆分的话 后期维护就麻烦了
