### ISSUE TITLE
【HELP】Unicode和Font class 都有问题，Symbol是正常

### ISSUE THREAD

**Issue by pchmlrs** [thx/iconfont-plus#1999]
机型：HUAWEI TAG-AL00
Android版本: 5.1

以上机型 安装APP中使用“项目预览链接”，Font Class 和Unicode都失效 Symbol正常。

同样的环境，小米 OPPO等都正常
同样的环境，2个月前的demo_index.html都正常。

**Comment by pchmlrs** [comment]
https://at.alicdn.com/t/project/1113967/9f1e38db-5981-4f9f-a902-7e04e1ff2147.html?spm=a313x.7781069.1998910419.35

**Comment by pchmlrs** [comment]
![image](https://user-images.githubusercontent.com/2193389/121987689-807f3a00-cd88-11eb-97d2-45bc73af39c7.png)

**Comment by kasuo1718** [comment]
遇到了同样的问题，请问有方法解决吗？

**Comment by yisibl** [comment]
找到问了，今天发布一个新版本。

**Comment by yisibl** [comment]
已修复，请重新生成试试：![image](https://user-images.githubusercontent.com/2784308/122356914-d1a84d00-cf85-11eb-9f3f-f9df90b6b70b.png)
