### ISSUE TITLE
BUG反馈

### ISSUE THREAD

**Issue by XuanHenLove** [thx/iconfont-plus#20]
1. 修改图标大小后生成的新链接图标大小并没有变化。
2. woff、ttf后缀链接返回404错误。（引用CSS文件报错，直接引入字体文件无报错）

**Comment by purplebamboo** [comment]
亲  麻烦提供更清楚的case。最好截个图。

或者可以私信我，你的用户名  还有项目名。我去看下。

**Comment by XuanHenLove** [comment]
http://works.xuanhen.cc/iconfont/2.html  （404错误）
http://works.xuanhen.cc/iconfont/1.html  （图标不变大）
![qq 20161020170600](https://cloud.githubusercontent.com/assets/22951987/19553626/9105029c-96e7-11e6-8060-892c903cf66e.png)


很抱歉我并不用git来做开发和学习。所以我只能放到我自己的网址上给你展示。略显麻烦。
@purplebamboo

**Comment by purplebamboo** [comment]
感谢反馈，这个问题 待会儿就修复
