### ISSUE TITLE
在vue引入iconfont在安卓下显示方框叉，是新添加图标之后，之前能正确显示[Help]

### ISSUE THREAD

**Issue by kasuo1718** [thx/iconfont-plus#2001]
## 问题描述
在vue引入iconfont在安卓下显示方框叉，是新添加图标之后，之前能正确显示

> `相关截图`

**Comment by yisibl** [comment]
请重新提交一个 bug 类型的 issue（包含新增图标的名称和截图），按要求填写相关信息



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月16日(星期三) 上午8:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [thx/iconfont-plus] 在vue引入iconfont在安卓下显示方框叉，是新添加图标之后，之前能正确显示[Help] (#2001)





 
问题描述
 
相关截图

**Comment by kasuo1718** [comment]
![ba12962bcdeb8a564f3ae8a0cead08d](https://user-images.githubusercontent.com/40145257/122169382-e9ad9d00-ceaf-11eb-808c-a169c1e96191.jpg)

https://at.alicdn.com/t/project/2018829/2b6d2ce1-8469-4135-ab94-3326c8ec0c74.html?spm=a313x.7781069.1998910419.64

没有新增图标，按原来的图标重新下载到本地引入就显示不了；一个月前，新增图标下载到本地还是可以的；

项目中使用的font class形式

系统版本是5.1.1；

**Comment by yisibl** [comment]
请重新生成再试试。

**Comment by yisibl** [comment]
下次提交 bug请用这个地址：https://github.com/thx/iconfont-plus/issues/new?assignees=&labels=&template=bug_report.md
