### ISSUE TITLE
图标库本地下载无法显示一个框中间有一个叉

### ISSUE THREAD

**Issue by kasuo1718** [thx/iconfont-plus#2003]
## 问题描述
图标库本地下载无法显示一个框中间有一个叉
## 截图
![微信图片_20210616140903](https://user-images.githubusercontent.com/40145257/122166649-7ce4d380-ceac-11eb-9cba-83a459a962a5.jpg)；
![image](https://user-images.githubusercontent.com/40145257/122166827-b1588f80-ceac-11eb-8727-52129da27cf3.png)

## 重现步骤
1. 打开：在vue中引入，使用font class
2. 点击：
3. 出现：

## 期望结果
正常显示
## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

https://at.alicdn.com/t/project/2338451/91d5b8c1-c50e-4c80-b673-564f03ef98d1.html?spm=a313x.7781069.1998910419.36

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：安卓5.1

- 浏览器名称及版本：

**Comment by The-zzZ** [comment]
遇到同样问题，求解@yisibl

**Comment by yisibl** [comment]
知道问题的原因了，等我发布新版本解决。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月16日(星期三) 下午4:56
***@***.***&gt;;
抄送:&nbsp;"Percy ***@***.******@***.***&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 图标库本地下载无法显示一个框中间有一个叉 (#2003)





 
***@***.***

**Comment by kasuo1718** [comment]
![1013c85148673e21d40b42517dc92eb](https://user-images.githubusercontent.com/40145257/122347019-2c3cab80-cf7c-11eb-8921-9ee2c85c848c.jpg)

在今天收到发布了新的版本的邮件后，重新下的demo,还是显示不对

**Comment by yisibl** [comment]
iconfont 后台需要发布新版本，稍等。

**Comment by yisibl** [comment]
请重新生成再试试。

**Comment by kasuo1718** [comment]
已经正常显示。谢谢 @yisibl
