### ISSUE TITLE
[FR] 期望能支持绑定第三方账号，如微信或微博，或邮箱。

### ISSUE THREAD

**Issue by johonz** [thx/iconfont-plus#2006]
## 需求背景
由于github间歇性的无法访问或访问异常，导致以github授权登录的方式的话，无法正常登录iconfont。

**Comment by yisibl** [comment]
我们正在开发

**Comment by yisibl** [comment]
手机注册登录功能已经上线，[点击查看](https://mp.weixin.qq.com/s?__biz=Mzg5OTUzNjQ0Mg==&mid=2247483866&idx=1&sn=e6d02ca84cba8157c8f90d072db66bbf&chksm=c050828ff7270b99b00d784681a47fb4d1063a9139732075dc84d8da4ad77d446df386384acc&token=1155149842&lang=zh_CN#rd)

相关 issue：#1718
