### ISSUE TITLE
图标修改报！Error

### ISSUE THREAD

**Issue by An575** [thx/iconfont-plus#2014]
## 问题描述
添加到项目的图标修改保存时提示!ERROR
## 截图

![未命名](https://user-images.githubusercontent.com/14040658/123031385-cedea980-d416-11eb-8e7e-afc074984077.PNG)

**Comment by Leega0** [comment]
一样，突然不能保存了

**Comment by loveempathy** [comment]
一样，所有的都不能编辑保存了

**Comment by Reeyc** [comment]
一样

**Comment by geekFeier** [comment]
一样

**Comment by geekFeier** [comment]
一样

**Comment by Leega0** [comment]
小号三联？[![RnJDUI.png](https://z3.ax1x.com/2021/06/23/RnJDUI.png)](https://imgtu.com/i/RnJDUI)

**Comment by yisibl** [comment]
请重新试试

**Comment by An575** [comment]
已OK

**Comment by yisibl** [comment]
![image](https://user-images.githubusercontent.com/2784308/123048807-63560580-d431-11eb-9db1-c27fad97338b.png)

**Comment by loveempathy** [comment]
> 小号三联？[![RnJDUI.png](https://camo.githubusercontent.com/37c9e1159bea844c2e197628ff254a8330a8fdc1d4e02428fb0509c828aeeaab/68747470733a2f2f7a332e617831782e636f6d2f323032312f30362f32332f526e4a4455492e706e67)](https://imgtu.com/i/RnJDUI)

这都让你发现了？
