### ISSUE TITLE
上传图标部分图标名称前面会有系统自己生成的字母a-

### ISSUE THREAD

**Issue by fengchuanBIG** [thx/iconfont-plus#2022]
系统是Mac 谷歌浏览器   之前的项目重新上传图标，图标本身的名字没有变，但是上传icon font  会自动在前面加入没有的a-导致现在系统部分图标完全失效，  没有使用icon font前缀；请紧急回复一下，影响很多系统的使用，大家共用的一个图标库

**Comment by fengchuanBIG** [comment]
找到问题了，系统自动把我图标里面的、号  前置变成了a-    请紧急修复该bug

**Comment by fengchuanBIG** [comment]
一个人慢慢把作者顶出来，  系统现在图标不显示了囧

**Comment by fengchuanBIG** [comment]
作者作者快出现作者作者快现身吧   大佬大佬在不在呀在不在

**Comment by fengchuanBIG** [comment]
大佬  快出一套明确的命名规范吧，或者你们提前将某些字符 限定上传  留给你们自己内部升级的时候使用，不要在使用过程中，突然改了， 我们玩不起呀  大佬

**Comment by yisibl** [comment]
CSS Class 以数字开头是不合法的，浏览器无法识别，所以现在 Class 命名必须符合 CSS 规范。
注意：**我们当前的语法规则是 CSS 语法规则的子集**，具体规则如下：

- 必须是字母、连字符、下划线开头，且后面只能是数字、连字符、下划线，- 后面第一个字符不能是数字。
- 虽然浏览器支持 Unicode 字符（如 emoji）作为 Class 名称，但当前实现不支持，这会增加复杂度，
- 并且不支持两个连字符开头，例如：--foo，旧的浏览器支持度不好。
- 合法的 class 名称：f2_-2，Foo-12a，-_foo，-foo，__foo，_2foo
- 不合法的 class 名称：2foo，23，--foo

上传图标后，不合法的 class 会自动添加前缀 `a-`，下个版本考虑在上传的时候处理不合法的文件名（class 名称）

CSS Spec: http://www.w3.org/TR/CSS21/grammar.html#scanner

**Comment by fengchuanBIG** [comment]
最终还是全部手动修改了，  哎  大佬 快快修复吧

**Comment by yisibl** [comment]
如果 Class 不符合 CSS 规范，必须手动修改为上述规则。
