### ISSUE TITLE
点“下载至本地”没反应

### ISSUE THREAD

**Issue by willwellweb** [thx/iconfont-plus#2023]
## 问题描述
进入项目，点“下载至本地”没反应
## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
请提供具体信息
