### ISSUE TITLE
上传图标的时候一直在显示加载中，任何点击都不生效

### ISSUE THREAD

**Issue by PARISHAPPYTIME** [thx/iconfont-plus#2024]
![image](https://user-images.githubusercontent.com/40844077/124552523-41637680-de66-11eb-9918-38005e03ca46.png)

**Comment by PARISHAPPYTIME** [comment]
![image](https://user-images.githubusercontent.com/40844077/124552571-53ddb000-de66-11eb-9cee-33677a4c5d8c.png)

**Comment by MissQ** [comment]
我也遇到这个问题  怎么解决的

**Comment by yisibl** [comment]
请按照 issue 模板提交问题，没有原始 svg 文件无法排查。
