### ISSUE TITLE
批量删除的时候！怎么直接整个项目都没有了啊！！！！急死人了~！！！里面一堆的东西~！！老板都要干掉我了

### ISSUE THREAD

**Issue by vivi0201** [thx/iconfont-plus#203]
批量删除的时候！怎么直接整个项目都没有了啊！！！！急死人了~！！！里面一堆的东西~！！老板都要干掉我了

**Comment by purplebamboo** [comment]
亲  项目名称给我下？

**Comment by purplebamboo** [comment]
批量删除不可能删除项目的呀，你是不是点错了。

**Comment by vivi0201** [comment]
应该是误操作了~~项目名称应该是 en+pc端图标~~麻烦帮忙查找一下

**Comment by purplebamboo** [comment]
很抱歉，亲。项目删除了就是没有了。

＝ ＝ 找不回来的。

**Comment by purplebamboo** [comment]
我已经查不到了。

**Comment by vivi0201** [comment]
怎么插入图片呀？我先是在批量操作里面批量选择图标后 然后先的更多选择删除项目 就整个消失了 ~~才惊发现 可能是删除错了~~

**Comment by vivi0201** [comment]
你们那里没有缓存么~~
![image](https://cloud.githubusercontent.com/assets/23694128/20553596/b9ca6cc6-b190-11e6-9bc3-975fdaa03895.png)

**Comment by purplebamboo** [comment]
把图片拖到你的评论框就行。

亲，删除项目有二次确认的。。＝＝。囧 这个真的找不回来了额。

**Comment by vivi0201** [comment]
好吧~~这真是一个悲伤的故事~~

**Comment by purplebamboo** [comment]
爱莫能助。。。

一脸无奈.jpg

**Comment by vivi0201** [comment]
谢谢~~~
