### ISSUE TITLE
【项目设置勾选了彩色图标 后预览显示Unicode&Font class字体空白】下载之后的字体也为空白

### ISSUE THREAD

**Issue by dingfeipeng** [thx/iconfont-plus#2032]
## 问题描述
【项目设置勾选了彩色图标 后预览显示Unicode&Font class字体空白】下载之后的字体也为空白
## 重现步骤
1. 新建项目：选择彩色模式
2. 点击：生成代码
3. 出现：下载或预览

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

http://qw82nzx8n.hn-bkt.clouddn.com/33770E4B-FB0D-4049-A32F-E9BC80A82C66.png

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：MACOS 10.15.7 (19H114)

- 浏览器名称及版本：Google Chrome 
版本 91.0.4472.114（正式版本） (x86_64)

**Comment by wapznw** [comment]
同样的问题，用Safari可以显示

**Comment by dingfeipeng** [comment]
明明前一天还是好的

**Comment by yisibl** [comment]
可以复现，我看一下

**Comment by yisibl** [comment]
已修复

**Comment by DEC-QI** [comment]
我也遇到了相同的问题,怎么解决

**Comment by DEC-QI** [comment]
> 已修复



> 已修复

我今天也遇到了和@dingfeipeng 一摸一样的问题 ,下载下来后一些彩色图标是空白,一些可以正常显示.但是昨天又都是可以正常显示的
