### ISSUE TITLE
我的项目打开一直loading

### ISSUE THREAD

**Issue by dpfl2015** [thx/iconfont-plus#2034]
## 问题描述

我的项目打不开，一直loading状态

## 重现步骤
1. 打开：我的项目
2. 点击：一直loading状态
3. 出现：```
Uncaught TypeError: Cannot read property 'id' of undefined
    at e._render (myprojects.js:1)
    at myprojects.js:1
    at r.<anonymous> (index.js:1)
    at k (magix.js:1)
    at Ht.Nt.b (magix.js:1)
    at r (jquery-1.12.1.js:1)
    at Object.complete (service.js:1)
    at i (jquery-1.12.1.js:1)
    at Object.fireWith (jquery-1.12.1.js:1)
    at s (jquery-1.12.1.js:1)

```
## 期望结果
正常看到我的项目



## 账号
账号是2015年账号

**Comment by mklfeng** [comment]
同出现此问题

**Comment by cbxcbx** [comment]
> ## 问题描述
> 我的项目打不开，一直loading状态
> 
> ## 截图
> ## 重现步骤
> 1. 打开：我的项目
> 2. 点击：一直loading状态
> 3. 出现：```
>    Uncaught TypeError: Cannot read property 'id' of undefined
>    at e._render (myprojects.js:1)
>    at myprojects.js:1
>    at r. (index.js:1)
>    at k (magix.js:1)
>    at Ht.Nt.b (magix.js:1)
>    at r (jquery-1.12.1.js:1)
>    at Object.complete (service.js:1)
>    at i (jquery-1.12.1.js:1)
>    at Object.fireWith (jquery-1.12.1.js:1)
>    at s (jquery-1.12.1.js:1)
> 
> ```
> ## 期望结果
> 正常看到我的项目
> 
> 
> 
> ## 账号
> 账号是2015年账号
> ```

可能是没有项目，需要别人添加你到项目后，才会显示
