### ISSUE TITLE
微博账号注销，账号管理着很多个项目，可以帮转移项目的管理权吗？[Help][Help][Help]

### ISSUE THREAD

**Issue by sunmengjing** [thx/iconfont-plus#2037]
## 问题描述
微博账号是管理员权限，找不回来了， 可以帮转移项目的管理权吗？ 原来的账号是微博账号 ： 445843780@qq.com  
新账号是 github账号 ：445843780@qq.com    拜托了，有点急~~~

**Comment by yisibl** [comment]
请提供原有账号昵称和需要转移账号的昵称，以及项目的 ID

**Comment by sunmengjing** [comment]
感谢！！！🙏🙏🙏🙏
原账号账号昵称：甘蔗不太甜
新账号昵称：孙梦晶（Github账号：sunmengjing）
迁移项目名称是zhixinApp和编辑器这两个，ID不知道在哪里找







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月22日(星期四) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 微博账号注销，账号管理着很多个项目，可以帮转移项目的管理权吗？[Help][Help][Help] (#2037)





 
请提供原有账号昵称和需要转移账号的昵称，以及项目的 ID

**Comment by cxjanker** [comment]
附议，原帐号“陈老师不着调”，新帐号“盖世英雄utd”

**Comment by yisibl** [comment]
请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)
