### ISSUE TITLE
我也是醉了，新版问题太多了。

### ISSUE THREAD

**Issue by ssohj** [thx/iconfont-plus#204]
新版问题太多太多了，新版上线后我老登录不了，现在好不容易登陆上了，下载就开始报错了。说什么乱七八糟的。

![image](https://cloud.githubusercontent.com/assets/23695280/20554507/60e2f900-b197-11e6-9829-a0d7f23c2c29.png)

我服了，不仅仅我电脑上有问题，多好人电脑上都有问题。强烈要求换回来。

**Comment by purplebamboo** [comment]
亲  这里面已经有了提示哦 

你里面的xiugai这个图标  有问题。unicode是  1是非法的。你把这个删除就行了。

就算用旧版也是有问题的哦。

**Comment by NE-SmallTown** [comment]
@ssohj 提建议没问题，发牢骚不要上github。另外，导航里面有“返回旧版”四个大字

**Comment by purplebamboo** [comment]
@NE-SmallTown   感谢理解。
新版刚起步，肯定有不少问题，我们会慢慢优化的。

**Comment by goblin123dan** [comment]
新版也有新版的好处 不习惯可以切换回旧版 
iconfont一路走到现在太不容易 只有几个人 还是工作之外的时间
反正个人用着挺好 有一些小问题 但不影响使用
感谢你们的默默付出
