### ISSUE TITLE
SVG上传不上去  我以为我的SVG有问题  然后我试了从上面下载其他的SVG试下一下也传不上去

### ISSUE THREAD

**Issue by MissQ** [thx/iconfont-plus#2041]
![image](https://user-images.githubusercontent.com/10217039/126862189-ce775799-3764-4777-a76f-2eee941ac323.png)
打开控制台都在报错  
急需求解决哈

**Comment by yisibl** [comment]
请按照 issue 模板提交问题，没有原始 svg 文件无法排查。

**Comment by MissQ** [comment]
好的
