### ISSUE TITLE
关于作品版权

### ISSUE THREAD

**Issue by jdh8088** [thx/iconfont-plus#2042]
## 作品：常用_icon002 侵权  小假哥_常用_icon044
     作品：娱乐_icon001 侵权 小假哥_娱乐_icon053 
     作品：缺省页_插画001 侵权 小假哥_缺省页_插画007

##不知道能不能解决这个问题先谢谢了，可以的话希望平台出一个侵权投诉功能~

**Comment by yisibl** [comment]
感谢反馈，投诉功能后面会做，排期中。

**Comment by yisibl** [comment]
经过仔细核查，该用户在图标库上存在明显模仿痕迹，插画库 SVG 的代码是完全一样的。

蓝色为「懒懒&瘦瘦」用户的图标：
![image](https://user-images.githubusercontent.com/2784308/126968992-be51ae3d-ca16-4c72-8068-c6daf7b3ccf3.png)

我们会尽快下架该用户相关的图标库和插画库，感谢反馈。

**Comment by chen-xq405** [comment]
**发现用户 ”Nancy_ZZ“ 作品中有一套插画作品为盗发 用户“chenxq”作品 希望平台协助警告并删除侵权作品！**

**用户 ”Nancy_ZZ“ 作品中的“空白页”侵权  用户“chenxq”作品中的”蓝色系列“矢量插画库**


##不知道能不能解决这个问题先谢谢了，可以的话希望平台出一个侵权投诉功能~
