### ISSUE TITLE
作者侵权直接上传我图标怎样联系对方删除该作品

### ISSUE THREAD

**Issue by jdh8088** [thx/iconfont-plus#2044]
## 截图

![image](https://user-images.githubusercontent.com/68884174/126942896-cd16d528-e2fb-40a8-b92b-30b868cc245b.png)
![image](https://user-images.githubusercontent.com/68884174/126942938-2ef84493-a50e-43a7-a4ba-95e9b139940e.png)

## 相关信息（重要）
- 发生问题的 URL：001-https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.dc64b3430&cid=33701
- 002-https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.dc64b3430&cid=33700
- 003-https://www.iconfont.cn/illustrations/detail?spm=a313x.7781069.1998910419.dc64b3430&cid=33698
- iconfont 的用户昵称：侵权用户：懒惰&瘦瘦
- iconfont 项目 ID：https://www.iconfont.cn/user/detail?spm=a313x.7781069.1998910419.d9bd4f23f&uid=5620213

**Comment by yisibl** [comment]
我看一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月26日(周一) 下午2:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [thx/iconfont-plus] 作者侵权直接上传我图标怎样联系对方删除该作品 (#2044)




 
作者侵权直接上传我图标怎样联系对方删除该作品
 
截图
 

 
 
期望结果 ：及时通知对方删除作品或者平台下架该侵权作品
 
相关信息（重要）
  
发生问题的 URL：001-https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.dc64b3430&amp;cid=33701 

002-https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.dc64b3430&amp;cid=33700 

003-https://www.iconfont.cn/illustrations/detail?spm=a313x.7781069.1998910419.dc64b3430&amp;cid=33698 

iconfont 的用户昵称：侵权用户：懒惰&amp;瘦瘦 

iconfont 项目 ID：https://www.iconfont.cn/user/detail?spm=a313x.7781069.1998910419.d9bd4f23f&amp;uid=5620213

**Comment by yisibl** [comment]
请提供版权相关证明和你的 iconfont 昵称。

**Comment by yisibl** [comment]
请勿重复提交问题，相关处理结果在：https://github.com/thx/iconfont-plus/issues/2044

后续涉及版权问题，请提供类似的截图证明。
