### ISSUE TITLE
上传图标的时候一直在显示加载中

### ISSUE THREAD

**Issue by MissQ** [thx/iconfont-plus#2049]
SVG上传不上去 我以为我的SVG有问题 然后我试了从上面下载其他的SVG试下一下也传不上去
## 描述
VM2572:1 Uncaught SyntaxError: Unexpected token  in JSON at position 2023
    at JSON.parse (<anonymous>)
    at e.ctor (index.js:1)
    at new e (magix.js:1)
    at magix.js:1
    at H.i.callback (sea.js:1)
    at H.a.seajs.H.onload (sea.js:1)
    at H.a.seajs.H.load (sea.js:1)
    at Function.a.seajs.H.use (sea.js:1)
    at sea.js:1
    at Function.a.seajs.H.preload (sea.js:1)
## 截图
![image](https://user-images.githubusercontent.com/10217039/127725469-194f139f-467f-42b3-a76c-03e222c31f93.png)

## 重现步骤
1. 打开：打开上传图标至项目
2. 点击：点击上传图标 选择SVG文件
3. 出现：然后一直处于上传中并没有效果  打开控制台 查看console 发现JSON解析错误 查看NetWork没有发起请求

## 期望结果
希望尽快解决 
## 相关信息（重要）
- 发生问题的 URL：https://www.iconfont.cn/icons/upload?spm=a313x.7781069.1998910419.d7543c323&projectId=2675193
- iconfont 的用户昵称：任务系统
- iconfont 项目 ID：290024850264-2675193

2675193
## 相关文件（重要）

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="36.828" height="37.657" viewBox="0 0 36.828 37.657">
  <defs>
    <style>
      .cls-1 {
        fill: #6e6e6e;
        opacity: 0;
      }

      .cls-2 {
        fill: none;
        stroke: #262626;
        stroke-linecap: round;
        stroke-width: 4px;
      }
    </style>
  </defs>
  <g id="组件_4_42" data-name="组件 4 – 42" transform="translate(0.828 0.828)">
    <rect id="矩形_3" data-name="矩形 3" class="cls-1" width="36" height="36"/>
    <g id="组_2" data-name="组 2" transform="translate(-36.5 -114.5)">
      <line id="直线_3" data-name="直线 3" class="cls-2" x1="16" y2="16" transform="translate(38.5 116.5)"/>
      <line id="直线_4" data-name="直线 4" class="cls-2" x1="16" y1="16" transform="translate(38.5 132.5)"/>
    </g>
  </g>
</svg>

<svg id="组件_3_3" data-name="组件 3 – 3" xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 96 96">
  <defs>
    <style>
      .cls-1 {
        fill: #69c747;
      }

      .cls-2 {
        fill: #fff;
      }
    </style>
  </defs>
  <circle id="椭圆_3" data-name="椭圆 3" class="cls-1" cx="48" cy="48" r="48"/>
  <path id="路径_1" data-name="路径 1" class="cls-2" d="M37.832,108.686a17.429,17.429,0,0,1,1.911.119c-1.712-7.972-10.232-13.893-19.96-13.893C8.908,94.912,0,102.321,0,111.735c0,5.432,2.962,9.893,7.916,13.358l-1.977,5.949,6.917-3.465a34.077,34.077,0,0,0,6.927.989c.622,0,1.237-.028,1.844-.073a14.829,14.829,0,0,1-.611-4.15C21.019,115.7,28.438,108.686,37.832,108.686ZM27.2,103.324a2.471,2.471,0,1,1,0,4.943,2.513,2.513,0,1,1,0-4.943Zm-13.844,4.943c-1.485,0-2.98-.992-2.98-2.473s1.5-2.47,2.98-2.47a2.471,2.471,0,0,1,0,4.943Zm42.537,15.838c0-7.909-7.916-14.354-16.806-14.354-9.414,0-16.823,6.449-16.823,14.354,0,7.93,7.413,14.354,16.823,14.354a24.809,24.809,0,0,0,5.935-.989l5.425,2.976L48.958,135.5C52.93,132.517,55.892,128.566,55.892,124.105Zm-22.262-2.477a1.977,1.977,0,1,1,0-3.954,2.028,2.028,0,1,1,0,3.954Zm10.881,0a1.977,1.977,0,0,1,0-3.954,2.028,2.028,0,1,1,0,3.954Z" transform="translate(20 -69.912)"/>
</svg>
```

## 平台/浏览器版本（重要）
- 浏览器名称及版本：
   例如 Google Chrome 90.0.4430.85

**Comment by yisibl** [comment]
目前SVG只支持path 其他元素必须转换为path



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年7月31日(周六) 上午10:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [thx/iconfont-plus] 上传图标的时候一直在显示加载中 (#2049)




 
SVG上传不上去 我以为我的SVG有问题 然后我试了从上面下载其他的SVG试下一下也传不上去
 
描述
 
VM2572:1 Uncaught SyntaxError: Unexpected token   in JSON at position 2023
 at JSON.parse ()
 at e.ctor (index.js:1)
 at new e (magix.js:1)
 at magix.js:1
 at H.i.callback (sea.js:1)
 at H.a.seajs.H.onload (sea.js:1)
 at H.a.seajs.H.load (sea.js:1)
 at Function.a.seajs.H.use (sea.js:1)
 at sea.js:1
 at Function.a.seajs.H.preload (sea.js:1)
 
截图
 

 
重现步骤
  
打开：打开上传图标至项目 

点击：点击上传图标 选择SVG文件 

出现：然后一直处于上传中并没有效果  打开控制台 查看console 发现JSON解析错误 查看NetWork没有发起请求 
 
期望结果
 
希望尽快解决
 
相关信息（重要）
  
发生问题的 URL：https://www.iconfont.cn/icons/upload?spm=a313x.7781069.1998910419.d7543c323&amp;projectId=2675193 

iconfont 的用户昵称：任务系统 

iconfont 项目 ID：290024850264-2675193 
 
2675193
 
相关文件（重要）
 <svg xmlns="http://www.w3.org/2000/svg" width="36.828" height="37.657" viewBox="0 0 36.828 37.657"&gt;   <defs&gt;     <style&gt;       .cls-1 {         fill: #6e6e6e;         opacity: 0;       }        .cls-2 {         fill: none;         stroke: #262626;         stroke-linecap: round;         stroke-width: 4px;       }     </style&gt;   </defs&gt;   <g id="组件_4_42" data-name="组件 4 – 42" transform="translate(0.828 0.828)"&gt;     <rect id="矩形_3" data-name="矩形 3" class="cls-1" width="36" height="36"/&gt;     <g id="组_2" data-name="组 2" transform="translate(-36.5 -114.5)"&gt;       <line id="直线_3" data-name="直线 3" class="cls-2" x1="16" y2="16" transform="translate(38.5 116.5)"/&gt;       <line id="直线_4" data-name="直线 4" class="cls-2" x1="16" y1="16" transform="translate(38.5 132.5)"/&gt;     </g&gt;   </g&gt; </svg&gt; <svg id="组件_3_3" data-name="组件 3 – 3" xmlns="http://www.w3.org/2000/svg" width="96" height="96" viewBox="0 0 96 96"&gt;   <defs&gt;     <style&gt;       .cls-1 {         fill: #69c747;       }        .cls-2 {         fill: #fff;       }     </style&gt;   </defs&gt;   <circle id="椭圆_3" data-name="椭圆 3" class="cls-1" cx="48" cy="48" r="48"/&gt;   <path id="路径_1" data-name="路径 1" class="cls-2" d="M37.832,108.686a17.429,17.429,0,0,1,1.911.119c-1.712-7.972-10.232-13.893-19.96-13.893C8.908,94.912,0,102.321,0,111.735c0,5.432,2.962,9.893,7.916,13.358l-1.977,5.949,6.917-3.465a34.077,34.077,0,0,0,6.927.989c.622,0,1.237-.028,1.844-.073a14.829,14.829,0,0,1-.611-4.15C21.019,115.7,28.438,108.686,37.832,108.686ZM27.2,103.324a2.471,2.471,0,1,1,0,4.943,2.513,2.513,0,1,1,0-4.943Zm-13.844,4.943c-1.485,0-2.98-.992-2.98-2.473s1.5-2.47,2.98-2.47a2.471,2.471,0,0,1,0,4.943Zm42.537,15.838c0-7.909-7.916-14.354-16.806-14.354-9.414,0-16.823,6.449-16.823,14.354,0,7.93,7.413,14.354,16.823,14.354a24.809,24.809,0,0,0,5.935-.989l5.425,2.976L48.958,135.5C52.93,132.517,55.892,128.566,55.892,124.105Zm-22.262-2.477a1.977,1.977,0,1,1,0-3.954,2.028,2.028,0,1,1,0,3.954Zm10.881,0a1.977,1.977,0,0,1,0-3.954,2.028,2.028,0,1,1,0,3.954Z" transform="translate(20 -69.912)"/&gt; </svg&gt;
 
平台/浏览器版本（重要）
  
浏览器名称及版本：
 例如 Google Chrome 90.0.4430.85

**Comment by MissQ** [comment]
貌似在苹果电脑上 谷歌可以上传上去
