### ISSUE TITLE
[FR]项目中图标名称的修改（上传时候的文件名称）

### ISSUE THREAD

**Issue by MrGary666** [thx/iconfont-plus#2054]
## 需求背景
当我把平时收集和制作的svg图标统一上传至项目后，这时发现了图标文件名称不够统一，但是不想在线下一个个修改好后再次上传；所以有了此项需求建议
## 解决方案
进入项目后，点击图标的编辑按钮，进入编辑页面 可以编辑图标文件名称即可，
## 相关截图
![截图](https://user-images.githubusercontent.com/14814856/128449414-c6fc89bc-ab55-4ea6-a7fb-edd5feeee5fc.png)

**Comment by yisibl** [comment]
感谢建议，但目前这个功能优先级不高，暂时可以在我上传的 icon 中修改名称，后续可考虑该功能。

**Comment by guoyunhe** [comment]
这个功能真的是我现在用 iconfont.cn 最大的痛点，太反人类了。这个应该很容易改的吧，就加一个输入框而已。

**Comment by GarethHub** [comment]
臣复议。我认为的图标意义，经常和原名称不一致，希望有个方便的修改图标名称途径。

**Comment by WchenE** [comment]
臣复议

**Comment by guoyunhe** [comment]
最近要给一个一百多图标的项目做命名规范化，一个个下载上传工作量巨大，跪求开发者考虑支持一下！

**Comment by MIZIZHU** [comment]
非常需要这个功能，现在一个项目中的图标体量大了，名称的规范就非常重要！现在貌似就只能在自己上传图标的列表中去修改，不能在项目中修改

**Comment by yisibl** [comment]
感谢反馈，项目中图标修改名称功能已经上线。

![image](https://github.com/thx/iconfont-plus/assets/2784308/ddde4924-378e-4882-88e8-1f8771459564)
