### ISSUE TITLE
[Help]上传的svg图标，svg viewBox属性值会被修改为0 0 1024 1024，有没有办法避免这个属性值的修改？

### ISSUE THREAD

**Issue by yangmiao7** [thx/iconfont-plus#2056]
## 问题描述
RT
## 相关截图
![image](https://user-images.githubusercontent.com/20420986/128846908-8ae5f9ec-8063-482a-9f89-e7cb39193565.png)

**Comment by yisibl** [comment]
iconfont 会把 svg 生成字体，而字体中需要使用同一的 viewBox。如果你需要下载原始的 SVG 请重新提一个 PR 的 issue。
