### ISSUE TITLE
无法更新icon代码

### ISSUE THREAD

**Issue by zrl829** [thx/iconfont-plus#206]
```javascript
Command failed: /bin/sh -c ttfautohint --latin-fallback --hinting-limit=200 --hinting-range-max=50  --symbol '/home/admin/icon-font/tmp/font_vq5hq0lzdbyv6lxr/origin.ttf' '/home/admin/icon-font/tmp/font_vq5hq0lzdbyv6lxr/iconfont.ttf'
```

更新icon的时候，页面提示如上

**Comment by purplebamboo** [comment]
亲  把项目id给我下哈

或者直接当前项目上面的  url地址，我帮你排查下。

**Comment by zrl829** [comment]
现在更新字体，提示『字体生成出错啦，这通常是项目里某个图标有问题（unicode非法等），删除掉就可以啦』

projectId：149542

**Comment by purplebamboo** [comment]
亲  你好，其实用二分法  很容易可以查找出来的。   我们其实有时也不知道到底哪个图标出问题了。

因为我们也是依赖的第三方的库来处理字体的。排查发现 项目里有个叫empty的图标。这个图标在用ttfautohint去优化时，会有问题。（具体问题我们其实也不是特别明白）。


排查办法，你可以看下我在你个人项目下建立的若干项目哈。

就是一半一半的排除，将有问题的项目里的一半图标加入到一个新项目生成字体看有没有问题。

这样一层层往下找，很容易找出来的。





目前针对这些有问题的图标，我们还没啥特别好的办法，准备后期会出一个举报机制，让用户来对每个图标打标啥的。

**Comment by zrl829** [comment]
![image](https://cloud.githubusercontent.com/assets/5548420/20710532/e060a38e-b675-11e6-95b4-6bbcf80a64dd.png)
突然看到我的项目里多了这么多文件夹，吓了一跳，然后反应过来应该是你帮我弄的，感觉略萌，哈哈！

真心感谢你抽空帮我的图标库找出问题图标，用二分法的确是有效的办法，感谢😀 ！
