### ISSUE TITLE
图标上传后变形，图案丢失

### ISSUE THREAD

**Issue by VvTianTian** [thx/iconfont-plus#2060]
没有未闭合的线，图案也不算复杂

![image](https://user-images.githubusercontent.com/8371797/128992749-f152f694-6b94-4945-9d4d-0b8817d769b5.png)
![image](https://user-images.githubusercontent.com/8371797/128992827-3b4c1c0a-7b2b-4a40-8118-8dcf526c5722.png)
![image](https://user-images.githubusercontent.com/8371797/128992883-623f0786-be4c-49e5-a8b8-6c0dde4e6e4f.png)

**Comment by VvTianTian** [comment]
<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
<g clip-path="url(#clip0)">
<path d="M1036 -1325H-404V1075H1036V-1325Z" fill="white"/>
<path fill-rule="evenodd" clip-rule="evenodd" d="M12 4C9.87827 4 7.84344 4.84285 6.34315 6.34315C4.84285 7.84344 4 9.87827 4 12C4 13.0506 4.20693 14.0909 4.60896 15.0615C4.82249 15.577 5.08884 16.0675 5.40296 16.5254C7.45293 15.5202 9.70987 14.9966 12.0008 15C14.3657 15.0001 16.6052 15.548 18.5971 16.5252C18.9112 16.0674 19.1775 15.5769 19.391 15.0615C19.7931 14.0909 20 13.0506 20 12C20 9.87827 19.1571 7.84344 17.6569 6.34315C16.1566 4.84285 14.1217 4 12 4ZM19.6651 18.4223C20.3176 17.6436 20.8487 16.7686 21.2388 15.8268C21.7413 14.6136 22 13.3132 22 12C22 9.34784 20.9464 6.8043 19.0711 4.92893C17.1957 3.05357 14.6522 2 12 2C9.34784 2 6.8043 3.05357 4.92893 4.92893C3.05357 6.8043 2 9.34784 2 12C2 13.3132 2.25866 14.6136 2.7612 15.8268C3.1513 16.7686 3.68242 17.6436 4.33489 18.4223C4.34962 18.4411 4.36493 18.4592 4.38079 18.4767C4.55514 18.6818 4.73798 18.8801 4.92893 19.0711C5.85752 19.9997 6.95991 20.7362 8.17317 21.2388C9.38642 21.7413 10.6868 22 12 22C13.3132 22 14.6136 21.7413 15.8268 21.2388C17.0401 20.7362 18.1425 19.9997 19.0711 19.0711C19.262 18.8801 19.4449 18.6818 19.6192 18.4767C19.6351 18.4592 19.6504 18.4411 19.6651 18.4223ZM17.1985 18.0808C15.6072 17.3855 13.8496 17 12 17H11.9985C10.2054 16.9973 8.43631 17.3673 6.80181 18.081C7.43981 18.6264 8.16069 19.0688 8.93853 19.391C9.90914 19.7931 10.9494 20 12 20C13.0506 20 14.0909 19.7931 15.0615 19.391C15.8394 19.0688 16.5604 18.6263 17.1985 18.0808ZM12 8C11.4696 8 10.9609 8.21071 10.5858 8.58579C10.2107 8.96086 10 9.46957 10 10C10 10.5304 10.2107 11.0391 10.5858 11.4142C10.9609 11.7893 11.4696 12 12 12C12.5304 12 13.0391 11.7893 13.4142 11.4142C13.7893 11.0391 14 10.5304 14 10C14 9.46957 13.7893 8.96086 13.4142 8.58579C13.0391 8.21071 12.5304 8 12 8ZM9.17157 7.17157C9.92172 6.42143 10.9391 6 12 6C13.0609 6 14.0783 6.42143 14.8284 7.17157C15.5786 7.92172 16 8.93913 16 10C16 11.0609 15.5786 12.0783 14.8284 12.8284C14.0783 13.5786 13.0609 14 12 14C10.9391 14 9.92172 13.5786 9.17157 12.8284C8.42143 12.0783 8 11.0609 8 10C8 8.93913 8.42143 7.92172 9.17157 7.17157Z" fill="#262626"/>
</g>
<defs>
<clipPath id="clip0">
<rect width="24" height="24" fill="white"/>
</clipPath>
</defs>
</svg>

**Comment by VvTianTian** [comment]
> 请提供SVG文件
> […](#)
> ---原始邮件--- 发件人: "Surain ***@***.***&gt; 发送时间: 2021年8月11日(周三) 下午4:04 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [thx/iconfont-plus] 图标上传后变形，图案丢失 (#2060) 没有未闭合的线，图案也不算复杂 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

感谢

链接: https://pan.baidu.com/s/1w5jZtIytFNmNGGYEkaqA7g 提取码: t22t

**Comment by yisibl** [comment]
直接把 svg 打包为 zip，上传到这里。

**Comment by VvTianTian** [comment]
> 直接把 svg 打包为 zip，上传到这里。

[user-circle.svg.zip](https://github.com/thx/iconfont-plus/files/6981519/user-circle.svg.zip)

**Comment by VvTianTian** [comment]
> 直接把 svg 打包为 zip，上传到这里。

[user-circle.zip](https://github.com/thx/iconfont-plus/files/6981527/user-circle.zip)

**Comment by yisibl** [comment]
填充模式不对，请参考这个文章修改：https://zhuanlan.zhihu.com/p/137298478

**Comment by yisibl** [comment]
然后图标尺寸不要太小了，这会影响转换为字体后的精度，请保持图标在 500*500px 以上。

**Comment by VvTianTian** [comment]
感谢！
