### ISSUE TITLE
上传宽小于高的icon，会自动转成正方形，而上传宽大于高的，则不会，前者能否修复

### ISSUE THREAD

**Issue by mansonhong86** [thx/iconfont-plus#2068]
上传宽小于高的icon，会自动转成正方形，而上传宽大于高的，则不会，前者能否修复，不要让它自动转成正方形

**Comment by yisibl** [comment]
iconfont icon 转为字体的时候，宽度单位(em box) 始终设置为 1024，这是字体的特性决定的，目前无法调整。
