### ISSUE TITLE
图标库项目管理

### ISSUE THREAD

**Issue by wxungang** [thx/iconfont-plus#207]
![image](https://cloud.githubusercontent.com/assets/9672404/20588925/dbe831c6-b253-11e6-8d07-363b2c0cd68a.png)
1、目前关于 项目的一些描述不够友好。
2、希望新增一个markdown文档区域。

**Comment by wxungang** [comment]
类似于github上可以添加一个readme.md文件。

**Comment by purplebamboo** [comment]
额。。这个有点重。 ＝ ＝ 项目描述需要这么多吗？

**Comment by wxungang** [comment]
那你这描述也太不友好了。至少增加让显示全吧

**Comment by purplebamboo** [comment]
明白，这个的确可以考虑下。我们内部考虑下。

如果有相关好的建议，也可以提出来哈。

在这个issue统一讨论吧，接下来我们要整体做个日常优化下。

https://github.com/thx/iconfont-plus/issues/139
