### ISSUE TITLE
[Help]微博注销了，请求帮转移项目

### ISSUE THREAD

**Issue by also1024** [thx/iconfont-plus#2079]
第三方登录原始微博注销，请求将老账户的所有项目转移到新的账户下。
原始账号名称：全栈Dev
新账号名称：TUXP

谢谢

**Comment by cxjanker** [comment]
附议，原帐号“陈老师不着调”，新帐号“盖世英雄utd”

**Comment by also1024** [comment]
@yisibl

**Comment by yisibl** [comment]
大家好，加一下答疑群吧：
![image](https://user-images.githubusercontent.com/2784308/133039535-fc370bf6-7e08-41c3-9215-546cc7d80464.png)
