### ISSUE TITLE
希望【我的图标】增加图标全选、点选批处理功能。

### ISSUE THREAD

**Issue by DX-WEB** [thx/iconfont-plus#208]
现在【我的图标】中不能多选、全选多个图标执行删除、添加至项目操作，希望【我的图标】可以添加多选、全选图标执行删除、添加值项目操作，谢谢。

**Comment by Muqing1221** [comment]
Get~~下期优化就会做哦~亲敬请期待

**Comment by purplebamboo** [comment]
项目里面目前是有的哈，在项目名称旁边有个批量操作的。

我的图标那边，这个星期我会加上去的，批量删除什么的。
