### ISSUE TITLE
[FR] 台湾同胞无法绑定手机，请支援台湾号码

### ISSUE THREAD

**Issue by ViolaTz** [thx/iconfont-plus#2081]
台湾同胞无法绑定手机号，
说没绑定会影响正常使用，我们有共同项目在上面，要是被影响该怎么办？

**Comment by Xiakecat** [comment]
同上，很不人性化的绑订，请尽快支援绑订台湾号码，中国专案的icon都在里面，要转移很麻烦。

**Comment by yisibl** [comment]
后面会支持更多国家或地区的手机。

**Comment by ndoli0919** [comment]
台灣地區手機沒辦法綁定，還說什麼一個中國？？？？

**Comment by Anp567** [comment]
> 后面会支持更多国家或地区的手机。

現在只能含淚忍耐，期待盡快支持...

大大辛苦了!!

**Comment by yisibl** [comment]
国外手机号已支持，注册时请填写对应国家或地区的区号即可，例如中国澳门：+853xxxxxx
