### ISSUE TITLE
[Help]微博帐号注销，请求将原帐号项目转移到新帐号

### ISSUE THREAD

**Issue by cxjanker** [thx/iconfont-plus#2082]
原微博帐号注销了，管理了多个项目，都是公司的项目，能否给转移到新账号里
原帐号昵称“陈老师不着调”，新帐号昵称“盖世英雄utd”

**Comment by yutent** [comment]
同问, 以前为了登录, 弄了个微博号, 结果因为长期没用微博, 被微博注销了。

搞的我现在也没法登录iconfont了

**Comment by yisibl** [comment]
请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)
