### ISSUE TITLE
不能注销账号~，手机绑定了不能解绑

### ISSUE THREAD

**Issue by listar** [thx/iconfont-plus#2085]
## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
账号删除功能已经上线，可以在账户设置中进行操作：https://www.iconfont.cn/user/center?tab=account
