### ISSUE TITLE
我之前邮箱注册的账号，没有绑定手机。换了台设备忘记密码找不回了。。

### ISSUE THREAD

**Issue by rinbowLi** [thx/iconfont-plus#2087]
我之前邮箱注册的账号，没有绑定手机。换了台设备忘记密码找不回了。。
找回只能手机号，邮箱不支持，很蛋疼

**Comment by yisibl** [comment]
新的找回密码只能给绑定了手机的账号使用，iconfont 老的账号只能通过微博或 GitHub 三方账号进行登录。

可以加一下钉钉答疑群帮你看看：
![image](https://user-images.githubusercontent.com/2784308/133039535-fc370bf6-7e08-41c3-9215-546cc7d80464.png)

**Comment by yisibl** [comment]
钉钉群沟通吧，我先关闭这个 issue 了
