### ISSUE TITLE
更新代码报错 Error

### ISSUE THREAD

**Issue by wang777777** [thx/iconfont-plus#2088]
iconfont 更新代码报错 Error

![image](https://user-images.githubusercontent.com/33274320/133390329-948c36f3-c7f1-4dcf-867f-c0b5a2f7e6d4.png)

**Comment by yisibl** [comment]
请提供项目 id

**Comment by wang777777** [comment]
> 请提供项目 id

路由上找的 projectId=1657352

**Comment by tvrrdfn** [comment]
@yisibl 
projectId=2001444
更新报错

**Comment by yisibl** [comment]
请检查一下最近是否添加了尺寸比较大的异形图标

**Comment by yisibl** [comment]
现在点击「生成代码」会提示具体有问题的图标了，请删除或修改图标尺寸重新上传即可。

![image](https://user-images.githubusercontent.com/2784308/138203081-bf624080-2dd9-409d-b561-c4fe5eedee81.png)
