### ISSUE TITLE
账号无法退出

### ISSUE THREAD

**Issue by AndrewTseZhou** [thx/iconfont-plus#2091]
## 问题描述
账号无法退出!!! 提示要绑定手机号! 为什么不绑定手机号 连账号都没法退出了!!!!!

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 期望结果
正常退出账号

## 平台/浏览器版本（重要）
- 操作系统及版本：
macOS 11.6
- 浏览器名称及版本：
Google Chrome 93.0.4577.82

**Comment by yisibl** [comment]
iconfont 之前只有三方登录，但这样问题很多。以微博三方登录为例，如果注销了微博就会导致无法登录 iconfont，所以我们开发了手机登录功能。绑定手机后，当账号出现异常也可以即时收到短信，使账户更加安全。

退出时弹出「去绑定」是因为之前很多用户退出登录后忘记原来使用哪个微博注册，从而导致无法找到老的账号。

如果确定暂时不用绑定手机号，需要退出登录，请按照以下步骤操作：

1. 在登录状态下，点击「快速绑定」按钮或直接打开 https://www.iconfont.cn/register?bind_mobile=1，
2. 再次点击右上角的「退出」即可退出登录。

最后，为了你的账号安全，我们建议尽快绑定手机号和安全邮箱。
