### ISSUE TITLE
点击搜索框效果如下这是不是一个bug

### ISSUE THREAD

**Issue by XujiaLin-DaShuaiGe** [thx/iconfont-plus#2094]
## 问题描述
点击搜索框，外边框看着像个bug
## 截图

![image](https://user-images.githubusercontent.com/87808465/135110211-3b41a5c5-066d-4138-b8b9-e981a197e089.png)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
这是 Chrome 的 bug，outline 没有适应圆角（border-radius），iconfont 目前用其他方式修复了。
