### ISSUE TITLE
无法查看图标

### ISSUE THREAD

**Issue by guoyunhe** [thx/iconfont-plus#2097]
## 问题描述

突然出现无法打开图标的问题

## 截图

![image](https://user-images.githubusercontent.com/5836790/135225215-2ea781e4-a087-4a64-bba2-dbc937676e6c.png)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
已经好了
