### ISSUE TITLE
下载代码为.json格式的文件

### ISSUE THREAD

**Issue by OliveKong** [thx/iconfont-plus#21]
加入购物车后，点击下载代码按钮，下载的是.json格式的文件，这是正确的？现在要引入iconfont只能是在线引用了是吗？不可以下载.ttf格式的了？

**Comment by purplebamboo** [comment]
可以的  这是个bug。请问是什么浏览器。

**Comment by gongeek** [comment]
您是firefox浏览器吗？改下扩展名为.zip就可以正常使用。
我们会尽快修复firefox下的这个bug

**Comment by OliveKong** [comment]
我是谷歌呀

**Comment by purplebamboo** [comment]
应该修复了 亲。

**Comment by OliveKong** [comment]
嗯嗯，已经好了
