### ISSUE TITLE
更新代码报错 Error

### ISSUE THREAD

**Issue by carrywong** [thx/iconfont-plus#2100]
项目 projectId=1376943

![image](https://user-images.githubusercontent.com/46438923/136747152-4ed0d8a1-e14e-4246-a257-8c57e57c18e1.png)

**Comment by yisibl** [comment]
现在点击「生成代码」会提示具体有问题的图标了，请删除或修改图标尺寸重新上传即可。

![image](https://user-images.githubusercontent.com/2784308/138203081-bf624080-2dd9-409d-b561-c4fe5eedee81.png)
