### ISSUE TITLE
SVG 上传空白，空白的 SVG 里面包含 <polyline> 或 <circle> 等 tag

### ISSUE THREAD

**Issue by SolidZORO** [thx/iconfont-plus#2101]
这个项目 Feather https://github.com/feathericons/feather/tree/master/icons 

想上传 icons 文件夹里面的 svg 到 iconfont，结果全都是空白。

我看了一下他们 SVG 的结构，大概是这样的：

```
<svg
  xmlns="http://www.w3.org/2000/svg"
  width="24"
  height="24"
  viewBox="0 0 24 24"
  fill="none"
  stroke="currentColor"
  stroke-width="2"
  stroke-linecap="round"
  stroke-linejoin="round"
>
  <circle cx="12" cy="12" r="10" />
  <line x1="12" y1="8" x2="12" y2="12" />
  <line x1="12" y1="16" x2="12.01" y2="16" />

  或者

  <polyline points="22 12 18 12 15 21 9 3 6 12 2 12" />

</svg>
```

是不是目前 iconfont 只认 `<path>` 这个 tag？

这里有几个 demo svg，如果有时间可以帮忙调试看看是什么问题嘛吗？

[feather-3-demo-svg.zip](https://github.com/thx/iconfont-plus/files/7326934/feather-3-demo-svg.zip)

**Comment by yisibl** [comment]
我们将统一在这个 issue 跟踪：https://github.com/thx/iconfont-plus/issues/1937
