### ISSUE TITLE
急急急！我选择了593个icon，但无法下载

### ISSUE THREAD

**Issue by PooKiZhang** [thx/iconfont-plus#2102]
DevTools 无法加载源映射： 无法加载chrome-extension://popomkonnjgcdagdhgcpcekbdeoibglc/js/xl-content.js.map 的内容:HTTP 错误: 状态代码 404，net::ERR_UNKNOWN_URL_SCHEME

按F12 提示这个信息

我选择了593个icon，手动点的，点了593次，但当点击下载的时候，报错了，如上

如何解决？
![image](https://user-images.githubusercontent.com/45157248/136925038-34406b65-27ba-4dae-afd0-ef10ba1cedc7.png)

**Comment by PooKiZhang** [comment]
急急急！

**Comment by yisibl** [comment]
看起来这是浏览器插件的报错，请用隐身模式或禁用插件。
