### ISSUE TITLE
账户数据丢失，新版本将我的账户数据独立出去了，绑定的信息在一个新的账户

### ISSUE THREAD

**Issue by RayJason** [thx/iconfont-plus#2103]
## 问题描述
账户数据丢失，一个账户被拆成两个。

## 截图
![image](https://user-images.githubusercontent.com/15711610/136933127-dce8ed4d-027c-4a9f-a6e6-bf01193ea4c3.png)

![image](https://user-images.githubusercontent.com/15711610/136933097-4524bc26-a648-44af-bd1c-a7f8ac316348.png)

## 期望结果
请求帮我恢复数据，谢谢～

## 相关信息（重要）
- iconfont 的用户昵称：RayJason

**Comment by yisibl** [comment]
另外，不要在公开场合暴露你账户的邮箱和带星号手机，这会泄露你的隐私。

**Comment by jifengmm** [comment]
你好我的一个项目也没有了，我之前好像是用邮箱登录的，邮箱是 1039416195@qq.com。账号名称为 jifengmm
还有我可以通过下载的iconfont.json，将之前下载下来的项目重新导入回我的新账户中吗。
