### ISSUE TITLE
下载项目，更新代码失败

### ISSUE THREAD

**Issue by hejianneng** [thx/iconfont-plus#2105]
https://www.iconfont.cn/manage/index?manage_type=myprojects&projectId=1517760
![image](https://user-images.githubusercontent.com/12930137/137084796-d8c4a3ff-9536-4643-bcc0-c1e6be492a00.png)

**Comment by yisibl** [comment]
现在点击「生成代码」会提示具体有问题的图标了，请删除或修改图标尺寸重新上传即可。

![image](https://user-images.githubusercontent.com/2784308/138203081-bf624080-2dd9-409d-b561-c4fe5eedee81.png)
