### ISSUE TITLE
图标风格不一,希望能够增加付费扩展。

### ISSUE THREAD

**Issue by zhougonglai** [thx/iconfont-plus#211]
一个项目要用到的icon非常多,老板要求项目风格统一.图标之间的差异性比较大,希望能够 付费给 作者 针对 关键字进行 图标拓展.
当然是 公共模块的会更好.
作者会有额外收入,市场会有更多反馈.
加速提升 市场需求.质量非常高的图标 ，
并且 未补完备 的 图标.

**Comment by purplebamboo** [comment]
亲   项目里的风格如果你要统一的话，可以直接全部用某一个公共库里的图标的，那样风格肯定统一。

平台其实提供了大赏机制提高设计师积极性。


另外针对你的付费需求，你可以直接在你喜欢的公共库下面留言，联系作者让他们单独给你们设计一个公共库给你们用。

iconfont不会做这种付费定制的事情哈，你们可以私下约定的。
