### ISSUE TITLE
请求iconfont上的静态资源文件，网络报错 net::ERR_HTTP2_PROTOCOL_ERROR [Help]

### ISSUE THREAD

**Issue by wangdaxiaoda** [thx/iconfont-plus#2113]
## 问题描述
项目中请求资源css：//at.alicdn.com/t/font_2046281_tpgbzmp9u1.css，概现网络错误，导致资源加载失败，icon显示不出来

## 相关截图
![image](https://user-images.githubusercontent.com/17582231/139246726-9b12cc58-9498-4cd7-88f9-54000397d7ac.png)
![image](https://user-images.githubusercontent.com/17582231/139246749-e6f87309-940b-4471-9dc2-970e63c7cccc.png)

**Comment by yisibl** [comment]
无法复现，请更换其他网络，比如4G 再试一下。
