### ISSUE TITLE
[Help]Unicode字体图标使用color:#fff会比使用其他颜色偏粗

### ISSUE THREAD

**Issue by jiasber** [thx/iconfont-plus#2115]
## 问题描述
使用Unicode 白色会出现 使用svg引入不会有这样情况
## 相关截图
.iconfont {
  font-family: 'iconfont' !important;
  font-size: 60px;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  -webkit-text-stroke-width: 0.2px;
  -moz-osx-font-smoothing: grayscale;
}
![image](https://user-images.githubusercontent.com/26052131/140243727-eccb7d8e-92fc-4f62-9b94-fe21661b7008.png)

**Comment by yisibl** [comment]
视觉错觉
