### ISSUE TITLE
我用微博登录绑定了手机号，然后刚刚用另外一个微博登录没有绑定登录没有办法退出，急，急，急，现在用不了咯

### ISSUE THREAD

**Issue by larrylr** [thx/iconfont-plus#2120]
## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
请看：https://github.com/thx/iconfont-plus/issues/2092
