### ISSUE TITLE
微博登录的账户突然丢失了最近几年的项目

### ISSUE THREAD

**Issue by vChenoo** [thx/iconfont-plus#2122]
## 问题描述
微博登录的账户突然丢失了最近几年的项目，可能是微博绑定了手机号码？？原昵称是miff橙，现在昵称自动改为了微博账户的昵称

**Comment by yisibl** [comment]
应该是登录到其他的微博上去了，每个微博对应不同的 iconfont 账号。
如果还没解决请加群：https://github.com/thx/iconfont-plus/issues/2092
