### ISSUE TITLE
下载AI格式的图标，点击AI下载竟然下载出来SVG格式的图标

### ISSUE THREAD

**Issue by spume123** [thx/iconfont-plus#213]
下载AI格式的图标，点击AI下载竟然下载出来SVG格式的图标

**Comment by purplebamboo** [comment]
嗯  目前eps的格式 对于彩色图标还有点问题，我们还在解决中哈。

**Comment by spume123** [comment]
意思是现在还不能下载AI格式的图标是吗？

**Comment by purplebamboo** [comment]
嗯嗯  对的  但是其实亲   svg格式  直接可以用  ai打开编辑的呀。

也可以直接通过ai转换成  eps的

**Comment by spume123** [comment]
好的，非常感谢哈
