### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by wx11111** [thx/iconfont-plus#2130]
您好！感谢您让我免费使用此字体库，为了进一步完善，提出以下一点建议：
当我使用微博账号登录时，提示我需要绑定手机号，当我输入手机号时，提示我该手机号已注册，请使用手机号登录，当我使用手机号登录想要绑定微博时，提示我该第三方账号已注册账号，无法绑定，请换一个第三方账号，请问，我只有这一个手机号和微博，我该怎样用我自己的手机号绑定我自己的微博，无奈之下，只好注销手机号账号，重新绑定，希望意见可以被看到，做出改进，使得用户体验更加人性化。

**Comment by yisibl** [comment]
在未登录之前，iconfont 是不知道用户是否有历史账号的，所以推荐的流程是先使用三方账号登录老的账号，再绑定手机。

如果手机不小心注册成为了一个全新账号，目前只能注销。
