### ISSUE TITLE
标题请简明扼要，具体内容写在下面

### ISSUE THREAD

**Issue by alexlufa** [thx/iconfont-plus#2134]
## 问题描述
打开 iconfont 图标编辑按钮 提升找不到该图标， 项目 owner 可以看到编辑界面，其他人都看不到
## 截图

![image](https://user-images.githubusercontent.com/15064199/146498463-4509efc1-1636-458b-ba1a-2fc7cd9bad16.png)

## 重现步骤
1. 打开：我的项目
2. 点击：图标的编辑按钮
3. 出现：弹窗加载，提示找不到该图标，但项目创建者可以正常打开

## 期望结果
可以查看并编辑图标
## 相关信息（重要）
- 发生问题的 URL：https://www.iconfont.cn/manage/index?spm=a313x.7781069.1998910419.db775f1f3&manage_type=myprojects&projectId=2151960
- iconfont 的用户昵称：alexlufa
- iconfont 项目 ID：e7d4079dea5c-2151960

2151960
## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：macOS 12.0.1

- 浏览器名称及版本：Google Chrome 96.0.4664.110（正式版本） (x86_64)

**Comment by yisibl** [comment]
请修改标题，不要使用默认文案
