### ISSUE TITLE
关于搜索的小bug，请及时修复

### ISSUE THREAD

**Issue by xiemin2161** [thx/iconfont-plus#214]
如图，这个搜索按钮点击没有反映
只能按回车搜索
![_2016-11-28t09-16-54 740z](https://cloud.githubusercontent.com/assets/23207744/20662620/12c71e44-b58f-11e6-94ee-2f46c8b27f97.png)

**Comment by purplebamboo** [comment]
= = 额。。这个本来设计就不是可以点的呀。他有个hover弹出的效果，如果再加一个点击，好像有点怪哎。
