### ISSUE TITLE
已收藏的图标库无法在个人主页里查看

### ISSUE THREAD

**Issue by xtnp** [thx/iconfont-plus#2142]
## 问题描述
已收藏的图标库无法在个人主页里查看
## 截图
![image](https://user-images.githubusercontent.com/13042978/147720728-91a3aafd-eae0-40bb-8ec3-2acc490383bd.png)
![image](https://user-images.githubusercontent.com/13042978/147720811-2ade5f27-72ce-4194-a43d-fe12fcb396fb.png)

![image](https://user-images.githubusercontent.com/13042978/147720762-eae36f96-1b71-46c7-9271-709d9cf5a8c9.png)

## 重现步骤
1. 打开：个人主页
2. 点击：收藏
3. 出现：无图标库

## 期望结果
显示收藏图标库
## 相关信息（重要）
- 发生问题的 URL：https://www.iconfont.cn/user/detail?spm=a313x.7781069.1998910419.d402eebd7&userViewType=likes&uid=943925
- iconfont 的用户昵称：xtnp
- iconfont 项目 ID：13696920690

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：win10

- 浏览器名称及版本：华为浏览器 11.0.8.301

![image](https://user-images.githubusercontent.com/13042978/147720890-20dd27f1-b0f2-42ff-8bf5-751d1ed0f42f.png)

**Comment by yisibl** [comment]
从个人主页重新进去：https://www.iconfont.cn/user/detail?spm=a313x.7781069.1998910419.d402eebd7&userViewType=likes&uid=943925&nid=B3CV4oSgBUIB
