### ISSUE TITLE
无法设置PNG下载路径

### ISSUE THREAD

**Issue by mini443** [thx/iconfont-plus#215]
下载PNG的时候直接下载到我浏览器设置的路径里面去了，不会弹出那个选择路径框

**Comment by mini443** [comment]
![image](https://cloud.githubusercontent.com/assets/23074356/20663045/115c90fa-b591-11e6-9dc7-55dcec62561f.png)
下载SVG时的状态   
![image](https://cloud.githubusercontent.com/assets/23074356/20663084/2cb39d3a-b591-11e6-9feb-c07870ebbf33.png)
点击下载PNG直接跳转到 这里

**Comment by Muqing1221** [comment]
会不会是浏览器的设置问题？

**Comment by purplebamboo** [comment]
亲  这个是浏览器自己设置的呀。

在高级配置里面，设置 每次下载询问下载路径哈。
