### ISSUE TITLE
导入svg图标部分被填色

### ISSUE THREAD

**Issue by zomfo** [thx/iconfont-plus#2150]
## 截图
svg图片内容为：
![image](https://user-images.githubusercontent.com/46883068/148636270-b498ee8b-d583-4f6e-8a1c-dff3f541624a.png)
导入后，实际icon为
![image](https://user-images.githubusercontent.com/46883068/148636204-f28dcd4d-8ec2-4046-b66a-94b71062d603.png)

## 重现步骤
1. 点击上传ICON
2. 选择svg图片
3. 导出成功后查看icon

## 期望结果
导入成功的icon与svg图片一致，但实际上不一致

## 相关信息（重要）
- 发生问题的 URL：https://www.iconfont.cn/icons/upload?spm=a313x.7781069.1998910419.d1baf4ee7&type=icon
- iconfont 的用户昵称：ZhenFu-T

## 相关文件（重要）
导入的svg文件如下
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="500" height="500" viewBox="0 0 500 500" fill="none"><path id="排除重叠" fill-rule="evenodd" style="fill:#C4C4C4" transform="translate(0 0)  rotate(0 250 250)" opacity="1" d="M500 450C500 477.61 477.61 500 450 500L50 500C36.74 500 24.02 494.73 14.64 485.36C5.27 475.98 0 463.26 0 450L0 50C0 36.74 5.27 24.02 14.64 14.64C24.02 5.27 36.74 0 50 0L450 0C463.26 0 475.98 5.27 485.36 14.64C494.73 24.02 500 36.74 500 50L500 450ZM30 83C30 69.74 35.27 57.02 44.64 47.64C54.02 38.27 66.74 33 80 33L420 33C433.26 33 445.98 38.27 455.36 47.64C464.73 57.02 470 69.74 470 83L470 133L30 133L30 83ZM156 173L30 173L30 299L156 299L156 173ZM305 173L305 299L196 299L196 173L305 173ZM470 173L470 299L344 299L344 173L470 173ZM31 415C31 428.26 36.27 440.98 45.64 450.36C55.02 459.73 67.74 465 81 465L157 465L157 339L31 339L31 415ZM197 465L197 339L306 339L306 465L197 465ZM471 339L345 339L345 465L421 465C448.61 465 471 442.61 471 415L471 339Z" /></svg>
```

## 平台/浏览器版本（重要）
- 操作系统及版本：
windows10
- 浏览器名称及版本：
Google Chrome版本 96.0.4664.110（正式版本） （64 位）

**Comment by yisibl** [comment]
当前不支持 `fill-rule="evenodd"` 填充模式的图标，需要转换一下，参考：https://zhuanlan.zhihu.com/p/137298478

**Comment by zomfo** [comment]
好的 ，转换下正常显示了，谢谢
