### ISSUE TITLE
svg文件，修改了path的fill属性为currentColor，上传失败。

### ISSUE THREAD

**Issue by purple-force** [thx/iconfont-plus#2153]
![image](https://user-images.githubusercontent.com/16146970/148936700-aada75a7-0fe4-4580-ae81-196be37320df.png)

<?xml version="1.0" encoding="UTF-8"?>
<svg width="16px" height="16px" viewBox="0 0 16 16" version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <title>快照备份</title>
    <g id="双色icon规范" stroke="none" stroke-width="1" fill="none" fill-rule="evenodd">
        <g id="双色icon使用规范" transform="translate(-1345.000000, -2224.000000)" fill-rule="nonzero">
            <g id="快照备份" transform="translate(1345.000000, 2224.000000)">
                <g id="安全组-Security-group-fill" transform="translate(2.000000, 1.000000)">
                    <path d="M6.66135827,0 L12.5901833,1.06719674 C13.0493034,1.14985894 13.3826286,1.54381688 13.3824228,2.0031428 L13.3824228,6.62738751 C13.3824228,9.16315074 11.9376358,11.4845893 9.64275618,12.6359924 L7.12984601,13.8963078 C6.85376465,14.0345641 6.52865809,14.0345641 6.25257673,13.8963078 L3.51175361,12.5210065 C1.43675749,11.4800599 0.0953240266,9.41607853 0.00483826053,7.12500775 L0,6.87969765 L0,2.00128985 C0.000205883427,1.54247863 0.333016443,1.14924129 0.791210009,1.06627027 L6.66135827,0 Z" id="路径" fill="#383838"></path>
                    <path d="M7.70317124,2.98552184 L5.78593902,2.98552184 L5.7726195,2.98610523 C5.69766078,2.99291082 5.63884103,3.05591115 5.63864658,3.13291155 L5.63864658,5.04975489 L5.63922992,5.06317162 C5.64603551,5.13832479 5.70903584,5.19733899 5.78603624,5.19733899 L6.51510949,5.19733899 L6.51510949,5.54160467 L4.63064132,5.54160467 L4.61119678,5.54218801 C4.41091796,5.5523964 4.25108379,5.71991116 4.25108379,5.92466223 L4.25108379,6.81318075 L3.50587157,6.81318075 L3.49206594,6.81376409 C3.41361751,6.8212428 3.35375754,6.88721092 3.35391214,6.96601488 L3.35391214,8.9572336 L3.35449578,8.97123367 C3.36137792,9.04981018 3.42699504,9.11020153 3.50587157,9.11055384 L5.47968742,9.11055384 L5.49359027,9.10997051 C5.56687674,9.10293098 5.62469466,9.0445815 5.63106321,8.97123367 L5.63164654,8.9572336 L5.63164654,6.96640377 L5.63106321,6.95250092 C5.62437501,6.87402248 5.55893533,6.81360041 5.48017353,6.81318075 L4.7066695,6.81318075 L4.7066695,6.00127374 L8.77894074,6.00127374 L8.77894074,6.81308353 L8.03392296,6.81308353 L8.02011734,6.81376409 C7.94170741,6.82128975 7.88190143,6.8872448 7.88206106,6.96601488 L7.88206106,8.9572336 L7.8826444,8.97123367 C7.88954721,9.04930353 7.95458922,9.11055384 8.03392296,9.11055384 L10.007836,9.11055384 L10.0216417,9.10997051 C10.1000793,9.10224977 10.1597823,9.03614706 10.1595045,8.95733082 L10.1595045,6.96630655 L10.1588229,6.9524037 C10.1520429,6.87393162 10.0865991,6.81354466 10.007836,6.81308353 L9.23472089,6.81308353 L9.23472089,5.92446778 L9.23423478,5.90482879 C9.22402639,5.70260551 9.05777553,5.54150745 8.85487169,5.54150745 L6.9706952,5.54150745 L6.9706952,5.19733899 L7.70287957,5.19733899 L7.71629631,5.19675565 C7.78722382,5.19029327 7.84341796,5.13409914 7.84988034,5.06317162 L7.85046367,5.04975489 L7.85046367,3.13291155 L7.84988034,3.1193976 C7.84293963,3.04351721 7.77927114,2.9854566 7.70307402,2.98552184 L7.70317124,2.98552184 Z" id="路径" fill="currentColor"></path>
                </g>
            </g>
        </g>
    </g>
</svg>

**Comment by yisibl** [comment]
目前不支持 currentColor
