### ISSUE TITLE
[Help] 选择 Github 登录显示页面出错

### ISSUE THREAD

**Issue by bambooom** [thx/iconfont-plus#2154]
## 问题描述
选择 GitHub 账号登录，跳转回来页面显示页面出错
## 相关截图
![Screen Shot 2022-01-13 at 10 20 09 AM](https://user-images.githubusercontent.com/14840170/149254401-e97225d7-17e3-4489-838f-cc6dd45a6233.png)

**Comment by houyhea** [comment]
同问，有能处理一下的吗？着急~~~

**Comment by wayneCui628** [comment]
遇到了同样的问题

**Comment by ShaoGuo520** [comment]
同问，有能处理一下的吗？着急~~~

**Comment by yisibl** [comment]
正在排查中，GitHub 由于有被墙的风险，请大家在恢复 GitHub 登录后尽快绑定手机号，这样不依赖三方登录。
