### ISSUE TITLE
标题请简明扼要，具体内容写在下面

### ISSUE THREAD

**Issue by yangjiaxin1995** [thx/iconfont-plus#2156]
## 问题描述
UI是不是错位了？

## 截图
![image](https://user-images.githubusercontent.com/50611577/150343033-5984511c-b65d-4562-a726-411b52863f7f.png)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
Thanks, 已修复。
