### ISSUE TITLE
【无法直接上传项目图标】

### ISSUE THREAD

**Issue by koolyang** [thx/iconfont-plus#2157]
## 【无法直接上传项目图标】
在项目里上传图标后，图标跑到我的资源了
## 截图
![image](https://user-images.githubusercontent.com/98135490/150450585-66d1ce34-af36-45be-b73f-32c4dd47bceb.png)
![Snipaste_2022-01-21_09-44-38](https://user-images.githubusercontent.com/98135490/150450615-59adadd2-5c0e-4be6-bd0b-1db64e4fc27a.png)

## 重现步骤
1. 打开：项目
2. 点击：上传图标
3. 出现：项目里没有刚刚上传的图标，只在我的资源出现

## 相关信息（重要）
- 发生问题的 URL：https://www.iconfont.cn/manage/index?spm=a313x.7781069.1998910419.db775f1f3&manage_type=myprojects&projectId=2072170&keyword=&project_type=&page=
- iconfont 的用户昵称：大高杨
- iconfont 项目 ID：78e347592923-2072170

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by jasminefeng** [comment]
我也是遇到这样的问题

**Comment by yisibl** [comment]
已修复，thanks。

**Comment by jasminefeng** [comment]
您好，！您的邮件我已经收到，我将尽快给您回复。谢谢！
