### ISSUE TITLE
搜索出来的图标页面错位

### ISSUE THREAD

**Issue by wuwiwo** [thx/iconfont-plus#2160]
## 问题描述
搜索出来的图标页面错位，直接进入分类的没问题。

## 截图

![image](https://user-images.githubusercontent.com/38783494/150903007-80bda10d-889f-4236-8bfe-1242bb3c0ae0.png)

## 重现步骤
1. 打开：首页
2. 搜索：任意图标（如**疫苗**）
3. 出现：搜索结果

## 期望结果
正常的页面

## 相关信息（重要）
- 发生问题的 URL：iconfont.cn/search/index?searchType=icon&q=疫苗
- iconfont 的用户昵称：by时不知归
- iconfont 项目 ID：无

## 平台/浏览器版本（重要）
- 操作系统及版本：
Windows 10 1909
Windows 10 2004
- 浏览器名称及版本：
> 以下两个都有问题
Google Chrome 97.0.4692.71
Edge  97.0.1072.69

**Comment by yisibl** [comment]
很抱歉，我这边无法复现，请用浏览器的隐身模式再试试。

**Comment by wuwiwo** [comment]
已尝试隐身模式是可以的，请问这个是缓存的原因吗？
不知道是不是这个css的原因，注释掉就正常了。
![image](https://user-images.githubusercontent.com/38783494/150941717-e7a4c547-4ec6-4dd5-aac6-fcdc21e2b50e.png)

**Comment by yisibl** [comment]
应该是缓存，清理一下浏览器缓存试试。
