### ISSUE TITLE
江西赣州地区无法加载iconfont在线链接

### ISSUE THREAD

**Issue by Aaron0525** [thx/iconfont-plus#2171]
## 问题描述
项目使用了iconfont作为图标库，引入方式：复制在线链接，目前出现以下问题：2022-20-23 ~ 至今，江西赣州地区客户反馈软件中字体图标全部丢失，经过排查是iconfont库无法加载，其它地区正常，请问这块官方能帮忙看看吗？

## 截图

将链接的地址发给客户用手机浏览器也无法正常加载，如下图：
![image](https://user-images.githubusercontent.com/25900981/155501370-73ce9021-4f98-43b3-9251-8eca2cb5222e.png)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 期望结果
期望能像之前一样正常加载。
## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：森果+杨钊
- iconfont 项目 ID：1633581

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by ChaoQunPeng** [comment]
南昌地区，也是偶尔加载不出来
