### ISSUE TITLE
iconfont编辑后的颜色16进制值没有保存

### ISSUE THREAD

**Issue by shiyubi123** [thx/iconfont-plus#2174]
## 问题描述
iconfont编辑后的颜色16进制值没有保存
## 截图

![image](https://user-images.githubusercontent.com/49309748/155934604-8010cad4-445d-45d1-bedd-1ac3b0291459.png)

## 重现步骤
1. 打开：打开icon-font编辑，更换font颜色，保存
2. 点击：再次编辑
3. 出现：icon-font的十六进制颜色配置依旧为#333333

## 期望结果
保存有已经配置的十六进制颜色
## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：shiyubi123
- iconfont 项目 ID：3209501

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

win10 专业版
- 浏览器名称及版本：

 Google Chrome 98.0.4758.102

**Comment by yisibl** [comment]
这里这是一个颜色选择器的默认值，设计就是初始值是 `#333333`。因为有的图标有多种颜色，这里不太好定义。
