### ISSUE TITLE
希望图片编辑颜色的时候可以设置渐变颜色

### ISSUE THREAD

**Issue by wh123660** [thx/iconfont-plus#2177]
希望网页端编辑图标颜色的时候可以设置成渐变颜色，因为最近的App基本上都有渐变色了，所以，选择图标的时候，还需要修改渐变颜色，否则需要我们下载出来之后再让ui改下颜色才能用

**Comment by yisibl** [comment]
当前 iconfont 还不支持渐变色，请参阅：https://github.com/thx/iconfont-plus/issues/1938
