### ISSUE TITLE
希望增加复制(克隆)项目的功能

### ISSUE THREAD

**Issue by tianyiw2013** [thx/iconfont-plus#2179]
## 需求背景
想基于某个项目，复制为新项目，然后往新项目里增加图标。目前好像没有这样的功能，只能加入购物车、然后再加入到项目，略微繁琐。

相关的issus #506 但我觉得根这个需求不太一样，他想要的是复制图标到另一个项目，我这个需求是复制整个项目为一个新项目（克隆）。

## 解决方案
在项目>更多操作，增加克隆项目，然后弹出输入框输入新项目名称。（或者叫做 克隆项目）

## 相关截图
![微信截图_20220313182730](https://user-images.githubusercontent.com/4644588/158055301-af1a676a-6270-4cd6-8176-75c46641d529.png)

**Comment by Mi-liu** [comment]
同上，太需要了

**Comment by yisibl** [comment]
克隆项目功能上线了。
