### ISSUE TITLE
是bug吧？！！！icon换个颜色下载出错

### ISSUE THREAD

**Issue by chan0925** [thx/iconfont-plus#218]
如图：下载某个icon的时候自定义颜色就会这样
![b2fd8f18-43c8-470e-b5c2-f341430f130c](https://cloud.githubusercontent.com/assets/23234627/20695383/7fee82b8-b626-11e6-9054-7689740135d1.png)

**Comment by purplebamboo** [comment]
出错是指？ 亲  我试了下正常呀。

你是指设置颜色无效？  还是说设置颜色，一下子所有颜色都被改了？


如果是后者，那么其实你可以点击里面的图层的，是可以分开设置不同图层的颜色的哦。
