### ISSUE TITLE
火狐50.0的版本 复制代码提示版本过低？

### ISSUE THREAD

**Issue by LOADINGG** [thx/iconfont-plus#219]
如题~
对浏览器版本要求也太高了吧
![ff](https://cloud.githubusercontent.com/assets/6230922/20699622/38686536-b643-11e6-9e0a-4347c8f9cc50.png)

**Comment by gongeek** [comment]
理论上这些都支持：https://github.com/zenorocha/clipboard.js#browser-support
我本地试了49也是支持的 50 我们待会测下

**Comment by purplebamboo** [comment]
亲  我们测试了没问题呀，这个也是用的第三方开源的东西，理论上不会有问题的。

建议亲可以先使用chrome浏览器哈。
