### ISSUE TITLE
[Help] 不同情况下下载的 SVG 大小不一致

### ISSUE THREAD

**Issue by wangxiaocuo** [thx/iconfont-plus#2193]
## 问题描述

我一个同事的电脑，Windows，用 Chrome 下载的 SVG 很大，有 93k。该同事用 Edge 下载，就是正常的 1K。
我用 Mac，我和我另外一个用 Windows 的同事几个浏览器都试了，都是正常的 1k。

通过对比发现，93K 的 SVG，其中的 @font-face 是以 base64 的形式嵌入的。而 1k 的是 url 形式的。

这个是有什么规律吗？什么情况下会是 base64？可以主动控制下载哪种形式吗？

## 相关截图

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/16472134/161191583-ba23a618-73ca-4743-9d04-3d35f2c6ce06.png">
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/16472134/161191604-31374684-8790-4690-9aa9-e8ce8eb7bf25.png">
<img width="689" alt="image" src="https://user-images.githubusercontent.com/16472134/161191626-fab1000f-a804-4553-a845-532b67204c83.png">

**Comment by yisibl** [comment]
请再试一下。

**Comment by wangxiaocuo** [comment]
> 请再试一下。

抱歉刚看到，现在正常了
