### ISSUE TITLE
[Help]进入我的项目一直在loading，控制台报错e.name.replaceAll is not a function

### ISSUE THREAD

**Issue by huxx5429** [thx/iconfont-plus#2196]

**Comment by sws797** [comment]
你可以换个浏览器试试，我用QQ浏览器也是这样，换Edge就可以了

**Comment by huxx5429** [comment]
> 
我用chrome和Firefox都不行

**Comment by sws797** [comment]
我这 chrome 可以，就qq浏览器不行

**Comment by huxx5429** [comment]
> 我这 chrome 可以，就qq浏览器不行

我刚开始怀疑是我账号问题，因为同事都可以看，然后就切换成同事的账号密码发现还是不行

**Comment by oldmanvv** [comment]
@huxx5429 @sws797 你好，该问题已经修复。

**Comment by sws797** [comment]
@OlddogClock 你好，方便说一下是什么原因造成的吗，我自己也是前端，但是在我看来这只像一个网络问题，没有解决方向

**Comment by yisibl** [comment]
旧版本的浏览器不支持 `replaceAll()` 方法，换成了 `replace()`

**Comment by sws797** [comment]
@yisibl 绝了，我是最新版的QQ浏览器，查了下`replaceAll()`的兼容性应该也没问题。。。总不能是你们后端渲染完成之后才输出到前端吧，如果这样也应该是所有人都加载不了。我晕了😵
![image](https://user-images.githubusercontent.com/33458935/162359573-1fbfd229-7e3a-4bb4-a929-4817f4a0e4fc.png)

**Comment by yisibl** [comment]
@sws797 得看一下 QQ 浏览器使用的内核版本是多少？

**Comment by sws797** [comment]
@yisibl 
![image](https://user-images.githubusercontent.com/33458935/162385130-3d487ff2-d99b-48ba-8a64-a33aa73ec365.png)
确实是低版本，牛！👍
