### ISSUE TITLE
icon删除后不能撤销

### ISSUE THREAD

**Issue by ludeng0310** [thx/iconfont-plus#2198]
## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by oldmanvv** [comment]
是项目中删除图标吧？预计下周解决

**Comment by yisibl** [comment]
感谢反馈，已修复
