### ISSUE TITLE
图标删除后无法再次添加

### ISSUE THREAD

**Issue by caishun2013** [thx/iconfont-plus#2199]
## 重现步骤
添加图标到我的项目中后，然后再删除（因为修改后无法恢复到原样才删除的-。-），再次添加时就会添加不了，如果能添加就再删再添加，一般最多2次后就不能再添加到删除图标的那个项目中了

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：妈妈说小孩子哪来的腰
- iconfont 项目 ID：3307590

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：、
- win10 企业版

- 浏览器名称及版本：

谷歌浏览器

**Comment by yisibl** [comment]
感谢反馈，已修复
