### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by OliveKong** [thx/iconfont-plus#22]
1.项目中，复制代码按钮有时候不好用
2.彩色的小图标引用到网页后依然是灰色的

**Comment by purplebamboo** [comment]
1. 复制代码目前使用的是flash，好像兼容性有点问题，这个稍后我们会修复的，
2. 彩色图标，只有symbol的方式可以用哈，亲可以下载项目到本地。看下三个demo。unicode，font_class都是字体，是不支持彩色的哦。
