### ISSUE TITLE
细节方面希望优化一下,和原网站不一样的地方

### ISSUE THREAD

**Issue by lifetin** [thx/iconfont-plus#220]
细节方面希望优化一下,和原网站不一样的地方

1,点击某个图标,下载,填入 **大小和颜色** 下载
2,关闭下载框
3,换个图标,点击下载 
 这里的**大小和颜色**, 马上又恢复到默认值了.不是前一次自己填写的值.

希望能优化一下这里.下载过后,自动记录上次填写的颜色值和大小.因为APP中需要图标,肯定每次都是要下载一样大小的图片了.这样避免每次都要重填写.谢谢

**Comment by purplebamboo** [comment]
好的，这个我们评估过，觉得意义不大，因为有历史颜色记录了。

但是既然有这个需求，那我们就加上。这周弄完哈。

**Comment by purplebamboo** [comment]
已经弄好，请注意查看。
