### ISSUE TITLE
font class 下载后变成黑色

### ISSUE THREAD

**Issue by bjsbl** [thx/iconfont-plus#2203]
现象：
在4.11下载的版本里，font class 还是彩色的，可以正常使用
![e1](https://user-images.githubusercontent.com/1332511/163363545-d01b10fd-0dc8-4fb2-929a-554e57f7c71b.png)

在更新文件后，再下载后，就变成黑色的，symbol正常
![e2](https://user-images.githubusercontent.com/1332511/163363670-f515231b-07c6-478a-897a-3ca0641dcd6f.png)

求解：
如何下载后可以得到彩色的font class

**Comment by yisibl** [comment]
请提供截图中的链接

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: SANT ***@***.***&gt;
发送时间: 2022年4月14日 18:10
收件人: thx/iconfont-plus ***@***.***&gt;
抄送: Subscribed ***@***.***&gt;
主题: Re: [thx/iconfont-plus] font class 下载后变成黑色 (Issue #2203)





 
现象：
 在4.11下载的版本里，font class 还是彩色的，可以正常使用
 
 
在更新文件后，再下载后，就变成黑色的，symbol正常
 
 
求解：
 如何下载后可以得到彩色的font class

**Comment by bjsbl** [comment]
是css的链接吗

**Comment by yisibl** [comment]
项目链接以及这个demo 链接


------------------ 原始邮件 ------------------
发件人: SANT ***@***.***&gt;
发送时间: 2022年4月14日 18:28
收件人: thx/iconfont-plus ***@***.***&gt;
抄送: 一丝 ***@***.***&gt;, Comment ***@***.***&gt;
主题: Re: [thx/iconfont-plus] font class 下载后变成黑色 (Issue #2203)





 
是css的链接吗

**Comment by yisibl** [comment]
我看了一下，目前彩色字体项目不支持超过 40 个图标。

**Comment by bjsbl** [comment]
oh god~
