### ISSUE TITLE
库简介多行时溢出

### ISSUE THREAD

**Issue by LUFEIllllll** [thx/iconfont-plus#2208]
文字显示超范围

## 问题描述
文字显示超范围
## 截图
https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512&cid=39186
![1751650356121_ pic](https://user-images.githubusercontent.com/96859233/163957247-aae1945b-88fb-464f-9109-b091b7f310d3.jpg)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
感谢反馈，已修复
