### ISSUE TITLE
希望可以在【我的项目】里面直接上传图标

### ISSUE THREAD

**Issue by DX-WEB** [thx/iconfont-plus#222]
现在上传图标到项目需要执行上传svg到【我的图标】，再从【我的图标】添加到购物车，再从购物车添加到【我的项目】里面，中间的流程太繁琐，能否直接在【我的项目】里面上传图标？

**Comment by purplebamboo** [comment]
项目里面的图标都是一份拷贝，必须要有个原始的图标映射。
比如你的项目的图标本身肯定有一个对应的原始图标（可以是别人上传的，也可以是自己上传的）。


项目里目前支持针对一个图标替换它的svg哈，当然这个应该不能完全解决你的问题。

我们目前在计划做这样一个功能，就是上传图标后，在上传界面直接添加到项目里，这些图标也会在 【我的图标】里有记录，相当于把后面几步流程省略哈。

这样应该可以解决你的问题。

**Comment by DX-WEB** [comment]
感谢快速反馈，期待你们的更新^^

**Comment by yisibl** [comment]
近期会优化上传的交互

**Comment by yisibl** [comment]
已经支持。
