### ISSUE TITLE
为什么不能注册？

### ISSUE THREAD

**Issue by Aric-Rondstedt** [thx/iconfont-plus#2226]
点击注册按钮如下图

![image](https://user-images.githubusercontent.com/87656963/173070379-f5281400-6863-45a6-a87e-924bd8870f13.png)

**Comment by Hanguangguang1993** [comment]
这个登录不了，注册不了，网站只能看啊

**Comment by chizizhixin** [comment]
同问

**Comment by MinjingLin** [comment]
同问

**Comment by codelibo** [comment]
//??????

**Comment by kirk-ye** [comment]
已经恢复
