### ISSUE TITLE
新建醒目没有https://at.alicdn.com/域名生成功能了

### ISSUE THREAD

**Issue by divspana** [thx/iconfont-plus#2227]
## 需求背景 之前有这个连接的，新建项目哪里一键生成连接
<img width="546" alt="image" src="https://user-images.githubusercontent.com/93388814/173098644-a8970eca-b50f-4878-b211-5144c742f33e.png">

**Comment by lvhaibin** [comment]
好像也没有上传资源入口了。

**Comment by zy0228** [comment]
是不是更新后就没了， 我今天也没看到。。。

**Comment by kirk-ye** [comment]
已经恢复。
