### ISSUE TITLE
下载再上传删除图库仍能搜到我的图标

### ISSUE THREAD

**Issue by notelibrary** [thx/iconfont-plus#223]
很高兴见到ICON提供了大量的ICON图标格式，我是昨天看到iconfont.cn的，注册并登录使用了icon，因为第一次玩，所以很好奇的下载了他人的图标，然后上传为自己的图库，（不多）五个，并创建了自己的项目，但是发现在搜索名称的时候能搜到我上传命名的图标，考虑到图标样式重复性，我选择了删除。
可惜，删除了图标仍然能搜索到，这让我感到很困扰。能否提供处理解决的方法

**Comment by purplebamboo** [comment]
目前的逻辑的确是这样的，删除的图标也是可以搜索到的。

图标做的是软删除，其实删除了数据还在的。所以还是可以被检索到的。这个会带来什么困扰吗？

**Comment by notelibrary** [comment]
因为还能搜索到的话，同样的图标可能越来越多，不方便新人查找！
而且，看到法律声明，不排除某人喜欢捣乱，非要说这是盗用谁的的，该怎么怎么的！

**Comment by purplebamboo** [comment]
明白，这个我们评估下，这周做好引擎升级。删除掉的就直接不能搜索。

**Comment by notelibrary** [comment]
好的，谢谢支持！

**Comment by purplebamboo** [comment]
已经修复
