### ISSUE TITLE
无法编辑icon

### ISSUE THREAD

**Issue by LilyLaw** [thx/iconfont-plus#2234]
icon已经上传了，现在需要修改一下 class，发现没法儿修改了，这个功能是被阉割了么？

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/22066881/173311752-9278878b-ccd7-4930-a596-b774f57100fb.png">

**Comment by eastqqq** [comment]
什么时候完全恢复阿

**Comment by kongyijilafumi** [comment]
+1

**Comment by dgf957492430** [comment]
+1，希望能尽快修复

**Comment by vinceok** [comment]
+10086

**Comment by kirk-ye** [comment]
已经恢复。
