### ISSUE TITLE
重复添加同一个icon会修改先前这个icon对应的代码

### ISSUE THREAD

**Issue by ngn999** [thx/iconfont-plus#224]
RT.

项目前期添加了post这个icon, 代码是，`&#xe603;`

项目后面又添加了一次这个icon,可是代码确变成了 `&#xe759;` 也没有提醒已经存在。导致先前的地方显示有问题。

**Comment by purplebamboo** [comment]
亲 这是什么时候发现的？

这个问题后来应该已经修复了呀，就是如果项目里已经有这个icon。  那么你再次添加时，如果形状不一样会修改掉，但是unicode还有font-class会保持不变的。


如果还是有问题，那么你可以把项目地址发给我。再把post这个icon搜藏下，我去尝试下哈。

**Comment by ngn999** [comment]
@purplebamboo  我是2016-11-17重复添加的，可能你们后面修复了。你看看你们的修复时间

**Comment by purplebamboo** [comment]
亲 差不多，查看git 记录是  11-16号修复的，应该是后面几天发布的，发布的日期不记得了。

你现在试下，应该没有这个问题了。
