### ISSUE TITLE
请问生成CDN功能什么时候可以使用[Help]

### ISSUE THREAD

**Issue by convallaria96** [thx/iconfont-plus#2243]
## 相关截图
![image](https://user-images.githubusercontent.com/69450381/173978627-00d9ce3c-e3e4-4482-88fd-e687fefdfb51.png)

**Comment by Mr-Song9898** [comment]
同问

**Comment by BeyondToSky** [comment]
顶起

**Comment by JGHQ39** [comment]
同问，需要加图标，一直提示不可用

**Comment by kirk-ye** [comment]
已经恢复。
