### ISSUE TITLE
我想不通这么一个纯静态的网站，没有什么复杂交互，也没有什么特别难的高科技，请问为啥要维护这么久，到现在了图标还是无法编辑。

### ISSUE THREAD

**Issue by LilyLaw** [thx/iconfont-plus#2248]
阿里要倒闭了吗？？？

**Comment by hjl-1994** [comment]
免费给你们用就不错了

**Comment by tb3706666** [comment]
你不妨也做个这样的网站，给我们免费用用呗

**Comment by evertronicds** [comment]
为什么无法改名啊

**Comment by hjl-1994** [comment]
我哪做的出来&nbsp; 要能做出来不得收费




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月21日(星期二) 下午3:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 我想不通这么一个纯静态的网站，没有什么复杂交互，也没有什么特别难的高科技，请问为啥要维护这么久，到现在了图标还是无法编辑。 (Issue #2248)





 
你不妨也做个这样的网站，给我们免费用用呗
