### ISSUE TITLE
IPHONE 5s ios10.1.1 加载iconfont 浏览器报证书无效

### ISSUE THREAD

**Issue by x-yao** [thx/iconfont-plus#225]
Failed to load resource: 此服务器的证书无效。您可能正在连接到一个伪装成“at.alicdn.com”的服务器，这会威胁到您的机密信息的安全。

页面是https页面

**Comment by purplebamboo** [comment]
有线上demo地址可访问吗？

好像第一次有人反馈哎，cdn是支持https的。我明天找个https的页面试下哈。

**Comment by x-yao** [comment]
@purplebamboo 用safari访问下后莫名其妙好了。。。没问题了。
