### ISSUE TITLE
早知道好几周都恢复不了，还真不如自己写一个，是我肤浅了

### ISSUE THREAD

**Issue by llywuchen** [thx/iconfont-plus#2251]
故意的吧，这么简单的东西

**Comment by llywuchen** [comment]
不需要了，自己动手，丰衣足食。

**Comment by vanswang** [comment]
svgtofont 欢迎你，哈哈

**Comment by zhazhazhu** [comment]
写好了给个地址，果断转了

**Comment by vanswang** [comment]
> 写好了给个地址，果断转了

你可以看看 svgtofont 这个库的使用，我自己在本地搞了一个脚本做转化。有一个问题是这个库只支持纯 path，旋转之类的都不支持。issue：https://github.com/jaywcjlove/svgtofont/issues/162

**Comment by kirk-ye** [comment]
#2317
