### ISSUE TITLE
[Help]什么时候恢复上传图标功能? 2022-06-20

### ISSUE THREAD

**Issue by hwanboo** [thx/iconfont-plus#2252]
## 问题描述
如题,已经过了一个多星期了
## 相关截图
rt

**Comment by Mier11** [comment]
也不见有相关说明信息，等这么久了

**Comment by lichong01** [comment]
+1111111，厉害的程序员都被kc了。说不定要维修几个月呢，坑爹啊。。。。这跟没恢复有什么区别

**Comment by lichong01** [comment]
特地注册个账号来评论

**Comment by Fitz-Wen** [comment]
+1

**Comment by zhao-ping** [comment]
想知道到底出啥事了，这哪里是升级啊，降级还差不多

**Comment by lionnner** [comment]
盲猜程序员在加班处理上传的自动审核功能。。。

**Comment by mujinzjh** [comment]
正在等待上传功能的恢复

**Comment by isooc** [comment]
两个项目都是手动替换双色图标临时处理了Otz

**Comment by aOldMa** [comment]
好像知道那个搞崩的敏感图标长啥样子

**Comment by aOldMa** [comment]
可能官方也不知道啥时候能上吧

**Comment by shengminglei** [comment]
RT

**Comment by fyddaben** [comment]
我简单撸了个，本地部署版本，有兴趣的可以看下 https://github.com/fyddaben/iconfontLocal

**Comment by vinceok** [comment]
+1

**Comment by leehomeok** [comment]
+1

**Comment by jdh8088** [comment]
感觉部门全部拆了 哈哈哈

**Comment by Cool-Star** [comment]
不会被裁了吧？

**Comment by jdh8088** [comment]
最怕这种又没客服又没联系方式的平台了

**Comment by mxp131011** [comment]
恢复了

**Comment by mxp131011** [comment]
上传添加审核

**Comment by hwanboo** [comment]
终于恢复了😭
![image](https://user-images.githubusercontent.com/45534519/177121988-9c4ba11a-fa9a-4fee-a4dc-466831b35779.png)
