### ISSUE TITLE
bug：下载后iconfont.css 类名前有空格

### ISSUE THREAD

**Issue by cipo2008** [thx/iconfont-plus#227]
我的项目，添加了点图标，然后下载。
在压缩包解压后，里面有个iconfont.css
这个css中类名前与css的标识符.直接有空格。

如果数量少，可以手动删除，如果每次对更新的包数量不一定，那么数量一多就繁琐了。

**Comment by purplebamboo** [comment]
亲 我看了下 没有问题啊 没有空格呀。。

是不是特殊场景，你把项目地址发给我看下？我排查下

**Comment by cipo2008** [comment]
//at.alicdn.com/t/font_kewdq01tjv0od2t9.css

**Comment by purplebamboo** [comment]
亲  我看了下  ，你设置前缀的时候  ssy  这个前面有个空格，所以才会这样。

＝ ＝

这个我后面做个兼容，去掉前后的空格，你先把前面的空格删除重新生成样式吧。

**Comment by cipo2008** [comment]
额，不懂什么时候加上的空格   去掉空格就好了
