### ISSUE TITLE
图标库什么时候可以正常生成在线url？

### ISSUE THREAD

**Issue by JGHQ39** [thx/iconfont-plus#2272]
## 问题描述
在线调用iconfont图标，之前可以正常添加，最近突然就不能用了，什么时候可以使用？恢复正常？
## 相关截图[](url)
![截图20220701111453](https://user-images.githubusercontent.com/108505353/176818245-1c6103ad-c6a5-4590-8f51-73647c7885b8.png)

**Comment by kirk-ye** [comment]
#2317
