### ISSUE TITLE
只要把上传功能恢复就行了，我只有这么点要求了，谢谢🙏

### ISSUE THREAD

**Issue by LilyLaw** [thx/iconfont-plus#2275]

**Comment by Janice-qiyue** [comment]
iconfont功能还是很强大的，希望技术小哥哥快马加鞭恢复上传功能呀～～期待

**Comment by mxp131011** [comment]
上传恢复了

**Comment by mxp131011** [comment]
不过要审核，果然是因为政治问题下架的

**Comment by LilyLaw** [comment]
> 上传恢复了

天呐真的恢复了！！！！！

**Comment by lp452254117** [comment]
我还是不能看到入口呢？ 如果是政治问题，那上传功能触犯了什么红线

**Comment by LilyLaw** [comment]
> 我还是不能看到入口呢？ 如果是政治问题，那上传功能触犯了什么红线

网站头部导航右侧，有个上传的 icon，或者你访问这个链接也行：https://www.iconfont.cn/icons/upload

**Comment by lp452254117** [comment]
> > 我还是不能看到入口呢？ 如果是政治问题，那上传功能触犯了什么红线
> 
> 网站头部导航右侧，有个上传的 icon，或者你访问这个链接也行：https://www.iconfont.cn/icons/upload

非常感谢

**Comment by LilyLaw** [comment]
s d f s d f s d f
