### ISSUE TITLE
在线cdn没了？

### ISSUE THREAD

**Issue by YY-hub** [thx/iconfont-plus#2278]
在线生成cdn功能呢？上传icon好了 cdn下架了？

**Comment by xlanghejianfeng** [comment]
同问，cdn这个挺好用的，什么时候能恢复

**Comment by FreshManCode** [comment]
真是无语,提供服务就好好用,大刀阔斧的改功能搞毛线;更新图片之后cdn连接没了?要搞啥?

**Comment by Lucas0819** [comment]
同问，之前功能还有，提示暂时无法使用，今天打开后直接把功能干掉了？

**Comment by yangjunran** [comment]
同问，是还没升级好吗？

**Comment by kkkdb** [comment]
同问，啥时候能开放cdn

**Comment by Hello-job** [comment]
几个亿的大项目都在用这个iconfont呀 什么时候可以恢复呀

**Comment by LeeXhuan** [comment]
在线生成cdn功能呢？上传icon好了 cdn下架了？

**Comment by dongj0316** [comment]
服了

**Comment by kaiaiz** [comment]
同问，好几个项目都在使用在线cdn

**Comment by xiaoyu1035355110** [comment]
啥时候能恢复啊  无语了

**Comment by xlanghejianfeng** [comment]
同问，预计什么时候能恢复cdn呢

**Comment by daoke0818** [comment]
给不出个具体时间给个大概时间，给不出大概时间给个明确答复这个功能还在修吗？

**Comment by xinshou1314** [comment]
mmp 我还以为是我浏览器出问题了，找了半天找不到在线链接。百度里的查看链接按钮都没了

**Comment by xingorg1** [comment]
在线cdn还能用么？antdv都是配套的啊（哭唧唧）

**Comment by wq1308786830** [comment]
+1

**Comment by oozm** [comment]
cdn呢？

**Comment by jdh8088** [comment]
推测可能是部门全部毕业了，回不去了同志们...

**Comment by yangjunran** [comment]
今天看了一下，回来了，又可以愉快的玩耍了。

**Comment by Yilimmilk** [comment]
家人们今天恢复了，可以去看看了

**Comment by kirk-ye** [comment]
#2317
