### ISSUE TITLE
sass编译问题

### ISSUE THREAD

**Issue by zengwenyu** [thx/iconfont-plus#228]
采用Unicode的方式引用字体，出现编译错误 “Invalid US_ASCII character "xEF", sass文件首行加上@charset  "utf-8"; 还是不行，后来发现是font-family行的注释冒号引起的，改成英文冒号即可正常编译

**Comment by purplebamboo** [comment]
明白，我们修复下，把这个冒号去掉。

**Comment by purplebamboo** [comment]
已经修复，感谢反馈
