### ISSUE TITLE
[Help] 在线链接什么时候恢复啊，太影响开发了

### ISSUE THREAD

**Issue by OrangeSAM** [thx/iconfont-plus#2281]
## 问题描述
无法生成项目的在线链接

**Comment by ghost** [comment]
同问

**Comment by zhumengzj** [comment]
同问

**Comment by tanglewang** [comment]
每天都是希望而来失望而归，希望明天能恢复

**Comment by zhumengzj** [comment]
**问题：** 微信小程序引入symbol图标在线链接失败。
**解决方案：**本地下载，导出iconfont.js至项目，本地启动http服务，更改iconfont.json的链接为本地链接，启动npx iconfont-wechat
![image](https://user-images.githubusercontent.com/25915202/177671783-15c4e785-2049-4c86-a99c-da00dc3df05b.png)

**Comment by fjc0k** [comment]
可以使用这个浏览器插件，可以「生成内联 CSS」，不使用 CDN：

https://github.com/fjc0k/Iconfonter

<img width="984" alt="未命名" src="https://user-images.githubusercontent.com/13151189/181173022-669622d7-995f-488e-9859-7513b396a9a4.png">
<img width="613" alt="未命名33" src="https://user-images.githubusercontent.com/13151189/181173031-de25fbfa-15bc-4587-8539-01ec870ffbf6.png">
