### ISSUE TITLE
希望添加修改图标名称的功能

### ISSUE THREAD

**Issue by mindops** [thx/iconfont-plus#2284]
## 需求背景
同一个图标在不同的项目或背景下，含义有可能是不同的，图标修改时，只能修改class，不能修改名称，就导致icon的功能的可读性降低，如果使用“保存为副本”的功能，图标的名字里会自动带上 “_Copy”字样，这样会更加不友好
## 解决方案
所以希望添加修改图标名称的功能，这样能够更好的提示图标的功能或用途。
## 相关截图
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/6076639/177710427-104f7f3a-e055-4eb0-8345-1ec85a45ce85.png">

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/6076639/177710803-9832adfd-a2ac-4908-93bb-6a13a43dc17e.png">

**Comment by yisibl** [comment]
感谢建议，请关注：https://github.com/thx/iconfont-plus/issues/2054
