### ISSUE TITLE
颜色显示不正常

### ISSUE THREAD

**Issue by chm994483868** [thx/iconfont-plus#229]
<img width="1299" alt="2016-12-02 16 03 09" src="https://cloud.githubusercontent.com/assets/16462631/20826880/fed5981c-b8a8-11e6-9f8c-ff4ed03932c9.png">
我输入16进制的色值，然后下载图片，下载完的图片颜色显示一部分不正常

**Comment by purplebamboo** [comment]
麻烦提供下 浏览器版本

然后有问题的icon麻烦 加入搜藏 

再提供下用户名。我去尝试下哈

**Comment by chm994483868** [comment]
<img width="1559" alt="2016-12-02 17 23 44" src="https://cloud.githubusercontent.com/assets/16462631/20828809/2f8141a4-b8b4-11e6-9ff8-01cc154400a2.png">
就是这个在搜索框里面输入“扫描”，横行第8个图标，然后把色值修改为＃C0C0C0,下面是我的浏览器：
<img width="324" alt="2016-12-02 17 26 31" src="https://cloud.githubusercontent.com/assets/16462631/20828881/8b5c397a-b8b4-11e6-8190-bf9ed6ab28b3.png">

**Comment by chm994483868** [comment]
我也是搜着玩的，恰好遇到，也不是想给你们制造麻烦，就是帮助你们完善产品，不好意思

**Comment by purplebamboo** [comment]
safari 的确有问题，亲可以先用 chrome哈。chrome应该没问题。
这个我待会儿修复掉

**Comment by purplebamboo** [comment]
已经修复了哈

**Comment by chm994483868** [comment]
赞👍👍👍
