### ISSUE TITLE
在线功能能不能恢复，官方就不能给个准确的话吗？？？搁着都差不多快一个月了，也没个明确回应？还有人在吗？

### ISSUE THREAD

**Issue by ConstancyMan** [thx/iconfont-plus#2297]
在线功能能不能恢复，官方就不能给个准确的话吗？？？搁着都差不多快一个月了，也没个明确回应？还有人在吗？

**Comment by scfobao** [comment]
me too

**Comment by wangze0618** [comment]
用字节的 IconPark 吧

**Comment by ConstancyMan** [comment]
>字节的在原生微信小程序中无法使用吧？？

**Comment by gtwxxh666** [comment]
同问，急死了！
或者我们用fontawsome吧

**Comment by 1260692465** [comment]
估计倒闭了

**Comment by 9527zhang** [comment]
me too

**Comment by mitchhu** [comment]
官方敢不敢站出来说句话

**Comment by jdh8088** [comment]
推测可能是部门全部毕业了，回不去了同志们...

**Comment by AngoLGW** [comment]
> 用字节的 IconPark 吧
好不好用

**Comment by gtwxxh666** [comment]
> > 用字节的 IconPark 吧
> > 好不好用

好用

**Comment by Harley1874** [comment]
> > > 用字节的 IconPark 吧
> > > 好不好用
> 
> 好用

vue2，不使用js，没办法使用项目图标吧

**Comment by Harley1874** [comment]
> 

ts

**Comment by Harley1874** [comment]
> > > > 用字节的 IconPark 吧
> > > > 好不好用
> > 
> > 
> > 好用
> 
> vue2，不使用js，没办法使用项目图标吧

vue2，不使用ts，没办法使用项目图标吧

**Comment by fjc0k** [comment]
可以使用这个浏览器插件，可以「生成内联 CSS」，不使用 CDN：

https://github.com/fjc0k/Iconfonter

<img width="984" alt="未命名" src="https://user-images.githubusercontent.com/13151189/181173022-669622d7-995f-488e-9859-7513b396a9a4.png">
<img width="613" alt="未命名33" src="https://user-images.githubusercontent.com/13151189/181173031-de25fbfa-15bc-4587-8539-01ec870ffbf6.png">

**Comment by gtwxxh666** [comment]
> 可以使用这个浏览器插件，可以「生成内联 CSS」，不使用 CDN：
> 
> https://github.com/fjc0k/Iconfonter
> 
> <img alt="未命名" width="984" src="https://user-images.githubusercontent.com/13151189/181173022-669622d7-995f-488e-9859-7513b396a9a4.png">
> 
> <img alt="未命名33" width="613" src="https://user-images.githubusercontent.com/13151189/181173031-de25fbfa-15bc-4587-8539-01ec870ffbf6.png">

可以啊

**Comment by kirk-ye** [comment]
#2317
