### ISSUE TITLE
一些有的没的

### ISSUE THREAD

**Issue by Ciel-pton** [thx/iconfont-plus#23]
1. 首页搜索搜索相关用户无结果时，建议提示无相关用户。
   2.个人信息修改完成保存后，建议关闭页面并跳转至进入信息修改前页面。
   3.我的项目页面，左侧切换栏目，无法查看当前在停留栏目。
   4.库侧滑右侧，库图标不醒目。
   5.多个添加至库，全部下载，也不知道下载的是什么鬼。（代码是json文件，SVG、PNG、AI是downloadIcon）
   6.帮助页面，中间线性图标感觉上和网站整体风格不一致，建议调整；最底部多了灰色横条。
   7.当翻页数目在3位时，底色未完整衬托。
   8.http://iconfont.cn/plus/search/index?q=%E4%B8%93%E5%AE%B6       有空图标
   9.整体的图标感觉不是很细致。

以上是作为用户的建议，如有不妥请忽视。

**Comment by Muqing1221** [comment]
哇哦~好细心，谢谢亲的宝贵的建议和耐心细致的提醒
1、2 我们会考虑的
3 没太明白
4 记下了
5 亲说的是全部下载出现在哪里啊
6、7、8、9 我们会检查调整的~

**Comment by Ciel-pton** [comment]
3.http://iconfont.cn/plus/manage/index?manage_type=myprojects&projectId=null左侧栏目点击切换，没有交互效果，不知道自己目前停留在“我发起的项目”，还是”我参与的项目“。
5.将多个图标添加到库里后，从右划出现的库里全部下载的情况下，会出现上述情况。

**Comment by Muqing1221** [comment]
3、了解~恩，我们只会从项目名称上区分是处在哪个项目，暂时没有从项目类别上区分，title色号是有变化的~
5、还是没太明白，哈哈，我会问下我们的技术同学~

PS 好的好的，我反馈给我们的前端同学，谢谢亲的细心Again~

**Comment by Ciel-pton** [comment]
3.“我的项目”下，两个切换时title色号没有变化

关于多色图标如何下载使用，建议最好给个视频的下载操作使用说明，不然用户会以单色图标操作方式进行操作下载，导致全部换色的后果。

**Comment by Muqing1221** [comment]
好的，之后我们会考虑完善一些新功能的使用介绍~~敬请期待~

谢谢亲的建议~again and again~
