### ISSUE TITLE
严格模式下报错

### ISSUE THREAD

**Issue by PanJiaChen** [thx/iconfont-plus#230]
![image](https://cloud.githubusercontent.com/assets/8121621/20856393/ae251942-b948-11e6-9439-61622bf1051d.png)

**Comment by purplebamboo** [comment]
亲 不是太明白 你用的什么测试的

具体场景说下？

**Comment by PanJiaChen** [comment]
当我使用iconfont svg的时候会引入iconfont.js， 它里面用了arguments.callee() 这个方法，但这个方法已被w3c标准警告。并且webpack等类似构建工具构建时都会他头部写入use strict，这样的活iconfont.js文件就会报错了。
所以建议arguments.callee()这个方法去掉，换一种实现方式就可以了
