### ISSUE TITLE
在线链接呢，我特么找了半天

### ISSUE THREAD

**Issue by dlsysoft** [thx/iconfont-plus#2302]
在线链接呢，我特么找了半天

**Comment by yangtao5201314** [comment]
太他妈坑了

**Comment by jjd1997** [comment]
确实，什么情况啊

**Comment by TiaNex-Com** [comment]
是他们坑，不知道怎么想的，只有图标，找作者的套图找不到，，，，

**Comment by AngoLGW** [comment]
我特么也找了半天，来git一看原地爆炸了

**Comment by zfcgithub** [comment]
找半天了，以为改版了，看代码里查看的那个写着deleted

**Comment by xfyanmeng** [comment]
我还各种刷新，CTRL+F5刷，退出重新登。进来一看你们也找不到，顿时心里舒坦了，哈哈

**Comment by hehekeji** [comment]
请问你们找生成的链接了吗

**Comment by dd442394485** [comment]
我还以为，是我的问题，原来大家都找不到

**Comment by lajizaishi** [comment]
他们提示已经更新完成，在线链接以后也没有了？？？

**Comment by aloniacode** [comment]
iconfont到底出啥事了

**Comment by aloniacode** [comment]
把项目下载到本地，再把目录里的iconfont.js放到自己云端上就能用了。

**Comment by 774265230** [comment]
> 把项目下载到本地，再把目录里的iconfont.js放到自己云端上就能用了。

老哥是怎么做到把项目下载到本地的啊，我看他不开源啊。

**Comment by aloniacode** [comment]
> > 把项目下载到本地，再把目录里的iconfont.js放到自己云端上就能用了。
> 
> 老哥是怎么做到把项目下载到本地的啊，我看他不开源啊。

是你在iconfont创建的项目，里面有个下载

**Comment by blusewang** [comment]
我去！我也找了半天！这么说就是没了呗！
哎！

**Comment by JR-wfr** [comment]
借一位评论区的话  看到你们也没有 我就放心了

**Comment by JR-wfr** [comment]
> > > 把项目下载到本地，再把目录里的icon.js放在自己驱动上用的字体。
> > 
> > 
> > 老哥是怎么把项目下载到本地的啊，我看他不开源啊。
> 
> 是你在字体创建的项目，里面的图标下载

再等等吧 他们好像还在修复  修复不好 就只能用别的了

**Comment by jjd1997** [comment]
我直接换字节的icon或者font awesome

**Comment by Hin7inn** [comment]
我真的吐了 在线链接没了debug半天

**Comment by blusewang** [comment]
@zyyjjd 感谢分享！

**Comment by fjc0k** [comment]
可以使用这个浏览器插件，可以「生成内联 CSS」，不使用 CDN：

https://github.com/fjc0k/Iconfonter

<img width="984" alt="未命名" src="https://user-images.githubusercontent.com/13151189/181173022-669622d7-995f-488e-9859-7513b396a9a4.png">
<img width="613" alt="未命名33" src="https://user-images.githubusercontent.com/13151189/181173031-de25fbfa-15bc-4587-8539-01ec870ffbf6.png">

**Comment by kirk-ye** [comment]
#2317
