### ISSUE TITLE
其实只是想问一下去除上传icon颜色这个功能是怎么实现的，悄悄的问一问

### ISSUE THREAD

**Issue by mfts2048** [thx/iconfont-plus#2303]
其实只是想问一下去除上传icon颜色这个功能是怎么实现的，悄悄的问一问

**Comment by yxswy** [comment]
其实只是想问一下去除上传icon颜色这个功能是怎么实现的，悄悄的问一问

**Comment by yxswy** [comment]
其实只是想问一下去除上传icon颜色这个功能是怎么实现的，悄悄的问一问

**Comment by yisibl** [comment]
就是把 SVG 中的 fill 等属性去掉。
