### ISSUE TITLE
[Help]我想请问一下，在线链接怎么没有了，那我微信小程序就是使用的在线链接引入的，现在没有，我该怎么办才好呢

### ISSUE THREAD

**Issue by 2518450374** [thx/iconfont-plus#2310]

**Comment by ceu** [comment]
同问, symbol  在线链接没有了

**Comment by YY-hub** [comment]
先下载到本地用吧 就是比较麻烦一点 没有在线链接方便

**Comment by lnsslimbo** [comment]
对，我也想问这个问题

**Comment by somanwai08** [comment]
> 先下载到本地用吧 就是比较麻烦一点 没有在线链接方便
如何下載到本地使用？

**Comment by heiyun** [comment]
用字节的iconpark吧

**Comment by 2518450374** [comment]
那也可以提前说一声吧，或者是官方发动态了，我不知道...如果是一声不吭的就去掉了这个功能，那真的有点过分了，毕竟我们也还在呢..

**Comment by foreverzhuo** [comment]
估计是要收费了吧。。哈哈

**Comment by fjc0k** [comment]
可以使用这个浏览器插件，可以「生成内联 CSS」，不使用 CDN：

https://github.com/fjc0k/Iconfonter

<img width="984" alt="未命名" src="https://user-images.githubusercontent.com/13151189/181173022-669622d7-995f-488e-9859-7513b396a9a4.png">
<img width="613" alt="未命名33" src="https://user-images.githubusercontent.com/13151189/181173031-de25fbfa-15bc-4587-8539-01ec870ffbf6.png">

**Comment by heiyun** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
