### ISSUE TITLE
上传图标显示不完整

### ISSUE THREAD

**Issue by yjq-717** [thx/iconfont-plus#2312]
图标的样式
![7595f589-803a-40e4-829b-cebde691f95e](https://user-images.githubusercontent.com/53717902/180709693-93ec9c49-4f0f-4df4-b02b-50542c58e5be.png)

上传后的样式
![企业微信截图_16587291332756](https://user-images.githubusercontent.com/53717902/180709680-a651ffbb-658a-4426-b481-b647bca2a12a.png)

**Comment by jdh8088** [comment]
先扩展一下试一试，或者扩展好后有合并在试一下

**Comment by yjq-717** [comment]
> 先扩展试一下，或者扩展好后有合并在一下

已解决 感谢
