### ISSUE TITLE
无法上传图标了是什么原因？是系统bug吗

### ISSUE THREAD

**Issue by 3212298839** [thx/iconfont-plus#2313]
## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by wangziqin123** [comment]
同问

**Comment by 3212298839** [comment]
> 同问

选择是修复好了，之前有一段时间不行

**Comment by jdh8088** [comment]
昨天试了一下是可以的哦，拖进去点提交等待5分钟左右的待审核在二次提交就可以了，不像以前提交就完成，不知道有没有帮助~
