### ISSUE TITLE
在线链接替代方案 🔥

### ISSUE THREAD

**Issue by fjc0k** [thx/iconfont-plus#2314]
可以使用这个浏览器插件，可以「生成内联 CSS」，不使用 CDN：

https://github.com/fjc0k/Iconfonter

<img width="984" alt="未命名" src="https://user-images.githubusercontent.com/13151189/181173022-669622d7-995f-488e-9859-7513b396a9a4.png">
<img width="613" alt="未命名33" src="https://user-images.githubusercontent.com/13151189/181173031-de25fbfa-15bc-4587-8539-01ec870ffbf6.png">

**Comment by Mr-xue** [comment]
这跟下载到本地引入感觉没太大区别啊

**Comment by fjc0k** [comment]
> 这跟下载到本地引入感觉没太大区别啊

@Mr-xue 图标变动频繁的时候下载引入会让人很崩溃的。。。

**Comment by gtwxxh666** [comment]
怎么用在网站啊，用什么html标签

**Comment by kirk-ye** [comment]
#2317
