### ISSUE TITLE
svg 文件上传报 500 错误

### ISSUE THREAD

**Issue by raisezhang** [thx/iconfont-plus#232]
@Muqing1221   今天发现 svg 文件上传报 500 错误

问题描述：

   今天设计的 icon 上传的时候不成功，接口返回的内容是 500 错误 ```{"code":500,"message":"上传失败"}``` ，一开始以为是文件格式啥的有问题，后来把之前传成功过的重新下载下来重新上传，发现仍然上传不了！

上传的文件如下：
[礼盒.svg.zip](https://github.com/thx/iconfont-plus/files/628827/svg.zip)

帐号：牙仔小朋友     

辛苦啦~

**Comment by purplebamboo** [comment]
亲  你好，你这个svg有点问题哈。

我看了下  你应该在一个画布里 把所有的图标都放上去了。然后把其他图标都隐藏了而已。
近期平台发现很多人上传的svg太大，导致解析太慢浪费系统资源，所以对上传的svg大小有了限制，目前是限制的20k哈。

平台的解析其实兼容性比较强大，所以这种也能兼容，但是还是不建议这么用呢。

所以麻烦亲  把其他隐藏的也删除掉再上传哈。

**Comment by raisezhang** [comment]
恩  明白了， 现有俩个问题：


1、上传失败提示问题，可以把具体业务报错的详细信息反馈到页面中；
2、设计湿吐槽如果单个保存的话操作比较繁琐，针对这个问题，有几点建议：

      1、你说的最近很多人都上传的是隐藏的图层形式，说明这个是有需求的，而且这个需求还不小；
      2、能否通过技术手段判断是否是隐藏的图层。如果可以的话直接干掉，需要在用户上传时需给出警告，隐藏的会被干掉之类
      3、针对一些项目有很多 icon 的情况，是否可以考虑通过标准化画布的形式，仅仅上传一次 icon 集合的文件，通过技术手段解析，解析后再修改 icon 名称。中间估计会有一些冲突 icon 的处理 .... 

辛苦 ~    多谢了~

**Comment by purplebamboo** [comment]
1. 提示问题，这个我们会再优化下，因为有些敏感信息不能透出到前台。

2. 这个隐藏图层需求其实不高，我说的是用户上传比较大的svg哈，比如有人上传自画像的（＝ ＝），至于一个个图标上传，这个设计师会觉得繁琐吗？因为你们那边就应该是一个个图标上传的呀，你们留存的也应该是一个个的图标源文件才对哎，自动处理可能有点不实际，说不定还会带来新的问题。

另外我理解，你们隐藏其他小icon，跟把这个icon单独弄个画布导出来，这个成本没多少区别呀？

**Comment by raisezhang** [comment]
设计师目前是在一个 PSD 文件里面

多谢啦~
