### ISSUE TITLE
修改个人信息报错

### ISSUE THREAD

**Issue by zexi-design** [thx/iconfont-plus#2325]
<img width="818" alt="image" src="https://user-images.githubusercontent.com/26563109/184145587-0106de10-1cc7-4458-8383-158170de6d5f.png">

**Comment by zexi-design** [comment]
期望各位老板看一下，为啥修改个人信息还会报错呢，这个算是流程阻塞类的了吧

**Comment by jdh8088** [comment]
以为这个模块他们平台还没有开放，其他用户根本看不到你个人信息，所以目前修改不修改都不重要了哈哈哈~

**Comment by kirk-ye** [comment]
#2343
