### ISSUE TITLE
网站首页搜索框宽度问题

### ISSUE THREAD

**Issue by ChadStone** [thx/iconfont-plus#2326]
## 问题描述
网站首页搜索框宽度超出，点击右侧空白区仍可进行搜索
## 截图

![QQ20220812-114909](https://user-images.githubusercontent.com/24889036/184290126-b2c59cef-9c73-47bd-9518-dd0fd6e23ec9.png)
## 重现步骤
1. 打开：网站首页
2. 点击：搜索框右侧区域
3. 出现：点击错误区域仍可进行搜索

## 期望结果
点击输入框区域才可进行搜索
## 相关信息（重要）
- 发生问题的 URL：https://www.iconfont.cn/?spm=a313x.7781069.1998910419.d4d0a486a
- iconfont 的用户昵称：MYJ2014围脖
- iconfont 项目 ID：无

## 相关文件（重要）

```svg
无
```

## 平台/浏览器版本（重要）
- 操作系统及版本：macOS 12.5

- 浏览器名称及版本：safari 15.6 (17613.3.9.1.5)

**Comment by oldmanvv** [comment]
已修复，感谢反馈
