### ISSUE TITLE
下载按钮，新版页面对笔记本用户体验很差

### ISSUE THREAD

**Issue by Hulkchan** [thx/iconfont-plus#233]
![qq 20161204190817](https://cloud.githubusercontent.com/assets/19217702/20865731/415c5240-ba55-11e6-93d6-f9adb8ab06a0.png)
![qq 20161204190837](https://cloud.githubusercontent.com/assets/19217702/20865733/4c9b967a-ba55-11e6-8523-f66abf091ed3.png)
如图所示，下载的按钮显示不全，可否让前端工程师稍作调整。一直使用贵网站提供的图标，拜谢！

**Comment by purplebamboo** [comment]
亲  麻烦提供下你的   电脑分辨率。

是windows下面的chrome 吗？

**Comment by Hulkchan** [comment]
对的，我公司的电脑是15.6 1366*768，家里是13.3的sony S13忘记分辨率了，截图是13.3的，公司的电脑个别按钮会看不到………原来是垃圾QQ浏览器的原因，chrome只有下载代码那个按钮是半个
Chrome


QQ浏览器






在 2016-12-05 13:13:39，"purplebamboo" <notifications@github.com> 写道：


亲 麻烦提供下你的 电脑分辨率。

是windows下面的chrome 吗？

**Comment by purplebamboo** [comment]
亲  你使用的是  windows吧？
我估计是你下面的  系统操作栏挡住了。我们的操作区会放在又下角。

现在你这个操作栏应该挡住了  浏览器的最下面的窗口。


参考下这个？ http://jingyan.baidu.com/article/03b2f78c1415d55ea237aed0.html

不过我这里针对  下载代码那块 还是做个兼容吧，往上提一点。

**Comment by Hulkchan** [comment]
嗯嗯，😂正在坑中爬努力攒钱买块显示器的菜鸟发来感谢


发自网易邮箱大师
在2016年12月06日 20:56，purplebamboo 写道:

亲 你使用的是 windows吧？
我估计是你下面的 系统操作栏挡住了。我们的操作区会放在又下角。

现在你这个操作栏应该挡住了 浏览器的最下面的窗口。

参考下这个？ http://jingyan.baidu.com/article/03b2f78c1415d55ea237aed0.html

不过我这里针对 下载代码那块 还是做个兼容吧，往上提一点。

**Comment by ishowman** [comment]
@Hulkchan 请确定你的设备分辨率，及浏览器是否缩放超过100%？
