### ISSUE TITLE
重新审核过的图标库为什么不在用户端显示？

### ISSUE THREAD

**Issue by jdh8088** [thx/iconfont-plus#2333]
## 截图

![image](https://user-images.githubusercontent.com/68884174/184611518-46b9012b-4eaa-49a0-a3e5-41c000e72ac1.png)
![image](https://user-images.githubusercontent.com/68884174/184611757-cd9ae3c9-7374-4098-a8d5-e65c5e5ddaf4.png)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by kirk-ye** [comment]
#2374
