### ISSUE TITLE
重新审核过的图标库不在用户端显示？

### ISSUE THREAD

**Issue by jdh8088** [thx/iconfont-plus#2338]
## 截图

![QQ截图20220817110819](https://user-images.githubusercontent.com/68884174/185026160-c1680417-5912-47c4-bdb4-be5656833b53.jpg)
![64030c7404b4c7d554d7c7df2c2ca54](https://user-images.githubusercontent.com/68884174/185026206-7250f52f-8666-47eb-90c8-23ade9c54d26.jpg)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by kirk-ye** [comment]
#2374
