### ISSUE TITLE
遨游4的浏览器，页面疯狂抽风抖动，上周五用还好好的，这两天都更新啥了啊！

### ISSUE THREAD

**Issue by sgttyyd** [thx/iconfont-plus#234]
遨游4的浏览器，页面疯狂抽风抖动，上周五用还好好的，这两天都更新啥了啊！

**Comment by purplebamboo** [comment]
木有改啥大的东西呀。

＝ ＝ 亲  建议用chrome来访问呢。

遨游这些浏览器我们实在木有太多精力去兼容呀。
