### ISSUE TITLE
取消收藏没有用

### ISSUE THREAD

**Issue by weishiyangweisy** [thx/iconfont-plus#2342]
## 问题描述
取消收藏之后刷新页面还是收藏状态
## 截图

![image](https://user-images.githubusercontent.com/108315295/185525255-91940b61-e52c-4ee6-ac6a-60575d9a1fb8.png)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by kirk-ye** [comment]
谢反馈，已解决！
