### ISSUE TITLE
审核真的很难用，说的5-10分种，半个月都没结果

### ISSUE THREAD

**Issue by FN-G** [thx/iconfont-plus#2349]

**Comment by jdh8088** [comment]
飘过——我们可以正常上传的啊：你可能没有提交成功吧?先拖入图标然后点击上传图标按钮，点击过后平台会提示等待审核5分钟（左右），此刻就等5-8分钟左右再次点击上传图标按钮，就完成上传了    没有遇到半个月的这种吧？

**Comment by LilyLaw** [comment]
你需要再点一次提交

**Comment by jdh8088** [comment]
上传好点击提交（这个是第一次提交）点击好后提示等待审核大概5分钟左右（这个是第一次审核），5分钟到了再一次点击提交（这是第二次提交）这时候就可以完成提交了（也不知道哪个神人产品经理想出来的操作模式）。上传完成后才到个人中心图标处去创建库，填写库名称，添加库图标然后在保存提交，审核通过就可以了

**Comment by fengchuanBIG** [comment]
审核机制真的恶心  不如直接开源 我们自己本地化部署

**Comment by yisibl** [comment]
感谢反馈，此前已经提供单独的审核列表页面
https://www.iconfont.cn/manage/index?
spm=a313x.home_index.i3.17.58a33a81IgjkVU&manage_type=myicons&icontype=auditing
