### ISSUE TITLE
加入某些图表后，图标高度有问题且无法调试啊

### ISSUE THREAD

**Issue by jerryyan1990** [thx/iconfont-plus#235]
## 正常情况
![nomarl](https://cloud.githubusercontent.com/assets/12929365/20872972/0bf69226-bade-11e6-8ca3-3ae7e17eb8f9.png)
## 加入某些图标后
![qq 20161205112224](https://cloud.githubusercontent.com/assets/12929365/20872987/24957130-bade-11e6-839d-18d0d2b59f90.png)

**Comment by purplebamboo** [comment]
嗯  这些图标是有问题的，建议删除这些图标哈。

具体的原因可以在这里找到答案。

http://www.iconfont.cn/plus/help/article_detail?article_id=1

页面里面搜索 '单个icon撑开的问题'
