### ISSUE TITLE
下载资源后图标变了

### ISSUE THREAD

**Issue by kyrieLiu** [thx/iconfont-plus#2350]
## 问题描述
下载后运行html文件,图标变了,在网站上预览是微笑图标,下载到本地后变成加号了
## 截图
![图片](https://user-images.githubusercontent.com/16189974/186355280-5a6fc0f6-328d-4e23-af06-ab3500d46111.png)
<img width="1104" alt="图片" src="https://user-images.githubusercontent.com/16189974/186355364-e075e58b-3d87-4db3-b494-38648c4124de.png">

## 重现步骤
1. 打开：https://www.iconfont.cn/manage/index?spm=a313x.7781069.1998910419.23&manage_type=myprojects&projectId=3606079
2. 点击：点击下载至本地
3. 出现：微笑图标变成加号了

## 期望结果
期望图标正常加载

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：我的小名叫小锋
- iconfont 项目 ID：
3606079

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：
macOS 11.4
- 浏览器名称及版本：
Google Chrome 104.0.5112.101

**Comment by kirk-ye** [comment]
对有问题icon 尝试改一下 Unicode 值（就是换另一个值）。

**Comment by oldmanvv** [comment]
已将项目中重复的icon标红显示，逐一修改即可
