### ISSUE TITLE
调整后重新审核的公开库其他用户无法看到能否查看一下原因呢？

### ISSUE THREAD

**Issue by jdh8088** [thx/iconfont-plus#2353]
## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by kirk-ye** [comment]
如果是审核通过的公开库，大家都能看得到的。
你可以把公开库id提供一下。

**Comment by jdh8088** [comment]
应该刚修复了，看到最近提交的一个出来了，以前重提都是公开库的但是审核后也看不见，在提交几个测试看看~

**Comment by kirk-ye** [comment]
#2374
