### ISSUE TITLE
账户设置修改个人信息提示昵称已被注册

### ISSUE THREAD

**Issue by xiemin2161** [thx/iconfont-plus#2356]
在账户设置页面修改个人信息，比如修改职业（没有修改昵称），点击保存直接提示"该昵称已被注册，请修改"，问题是我并没有修改昵称，用的是我自己的昵称，我是要修改昵称以外的其他信息，这就导致每次要修改信息，就要变更一次昵称，且不能重复

**Comment by kirk-ye** [comment]
已经修复！
