### ISSUE TITLE
Sketch导出的svg图标，上传上去是个色块

### ISSUE THREAD

**Issue by celementj** [thx/iconfont-plus#2359]
Sketch导出的svg图标，上传上去是个色块
把颜色去掉之后上传是个空的，填充上颜色之后也啥都 没有

**Comment by annieyayaya** [comment]
同样的问题，把图标倒入到AI中再导出为svg ，上传后同样是色块，很苦恼啊

> Sketch导出的svg图标，上传上去是个色块 把颜色去掉之后上传是个空的，填充上颜色之后也啥都 没有

**Comment by aCHEN-design** [comment]
> 同样的问题，把图标倒入到AI中再导出为svg ，上传后同样是色块，很苦恼啊
> 
> > Sketch导出的svg图标，上传上去是个色块 把颜色去掉之后上传是个空的，填充上颜色之后也啥都 没有

用旧版sketch可以解决，我92和你们问题一样，用89可以正常上传。。估计需要iconfont适配一下新版sketch

**Comment by wadewy** [comment]
> > 同样的问题，把图标倒入到AI中再导出为svg ，上传后同样是色块，很苦恼啊
> > > Sketch导出的svg图标，上传上去是个色块 把颜色去掉之后上传是个空的，填充上颜色之后也啥都 没有
> 
> 用旧版sketch可以解决，我92和你们问题一样，用89可以正常上传。。估计需要iconfont适配一下新版sketch

用93版本吧

**Comment by yisibl** [comment]
sketch 旧版本有问题，请升级到最新版试试。
