### ISSUE TITLE
图标库添加

### ISSUE THREAD

**Issue by BruceJson** [thx/iconfont-plus#236]
添加了一个图标库，现在不知道有没有成功，什么提示都没有，原来还有个库在那里，点开的话什么都没有，但至少知道在审核，现在什么都没有，也没有提示，难道是不能添加图标库了吗？？？

**Comment by purplebamboo** [comment]
亲  是这样的，可以看到的，在我的图标库点击编辑可以看到目前的审核进度。

老版本在详情页我们也会加，评估了后去掉了，希望在我的图标库那边统一管理。

不过针对亲的问题，我们可以优化下。在我的图标库列表页面，给每个图标库打个标展示目前的进度，应该会好点。这个我明天去加一下哈。

**Comment by BruceJson** [comment]
不是审核进度，是新建图标库
新建图标库选择了最新上传的图标，提交之后，我的图标库并没有新的图标库，原来6个，提交之后，还是6个；操作了2次都没有。
我记得之前提交新的图标库的时候，比如我原来有5个，新建一个之后就是6个，只是第6个是空的，在编辑页面可以看到是等待审核的。但是今天操作，什么都没有，也没有待审核图标

**Comment by purplebamboo** [comment]
亲  提供下你的用户名？ 我去查看下。

**Comment by BruceJson** [comment]
坏人一枚

**Comment by purplebamboo** [comment]
亲  这是一个bug。  sorry，感谢反馈，你再看下应该已经恢复了（可能会有多个重复的，因为亲应该新建了好几次）。

非常非常非常，感谢亲的反馈。
