### ISSUE TITLE
GET https://registry.npmjs.org/iconfont-wechat - Not found

### ISSUE THREAD

**Issue by ypFish** [thx/iconfont-plus#2363]
使用 [mini-program-iconfont-cli](https://github.com/iconfont-cli/mini-program-iconfont-cli) 开发微信小程序，生成图标组件的时候需要执行： npx iconfont-wechat，但是 iconfont-wechat 找不到了，报：
npm ERR! 404 Not Found - GET https://registry.npmjs.org/iconfont-wechat - Not found

想问问官方还维护吗？大家有没有替代方案

**Comment by cyjake** [comment]
这个不是官方工具，iconfont-cli 也不是官方在 Github 的 org，劳烦自行提交 issue 给 [mini-program-iconfont-cli](https://github.com/iconfont-cli/mini-program-iconfont-cli) 哈
