### ISSUE TITLE
提交后等审核，几分钟后再点提交，也太傻逼了，这是谁想出来的交互。就不能给个地方看审核状态吗。通过后自动入库。

### ISSUE THREAD

**Issue by molin0** [thx/iconfont-plus#2367]
## 需求背景
提交后等审核，几分钟后再点提交，也太傻逼了，这是谁想出来的交互。
## 解决方案
就不能给个地方看审核状态吗。通过后自动入库

**Comment by yisibl** [comment]
感谢反馈，此前已经添加审核列表页面：
https://www.iconfont.cn/manage/index?spm=a313x.home_index.i3.17.58a33a81IgjkVU&manage_type=myicons&icontype=auditing
