### ISSUE TITLE
是本地上传svg 到阿里图标库 生成的图标跟本地的svg的内容不一样

### ISSUE THREAD

**Issue by sisiAHAH** [thx/iconfont-plus#2368]
我上传本地的svg到阿里图标库中 生成的图标跟我本地的svg完全不一样
这是我本地的svg![Slice 14](https://user-images.githubusercontent.com/101077578/189062494-337a4600-5478-443d-a914-d096c564e2b9.svg) 
生成的![3906f1567bd5257e433ffa0c9e2c699](https://user-images.githubusercontent.com/101077578/189062530-78773ec4-be0e-4fc1-bffd-5b67152a1e24.jpg)

**Comment by kirk-ye** [comment]
![image](https://user-images.githubusercontent.com/10226/189796381-b4ab9f26-0464-4323-b221-37fb163c8742.png)
