### ISSUE TITLE
调整过的图标重新审核过后自己能看到其他用户还是不能看到

### ISSUE THREAD

**Issue by jdh8088** [thx/iconfont-plus#2374]
## 截图

![image](https://user-images.githubusercontent.com/68884174/190290043-82b9fdeb-8f9e-48dc-ba8c-cc6d538e763c.png)
![image](https://user-images.githubusercontent.com/68884174/190290093-1f339585-01f6-4f65-979c-0c1390bcf3a1.png)
![image](https://user-images.githubusercontent.com/68884174/190290305-b316fe94-a344-40a0-b730-738d67e9590f.png)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by jdh8088** [comment]
随便例举一套，你们去看原因吧，https://www.iconfont.cn/collections/detail?cid=20628

**Comment by jdh8088** [comment]
有平台人员在吗？

**Comment by kirk-ye** [comment]
@jdh8088   
1. 你的问题应该是审核通过的库自己又重新设置成私有了，这样自己能看到，别人是看不到的。 你需要把库再改成公开。
2. 上面的 https://www.iconfont.cn/collections/detail?cid=20628 库 应该是你自己做了删除图标库操作，导致图标库被删除了。
3. 如果你想得到快速的解答，你可以加入钉钉答疑群：![image](https://user-images.githubusercontent.com/10226/194792366-9a01d47d-a6f4-47bb-98d1-d75c47974b47.png)
