### ISSUE TITLE
<有些点进去  提示    找不到的图标能不能下掉 怪浪费时间的>

### ISSUE THREAD

**Issue by yuranjun3** [thx/iconfont-plus#2375]
## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by kirk-ye** [comment]
会有另一种用法。
