### ISSUE TITLE
我收藏的图标呢

### ISSUE THREAD

**Issue by ghost** [thx/iconfont-plus#2376]
## 需求背景
**我收藏的图标在哪看啊，我光收藏了，看不了，你出收藏功能有啥用，多此一举！！！**
## 解决方案
加个个人主页查看收藏的图标

**Comment by culiuo4** [comment]
顶部导航-资源管理-我的收藏

**Comment by kirk-ye** [comment]
![image](https://user-images.githubusercontent.com/10226/194792958-79c0a8ee-ae7f-4657-8534-02c94aa543c3.png)
