### ISSUE TITLE
建议搜索后的图标列表可以看到每个图标所属的图标库

### ISSUE THREAD

**Issue by Trinea** [thx/iconfont-plus#238]
目前搜索后的图标仅可以加入购物车、收藏及下载，建议加个跳转到所属图标库的链接，因为一般都是希望使用同样风格的图标，这个功能能快速找到类似风格图标一起使用。

**Comment by purplebamboo** [comment]
其实是有的哈，目前入口有点深。

你点击下载，如果这个图标是属于某个库的。在下载的最上面一排 是有这些图标库的链接的哈。

**Comment by Trinea** [comment]
看到了，谢谢，网站超棒。

貌似没找到关注某人以及收藏某个图标库的方式

**Comment by Muqing1221** [comment]
亲提到的功能现在还没有哦，目前的关注/收藏只能针对单个icon，之后会慢慢完善起来哒~
