### ISSUE TITLE
导航栏搜索问题

### ISSUE THREAD

**Issue by DongAndDi** [thx/iconfont-plus#2389]
## 截图

![image](https://user-images.githubusercontent.com/51230101/195495527-ab33f36b-fea0-46c3-a9f9-f647ba6f080c.png)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
感谢反馈，已修复。
