### ISSUE TITLE
下载图标的时候点击 ai 格式下载的是 svg格式的

### ISSUE THREAD

**Issue by ruodi** [thx/iconfont-plus#239]
下载图标的时候点击 ai 格式下载的是 svg格式的

**Comment by purplebamboo** [comment]
目前  eps下载对多色的支持还有点问题啊，我们还在想办法解决中。

svg本身就是矢量格式的，可以直接使用ai打开的哈。

我们目前已经在着手优化这些小点，欢迎关注：


https://github.com/thx/iconfont-plus/issues/139
