### ISSUE TITLE
font-class的方式有问题

### ISSUE THREAD

**Issue by OliveKong** [thx/iconfont-plus#24]
unicode和symbol的方式都成功引入了小图标，可是font-class的引入方式却总是不能成功

**Comment by purplebamboo** [comment]
项目里可以下载代码到本地哈，看下我们的demo，里面有详细步骤

**Comment by OliveKong** [comment]
我看了使用帮助了，知道了可以下载到本地了，下载的是.json的格式，改成.zip后就可以试用了。现在我说的是在线引入.css的问题哦，引用你们的在线css地址，出不来小图标哦

**Comment by purplebamboo** [comment]
嗯 是有问题  ，稍后就修复。
