### ISSUE TITLE
建立压缩下字体图标的大小

### ISSUE THREAD

**Issue by inier** [thx/iconfont-plus#240]
同样的图标，原来的版本和现在的版本体积相差近1倍。不知道什么原因产生的，是因为多色图标机制么？但我只使用了传统的单色图标啊。这个问题有点严重，差不多一套图标下来差值就上百k了，望重视。

**Comment by purplebamboo** [comment]
你好 亲，我试了下。没有区别呀。新旧版本目前使用的是同一套字体生成逻辑，大小按理都是一样的。就算因为使用的第三方的库的版本问题，也不会相差1倍呀。



![wangwang20161206103455](https://cloud.githubusercontent.com/assets/1409611/20910948/a846cc06-bb9f-11e6-9d15-b15c2330232c.png)
![wangwang20161206103439](https://cloud.githubusercontent.com/assets/1409611/20910947/a8463e4e-bb9f-11e6-802f-6d65afd67c06.png)

可以看到两个是差不多的呀。


是不是因为特定图标的差异？

要不 亲你把你项目地址发给我看下  我去试试看。
