### ISSUE TITLE
按照说明来制作的图标  审核被拒绝的时候可以给出拒绝理由的话，上传者至少可以知道，怎么修改，下次上传或者制作的时候应该注意什么。

### ISSUE THREAD

**Issue by BruceJson** [thx/iconfont-plus#241]

**Comment by purplebamboo** [comment]
其实是有拒绝信息的，点击编辑图标库，可以在审核拒绝那边 看到拒绝信息。

这个目前的确不好，我们考虑下  做的明显点。

**Comment by Muqing1221** [comment]
抱歉给亲带来的困扰，之后我们会在这方面加强说明的；一方面，对于拒绝原因会示意的更明显；另一方面，也会有相应的文章说明来解释怎样的一组图标更适合成为图标库~
谢谢建议
我能想象，逼一个视觉设计师来注册Github，然后给我们反馈信息，这是有多死忠，一万点感恩~~
