### ISSUE TITLE
字体库能否加入得意黑

### ISSUE THREAD

**Issue by DiamondHunters** [thx/iconfont-plus#2414]
## 需求背景
[得意黑](https://github.com/atelier-anchor/smiley-sans) 是一款新的开源字体，希望能够添加到[字体库](https://www.iconfont.cn/fonts/index) 板块中

**Comment by yisibl** [comment]
感谢您对 iconfont 字体库的关注和厚爱，我已经在得意黑的官方仓库发出了许可请求：https://github.com/atelier-anchor/smiley-sans/discussions/109
