### ISSUE TITLE
【我的图标】无法对添加的图标进行“删除或撤销”操作

### ISSUE THREAD

**Issue by asxz2008cool** [thx/iconfont-plus#2415]
"我的图标库"操作体验特别不好！
1、无法对添加的图标进行“删除或撤销”所见即所得操作，当添加大量图标后，若有重复时，想“删除或撤销”操作，非常困难！能否和【我的项目】一样的操作管理！
2、对于创作者来说，需要可以修改名称、去色、调整图摆放位置等操作！

**Comment by asxz2008cool** [comment]
> "我的图标库"无法对添加的图标进行“删除或撤销”所见即所得操作，当添加大量图标后，若有重复时，想“删除或撤销”操作，非常困难！能否和【我的项目】一样的操作管理！

**Comment by asxz2008cool** [comment]
如何将自己上传的图标，添加到【我的图标库】？如何管理【我的图标库】？

**Comment by kirk-ye** [comment]
可以在 “我的图标库” 中进行创建一个新的图标库进行管理。
https://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.26&helptype=about
