### ISSUE TITLE
[Help] 上传的3D素材没有展示

### ISSUE THREAD

**Issue by git-lt** [thx/iconfont-plus#2418]
## 问题描述
上传的3D素材没有展示
## 相关截图
![image](https://user-images.githubusercontent.com/8443758/205653363-0dc976d3-ccf0-4367-9ee7-a0b80771f8c5.png)
1. 素材库页找不到
2. 之前上传了6个，后面再上传还提示不满6不让上传
3.  无法按素材单个设置是否授权，只能整体设置授权与否

**Comment by kirk-ye** [comment]
已经解决。

**Comment by git-lt** [comment]
谢谢，还有一个问题，无法重命名已经上传的素材 @kirk-ye

**Comment by git-lt** [comment]
@kirk-ye 我设置了一下封面，提交之后，素材库里又不显示了
