### ISSUE TITLE
[Help]平台审核有漏洞，容许某些人打着原创的名义，上传并贩卖盗版资源

### ISSUE THREAD

**Issue by sanshui3** [thx/iconfont-plus#2419]
## <img width="1278" alt="image" src="https://user-images.githubusercontent.com/119911667/205806204-e9b08943-54a5-4a8d-bffa-b2ca0b76b84d.png">
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/119911667/205806212-2e77dbc4-4fd2-4536-89ee-3ecfa4cf68e4.png">

部分素材原始出处：https://www.freepik.com/free-vector/tiny-people-sitting-standing-near-giant-faq_9650829.htm#query=q%20amp%20a&position=1&from_view=search&track=sph

<img width="1234" alt="image" src="https://user-images.githubusercontent.com/119911667/205806452-687a85c6-b61b-4860-a520-b7fa995f1506.png">

<img width="731" alt="image" src="https://user-images.githubusercontent.com/119911667/205807021-d4fb2baa-398f-410e-a0c3-640496c936c8.png">

**Comment by sanshui3** [comment]
该资源在https://www.freepik.com/ 上可以免费下载并商用，某些人却以此来牟利

**Comment by kirk-ye** [comment]
感觉您的反馈，已经做下架处理了。
