### ISSUE TITLE
iconfonts不能同时使用一个字母的大写形式和小写形式命名，只能选择其一，否则会出现命名重复，这是之前创建字体项目库时没有出现过的

### ISSUE THREAD

**Issue by jinjing602** [thx/iconfont-plus#242]
iconfonts中font_class不能同时使用一个字母的大写形式和小写形式命名，只能选择其一，否则会出现命名重复，这是之前创建字体项目库时没有出现过的

**Comment by purplebamboo** [comment]
的确如此，新版校验更严格，大小写一样也是代表重复的哈。
