### ISSUE TITLE
图标库突然黑白融合块状化

### ISSUE THREAD

**Issue by jdh8088** [thx/iconfont-plus#2426]
## 问题描述
图标库黑白融合块状化，系统又出问题了吧？
## 截图
![image](https://user-images.githubusercontent.com/68884174/207478101-ff7e817b-0db9-4942-97f1-0b0f682519f3.png)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 期望结果
恢复原上传效果
## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by jdh8088** [comment]
https://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.dc64b3430&cid=42759  链接

**Comment by yisibl** [comment]
感谢反馈，已经恢复。
