### ISSUE TITLE
再次举报盗版资源，竟然可以随意打上原创标签，将其他平台付费资源做私用，授权商用，私自出售！

### ISSUE THREAD

**Issue by sanshui3** [thx/iconfont-plus#2429]
## 问题描述
再次举报盗版资源，竟然可以随意打上原创标签 将其他平台付费资源做私用，授权商用，私自出售

## 截图

https://www.iconfont.cn/illustrations/detail?spm=a313x.7781069.1998910419.dc64b3430&cid=43156
<img width="1185" alt="image" src="https://user-images.githubusercontent.com/119911667/209604610-d077d702-d48b-43b4-9694-167a00a33a48.png">
<img width="825" alt="image" src="https://user-images.githubusercontent.com/119911667/209605631-7f2e92f8-f0fd-49f7-a37f-39565cc486d5.png">

原资源出处 https://iconscout.com/illustration-pack/business-1068
<img width="1877" alt="截屏2022-12-27 11 01 44" src="https://user-images.githubusercontent.com/119911667/209604570-a5bcb63f-3127-4eab-ba13-3d37deba21e3.png">

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 期望结果
下架资源
ps：该用户其他资源均为盗版资源，并且以原创授权商用为名，私自出售

## 相关信息（重要）
- 发生问题的 URL：https://www.iconfont.cn/illustrations/detail?spm=a313x.7781069.1998910419.dc64b3430&cid=43156
- iconfont 的用户昵称：神下无言
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by huzunjie** [comment]
该审核拒绝的不拒绝，不该拒绝的反复上传都无法成功

**Comment by yisibl** [comment]
非常感谢您的反馈，这个库在之前已经下架
