### ISSUE TITLE
在项目里删除图标后页面上还会显示该图标

### ISSUE THREAD

**Issue by DBvc** [thx/iconfont-plus#2431]
## 问题描述
删除图标后刷新页面，图标还存在，但再次编辑的时候又会提示找不到图标
## 截图

<img width="608" alt="1672207838177" src="https://user-images.githubusercontent.com/5419886/209766471-c8db7ece-7f41-40e1-9c2f-5faafb3b7227.png">

## 重现步骤
1. 打开：我的项目里的任意一个项目
2. 删除已有的某个图标，然后刷新页面
3. 这个页面还会出现在项目中，但是点击编辑会提示找不到这个图标

## 期望结果
能正确删除图标

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：DBvc
- iconfont 项目 ID：2164663

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：win11

- 浏览器名称及版本：Chrome Version 108.0.5359.125 (Official Build) (64-bit)

**Comment by superlongwei** [comment]
同样的问题

**Comment by DBvc** [comment]
看起来已经恢复了，先关了
