### ISSUE TITLE
下载默认了上次的颜色 需要怎么手动去色？

### ISSUE THREAD

**Issue by H402861965** [thx/iconfont-plus#2437]
## 问题描述
下载默认了上次的颜色 需要怎么手动去色？
## 截图

![1672738068212](https://user-images.githubusercontent.com/31874808/210330547-d9205f8d-f769-48f0-b813-a7ed45bb8f99.jpg)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
![image](https://user-images.githubusercontent.com/2784308/210696531-dc6ae395-ef7e-4de1-9aac-cd0869213948.png)
颜色选择器现在增加了清空功能，点击后使用图标的默认颜色。
