### ISSUE TITLE
为啥新版要登录才能下载

### ISSUE THREAD

**Issue by PMSherlock** [thx/iconfont-plus#244]
为啥？

**Comment by PMSherlock** [comment]
而且为啥把默认可选的色值改了？#1afa29 这个绿色辣眼睛，#f4ea2a也好不到哪里去，本来很多时候只是要一个顺眼的颜色做快速原型，这下还得自己copy色值过去，差评

**Comment by purplebamboo** [comment]
sorry 亲  登陆才能下载是因为 好多人爬我们的数据，所以需要用登陆拦截这些人。敬请谅解。

关于默认颜色的问题，新版增加了更多的颜色呀，同时其实我们会记录下来你上次使用的颜色的，如果你不喜欢推荐的，你可以一直用你自己喜欢的那个的呀。

**Comment by PMSherlock** [comment]
这样哦，但是防爬数据，不是应该拉IP黑名单加验证码之类的吗，强制登录才能使用貌似不太合理吧。

**Comment by purplebamboo** [comment]
嗯  我们之前也是 用nginx 禁止ip的，但是  这样总不是个办法，老有人跟我们做迷藏呀。

后续我们会考虑接入 阿里的防爬系统的。话说 登陆一下 也不是啥大问题呀，登陆一次就可以一直用下去了呀，也不需要你注册啥的，就点一下而已。希望亲 谅解下。
