### ISSUE TITLE
[Help]上传图标报错 UPLOAD_ERROR_DETAIL

### ISSUE THREAD

**Issue by azhu007** [thx/iconfont-plus#2440]
## 问题描述
上传svg图标报错，提示UPLOAD_ERROR_DETAIL

## 相关截图
![image](https://user-images.githubusercontent.com/19324818/211272650-e6e05a30-60f4-48e5-95ec-bdf8245ba62a.png)

**Comment by yisibl** [comment]
请提供报错图标的 svg 文件

**Comment by yisibl** [comment]
出现这个通常是需要将 SVG 中的图层进行轮廓化，然后去掉滤镜遮罩等效果。
