### ISSUE TITLE
windows新版Chrome下图标渲染模糊

### ISSUE THREAD

**Issue by e-cloud** [thx/iconfont-plus#245]
iconfont 本身加了这样一个增加图标线段宽度的属性：
```css
-webkit-text-stroke-width: 0.2px;
```

但在windows的新版Chrome 54+下，却会造成图标线段加粗效果:
这是16p下的图标效果 ![qq 20161208104029](https://cloud.githubusercontent.com/assets/5255354/20995547/cfb88a4c-bd32-11e6-95fb-52ea015c81d3.png)

PS: 但是在ubuntu下却没有那么明显的模糊

**Comment by purplebamboo** [comment]
嗯嗯 我们也发现了。

新版的chrome不需要用这个了，我会把它从 我们的生成的css里面去掉，不过最近双十二封网了。

需要等13号发布上线哈。

**Comment by purplebamboo** [comment]
已经去掉了哈

**Comment by e-cloud** [comment]
请问需要更新访问链接吗？

**Comment by purplebamboo** [comment]
要的哈，需要重新生成一下。

可以修改下项目信息，或者 修改下图标。比如改下图标名字啥的。

之后重新生成就可以了哈。

**Comment by e-cloud** [comment]
好的，谢谢
