### ISSUE TITLE
希望添加【生成雪碧图】功能

### ISSUE THREAD

**Issue by jwwwww** [thx/iconfont-plus#2458]
## 需求背景
为了减少图片请求次数，这些小图使用雪碧图会更划算。下载图片后还得用其他软件生成雪碧图，很麻烦

## 解决方案
在【我的图标】页面添加【生成雪碧图】功能，点击后可选择需要的图标，设置一次 各图标大小，设置图标颜色（默认当前颜色），设置背景颜色（默认透明）。然后点击【生成雪碧图并下载】即可获得一张png格式的雪碧图
## 相关截图
![image](https://user-images.githubusercontent.com/22487180/216501498-e9e12460-3866-42ae-aac3-9ae2e12373d2.png)

**Comment by yisibl** [comment]
推荐使用使用字体模式
