### ISSUE TITLE
汽车仪表 icon 的多色问题[Help]

### ISSUE THREAD

**Issue by SilvioSha** [thx/iconfont-plus#2459]
## 问题描述
单色 icon 为什么不能在同一图标库里使用多色？
对于汽车仪表的 icon 常常用同一个 icon 的不同颜色来表示不同状态，如果我全部去色根本不能传达对应的意思啊
## 相关截图
<img width="692" alt="image" src="https://user-images.githubusercontent.com/104990316/217132072-51cde59f-4341-4bb3-841a-081bf6c2b7d7.png">

**Comment by yisibl** [comment]
上传多色图标到项目→点击编辑→保存为副本→对副本图标去色
