### ISSUE TITLE
我的项目中批量下载png图标，能选择颜色下载

### ISSUE THREAD

**Issue by Chen-Page** [thx/iconfont-plus#2463]
## 需求背景
用户导航等功能需要同时有默认图标颜色，和点击后显示的高亮颜色
考虑到用户使用的便捷性，此功能为让用户自己上传图片，而不是使用字体图标
在将图标添加进我的项目后，在项目内可以批量下载png图标，但是都是图标默认的颜色
现在要修改颜色只能单独点进每个图标去修改
现在已有批量去色功能

## 解决方案
希望能直接在项目编辑的地方批量修改颜色或者在下载时选择颜色

## 相关截图
![image](https://user-images.githubusercontent.com/42233758/218945389-31ace796-6d77-4116-bdeb-dc3dfa8f630c.png)

![image](https://user-images.githubusercontent.com/42233758/218944638-4cfb90c0-f1f5-4d96-9119-b19a64ae22c6.png)

**Comment by yisibl** [comment]
已经有下载时批量修改颜色的功能：

- 把需要的图标添加到购物车。
- 打开购物车，下载按钮上方有修改颜色的选择器。
