### ISSUE TITLE
搜索关键字 sql 出来的图标都不能下载

### ISSUE THREAD

**Issue by somnusnrlq** [thx/iconfont-plus#2469]
![image](https://user-images.githubusercontent.com/10290501/220259332-30654ab5-3017-4192-82f2-41f9a2689048.png)
搜素sql 这个关键字能搜出很多结果，点击下载效果如下 
![image](https://user-images.githubusercontent.com/10290501/220259308-9c94222b-82a4-44e4-a7bb-010bc18c9786.png)

**Comment by yisibl** [comment]
已解决
