### ISSUE TITLE
图标的高度过大，引入之后影响其他的布局

### ISSUE THREAD

**Issue by tiramisu-leo** [thx/iconfont-plus#247]

**Comment by purplebamboo** [comment]
亲  这一般都是你项目里某个图标比较高，把整个字体撑开了。

只要采用二分法，把这种图标删除掉就行了。

可以查看这里http://www.iconfont.cn/plus/help/article_detail?article_id=1

搜索 单个icon撑开的问题

**Comment by tiramisu-leo** [comment]
我引入的所有的字体都有一个默认的高度，不改变字体大小的情况下，在浏览器中查看高度都是47

**Comment by purplebamboo** [comment]
亲  给个具体的例子？ 我理解你应该就是  因为单个图标把所有的字体撑开了。

**Comment by purplebamboo** [comment]
你先看看  我给你贴的链接哈，应该就是这个问题哈。
