### ISSUE TITLE
iconfont还有在维护吗？搜索功能很久以前就无法使用了，到现在还是不行

### ISSUE THREAD

**Issue by hzm07** [thx/iconfont-plus#2470]
## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by kirk-ye** [comment]
无法使用能更具体吗？
