### ISSUE TITLE
登录不上了

### ISSUE THREAD

**Issue by littlebearGreat** [thx/iconfont-plus#2471]
什么情况啊，以前绑定过手机号码了，现在直接用手机号登录，提示错误；又装了个新浪微博扫码登录，扫码登录后还是让绑定手机号码，并且没有登录状态，绑定手机号码的时候发送验证码提示错误。反正就是登录不上

**Comment by leechuichui** [comment]
+1，啥情况啊

**Comment by ivista110** [comment]
我也不能登录了，搜索功能也用不了

**Comment by Janesonalbert** [comment]
不会停用了吧

**Comment by Acong96** [comment]
我也是

**Comment by fengkunCode** [comment]
手机可登录，下载不了。电脑一直提示错误

**Comment by WYWY131466** [comment]
怎么回事。发送验证码报error

**Comment by zbr826858040** [comment]
直接登录报登录失败，微博扫码后又要帮手机号，发送手机验证码也报错

**Comment by sunliu92** [comment]
昨天开始登录提示“登录失败”，找回密码提示“error”

**Comment by yisibl** [comment]
已经可以了，感谢反馈。
