### ISSUE TITLE
审核流程会让开发人员，设计人员远离该平台

### ISSUE THREAD

**Issue by amazecc** [thx/iconfont-plus#2473]
作为一个前端开发，对目前的审核机制非常无力，在有好的选择的情况下，会考虑以后不在基于该平台管理项目图标。

**Comment by fengchuanBIG** [comment]
是的我也这样认为，还是只有自己公司私有化才是终极王道，现在的审核机制太恶心了，

**Comment by qingLongMuZi** [comment]
有新的选择么？？现在购物车已经无法点击了，估计已经放弃，没有维护了

**Comment by kirk-ye** [comment]
审核机制是因为要保障内容。
@qingLongMuZi   购物车目前我看是可以操作的。如果无法点击可以反馈给我。

**Comment by yixinyou123** [comment]
> 审核机制是因为要保障内容。 @qingLongMuZi 购物车目前我看是可以操作的。如果无法点击可以反馈给我。

但是我们上传自己项目所用的icon，就别要审核了吧，如果公开可以审核，我们都是私有的
