### ISSUE TITLE
下载font class 到本地，windows 提示有病毒

### ISSUE THREAD

**Issue by mizhousoft** [thx/iconfont-plus#2474]
![1677542692152](https://user-images.githubusercontent.com/4065604/221717498-274b793d-9737-4f03-b1b4-c784599663bc.png)

**Comment by yang-xianzhu** [comment]
同样问题

**Comment by yisibl** [comment]
这个应该是误报了

**Comment by mizhousoft** [comment]
我重新把图标复制到另外一个项目就正常了

**Comment by yisibl** [comment]
好的，那我先关闭了
