### ISSUE TITLE
之前老版用的淘宝账号登录的，现在新版不支持了，我收藏的图标怎么办啊，急！！！

### ISSUE THREAD

**Issue by zhengyuxi1991** [thx/iconfont-plus#248]
@purplebamboo 之前老版用的淘宝账号登录的，现在新版不支持了，我收藏的图标怎么办啊，急！！！
淘宝账号是:d调华丽_jay
现在用的github账号(zhengyuxi1991)登录的，能帮我转移一下么，谢谢了

**Comment by purplebamboo** [comment]
亲  iconfont从来不支持淘宝账号呀。

你这个用户名  我搜索了下  没有呀。
