### ISSUE TITLE
[Help]有没有办法优化在字体未加载情况下的显示效果

### ISSUE THREAD

**Issue by lie5860** [thx/iconfont-plus#2480]
## 问题描述
字体没有加载的时候，显示的是一个框 口
虽然中的字体大小也才22kb 其实在大部分场景下加载是很快的。但是我想默认显示一个宽高一致的字。。不知道有没有什么好的办法。

**Comment by yisibl** [comment]
你是指字体库吗？

在引用 iconfont 字体的 `@font-face` 中试试加一个 `font-display: block;`

**Comment by lie5860** [comment]
![1679498317453](https://user-images.githubusercontent.com/30894657/226951910-d4a94189-1b0d-4a11-9075-2d3c20bfca7c.jpg)
就是在字体库没加载完成的时候 会使用默认的字体库。那图标的宽度就变化了。布局会变化。。

**Comment by yisibl** [comment]
看起来你说的是图标，不是中文字体。

所以，你可以试试使用  `<link preload>` 预加载字体图标的 woff2 文件。

**Comment by lie5860** [comment]
嗯 现在通过对icon的组件设置1em的宽度和高度 能保证布局不会变化。
我现在就是在假想一种场景。我的woff、ttf的加载速度很慢。样式表和页面其他内容都挺快的。
有没有一种可能。就是我可以在样式文件里面创建一个字体。所有的字符都会映射到同一个图标上（例如一个默认图标）。然后我直接把这个图标的svg用base64写在样式表中。（因为我对字体文件的生成逻辑不太了解。如果说 一个会映射到任意字符的字体文件等于几何倍数的图标文件大小的话。那就算了。

**Comment by yisibl** [comment]
字体也可以在 项目设置中转换为 base64
![image](https://user-images.githubusercontent.com/2784308/228536126-a6ae97d8-5ef2-48b4-8670-5d65b3c5c6bb.png)

**Comment by lie5860** [comment]
好耶 感谢大佬解答
