### ISSUE TITLE
iconfont我的项目消失了

### ISSUE THREAD

**Issue by wooffox** [thx/iconfont-plus#2482]
突然发现我的项目下面的多个字体项目消失了，2月份应该是还在，引入的cdn还可以用
项目ID：3898222

劳烦帮忙查看查看

**Comment by kirk-ye** [comment]
看项目都还是在的，项目名：videvo。
你是不是搞错登录账号了。

**Comment by yangjie2021** [comment]
我的也丢了，没有换zhan账号，这个项目只有我一个人管理
项目ID：2766635

<img width="1245" alt="image" src="https://user-images.githubusercontent.com/19945710/228181880-b81d8fab-5365-4d11-97fd-46a791e6ac8d.png">

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/19945710/228181749-555f7e75-d4cc-4f0d-bbd0-1eaa0ca94525.png">

**Comment by yangjie2021** [comment]
@kirk-ye
