### ISSUE TITLE
自己上传的图标无法编辑

### ISSUE THREAD

**Issue by 13148829008** [thx/iconfont-plus#2484]
`##` 上传的图标无法编辑，提示使用代理服务器或VPN

## 截图
![1679541515538](https://user-images.githubusercontent.com/49675145/227093292-e8264772-92f5-4d54-9181-e6b6766f43f2.jpg)

**Comment by kirk-ye** [comment]
这种一般是被安全拦截了，可以过一段时间再尝试。
