### ISSUE TITLE
iconfont在页面中使用时全变成了一个小方框

### ISSUE THREAD

**Issue by youniuben** [thx/iconfont-plus#249]
之前使用的时候没有问题，从昨天开始使用新上传的iconfont网页中显示的全是小方框，不知道是哪里出了问题

**Comment by purplebamboo** [comment]
最好提供个demo，最好是线上地址。

如果用的是我们生成的cdn地址。
可能的原因有：

1. 新加了几个图标，这几个图标有问题，导致整个字体坏掉了。
2. 多加了几份字体，字体冲突了。

另外提供下 项目地址。

**Comment by youniuben** [comment]
项目还在开发  现在使用之前的图标还是没有问题  只是使用这两天新上传的就变成小方框了

**Comment by youniuben** [comment]
http://www.iconfont.cn/plus/manage/index?manage_type=myprojects&spm=a313x.7781069.1998910419.10.QAqJQD&projectId=97076

**Comment by purplebamboo** [comment]
嗯  那就是说  你们新增加了几个小icon，导致整个项目被影响了。

**Comment by youniuben** [comment]
现在使用之前的iconfont没有问题  使用从昨天开始上传的就有问题了

**Comment by youniuben** [comment]
负责上传iconfont的人说她是和以前一样上传的  哪里会出问题呢

**Comment by purplebamboo** [comment]
亲  我看了下，字体没有问题。

应该是不是使用上的问题，比如字体冲突了。


![wangwang20161209145605](https://cloud.githubusercontent.com/assets/1409611/21040407/a97cce2c-be1f-11e6-8d5d-615c96f30551.png)

**Comment by purplebamboo** [comment]
另外我下载我们平台的demo。都是正常的。
证明字体什么的都是正常的哦。

**Comment by youniuben** [comment]
好的 我再检查下 谢谢您的答复

**Comment by youniuben** [comment]
我刚才又试了一下 只有 chrome浏览器下有这个问题  换个浏览器就好了。。

**Comment by purplebamboo** [comment]
亲  你试下我们的demo呢  下载项目到本地，如果这个没问题  那么就是使用上的问题，如果demo也有问题，那么就是字体的问题。

**Comment by cgd199158** [comment]
@youniuben 请问下问题解决了吗？我也碰到一样的问题，在chrome浏览器下为方框，在Firefox下能够正常显示
