### ISSUE TITLE
公开的矢量库修改了简介重新提交审核通过后，在库里看不到也搜不到自己上传

### ISSUE THREAD

**Issue by Xieekep** [thx/iconfont-plus#2490]
## 截图
![5031680573710_ pic](https://user-images.githubusercontent.com/129812649/229667306-a99a367b-3e55-495f-9603-36290d0019a4.jpg)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：https://www.iconfont.cn/illustrations/detail?cid=44303
- iconfont 的用户昵称：汀雪楼
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
已经可以了。
