### ISSUE TITLE
创建图标库上传源文件失败

### ISSUE THREAD

**Issue by Hannah-D-Y** [thx/iconfont-plus#2500]
## 问题描述
##创建图标库时上传源文件，尝试上传了.sketch和.fig格式文件，都提示上传失败

##
![1682413079456](https://user-images.githubusercontent.com/104352750/234227264-6d5ad646-4115-4809-90b4-3e21b1ae97b8.jpg)

**Comment by yisibl** [comment]
收到，感谢反馈，我们会尽快修复
