### ISSUE TITLE
矢量插画无法下载，控制台报错

### ISSUE THREAD

**Issue by aRin-1995** [thx/iconfont-plus#2504]
## 问题描述

目前只测了矢量插画库有这个问题，并且很多插画都无法下载，点击任意下载按钮弹窗无法进入颜色编辑模式，
并且 SVG下载、PNG下载等按钮点击均无响应，同时控制台有报错

## 截图

![image](https://github.com/thx/iconfont-plus/assets/64877781/fa8f8073-b6e3-4937-abfc-79c2292b4c0a)

## 重现步骤
1. 打开：矢量插画库
2. 点击：任意下载按钮
3. 出现：无法编辑

## 相关信息（重要）
- 发生问题的 URL：https://www.iconfont.cn/search/index?searchType=illustration&q=%E8%B4%AD%E7%89%A9%E5%A5%B3%E5%AD%A9
- iconfont 的用户昵称：aRinCloud
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：Win10企业版21H2 19044.2846

- 浏览器名称及版本：Chrome 112.0.5615.138

**Comment by aRin-1995** [comment]
补充一个报错信息，这个问题真的很影响使用，好多矢量插图库都用不了，希望能尽快解决

![image](https://github.com/thx/iconfont-plus/assets/64877781/47747c35-f332-49dd-8842-cf181a63f80c)

**Comment by zimond** [comment]
今天修好

**Comment by zimond** [comment]
已经上线
