### ISSUE TITLE
2016年度用户体验最差产品-iconfont

### ISSUE THREAD

**Issue by caolingpeng** [thx/iconfont-plus#251]
所有登录方式都试遍了，都不能登录，简直比12306的用户体验还差，我本来以为12306没人能超过，没想到是大阿里完胜，厉害了我的哥

**Comment by purplebamboo** [comment]
＝ ＝ 亲不能登陆不是我们的锅，应该是 你访问github比较慢，加微博登陆限制了你。

因为一个登陆就说 体验差，实在不敢苟同。有问题可以慢慢解决呀。

**Comment by purplebamboo** [comment]
另外github是用来提建议的地方，不是用来抱怨的。抱怨也解决不了问题。
