### ISSUE TITLE
我在下载iconfont图标为png图片时，修改了宽高为20px，下载后发现图片失真了，有什么解决方法吗？[Help]

### ISSUE THREAD

**Issue by qingziAA** [thx/iconfont-plus#2511]

**Comment by qingziAA** [comment]
<img width="586" alt="1" src="https://github.com/thx/iconfont-plus/assets/133961348/021f8f5c-965f-4c36-9a12-f478f668fca7">

**Comment by yisibl** [comment]
可以试试下载更大尺寸的，然后用其他工具缩小为需要的小尺寸
