### ISSUE TITLE
上传3d素材，提交c4d源文件，无法上传

### ISSUE THREAD

**Issue by 1spotlight** [thx/iconfont-plus#2512]
## 截图

![image](https://github.com/thx/iconfont-plus/assets/134031963/8a7c98f8-4cd2-4986-9cac-2d09c4629569)

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
现在可以了，再试试。
