### ISSUE TITLE
「文档」代码应用文档补充彩色字体

### ISSUE THREAD

**Issue by wenfangdu** [thx/iconfont-plus#2514]
## 需求背景
现在 iconfont 已支持彩色字体，但是文档里还是写着字体只支持单色，多色推荐 svg symbol：

https://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.27&helptype=code

## 解决方案
文档补充彩色字体相关的使用方式。

## 相关截图
![image](https://github.com/thx/iconfont-plus/assets/28700378/ee1468a8-049a-4d4f-83df-27039b6f22e5)

**Comment by yisibl** [comment]
好建议，我晚点更新一下。

**Comment by yisibl** [comment]
已更新

**Comment by wenfangdu** [comment]
@yisibl 大佬，还有这些：
![image](https://github.com/thx/iconfont-plus/assets/28700378/6d0dbd9d-f188-4c85-97cc-78a873b1d0d4)
![image](https://github.com/thx/iconfont-plus/assets/28700378/0ac787a7-c057-4ae8-a258-caba3afd9615)

**Comment by wenfangdu** [comment]
@yisibl 大佬，重开一下吧，还有这些：
![image](https://github.com/thx/iconfont-plus/assets/28700378/6d0dbd9d-f188-4c85-97cc-78a873b1d0d4)
![image](https://github.com/thx/iconfont-plus/assets/28700378/0ac787a7-c057-4ae8-a258-caba3afd9615)

**Comment by wenfangdu** [comment]
@yisibl 大佬，重开一下吧，还有这些，建议整体过一遍：
![image](https://github.com/thx/iconfont-plus/assets/28700378/6d0dbd9d-f188-4c85-97cc-78a873b1d0d4)
![image](https://github.com/thx/iconfont-plus/assets/28700378/0ac787a7-c057-4ae8-a258-caba3afd9615)

**Comment by wenfangdu** [comment]
@yisibl 大佬，重开一下吧，还有这些，建议把文档整体过一遍：
![image](https://github.com/thx/iconfont-plus/assets/28700378/6d0dbd9d-f188-4c85-97cc-78a873b1d0d4)
![image](https://github.com/thx/iconfont-plus/assets/28700378/0ac787a7-c057-4ae8-a258-caba3afd9615)

**Comment by wenfangdu** [comment]
@yisibl 大佬，重开一下吧，还有这些，建议把文档整体过一遍哈：
![image](https://github.com/thx/iconfont-plus/assets/28700378/6d0dbd9d-f188-4c85-97cc-78a873b1d0d4)
![image](https://github.com/thx/iconfont-plus/assets/28700378/0ac787a7-c057-4ae8-a258-caba3afd9615)
