### ISSUE TITLE
[Help]请问生成的旧链接有没有具体的存续机制？能存在多久？

### ISSUE THREAD

**Issue by jxzhou-anylink** [thx/iconfont-plus#2524]

**Comment by yisibl** [comment]
哪个地方的链接？

**Comment by jxzhou-anylink** [comment]
> 
![image](https://github.com/thx/iconfont-plus/assets/76543102/aa369690-a61b-4816-b218-3abb4bbfb8ab)
生成新链接后，以前的旧链接还能用，但不知道能存在多久

**Comment by yisibl** [comment]
只要图标合法合规理论上会长期有效。
