### ISSUE TITLE
数黑体中，缺少字：鸿

### ISSUE THREAD

**Issue by xgd0116** [thx/iconfont-plus#2531]
<img width="1077" alt="image" src="https://github.com/thx/iconfont-plus/assets/16185603/480dbfc8-26ff-4ac2-96e8-a50c6811e928">
数黑体中，缺少字：鸿
https://www.iconfont.cn/api/webfont/subset.json
{"text":"鸿","is_buffer":false,"cnid":"a9fXc2HD9n7s"}
{code: 500, error_code: "font_file_size_check_failed"}

**Comment by yisibl** [comment]
感谢反馈，已解决

![image](https://github.com/thx/iconfont-plus/assets/2784308/c5cacc35-0e4c-4a09-b303-e1086ac0cb21)

**Comment by 1361751025** [comment]
我在转换子集的“幽”时，提示我：font_file_size_check_failed
![微信图片_20240822155915](https://github.com/user-attachments/assets/69ca751d-cd77-43b1-91c3-1abd974a4d6b)
