### ISSUE TITLE
没有注销功能，忘记登录方式用手机注册后，无法跟以前微博登录的账户绑定

### ISSUE THREAD

**Issue by sunzizhen** [thx/iconfont-plus#2539]

**Comment by yisibl** [comment]
登录后可以在这里删除账户：
https://www.iconfont.cn/user/center?spm=a313x.7781069.1998910419.de91a75a0.60463a81Y0A2QM&tab=account

![image](https://github.com/thx/iconfont-plus/assets/2784308/6ecc635d-0658-40b7-94b3-61ae27e343bb)
