### ISSUE TITLE
拜托图标的Unicode还是按顺序啊,别更新一个图标,Unicode又变了,还得回去改代码..

### ISSUE THREAD

**Issue by amhoho** [thx/iconfont-plus#254]
我的项目都是用的Unicode,原来挺好的,都按着顺序比如xe601 xe602...现在这样无需很不方便啊,特别是删除了icon再换个的时候的就得回页面改代码,好麻烦.

**Comment by amhoho** [comment]
再建议一个,啥时候出个可以调整粗细的就很棒了,经常因为太粗或太细而找好几回.

**Comment by purplebamboo** [comment]
先回答第一个问题哈，目前是按照 图标的加入项目的时间排序的。也就是说，后加入的图标在最前面。这么做的原因是用户可以看到最新加入的icon。其实unicode不需要按顺序呀，反正只是用的时候查一下。而且目前大部分人使用的是  font——class的方式哦。当然针对亲的场景，后期我们推出个排序功能，可以自定义排序，按照不同的方式排序（按时间，按unicode，按名称）

第二个问题，粗细有点难办，＝ ＝因为我们的图标都是用户上传的，很不可控。亲，经常发现图标不统一是因为没有用一个系列的图标。是这样的，点击下载图标，是可以看到这个图标所属的公共库的，你可以跟进去找到相关的一个体系的图标的。

**Comment by amhoho** [comment]
@purplebamboo 第一个好像理解歧义了 并非项目里的图标排序,而是每个图标下面的unicode代码现在没什么规律,比如我经常这样:
原有图标xe601,xe602,xe603.
当我想更新xe602的时候,
旧版:删除xe602,再添加的时候就是xe602了.
现在:删除xe602.再添加的时候也许就是ex60b了,这样一来,用户就要返回自己引用页去改代码,太累撒.

我觉得第二个你们会想出一个好办法,谁叫你们这么聪明撒.^_^

**Comment by purplebamboo** [comment]
第二个 目前真心没办法，我们也一直想做呢。

关于unicode的问题，两个逻辑是一样的呀。
我再复述下unicode的生成逻辑哈。

每个图标上传时自己就会分得一个unicode。

而加入项目里，会对这个unicode重排：
比如你现在要加图标A，它的原始unicode是xe601。
比如要加的项目里有了  xe601,xe603.  这个时候你加一个A，那么就会重排，A加入的时候会发现601已经有了，那么自己就加1。发现602没有啦，那就安心的用602.

同理，你说的第二种情况，比如你要加一个原始图标是 B ，它的原始unicode是 ex60b。那么问题来了，它加入的时候，发现这个坑位没人，那它就占据了。

综上所述，图标的unicode生成规律很随性的，你千万别指望靠这个达到，删除图标加图标uniocde不变的目的。


正确的做法是，删除这个图标，记住它的unicode，再加入新的图标，编辑修改新图标的unicode为之前的那个。这样就可以啦。

**Comment by amhoho** [comment]
嗯了 明白了 不过你上文说的这种填补如今是真的真的没有了...不过没关系了 以后项目都用class来解决,建议选中后还是继续抛物到购物车 现在有时候加了都不知道.

**Comment by purplebamboo** [comment]
= = 天地良心，这个补位真的有的，我刚才还特地去试了下，真的有的。

加购物车这个，主要有人反馈那个动画碍事。所以才去掉的，添加后  会有选择的虚框的哈，怎么会不知道加了呢。然后购物车会有个+1弹圈的效果，不过这个效果的确有点弱，我们后面再优化看看
