### ISSUE TITLE
推特官网logo已更新，iconfont未更新

### ISSUE THREAD

**Issue by zxm0620** [thx/iconfont-plus#2543]
推特官网logo已更新，iconfont未更新

## 重现步骤
1. 打开：
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
请提供一下链接。

**Comment by zxm0620** [comment]
https://www.twitter.com/
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "一丝"; 
Date: 2023年8月30日(星期三) 下午2:47
To: "thx/iconfont-plus"; 
Cc: "zxm0620"; "Author"; 
Subject: Re: [thx/iconfont-plus] 推特官网logo已更新，iconfont未更新 (Issue #2543)

&nbsp;


 
请提供一下链接。

**Comment by yisibl** [comment]
我是指 iconfont 哪个地方的 Twitter 图标需要更新？提供一下 iconfont 页面的地址。

**Comment by zxm0620** [comment]
https://www.iconfont.cn/search/index?searchType=icon&amp;q=%E6%8E%A8%E7%89%B9&amp;page=1&amp;fromCollection=1&amp;fills=&amp;tag=
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "一丝"; 
Date: 2023年8月30日(星期三) 晚上7:00
To: "thx/iconfont-plus"; 
Cc: "zxm0620"; "Author"; 
Subject: Re: [thx/iconfont-plus] 推特官网logo已更新，iconfont未更新 (Issue #2543)

&nbsp;


 
我是指 iconfont 哪个地方的 Twitter 图标需要更新？提供一下 iconfont 页面的地址。

**Comment by yisibl** [comment]
这是三方用户自行上传的图标，需要上传者自己更新。
