### ISSUE TITLE
在下载历史中点击图标，全都报错“找不到这个图标”

### ISSUE THREAD

**Issue by kankanai** [thx/iconfont-plus#2544]
## 问题描述
在有的界面，比如  下载历史  中点击图标，明明都可以看到，也可以搜索到，却全都报错“找不到这个图标”

## 截图
   
![image](https://github.com/thx/iconfont-plus/assets/142068366/35816dcb-8d06-43fe-8c36-73528b3b88d1)

**Comment by yisibl** [comment]
修复了，再试一下
