### ISSUE TITLE
添加成员真的太太太太太太麻烦了

### ISSUE THREAD

**Issue by Jemity** [thx/iconfont-plus#2547]
## 需求背景
创建项目后需要拉项目成员进项目使用项目图标
## 解决方案
增加批量添加人员进项目的入口，类似蓝湖的链接进入或者百度网盘的密码进入
## 相关截图
未截图，一想到我要一个个搜索成员添加，我就不想用

**Comment by yisibl** [comment]
感谢建议，通过链接邀请成员功能已经上线。
![image](https://github.com/thx/iconfont-plus/assets/2784308/469a4e27-c686-462f-b249-4d51cda2608f)
