### ISSUE TITLE
我上传的icon列表批量操作选择后没有加入购物车操作项

### ISSUE THREAD

**Issue by elonglau** [thx/iconfont-plus#255]
少了一个入库的按钮，导致只能一个一个选进去

**Comment by purplebamboo** [comment]
额。。 因为，亲 你这个是多此一举啊。

1. 你一个个选择 加入购物车。
2. 你点批量操作按钮，再一个个选择，再点批量加入购物车。

你不觉得，第二个操作还多了两步吗？

**Comment by elonglau** [comment]
你没明白我的意思，批量选择之后就没有任何操作可进行了，也并没有直接“默认”同时加入购物车，点购物车无效

**Comment by purplebamboo** [comment]
不是太明白哈。批量选择目前只会提供删除图标的功能哈。

批量加入购物车没有必要，因为你一个个选择图标 本身就是批量选择的动作呀。

**Comment by elonglau** [comment]
我看出来了只有删除。不过我一次传100个图标一个个选进去，你们不觉得有个批量操作更好吗？

**Comment by purplebamboo** [comment]
@elonglau 

亲  就像我上面说的呀。这个批量操作没有意义啊。

比如你现在有100个图标，两个路径。

* 你一个个选择加入购物车
* 你先点击批量操作-》 再一个个选择-》 最后再点击批量加入购物车

＝ ＝ 我以前也有你这样的疑问，后来交互表示其实没必要的。

或者是不是因为目前加入购物车的那个浮层不是太直观，点起来不好点？所以你希望直接用批量的选择？
如果是这个，到时可以试试优化下。
