### ISSUE TITLE
彩色图标不支持color修改颜色吗？看你们官方案例支持。

### ISSUE THREAD

**Issue by imp-oh** [thx/iconfont-plus#2550]
## 问题描述
彩色图标不支持color修改颜色吗？看你们官方案例支持。
我在项目中下载的彩色字体使用color 修改颜色并没有效果

## 相关截图
![image](https://github.com/thx/iconfont-plus/assets/90586970/b78882c8-bd41-4b90-ae34-bb33f6ec7998)

而你们官方的图标是正常的
![image](https://github.com/thx/iconfont-plus/assets/90586970/523e0bf2-d095-46a0-a7d1-f43043ec1b26)

**Comment by yisibl** [comment]
彩色字体本身是不支持用 CSS color 修改颜色的，示例中第一图标不是彩色字体。

**Comment by imp-oh** [comment]
> 彩色字体本身是不支持用 CSS color 修改颜色的，示例中第一图标不是彩色字体。

也就是说，彩色字体跟单色图标必须分开使用吗

**Comment by yisibl** [comment]
嗯 目前是的，要分开使用。一起使用我得看看能不能实现。

**Comment by imp-oh** [comment]
> 
好的，谢谢
