### ISSUE TITLE
阿里妈妈东方大楷是免费商用吗？可以用包装设计吗？需要授权吗？

### ISSUE THREAD

**Issue by 321sunshine** [thx/iconfont-plus#2553]
## 问题描述
阿里妈妈东方大楷字体是免费商用字体吗？
可以用来包装设计吗？需要授权吗？

**Comment by jamin-han** [comment]
你好, 

感谢贵司的信任

阿里妈妈系列免费字体是向全社会免费开放商用的beta公测字体，可以用于贵司的包装设计。

还望提出宝贵意见，方便我们日后进行迭代。 
反馈邮箱：alimama-font@list.alibaba-inc.com
谢谢 

阿里妈妈智造字团队

**Comment by 321sunshine** [comment]
能出示授权吗？因为厂家需要




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月5日(星期二) 下午5:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 阿里妈妈东方大楷是免费商用吗？可以用包装设计吗？需要授权吗？ (Issue #2553)





 
Closed #2553 as completed.
