### ISSUE TITLE
上传图标后无法显示

### ISSUE THREAD

**Issue by xsheri** [thx/iconfont-plus#257]
上传图标后是空白，画布是设置的100*100px，上传格式也没错，请问是什么原因？

**Comment by purplebamboo** [comment]
亲  再看看我们的上传规范？ 

如果还是有问题，可以把svg发给我们看看。

**Comment by shanhuayao** [comment]
同样的问题，求解，
我们设计从iconfont里下载svg，调整了一下尺寸比例再导出来上传就空白了，好着急
