### ISSUE TITLE
想问一下，为什么上传的图标，应用于网站上，没办法用字体图标方式改颜色？

### ISSUE THREAD

**Issue by Zero-Freely** [thx/iconfont-plus#2573]
![3菜单收起-2](https://github.com/thx/iconfont-plus/assets/54424597/a1944b4f-75e4-4efb-b254-3523c20ec4d3)
z
![GB8消息-2](https://github.com/thx/iconfont-plus/assets/54424597/7516bb61-3056-4840-9adb-9a0ba8c14250)

**Comment by Zero-Freely** [comment]
下载了字体文件，但是之后改不了颜色，不知道怎么回事，改了好多次图标，也不行。

**Comment by luchaoet** [comment]
得在网站上把图标的颜色去掉 才能通过css改颜色

**Comment by yisibl** [comment]
> 得在网站上把图标的颜色去掉 才能通过css改颜色

是的
