### ISSUE TITLE
[Help]在mastergo上导出了svg，上传图标时显示不完全

### ISSUE THREAD

**Issue by BBX-wangyouduye** [thx/iconfont-plus#2576]
## 问题描述
mastergo导出svg后，打开是正常的，但在iconfont里上传后，轮廓全部被填上了!!!显示不完全!!!

## 相关截图
![432e2a1fed652a61b5f601ab9cedb66](https://github.com/thx/iconfont-plus/assets/46733399/1c1b5111-40bf-4792-8e46-e7d1699a51ad)

![ea98b0e7388cbe6139dbd15d4664d23](https://github.com/thx/iconfont-plus/assets/46733399/068ce827-3fdb-4e65-9638-d16738dad10e)

**Comment by BBX-wangyouduye** [comment]
![bed38f8c53f385f72a2c747c4e550a7](https://github.com/thx/iconfont-plus/assets/46733399/7f28fce5-9fe6-4655-9cf8-495ae71f573e)

**Comment by BBX-wangyouduye** [comment]
![1701239514947](https://github.com/thx/iconfont-plus/assets/46733399/f25aba65-30fb-421c-9447-ac74d1f3779a)

**Comment by BBX-wangyouduye** [comment]
![Chinese (1)](https://github.com/thx/iconfont-plus/assets/46733399/9eae7eda-8d36-4275-9bc7-0532b9861409)
 此链接是svg源文件

**Comment by yisibl** [comment]
很抱歉，目前还不支持 MasterGo
