### ISSUE TITLE
下载到本地后，采用font-class的使用方式，图标是错误的

### ISSUE THREAD

**Issue by BZJ-TYY** [thx/iconfont-plus#2583]
照下面的模板填写，以便更好的帮助你解决问题，不遵循模版，issue 将会被直接关闭。-->

## 问题描述
下载到本地后，采用font-class的使用方式，图标是错误的
## 截图

![1](https://github.com/thx/iconfont-plus/assets/81230412/0d48645e-1ddd-4bac-87e5-381e2d875665)
![2](https://github.com/thx/iconfont-plus/assets/81230412/9cda7ed2-a0a2-426c-a027-d9f9cd107a43)

## 重现步骤
1. 打开：下载到本地后，使用图标，发现出现未知图标
2. 点击：
3. 出现：

## 相关信息（重要）
- 发生问题的 URL：还是本地项目，暂无URL
- iconfont 的用户昵称：cx_QAQ
- iconfont 项目 ID：8d9223531038-4359127

## 相关文件（重要）

```svg
<svg t="1702276043075" class="icon" viewBox="0 0 1024 1024" version="1.1" xmlns="http://www.w3.org/2000/svg" p-id="2280" width="200" height="200"><path d="M800 32a128 128 0 0 1 128 128v715.264a128 128 0 0 1-189.312 112.384l-165.376-90.24a128 128 0 0 0-122.624 0l-165.376 90.24A128 128 0 0 1 96 875.264V160a128 128 0 0 1 128-128h576z m-158.016 260.032c-46.464 0-100.864 52.672-129.984 86.656-29.12-33.984-83.52-86.656-129.984-86.656-82.304 0-130.048 64.192-130.048 145.92 0 90.432 86.72 186.24 260.032 287.36 173.312-101.12 260.032-195.008 260.032-281.6 0-81.728-47.744-151.68-130.048-151.68z" fill="#C9CDD4" p-id="2281"></path></svg>
```

## 平台/浏览器版本（重要）
- 操作系统及版本：win11专业版 10.0.22621

- 浏览器名称及版本：

**Comment by kirk-ye** [comment]
你可以在下载后，直接在先在本地预览所有图标是否正常展现。
在项目中查看是否引用url错误导致。
