### ISSUE TITLE
[Help] 无法登陆！github授权 或者 登录账号 都没有反应

### ISSUE THREAD

**Issue by Taoqun** [thx/iconfont-plus#2587]
## 问题描述
网站无法登录，github授权 或者 登录账号 都没有反应

下载 图标，就提示登录，登录后也没反应，还是提示需要登录。

**Comment by yisibl** [comment]
请提相关页面的截图和账号昵称。

**Comment by Taoqun** [comment]
账号：13120905628
使用账号登录 或者 github 授权 均不成功。

视频地址：https://aawsfukmrc.feishu.cn/docx/B5MadAVqyopWp3xR49tcYHDNnRe?from=from_copylink

**Comment by yisibl** [comment]
很奇怪，你的三方登录里为啥没有微信登录，这是什么浏览器，禁用掉浏览器插件在隐身模式下试试？

正常的登录这里有微信登录。
![image](https://github.com/thx/iconfont-plus/assets/2784308/f3d7af9d-807c-4ca7-af16-a4b86de1be9e)

**Comment by Taoqun** [comment]
打开隐私模式，会展示微信登录，但是扫码登录，依然失败。

**Comment by yisibl** [comment]
看一下 DevTools 是否有什么报错

**Comment by Taoqun** [comment]
DevTools 也没有报错；

而且发现，第一次登录框有微信按钮，第二次的登录框没有微信按钮了。可以看下在线文档，我都录了视频

视频地址：https://aawsfukmrc.feishu.cn/docx/B5MadAVqyopWp3xR49tcYHDNnRe?from=from_copylink

**Comment by yisibl** [comment]
很抱歉，我们排查一下

**Comment by yisibl** [comment]
修复了，请再试一下。

**Comment by Taoqun** [comment]
好了！
