### ISSUE TITLE
[Help]无法登陆，使用第三方登录或者账号密码登录后，依然无法登陆

### ISSUE THREAD

**Issue by wp901901** [thx/iconfont-plus#2588]
## 问题描述
每次登录依然是未登录状态，下载图片就提示去登录！

**Comment by gplcn** [comment]
同样问题

**Comment by Jimu-1996** [comment]
同样问题

**Comment by Taoqun** [comment]
登录相关，相同问题，好几天了。

**Comment by yisibl** [comment]
使用哪种方式登录的？登录后有什么错误提示吗？请提供截图和相关账号昵称。

**Comment by wp901901** [comment]
> 使用哪种方式登录的？登录后有什么错误提示吗？请提供截图和相关账号昵称。

第三方使用微博登录和账号密码登录都不行，没有错误提示，登录之后跳转回页面之后依然是未登录状态。账号昵称：-鹏鹏喂

**Comment by Taoqun** [comment]
账号：13120905628
使用账号登录 或者 github 授权 均不成功。

视频地址： https://aawsfukmrc.feishu.cn/docx/B5MadAVqyopWp3xR49tcYHDNnRe?from=from_copylink

**Comment by 18013863921** [comment]
18013863921同样的问题麻烦解决一下

**Comment by yisibl** [comment]
很抱歉，我们排查一下

**Comment by yisibl** [comment]
修复了，请再试一下。
