### ISSUE TITLE
之前上传了有色的图标，但是后期想把之前上传的图标改为去色，怎么弄

### ISSUE THREAD

**Issue by QinnnnnnnnngCao** [thx/iconfont-plus#2598]
## 问题描述
之前上传了的图标是有色的，后期需要把图标改为去色的，这个怎么改
能在上传已有的图标上改么

## 相关截图
![20240223113215](https://github.com/thx/iconfont-plus/assets/160990454/4df22f71-08cc-432a-9489-e10c31bfa463)

**Comment by yisibl** [comment]
![image](https://github.com/thx/iconfont-plus/assets/2784308/8fd460fc-6dc7-4920-8f78-f72288f2453a)
可以使用「批量去色」功能。
