### ISSUE TITLE
[Help]中国地图图标不让使用了吗？为什么审核被拒绝？

### ISSUE THREAD

**Issue by zzsssssss** [thx/iconfont-plus#2599]
## 问题描述
上传自己的地图图标，审核拒绝
## 相关截图
![image](https://github.com/thx/iconfont-plus/assets/82629043/81e4d3ce-8850-49aa-872b-2f258ccd106c)

**Comment by yisibl** [comment]
根据国家法律法规规定，地图应当规范使用，为免争议，建议通过官方渠道下载、获取地图图标，平台暂不支持上传。
