### ISSUE TITLE
图标颜色改变失败

### ISSUE THREAD

**Issue by Lizekun123** [thx/iconfont-plus#260]
保存到项目后，然后修改颜色，再生成在线链接，页面加载出来还是灰色，没有颜色，求助

**Comment by purplebamboo** [comment]
如果是下载的我们的demo。。只有symbol的应用方式才能有彩色哈。。另外两种是字体 不支持多色的哈

**Comment by Lizekun123** [comment]
好吧  意思就是在线的不支持改变颜色么   只能下载么

**Comment by purplebamboo** [comment]
在线的也支持的哈 一样的  三种使用方式   只有symbol的支持彩色图标

如果你不是指代码应用 只是说平台显示 那么在平台里是可以编辑图标修改颜色的

**Comment by Lizekun123** [comment]
symbol 是什么

**Comment by purplebamboo** [comment]
是一种 新的使用方式哈

目前在项目里有 unicode  fontclass  symbol三种运用方式哈。

你可以下载到本地 看下三个demo

**Comment by Lizekun123** [comment]
谢谢  好的  我看看


发自网易邮箱大师
在2016年12月13日 20:27，purplebamboo 写道:

是一种 新的使用方式哈

目前在项目里有 unicode fontclass symbol三种运用方式哈。

你可以下载到本地 看下三个demo
