### ISSUE TITLE
[Help]历史记录图标 审核拒绝

### ISSUE THREAD

**Issue by sszzl** [thx/iconfont-plus#2608]
## 问题描述
历史记录图标 审核拒绝

## 相关截图
![image](https://github.com/thx/iconfont-plus/assets/83052212/d01a0827-87c2-4d5a-ba75-e6277fe02ebb)
![image](https://github.com/thx/iconfont-plus/assets/83052212/baedfa5e-be5b-4a8f-b37f-349e5c777202)

**Comment by 758060714** [comment]
这个审核机制很迷啊，我调整了很多次都不行

**Comment by sszzl** [comment]
无奈了，重新做一个上传还是有问题

**Comment by sengoku-f** [comment]
我也是，这个图标上传失败，垃圾的一匹

**Comment by yixinyou123** [comment]
你最后怎么处理的

**Comment by yisibl** [comment]
目前机器审核可能存在一定的误识别，我们会尽快优化模型。

**Comment by yisibl** [comment]
已经进行了一些优化，请再试试。
