### ISSUE TITLE
字体文件整体导入

### ISSUE THREAD

**Issue by DevinXian** [thx/iconfont-plus#261]
之前一直使用的`fontello`，可以将已下载字体文件svg导入网站，然后添加额外的图标，重新打包下载，即使之前字体库不存在也非常方便。现在另一个小组用的`iconfont`，且字体库确实不知道谁弄的，很久了...不知道是否提供了将已下载字体svg整体导入的功能；遍寻各个入口，没找到

**Comment by purplebamboo** [comment]
目前没有这个功能哎。。。
