### ISSUE TITLE
[Help]项目上传了很多图标，唯独这几个一直审核不通过，怎么弄啊

### ISSUE THREAD

**Issue by yixinyou123** [thx/iconfont-plus#2614]
## 相关截图
<img width="1181" alt="image" src="https://github.com/thx/iconfont-plus/assets/88841186/049281c5-8692-4266-8b64-c5a166d98b22">

**Comment by JULYsun** [comment]
我也想问 一个图标如何色情暴力恐吓，这个info跟图标不通过根本没关系

**Comment by yisibl** [comment]
目前机器审核可能存在一定的误识别，我们会尽快优化模型。

**Comment by Ken20220212** [comment]
> 我也想问 一个图标如何色情暴力恐吓，这个info跟图标不通过根本没关系

你的问题解决了吗？我也遇到同样的情况

**Comment by uyoungco** [comment]
同样问题 拜托了

**Comment by yisibl** [comment]
近期对审核模型进行了一些优化，可尝试重新上传。如还有问题，请新增 issue 反馈。
