### ISSUE TITLE
iconfont.cn 页面很容易崩掉

### ISSUE THREAD

**Issue by huarse** [thx/iconfont-plus#2615]
现在随便操作一下都会报错，或者页面一刷新，就会出现以下界面：

<img width="1075" alt="image" src="https://github.com/thx/iconfont-plus/assets/3724927/3d284ae0-5f5a-464f-b8b7-c7888c7159a6">

账号：阿里域账号

**Comment by yisibl** [comment]
现在应该好了吧

**Comment by huarse** [comment]
后来好了，看来刚好在发布吧
