### ISSUE TITLE
我在a账号的项目里有100多个icon，把我的项目下载下来生成了换一个html文件，我如何拿着这个文件，上传到b账号新项目从而把这个项目恢复到原来100个icon且可编辑的地步呢？

### ISSUE THREAD

**Issue by jasonZhang1990** [thx/iconfont-plus#2630]
我在a账号的项目里有100多个icon，
把项目下载下来生成了换一个html文件，
我如何拿着这个文件，上传到b账号新项目从而把这个项目恢复到原来100个icon且可编辑的地步呢？
新项目只能上传单个icon，无法把生成的js文件直接上传。
请问有什么办法么？

**Comment by yisibl** [comment]
可以将 A 账号的项目转让给 B。
![image](https://github.com/thx/iconfont-plus/assets/2784308/308d90c1-4e06-4a9e-be43-c001cc200129)

**Comment by jasonZhang1990** [comment]
A账号是别人的，不同意转让，那就没有办法了吧？

**Comment by yisibl** [comment]
那得和他商量了，理论上肯定要取得他的授权。
