### ISSUE TITLE
标题请简明扼要，具体内容写在下面

### ISSUE THREAD

**Issue by gh20200861232** [thx/iconfont-plus#2632]
## 问题描述
http://www.iconfont.cn/ 网站访问失败

## 截图
---------------------------------------------------------
![20240511150523](https://github.com/thx/iconfont-plus/assets/92374766/f5eff1b1-c587-4190-8d27-b55cc937c137)
---------------------------------------------------------

## 重现步骤
访问iconfont.cn页面显示失败，加载图标也是，提示 Error！

## 期望结果
正常访问

## 相关信息
- 操作系统及版本：
macOS 13.5 (22G74)
- 浏览器名称及版本：
Google Chrome 版本 124.0.6367.201（正式版本） (arm64)

**Comment by gh20200861232** [comment]
有时候显示出来有时候又加载失败

**Comment by yisibl** [comment]
现在可以了。
