### ISSUE TITLE
网站报错，多出地方报502

### ISSUE THREAD

**Issue by liaoyuyu** [thx/iconfont-plus#2633]
## 问题描述
  项目设置，生成GUID的时候报了个错，没在意，然后取消勾选彩色，然后保存后就各种502了
## 重现步骤
1. 打开：项目设置
2. 点击：生成GUID报错，取消彩色
3. 出现：各种ERROR 报错

## 相关信息（重要）
- 发生问题的 URL：https://www.iconfont.cn/manage/index?spm=a313x.manage_type_myprojects.i1.db775f1f3.674b3a8145Qne7&manage_type=myprojects
- iconfont 的用户昵称：
- iconfont 项目 ID：

**Comment by yisibl** [comment]
现在可以了。
