### ISSUE TITLE
资源管理-我的项目打不开，接口请求不成功

### ISSUE THREAD

**Issue by Ourydy** [thx/iconfont-plus#2635]
## 重现步骤
1. 打开：资源管理
2. 点击：我的项目
3. 出现：
![image](https://github.com/thx/iconfont-plus/assets/104473720/00b426a5-1603-4d7d-8fa9-5802d8ce06af)

![image](https://github.com/thx/iconfont-plus/assets/104473720/eee08683-aca6-46d8-93b4-ca27098162e5)

## 相关信息（重要）
- 发生问题的 URL：https://www.iconfont.cn/manage/index?spm=a313x.manage_type_myicons.i3.22.289c3a81TSytQB&manage_type=myprojects
- iconfont 的用户昵称：
- iconfont 项目 ID：

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：window 11

- 浏览器名称及版本：Google Chrome版本 124.0.6367.60

**Comment by kuaidy** [comment]
+1

**Comment by yisibl** [comment]
这会可以了吗

**Comment by MerlinAhh** [comment]
+1
