### ISSUE TITLE
明明登录了，咋下载图标库提示需要登录。

### ISSUE THREAD

**Issue by chris573** [thx/iconfont-plus#264]
{"code":500,"message":"LOGIN REQUIRED"}

PS：
改版可以直接页面上编辑尺寸、位移，设置颜色，很棒啊！
谢谢大伙

**Comment by purplebamboo** [comment]
亲 你是用的什么浏览器？

是下载图标库里的图标吗？

可以截图给我们看看不？

**Comment by hanfenjin** [comment]
{"code":500,"message":"LOGIN REQUIRED"}怎么回事

**Comment by chris573** [comment]
你好，
我用谷歌浏览器，退出账号重新登录，或者换浏览器登录下载图标库，都一样报错。同事一样的wifi下就不会。好几次中偶尔可以下载图标库，大多数提示错误；
win10 x64；今天谷歌chrome下载依旧报错，换火狐可以下载
[cid:_Foxmail.1@701c080a-0f59-c8ba-f867-f9805f532147] 谢谢平台，新版很好

________________________________
qi573@live.cn

发件人： purplebamboo<mailto:notifications@github.com>
发送时间： 2016-12-15 16:02
收件人： thx/iconfont-plus<mailto:iconfont-plus@noreply.github.com>
抄送： chris573<mailto:qi573@live.cn>; Author<mailto:author@noreply.github.com>
主题： Re: [thx/iconfont-plus] 明明登录了，咋下载图标库提示需要登录。 (#264)

亲 你是用的什么浏览器？

是下载图标库里的图标吗？

可以截图给我们看看不？

―

**Comment by chris573** [comment]
换浏览器试试，我就是换浏览器，偶尔可以下载

________________________________
qi573@live.cn

发件人： hanfenjin<mailto:notifications@github.com>
发送时间： 2016-12-17 10:50
收件人： thx/iconfont-plus<mailto:iconfont-plus@noreply.github.com>
抄送： chris573<mailto:qi573@live.cn>; Author<mailto:author@noreply.github.com>
主题： Re: [thx/iconfont-plus] 明明登录了，咋下载图标库提示需要登录。 (#264)

{"code":500,"message":"LOGIN REQUIRED"}怎么回事

**Comment by purplebamboo** [comment]
@chris573  奇怪 我这边一直无法复现，我再排查下，亲可以提供下 chrome的版本号吗？


另外 麻烦亲清空缓存再下载试试？

**Comment by chris573** [comment]
Chrome 版本 55.0.2883.75 m
win x64


________________________________
qi573@live.cn

发件人： purplebamboo<mailto:notifications@github.com>
发送时间： 2016-12-19 17:57
收件人： thx/iconfont-plus<mailto:iconfont-plus@noreply.github.com>
抄送： chris573<mailto:qi573@live.cn>; Mention<mailto:mention@noreply.github.com>
主题： Re: [thx/iconfont-plus] 明明登录了，咋下载图标库提示需要登录。 (#264)

@chris573<https://github.com/chris573> 奇怪 我这边一直无法复现，我再排查下，亲可以提供下 chrome的版本号吗？

另外 麻烦亲清空缓存再下载试试？

**Comment by chris573** [comment]
你好，我下载图标库总有问题，之前反馈过的问题，还是出现了。 定制图标，下载提示错误，换浏览器、清除cookie重新登录、甚至重启机子，都还是这问题。希望你们重视下[cid:_Foxmail.1@08427c3a-b5c3-9af9-599d-6788cfdf2201][cid:_Foxmail.1@aed91942-e0e1-0dd8-9022-8ef081621221]

附上截图这次[cid:_Foxmail.1@aab3707e-3c36-62e3-6eeb-e1f781349362]

[cid:_Foxmail.1@face3399-c5d8-7e14-7e65-e156a70b9e56]

{"code":500,"message":"LOGIN REQUIRED"}

________________________________
qi573@live.cn

发件人： qi573@live.cn<mailto:qi573@live.cn>
发送时间： 2016-12-21 10:37
收件人： thx/iconfont-plus<mailto:reply@reply.github.com>
主题： Re: Re: [thx/iconfont-plus] 明明登录了，咋下载图标库提示需要登录。 (#264)
Chrome 版本 55.0.2883.75 m
win x64


________________________________
qi573@live.cn

发件人： purplebamboo<mailto:notifications@github.com>
发送时间： 2016-12-19 17:57
收件人： thx/iconfont-plus<mailto:iconfont-plus@noreply.github.com>
抄送： chris573<mailto:qi573@live.cn>; Mention<mailto:mention@noreply.github.com>
主题： Re: [thx/iconfont-plus] 明明登录了，咋下载图标库提示需要登录。 (#264)

@chris573<https://github.com/chris573> 奇怪 我这边一直无法复现，我再排查下，亲可以提供下 chrome的版本号吗？

另外 麻烦亲清空缓存再下载试试？
