### ISSUE TITLE
原手机号同学离职了，需要替换手机号，原先账号上不去了，原账号：winbaoxian2016@163.com，如果是直接替换手机号，新号码：19012803659；如果是需要图标迁移的话新账号也是19012803659这个手机号注册的，昵称保险师UED，麻烦帮忙解决下，谢谢~

### ISSUE THREAD

**Issue by jennyloewe** [thx/iconfont-plus#2640]
## 截图

<img width="713" alt="image" src="https://github.com/thx/iconfont-plus/assets/7698333/d7ae05d0-c3a2-4bbe-b3aa-2fabe76b2a99">

## 重现步骤
1. 打开：登录
2. 点击：登录
3. 出现：登录验证，选择使用“其他号码验证"，无响应猜测链接失效了

## 期望结果
项目及icon资产迁移，或账号手机号重新绑定

## 相关信息（重要）
- 发生问题的 URL：https://passport.weibo.com/protection/index?token=2NjJmRyAVAFBskshKWE0LnvKKcw1AyoM9CnByb3RlY3Rpb24.&callback_url=https%3A%2F%2Fapi.weibo.com%2Foauth2%2Fauthorize%3Ftime%3D1715937282922%26sign%3D3d5bc7ee2fe0ab80709a784d25567af2%26client_id%3D1283124999%26redirect_uri%3Dhttps%253A%252F%252Fwww.iconfont.cn%252Fapi%252Flogin%252Fweibo%252Fcallback%26state%3Dplus-login
- iconfont 的用户昵称:保险师
- iconfont 项目 ID：[winbaoxian2016@163.com](mailto:winbaoxian2016@163.com)

## 相关文件（重要）

```svg

```

## 平台/浏览器版本（重要）
- 操作系统及版本：

- 浏览器名称及版本：

**Comment by yisibl** [comment]
联系一下离职同学做一下账号转让吧。
