### ISSUE TITLE
[Help]以前的同事把项目图标库转让我的时候，不小心在我的用户名后面加了个0，结果转错用户了，她也没有权限再转给我了，能帮我处理下吗

### ISSUE THREAD

**Issue by Arya1-0** [thx/iconfont-plus#2644]
以前的同事把项目图标库转让我的时候，不小心在我的用户名后面加了个0，结果转错用户了，她也没有权限再转给我了，能帮我处理下吗

**Comment by Arya1-0** [comment]
![WeChat105bf9ffea002138edbd45df7149deab](https://github.com/thx/iconfont-plus/assets/170999323/9e6fac79-7183-4b2e-a9bc-9be7bace7070)
![WeChat20b26279eae2c6942d91f7294a7b07c2](https://github.com/thx/iconfont-plus/assets/170999323/759f748a-0b68-4abc-959d-49c5d2b694f9)

**Comment by yisibl** [comment]
如钉钉沟通，已经处理。
