### ISSUE TITLE
unicode方式接入，图标色彩丢失，只显示黑色，希望原色展示

### ISSUE THREAD

**Issue by tangtang09** [thx/iconfont-plus#2645]
## 问题描述
将图标文件下载本地，使用后，图标全部显示黑色

## 相关截图
![image](https://github.com/thx/iconfont-plus/assets/83819365/b1b4e3c6-9c5c-495f-9fef-82ae16776fd9)<img width="835" alt="image" src="https://github.com/thx/iconfont-plus/assets/83819365/2b55a62d-e9ec-4661-aba1-043869216e86">![image](https://github.com/thx/iconfont-plus/assets/83819365/50d0a791-f1f9-4e71-8d6e-81c9460fa647)

**Comment by yisibl** [comment]
这个项目彩色图标个数超过 40 个了，目前最多只支持 40 个。
