### ISSUE TITLE
下下来的字体包 小米手机上读不出来，求解！急！

### ISSUE THREAD

**Issue by shenjiejun** [thx/iconfont-plus#265]

**Comment by purplebamboo** [comment]
是我们平台下载下来的demo在小米手机打不开？

是小米几  什么浏览器  
是否其他手机都没问题 只有小米有问题？

麻烦场景再说清楚一点哈。。。

**Comment by shenjiejun** [comment]
刚刚知乎上看了下 [有人也提了这个问题 暂时发现在小米手机上，用微信自带浏览器打开的网址，上面的iconfont图标都不会显示，微信浏览器是QQ浏览器，X5内核。换一下文件加载顺序什么的，都已经试过了，也没生效

**Comment by shenjiejun** [comment]
https://www.zhihu.com/question/36898167

**Comment by purplebamboo** [comment]
试过小米原生浏览器吗？

方便的话最好给个测试demo我等会儿开完会就去试下哈。。

**Comment by purplebamboo** [comment]
另外 亲是直接用的本地字体？

你要用线上字体呀，可以用我们的cdn地址

我怀疑可能微信不允许直接用本地字体。。你可以先尝试下哈。。

**Comment by shenjiejun** [comment]
恩 线上字体的cnd 地址是什么

**Comment by shenjiejun** [comment]
找到了

**Comment by shenjiejun** [comment]
我先试试

**Comment by purplebamboo** [comment]
额 在项目里  点击那个查看在线链接 里面有把demo里的换掉

**Comment by purplebamboo** [comment]
另外本地起个服务哈，

**Comment by shenjiejun** [comment]
好了好了 可以了 谢谢啊！
