### ISSUE TITLE
[Help]绑定的手机号已经注销，如何换绑手机号

### ISSUE THREAD

**Issue by SingleSteven** [thx/iconfont-plus#2652]
## 问题描述
之前绑定的手机号注销了，现在该如何换绑手机号？

**Comment by omoxop** [comment]
问题应该有很多人遇到，不解决吗？绑定那么多平台没有作用？账号机制如果下一任号主直接上来注销，账户还真能删成功。赶紧处理吧，比什么其他活动来说，账户安全性才是本质工作

**Comment by yisibl** [comment]
感谢反馈，我们看看如何优化。

**Comment by yisibl** [comment]
请发送邮件到 `iconfont@list.alibaba-inc.com` 申请人工审核，邮件中需要包含以下信息：

### 必填信息

- 你的 iconfont 个人主页链接（点击右上角头像下拉菜单中的个人主页，然后复制浏览器地址栏中的链接）<br>
  <img width="200" src="https://img.alicdn.com/imgextra/i2/O1CN010SWzjj28R4zIOGJy0_!!6000000007928-0-tps-402-454.jpg">
- 原手机号
- 新手机号（请确保可以收到验证码，并且**未绑定到其他 iconfont 账号**）
- **原手机号入网证明**（入网证明需线下前往营业厅办理）或者原手机号至少 6 个月的**话费缴纳记录**（可以是支付宝等充值付款截图）
- 目前是否能登录 iconfont
- 是否绑定了三方帐户（即能否用微信、GitHub 或新浪微博登录）
- 身份证正反面照片

### 可选信息

- 尽量列举你的常用设备信息，常用登录地点
- 最后一次登录时间、地点
- 其他你想补充的可以证明的资料

**Comment by liyouzhuo** [comment]
> 请发送邮件到 `iconfont@list.alibaba-inc.com` 申请人工审核，邮件中需要包含以下信息：
> 
> ### 必填信息
> * 你的 iconfont 个人主页链接（点击右上角头像下拉菜单中的个人主页，然后复制浏览器地址栏中的链接）
>   <img alt="" width="200" src="https://camo.githubusercontent.com/3fbfcc7b3c677ec9a53cedef14d17d4872e1fa76357d9310601862dcd99fa367/68747470733a2f2f696d672e616c6963646e2e636f6d2f696d6765787472612f69322f4f31434e30313053577a6a6a323852347a494f474a79305f2121363030303030303030373932382d302d7470732d3430322d3435342e6a7067">
> * 原手机号
> * 新手机号（请确保可以收到验证码，并且**未绑定到其他 iconfont 账号**）
> * **原手机号入网证明**（入网证明需线下前往营业厅办理）或者原手机号至少 6 个月的**话费缴纳记录**（可以是支付宝等充值付款截图）
> * 目前是否能登录 iconfont
> * 是否绑定了三方帐户（即能否用微信、GitHub 或新浪微博登录）
> * 身份证正反面照片
> 
> ### 可选信息
> * 尽量列举你的常用设备信息，常用登录地点
> * 最后一次登录时间、地点
> * 其他你想补充的可以证明的资料

很好奇，这里要身份证正反面是做什么？为什么不能参考下其他平台的换绑手机号机制，没有别的意思只是觉得这个因为之前手机号注销现在换绑感觉流程很麻烦
