### ISSUE TITLE
想要一个邀请链接长期有效的功能

### ISSUE THREAD

**Issue by blueting777** [thx/iconfont-plus#2658]
## 需求背景
目前邀请链接有效期只有7天，很多项目开发都是在七天后甚至更久才开始项目，那时的邀请链接就失效了，又需要重新发链接，感觉很麻烦。

## 解决方案
每次项目对应的也是不同的开发，没办法提前预知开发人员，无法提前加成员，希望可以设置一个长期有效的链接，这样开发就不会看到失效的链接了。

## 相关截图
![image](https://github.com/user-attachments/assets/ebd9d4b7-3cb5-4645-8c53-329ebbadb229)

**Comment by yisibl** [comment]
设置有效期是基于安全性考虑的，防止邀请链接泄露后任何人都可以加入。目前来看，我们可以适当延长邀请链接的有效期。

**Comment by blueting777** [comment]
嗯嗯，理解，延长一些对于我们来说是很需要的，有效期一个月也可以~

**Comment by yisibl** [comment]
已延长为 15 天

**Comment by blueting777** [comment]
太好了，谢谢你们，辛苦了~
