### ISSUE TITLE
请求获取网站全部IP地址

### ISSUE THREAD

**Issue by If-Freedom** [thx/iconfont-plus#2659]
<br class="Apple-interchange-newline">
</body>
</html>你好，我们单位想做安全防护，通过防火墙做应用白名单，但防火墙策略只能添加IP地址，想获取阿里巴巴图标库全部IP地址，加到防火墙白名单里面。可以让阿里巴巴图标库网页正常使用。

通过nslookup域名[www.iconfont.cn解析出](http://www.iconfont.xn--cn-5c5cr23fjh3b/)IP地址是下面这些，但是加到防火墙里面，网页无法打开，我获取的IP地址不全，请求获取一下全部的网站服务器IP地址，达到网站通过域名正常访问。联系方式18643161194

59.82.23.55

59.82.23.156

59.82.23.37

59.82.31.200

59.82.23.172

59.82.23.111

106.11.208.185

106.11.211.252

106.11.211.253

110.75.67.92

110.75.96.115

140.205.243.70

140.205.34.99

203.119.245.10

203.119.245.8

203.119.245.9

42.156.210.47

59.82.23.146

59.82.23.172

59.82.23.63

59.82.31.142

59.82.31.179

59.82.31.201

59.82.31.215

59.82.31.216

59.82.31.141

59.82.62.66

59.82.62.67

**Comment by yisibl** [comment]
IP 地址可能会变化，你可能需要根据域名来做白名单而非 IP。
