### ISSUE TITLE
织梦本地测试可以正常显示iconfont字体图标，但是上传服务器之后图标字体就显示不出来，变成了一个一个方框

### ISSUE THREAD

**Issue by dxccms** [thx/iconfont-plus#266]
今天写一个专题页，html能显示图标，本地织梦环境也能显示，但是上传到服务器之后就显示不出来了，全部变成了方框，苹果手机可以正常显示iconfont字体，安卓显示不出来，消失不见了

**Comment by dxccms** [comment]
字体的引用路径没有问题，检查了n多边

**Comment by purplebamboo** [comment]
变成方框证明字体没加载。。。建议使用我们的cdn地址哈。。

你这个应该去织梦论坛问问哈。。
