### ISSUE TITLE
图标使用的时候与上传的图标不一致

### ISSUE THREAD

**Issue by DeerAndMan** [thx/iconfont-plus#2664]
## 问题描述
UI在AI软件中制作了一个图标上传，之后在项目中使用的时候与原svg文件样式不一致。

## 相关截图
原始图
![学生(2)](https://github.com/user-attachments/assets/dd21c967-ff03-4156-a829-dcdb81567253)
[学生(2).svg.zip](https://github.com/user-attachments/files/16262383/2.svg.zip)

问题图
![image](https://github.com/user-attachments/assets/cee799bc-0c14-407d-b97a-4cfc1f1797a5)

设计图 .ai 文件
[学生.ai.zip](https://github.com/user-attachments/files/16262322/ai.zip)

**Comment by yisibl** [comment]
我这边上传到 iconfont 是可以的

![image](https://github.com/user-attachments/assets/8c6f4d3c-0dfe-4486-a3ce-1a782f5b411b)
