### ISSUE TITLE
图标上传后使用的时候是一团，透明度没有体现

### ISSUE THREAD

**Issue by DeerAndMan** [thx/iconfont-plus#2665]
## 问题描述
文件去除颜色上传后显示的是一团黑色的。不管设置什么颜色都是一块修改的，正常情况下应该是透明度不一样的。这种情况的图标要怎么修改？

#设置
![image](https://github.com/user-attachments/assets/c92b2c8b-f237-4326-af07-78239eed5a75)
![image](https://github.com/user-attachments/assets/9379bd7b-7626-43ee-983e-b80e20689e50)

## 相关截图
# 效果
![2611721642019_ pic](https://github.com/user-attachments/assets/0588d878-7502-4376-a867-be7ce1f651ae)
<img width="339" alt="image" src="https://github.com/user-attachments/assets/b5cd7ae0-0c5b-4fb5-aec9-9ba53cd3c2da">

##错误
![2591721641979_ pic](https://github.com/user-attachments/assets/95c7faf3-5ffd-475d-b7b8-c09a118d582c)
![image](https://github.com/user-attachments/assets/05420a82-5db1-42c5-a1b6-c5f9c29adbde)

## 原始文件：
![聊天](https://github.com/user-attachments/assets/7d75fe96-5063-432b-a486-f5cec8f36202)
![分析报告](https://github.com/user-attachments/assets/f2ecae20-fca7-4198-a41a-5b4bca4dc7af)

**Comment by DeerAndMan** [comment]
刚刚看了下 #1937 等明天设计去试一下

**Comment by DeerAndMan** [comment]
设计还是说没办法达成效果，透明度这些无法设置。上传到另一项目中（保留颜色上传）能够还原设计但是无法改变颜色这些
![image](https://github.com/user-attachments/assets/a601877b-9ff2-47c9-b859-faf41f04ba2a)

**Comment by yisibl** [comment]
目前不支持带有透明度的 svg
