### ISSUE TITLE
字体无法下载至本地

### ISSUE THREAD

**Issue by HADB** [thx/iconfont-plus#267]
之前一直用得好好的，今天发现点击下载至本地没反应了，会跳转到一个新页面，但是并没有像以前那样弹出下载，试了好几次都不行，啥问题

**Comment by purplebamboo** [comment]
一般是  你加入了啥新icon导致整个项目生成出错。 可以二分法一个个的建立新项目检查下。

**Comment by HADB** [comment]
不是，我发现我之前所有的项目下载至本地的功能都用不了了

**Comment by purplebamboo** [comment]
亲  你的用户名发一下  我去看下。

**Comment by HADB** [comment]
邓斌HADB

**Comment by purplebamboo** [comment]
亲  我进去  挨个看了下   都可以下载。

是不是你浏览器的问题？  你现在用的什么浏览器。建议使用chrome哈。

另外可以找同事看看。

最后关闭所有插件，还有网络代理啥的。

**Comment by HADB** [comment]
ok，我试试

**Comment by HADB** [comment]
换了台mac，上面的chrome可以正常下载。之前那台windows上不管什么浏览器或者用不用代理都下不了，好奇怪。

**Comment by purplebamboo** [comment]
稍等 我去试下windows。

你也可以找同事的windows试试。

看看是不是  网络环境问题，比如防火墙啥的，翻墙代理啥的。

**Comment by purplebamboo** [comment]
你好亲  我用windows试了下  都没问题。

你下载失败具体是什么表现呢。

**Comment by HADB** [comment]
就是弹出一个about:blank的新页面，但是没有文件下载

**Comment by purplebamboo** [comment]
那有点像兼容性问题  麻烦看下

浏览器版本号。。。

**Comment by HADB** [comment]
版本 55.0.2883.87 m

**Comment by HADB** [comment]
找到了弹出下载页面的代码：

window.open("/api/project/download.zip?pid=" + e + "&ctoken=" + i.config().ctoken)

通过断点找到了地址：http://iconfont.cn/api/project/download.zip?pid=179944&ctoken=OxB3SuO3rnNKwygEXBuVicon-font

直接在chrome里面没办法打开，用迅雷可以下载，不过里面的内容是：
`{"code":500,"message":"LOGIN REQUIRED"}`

不知道是不是身份验证的问题。

**Comment by purplebamboo** [comment]
这个错误码的意思  是指  没有登陆。因为你直接用迅雷没有登陆信息的。

在chrome里面直接无法打开吗？ 就直接是空白页？


我待会儿去升级chrome是试下哈。

**Comment by purplebamboo** [comment]
55.0.2883.87 m  奇怪了  我的chrome也是这个版本

**Comment by purplebamboo** [comment]
直接输入也可以正常下载的。windows下面的chrome。

＝ ＝

**Comment by HADB** [comment]
我试了隐身窗口，也不行，应该也不会是插件导致的问题

**Comment by HADB** [comment]
过段时间我再试下看看。现在先直接用在线链接去下载了。

**Comment by HADB** [comment]
我记得以前下载是可以直接弹出迅雷下载，然后可以下载成功的，应该就是通过链接里的pid和ctoken去验证身份的吧？是不是什么原因导致我这个地方生成的pid和ctoken有问题，验证不通过了

**Comment by purplebamboo** [comment]
不是的 ，是否登陆，是根据cookie来的，跟这个ctoken没有关系。
很久很久以前我们下载是不需要登陆的，导致很多人刷，恶意攻击。所以后来做了限制。

你这个验证不通过，应该是登陆状态有问题，不过很奇怪，你既然已经可以在项目里了，肯定是登陆了。不应该还是会被卡住。

**Comment by HADB** [comment]
今天尝试发现Windows上已经可以正常下载，点击“下载至本地”会自动弹出迅雷下载，迅雷也可以正常下载，没有问题。
暂不清楚之前出现问题是什么原因导致。

**Comment by purplebamboo** [comment]
@HADB  最近并没有做任何改动，是这样的 我们的下载是需要登陆的。

我怀疑用迅雷下载可能丢失了啥信息。下次还有问题，可以尝试关闭迅雷，用普通的下载试试。

**Comment by HADB** [comment]
上次用普通下载也有问题。今天发现普通下载没问题了，直接弹出的迅雷下也没问题了。可能是电脑的问题吧……前段时间网络有些不稳定
