### ISSUE TITLE
希望在字体库中加入alibaba普惠体-数字字体，在数据设计中应用广泛

### ISSUE THREAD

**Issue by JULYsun** [thx/iconfont-plus#2670]
## 需求背景
数据产品开发中需要使用专用窄体等宽数字字体，例如alibaba普惠体数字版
## 解决方案
需要引入字体，方便使用，字体地址：

**Comment by yisibl** [comment]
请不要把内部资源发到外部，仅供内部使用，不对外商业授权

**Comment by JULYsun** [comment]
> 请不要把内部资源发到外部，仅供内部使用，不对外商业授权

内部iconfont链接跳转来的。另外内部客服联系过并无人回复。那内部iconfont的反馈渠道在哪里

**Comment by yisibl** [comment]
你联系壹丝
