### ISSUE TITLE
项目通过链接邀请功能无法使用

### ISSUE THREAD

**Issue by 0214ggyy** [thx/iconfont-plus#2673]
![image](https://github.com/user-attachments/assets/ab9d7d90-8931-4db0-bf77-6bb5da530ad0)

**Comment by yisibl** [comment]
感谢反馈，已解决。

**Comment by 0214ggyy** [comment]
在欢乐时，朋友们会认识我们；在患难时，我们会认识朋友。谢谢，来信！！！
