### ISSUE TITLE
首页的搜索框那么大为什么不能搜索

### ISSUE THREAD

**Issue by ioate** [thx/iconfont-plus#2676]
## 需求背景
首页进来之后一个大大的搜索框，点了半天发现是不能输入的，设计太反人类了，是BUG吗?

## 相关截图
![image](https://github.com/user-attachments/assets/0468bb7c-4a5e-4080-91df-c1d0f1931d21)

**Comment by embraceyouting** [comment]
![image](https://github.com/user-attachments/assets/a84cdbb1-f6d8-4a2d-8448-01339903e1cd)
可以搜索啊

**Comment by yisibl** [comment]
感谢反馈，已改进，现在整个红框范围内都可以点击

![image](https://github.com/user-attachments/assets/76e58843-5241-469e-929b-1c023de2c218)
