### ISSUE TITLE
能不能加一个可以搜索同一作者作品的功能，现在想找一套的图标太难了

### ISSUE THREAD

**Issue by 13964285005** [thx/iconfont-plus#2677]
## 需求背景
想找相同的，整套的icon图标

## 解决方案
能不能加一个可以搜索同一作者作品的功能，或者可以很轻松的找到同一套的图标作品

**Comment by yisibl** [comment]
1. 在搜索界面选中精选图标
![image](https://github.com/user-attachments/assets/ea511027-b556-4003-a10e-1af969d98ae2)
2. 在对应的图标上点击下载按钮
3. 在弹出的浮层右侧会有对应图标所属的图标库
![image](https://github.com/user-attachments/assets/3e861cd9-f4ae-4483-b10f-c56f964de285)
