### ISSUE TITLE
注册验证码校验有问题

### ISSUE THREAD

**Issue by Github-mfl** [thx/iconfont-plus#2680]
百分百复现，直接使用手机号注册，验证码一直错误错误错误

**Comment by fannofan** [comment]
我也是，这系统真的还有人在运营吗

**Comment by rnb-tron** [comment]
+1

**Comment by Asia-king** [comment]
这系统有人管吗，让登录，注册提示验证码错误

**Comment by yisibl** [comment]
请提供错误截图

**Comment by CocaStar** [comment]
<img width="808" alt="image" src="https://github.com/user-attachments/assets/3094bded-f447-47a0-a8b7-eeeff30dbfbf">
![Uploading 5141724667174_.pic.jpg…]()

**Comment by CocaStar** [comment]
@yisibl 
必现，已经持续一下午，麻烦处理下

**Comment by yisibl** [comment]
@CocaStar 我这边注册是好的，麻烦加我一下钉钉沟通：壹丝

**Comment by CocaStar** [comment]
@yisibl 重试了下依然不行，同时你的钉钉也搜不到用户，壹丝、yisibl、yisi都是搜不到

**Comment by yisibl** [comment]
@CocaStar 你的钉钉是多少，我联系你。

**Comment by wangluosheng666** [comment]
我也不行，同样的原因。钉钉号silverwolf666 ，大佬求解决



> @CocaStar 你的钉钉是多少，我联系你。

**Comment by fahaixxl** [comment]
+11111

**Comment by fahaixxl** [comment]
钉钉：seb4491，求大佬帮忙解决

**Comment by akingseu** [comment]
必现。。这都还没修复吗

**Comment by QiuRuiAng** [comment]
+1，能否尽快修复？非常感谢。

**Comment by harrison3306** [comment]
尝试了两天了，也是一直出现这个问题。包括微信扫码登录之后，再尝试绑定手机号，也出现同样的问题

**Comment by Github-mfl** [comment]
没人维护嘛
![image](https://github.com/user-attachments/assets/f5ed19f4-90c8-48b8-8b45-5c928de10b0a)

**Comment by CocaStar** [comment]
> @CocaStar

@yisibl 早上试了下还是不行，我的钉钉号是 1jw-2ij6l8bbad

**Comment by yisibl** [comment]
修复排查中，请稍后

**Comment by zgyin** [comment]
+1 
很多用户是从v2过来的吧

**Comment by yisibl** [comment]
感谢各位的反馈，已修复，请再试一下。
