### ISSUE TITLE
[Help]账号被冻结，怎么解冻或者帮我注销也行

### ISSUE THREAD

**Issue by xiemin2161** [thx/iconfont-plus#2685]
## 问题描述
手机号登录提示账号被冻结，也不知道为啥被冻结，也没有解冻方法，就是登录不进去，提供帮我注销的方法也行啊，大不了注销了重新申请，总不能为了一个账号重新办个手机号啊

**Comment by yisibl** [comment]
请提供账号信息

**Comment by xiemin2161** [comment]
18130012022












X-man🔥
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月19日(周四) 下午4:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [thx/iconfont-plus] [Help]账号被冻结，怎么解冻或者帮我注销也行 (Issue #2685)




 
请提供账号信息

**Comment by yisibl** [comment]
已经解冻了，该账号可能涉及违规素材或违规评论，请合理使用该账号。
