### ISSUE TITLE
点击购物车-下载代码无法下载

### ISSUE THREAD

**Issue by zhangxin0711** [thx/iconfont-plus#2689]
需要在购物车里批量下载图标代码，无法下载，控制台报错
![Uploading 微信截图_20240927163122.png…]()

**Comment by zhangxin0711** [comment]
![微信截图_20240927163122](https://github.com/user-attachments/assets/9553228c-021a-414d-aff4-74e07f8f0780)

**Comment by yisibl** [comment]
看起来是一次性下载太多了，超出了浏览器 URL 长度限制

**Comment by zhangxin0711** [comment]
不允许一次性下载太多吗?项目开发要求一次性下载很多图标，有其他解决办法吗？




Luminous
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "thx/iconfont-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月15日(星期二) 下午2:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [thx/iconfont-plus] 点击购物车-下载代码无法下载 (Issue #2689)





 
看起来是一次性下载太多了，超出了浏览器 URL 长度限制
