### ISSUE TITLE
hover复制 svg 的功能不见了

### ISSUE THREAD

**Issue by Elevenmiaomiao** [thx/iconfont-plus#2698]
## 需求背景
首页图标列表通过 hover 的形式复制 SVG 的功能很好用，但不见了。此功能对于设计师和交互设计师的用途非常大。

## 解决方案
希望可以通过设置配置首页hover出现的快捷功能，目前只能修改本地 redis 实现。

## 相关截图
<img width="230" alt="image" src="https://github.com/user-attachments/assets/74cf1b00-faea-4d83-b715-dd1ccc86dda9">
<img width="163" alt="image" src="https://github.com/user-attachments/assets/9df52992-c02a-429a-8a4a-cd221b0e66a1">

**Comment by yisibl** [comment]
点击下载![image](https://github.com/user-attachments/assets/3c3178d4-05b1-456e-a9ab-2107237aecb3)按钮，在打开的对话框中有复制 SVG 按钮。

![image](https://github.com/user-attachments/assets/b1e38536-a38f-437e-bc3d-01093d5bf75b)
