### ISSUE TITLE
交互/体验建议

### ISSUE THREAD

**Issue by xiaonan101** [thx/iconfont-plus#27]
1.鼠标悬停图标效果（半透明浮层上有功能按键），个人觉得以前的交互样式比较好，理由：能看见被选择的图标。
2.中英文切换图标意思不明显，建议可否尝试用旗帜等。
3.用户退出没有确认提示弹出框，直接就退了。
4.图标下载历史没有删除或清除功能。
明天继续玩耍~ 不要嫌我烦哦  我也是来学习的 嘻嘻

**Comment by Muqing1221** [comment]
不会不会，谢谢亲的宝贵的反馈~
iconfont每天见~iconfont天天见~~

**Comment by purplebamboo** [comment]
1. 感谢亲的建议，鼠标悬停的 我们也考虑了好久，这个  我们后期会再考虑的。如果反馈的人多的话 ，我们会考虑修改的。目前可能是刚切过来，使用上有点不习惯
2. 这个我们头部都是一种视觉，就是比较简单的icon。用旗帜反而不明显呢。
3. 哈。这个确认框感觉没有太大必要，我们的登陆成本很低。而且基本上是不用退出的。
4. 这个建议可以，我明天找下设计师加上清空的交互。
