### ISSUE TITLE
用github授权登录好像一直登录不上去

### ISSUE THREAD

**Issue by guomindong** [thx/iconfont-plus#270]
用github授权登录好像一直登录不上去

**Comment by purplebamboo** [comment]
一般是网络不行，国内环境你懂的。会超时啥的。＝ ＝

**Comment by guomindong** [comment]
我单独登录github的时候速度蹭蹭的，没毛病

**Comment by purplebamboo** [comment]
因为两个不一样呀，一个是github直接登陆  一个是第三方的授权登陆。

囧  亲可以 换个网络，或者用微博登陆。

最后 我有时间把这个超时时间再设置的大点。
