### ISSUE TITLE
Iconfont上传icon丢失图形

### ISSUE THREAD

**Issue by ccccccccmax** [thx/iconfont-plus#2700]
我的图形导出svg后，上传至iconfont，发现丢失了部分图形，这个问题已经持续几个月。

我的联系方式：内网搜“听絮”。

PS：这个反馈渠道不能上传图片，不能清晰地描述问题，比如下面这个👇
![Uploading 截屏2024-11-06 16.34.44.png…]()

**Comment by yisibl** [comment]
已线下沟通，这是 masergo 的默认填充问题。
