### ISSUE TITLE
如何生成手机app用的彩色的iconfont

### ISSUE THREAD

**Issue by tofrookie** [thx/iconfont-plus#272]
如题，需要彩色的手机app用的ttf

**Comment by purplebamboo** [comment]
是这样的亲，字体ttf不支持多色的，你把项目里的demo下载到本地里面有介绍的。

symbol的方式也只能用在  移动端的h5. native的方式是无法用的哈。

native用的话只能 内嵌webview  或者  直接用我们平台下载  png图标哈。
