### ISSUE TITLE
项目另存为功能

### ISSUE THREAD

**Issue by kingyang** [thx/iconfont-plus#274]
多个项目可能会公用部分图标,但也会有差异,这样可以快速新建项目. 谢谢!!

**Comment by purplebamboo** [comment]
这个 我们考虑下哈。

项目里有全选功能，我们增加个一键加入购物车，是不是可以解决这个问题？

因为我理解公用的部分，本身还要做些筛选。

**Comment by kingyang** [comment]
谢谢答复!
一键加入购物车基本上可以满足需要,也相对会更为灵活一点(可以解决如多个项目的图标合并到一个项目中需求),再修改一下项目配置. 不过同时若有"项目另存为"就更方便快捷了

**Comment by purplebamboo** [comment]
已增加 批量加入购物车。

另存为这个 我们评估下哈。
