### ISSUE TITLE
字体太少了

### ISSUE THREAD

**Issue by murongqiaochu** [thx/iconfont-plus#275]
可以添加一些购买版权的方式，支持正版从我做起～

**Comment by purplebamboo** [comment]
嗯  亲说的 是webfont吗？ 这个我们也很无奈，针对阿里内部其实可以用很多字体的。

但是对外只能开放部分，购买版权操作又太复杂

**Comment by murongqiaochu** [comment]
可是即使是开源字体也并不全啊??

发自我的 iPhone

在 2016年12月19日，下午5:51，purplebamboo <notifications@github.com<mailto:notifications@github.com>> 写道：


嗯 亲说的 是webfont吗？ 这个我们也很无奈，针对阿里内部其实可以用很多字体的。

但是对外只能开放部分，购买版权操作又太复杂

―

**Comment by purplebamboo** [comment]
嗯  暂时没有花太多时间去找。开源的字体我们用的不多，所以没怎么管。

如果亲有需求，可以给我们找下 你需要的开源字体的ttf文件，我可以帮你弄上去哦

**Comment by murongqiaochu** [comment]
你好，之前受到邮件的时候手里没有太多的资源，最近找到了一个字体资源，也许收集了所有的开源字体，而且把授权标注的很清晰
http://zenozeng.github.io/Free-Chinese-Fonts/
以上就是网址了，因为是github的资源所以需要vpn才能打开，想必是难不倒你的。
真心希望iconfont能越做越好。
期待您的回信


在 2016年12月20日，下午8:34，purplebamboo <notifications@github.com<mailto:notifications@github.com>> 写道：


嗯 暂时没有花太多时间去找。开源的字体我们用的不多，所以没怎么管。

如果亲有需求，可以给我们找下 你需要的开源字体的ttf文件，我可以帮你弄上去哦
