### ISSUE TITLE
shit

### ISSUE THREAD

**Issue by lyf** [thx/iconfont-plus#276]
为什么我登录了还是提醒我要登录，，，，，，点击登录的又是直接进去我的github。。。这不是自相矛盾吗

**Comment by purplebamboo** [comment]
sorry 亲 给你带来了不好的体验，可以把场景详细说下不？
具体的步骤提供下，做好有截图。

因为我这里登陆无法复现你的问题哈。

**Comment by purplebamboo** [comment]
另外尽量使用chrome浏览器哈，因为我们毕竟用业余时间做的，没那么多精力去做全浏览器的兼容哈

**Comment by lyf** [comment]
没事了

在 2016-12-19 17:49:21，"purplebamboo" <notifications@github.com> 写道：


sorry 亲 给你带来了不好的体验，可以把场景详细说下不？
具体的步骤提供下，做好有截图。

因为我这里登陆无法复现你的问题哈。

**Comment by purplebamboo** [comment]
@lyf   是突然又好了？

**Comment by lyf** [comment]
恩恩 现在行了！！嘿嘿 打扰了

在 2016-12-19 18:00:08，"purplebamboo" <notifications@github.com> 写道：


@lyf 是突然又好了？
