### ISSUE TITLE
页面报错

### ISSUE THREAD

**Issue by mda07022** [thx/iconfont-plus#277]
![image](https://cloud.githubusercontent.com/assets/13713831/21334571/8456655a-c693-11e6-96ef-72dfb2c5d608.png)

**Comment by purplebamboo** [comment]
我这里没有错误哎，亲  试试关闭浏览器插件？

我理解你这个是先搜索文件夹之后再搜索delete对吧，我这里尝试了下，并没有这个错误。

请可以提供稳定的复现办法不？
