### ISSUE TITLE
旧版下载的svg可以兼容fontawesome，新版的不行

### ISSUE THREAD

**Issue by stonewinner** [thx/iconfont-plus#279]

**Comment by purplebamboo** [comment]
兼容是指？
新版旧版的字体生成svg是一样的哈。

麻烦再说清楚点哦，不然我也不知道怎么帮你解决问题哈。

**Comment by stonewinner** [comment]
我在http://fontello.com/来合并svg图标的。旧版下载过来的svg拖进来是正确的，新版下载过来的svg合并的时候，会使原来的图标乱码。

**Comment by stonewinner** [comment]
希望您们也有一个差不多的合并功能

**Comment by purplebamboo** [comment]
合并有问题应该是  unicode 重复的问题，跟字体svg本身没有关系的。

**Comment by stonewinner** [comment]
旧版下载的svg合并没有问题

**Comment by purplebamboo** [comment]
这个问题暂时没有 下文，我先关掉了。如果还有疑问再打开哈。
