### ISSUE TITLE
谷歌material icon中部分svg上传后和原图不一致

### ISSUE THREAD

**Issue by iHearty** [thx/iconfont-plus#281]
谷歌material icon中,关于电池电量的svg，一部分灰色，一部分黑色，可是上床到iconfont后全部变成了黑色。 例如：material-design-icons-master\device\svg\production\ic_battery_20.svg

**Comment by purplebamboo** [comment]
可以把svg  上传到这里不，我们检查下

**Comment by iHearty** [comment]
这个是svg文件，你试试~~
[ic_battery_charging_50.zip](https://github.com/thx/iconfont-plus/files/665611/ic_battery_charging_50.zip)

**Comment by purplebamboo** [comment]
亲 你这个图标我看了，里面有透明度的。

目前我们是不解析  渐变 透明度 描边 这些复杂的属性的。图标不宜太复杂。

目前支持的多色只是 fill，就是填充属性哈，这个图标使用 fill-opacity来让上半部分颜色变淡，所以会有问题的。

**Comment by yisibl** [comment]
支持渐变图标请关注：https://github.com/thx/iconfont-plus/issues/1938
