### ISSUE TITLE
搜索一个图标后，可以有链接连接到相应的图标库

### ISSUE THREAD

**Issue by gaoshaochen** [thx/iconfont-plus#282]
搜索一个图标后，有的时候不是找一个图标，而是找一组图标，目前只能一个一个的找，组合起来的风格没有一套图标那么融洽，希望可以找到一个图标后，有链接可以找到这个图标出自哪个图标库。

**Comment by purplebamboo** [comment]
其实有的，不是所有图标都属于某个图标库。

如果当前图标属于某个图标库，可以点击  下载，在弹框的左上角可以看到所属的图标库，可以直接点进去的。

**Comment by purplebamboo** [comment]
当然入口有点深，这个我们在评估，会优化一下的。

**Comment by gaoshaochen** [comment]
赞！
