### ISSUE TITLE
编辑项目-项目名称修改点击保存报错整个项目都没有了。。。

### ISSUE THREAD

**Issue by zhanghaitian** [thx/iconfont-plus#284]
这个项目能找回吗？账号（jcloud_icon@sina.com）帮忙查一下，谢谢

**Comment by purplebamboo** [comment]
亲 项目名称是啥呢？

用户名也提供下哈

**Comment by zhanghaitian** [comment]
项目名称是：卖家中心（恢复这个项目就行）
用户名：jcloud_icon 
麻烦一下，谢谢~

**Comment by purplebamboo** [comment]
亲 我查了下，没查到这个项目呀。是不是被你们不小心删除了呀

**Comment by zhanghaitian** [comment]
是啊 这个项目找不到了
没有删除，当时进入编辑项目 -项目名称修改点击保存报错这个项目就没有了。。。
这个不能恢复吗？

**Comment by purplebamboo** [comment]
囧  好奇怪，真的找不到了，系统看到应该是被删除了。。。。

这个目前还没有恢复的机制哎。

**Comment by zhanghaitian** [comment]
- - 直接数据库物理删除吗？

**Comment by purplebamboo** [comment]
囧，是的，项目直接是物理删除的。

只有上传的图标有软删除，可以恢复。

**Comment by zhanghaitian** [comment]
囧，好吧  谢谢

**Comment by OVampireo** [comment]
我的也是这样，项目名修改失败，提示了个error然后整个项目就不见了，不过如果用的是阿里地址的话还是能加载图标，就是不知道有效时间是多久。。。 安全起见还是下载下来吧。

**Comment by yisibl** [comment]
Duplicate of https://github.com/thx/iconfont-plus/issues/302
