### ISSUE TITLE
建议：增加个人项目的开放下载功能？ 

### ISSUE THREAD

**Issue by zhou-yg** [thx/iconfont-plus#286]
希望改善下使用图标库的体验，感觉每次在工程里更新新图标好麻烦。

**Comment by purplebamboo** [comment]
亲  你的描述我不是太明白哈。项目是项目  图标库是图标库，现在是哪个有困扰呢？

更新新图标不方便是指？

**Comment by zhou-yg** [comment]
@purplebamboo  发现你们支持在线图标，没问题啦
