### ISSUE TITLE
项目的图标不能改变名字~

### ISSUE THREAD

**Issue by OJesusO** [thx/iconfont-plus#287]
如题，项目里面的图标不能改名字的？而且  就算是外面改了 也不能改到里面的，那为什么 不开放，项目里面可以修改图标的名字（Icon Name）。。。

**Comment by purplebamboo** [comment]
这个问题是个历史遗留问题。

是这样的，项目里的图标都有个源。这个源就是某个作者上传的图标。项目里的图标有自己的图形，unicode，fontclass拷贝，可以修改，但是其他一些基本信息都是属于原始图标的。

类似儿子要继承父亲的姓。＝ ＝
所以项目里的名字需要继续用原始图标的名字，目前不开放修改的哎。可以通过修改原始的图标的名称，这样项目里以它为副本的图标名字都会修改掉的。

后面我们考虑下是否可以开放。稍微麻烦点，需要改造数据库结构。

**Comment by jrt324** [comment]
强烈支持 不能改名称太不方便了

**Comment by yuanguandong** [comment]
多设计一个一个字段嘛

**Comment by yisibl** [comment]
@yuanguandong 这是一个历史遗留问题，详见：https://github.com/thx/iconfont-plus/issues/287#issuecomment-269154387

另外请统一关注：#1500
