### ISSUE TITLE
又让我逮到了这个人性化的缺陷

### ISSUE THREAD

**Issue by 1060778506** [thx/iconfont-plus#288]
![qq 20161225140923](https://cloud.githubusercontent.com/assets/24760769/21469947/c8388da4-caab-11e6-8753-bd5f8eb968ef.png)
这个是小写的ffffff 白色，背景确实变成灰色的，图标也是白色的，但是

-----------------------------分割线---------------------------------

![image](https://cloud.githubusercontent.com/assets/24760769/21469957/f1e4845a-caab-11e6-92e2-2620ab4246ac.png)
大写的FFFFFF不行，背景是白色的，图标也是白色的,  虽然小写的 ffffff<FFFFFF   性能排序 但是你们忘记了大写的FFFFFF     fff<FFF<ffffff<FFFFFF  性能排序，   你们也忽略了，3个fff  和大小写的FFF    

--------------------------分割线----------------

看完双击评论66666666666666666666

**Comment by purplebamboo** [comment]
= = 这都被你发现了，的确是我们的失误.

是这样的，我们不建议使用fff这种缩写哈（目前是要输入6位的），fff这种是前端才知道的缩写。

大写的这个  FFFFFF我处理下，今天上线，感谢反馈。
