### ISSUE TITLE
symbol引用方法在ie不显示

### ISSUE THREAD

**Issue by LuxPax** [thx/iconfont-plus#289]
我把项目下载下来了，用的是symbol引用方法，但是在ie上不显示svg图标。怎样解决这个问题？谢谢！

**Comment by purplebamboo** [comment]
＝ ＝ 亲 看下里面的介绍   symbol本身兼容性就不好  支持ie9+

**Comment by LuxPax** [comment]
我ie11，不显示是怎么回事


发自网易邮箱大师
在2016年12月26日 15:45，purplebamboo 写道:

＝ ＝ 亲 看下里面的介绍 symbol本身兼容性就不好 支持ie9+

**Comment by purplebamboo** [comment]
额 亲  是我们的demo吗？  
下载我们的demo到本地打开。最好跑个服务，还不行的话记得用线上cdn地址哈。

**Comment by purplebamboo** [comment]
或者项目id给我下 我有空看看哈。

**Comment by LuxPax** [comment]
解决了，是我浏览器禁用了脚本，实在抱歉，麻烦你了，不好意思


发自网易邮箱大师
在2016年12月26日 15:54，purplebamboo 写道:

或者项目id给我下 我有空看看哈。
