### ISSUE TITLE
iconfont是多色的在页面上显示一坨黑色

### ISSUE THREAD

**Issue by youniuben** [thx/iconfont-plus#290]
http://www.iconfont.cn/plus/manage/index?manage_type=myprojects&spm=a313x.7781069.1998910419.10.tLC2jH&projectId=97076

**Comment by purplebamboo** [comment]
在我们平台是多色的  下载的demo是黑色的吧。

还是说是 上传的图标是彩色的 上传后变成黑色的？

需要描述的再清楚点哈。

**Comment by youniuben** [comment]
上传的是彩色的  下载下来在页面中使用的时候就变成了一坨黑色的东西

**Comment by purplebamboo** [comment]
使用时如果用的是  unicode 或者fontclass，那么本身是字体，是不支持多色的哈。

只有symbol的引入方式是支持多色的。
http://www.iconfont.cn/plus/help/detail?helptype=code
