### ISSUE TITLE
色值的小问题，阿里妈妈吗，双击评论666666+++

### ISSUE THREAD

**Issue by 1060778506** [thx/iconfont-plus#291]
![qq 20161226130123](https://cloud.githubusercontent.com/assets/24760769/21475891/bdeb8074-cb6c-11e6-8c57-79f4d7b66a5f.png)
别忘了类似这个类似白色的色值，这个我不知道怎么处理了，但是使用这个网站的人应该会很聪明的，他们应该知道先更改颜色的形状，然后在调一个对比度高的颜色看效果，然后在调成这种类似白色的颜色，用户应该是这样使用的，我估计你们应该只是判断了FFFFFF 和小写的ffffff  没有判断相近的白色的色值吧？我估计相似白色的色值判断起来应该很困难吧，我自认为我自认为我自认为很困难-------------------
![wbzigentu](https://cloud.githubusercontent.com/assets/24760769/21475896/cacfe320-cb6c-11e6-90c2-b246a79f9627.jpg)
![default](https://cloud.githubusercontent.com/assets/24760769/21475895/c48cbc0e-cb6c-11e6-8843-5f4fd10c16d0.jpg)
---------------------------------------------------------------------------------------------------------
阿里妈妈吗 图标，确实是很好的网站，，，，，我第一次知道这个网站的时候是别人推荐的，我使用这个 网站也就下载个图标，我到现在还不知道这个网站到底是干什么的ШШШΞ，惭愧，我只会下载个图标放到PS，确实很不错的网站，我有一个另类的疯狂的想法，我只是说说，想表达一下内心的感慨，你们看一下就可以了，不是建议也不是要求，我就是一个吃瓜的群主的想法，我的想法是，如果这些图标是3D的那很6666666666666，
![qq 20161226131646](https://cloud.githubusercontent.com/assets/24760769/21475963/9324e032-cb6d-11e6-9e8d-1eb8494514ef.png)
我只是说一下，我只是说一下，我只是说一下，这个可能真的超出你们的范围了，别的没有问题了，很666666666666666666666
------------------------------------
双击评论666666666666666666666666666666666+++++++++++++++++++++++

**Comment by purplebamboo** [comment]
我们的确只判断了 白色哈，另外两个 ＝ ＝ 判断起来比较复杂来着。

我们是图标网站哈，你可以直接下个图标走人，也可以用iconfont或者svg symbol的方式应用这些图标。
