### ISSUE TITLE
iconfont.js报错

### ISSUE THREAD

**Issue by lulei90** [thx/iconfont-plus#293]
在引用iconfont.js的页面 
虽然图标能正常显示 但是浏览器控制台会报
iconfont.js:1333 Error: <path> attribute d: Expected number, "MNaN NaNaNaN NaN …"
.appendSvg @ iconfont.js:1333
loadFn @ iconfont.js:1260

**Comment by purplebamboo** [comment]
这个是某个图标有问题哈。 你可以忽略。

是这样的，svg图标最终会弄到页面，如果这个svg图标本身就是有问题的，那么浏览器就会解析出错哈。

你可以在body里面找到这个图标的，看下它的 d属性，NaN的就是有问题的那个

**Comment by lulei90** [comment]
@purplebamboo 
在代码里面找到了
但是我发现那个出错的属性的那个svg的id是图标里面不存在的

**Comment by purplebamboo** [comment]
那么可能你删除了那个icon（删除后是不会触发重新生成 cdn地址的，毕竟资源还是不能浪费）
你可以随便修改下图标或者项目的信息，重新生成cdn。

**Comment by lulei90** [comment]
@purplebamboo 
嗯嗯 谢啦 你们这回复速度太赞了
