### ISSUE TITLE
 添加到购物车后无法添加到项目 下载不了 

### ISSUE THREAD

**Issue by wenghuiliu** [thx/iconfont-plus#296]
图标添加都购物车后  下载不了 也不发添加到项目

**Comment by purplebamboo** [comment]
亲 是什么浏览器？

可以提供具体的步骤吗？

不能下载是指，下载了报错，还是点了没反应呢？

**Comment by wenghuiliu** [comment]
360  添加到购物车后，添加至项目 、下载素材、下载代码  都是点击不了

**Comment by purplebamboo** [comment]
奥奥 我去试试360，建议亲尽量使用 chrome哈

因为我们是业余时间做的iconfont。精力有限,可能没那么多时间去兼容所有浏览器。
