### ISSUE TITLE
项目成员添加能更方便点吗（支持分组）

### ISSUE THREAD

**Issue by lulei90** [thx/iconfont-plus#298]
现在新建项目的时候 想吧固定的几个人添加到项目里面去
每次都只能一个个的输入 这个好麻烦

**Comment by purplebamboo** [comment]
的确，我们后续可以考虑 加个最近常用人员。这样应该会方便点

**Comment by yisibl** [comment]
感谢建议，通过链接邀请成员功能已经上线。
