### ISSUE TITLE
图标下载那个交互有点难受

### ISSUE THREAD

**Issue by minganlee** [thx/iconfont-plus#3]
感觉新版的图标下载那个交互有点难受，鼠标一放上去就出现三个按钮，旧版的感觉更好一些，更加方便和直接，出现三个按钮，每次需要滑动选择

**Comment by Muqing1221** [comment]
明白亲的感受~~采用新的方式，主要是考虑到新的方式会让触发区域变大，而易于操作；不知道亲是不是只是还不习惯~多用用再看？

**Comment by lulei90** [comment]
的确 新版的图标下载 没老板的操作更直接

**Comment by purplebamboo** [comment]
理解 这个我们过段时间会再讨论一次。内测就是希望得到你们的反馈。

**Comment by github1900** [comment]
鼠标移到图标时，弹出的动作稍微优化一下，现在觉得很楞，的确不是很习惯

**Comment by purplebamboo** [comment]
之前是考虑做点效果的，但是如果做一些动态的效果又会导致这个浮层出的太慢，又会妨碍到操作，这个我们内部还在讨论中，看看还能不能再优化下。
