### ISSUE TITLE
体验还没之前的好

### ISSUE THREAD

**Issue by jxs123** [thx/iconfont-plus#30]
界面使用的字体看起来没变，可能是背景图的问题，## 页面字体很不清晰，有一种锐化过度的感觉。以前的版本就没有。当我看到右侧下拉会出现的3个灰色图标时，再看到友情链接的那3个图标时，觉得好失望，那么多清晰美观的图标，非要用”不清晰，边缘不平滑"，也是锐化过度或者放大导致的吧。虽然边边角角都不是重点，但是首页起码要平滑一点，## 到处都是锐化过度或者放大过度导致的边缘不平滑，感觉残次品似的。

上边头部3个次品，中间3个减肥过度（太细了），底部3个只能说这是古董吗，9个图标真的很次，图标库居然用这样的图标，好失望。

# **

> 建议：让页面的文字和图标圆润一点，看着会更舒服。

**

**Comment by Muqing1221** [comment]
谢谢亲的建议，我们会酌情调整的~

每一次的改版必然都有所尝试/改变/创新，或许不能让你所有细节都满意，(虽然这是我们的目标)，也或许不能让你在第一时间觉得非常好看~但就工具型网站而言，“好看”只是衡量产品质量的一个维度，除此之外还有“好用”“有趣”“情感化”等等多个维度~

我们也期待你再多使用一段时候后，能继续给我们反馈你的感受~这都将是我们非常宝贵的用户声音~

Thank you again, have a nice weekend~

**Comment by jxs123** [comment]
我是干前端的，所以有些页面上的表现感觉很次，在搜图标进去的页，顶部会出现一个搜索框，那个默认提示文字要放就放中间，偏下是什么景，输入内容却是垂直居中，前后不一致，偏下的很不好。虽然都是小细节，难道是故意的？

建议：给input加个行高line-height: 29px !important;，图标20px真的有点大，改成18px，向左多2px会更好。

**Comment by Muqing1221** [comment]
虽然犀利，但异常感谢，谢谢...
会仔细考虑你的建议，虚心接受，酌情修改
希望持续关注

另，如果真的很不喜欢现在的版本，在导航最后的展开项中，可以返回旧版
不确定会保留多久，但...你可以先用着

**Comment by jxs123** [comment]
其实很支持，感觉网站内容确实很好

**Comment by purplebamboo** [comment]
首先 非常感谢亲的建议，iconfont毕竟是我们业余时间搞出来的东西，加上最近忙双十一，暂时没有太多精力花在上面，可能有些细节并没有注意到，我们会慢慢打磨的。

亲说的几个建议，我们后续会优化掉的。
