### ISSUE TITLE
彩色的应该怎么在页面上显示?

### ISSUE THREAD

**Issue by sinyat** [thx/iconfont-plus#300]
我把彩色的图标放到页面上,显示的是黑的

**Comment by Muqing1221** [comment]
下载的png还是图标代码应用？
png应该没问题吧，代码应用的话，要用symbol

**Comment by purplebamboo** [comment]
代码方式 目前有三种  unicode   fontclass  symbol

其中unicode fontclass是用的字体不支持多色的。
只有 symbol的方式可以支持。

具体可以把项目下载到本地，里面三种用法都有哦。

**Comment by sinyat** [comment]
谢谢
