### ISSUE TITLE
找不到同一个作者作用相反的那个icon

### ISSUE THREAD

**Issue by bowei-jbw** [thx/iconfont-plus#301]
如题，很多场景下，需要找到相反的icon，比如我搜『向左』，找到一个满意的图标，这时很可能会需要同一个作者『向右』的图标，但现在没办法找到。
这个问题真的很影响体验。。

**Comment by Muqing1221** [comment]
如果某个图标隶属于某图标库，是可以在图标详情浮层左上角看到归属信息的，这样可能比较方便你找到相似的一系列图标；反之...我们暂时也还无解
记下你的需求啦~谢谢支持

**Comment by yisibl** [comment]
如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)
