### ISSUE TITLE
求帮助，修改项目名失败后整个项目都不见了！

### ISSUE THREAD

**Issue by OVampireo** [thx/iconfont-plus#302]

**Comment by purplebamboo** [comment]
你好可以提供下项目名称吗？

看来不是个小问题 我好好排查下

**Comment by purplebamboo** [comment]
我试着修改了一些项目 却都没有这个问题

**Comment by OVampireo** [comment]
不知道了，用的git账号登录的，项目名叫 meilin 修改为meilin-wechat还是meilin_wechat的时候就这样了，火狐浏览器下操作的，之后也试了一下发现没有问题，可是之前的项目确实不在了。这是这账号第一次修改项目名，你可以试试是不是只有第一次会有问题。

**Comment by OVampireo** [comment]
O(∩_∩)O，我想问问项目不在了，我之前写的东西用的是在线地址，这地址不会哪天就无效了吧？目前还是可以加载到的。

**Comment by purplebamboo** [comment]
@OVampireo  在线地址不会失效的，可以放心，具体原因 我继续排查下。

**Comment by OVampireo** [comment]
@purplebamboo 干吧蝶。

**Comment by wangwenjie1314** [comment]
我的也是，哭了，一定要找回来啊

**Comment by OVampireo** [comment]
你想多了。。 “不找了找不到了~”

**Comment by yisibl** [comment]
如果需要找回老账号遇到问题，请加一下钉钉答疑群
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
