### ISSUE TITLE
每次更新项目中的icon以后都会生成新的链接，那么旧的那个链接还可以用吗？ 可以用多久？

### ISSUE THREAD

**Issue by zhangjinxue** [thx/iconfont-plus#303]
我是通过 font class 那种方式引用的， 每次往项目中添加icon后都会生成新的链接，现在担心上线以后，如果开发环境需要更新icon，但是不会立马同步到线上，这个时候更新了这个链接 ，那原来的链接还可以用多久？

**Comment by purplebamboo** [comment]
永远都可以使用 放心用哈

**Comment by zhangjinxue** [comment]
好的，非常感谢
