### ISSUE TITLE
★★★★★重要功能建议：增加自动创建反色图标功能！

### ISSUE THREAD

**Issue by xiemin2161** [thx/iconfont-plus#304]
有的时候1个图标需要用到普通状态和点击状态，即反色状态，但是如果手动去处理的话，太麻烦，在网上直接找的话，想找一套普通状态加反色状态都齐全的也基本不可能，希望系统能够加入自动创建图标反色图标功能，即将原先透明的部分填充，将原先填色的部分透明，再加上边缘处理，如直角或圆角等，我想这个功能会大大改善大家使用图标的效率

**Comment by Muqing1221** [comment]
听起来比较像简易的在线图标编辑~恩，我们记下亲的建议了，在资源允许的时候，会持续更新优化产品的，谢谢支持~

**Comment by purplebamboo** [comment]
暂时无法做到哈，先delay了
