### ISSUE TITLE
建议：希望每个图标可以链接到它所在的图标库。

### ISSUE THREAD

**Issue by NikiYE** [thx/iconfont-plus#307]
有时候同时需要一个风格的图标，或者像点赞前后配套的图标，因为重复图标过多对比看起来很辛苦，大同小异。

**Comment by purplebamboo** [comment]
其实 有的，入口有点深哈。

点击下载按钮，如果这个图标有所属的公共库，都会罗列在最上面的。

我们目前已经在考虑优化了哈。
