### ISSUE TITLE
旧版直接在平台上面调整大小和尺寸方向后新版用不了！

### ISSUE THREAD

**Issue by 471937364** [thx/iconfont-plus#31]
好像只能在demo_symbol.html这个演示里面那样实现，没有旧版方便好用！略显复杂，如果要用的话之前的都不能用了，只能重新来！

**Comment by purplebamboo** [comment]
亲  你是指的哪一块？能提供具体的case吗？

**Comment by 471937364** [comment]
你好，刚刚下载试了，可以了，你们是不是改过了啊，速度挺快的啊！

**Comment by 471937364** [comment]
你好，刚刚下载试了，可以了，你们是不是改过了啊，速度挺快的啊！
今天下的文件都是可以的，之前的不行，我这里传不了附件！
We don’t support that file type.  选择文件 Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.
总之问题解决了，支持IconFont，非常好用和强大！
