### ISSUE TITLE
部分图标为啥不支持搜狗浏览器 比如直通车优化和梦

### ISSUE THREAD

**Issue by zhanghonglizhang** [thx/iconfont-plus#316]
部分图标为啥不支持搜狗浏览器 比如直通车优化和梦

**Comment by Muqing1221** [comment]
@purplebamboo

**Comment by gongeek** [comment]
不支持是指应用图标后的项目不支持？还是iconfont网站本身不支持？ 
如果是后者的话建议使用chrome来使用iconfont，精力有限，目前我们在chrome上的体验是最好的
