### ISSUE TITLE
下载的图标不是最新的

### ISSUE THREAD

**Issue by zfsn12** [thx/iconfont-plus#317]
下载的文件不是最新的，新增很多图标都下载的还是昨天生成的，目前所有的项目中下载的都是这一个文件，不管如何修改图标库中的内容，都无法生效

**Comment by Muqing1221** [comment]
@purplebamboo

**Comment by gongeek** [comment]
项目更新图标后如果是用的cdn 记得点更新cdn地址。
如果是直接下载图标文件的话，应该能够全部下载下来的，如果不能可以告知下项目id
