### ISSUE TITLE
建议提供 BASE64编码!!

### ISSUE THREAD

**Issue by Cabchinoe** [thx/iconfont-plus#318]
如题~~
在下载的时候选择完成后可以勾选base64编码最好啦, 省去了我们自己还要发布文件的一步~

**Comment by purplebamboo** [comment]
亲  你是要 什么的base64  字体的 还是svg图标的。

这个我们在考虑中了哈。

**Comment by huarse** [comment]
+1，老版本在css文件里面有一个base64编码的，可以直接copy到文件里面，对于离线包的项目特别好用，现在我还要自己下载然后编码

**Comment by wangcherry** [comment]
+1，期待什么时候实现
