### ISSUE TITLE
线上修改图标后，下载到本地，还是修改前的。。

### ISSUE THREAD

**Issue by wmrisme** [thx/iconfont-plus#32]

**Comment by Muqing1221** [comment]
亲是“直接保存”还是“保存为副本“？
But, 我刚再次试了下两种方式，下载PNG和SVG格式都是修改后的

需要的话，可以详细描述一下是哪个图标，以及那种错误样式

**Comment by Muqing1221** [comment]
BTW，我只是测试了单色图标，亲是单色还是多色
