### ISSUE TITLE
图标似乎不会自动居中自适应了？

### ISSUE THREAD

**Issue by kezidou001** [thx/iconfont-plus#322]
改版前的fonticon，上传的图标不需要手动去矫正图形的位置和大小。平台会自动将图形居中并自适应。自从可以加入彩色fonticon后，这个居中自适应的功能似乎就没有了。但是实际上我觉得居中自适应比彩色更重要。宁可图标恢复到黑白，也希望可以保留居中自适应的功能。

**Comment by gongeek** [comment]
应该不会的，上传后图标会解析一下的，一些不标准的会自动缩放移动位置的。
出现上面这种情况可能是图标不标准，新版解析上传图标略微有改动。
可以把有问题得图标发来我们看看？ gongweiqm@qq.com

**Comment by kezidou001** [comment]
又研究了一下，应该是我自己做的图标问题。规则和改版前不一样了。我现在已经知道怎么弄了，非常感谢！



xiang900709@163.com
 
发件人： gongeek
发送时间： 2017-01-12 10:21
收件人： thx/iconfont-plus
抄送： kezidou001; Author
主题： Re: [thx/iconfont-plus] 图标似乎不会自动居中自适应了？ (#322)
应该不会的，上传后图标会解析一下的，一些不标准的会自动缩放移动位置的。
出现上面这种情况可能是图标不标准，新版解析上传图标略微有改动。
可以把有问题得图标发来我们看看？ gongweiqm@qq.com
―
