### ISSUE TITLE
希望一个项目  生成的样式文件可以自定义名称，且更新图标后 样式文件名称不变

### ISSUE THREAD

**Issue by createskyak** [thx/iconfont-plus#323]
希望一个项目  生成的样式文件可以自定义名称，且更新图标后 样式文件名称不变
每次更新图标 都要修改一下引用文件路径 真的很不爽

**Comment by gongeek** [comment]
1.自定义cdn名称不需要吧，还要考虑不能和别人项目样式文件的cdn地址重复，还多了一步填名称的操作，感觉意义不大。
2.另外一个项目cdn文件名称都一样的话，项目更新了，如何让客户端浏览器不使用缓存？
3.并且假如你删除某个图标后如何让之前老的项目不出现问题？一个样式文件别的网站项目也可能使用不能保证。
4.如果名称不变的话等于说你每次更新图标，上传图标，删除图标。都需要实时生成新的样式文件，消耗会比较大，并且你对项目的操作会立马反应到项目当中去，误操作风险太大。

以上是基于亲使用的是我们生成的cdn地址，绝大部分项目都是这么应用的。如果是自己下载样式文件下来使用那就没办法了。

**Comment by yisibl** [comment]
https://github.com/thx/iconfont-plus/issues/891
