### ISSUE TITLE
建议在搜索的图标上显示作者信息，方便引用一系列相同风格的图标

### ISSUE THREAD

**Issue by wucuida** [thx/iconfont-plus#325]
当引用了某个图标，总是希望其他图标保持风格一致。比如我用了某个`edit`图标，我也希望找到相同风格的`save`图标，如果能显示此`edit`图标的作者，就可以方便的查看作者其他图标了。因而希望能在能在图标上提供作者其他图标的链接。

**Comment by gongeek** [comment]
见 #307
