### ISSUE TITLE
 我发起的项目  的列表如果过长会出现滚动条

### ISSUE THREAD

**Issue by zjpzjp** [thx/iconfont-plus#33]
个人中心  我发起的项目  的列表如果过长会出现滚动条。。不雅，不雅
首页帅的一比

**Comment by Muqing1221** [comment]
先谢谢亲的认可~
现在的滚动条是浏览器样式，我们暂时还没有想到更合适的解决方案~~如果不出现滚动条似乎也不太合适；之后会逐渐将首页的帅普及开来的~
