### ISSUE TITLE
之前是用新浪帐号弄的项目图标，现在想要转到git帐号下，怎么弄

### ISSUE THREAD

**Issue by dragonUiTeam** [thx/iconfont-plus#330]
由于某些原因，之前的新浪帐号是跟同事公用的，现在需要把新浪帐号上的项目转到我新注册git帐号上

新浪帐号：13799279561

git帐号：1469428977@qq.com

**Comment by gongeek** [comment]
这2个账号的用户名有吗？

**Comment by dragonUiTeam** [comment]
旧新浪用户名：dragonsoftUI
新git用户名：dragonUi

**Comment by gongeek** [comment]
项目有这个转让功能，你自己转让下项目？

![screenshot at jan 18 11-28-28](https://cloud.githubusercontent.com/assets/3911824/22049867/5286beae-dd71-11e6-86a7-f5e8f012340a.png)

![screenshot at jan 18 11-28-38](https://cloud.githubusercontent.com/assets/3911824/22049869/551c3f4a-dd71-11e6-8815-af9ed4bcbc80.png)
