### ISSUE TITLE
钉钉（ding talk）的图标库似乎没有

### ISSUE THREAD

**Issue by nuandongweiban** [thx/iconfont-plus#331]
钉钉（ding talk）的图标库似乎没有,没有找到Ding talk的图标库

**Comment by gongeek** [comment]
这些图标，图标库都是用户自己传的，我们不生产图标。 
找图标可以我我们的搜索
http://iconfont.cn/plus/search/index?searchType=icon&q=%E9%92%89%E9%92%89
