### ISSUE TITLE
可以搜索图标后，能够由此图标找到该图标所在的整套图标吗？

### ISSUE THREAD

**Issue by anny1994** [thx/iconfont-plus#335]

**Comment by guohuihot** [comment]
我也需要这样的功能，一套图标才是一样的风格

**Comment by guohuihot** [comment]
这个问题自从开始用这个库就开始反馈，没人管的

**Comment by gongeek** [comment]
https://github.com/thx/iconfont-plus/issues/49

**Comment by guohuihot** [comment]
我看的还是老网址的，新地址已经有了

**Comment by yisibl** [comment]
如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)
