### ISSUE TITLE
为什么现在下载的svg合并后都这么大，以前是可以的

### ISSUE THREAD

**Issue by guohuihot** [thx/iconfont-plus#336]
大的页面都放不下，只能把大小设置成1024，才是小图标，传个图片看看
![qq](https://cloud.githubusercontent.com/assets/3119995/22140674/dce62d56-df28-11e6-903a-1d4b53d1a5de.png)

**Comment by purplebamboo** [comment]
亲  可以设置宽高的呀，你是具体什么场景呀？ 可以描述的再详细点吗？

**Comment by guohuihot** [comment]
你说的宽高是哪里？我是下载时把大小设置成1024后，再合并才变小，但是以前直接下载就可以用
