### ISSUE TITLE
建议在点击下载后弹出的卡片中增加收藏按钮

### ISSUE THREAD

**Issue by kaeyleo** [thx/iconfont-plus#34]
喜欢的icon我一般直接下载，觉得有必要就会收藏，但是还要先关闭当前的卡片回到原页面中，找刚才的那个图标再去hover选择收藏太麻烦了。

建议在点击下载后弹出的卡片中直接增加 收藏 功能，就是把显示收藏数量的info-item变为可点击收藏。

虽然有点吹毛求疵，不过还是希望能改进一下，会方便很多。

最后感谢团队的努力，我会一直支持下去的。加油。

**Comment by Muqing1221** [comment]
哪里吹毛求疵啦~~哈哈~
当初的设计是有考虑在下载卡片上承载更多的更能，比如直接收藏，直接加入项目等，不过局限于我们的资源有限、时间有限，所以只能分步实现啦~以后会逐步更新上去的
谢谢亲的一直的支持，有问题继续吐槽~我们在听~

**Comment by purplebamboo** [comment]
之前是因为资源不足，这个功能才没做。等我们忙完双十一会加上去的哈。

目前时间不足，除了非改不可的bug。其他我们过完双十一再改哈。

**Comment by purplebamboo** [comment]
这里统一讨论吧：
https://github.com/thx/iconfont-plus/issues/139
