### ISSUE TITLE
希望搜索出来的图标 能进入到相关的项目库中去

### ISSUE THREAD

**Issue by www295686243** [thx/iconfont-plus#340]
关键词搜索出的图标 希望知道是哪个项目库中的  这样可以进入这个库 添加统一的图标
比如搜索 主页 这个词  出来很多房子图标   我想使用高亮和不高亮的两种  但有些大小不统一有细微的差别也只能添加后 编辑才知道  比较麻烦

**Comment by Muqing1221** [comment]
收到，谢谢反馈~

**Comment by kittytang** [comment]
啊啊啊这个真的超级需要，每次想找同一画风的两个都好难

**Comment by yisibl** [comment]
点击图标 详情，如果该图标有图标库，可以直接看到所属图标库
