### ISSUE TITLE
API, API, API合适上线API利于程序员自动化开发，不用每次上传都手动更新！

### ISSUE THREAD

**Issue by 1021683053** [thx/iconfont-plus#347]
API, API, API合适上线API利于程序员自动化开发，不用每次上传都手动更新！

**Comment by purplebamboo** [comment]
囧  其实我们有api的  只是处于安全的考虑，这些api仅限阿里内部使用，暂时没有对外开放哈。

这个我们后面再思考下  如何对外开放。

**Comment by 1021683053** [comment]
@purplebamboo 可以期待，最好对开发者申请开放！

**Comment by dongjb** [comment]
5年过去了，2022年了还没有开放API

**Comment by peakchen90** [comment]
2023 依旧没有开发 API

**Comment by 1021683053** [comment]
> 2023 依旧没有开发 API

换战场吧，换iconify吧

**Comment by TracyWalt** [comment]
2024了都依然没有api开放，这帮人真是蛀虫，在里面躺平混吃等死，真是垃圾

**Comment by 1021683053** [comment]
> 2024了都依然没有api开放，这帮人真是蛀虫，在里面躺平混吃等死，真是垃圾
换方案了，赶紧换吧，迟早要换

**Comment by Mr-Persona** [comment]
> 囧 其实我们有api的 只是出于安全的考虑，这些api仅限阿里内部使用，暂时没有对外开放哈。
> 
> 这个我们后面再思考下 如何对外开放。

你们这个问题考虑7年了，都快2025年了还未解决
