### ISSUE TITLE
无法登陆，访问受限？

### ISSUE THREAD

**Issue by muzidx** [thx/iconfont-plus#348]
![image](https://cloud.githubusercontent.com/assets/11745992/22639020/da87b7d0-ec86-11e6-88a0-d41119a62689.png)
点击之后，访问受限，跳到了这个链接下面？http://err.taobao.com/error2.html
![image](https://cloud.githubusercontent.com/assets/11745992/22639049/feb56e18-ec86-11e6-8e23-62cda1edcea8.png)

**Comment by androiddeveloperzp** [comment]
就是，求阿里大神修复呀

**Comment by 18234110325** [comment]
大神啊 效率啊 急用图标

**Comment by purplebamboo** [comment]
sorry  已经修复。。。
