### ISSUE TITLE
bug 以及一些意见

### ISSUE THREAD

**Issue by hanwenting** [thx/iconfont-plus#35]
1、下载弹出框在mac 13英寸屏幕下
![wechatimg1](https://cloud.githubusercontent.com/assets/23020715/19631499/c47086b6-99cf-11e6-8241-5a69325e317e.jpeg)

2、同样在该设备下，翻页后不会跳到页首，而是仍然在底部，所以我要手动滚到头部查看内容

3、如果可以给整个项目加上收藏就好了

**Comment by Muqing1221** [comment]
谢谢亲的意见，1、2、我们稍后会检查修复的
3、 现在的收藏只在图标维度，之后的之后的之后，或许会增加对于图标库的收藏，以及对于用户的follow，会一步步来；但因为“项目”是相对比较私有化的图标集合，我们暂时没有足够的理由来说服自己对项目增加收藏~~不知道亲有这个需求的理由是？

**Comment by Muqing1221** [comment]
1、因为亲没有全屏，现在是浮层固定大小
2、已修复，多谢~多谢again
