### ISSUE TITLE
关于symbol引用

### ISSUE THREAD

**Issue by valarsu** [thx/iconfont-plus#350]
symbol引用时，无法设置字体颜色，color不生效。下载的demo都不行

**Comment by valarsu** [comment]
已经解决了，生成的iconfont.js里面的path标签，有一个fill属性，如果这个fill属性有固定值，那么就无法在css里面修改color。解决方法就是把fill属性删除，这样就可以自行修改color颜色（对于单色图标来说）。

**Comment by valarsu** [comment]
目前还不清楚图标默认是不是都有缺省fill值，也可能是设计师上传图标时有相关设置。

**Comment by valarsu** [comment]
目前还不清楚图标默认是不是都有缺省fill值，也可能是设计师上传图标时有相关设置。

**Comment by purplebamboo** [comment]
你好 亲  的确是这样的。 本身就是设置的  fill:currentColor 来实现的 通过color设置svg的颜色。

多色图标本身就是有颜色的 我们就不建议修改颜色的。多色图标有自己的 fill属性，是无法去覆盖的。

这里还有个特殊的，就是本身是单色图标，被设计师上传时选择了保留颜色上传的，这个也会保留fill属性。



对于想要通过color修改颜色的目的，可以在项目里 -》 批量操作-》 去除颜色。这样生成的  symbol里面就不会有fill属性啦，就可以直接通过color来改啦。


更具体的可以在这里找到答案：

https://zhuanlan.zhihu.com/p/20753791?refer=FrontendMagazine

**Comment by NE-SmallTown** [comment]
@purplebamboo 你好，关于这个请教两个问题。

一是我项目里有的图标去色了，但是还是可以看到生成的symbol里有fill属性，也无法通过设置color来改变颜色。还有就是无法知道项目里哪些图标去色了哪些没有。

二是没有办法重新搜索到项目里某个图标，因为去色不可恢复，我去色了但是想恢复，只有重新找到这个图标重新添加才行。

**Comment by NE-SmallTown** [comment]
@purplebamboo Hello?

**Comment by purplebamboo** [comment]
@NE-SmallTown   看来是深度用户。

最近比较忙，我先简单回答下哈。

一 去色了应该会去掉fill属性的，你是不是没有重新生成symbol代码呢。 至于有没有办法知道有没有去色，囧目前的确比较弱，颜色比较明显的可以很快看出来，但是那种本身是单色的  多色图标，尤其是灰色的，就比较尴尬额。

二 重新搜索图标的确不好找，你可以这样，在去色之前先保存到其他项目，当然也可以点击下载，如果这个图标属于某个公共库，在那个上面会列出来。如果还不行，那么可以审查元素  看到里面的J_icon_id_1641993  后面的数字就是id。当然 你会说拿到id还是找不到。＝ ＝的确，不过可以追到一些信息，http://www.iconfont.cn/open/icon/detail.json?id=53183  通过这个可以查到一些信息。你可以继续用名称搜索，或者直接把 show_svg这个里面的拷贝下来变成svg 再上传一次就行了。

说了这么多还是平台功能不完善，不过目前的确没精力去做，望见谅。

**Comment by NE-SmallTown** [comment]
@purplebamboo 我看了下，那个图标的id是1039996，我试了下你提供的那个接口，的确能找到。但是这里还是有几个问题。

1.我搜索了这个人，但是发现他的图标库是空的，收藏里面有3个，但是没有我要找的这个图标，也许删除了？

2.那个show_svg直接保存是不行的，因为用到了class，style这些属性，但是这是原生的svg是无法识别的，我换成把这些属性对应的值填上去也不行，只复制他的path然后粘贴到其他svg上面貌似也不行。

3.从你提供的接口可以查到这个图标的关键词是“导航”（ - - 貌似我自己也知道），然后看了下你们的搜索接口，所以控制台写了个脚本：

```
function queryIconById(iconId, pageSize) {
  for(var i = 1; i <= pageSize; i++) {
    var xhr = new XMLHttpRequest();

    xhr.open('POST', 'http://www.iconfont.cn/api/icon/search.json');

    xhr.setRequestHeader('Content-Type', 'application/x-www-form-urlencoded');
    xhr.setRequestHeader('X-Requested-With', 'XMLHttpRequest');

    xhr.send('q=%E5%AF%BC%E8%88%AA%20&sortType=updated_at&page=' + i + '&pageSize=' + pageSize + '&t=1489587103575&ctoken=zBiiUwKSw8Al812cO0Moicon-font');

    xhr.onreadystatechange = (function(i) {
      return function() {
        if(this.readyState == 4) {
          var icons = JSON.parse(this.response).data.icons;

          icons.forEach(function(ele) {ele.id === iconId && console.log('page:' + i);});
        }
      };
    })(i)
  }
}

queryIconById(1039996, 36);

```

1039996是这个图标的id，36是"导航"的搜索结果一共有36页。但是发现通过xhr和直接在界面上点击触发xhr的结果居然是不同的- -，虽然参数都一样，比如上面打印出来是在第三页，我在第三页找了半天都没找到，然后在第二页找到了。。我比较了通过自己xhr请求第二页时返回的数据和点击第二页的触发的xhr的返回的数据，也是不一样的。。所以暂时不清楚是什么原因，也不知道是不是所有的情况下都需要减去1页。

不过好在还是找到了，谢谢你的建议哈哈，最后当然这是个业余时间维护的项目，有些需求没时间做很正常，非常理解你们 :smile:
