### ISSUE TITLE
建议图标中文名可像Font Class一样可以自定义

### ISSUE THREAD

**Issue by rockliuxn** [thx/iconfont-plus#355]
希望图片在copy之后，可以自定义名称，这样方便维护和管理。

**Comment by jiyi1990118** [comment]
这个早就实现了啊！

**Comment by rockliuxn** [comment]
<img width="913" alt="qq20170215-155102 2x" src="https://cloud.githubusercontent.com/assets/7591665/22965101/d5971092-f396-11e6-86bd-242948314a1a.png">

@jiyi1990118  如上图，保存为副本后， icon的中文名“赏金” 并不能进行修改

**Comment by yisibl** [comment]
请统一在 #1500 回复并关注该 issue。

**Comment by yisibl** [comment]
项目中单个图标修改名称功能已经上线。

![image](https://github.com/thx/iconfont-plus/assets/2784308/6ee34736-2e62-4f00-beb5-5cadb988fbe2)
