### ISSUE TITLE
使用fontclass的方式图标的高度增高

### ISSUE THREAD

**Issue by xiaolan017515** [thx/iconfont-plus#359]
使用fontclass的方式图标的高度增高，在移动端上导致错位

**Comment by NameNull** [comment]
旧项目不会 ，新建的项目都会，我也发现了这个问题，找了一早上，图标的padding-top增多了很多，无论是网页端还是手机端。而将同样的图标收藏到旧项目使用，却没有padding-top

**Comment by purplebamboo** [comment]
奇怪  没有做什么改动呀。

亲 你们这个问题 我感觉是项目中某个图标撑开了整个字体。

用二分法 可以筛选出来是哪个图标有问题，把这个图标删除就可以了。

可以参考这里：

http://www.iconfont.cn/plus/help/article_detail?article_id=1

搜索：单个icon撑开的问题

**Comment by NameNull** [comment]
敢不敢留下个邮箱给你发示例

**Comment by purplebamboo** [comment]
可以的哈，邮箱一直有的来着，点我头像进去 可以看到的，
是  xhzhuweikang@163.com

**Comment by NameNull** [comment]
已经发了，你看看

**Comment by NameNull** [comment]
这个问题导致图标多余空白部分盖住其他元素，导致该元素触发的点击事件变成此图标的点击事件

**Comment by purplebamboo** [comment]
你好 亲  看了你的邮件  就是  我说的那个问题哈，你看看我给的链接里面的解释。

你的项目里有个图标导致整个字体撑开了。



![wangwang20170216161951](https://cloud.githubusercontent.com/assets/1409611/23013007/c655768c-f463-11e6-8a86-519207c6044e.png)



把这个 e643的图标删除重新生成字体，就行了哈。

**Comment by NameNull** [comment]
。。。厉害了 ，谢谢！

**Comment by xiaolan017515** [comment]
怎么找到撑开的那个图标啊？

**Comment by gongeek** [comment]
https://fontforge.github.io/en-US/  用这个软件打开下字体文件试试

**Comment by woden0415** [comment]
也遇到了这个问题，看了@purplebambo提供的链接和错误案例，和我这种情况还不一样。
描述一下：
从iconfont网站下载的字体包，打开demo页面后(测试浏览器是chrome，引用的文件是woff字体文件)，是这样的：
![字体图标拉伸](https://i.screenshot.net/6ol86sx)

然后我用字体编辑软件FontCreator，打开该woff文件，查看对应的”X“图标，是这样的：
![通过软件打开woff文件](https://i.screenshot.net/63xg6hg)

网上搜索了一下，这个==WinAscent==是指字符显示的上边界。同样，我打开了其它的图标，都是这样，有一个很高的==WinAscent==。

我又下载了我其它项目里的字体文件，woff文件打开后，是正常的。
![正常的字体图标大小](https://i.screenshot.net/62jo6f4)
==WinAscent==值大小差不多。

我的项目图标css文件是这个。[http://at.alicdn.com/t/font_nhu9ezd0wf06n7b9.css](http://at.alicdn.com/t/font_nhu9ezd0wf06n7b9.css)

====================
因为网站需要，必须得访问一个外链字体文件，之前提问过一次，那个跨域问题服务器同学也不好解决，所以想访问iconfont网站字体。此致敬礼，谢谢！

**Comment by purplebamboo** [comment]
@woden0415   亲  就是我说的那个问题哈。

你里面有个图标   是个% 这个图标有问题的，导致所有撑开

unicode是  e651  你删掉这个  重新生成就可以了哈

**Comment by woden0415** [comment]
@purplebamboo 果然可以了。刚才在查看字体的时候，确实发现那个计算器图标右上角多了个符号，但是没深入去想。在另一款软件里，一个一个图标删除后还是有这样的高度，所以就忽略了。
![](https://i.screenshot.net/6m0xxh6)

谢谢啦! ^_^
