### ISSUE TITLE
必须使用ai制作吗？

### ISSUE THREAD

**Issue by wyfang** [thx/iconfont-plus#36]
我用sketch制作导出svg，基本是不行的。

**Comment by Muqing1221** [comment]
不知道是不是解析路径的缘故，以前有同学用PS制作可以的，亲可以试下

**Comment by gongeek** [comment]
理论上svg都可以上传的 不一定要是ai制作的
上传有报错吗？出错的svg能发我邮箱(gongweiqm@qq.com)一下吗？
还是图标绘制的有问题？ http://iconfont.cn/plus/help/detail?helptype=draw

**Comment by Luke699** [comment]
我用Sketch输出的SVG经常会出现上传错误，但不是每一个图标都会，但是我本地用chrome大概svg图形都是正常预览的。

**Comment by gongeek** [comment]
@Luke699  出问题的svg 能发我邮箱一下吗 gongweiqm@qq.com？

**Comment by purplebamboo** [comment]
Sketch 目前支持不是太好，麻烦亲图标再发下，我们尽量做兼容
