### ISSUE TITLE
添加项目成员中无法增加一位内部用户

### ISSUE THREAD

**Issue by hinyon** [thx/iconfont-plus#361]
这位内部用户花名叫：两断；我们无法在添加用户的搜索列表中找到他。其他用户都添加正常。

![image](https://cloud.githubusercontent.com/assets/4123514/23110582/66c941c4-f75d-11e6-93df-c7632916dfcf.png)

**Comment by purplebamboo** [comment]
是这样的  需要这个用户 先登陆一下哈，这样才能找到这个用户 如果还找不到。

让他点击个人主页 看下自己的  用户名  用这个去搜索哈。
