### ISSUE TITLE
彩色的iconfont 在页面里显示全是灰色

### ISSUE THREAD

**Issue by youniuben** [thx/iconfont-plus#366]
地址：http://www.iconfont.cn/plus/manage/index?manage_type=myprojects&spm=a313x.7781069.1998910419.10.jurvx6&projectId=97076

**Comment by gongeek** [comment]
是在iconfont的页面是灰色的，还是你网站项目应用的是灰色的？
如果要在网站应用彩色图标 请使用symbol 方式，http://www.iconfont.cn/plus/help/detail?helptype=code
