### ISSUE TITLE
部分浏览器下图标显示不全问题

### ISSUE THREAD

**Issue by fox19920726** [thx/iconfont-plus#367]
Hi，我最近发现一个问题，16像素的图标，显示不全，如图：
![default](https://cloud.githubusercontent.com/assets/7921911/23347713/1ceb5010-fcdf-11e6-8f15-074630836d04.png)
正常显示应该是：
![image](https://cloud.githubusercontent.com/assets/7921911/23347738/3ffebf4c-fcdf-11e6-83eb-a46d908c9153.png)
然后我为了解决这个问题，我把图标调整成了17像素，然后图标就正常显示了，请问大家这个是什么原因呀？
复现浏览器：360浏览器（极速模式和兼容模式），QQ浏览器（兼容模式）

**Comment by purplebamboo** [comment]
不同浏览器的 渲染逻辑不同。

所以一般设计图标时不要 撑满整个画布。

可以在项目里编辑，把图标适当缩小点哈。
