### ISSUE TITLE
搜索关键词：时间，有图标因为尺寸问题影响了排版

### ISSUE THREAD

**Issue by kaeyleo** [thx/iconfont-plus#37]
如题

**Comment by Muqing1221** [comment]
理解，因为现在审核机制只存在于图标库层级，如果用户仅仅是上传图标，不会进入审核流程~所以可能会出现一些暂时不可控的影响美观度的问题
但之后我们会设定相应规则，如优化搜索结果的权重配比，增添图标的报错机制等等，现在还都是我的yy~但已拿出小本本记下亲的建议~以后逐步践行~

**Comment by Muqing1221** [comment]
理解，因为现在审核机制只存在于图标库层级，如果用户仅仅是上传图标，不会进入审核流程~所以可能会出现一些暂时不可控的影响美观度的问题
但之后我们会设定相应规则，如优化搜索结果的权重配比，增添图标的报错机制等等，现在还都是我的yy~但已拿出小本本记下亲的建议~以后逐步践行~

**Comment by purplebamboo** [comment]
目前还不能控制用户上传的图标的质量，后期我们会想办法出一个  举报机制。。不过最近忙双十一，可能要稍等一段时间
