### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by nftstudio** [thx/iconfont-plus#375]
首先，登录随时都登录不上，赶紧弄个你们自己的会员系统。
其次，图标库能不能分开？分开就是说，我的图标库里的图标就只在这个图标库里显示，不在其他库显示。
暂时先把自己做的图标删除了，等你们的会员系统出来了再说了。

**Comment by purplebamboo** [comment]
囧  精力有限，做会员系统需要额外多出好多东西，注册，密码找回，验证，过滤等等等等。

图标库本来就可以分开呀，你可以把一部分图标单独放到一个图标库里不放到其他地方呀。

**Comment by nftstudio** [comment]
好把 会员系统 这个不说 图标库的意思是：比如我上传了图标，然后在我的图标里会看见，对吧，然后我建立一个图标库，在我的图标里选择了图标，图标就之在这个新建立的图标库里。我的图标这个页面是看不到已经选择的图标的。这样的话对作者分类的话会不会很方便（设计师一般都有强迫症的……）。

**Comment by nftstudio** [comment]
再补充一些话：图标上传，我是想按我编号好的顺序显示。结果无效。这个就不说了，上传之后，编号也不给我去掉…啥也不说了，我得去删掉编号。

**Comment by veryweb8** [comment]
看能否支持
