### ISSUE TITLE
可以根据作者来显示他提供的所有图标吗？

### ISSUE THREAD

**Issue by kaixinsoft** [thx/iconfont-plus#376]
比我我搜索“继续”，看到相关“继续”的icon，点某个下载，可以看是某个作者提供的，然后我点击这作者，到达他的url：如 http://www.iconfont.cn/plus/user/detail?userViewType=collections&uid=95007。但是网页显示 “暂时木有内容呀～～”。是不是他的链接下，应该显示他的所有图标呢？

**Comment by purplebamboo** [comment]
因为可能有侵权的风险，目前只能看到这个作者公共库的图标，还有搜藏的图标。

＝ ＝ 主要现在搜索比较单一，搜素是可以搜索所有的图标的，包括上传的图标，这个我们后面会想办法改造一下。
