### ISSUE TITLE
big5繁体转码后，字体图标无法显示

### ISSUE THREAD

**Issue by woden0415** [thx/iconfont-plus#377]
公司的网站需要经过**一个程序**将页面简体转为繁体，但是转为繁体后icon图标成方框了。
这是[公司简体网站](http://www.gtja.com/i/)，[繁体版](http://big5.gtja.com/i/)。
考虑到这个程序也会编译字体文件，所以我在icon.css文件里把*.ttf文件指向简体版官网，但是出现了这个错误。*Failed to decode downloaded font*,*OTS parsing error: incorrect file size in WOFF header*。打开[繁体版](http://big5.gtja.com/i/)官网，控制台会有提示。
谢谢查看，静候佳音^_^

**Comment by xinglie** [comment]
你简体是这样处理的：
![image](https://cloud.githubusercontent.com/assets/1290017/23657758/b5476b4a-037a-11e7-821b-b9a599084045.png)

字体文件和当前网站在一台服务器上。

而到了繁体变成了下面这样子：
![image](https://cloud.githubusercontent.com/assets/1290017/23657818/e1194c34-037a-11e7-9252-34df9bf51283.png)

字体文件在另外一台服务器上，同时没有设置cors的响应头　所以导致字体无法显示。

http://www.ruanyifeng.com/blog/2016/04/cors.html

字体文件也需要设置，否则也会不成功，你看iconfont官网使用的字体就是这样的：

![image](https://cloud.githubusercontent.com/assets/1290017/23657981/b08c3d8c-037b-11e7-8706-f2b78bdec02d.png)

官网域名是iconfont.cn，但是字体在at.alicdn.com上，能显示是因为下面：
![image](https://cloud.githubusercontent.com/assets/1290017/23658348/2468f5fa-037d-11e7-89bd-b5d7e5eedcce.png)

这个要设置的，不设置不能跨域，如果不方便设置，就把字体和网站放在同一台服务器上，不要跨域

**Comment by woden0415** [comment]
谢谢
