### ISSUE TITLE
希望能在项目下还能建立子级文件夹

### ISSUE THREAD

**Issue by wuxiayehan** [thx/iconfont-plus#378]
因为很多时候我们建立是以项目单位建立，但是项目里面还会有很多分类内容，很多icon全放在一个项目下的话，不是很好找～

谢谢大神们能提供这样方便的平台，希望越来越好～

**Comment by purplebamboo** [comment]
明白 这个我们再考虑下，我再找交互设计师讨论看看

**Comment by yisibl** [comment]
请关注：Duplicate of #1496
