### ISSUE TITLE
下载失败 

### ISSUE THREAD

**Issue by CIACloud** [thx/iconfont-plus#379]
{"code":500,"message":"LOGIN REQUIRED"}

为何提示需要登录

**Comment by purplebamboo** [comment]
亲  有详细的场景吗？什么浏览器？

**Comment by menglong-li** [comment]
chrome，一开始可以下载，但迅雷下载以后压缩包损坏。多次以后迅雷阻止该链接继续下载。然后就提示如楼主的问题。

**Comment by purplebamboo** [comment]
亲  不要用迅雷下载哈。
