### ISSUE TITLE
无法绑定多个OA

### ISSUE THREAD

**Issue by Tokinx** [thx/iconfont-plus#38]
如果用微博登录，无法再继续绑定GitHub，这个很不科学啊。

难道不是应该：

微博登录后，在设置里还可以选择追加绑定GitHub吗？

平时根本不用微博，最近微博必须要求客户端扫二维码登录了，我难以接受

**Comment by purplebamboo** [comment]
哈 但是我们的账号是两个独立的账号来着。  ＝ ＝  ，好像实现起来有点复杂。

**Comment by purplebamboo** [comment]
算是优化点，这里统一讨论：

https://github.com/thx/iconfont-plus/issues/139
