### ISSUE TITLE
最新功能建议

### ISSUE THREAD

**Issue by 360060316** [thx/iconfont-plus#380]
1.可以自动调整图标为最大。每个图标大小不一很烦恼。
2.字体地址可以固定地址，每次添加图标要重新生成麻烦。

**Comment by purplebamboo** [comment]
自动调整有点难办哎，因为没有衡量标准。  图标大小不一，可以使用统一公共库的图标，或者自己编辑微调哈。

字体地址不适合固定，因为不能影响已有的项目，比如你已经用在线上了，这时预发使用加了一些icon，不能影响到线上呀。

**Comment by nimojs** [comment]
挺尴尬的，有些图标并不适合填满。
只能是设计师都按照 http://iconfont.cn/plus/help/detail?helptype=draw 来做，
并且 左箭头这种`<` 需要设计师自己考虑是四周至少留一格，还是留多格。
