### ISSUE TITLE
iconfont下载后字体全部变长，下面空白很多。

### ISSUE THREAD

**Issue by xuminjing** [thx/iconfont-plus#381]
以前的项目是好的，现在下载后，字体很长，打开ttf看，多了一个没见过的图标，不知如何删除，项目链接http://www.iconfont.cn/plus/manage/index?manage_type=myprojects&spm=a313x.7781069.1998910419.10.v9oSw5&projectId=103865&keyword=

**Comment by purplebamboo** [comment]
亲 这个一般都是里面有个icon有问题 撑开了整个字体，用二分排除法，可以找出来这个icon，删掉重新生成字体就行了。

**Comment by purplebamboo** [comment]
应该就是这个问题哈  有疑问再重新打开这个issue哈。
