### ISSUE TITLE
能否把一些自己上传的图标设为私有

### ISSUE THREAD

**Issue by sanzhumu** [thx/iconfont-plus#382]
能否把一些自己上传的图标设为私有，因为有些图标是注册商标，被别人误用可能会有侵权问题。

**Comment by purplebamboo** [comment]
上传后   可以设为隐私图标库。

**Comment by purplebamboo** [comment]
不过 目前所有的图标都是可以被搜索的，亲是不想被搜索到吗？

**Comment by sanzhumu** [comment]
是的，被搜索到就有被使用的风险。

**Comment by purplebamboo** [comment]
明白  这个需要改造下引擎，我们后续考虑下 可以只能搜索到  公开库的图标。

不过改造起来有点麻烦。

**Comment by sanzhumu** [comment]
嗯，好的，理解

**Comment by yisibl** [comment]
私有化图标已经支持，在 我的图标→我上传的 icon→点击批量操作→批量私有
