### ISSUE TITLE
转让项目后项目丢失

### ISSUE THREAD

**Issue by birdplane9527** [thx/iconfont-plus#385]
昨天把我建的一个项目转让后，几天我和我转让给的那位同事的项目都莫名其妙的丢失了，只能来这里求助下看有没有希望恢复...

**Comment by purplebamboo** [comment]
你好 亲 很抱歉给你带来了不好的体验

项目名称是什么我先看看能不能查到
还有用户名也给我下

至于这个问题我后续再详细看看。。

**Comment by birdplane9527** [comment]
@purplebamboo 项目名称是女神有财 转让后项目所有者是昵称是 nvshenyoucai  我的昵称是treeeeeees

**Comment by purplebamboo** [comment]
好的 不过电脑不在身边 

明天我帮你看看哈

**Comment by birdplane9527** [comment]
好的 多谢啦

**Comment by birdplane9527** [comment]
@purplebamboo 请问有结果了么..

**Comment by purplebamboo** [comment]
亲  我搜了下  囧 搜不到这个项目了哎

**Comment by purplebamboo** [comment]
是不是  被项目成员删除了呢

**Comment by birdplane9527** [comment]
我们两个项目成员都没有删除啊..

**Comment by purplebamboo** [comment]
亲 项目的 应用代码有吗？ 里面有项目id 我再查一下

**Comment by birdplane9527** [comment]
我发你那个163的邮箱吧

**Comment by purplebamboo** [comment]
好的

**Comment by purplebamboo** [comment]
亲  也搜索不到。。囧  应该是被删除了。

你们没有加其他协助者吗？

**Comment by birdplane9527** [comment]
没有..

**Comment by purplebamboo** [comment]
女神有材  是不是这个？

**Comment by birdplane9527** [comment]
是的

**Comment by purplebamboo** [comment]
亲  我先帮你放到  nvshenyoucai  这个名称下哈。你登陆后应该可以看到。

应该是触发了啥隐藏bug。


亲  转让时  有报错吗？

**Comment by birdplane9527** [comment]
当时没报错 转让之后过了一天才消失 
我treeeeeees这个账号下现在还是看不到这个项目

**Comment by purplebamboo** [comment]
在  nvshenyoucai 这个用户下面哈

**Comment by birdplane9527** [comment]
好的 多谢~
