### ISSUE TITLE
项目莫名没有了是怎么回事？

### ISSUE THREAD

**Issue by ShenJianShou** [thx/iconfont-plus#389]
今天下午登录后发现项目都被删除了，请问是什么原因？还能找回吗？

**Comment by purplebamboo** [comment]
项目id可以提供下吗？

**Comment by ShenJianShou** [comment]
具体怎么查找呢？项目已经被删除了 通过账户名可以查到吗？

**Comment by purplebamboo** [comment]
账户名 提供下哈。我查找看看

**Comment by ShenJianShou** [comment]
好的 通过微博登陆的 账户名是admin@bihu.mobi

**Comment by purplebamboo** [comment]
额。亲 不是这个吧。。这个看着像邮箱

**Comment by purplebamboo** [comment]
点设置 看下昵称哈

**Comment by ShenJianShou** [comment]
我们是通过微博账号登陆的 你需要的账户是指？

**Comment by ShenJianShou** [comment]
昵称是：神箭手云爬虫

**Comment by purplebamboo** [comment]
主页  点头像  点 设置  进入个人中心页面   看下昵称是啥

**Comment by ShenJianShou** [comment]
昵称是：神箭手云爬虫

**Comment by purplebamboo** [comment]
亲  会不会被你们的协助者删除了额？  我查了下 好像查不到。账号下一个项目都没有

**Comment by ShenJianShou** [comment]
是的 之前就只有一个项目 今天登陆发现没有了 还能找回吗？

**Comment by ShenJianShou** [comment]
或者能查到上次登陆删除的时间 方便我们查找是谁删除的吗？

**Comment by purplebamboo** [comment]
囧  目前没有做这个日志。。。。或者你之前有在哪里用过这个项目吗？把代码贴出来  

我再找找看

**Comment by ShenJianShou** [comment]
代码具体是指？我问问开发 另外还能恢复吗？

**Comment by purplebamboo** [comment]
如果真的被删除了  就恢复不了哎。
