### ISSUE TITLE
建议增加账户协同功能

### ISSUE THREAD

**Issue by amasun** [thx/iconfont-plus#392]
这样UI设计师就可以直接将设计的iconfont项目直接在线交给Front End 同学了，不需要浪费FE同学切图时间

**Comment by nimojs** [comment]
现在的功能不就是直接下载文件使用么？
http://iconfont.cn/plus/help/detail?helptype=code

**Comment by purplebamboo** [comment]
亲  现在就有呀  生成项目  增加前端同学使用就行
