### ISSUE TITLE
symbol引用在react jsx中解析报错

### ISSUE THREAD

**Issue by yangkai314** [thx/iconfont-plus#393]
<svg className="icon" aria-hidden="true">
            <use xlink:href="#icon-sousuo-sousuo"></use>
          </svg>

报错
ERROR in ./src/components/nav/index.js
Module build failed: SyntaxError: D:/wamp/www/react-express-blog/src/components/nav/index.js: Namespace tags are not supported. ReactJSX is not XML.

         <i>
          <svg className="icon" aria-hidden="true">
           <use xlink:href="#icon-sousuo-sousuo"></use>
              ^
         </svg>
       </i>

**Comment by NE-SmallTown** [comment]
报错写的很清楚了呀，这本身就和iconfont没关系。随便搜索下就有，你应该用xlinkHref
