### ISSUE TITLE
建议增加图标私有化的功能

### ISSUE THREAD

**Issue by bashen1** [thx/iconfont-plus#394]
建议增加图标私有化的功能，项目中的有些图标不想共享出来。特别是自己做的一些图标

**Comment by purplebamboo** [comment]
考虑中，比较麻烦，需要改造搜索引擎哈。再给我门点时间

**Comment by miaoyuxinbaby** [comment]
@purplebamboo  2019年了，请问有私有化功能了吗？

**Comment by yisibl** [comment]
私有化图标已经支持，在 我的图标→我上传的 icon→点击批量操作→批量私有
