### ISSUE TITLE
如何把Weibo账户的项目转移到Github账户里？

### ISSUE THREAD

**Issue by ec2ec** [thx/iconfont-plus#397]
由于Weibo账户老是无法登录，想把原先账户里面的项目转移到新Github账户里，该如何实现啊？

**Comment by purplebamboo** [comment]
可以 转让项目的。

现在微博账户完全登陆不上了？

如果是这样，可以提供下  两个账号，我可以帮你操作下。

**Comment by ec2ec** [comment]
微博登陆不了啊。。soec@163.com ，麻烦全部转到 现在这个账户，谢谢

**Comment by purplebamboo** [comment]
ec2ec 是这个用户名吗？ 已经转过去了哈。

**Comment by ec2ec** [comment]
GOOD！非常感谢！

**Comment by Svmtimend** [comment]
@purplebamboo 
请问还能帮忙操作下吗？微博帐号：fangya1990@qq.com，希望转到这个github帐号中来，谢谢！

**Comment by Svmtimend** [comment]
@purplebamboo 
  请问还能帮忙操作下吗？微博帐号：fangya1990@qq.com，希望转到这个github帐号中来，谢谢！
