### ISSUE TITLE
怎么合并两套图标

### ISSUE THREAD

**Issue by LeeRayno** [thx/iconfont-plus#403]
因为项目之前用了一套图标，是直接下载的，没有在iconfont上面建项目，现在需要新增一些图标，需要重新添加一些图标，所以需要再下一套图标，怎么合成这两套图标。

**Comment by purplebamboo** [comment]
奥  可以使用一个开源库。

可以直接用开源库把字体的svg全部导出来，再重新上传到平台就行了。


https://github.com/purplebamboo/font-carrier
