### ISSUE TITLE
实体填充可现实,空心描边(stroke)的上传就是空白

### ISSUE THREAD

**Issue by xs23933** [thx/iconfont-plus#404]
有人遇到过这样的么
x.svg

 &lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  --&gt;
&lt;svg version="1.1" id="layout_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 1024 1024" style="enable-background:new 0 0 1024 1024;" xml:space="preserve"&gt;
&lt;path style="fill:none;stroke:#000000;stroke-width:24;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;" d="
	M653.22,419.11v-34.89h37.51c15.48,0,28.04-10.84,28.04-24.22v-63.47c0-13.38-12.55-24.22-28.04-24.22h-111.8
	c0.02-0.48,0.04-0.95,0.04-1.44V108.94c0-20.58-19.31-37.27-43.14-37.27h-48.66c-23.82,0-43.14,16.69-43.14,37.27v161.93
	c0,0.48,0.02,0.96,0.04,1.44h-111.8c-15.48,0-28.04,10.84-28.04,24.22v63.47c0,13.38,12.55,24.22,28.04,24.22h37.51v34.89
	c-39.81,2.85-71.1,31.66-71.1,66.79v6.99v17.76v414.9c0,17.56,16.47,31.79,36.79,31.79h352.05c20.32,0,36.79-14.23,36.79-31.79
	v-414.9v-17.76v-6.99C724.32,450.76,693.03,421.96,653.22,419.11z"/&gt;
&lt;/svg&gt;

上面的是有问题的

y.svg

这个是上传正常的
实体填充的

&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;!-- Generator: Adobe Illustrator 21.0.0, SVG Export Plug-In . SVG Version: 6.00 Build 0)  --&gt;
&lt;svg version="1.1" id="layout_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 1024 1024" style="enable-background:new 0 0 1024 1024;" xml:space="preserve"&gt;
&lt;path style="stroke:#000000;stroke-width:20;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;" d="M644.89,415.46
	v-35.28h35.35c14.6,0,26.43-10.96,26.43-24.49v-64.16c0-13.52-11.83-24.49-26.43-24.49H574.86c0.02-0.48,0.04-0.96,0.04-1.45V101.9
	c0-20.81-18.2-37.68-40.66-37.68h-45.87c-22.46,0-40.66,16.87-40.66,37.68v163.7c0,0.49,0.02,0.97,0.04,1.45H342.36
	c-14.6,0-26.43,10.96-26.43,24.49v64.16c0,13.52,11.83,24.49,26.43,24.49h35.35v35.28c-37.53,2.88-67.02,32-67.02,67.52v7.06v17.96
	v419.43c0,17.75,15.53,32.13,34.68,32.13h331.85c19.15,0,34.68-14.39,34.68-32.13V507.99v-17.96v-7.06
	C711.91,447.46,682.42,418.34,644.89,415.46z"/&gt;
&lt;/svg&gt;

**Comment by xs23933** [comment]
对比了下, &lt;path 下的样式 fill:none; 为无填充空心的时候上传就是空白

**Comment by xs23933** [comment]
在chrome safari 上看都是正常 osx 下预览正常 ai 2017制作的
上面这2段代码皆可保存为 svg格式即可看 往谁知道帮忙建议下啥问题呢

**Comment by gongeek** [comment]
平台不支持这种通过对路径描边画的图像的解析，需要转换下。例如第一段代码中的 stroke-width:24;stroke-linecap:round;stroke-linejoin:round;stroke-miterlimit:10;" 这些属性不支持解析。

你试下ai中的“路径—轮廓化描边” 看能不能解决这种问题，转换后再上传应该是你想要的效果。见下图：

![image](https://cloud.githubusercontent.com/assets/3911824/24182184/f0fcc186-0efa-11e7-8f9d-69db30768ed7.png)
