### ISSUE TITLE
增加第三方登录

### ISSUE THREAD

**Issue by sayhellovip** [thx/iconfont-plus#405]
强烈建议增加第三房的登录，如QQ，微信！！！强烈建议增加第三房的登录，如QQ，微信！！！

**Comment by okyansoft** [comment]
我真不明白这么一个强大的平台为何逼我们翻墙来github？ 现在有那么多第三方登录，微博又不能登录   GitHub又不能登录

**Comment by benxiaohai1212** [comment]
为什么不对接国内的git平台，如gitee.com做第三方平台登录呢？如果哪一天github不能用了。是不是大家做的字体库就都拿不回来了。

**Comment by yisibl** [comment]
现在手机注册登录功能已经上线，不再依赖三方登录。[点击查看](https://mp.weixin.qq.com/s?__biz=Mzg5OTUzNjQ0Mg==&mid=2247483866&idx=1&sn=e6d02ca84cba8157c8f90d072db66bbf&chksm=c050828ff7270b99b00d784681a47fb4d1063a9139732075dc84d8da4ad77d446df386384acc&token=1155149842&lang=zh_CN#rd)

相关 issue：#1718
