### ISSUE TITLE
icon在IE8下，强制刷新图标会消失。

### ISSUE THREAD

**Issue by XiaoqingZhou** [thx/iconfont-plus#406]
在其他主流浏览器上图标均可正常显示。用有些电脑的IE8打开时，再在当页ctrl+F5，图标会消失。是什么情况了？？注：在IE8下不会图标消失的电脑上用IEtester打开点击刷新，图标也会消失。。

**Comment by purplebamboo** [comment]
消失后就一直空白吗？
亲 可以提供更详细的信息吗？
