### ISSUE TITLE
建议搜索到的图标可以找到属于哪个图标库

### ISSUE THREAD

**Issue by joybbs** [thx/iconfont-plus#409]
通过关键词搜索到图标，但是不知道这个图标来自哪个图标库。

**Comment by rechal-liu** [comment]
复议，这样就可以参考一套的图标库，很容易找到其反义的图标。

**Comment by purplebamboo** [comment]
亲  目前平台是有这样的功能的 只是比较隐蔽。

如果这个图标属于某个图标库，那么点击下载 是可以看到那些图标库的点击进去就行了。
