### ISSUE TITLE
新版的多色图标代码可编辑性欠缺部分说明！

### ISSUE THREAD

**Issue by DX-WEB** [thx/iconfont-plus#41]
1.尝试一番才发现多色图标并不是任何部位都可以用例如：color:#f46;修改。
2.相对于每个图标只能用代码修改图标中的一个颜色，而不能用代码修改单个图标中其它部分的颜色。
3.然而并没有看到相关的文字提示只能修改图标的一个颜色，希望对于多色图标的代码可编辑性能在“帮助”里面增加相应的文字说明。

**Comment by gongeek** [comment]
看看这里 https://github.com/thx/iconfont-plus/issues/13
