### ISSUE TITLE
阿里妈妈UED除了iconfont，我们还搞了这个黑科技...问题来了。

### ISSUE THREAD

**Issue by keyus** [thx/iconfont-plus#414]
阿里妈妈UED除了iconfont，我们还搞了这个黑科技...

问题来了，我们非阿里系的什么时候才能用上。

**Comment by purplebamboo** [comment]
设计师老大让我回：  你猜

嗯 原话，目前还没考虑对外哈，以后可能会的，亲可以期待下。O(∩_∩)O
