### ISSUE TITLE
上传画布20*20的图片，不知为什么unicode和font-class生成的图标宽高比为20:19，而symbol则是20:20

### ISSUE THREAD

**Issue by nuonuoge** [thx/iconfont-plus#417]
环境：
chrome浏览器49，火狐浏览器50 window/linux
不知道是不是对16-24的画布做了特殊处理
20:19宽高比，当font-size为偶数px，在用flex垂直居中时需要做额外处理

**Comment by purplebamboo** [comment]
不是看的太明白，亲可以说的详细点吗》

unicode和font-class 生成的是字体，本身会有些各种转换。

而symbol直接是svg所以二者直接的确可能有细微的差别

**Comment by nuonuoge** [comment]
上传了20*20的图片后，我期望生成的字体当设置font-size为20时，图标大小是20*20，而unicode和font-class是20*19，并不是方正的20*20的size， 我试了一些icmoon的网站他们生成的是20*20的，不知道阿里这个为什么是20*19
