### ISSUE TITLE
在图标绘制规范文档中发现一个中文错别字（Typo）

### ISSUE THREAD

**Issue by benweizhu** [thx/iconfont-plus#419]
http://iconfont.cn/help/iconmake.html

![image](https://cloud.githubusercontent.com/assets/5471228/24608970/63952378-18ab-11e7-8c69-792055e94532.png)

**无发**转译未闭合曲线的图形的。

**Comment by purplebamboo** [comment]
收到  我抽空改掉。。。感谢反馈。。。。
