### ISSUE TITLE
无法设置项目名称

### ISSUE THREAD

**Issue by juechenshiai** [thx/iconfont-plus#42]
在购物车中新建项目后，项目名为空，编辑项目修改项目名称后依然为空

**Comment by Muqing1221** [comment]
点保存了么~
亲方便详细描述一下么，因为我测试是Ok的

**Comment by juechenshiai** [comment]
感觉不太稳定，有时候正常，有时候又会出现，频率不高

**Comment by Muqing1221** [comment]
不知道会不会跟浏览器或者操作系统有关什么的，下次如果还出现这种情况，亲可以描述详细些~比如哪个浏览器哪个版本，不是不是OS的sierra 10.22
