### ISSUE TITLE
如果对icon 修改了大小，在ajax后，显示不了图标

### ISSUE THREAD

**Issue by ketuzhong** [thx/iconfont-plus#422]
如上，

只能在浏览器调试模式下，审查元素，修改图标的样式才会在出现

**Comment by purplebamboo** [comment]
不是很明白亲的意思呀。有具体场景吗？

**Comment by ketuzhong** [comment]
比如：

html中的ajax片段（即ajax后才出现的内容）:
`<div class="ajax-content"><i class="icon"></i></div>`

css:
`.icon {
  font-size: 20px;
}`

这样的场景下，图标显示不出来。只能在浏览器调试模式下，修改图标的样式才会出现
