### ISSUE TITLE
请问怎么解决图标跟文字水平对齐问题

### ISSUE THREAD

**Issue by teojs** [thx/iconfont-plus#424]
为什么我上传的图标很规范，使用的时候总是无法跟文字垂直居中并排，安卓跟iOS显示也有差距，请问大神们有这个问题吗？不用line-height的情况下是怎么解决的？

**Comment by purplebamboo** [comment]
vertical-align -1px

用这个慢慢调哈，每个字体都有自己的基线，很难完全对其的。
