### ISSUE TITLE
登录不了

### ISSUE THREAD

**Issue by xiaoxiaocao** [thx/iconfont-plus#425]
登录老提示失败

**Comment by 7852468** [comment]
我也是经常登录失败

**Comment by sabery1** [comment]
总是登录失败，，{"code":500,"message":"LOGIN REQUIRED"}

**Comment by yisibl** [comment]
现在我们支持手机登录了，不再依赖三方登录。
![image](https://user-images.githubusercontent.com/2784308/134634348-c6142d13-bff6-4df9-9600-e744661afe77.png)

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
