### ISSUE TITLE
去掉颜色保存有问题

### ISSUE THREAD

**Issue by GP2513** [thx/iconfont-plus#426]
![qtp 88 pq103f d hw8a3k](https://cloud.githubusercontent.com/assets/11567527/24902835/092cb520-1ede-11e7-87a5-f25f2aa4a1ea.png)
去掉颜色保存就变成实心的了这是为什么

**Comment by purplebamboo** [comment]
因为 这个图标没有分层哈，是直接堆在上面的，当你去掉颜色  因为大家都是一个颜色呀，所以你就看不到上面盖着的小东西了
