### ISSUE TITLE
【功能建议】翻页的按钮做大点。

### ISSUE THREAD

**Issue by deifk** [thx/iconfont-plus#427]
现在的下一页、上一页的按钮。太小了，不方便点击

**Comment by purplebamboo** [comment]
哈 我向设计师反馈过，= = 暂时他们还是坚持，嗯 这个锅就让 设计师妹妹背了

**Comment by yisibl** [comment]
翻页按钮已经调整的更大了，感谢您的支持。
![image](https://user-images.githubusercontent.com/2784308/72678257-45b79a80-3adf-11ea-94f4-b06a2e902a77.png)
Duplicate of #1513
