### ISSUE TITLE
png下载的图片会被切边

### ISSUE THREAD

**Issue by caisd1998** [thx/iconfont-plus#431]
我们项目里的很多圆形图片，编辑时发现下边和右边有稍微超过边界，下载png下来后发现下边和右边会有部分被切掉。
这个在原始设计里是没有的。

**Comment by purplebamboo** [comment]
额 亲可以在线编辑，缩放一下哈。

建议设计图标的时候就不要撑满哈。

**Comment by caisd1998** [comment]
@purplebamboo 一个字体图像，设计的时候撑满的话，上传到iconfont网站后再下载png会被截断，我觉得这个是网站的问题吧？为什么设计时撑满（但没有越线）后，在iconfont网站却会有问题？
