### ISSUE TITLE
图标上传后在‘我的图标’里面啥都没有

### ISSUE THREAD

**Issue by kenicya** [thx/iconfont-plus#434]
上传图标的按钮找半天不说！上传之后再我的图标里面怎么都没有，上传无数次还是没有！！！这是什么大bug啊？？？

**Comment by purplebamboo** [comment]
亲  你是不是没有点击完成上传？

是这样的  上传后只是个中间状态，需要点击完成上传，才是真的跑到我的图标下面的哈。

**Comment by kenicya** [comment]
后面发现了~~~~(>_<)~~~~上传按钮要滚动到下面才看到，屏幕比较小就忽略了这个操作，可以改进下按钮位置

**Comment by purplebamboo** [comment]
嗯嗯 好的 我找设计师去
