### ISSUE TITLE
啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊啊又怎么登录不了啊！！！

### ISSUE THREAD

**Issue by FortuneDream** [thx/iconfont-plus#436]
新版还没有旧版好用，内定的颜色没有以前的那些好看了！！！
现在都登录不上了！！！！
Github不行！
新浪也不行！！！

**Comment by gongeek** [comment]
亲，现在可以登入了

**Comment by FortuneDream** [comment]
666666666666666.之前的那种白色版本没有维护了？（那个白色版本进行搜索可以选择的颜色更加好看的。。。。）

**Comment by FortuneDream** [comment]
666666666666666.之前的那种白色版本没有维护了？（那个白色版本进行搜索可以选择的颜色更加好看的。。。。）
