### ISSUE TITLE
功能建议: 希望增加整套图标一键收藏/添加至项目 的功能

### ISSUE THREAD

**Issue by SilenceDN** [thx/iconfont-plus#439]

**Comment by NameNull** [comment]
me too , 项目转移还要一个个图标点 麻烦

**Comment by purplebamboo** [comment]
额。。其实有批量添加功能的，= = 也有全选功能的。

整套图标库的收藏我们一直想做呢，只是实在没有时间，业务实在太忙了。

**Comment by pcloth** [comment]
@purplebamboo 所以。。。批量添加和全选功能到底在哪里？看了你的回复又去网站找了N遍，没找到，请指教。

**Comment by yisibl** [comment]
图标库收藏功能已经实现。
