### ISSUE TITLE
建议多账号关联

### ISSUE THREAD

**Issue by juechenshiai** [thx/iconfont-plus#44]
建议多账号关联，现在github账号登录和微博账号登录是分开的，建议关联一下

**Comment by slimcheng** [comment]
同样建议多账号关联，很久以前就开始用了，当时用的是微博登录，但是现在微博基本都不用了，希望能再同时关联github

**Comment by purplebamboo** [comment]
目前有点麻烦，因为每个账号下面都可能有自己的 项目，图标库啥的。如果关联的话，这两边的内容是要放在一起吗？那又会涉及到各种同步的问题。

**Comment by HADB** [comment]
建议还是通过多账号关联的方式进行吧。另外新增一个账号合并的功能，用于合并已经分别通过github和微博登录过的账户。

**Comment by purplebamboo** [comment]
账号体系的问题，这里统一讨论吧：
https://github.com/thx/iconfont-plus/issues/139
