### ISSUE TITLE
项目添加用户查找不到什么原因

### ISSUE THREAD

**Issue by NameNull** [thx/iconfont-plus#441]
* 添加项目成员若不存在按回车后报错
![image](https://cloud.githubusercontent.com/assets/11754843/25111662/df979fe0-241e-11e7-90ee-89a70f2fe724.png)

**Comment by purplebamboo** [comment]
嗯嗯  这个我们优化下。

另外 亲 如果要添加一个人，这个人需要先在平台上登录一下哈。
