### ISSUE TITLE
CDN挂了？

### ISSUE THREAD

**Issue by sentsin** [thx/iconfont-plus#442]
at.alicdn.com

**Comment by gongeek** [comment]
没有吧 自己访问文件应该是可以的

**Comment by purplebamboo** [comment]
我试了下 没有啊亲  cdn是 阿里云的cdn，稳定性还是有保障的。目前很多淘系的都在用没有人反馈呀

**Comment by sentsin** [comment]
@gongeek @purplebamboo 这是官网的异常请求：http://at.alicdn.com/t/font_jexf5v7k4qkyy14i.css

**Comment by purplebamboo** [comment]
可以打开呀，亲 是不是你的网络问题，试试直接用手机4g打开呢。

**Comment by sentsin** [comment]
嗯，的确是我网络问题
