### ISSUE TITLE
iconfont字体异常

### ISSUE THREAD

**Issue by allan2coder** [thx/iconfont-plus#443]
自己网站的项目字体图标无法正常显示，都是框
打开天猫和淘宝网站也是，图标都是框
![11111](https://cloud.githubusercontent.com/assets/14307551/25119644/95473b6a-244d-11e7-8a31-ccb80e870909.jpg)

**Comment by wyy9630** [comment]
可能跟网络有关系，之前我们公司内网也这样，换手机热点就可以了，你可以试试

**Comment by iconfont-cn** [comment]
亲 是不是你的网络 屏蔽了阿里的cdn域名。
