### ISSUE TITLE
项目一改名 啥都没了 哭

### ISSUE THREAD

**Issue by wangwenjie1314** [thx/iconfont-plus#450]

**Comment by purplebamboo** [comment]
你好  项目名称给我下？ 还有 用户名也给我下？

**Comment by wangwenjie1314** [comment]
用户名：文杰 （我是用微博关联登录的）
项目名字： 修改前叫：事事项目图标 ；修改后叫：ethings项目图标

你查下数据库看看有没有，要是没有，我再想想是不是这个名字，辛苦

**Comment by purplebamboo** [comment]
项目可以找回 放心 亲。

请问下  你的具体操作步骤是？ 协助我排查下问题哈。
是  http://www.iconfont.cn/plus/manage/index?manage_type=myprojects 这里修改名称的吗？

**Comment by wangwenjie1314** [comment]
对的，我是在你发的链接 个人中心- 我发起的项目 （我回放一下操作：我添加几个新图标到购物车，然后购物车到我改名的项目，放里面以后我 点击更多操作-编辑项目-保存 ： 报错 invalid error 好像是）

**Comment by wangwenjie1314** [comment]
我改名的项目里面算上我共两个成员；图标在300多个，

**Comment by purplebamboo** [comment]
好的 我先帮你恢复哈。

**Comment by purplebamboo** [comment]
先帮你恢复了哈，具体原因 我再看下。。。

**Comment by wangwenjie1314** [comment]
感谢大兄弟，挽救了我的case
