### ISSUE TITLE
旧版iconfont下用淘宝账户登录项目的找回问题

### ISSUE THREAD

**Issue by 17khba** [thx/iconfont-plus#454]
#### 记得旧版iconfont里有**淘宝**账户登录的选项，有几个项目存放在里面，麻烦帮忙找回下。谢谢，祝快乐！

![account](https://cloud.githubusercontent.com/assets/7893589/25465854/7a11919c-2b37-11e7-9b2e-5cac9c4750cf.png)

淘宝账户登录信息如上图：
+ uid：254735
+ iconfont用户名：17khba
+ 签名：Less is more...

现在使用的是新浪登录的帐号：
+ uid：55187
+ iconfont用户名：17khba（同上）
+ 签名：生命不止，折腾不息…

**Comment by purplebamboo** [comment]
你好 亲  Less is more...  这个我查了下 是用的github登录的。

我帮你转给微博账号哈

**Comment by 17khba** [comment]
自己记错了，麻烦了！
