### ISSUE TITLE
无法批量下载

### ISSUE THREAD

**Issue by michaeltimber** [thx/iconfont-plus#46]
做原型的时候需要一组相类似的图标，但是这时候没法批量下载真的是非常痛苦，尤其是每一个icon我都需要单独去设置大小和颜色，让人崩溃。

**Comment by Muqing1221** [comment]
购物车批量下载~你值得拥有~

**Comment by michaeltimber** [comment]
@Muqing1221 棒极了！那么图标库里面的可以批量下载么？就是一次下载一套。

**Comment by Muqing1221** [comment]
一次下一套暂不支持（是啊，我们想在大家的索取预上稍加限制~~是的....）

**Comment by Muqing1221** [comment]
你所期望的批量下载，现在只存在于购物车里~

**Comment by michaeltimber** [comment]
@Muqing1221 还有一个问题，单色的图标似乎是正常的，但是彩色的icon直接下载png没法用，原本透明的部分会被纯黑色填充，需要下载SVG之后处理之后导出的PNG才能正常使用。
系统是macOS 10.12.1

**Comment by Muqing1221** [comment]
亲，其实你的问题我也遇到过~然后我发现我这边试的是，finder里的缩略有黑底，我放在keynote里，小于一定尺寸会有黑底，当大于一定尺寸时会黑底，播放状态下会黑底~
已经跟我们的前端GG们反映过，目测应该是对新系统的不那么兼容~
当然，偶萌已经在快马加鞭的研究修复了，但最近业务暴多，所以只能mark在小本本上~
