### ISSUE TITLE
退出然后重新登录以后，我的项目没有了，不知道什么原因？

### ISSUE THREAD

**Issue by liangq** [thx/iconfont-plus#461]

**Comment by purplebamboo** [comment]
亲 项目名称 可以提供下吗？

用的是什么账户登录的，微博还是github  用户名是啥

**Comment by liangq** [comment]
我最初应该都是用微博登录的 damaoliangqing@163.com
用户6242966727 
项目名称有好多  寻呼台  定制 傲林 ....

**Comment by liangq** [comment]
今天试了一下用github登录，然后又换回微博登录，就看不到以前存的项目了
以前存项目的ID还是昵称是： 用户6242966727

**Comment by liangq** [comment]
不好意思，是因为我有两个微博账号，弄混了，谢谢！
