### ISSUE TITLE
今天新开项目使用 fontclass 直接 @import ，出现跨越错误

### ISSUE THREAD

**Issue by liuxiaojiu** [thx/iconfont-plus#462]
![image](https://cloud.githubusercontent.com/assets/15249267/25709958/61a3fb7c-311d-11e7-9aec-1976e84aca49.png)
之前版本未出现此问题

**Comment by ironmaxtory** [comment]
对呀，我的也是，无端端就跨域出错了，以前都没有该问题

**Comment by inJonathan** [comment]
是的，我看了css源码，发现字体url那里引用的地址都是不能访问的，和之前的不一样

**Comment by purplebamboo** [comment]
已经修复，感谢反馈

**Comment by ironmaxtory** [comment]
@purplebamboo 
非常感谢反馈速度那么及时！

**Comment by kolf** [comment]
我的还没好啊，就前天出现的问题

**Comment by purplebamboo** [comment]
亲  修改下项目 重新生成下字体哈
