### ISSUE TITLE
建议细化颗粒度，引入模块化思想，在创建/编辑项目的时候选择多个图标库进行组合

### ISSUE THREAD

**Issue by kooofly** [thx/iconfont-plus#47]
比如：我新建了两个基础项目【第三方社交ICONS】【提示状态ICONS】
业务项目A 需要这两个ICON项目的合集。建议可以在创建/编辑项目的时候选择多个图标库进行组合

**Comment by Muqing1221** [comment]
谢谢亲的建议，考虑到合并项目的场景在全部用户的维度并不是非常高频的刚需；所以我们在之后会酌情考虑；多谢again
在操作便捷性方面，会逐步提升~~
持续关注吧
