### ISSUE TITLE
现在每个项目都是只有成员能看，能否提供一种在线地址，所有人都有权限看和下载？

### ISSUE THREAD

**Issue by PanJiaChen** [thx/iconfont-plus#476]
现在一个开源项目用了一组iconfont，但开源项目使用的人都不是项目成员，都无法方便查看现有iconfont有哪些。

**Comment by mamakele** [comment]
建议把项目成员放到iconfont项目的协作人员中，在项目编辑中可以添加人员~~

**Comment by PanJiaChen** [comment]
开源项目。。所有人都可以看。。。。你要加 无穷无尽啊

**Comment by gongeek** [comment]
去建个图标库？ http://iconfont.cn/manage/index?manage_type=myicons&icontype=collections_handle

**Comment by PanJiaChen** [comment]
@gongeek 图库的作用并不是这个。。人家官方文档写的很明确了
