### ISSUE TITLE
无法添加成员

### ISSUE THREAD

**Issue by HandsomeL** [thx/iconfont-plus#477]
创建项目是如果有其他成员会导致创建醒目失败；
在项目边界界面添加成员无效！
体验太差了。

**Comment by purplebamboo** [comment]
亲 我试了下 可以的啊，可以说下你具体的场景吗？

比如你的浏览器环境，可以的话  尝试换chrome试下？

**Comment by zxm1989** [comment]
添加成员，还是不行啊，我用的谷歌，搜不到我朋友的帐号，就添加不上，她能搜到我的，就能加上，赶紧修bug吧，哈哈哈哈

**Comment by zxm1989** [comment]
现在又可以了，又能搜到了，绝对的bug，有时管用，有时不管用，好好测一下
