### ISSUE TITLE
别人回复我的图表库没有消息提醒

### ISSUE THREAD

**Issue by suhehe** [thx/iconfont-plus#48]
别人在我图标库下面留言我都不知道，不太好

**Comment by Muqing1221** [comment]
应该是有提醒的呀~亲是不是没留意到~
因为我这边别人对我的评论的回复什么的，我都收得到，因为我们外接的多说，右上是有消息提醒的

**Comment by suhehe** [comment]
这样。。要下次有人评论才能知道了

**Comment by Muqing1221** [comment]
你id多少~我去评论下？

**Comment by Muqing1221** [comment]
你id多少~我去评论下？

**Comment by suhehe** [comment]
有人评论我的图表库了，但是我真的看不到消息提醒，右上角只有图标购物车的提醒

**Comment by suhehe** [comment]
这个issue都还没解决就被关掉了。。

**Comment by suhehe** [comment]
我的id 是 苏德不易勒夫，要不你截个图给我看看你的消息提醒是在哪里？谢啦 @Muqing1221

**Comment by Muqing1221** [comment]
亲，抱歉我之前理解错你的意思~
这个问题我们再看一下哈

之前我测试的是，如果我评论别人的库，然后如果跟别人有互动的话，右上角是有提示的，如果这个你还木有，那就去“多说”那设置下，我找下截图给你哈~~我对你的id有印象~哈哈

**Comment by suhehe** [comment]
我是比较在意别人的反馈所以想打开iconfont就看到消息提示，现在要进到图标库看下面的留言有些麻烦
太谢谢你很热心~一般人对我的头像会比较有印象

**Comment by Muqing1221** [comment]
这我应该做的啊
恩，我等下看一下啦~有解决方案后同步你哈

稍等下哈

**Comment by suhehe** [comment]
我看到多说的通知提醒设置了，但是那个是邮件提醒不知道是不是你说的

**Comment by Muqing1221** [comment]
是这样的，你评论后，别人和你的互动，这个消息提醒在你的多说设置里设置~~

然后你说的这个，想收到别人对你的图标库的提醒，目测要我们接多说的账户要设置点什么，这个晚些我麻烦开发同学解决一下哈~

**Comment by suhehe** [comment]
不是很懂不过相信你们~
