### ISSUE TITLE
关联某个图标所在的图标包

### ISSUE THREAD

**Issue by xinglie** [thx/iconfont-plus#49]
按关键字搜索出一堆图标，能不能在每个图标那加个链接可以查看该图标所在图标包中的其它图标。
这样在使用的时候基本上是一个设计师设计出来的图标，图标相对来说比较统一。

**Comment by Muqing1221** [comment]
点击下载icon，在图标详情浮层中，左上方有该icon的归属人和归属图标库，前提是如果该icon属于某个公开图标库的话，介样你就可以看到一套成体系的icon啦

**Comment by xinglie** [comment]
隐藏的好深

**Comment by purplebamboo** [comment]
目前 这个入口还是有点深，但是外面也没什么地方看了。这个还需要再讨论下，有没有更好的办法。

**Comment by purplebamboo** [comment]
在这里讨论：

https://github.com/thx/iconfont-plus/issues/139
