### ISSUE TITLE
下载不下载，下载下来的图标变样了

### ISSUE THREAD

**Issue by caixiaoxia109** [thx/iconfont-plus#490]
已经三个星期了，一下载项目就报错页面。
现在下载的小图标有的变样了，有好几个，从上上月的时候就有了这个问题，小图标有的戴上了叶子，不知道为什么，明明网上看见是好的，下载下来就变了

**Comment by caixiaoxia109** [comment]
下载下来的小图标，不知道为什么高度很高，统一向下

**Comment by purplebamboo** [comment]
亲 我试了下 是好的 提供下项目id 或者地址

**Comment by caixiaoxia109** [comment]
http://www.iconfont.cn/manage/index?manage_type=myprojects&spm=a313x.7781069.1998910419.9.5J8UdU&projectId=257628&keyword=

**Comment by caixiaoxia109** [comment]
两小时前就发现的问题，就是下载的新的，图标和现在的页面里面的样式有问题，所有小图标都向下跑了。
我就按这种错的调整了，但是后期如果这个变好，我的页面就有变坏了，郁闷。因为我还有好多页面没做。要用小图标

**Comment by caixiaoxia109** [comment]
总之，现在的小图标，样式向下，这个毛病，得解决，我现在都是按错误的样式在调整，不是长久之计

**Comment by purplebamboo** [comment]
亲 参考下491这个issue 哈  是项目里引入了一个有问题的图标 导致整个字体撑开了哈。。删除掉这个图标就好了。。

可以才用二分法  加几个到新项目下载看下demo 找到这些有问题的图标删除掉就可以了哈

**Comment by caixiaoxia109** [comment]
抱歉，没有看明白

**Comment by purplebamboo** [comment]
https://github.com/thx/iconfont-plus/issues/491#issuecomment-304429606

**Comment by purplebamboo** [comment]
在平台的帮助中心里也有解释的哈 我在外面不方便用电脑。。如果还不理解 我晚上再给你详细解释下

**Comment by caixiaoxia109** [comment]
谢谢

**Comment by caixiaoxia109** [comment]
我每次 下载

**Comment by caixiaoxia109** [comment]
http://111.161.65.92/1Q2W3E4R5T6Y7U8I9O0P1Z2X3C4V5B/www.iconfont.cn/api/project/download.zip?pid=313532&ctoken=U69jflLYagJyIqQNratJicon-font

**Comment by caixiaoxia109** [comment]
都是这 错误 页 说页面不存在

**Comment by caixiaoxia109** [comment]
谢谢

**Comment by purplebamboo** [comment]
这个页面不是我们的 是不是用了啥下载工具？ 或者试试换个浏览器哈。。。试试关闭chrome 插件

**Comment by caixiaoxia109** [comment]
我一直用360浏览器。天天点，都下载不下来，已经3个星期了。这两天发现，我只要一直点，不停的点，把错误页面关闭，一直点下载，点个50次60次也就下载了。

**Comment by purplebamboo** [comment]
亲 你换个浏览器试试呗。。囧人力有限，360我们没有具体测试过。。

**Comment by caixiaoxia109** [comment]
无数次的下载失败。
点“我的项目”-“下载至本地”。。。然后报错页面。我一直点，一直点。前两天每天都是点个百八十次就能下下来。今天点了无数次，依然报错页。求救！
