### ISSUE TITLE
近期，新生成的代码；图标统一往下偏移了！！

### ISSUE THREAD

**Issue by huangyu-snail** [thx/iconfont-plus#491]
项目ID=24656

**Comment by purplebamboo** [comment]
你好 一般是项目里某个图标有问题哈。。导致整个字体被撑开了。
解决方案是找出这个图标删除重新生成就行。

具体思路是二分法 把怀疑的图标加到新的项目一个个下载看下demo 是不是有问题 就可以找到这个有问题的图标了哈

**Comment by huangyu-snail** [comment]
嗯嗯，好的；谢谢！
