### ISSUE TITLE
请问，项目中引入css文件即报错，请问这是什么问题？在html文件中引入没有问题。

### ISSUE THREAD

**Issue by ymrdf** [thx/iconfont-plus#492]
./~/css-loader?{"minimize":false,"sourceMap":true}!./~/vue-loader/lib/style-compiler?{"id":"data-v-8ed20dee","scoped":false,"hasInlineConfig":true}!./~/sass-loader?{"indentedSyntax":true,"sourceMap":true}!./src/styles/common.scss
Module build failed: Unexpected formathttp://at.alicdn.com/t/font_7m1n792nthntgldi.css (7:0)

   5 |   border: 0;
   6 |   font: inherit;
>  7 |   margin: 0;
   8 |   padding: 0;
   9 |   font-weight: normal;
  10 |   vertical-align: baseline;

 @ ./~/vue-style-loader!./~/css-loader?{"minimize":false,"sourceMap":true}!./~/vue-loader/lib/style-compiler?{"id":"data-v-8ed20dee","scoped":false,"hasInlineConfig":true}!./~/sass-loader?{"indentedSyntax":true,"sourceMap":true}!./src/styles/common.scss 4:14-333 13:3-17:5 14:22-341
 @ ./src/components/app/app.vue
 @ ./src/main.js
 @ multi ./build/dev-client ./src/main.js

**Comment by iconfont-cn** [comment]
亲 你是用的vue？ 这个应该不是 本身css的问题

而是 loader的问题哈。

**Comment by ymrdf** [comment]
噢，谢谢，可是没找到解决办法。

**Comment by nxboo** [comment]
你可以在html里直接引用
<link href="//at.alicdn.com/t/font_xxxxxxxxx.css" rel="stylesheet" />
我就是这么干的

**Comment by nxboo** [comment]
> <link href="//at.alicdn.com/t/font_s2pap9gll2b21emi.css" rel="stylesheet" />
