### ISSUE TITLE
缺少查看风格相同的图标的功能

### ISSUE THREAD

**Issue by citybuster** [thx/iconfont-plus#495]
缺少查看风格相同的图标的功能，比如找到一个图标 对号 的图标，再提供一个查找风格相同的 错号 的图标等

**Comment by citybuster** [comment]
缺少查看风格相同的图标的功能

**Comment by nxboo** [comment]
最起码有一个查看对应图标所在图标库的功能，一套系统一般情况下都想用差不多的图标，而搜索到到一些图标后，确不知道怎么才能找到类似风格的，也不知道所在的图标库，可用率大大下降啊，急

**Comment by belerweb** [comment]
很实用很必须的一个功能，支持

**Comment by yisibl** [comment]
如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)
