### ISSUE TITLE
你们页面有bug啊~

### ISSUE THREAD

**Issue by belief-cyf** [thx/iconfont-plus#497]
我的项目 -》 更多操作 -》 项目信息 -》 弹出层里面的项目描述  这个textarea居然可以一直往下拉    下面的信息会被挤出 溢出的！！！   快去找测试撕逼！！！

**Comment by HuangFuQuang** [comment]
有bug吗

**Comment by belief-cyf** [comment]
![image](https://user-images.githubusercontent.com/19991842/27942450-77c85556-6309-11e7-8c43-c2ab033dc3ae.png)

**Comment by purplebamboo** [comment]
哈 感谢反馈  可以算是一个bug。

我们没有测试 = =。都是我们这么几口人自己测试的，囧  可能测的不全面，见谅哈。

**Comment by belief-cyf** [comment]
哈哈   - -    不小心看到的    溜啊   就几口人维护这个项目。

**Comment by yisibl** [comment]
非常感谢对 iconfont 项目的支持，已经修复，下个版本发布。
