### ISSUE TITLE
怎么制作彩色的字体图标呢，有没有详细的教程呢

### ISSUE THREAD

**Issue by xiaohenetpad** [thx/iconfont-plus#498]

**Comment by gongeek** [comment]
正常绘制彩色的图标，导出svg 上传到项目中，通过symbol 引用的方式就可以使用。

绘制没什么特别要求，满足下面的就行
http://iconfont.cn/help/detail?spm=a313x.7781069.1998910419.d8d11a391.BZmedn&helptype=code

http://iconfont.cn/help/detail?spm=a313x.7781069.1998910419.d8d11a391.BZmedn&helptype=code

http://www.zhangxinxu.com/wordpress/2014/07/introduce-svg-sprite-technology/?spm=a313x.7781069.1998910419.50.BZmedn

**Comment by yjiawqgj** [comment]
> 正常绘制彩色的图标，导出svg 上传到项目中，通过symbol 引用的方式就可以使用。
> 
> 绘制没什么特别要求，满足下面的就行 http://iconfont.cn/help/detail?spm=a313x.7781069.1998910419.d8d11a391.BZmedn&helptype=code
> 
> 其它相关链接： http://iconfont.cn/help/detail?spm=a313x.7781069.1998910419.d8d11a391.BZmedn&helptype=code
> 
> http://www.zhangxinxu.com/wordpress/2014/07/introduce-svg-sprite-technology/?spm=a313x.7781069.1998910419.50.BZmedn

怎么在wordpress中引用symbol，官方教程写的太简单了。第一步光说拷贝js代码也没有说在粘贴在哪？第二步加入通用css代码也没有说在哪加入。对于一个新手来说这教程有用吗？
