### ISSUE TITLE
建议：下载图标时记住尺寸、颜色

### ISSUE THREAD

**Issue by clytiee** [thx/iconfont-plus#5]
现在使用过的颜色会出现在左边，但是还需要自己点一下。
如果能记住上次选择的颜色和尺寸就好了，不需要每次都多点2下。

**Comment by Muqing1221** [comment]
哈，可能我们只是觉得，有时候少做一步，比做错一步要好一些~~万一默认下载的颜色不是你想要的咧~

**Comment by purplebamboo** [comment]
这个以前老版本是有的,等我们忙完了，会加上去的哈。

**Comment by purplebamboo** [comment]
这里统一讨论：

https://github.com/thx/iconfont-plus/issues/139
