### ISSUE TITLE
可以添加一个复制图标项目的功能吗？

### ISSUE THREAD

**Issue by liuxfu** [thx/iconfont-plus#50]
不同的网站有些基本差不多的图标，有些自己独有的图标，每次都添加伤不起啊

**Comment by Muqing1221** [comment]
没太明白亲的需求

**Comment by purplebamboo** [comment]
明白亲的意思，其实现在成本不大了，项目里有批量选择的功能，每次有新项目，批量把以前的加进去就好了。

当然如果还不满足，我们可以考虑加一个  一键全选的功能。

**Comment by purplebamboo** [comment]
这里讨论哈。

https://github.com/thx/iconfont-plus/issues/139
