### ISSUE TITLE
建议可以提供项目复制功能

### ISSUE THREAD

**Issue by happyi** [thx/iconfont-plus#506]
我有一个项目 在正式环境应用，现在测试环境想多加几个图标进去，而地址不能变。希望能有项目复制功能，把正式库的图标复制到测试项目，这样改变测试项目 就不会影响正式项目了

**Comment by erguotou520** [comment]
+1 我也有类似的需求，新项目想基于原来的项目生成

**Comment by yisibl** [comment]
克隆项目功能上线了。
