### ISSUE TITLE
可以添加一个团队成员管理功能吗

### ISSUE THREAD

**Issue by 18612790635** [thx/iconfont-plus#51]
团队人员比较多 项目比较多
不同的icon项目添加的成员不一样
每次新建项目都得复制很多微博昵称感觉像是日了狗

**Comment by purplebamboo** [comment]
单独搞一个团队成员管理，好像没必要。

针对亲  你这个场景，我觉得 加一个历史记录好点，就是在加入那里，给你罗列出最近添加过的人，是不是好点。

**Comment by purplebamboo** [comment]
暂时还没大的计划哈，这个点会记下来，后续找设计师再沟通优化。
