### ISSUE TITLE
建议主样式名可以自定义

### ISSUE THREAD

**Issue by hizencss** [thx/iconfont-plus#513]
每个项目都会有自己的一套样式命名规范,比如iconfont建议的主样式名是 **icon-font**
<i class="icon-font icon-a">

但比如我我要写成**svg-font**样式就不匹配了.
<i class="svg-font icon-a">

比让我批量修改主样式名更好的办法就是,提供css的命名规则设置,请考虑下看

**Comment by gongeek** [comment]
试试这个
![image](https://user-images.githubusercontent.com/3911824/27121344-7eaf6226-5119-11e7-90fc-b7c7cce54eb2.png)
