### ISSUE TITLE
生成的font class格式的图标和原图不一致

### ISSUE THREAD

**Issue by zhangyihao** [thx/iconfont-plus#520]
生成的font class格式的图标（csss样式为.gams-edu-daib-active）和原图不一致，原图大概是个钟表的样子，中间钟表的时针分针应该是白色，现在是整个是黑色的，看不见时针、分针了
css在线地址：//at.alicdn.com/t/font_u7vb9ys1c4z5xw29.css

**Comment by gongeek** [comment]
可能是这个钟表的svg不符合我们的要求 http://iconfont.cn/help/detail?spm=a313x.7781069.1998910419.12.s3sJDP&helptype=draw

可以吧原始icon的svg文件贴出来给我看看，是不是图标本身有问题

**Comment by zhangyihao** [comment]
这个跟提供图片的美工同事联系了，是原始svg文件的问题
