### ISSUE TITLE
建议自己上传的图标可以直接添加到项目

### ISSUE THREAD

**Issue by juechenshiai** [thx/iconfont-plus#53]
建议自己上传的图标可以直接添加到项目，每次都要先添加到购物车，然后在添加到项目，比较麻烦，最好是可以批量添加

**Comment by Muqing1221** [comment]
这个功能有设计的，不仅上传的图标可以直接加入项目，最好也能直接加入图标库~~也就是上传图标目的地自定义~~
不过由于资源有限等问题，这个功能点在开发环节暂时被列入了优先级稍低的位置
所以，我们一起呼吁，快点加上~加上~

**Comment by purplebamboo** [comment]
估计 你的纠结点主要在批量操作上，可能觉得加入购物车这个动作比较麻烦。

**Comment by purplebamboo** [comment]
这里集中讨论哈：
https://github.com/thx/iconfont-plus/issues/139
