### ISSUE TITLE
项目编辑进行成员添加提示error后项目消失

### ISSUE THREAD

**Issue by bananafishM** [thx/iconfont-plus#534]
'编辑项目' -> 添加成员 -> '保存' 后提示了一个error信息, 退出编辑后无法找到项目, 成员都没有显示这个项目. 请问能找回项目吗?
项目ID : 61187

**Comment by purplebamboo** [comment]
亲  你的用户名是什么，我帮你处理下哈。

**Comment by bananafishM** [comment]
账号名: bananafishM
麻烦了~

**Comment by purplebamboo** [comment]
亲  你好 归属给你了哈。

这是一个bug，目前已经在解决中了  近期会上线，给您造成的不便 敬请谅解哈。

**Comment by bananafishM** [comment]
好的, 感谢!
