### ISSUE TITLE
没有删除项目文件，但是项目文件不见了，急急急！

### ISSUE THREAD

**Issue by PPpanpan** [thx/iconfont-plus#536]

**Comment by purplebamboo** [comment]
是项目被删除了吗？  

亲  麻烦提供下  项目名  还有用户名

**Comment by PPpanpan** [comment]
项目名，记不清除了，用户名是：畔女郎，这个项目是别人转移给我的。麻烦你帮我查一下!谢谢！



在 2017-06-22 16:06:31，"purplebamboo" <notifications@github.com> 写道：


是项目被删除了吗？

亲 麻烦提供下 项目名 还有用户名

**Comment by PPpanpan** [comment]
平台上的图标链接都还能用，就是找不到项目图标库了

**Comment by purplebamboo** [comment]
亲  我需要知道项目名才行。

或者 之前是谁转给你的，那个人的用户名是啥。

最好再提供下你的 项目的字体cdn地址啥的。

我帮你找找。

**Comment by PPpanpan** [comment]
Kaloosh_zj    之前转给我的那人用户名

https://at.alicdn.com/t/font_vniupobhwjexw29.css   这是cnd地址




在 2017-06-23 11:43:25，"purplebamboo" <notifications@github.com> 写道：


亲 我需要知道项目名才行。

或者 之前是谁转给你的，那个人的用户名是啥。

最好再提供下你的 项目的字体cdn地址啥的。

我帮你找找。

**Comment by PPpanpan** [comment]
找回来了吗？我们这边挺急的，希望你能帮我们尽快找回来，谢谢！

**Comment by PPpanpan** [comment]
亲，怎么样了，查到了吗

**Comment by purplebamboo** [comment]
亲 这个项目还会找不到哎

项目的字体地址  查不到。。。可以提供项目名吗？
我看了下  Kaloosh_zj这个用户下有这些项目：

美佳

test

美佳后台

是这里面的一个吗？

**Comment by PPpanpan** [comment]
qijicheguan   你试试用这个项目名查一下



在 2017-06-27 10:24:37，"purplebamboo" <notifications@github.com> 写道：


亲 这个项目还会找不到哎

项目的字体地址 查不到。。。可以提供项目名吗？
我看了下 Kaloosh_zj这个用户下有这些项目：

美佳

test

美佳后台

是这里面的一个吗？

**Comment by purplebamboo** [comment]
qijicheguan 查不到哎。
