### ISSUE TITLE
下载压缩包中没有.json的文件

### ISSUE THREAD

**Issue by FE-Lockie** [thx/iconfont-plus#537]
加入购物车后，点击下载代码
![image](https://user-images.githubusercontent.com/13660961/27567538-ff3e36c4-5b1e-11e7-87eb-3cb604485713.png)
下载的压缩包解压出来后，没有json格式的对应关系呢~
![image](https://user-images.githubusercontent.com/13660961/27567561-23a0a47a-5b1f-11e7-9a6d-7d1e34161c6c.png)
在React Native中使用`react-native-vector-icons`自定义图标，需要导入一个`key-value`对应的字体图标json数据文件。希望官方能考虑一下下载压缩包中加入json文件

**Comment by JoshYuJump** [comment]
+1

**Comment by yisibl** [comment]
已经支持。
