### ISSUE TITLE
为什么只有第三方快捷登录方式？

### ISSUE THREAD

**Issue by rossroma** [thx/iconfont-plus#538]
为什么只有第三方快捷登录方式，而没有自己的账号密码？
微博登录一直失败:
```
"code": 21331,
"message": "temporarily_unavailable"
```

**Comment by yisibl** [comment]
Duplicate of #1718

**Comment by yisibl** [comment]
手机注册登录功能已经上线，[点击查看](https://mp.weixin.qq.com/s?__biz=Mzg5OTUzNjQ0Mg==&mid=2247483866&idx=1&sn=e6d02ca84cba8157c8f90d072db66bbf&chksm=c050828ff7270b99b00d784681a47fb4d1063a9139732075dc84d8da4ad77d446df386384acc&token=1155149842&lang=zh_CN#rd)
