### ISSUE TITLE
下载代码BUG

### ISSUE THREAD

**Issue by ysstech** [thx/iconfont-plus#55]
选择多个图标到购物车，下载代码包后，里面的字体包含的图标不全。
这是导出的字体图标：
![ttf](https://cloud.githubusercontent.com/assets/23044050/19762829/298d5556-9c6e-11e6-83c8-45983ff7ec55.png)

这是购物车里的图标
![car](https://cloud.githubusercontent.com/assets/23044050/19762864/4f8f8580-9c6e-11e6-916a-fd2a63323f0d.png)

**Comment by purplebamboo** [comment]
亲  你不要直接用系统自带的软件看哈。

你打开下载下来的demo。里面字体都有的。系统这个有些图形是不显示的，我估计是显示常用的一些unicode上面的。

**Comment by purplebamboo** [comment]
亲  你不要直接用系统自带的软件看哈。

你打开下载下来的demo。里面字体都有的。系统这个有些图形是不显示的，我估计是显示常用的一些unicode上面的。

**Comment by purplebamboo** [comment]
亲  你不要直接用系统自带的软件看哈。

你打开下载下来的demo。里面字体都有的。系统这个有些图形是不显示的，我估计是显示常用的一些unicode上面的。

**Comment by purplebamboo** [comment]
亲  你不要直接用系统自带的软件看哈。

你打开下载下来的demo。里面字体都有的。系统这个有些图形是不显示的，我估计是显示常用的一些unicode上面的。

**Comment by ysstech** [comment]
亲，我打开demo_unicode.html （Chrome）里面显示的效果如上图所示，unicode只有两个。

**Comment by purplebamboo** [comment]
奥奥  这样  你把下载下来的包发给我看看？

**Comment by ysstech** [comment]
你好，10月28日已经把包发给你了，请问这个问题已经修复了吗？
