### ISSUE TITLE
为什么 sketch 做的图标 同样的形状组合 单色的话上传后正常显示 多色的话上传后不显示呢

### ISSUE THREAD

**Issue by hzy1106** [thx/iconfont-plus#553]

**Comment by gongeek** [comment]
目测你用sketch绘制的图标有特殊的填充属性 我们不支持解析 。
您可以使用ai重新导一下应该就可以上传了，试一下。

或者把图标源文件传到这里我们看下。

**Comment by ttttianzhen** [comment]
嗯嗯是的 拿到 ai 里重新导出就可以了 谢谢（现在好多都是直接用 sketch 画的图标 如果也可以支持 sketch
 直接导出的图标就好了呢
