### ISSUE TITLE
希望项目中可以按文件夹创建分类

### ISSUE THREAD

**Issue by xuyoung** [thx/iconfont-plus#56]
非常需要一个功能就是在项目可以创建文件夹来分类管理这个项目的图标，如菜单类、常用类

**Comment by xuyoung** [comment]
![image](https://cloud.githubusercontent.com/assets/3674919/19776025/2475bcd4-9ca5-11e6-9593-e8362ad7d506.png)
![image](https://cloud.githubusercontent.com/assets/3674919/19776054/37ceb394-9ca5-11e6-9e86-a1b39b1b11a7.png)
项目设置里边设置了 FontClass，希望demo文件里边的示例 就自动改成 我设置的FontClass，这样demo页面就可以直接用了 否则每次下载下来还要改

**Comment by purplebamboo** [comment]
创建分类可能有点麻烦，demo里修改 fontclass可以的，等封网结束后我更新上去哈。
