### ISSUE TITLE
为什么下载的字体会把字母x替换为打印机图标

### ISSUE THREAD

**Issue by szzbbb07** [thx/iconfont-plus#563]
![20170719140952](https://user-images.githubusercontent.com/19523906/28352971-f6889a1e-6c8b-11e7-9e51-495f687bcdc2.png)

**Comment by loveLibra** [comment]
解决了么 @szzbbb07

**Comment by Zeks1990** [comment]
我也是这个问题！！！

**Comment by purplebamboo** [comment]
你好 这个x 打印机 是专门塞进去的，不然的话 在xp下面的safari会蓝屏的。

**Comment by Zeks1990** [comment]
@purplebamboo 您好，那请问有什么解决方案吗？网站中英文比较多 影响太大了。。

**Comment by purplebamboo** [comment]
亲 这个对你们会有影响吗？  

这边的逻辑是  如果你有在x上面的图标那么就会用你的图标，没有我们才会补上一个打印机防止蓝屏。

也就是说 只有你不需要用x这个字符时 我们才会补上一个打印机的。应该不会影响你呀

**Comment by Zeks1990** [comment]
@purplebamboo 影响倒不是很大。。就是一开始把字体应用到全局了，发现网页所有的x都乱了。。。

**Comment by Zeks1990** [comment]
@purplebamboo 您好 再问一个问题 请问有没有办法自行把x字符替换回真正的x 毕竟XP下用Safari的几率少之又少。。。

**Comment by kimonoki** [comment]
可以编辑字体文件吗？ 需要全局应用啊

**Comment by mydy1987** [comment]
我也遇到同样的问题，iOS下面，那个控件只有用iconFont最方便，但是里面又有x这个文字，文字又不能设置部分文字的字体，我怎么才能把那个打印机删除掉呢
