### ISSUE TITLE
[建议] 项目内图标分组管理

### ISSUE THREAD

**Issue by zjruan** [thx/iconfont-plus#566]
## 一、添加【对项目内的图标分组】功能

![image](https://user-images.githubusercontent.com/12164900/28505514-42ed3576-7057-11e7-9acf-18359adaa400.png)

如图所示当一个项目使用一个iconfont 时，图标数量会越来越多，慢慢的，这些图标就变得越来越难维护，特别是当有人员变动的时候，谁也不知道这些图标会被什么地方引用。因此，添加分组功能，有助于我们对图标项目进行管理，如下图：

![image](https://user-images.githubusercontent.com/12164900/28505878-eb41b20e-7059-11e7-8d07-04e6cf2d2a53.png)

## 二、允许对图标名称进行修改

如上图一的第一排图标，里面有"下拉"、"tab_下拉"、 "下拉"，这都是啥玩意，出现这种情况有多种原因，比如你引用了别人的图标，而我们可能希望把它统一命名为"箭头-上"、"箭头-下"、"箭头-下-类型1"或者其他，这时候再默认以名称排序，使得项目看起来更有条理。目前貌似以上传时间来排序的，这显然是有问题的，对于迭代项目，某个域下的随时都有可能添加新的图标，如果时间间隔过长，就使得这个域下的图标分散在整个项目下了，请看图一，谁也不知道这个图标是哪个域下的。

**Comment by yisibl** [comment]
感谢您的建议，这是非常好的建议 

请关注：Duplicate of #1496
