### ISSUE TITLE
icon Ai下载格式是svg，而非eps

### ISSUE THREAD

**Issue by ethanmi** [thx/iconfont-plus#57]
点击下载Ai下载，下载的格式为svg，而非eps格式的文件，那这和svg下载有什么区别？
![ai-svg](https://cloud.githubusercontent.com/assets/23111038/19791162/580903e8-9cf1-11e6-833b-f6a404fb4829.PNG)
此处为bug

**Comment by gongeek** [comment]
目前 AI下载 eps格式图标会有棘手的问题，暂时没有很好的解决方案，故这里临时改成了下载svg ，ai软件也是可以正常使用svg格式的图标。
后面可能考虑修复，或者去掉这个按钮。
