### ISSUE TITLE
图标编辑之后不能保存？？？

### ISSUE THREAD

**Issue by qi8023for** [thx/iconfont-plus#572]
`service.js:1 Uncaught TypeError: Cannot read property 'message' of undefined
    at Object.complete (service.js:1)
    at l (jquery-1.12.1.js:2)
    at Object.fireWith (jquery-1.12.1.js:2)
    at r (jquery-1.12.1.js:3)
    at XMLHttpRequest.n (jquery-1.12.1.js:3)
﻿`

**Comment by purplebamboo** [comment]
亲 我这边可以  是不是你的图标比较特殊。
方便的话 留下你的用户名还有   编辑的图标  我去看下哈。

**Comment by qi8023for** [comment]
有两个图标编辑出错，其他的目前没问题
![image](https://user-images.githubusercontent.com/28771480/28653048-fb941e1a-72bd-11e7-9075-c4a87fd92780.png)
![image](https://user-images.githubusercontent.com/28771480/28653069-19f6083c-72be-11e7-9b3f-e0ad745393a7.png)
这个错误不能定位到原因吗？

**Comment by qi8023for** [comment]
您好，

附件两个图标编辑出错，其他的目前没问题。
这个错误不能定位到原因吗？
帮忙查一下，谢谢。



qi8023for@163.com
 
发件人： purplebamboo
发送时间： 2017-07-27 10:24
收件人： thx/iconfont-plus
抄送： qi8023for; Author
主题： Re: [thx/iconfont-plus] 图标编辑之后不能保存？？？ (#572)
亲 我这边可以 是不是你的图标比较特殊。
方便的话 留下你的用户名还有 编辑的图标 我去看下哈。
