### ISSUE TITLE
关于搜索功能的优化

### ISSUE THREAD

**Issue by kisscancer** [thx/iconfont-plus#576]
当我们在搜索图标时，经常希望能看到某个图标的作者和相关的整套图标。

现在的搜索功能，只能搜索到一个图标，对应的操作为“添加入库”、“收藏”、“下载图标”。

希望能给出一个“相关图标库”的功能，能看到此图标对应的图标库，方便我们搜索到的的图标拥有一致性。

**Comment by mewchen** [comment]
嗯，我也觉得。看到一个图标很不错，然后可能需要一整套的图标，毕竟一个一个拼凑不一定好看~最好可以直接提供该图标所在图标库。

**Comment by yisibl** [comment]
如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)
