### ISSUE TITLE
关于Logo 图标

### ISSUE THREAD

**Issue by ethanmi** [thx/iconfont-plus#58]
请问你们logo 图标中“iconfont”的“i”是小写的，还是大写的？
看其他地方的应用，应该是大写的，统一用法为“Iconfont”,但此次的I，在视觉上看却是另外一种效果，即缺了上面一点的“i”。
![iconfont](https://cloud.githubusercontent.com/assets/23111038/19791330/a3246a92-9cf2-11e6-8034-330c5d00c905.PNG)
![iconfont2](https://cloud.githubusercontent.com/assets/23111038/19791375/f5043ea0-9cf2-11e6-884f-a0c928e91ae8.PNG)

**Comment by Muqing1221** [comment]
亲好细心，我们的Iconfont是大写的,但logo出于视觉效果的考虑，做了一些字体的形变，所以就出现了亲示意的情况
