### ISSUE TITLE
项目能否做一个归类功能，这样更方便我们管理项目

### ISSUE THREAD

**Issue by iscmi** [thx/iconfont-plus#580]
现在的项目只有一个大的分类，我发起的，可是项目越来越多，查找起来并不是很方便，能否做一个项目分类功能，这样用户就可以根据自己的意愿将项目细化分类，比如说A项目：A-客户端、A-业务端、A-服务端
。谢谢！！！

**Comment by yisibl** [comment]
是指左侧的项目列表需要分类吗？

**Comment by yisibl** [comment]
请统一关注 https://github.com/thx/iconfont-plus/issues/1496
