### ISSUE TITLE
能动态更改标签内的图标吗？

### ISSUE THREAD

**Issue by wenkeShi** [thx/iconfont-plus#589]
unicode引用时能不能动态修改标签里填的东西

**Comment by wenkeShi** [comment]
unicode引用时，是在标签内填入一段这样的& # x e 6 c a ; 东东，不知道填入的这个能不能动态修改为我想变换的图标？

**Comment by purplebamboo** [comment]
可以啊，你用js 去修改就行的。

**Comment by wenkeShi** [comment]
是将那串字符作为字符串赋值给变量吗？JSX里面怎么支持呢？

**Comment by purplebamboo** [comment]
嗯 是的  jsx的话  你就复制给变量就行了呀。

之后动态改变变量，那么渲染的unicode就也动态改变就行了

**Comment by wenkeShi** [comment]
let icon='&#xe6ca;'
        return (<div className="input-box">
                <i className="show-button iconfont" onClick={this.handleIconClick}>{icon}</i>
              </div>);
我这样写，页面出来的不是预期的图标啊，这样写是对的吗？

**Comment by wenkeShi** [comment]
`let icon='&#xe6ca;'
        return (<div className="input-box">
                <i className="show-button iconfont" onClick={this.handleIconClick}>{icon}</i>
                `
            </div>
            );`
我这样写出现的不是预期的图标啊，是写法错了吗

**Comment by purplebamboo** [comment]
估计被转义了，你用 jsx的  dangerouslySetInnerHTML 设置哈

**Comment by ronggang** [comment]
@wenkeShi 使用 \ue 开头就可以了，如 icon='\ue6ca';

**Comment by wenkeShi** [comment]
@ronggang \ue不是被转义吗

**Comment by ronggang** [comment]
@wenkeShi jsx不清楚会不会转义，没用过；
如果直接用jQuery是不会的，如：
`$("<i class='i-iconButton'/>").html("\ue6ca");`
