### ISSUE TITLE
批量操作能加个全选按钮吗？

### ISSUE THREAD

**Issue by wangdaodao** [thx/iconfont-plus#59]
加一个全选的按钮吧，鼠标都快点坏了，点坏你们赔！

**Comment by Muqing1221** [comment]
恩，之后会加，亲持续关注哈~

**Comment by purplebamboo** [comment]
统一在这里讨论：

https://github.com/thx/iconfont-plus/issues/139

**Comment by leafiy** [comment]
`document.querySelectorAll('.icon-cover span:first-child').forEach(i=>i.click())`
