### ISSUE TITLE
下载代码功能失效

### ISSUE THREAD

**Issue by cumnlee** [thx/iconfont-plus#595]
返回{"message":"Cannot read property 'id' of null"}

**Comment by bearcandy** [comment]
我的也是。。

**Comment by Code-RoadFly** [comment]
我的也是，好像今天都这样

**Comment by purplebamboo** [comment]
亲 麻烦提供下  项目id？

或者当前的url地址。

**Comment by cumnlee** [comment]
http://www.iconfont.cn/collections/detail?spm=a313x.7781069.1998910419.d9df05512.691448ea5Tnyi6&cid=33

**Comment by purplebamboo** [comment]
sorry 亲  是个bug  已经修复了
