### ISSUE TITLE
MBE风格的icon绘制好后AI里保存成SVG上传到iconfont里为什么丢失了很多笔画细节部分

### ISSUE THREAD

**Issue by Joe1117** [thx/iconfont-plus#597]
MBE风格的icon绘制好后AI里保存成SVG上传到iconfont里为什么丢失了很多笔画细节部分

**Comment by Joe1117** [comment]
PS里绘制好的MBE风格的icon导入到AI里为什么保存输出SVG后丢失了很多笔画细节部分

**Comment by davinma** [comment]
可以对 SVG 路径进行合并扩展，尽量减少节点的使用，以及将图形轮廓画，参见[官方图标绘制指南](http://iconfont.cn/help/detail?spm=a313x.7781069.1998910419.12&helptype=draw)。可以把官方的模板下载来使用或者下载别人已有的模板，在其基础上进行修改尝试 :blush:

**Comment by yisibl** [comment]
统一到 https://github.com/thx/iconfont-plus/issues/1937 回复
