### ISSUE TITLE
关于用户体验

### ISSUE THREAD

**Issue by XueweiZheng** [thx/iconfont-plus#6]
看不到图标被点击时的颜色更改的样子  这个点改善一下就好了

**Comment by Muqing1221** [comment]
被点击时的颜色更改的样子？
亲方便描述的更详细些么~

**Comment by XueweiZheng** [comment]
就是一般图标获得焦点的时候发生颜色变化  会有一套带有色彩的同类型图标吗  看得到的话会好很多

**Comment by purplebamboo** [comment]
亲  不是太明白你的意思，建议再写的清楚点哈
