### ISSUE TITLE
画布希望支持拉宽成矩形，类似 icomoon

### ISSUE THREAD

**Issue by jsw0528** [thx/iconfont-plus#60]

**Comment by purplebamboo** [comment]
是这样的亲，我们不建议太依赖在线的那个编辑器，那个只是用来临时小修改的。如果需要画布变成矩形，可以设计的时候，图标超出正方形的画布，上传后也是可以正常显示的。

**Comment by jsw0528** [comment]
试了下，的确可以上传，不过显示就很凌乱了，图标一多就没法看了：

![snip20161104_8](https://cloud.githubusercontent.com/assets/197375/19975225/298a9f74-a226-11e6-9ea8-f572536a8d43.png)

下面这些是我在 icomoon 管理的其中几个，两年前就想迁回 iconfont.cn，可惜。。。

![snip20161104_5](https://cloud.githubusercontent.com/assets/197375/19974757/8796fc04-a224-11e6-8329-37ec3f90bb47.png)

![snip20161104_9](https://cloud.githubusercontent.com/assets/197375/19975362/98d761e6-a226-11e6-8f10-d6555ae4be4e.png)
