### ISSUE TITLE
添加的 icon 代码 无法下载到本地

### ISSUE THREAD

**Issue by pansy-cx** [thx/iconfont-plus#608]
点击下载代码后显示如下
![](https://raw.githubusercontent.com/pansy-cx/pansy-cx.github.io/master/assets/img/iconfont.PNG)

**Comment by purplebamboo** [comment]
您好 您是否安装了什么插件  或者迅雷之类的。。

尽量使用chrome来下载哈。。

**Comment by pansy-cx** [comment]
试过了，换了台什么插件都没有的电脑，用 chrome 下也是这样，这是下载地址
http://211.143.146.212/1Q2W3E4R5T6Y7U8I9O0P1Z2X3C4V5B/www.iconfont.cn/api/project/download.zip?pid=260051&ctoken=9p0HGOWcxEb7V6TZySnIicon-font
