### ISSUE TITLE
我的项目，下载到本地会出现 500的错误代码

### ISSUE THREAD

**Issue by highpy** [thx/iconfont-plus#616]
已经登录，但是把我的项目下载到本地，会出现{"code":500,"message":"LOGIN REQUIRED"}的错误

**Comment by MuRui666** [comment]
我也是

**Comment by yisibl** [comment]
之前的 GitHub 等三方登录会偶尔被墙，现在我们支持直接手机登录了。

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
