### ISSUE TITLE
可不可在每个图标上显示出图标的作者，或者是这个图标出自哪个图标集合、项目？

### ISSUE THREAD

**Issue by john830316** [thx/iconfont-plus#62]
经常会找一整套风格相同的图标，比如说我去找 ”放大” 这个图标的时候，同时也需要 “缩小” 等相关图标。

所以如果有个可以查看图标出处的地方，能更快找到设计风格完全一致的那组图标，去那里选需要的会更加便捷，建议加上图标来自哪个作业或者是哪个项目、哪组图标集等。

**Comment by xinglie** [comment]
功能是有的，參考這個鏈接：https://github.com/thx/iconfont-plus/issues/49
@Muqing1221 感覺這個功能太不明顯了，建議這種呼聲很高的需求點做的明顯一些，否則用起來太難找

**Comment by purplebamboo** [comment]
统一在 https://github.com/thx/iconfont-plus/issues/49 这个里面讨论吧，看看有没有好的方案，
