### ISSUE TITLE
建议添加搜索到的图标可以找到所在库的功能

### ISSUE THREAD

**Issue by crswebfront** [thx/iconfont-plus#625]
建议添加搜索到的图标可以找到所在库的功能

**Comment by EJellyfish** [comment]
顶一个，好想要这个啊，每次找风格匹配的都好累

**Comment by yisibl** [comment]
如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)
