### ISSUE TITLE
图标代码下载下来后，iconfont.css文件中出错

### ISSUE THREAD

**Issue by Code-RoadFly** [thx/iconfont-plus#631]
图标代码下载下来后，iconfont.css文件中，第四行代码出错，生成的格式跟以前不一样，导致路径找不到

以前的格式为：　url('iconfont.woff?t=1504660126892') format('woff'), /* chrome, firefox */

现在下载下来的格式为：　('data:application/x-font-woff;charset=utf-8;base64,d09GRgABAAAAAAaQAAsAAAAACZQAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABHU1VCAAABCAAAADMAAABCsP6z7U9TLzIAAAE8AAAARAAAAFZXAkkyY21hcAAAAYAAAABwAAABsgNZ08tnbHlmAAAB8AAAApAAAAMsYHMypGhlYWQAAASAAAAALwAAADYOyhrmaGhlYQAABLAAAAAcAAAAJAfeA4ZobXR4AAAEzAAAABMAAAAUE+kAAGxvY2EAAATgAAAADAAAAAwBhAJqbWF4cAAABOwAAAAeAAAAIAEUAGZuYW1lAAAFDAAAAUUAAAJtPlT+fXBvc3QAAAZUAAAAPAAAAE2l0R1OeJxjYGRgYOBikGPQYWB0cfMJYeBgYGGAAJAMY05meiJQDMoDyrGAaQ4gZoOIAgCKIwNPAHicY2Bk/s04gYGVgYOpk+kMAwNDP4RmfM1gxMjBwMDEwMrMgBUEpLmmMDgwVDx3ZW7438AQw9zAMAUozAiSAwAqPAzJeJzFkcENgCAMRV8VjTGM4hBenMA1PHlyYhwDP5SDTuBvHml/mkIKMAC9WEQAOzGKDrlW/Z65+oFV9cxEp7hSTPu95SzvnbtMfR4l7zSjzB75Tfbf1V/Feq6t0la4Gnpiio42Rtqd8jv35hAe6P0V8HicVVLNaxNBFJ83b2c2O012k91kN9l8bmKyhrZbk6ZZQZq0VaSKRWkpEhGhoDdb7KkXDzm0ICLYg3+BCHqq/0BB/wFPevDoJ6Io3sVEJ23B+uYxv+F9zPu9N0MYIX/e4z6miUVOkgY5R64QAnwcyjrNg+e3AjoOKY+lnKSOfsX31Eo5wFlwyjxpN9utmsNVboAOBZj2mm0/oD7MtDr0DDTtPEAm666Y1ZyJuyDSfmFneJE+hlSxkjM6k8MLE91ks2RFtqKmmTHNBxHOWIRSxdBh3bE1pgk+fMIMN7VfrNMiRDO+e6kXK2XNtXutjXzV0QD6fbCyJf1pN+EmpN51bcvMqPFYJO3GKieSsPVpLG1F87WPRArKXm/jS/qdGKRIQkKYF4Cf6EDoFcBJ6CDbUBPy6ElTQrrUWtkAvyZbLYIttdmFdgjtFtYHe3OrlK7O0eUDHGxUGwCNKl0+xFnhaj/XRSap7aCCPMoVRFC1R/8y5kY3YEfGDvaO5X7RxK9NYWXEfaRS5AaWyEjuVHJ/hq9w/oA7Ae9/qlaSq8eaSeHmoOS3AFo+fXeAdKo8uFMJAIIK3S1P4bx0HQ/5/ePI+fAQyVHNt7iNNTJBeqNfocrlz6g6BDBFAzmLdqieCtujsRSQG7QAHQyr0uzYTiiZtKedpl3EwmiuXA15ReUBtNpdma8ruK1nrr6+2XMjVjyObIcBKkLXkCF8NW2Dg5TsYv/a0mSF/R5a5bU3N5ZyPMYVhXGNMewrFIUSi8cofHPyGqX5xX7vclAVcP386ReaUoKzMQEqVT6IRJSNcUYROorCdaFTXHBj5ni9KW6tdJ8rUJoXY7IaQ8TPMligJp8rVDQ9qdGFnGHU6w2LkL8G4npTeJxjYGRgYADiFM7povH8Nl8ZuFkYQODq1ex5CPp/DgsDsyOQy8HABBIFABOJCe0AeJxjYGRgYG7438AQw8IAAkCSkQEVsAIARwsCbnicY2FgYGB+ycDAwoDAAA6bAP0AAAAAAAB2ANQBDgGWeJxjYGRgYGBliAJiEGACYi4gZGD4D+YzAAASDgF7AAB4nGWPTU7DMBCFX/oHpBKqqGCH5AViASj9EatuWFRq911036ZOmyqJI8et1ANwHo7ACTgC3IA78EgnmzaWx9+8eWNPANzgBx6O3y33kT1cMjtyDRe4F65TfxBukF+Em2jjVbhF/U3YxzOmwm10YXmD17hi9oR3YQ8dfAjXcI1P4Tr1L+EG+Vu4iTv8CrfQ8erCPuZeV7iNRy/2x1YvnF6p5UHFockikzm/gple75KFrdLqnGtbxCZTg6BfSVOdaVvdU+zXQ+ciFVmTqgmrOkmMyq3Z6tAFG+fyUa8XiR6EJuVYY/62xgKOcQWFJQ6MMUIYZIjK6Og7VWb0r7FDwl57Vj3N53RbFNT/c4UBAvTPXFO6stJ5Ok+BPV8bUnV0K27LnpQ0kV7NSRKyQl7WtlRC6gE2ZVeOEXpc0Yk/KGdI/wAJWm7IAAAAeJxjYGKAAC4G7ICVkYmRmZGFkZWRjYGxgi0lNTff0IinPDWzojQxryojPy+dvSg1rSi1OIOBAQC2OQrb') format('woff'),

**Comment by purplebamboo** [comment]
你好 这不是出错哈 这个是 base64的编码，可以减少一次请求的。


大部分浏览器都是可以直接用 woff字体  因此把它base64后在这个场景下可以少一次请求哈，是一个优化措施。

对使用者是透明的哈，你们可以继续用css的，内部可以不管的

**Comment by Code-RoadFly** [comment]
不好意思，刚才我下载下来引入到项目中，项目直接报错说找不到路径，然后我看了一下代码，手动改回原来的格式就好了，现在听你说了以后，我又把它改成base64编码，又不报错了，我也蒙了，不过问题解决了，谢谢
