### ISSUE TITLE
发现很多图标无故变模糊了

### ISSUE THREAD

**Issue by sentsin** [thx/iconfont-plus#635]
不知道iconfont进行了什么调整，之前很清晰的图标，未作任何改动，然而近期重新下载到本地后，图标变得异常模糊。

**Comment by purplebamboo** [comment]
没有做什么呀。。你有两份字体的备份吗？发出来我看下哈

**Comment by sentsin** [comment]
@purplebamboo 有的。
旧版（清晰）：http://cdn.layui.com/res/font_old.zip
新版（模糊）：http://cdn.layui.com/res/font_new.zip

很多相同的图标，差异都非常明显

**Comment by purplebamboo** [comment]
好的 电脑不在身边 我明天去看下哈

**Comment by sentsin** [comment]
@purplebamboo 好的，辛苦啦。
补充：问题主要出现在 Windows 下（如 Win10）各大浏览器都表现很明显（我不少用户也反馈存在模糊问题）；Mac下似乎正常，差异不是很明显。

**Comment by purplebamboo** [comment]
亲 我看了下 没有很虚的现象呀，两个文件 我试了下差别不大呀。。。

![image](https://user-images.githubusercontent.com/1409611/30249373-f3bdd540-966d-11e7-8969-2dfb9adedbc5.png)
