### ISSUE TITLE
哪里看图标编码？

### ISSUE THREAD

**Issue by Moveharder** [thx/iconfont-plus#64]
哪里看图标编码？能不能弄得明显一些？

**Comment by purplebamboo** [comment]
额。。亲  在项目里面  可以看到的呀。。。编码分三种，unicode，font-class,symbol。

你加入到一个项目里就可以看到了，可以直接下载下来使用的。

**Comment by Moveharder** [comment]
OK，我会试一下的。


发自网易邮箱大师
在2016年10月28日 22:20，purplebamboo 写道:

额。。亲 在项目里面 可以看到的呀。。。编码分三种，unicode，font-class,symbol。

你加入到一个项目里就可以看到了，可以直接下载下来使用的。
