### ISSUE TITLE
这个是漏洞吗 ?

### ISSUE THREAD

**Issue by chuchur** [thx/iconfont-plus#641]
应该是注入漏洞吧,
![image](https://user-images.githubusercontent.com/4814173/30363524-2a2a56b2-9826-11e7-9400-a22ed04cc908.png)
![image](https://user-images.githubusercontent.com/4814173/30363579-5e1fd38e-9826-11e7-9b5f-6a2f0f2ea4d5.png)

**Comment by chuchur** [comment]
![image](https://user-images.githubusercontent.com/4814173/30363766-1030fe40-9827-11e7-83f4-6cf81d3c5422.png)

**Comment by cricy** [comment]
是别人想玩注入，我们把他按字符串存入到数据库了。为了不影响其他人，刚才对这些数据做了清理。
