### ISSUE TITLE
svg上传失败

### ISSUE THREAD

**Issue by ydamen** [thx/iconfont-plus#644]
如题，设计提供了svg图标，上传到Iconfont后有些可以上传，有些上传失败，
[img.zip](https://github.com/thx/iconfont-plus/files/1305031/img.zip)
谁能看看问题出在哪，不懂

**Comment by gongeek** [comment]
![image](https://user-images.githubusercontent.com/3911824/30476221-e9dbe16c-9a3b-11e7-8a1e-1b940a9975d3.png)
这些属性不支持解析

用ai打开后重新导出图标后可以上传。
可以试试我重新导的。
[img2.zip](https://github.com/thx/iconfont-plus/files/1305915/img2.zip)

图标绘制规范 http://iconfont.cn/help/detail?spm=a313x.7781069.1998910419.12&helptype=draw
建议使用AI来绘制
