### ISSUE TITLE
删除icon，链接不会更新

### ISSUE THREAD

**Issue by alfie0904** [thx/iconfont-plus#645]
每次添加一个新的icon，可以手动刷新线上的地址。但是如果是删除一个icon，就没有办法手动刷新，导致at.alicdn.com的链接还是指向原来的 地址

**Comment by cricy** [comment]
删除icon，我们感觉没必要重新生成新地址，可以一样用原地址，好比只是你不用ttf的一个icon展现；删除一个icon，也只减少了一点文件大小，如果更新了，还要更新地址，增加维护成本。

**Comment by alfie0904** [comment]
soga,明白了，如果需要大批量删除，之后在增加一个新的icon，这样就可以把链接给更新了
