### ISSUE TITLE
新浪微博无法登录

### ISSUE THREAD

**Issue by yangzhedeID** [thx/iconfont-plus#65]
![image](https://cloud.githubusercontent.com/assets/6702107/19794306/9e370e7a-9d03-11e6-84ac-340690de759c.png)

**Comment by purplebamboo** [comment]
目前  新浪微博登陆对接还有点不稳定，我们还在排查哈。亲应该多试几次就可以登陆上去。目前调用的新浪的接口有点不稳定，我们再排查下。
