### ISSUE TITLE
希望可以在图标搜索结果列表页，提供每个图标所属库链接，以便进入查看、使用该库其他图标

### ISSUE THREAD

**Issue by Riant** [thx/iconfont-plus#650]
比如搜索一个 右箭头，那么左箭头当然也希望可以使用该库的，以便尽量保持风格、线条统一。

谢谢

**Comment by yisibl** [comment]
如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)
