### ISSUE TITLE
每增加一个图标，然后更新在URL,  然后在自己的源代码里再更改URL,太繁琐了。

### ISSUE THREAD

**Issue by numa001** [thx/iconfont-plus#655]
每增加一个图标，然后在iconfont后台更新URL,  然后在自己的源代码里再更改URL,太繁琐了。
有什么办法 只要在iconfont后台更新URL,  不需要在自己的源代码里更改URL.

**Comment by yuanzougaofei97** [comment]
同问

**Comment by judithhuang** [comment]
同问

**Comment by yisibl** [comment]
https://github.com/thx/iconfont-plus/issues/891
