### ISSUE TITLE
base64 IE8不支持，是否可以提供一个开关关闭

### ISSUE THREAD

**Issue by chenkaixia** [thx/iconfont-plus#659]
IE8下，图标显示不出来,字体文件使用了base64。
@font-face {font-family: "iconfont";
  src: url('//at.alicdn.com/t/font_408081_n4fqgeujk5nopqfr.eot?t=1506420344144'); /* IE9*/
  src: url('//at.alicdn.com/t/font_408081_n4fqgeujk5nopqfr.eot?t=1506420344144#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('data:application/x-font-woff;charset=utf-8;base64,d09GRgABAAAAAAfcAAsAAAAAC1QAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAABHU1VCAAABCAAAADMAAABCsP6z7U9TLzIAAAE8AAAAQwAAAFZW7kiTY21hcAAAAYAAAAB7AAABwJuaBcZnbHlmAAAB/AAAA7cAAATUhTw792hlYWQAAAW0AAAAMQAAADYQVNLuaGhlYQAABegAAAAeAAAAJAk0BNtobXR4AAAGCAAAABgAAAAYGWf//2xvY2EAAAYgAAAADgAAAA4EMgKobWF4cAAABjAAAAAeAAAAIAEWAH5uYW1lAAAGUAAAAUUAAAJtPlT+fXBvc3QAAAeYAAAAQwAAAFRojzmaeJxjYGRgYOBikGPQYWB0cfMJYeBgYGGAAJAMY05meiJQDMoDyrGAaQ4gZoOIAgCKIwNPAHicY2BksWGcwMDKwMHUyXSGgYGhH0IzvmYwYuRgYGBiYGVmwAoC0lxTGBwYKp6lMDf8b2CIYW5kaAAKM4LkAO4kDBYAeJzFkcsNhDAMRJ8hrFYRpdAEOW8ViDOnPaRitwHjBK20FTDWi+yR81EMTMAoFpHAvhihQ641fyQ3P1FUZ94MiurFN9/PU1719Zd3mfoysyLypDMm7cFePCZ77up/zW393FX8f73RE33txCy8dGI+vnWi3/cOwwVy8BnsAHicVZTLj9tUFIfvudd2Ysd2xrF97STj2I47TpkMnonz1DxSTSjQokplZqoUNkiVEJuqSBVTdcMiXSCxqBAS7T+AEKxYFbHqBs0OsWANK8RDsGHTFY9kOHcKarCudJzz+N1zvmOFyISc/sAeM5/Y5DzpkIvkVUJAaUPTpAHErV5G2+DGsus5JmslrbiQNDO2B15TcXg+6KWeUlDKYEIDunE+aGW0Bf3emO5AzgOAar12VFlbrbAPQfNbjfcWr9CPwQ2T1fL4+cXljQtOHtnFu3qlUq1U7hcVWS5SKpVNuOVxVVY1ZfGJXK65j8PnaAh6tVW78roR1Ss33u+9Hax5KsBsBnY9Mj+7YNUsPO/WuF2pFlaMol8zknMO3P2p5Nt6kP5I8AGc9Qn7iqUkImQNYtF+EmP3/x63YImZ+hbwMaTsy3kAv5Rtuzw/kWUmMZkCo+AENv2tVHdgkz6yAwcAKMNHliRpfiKy4ff5ZQ3cOiEK3vcp+47NiINs98gBuUFuE2Lng2G/N9iBMfTSNqIruA63k2a6Bxk0lQBRel3R29pZSBEpDhfpWJayRJDHBC4S84Eoki0siTFuZdCKTbCt3gC3wV3LUZK4maaWC4Z2Z4XzlYdBCvzkjmbgUjmkwUN00q/P4seW61oPRDx7IF6P/0uaS5gIP2ME7aIepJcMDT7XDENbHGkGvcdX/qc3f2dZK3YfwZJWgNL0e/QuNfSH0IRndyxqz9QN3Jv4RmcSYfdImfjkHHmT3MJl4pyFpbnlnDtKM+0NCnkDTJpBfwwIyISk2UIqrgkCMNaYCGwoWKI3HQP3UAPXkXPPRe9g2KBKQYBvABNyQpa9Ne9NppROJ/SbM7t4zY+irTD81lo1lGoU2RBSvSiptm6VgqvbUD1fHV2rliKfauvHk8nxukb9qFS9NsIAbF8NSpZuq1KxefPg4Cb1w3AritkM5Zev+SLajPDs2lFUVYxVyw/nf6qcG3qYqy/b9br9kpYHOnUjfWtX7au7W3rkUj3oaBedWs15Ue2EOoDOPXXtBa2vTeC2aHgzRp7S6enpTJ7id2mRbbJPLiFNhGDh1DFCsRBD7NkNKHQHGU36iYv/BU6Ddl0El5y9dBHuMINNgTIdDO0+JnNF+jvNAfL0rzfSLkA3hYPprx2XHoK3PgwPG6M25+1RAz1Hwh7uXwe4vn+Iv6nbeWpYG/LWXH1azq6gnS6elDIDa/3tbW9jtDdqex+VMjNEu7OD5ftTqmiZaWSlxQf3MdPcIP8ABbbAaAB4nGNgZGBgAGK/5vQn8fw2Xxm4WRhA4OoH9woY/f///wbWMOZGIJeDgQkkCgBicw07AAAAeJxjYGRgYG7438AQwxr6HwhYwxiAIiiADQCvjwcYAAAEAAAAA+kAAAQpAAAEAAAABAAAAAVV//8AAAAAAHYArgFSAfoCagAAeJxjYGRgYGBjKAJiEGACYi4gZGD4D+YzAAAUmAGVAAB4nGWPTU7DMBCFX/oHpBKqqGCH5AViASj9EatuWFRq911036ZOmyqJI8et1ANwHo7ACTgC3IA78EgnmzaWx9+8eWNPANzgBx6O3y33kT1cMjtyDRe4F65TfxBukF+Em2jjVbhF/U3YxzOmwm10YXmD17hi9oR3YQ8dfAjXcI1P4Tr1L+EG+Vu4iTv8CrfQ8erCPuZeV7iNRy/2x1YvnF6p5UHFockikzm/gple75KFrdLqnGtbxCZTg6BfSVOdaVvdU+zXQ+ciFVmTqgmrOkmMyq3Z6tAFG+fyUa8XiR6EJuVYY/62xgKOcQWFJQ6MMUIYZIjK6Og7VWb0r7FDwl57Vj3N53RbFNT/c4UBAvTPXFO6stJ5Ok+BPV8bUnV0K27LnpQ0kV7NSRKyQl7WtlRC6gE2ZVeOEXpc0Yk/KGdI/wAJWm7IAAAAeJxjYGKAAC4G7ICNkYmRmZGFkZWRjZGdgbGCtSAxPdWQo6o0MyUxozSRrSqzsjQxjyszOT8vPjc/L7WSgQEA9ZgMwwA=') format('woff'),
  url('//at.alicdn.com/t/font_408081_n4fqgeujk5nopqfr.ttf?t=1506420344144') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
  url('//at.alicdn.com/t/font_408081_n4fqgeujk5nopqfr.svg?t=1506420344144#iconfont') format('svg'); /* iOS 4.1- */
}

**Comment by fishinallblue** [comment]
遇到了同样的问题，请开放去掉base64的开关

**Comment by yisibl** [comment]
https://github.com/thx/iconfont-plus/issues/678
