### ISSUE TITLE
一个URL对应一个项目-版本 这样同项目同版本图标更改后就不用改URL了

### ISSUE THREAD

**Issue by wxb1123603312** [thx/iconfont-plus#667]
一个URL对应一个项目-版本 这样同项目同版本图标更改后就不用改URL了

**Comment by purplebamboo** [comment]
亲  不是这样的，

比如你项目做了改动，如果url不变，那影响到了线上的图标怎么办。

所以  每个版本 都必须出一个新的cdn地址，才能保证线上版本的稳定。而且也方便回滚。
