### ISSUE TITLE
请考虑导出文件中，增加.json文件

### ISSUE THREAD

**Issue by lemonweb** [thx/iconfont-plus#668]
目前 sketch 并不能像 Photoshop 一样可以直接解析 iconfont 字体，在协作和管理图标中，使用效率并不高，希望可以兼容 [sketch iconfont](https://github.com/keremciu/sketch-iconfont) 插件，生成一个.json文件，方便团队成员高效同步图标库。提高 iconfont 的使用效率。

**Comment by JoshYuJump** [comment]
+1

**Comment by yisibl** [comment]
下载项目的时候现在包含 JSON 文件了
