### ISSUE TITLE
图标代码无法下载 怎么回事？

### ISSUE THREAD

**Issue by zc5788248** [thx/iconfont-plus#669]
图标代码无法下载 怎么回事？一直都是{"code":500,"message":"LOGIN REQUIRED"}
账号换了好几个都没办法  还让其他同事下载也是这样问题  没办法下载代码

**Comment by w-mf** [comment]
同样遇到这个问题

**Comment by yisibl** [comment]
之前的 GitHub 等三方登录会偶尔被墙，现在我们支持直接手机登录了。

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
