### ISSUE TITLE
9月底修改了什么，导致图标在xp的IE8下显示不了

### ISSUE THREAD

**Issue by aiolos2016** [thx/iconfont-plus#673]
如题，我们的项目，9月22号之前下载的图标能正常使用，25号后从阿里云图标库下载的图标，在XP sp3 IE8下全挂。

**Comment by whatlife** [comment]
遇到同样的问题

**Comment by purplebamboo** [comment]
您好  9月底 上线了  woff的base64的编码这样 会减少一次字体请求。

font-class的方式我们还是建议支持ie9以上哈。

天猫已经全线不支持ie8了，希望亲们也放弃ie8的支持哈。

**Comment by purplebamboo** [comment]
如果对ie8有需求，可以使用  unicode的使用方式哈

**Comment by fascist** [comment]
臭不要脸的，那还说自己支持IE8

**Comment by fascist** [comment]
臭不要脸  赶紧下架吧

**Comment by yisibl** [comment]
https://github.com/thx/iconfont-plus/issues/678
