### ISSUE TITLE
微博账号一直登录不上去

### ISSUE THREAD

**Issue by riddlewzw** [thx/iconfont-plus#679]
点微博登录就跳转到了空页面，都两天了，麻烦解决下，谢谢了

**Comment by jeakiew** [comment]
你现在能进去吗，我还是进不去

**Comment by purplebamboo** [comment]
你好 我这边试了没问题呀。 你可以试试  直接打开微博登录试试呢。

微博登录我们也很无奈，经常出问题，他们接口不是太稳定。
