### ISSUE TITLE
无法下载图标，

### ISSUE THREAD

**Issue by ymj1019** [thx/iconfont-plus#68]
![_20161028115759](https://cloud.githubusercontent.com/assets/23112923/19794594/f1b13e2a-9d05-11e6-9347-f7f43891173d.png)
还有为什么反馈栏只有英文版，为什么不能中英文切换，我看到帮助中心的图里面有中英文切换功能但是我确在首页没有发现此功能

**Comment by purplebamboo** [comment]
今天早上  一台下载服务器挂了哈，已经修复了。

反馈功能直接用的  github的所以我们不能中英文切换哈。

首页也是有中英文切换的呀，在最右上角的小icon哈。
