### ISSUE TITLE
关于生成的ttf错误

### ISSUE THREAD

**Issue by lyj505** [thx/iconfont-plus#681]
经过20几次测试,从我的图标库内部从93个图标到94个图标的时候会报错,而我把图标找出来了,单独放在一个项目内部导致错误,这个问题,不知道是单个字体文件的bug,还是iconfont远程打包时,识别这个单个文件的问题,希望icon团队能够帮我测试出问题,。。。。。。我可以把你拉进我的这一个bug字体的库~~~可以吗~~

**Comment by lyj505** [comment]
关于这个bug图标的位置,我提供一下吧,
http://www.iconfont.cn/search/index?q=特权
就是在首页搜索特权,
然后在第三行,第六个元素。

**Comment by purplebamboo** [comment]
是这个图标的问题。

目前搜索的图标比较多，有些质量的确有问题。

我们近期会改造搜索，尽量去掉这些质量差的图标，敬请期待

**Comment by lyj505** [comment]
@purplebamboo  ,希望贵站越来越好哦,还有就是希望规范化。。上传图标大小。。。每次只有去标准库里找,,,因为字体大小不统一的问题,但是不清楚,为什么图标影响了整个ttf的输出
