### ISSUE TITLE
Iconfont官网Bug

### ISSUE THREAD

**Issue by aqiongbei** [thx/iconfont-plus#682]
Iconfont官网存在`Bug`，但是不知道找谁反馈，索性写在这里。
简单描述：多次点击`添加至项目`或弹出来多个`登录框`重叠在一起。见下图
![2017-10-21_213956](https://user-images.githubusercontent.com/20841215/31852355-dbca1556-b6a8-11e7-8f1d-2d6ff8887927.png)
望解决或向相关部门转达。

**Comment by purplebamboo** [comment]
哈  果然如此 之前双十一太忙   感谢反馈 我们尽快修复
