### ISSUE TITLE
FontClass  前缀BUG，如果设置为空「减号不消失」

### ISSUE THREAD

**Issue by zaxlct** [thx/iconfont-plus#69]
![image](https://cloud.githubusercontent.com/assets/14342431/19799733/c2ad51a2-9d2a-11e6-96fe-0a14b329485b.png)

我把 FontClass  前缀设置为空，没有智能的把减号去掉

还有，现在昵称是可以随便修改，没有重复检验了？

**Comment by purplebamboo** [comment]
原则上是不建议不加前缀的，不过这个我们可以处理下。

昵称是指icon的名称吗？昵称不会做重复校验的，但是  font-class会做的。

**Comment by zaxlct** [comment]
昵称是指用户名

**Comment by purplebamboo** [comment]
用户名不用做校验哈。前缀的这个已经处理了哈，是个bug
