### ISSUE TITLE
编辑图标时无法去除颜色

### ISSUE THREAD

**Issue by shanjie001** [thx/iconfont-plus#694]
RT，有时候上传的图标没有清除颜色，这样在使用symbol的时候不能自定义图标颜色，而点编辑图标时不能完成像图标上传时的去除颜色并提交的功能效果。建议增加该功能。

**Comment by purplebamboo** [comment]
在  批量编辑里面有这个功能的哈。

**Comment by shanjie001** [comment]
@purplebamboo  看到了，谢谢
