### ISSUE TITLE
无法下载，请求有，但是icon下不到本地

### ISSUE THREAD

**Issue by lanjeason** [thx/iconfont-plus#695]
![5ac4496b-8b4f-4fa5-b64e-e40ab6e5fbb6](https://user-images.githubusercontent.com/6246188/32159462-9f695838-bd88-11e7-8448-5e9da4befb05.png)

**Comment by purplebamboo** [comment]
麻烦提供下  具体的场景，是什么浏览器，下载了什么图标。

如果可以的话 收藏下这个图标  然后提供下用户id。

**Comment by zuowenyue** [comment]
点击下载没有反应，用的是苹果safari，但是加入购物车以后点击下载可以，什么图标都下载不了

**Comment by QibangLe** [comment]
me too! 点击下载没有反应，用的是苹果safari,什么图标都下载不了

**Comment by buyangdebuyang** [comment]
苹果电脑，所有浏览器都不能下载iconfont阿里巴巴的图标，点了没有反应，其他网站的图标可以正常下载

**Comment by gongeek** [comment]
已修复 safari可以下载了。推荐使用chrome
