### ISSUE TITLE
MacBook Pro 所有浏览器无法下载iconfont的图标

### ISSUE THREAD

**Issue by buyangdebuyang** [thx/iconfont-plus#697]
大概四五天前开始，safari无法下载阿里巴巴iconfont的图标，然后我试了qq浏览器、遨游、神马，都不能下载，点击无任何反应。如果是下载其他网站的图标都可以正常下载。

**Comment by gongeek** [comment]
已修复 safari可以下载了。推荐使用chrome

**Comment by yjj18** [comment]
MacBook Pro还是无法显示 iconfont官网图标也不能正常显示，使用chrome可以正常显示
