### ISSUE TITLE
项目库的权限管理

### ISSUE THREAD

**Issue by NameNull** [thx/iconfont-plus#698]
针对每个项目      master：增删查改， developer：增查
针对每个图标      master：增删查， developer：增查

每个项目有多个master和多个developer

**Comment by NameNull** [comment]
功能建议

**Comment by purplebamboo** [comment]
目前我们还没有针对图标的权限管理，怕做的太复杂。

目前项目维度，是 master：增删查改   developer：增删查改
但是 master 可以锁定图标，让developer无法去 删和改

**Comment by purplebamboo** [comment]
锁定的功能在  批量操作里面，master可以批量选择后  锁定一些图标。

**Comment by yisibl** [comment]
项目成员多角色管理功能已经上线，后续其他相关问题，请统一关注或回复： Duplicate of #1512
