### ISSUE TITLE
更改了 FontClass 前缀后 CDN 怎么更新？没找到按钮啊

### ISSUE THREAD

**Issue by zaxlct** [thx/iconfont-plus#70]
老版的 icon_font 有一些更新操作后，点击一下就更新 CDN 了。新版的更新 CDN 按钮在哪？

**Comment by purplebamboo** [comment]
亲  跟以前类似，点击查看在线链接按钮哈。
里面会有cdn的地址，并且只要有了更新，会有提示的。

**Comment by zaxlct** [comment]
不愧是阿里的。。说话都「亲」开头。。。
