### ISSUE TITLE
查询到的icon，能通过这个icon找到相应的库吗  这个很重要！！目的是能选用统一规格的icon

### ISSUE THREAD

**Issue by burro630** [thx/iconfont-plus#702]
查询到的icon，能通过这个icon找到相应的库吗  这个很重要！！目的是能选用统一规格的icon

**Comment by zhengxiansen** [comment]
+1

目前好像只支持官方的图标库，期望能支持更多的图标库，如果能做出 easyicon 那样，还支持同种风格的ICON 推荐就好了(手动滑稽)

**Comment by xiejijun** [comment]
再找成对图标时，很多时候找到了一个图标，很难找到另一个相匹配的图标。

**Comment by lemontree2000** [comment]
+1 @cricy @dotnil

**Comment by micoliu** [comment]
test

**Comment by purplebamboo** [comment]
目前 如果这个图标属于某个图标库，那么点击下载的时候是可以看到相关图标库的引用的哈。

**Comment by yisibl** [comment]
如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)
