### ISSUE TITLE
近期还是不是有做升级？图标的高度有点奇怪

### ISSUE THREAD

**Issue by huanghm** [thx/iconfont-plus#705]
在windows下图标高度大于本身且不是上下居中

**Comment by huanghm** [comment]
![image](https://user-images.githubusercontent.com/3291085/32371525-294fd5c2-c0cc-11e7-9c3f-110918c0cce8.png)

**Comment by webMasterMrBin** [comment]
@hhm1999 老哥 这个最后咋解决的  遇到跟你一样的问题  同一个icon mac下 没问题   windows下显示高度大于本身 没有居中
