### ISSUE TITLE
不能下载项目文件

### ISSUE THREAD

**Issue by zhaoxieluoke** [thx/iconfont-plus#708]
http://www.iconfont.cn/api/project/download.zip?pid=458336&ctoken=gaovbjN8mYRy2Fl3kWpVicon-font
提示Cannot read property 'length' of undefined"

**Comment by purplebamboo** [comment]
您好 这个问题一般是  您的unicode设置有问题哈。 
参考这里  https://github.com/thx/iconfont-plus/issues/717

**Comment by zhaoxieluoke** [comment]
@purplebamboo  谢了
