### ISSUE TITLE
[Bug] 切换账号登录之后，购物车数据出错

### ISSUE THREAD

**Issue by zacharyzh** [thx/iconfont-plus#709]
假设现在登录了账号A，然后退出，登录账号B，

那么账号A的购物车数据会写入账号B。

**Comment by sudot** [comment]
不仅仅如此,同一个账号在不同浏览器登录,购物车里的数据完全不一致
在A浏览器加入购物车后,切换到B浏览器登录,购物车是空的

**Comment by zacharyzh** [comment]
如果是记录到cookie里可以理解，但是至少导入之前应该询问一下是否写入，否则会很麻烦的。之前的东西全部被搞乱了。

**Comment by zacharyzh** [comment]
鉴于时间太久，关闭这个issue
