### ISSUE TITLE
无法下载png格式

### ISSUE THREAD

**Issue by yh-yuhui** [thx/iconfont-plus#715]
无法下载png格式的文件，点击会跳转到淘宝error页面

**Comment by cricy** [comment]
用safari与chrome做过测试，可以下载。我们下载png是前端生成的应该不会。如果你还是有问题，请提供下你的环境，如浏览器、访问路径、及提示内容并截图。

**Comment by yh-yuhui** [comment]
用同事的电脑试了下，应该是我的chrome有问题。上周下载还没有问题的

**Comment by yh-yuhui** [comment]
老铁，我测试出一个bug。购物车数量超过4还是更多的时候下载失败。
win7   chrome    erromrUrl : http://err.taobao.com/error1.html。

**Comment by purplebamboo** [comment]
我试了下  都没问题   @yh-yuhui   怀疑是你购物车加了什么  异常的图标。

你要不  收藏下这些图标，然后我们试下

提供下iconfont用户名，还有收藏的那几个图标哈

**Comment by yh-yuhui** [comment]
现在又好了。重现不了。等下次重现了我再告诉你们。
我的环境：win7  chrome   errorUrl : http://err.taobao.com/error1.html   ，下载是到桌面

**Comment by micoliu** [comment]
测试一下

**Comment by micoliu** [comment]
test
