### ISSUE TITLE
下载出现 ：Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by fengku** [thx/iconfont-plus#717]
下载出现 ：Cannot read property 'length' of undefined

请问这个是什么问题的呢

**Comment by purplebamboo** [comment]
你好  可以的话  收藏下这个图标

给一下这个图标的名字 还有你的iconfont的账号名称   我去看下。

**Comment by fengku** [comment]
你好 这个是我创建的一个项目 项目名称“珍宝平台”
iconfont账号：峰居

**Comment by purplebamboo** [comment]
你好 我排查了下  是因为你项目中的一个图标unicode设置的不对。



![screenruler-56a680bc-b75a-4eb1-ab8a-af2335ae4cfa](https://user-images.githubusercontent.com/1409611/32767790-96d477cc-c8da-11e7-87ff-93cac198138f.png)

8220ff 这种unicode在生成字体的时候会报错的，我们使用的也是第三方的库去生成的。

一般来说unicode是16进制的，建议在  e600 ~   eeee 哈不要用太奇怪的unicode

我已经帮你修改过了  已经可以用了哈

**Comment by fengku** [comment]
哈哈 谢谢咯哈
