### ISSUE TITLE
通过symbol引用字体图标，其他完美显示，有一个没有显示，查看代码发现<use>标签宽高为0

### ISSUE THREAD

**Issue by haledai** [thx/iconfont-plus#719]
通过symbol引用字体图标，其他完美显示，有一个没有显示，查看代码发现<use>标签宽高为0，但是其他正确显示的字体图标有宽高正常！
这是什么原因导致的，如何解决呢？

**Comment by purplebamboo** [comment]
可能是这个图标本身就是有问题的哦，建议删掉这个图标呢
