### ISSUE TITLE
下载的 PNG 格式图标的右边和下边都不完整，少了一两个像素

### ISSUE THREAD

**Issue by kevinfszu** [thx/iconfont-plus#72]
如下，我下载的尺寸是：26px

![image](https://cloud.githubusercontent.com/assets/5536550/19802049/5551a5a4-9d34-11e6-9727-dbd20db7bfb0.png)

![image](https://cloud.githubusercontent.com/assets/5536550/19802105/a6b338cc-9d34-11e6-89ca-02a8546f8065.png)

**Comment by purplebamboo** [comment]
亲  可以提供具体的图标吗？

比如你收藏下这个图标，然后用户名给我，我去看下问题。

这种情况有可能是图片本身超出范围。如果是自己的图标，可以打开编辑工具，把图标变小点。

**Comment by kevinfszu** [comment]
。。。加入到“我的项目”了，没有“收藏”操作；另外搜索的话，又找不回原来的那个图标；
找一个看起来饱满一些的圆形图标，应该就可以重现这种情况；

**Comment by kevinfszu** [comment]
。。。加入到“我的项目”了，没有“收藏”操作；另外搜索的话，又找不回原来的那个图标；
找一个看起来饱满一些的圆形图标，应该就可以重现这种情况；
