### ISSUE TITLE
不是我项目组成员，为何在我创建的组里上传了 icon ？？？

### ISSUE THREAD

**Issue by JuelChiang** [thx/iconfont-plus#720]
如题

项目组：
http://www.iconfont.cn/manage/index?spm=a313x.7781069.1998910419.10&manage_type=myprojects&projectId=423129&keyword=

<img width="857" alt="2017-11-16 15 07 25" src="https://user-images.githubusercontent.com/16832802/32878174-8a13acba-ca6a-11e7-92a9-6db1f00a9e4c.png">

这个叫 小白Y 的，并不是我项目组成员

**Comment by purplebamboo** [comment]
你好  这个 小白y  是这个图标的作者，也就是上传的人，这个图标的所有者是他。

而你们是使用者，你把他的图标加入了你们的项目，来使用。

就是这样的一个关系哈。这个人是看不到你们项目的情况的，也无法操作你们的项目的，请放心。

**Comment by JuelChiang** [comment]
好的，感谢解答，估计是我组的其他人添加了这个 icon
