### ISSUE TITLE
阿里icon中的fontclass类的字体图标对于ie8的支持情况

### ISSUE THREAD

**Issue by youlibin** [thx/iconfont-plus#738]
记得阿里巴巴icon库里说fontclass类的字体图标支持ie8+的浏览器，但在实际应用中，却发现fontclass类的字体图标并不支持ie8浏览器；除了用图片去替换字体图标外，有没有别的好方法？

**Comment by yisibl** [comment]
https://github.com/thx/iconfont-plus/issues/678
