### ISSUE TITLE
改版的小伙伴们    <script></script>里面引进css   ！！！！

### ISSUE THREAD

**Issue by yibingtao** [thx/iconfont-plus#74]
无语了  你们能不能长点心   

第一步：引入项目下面生成的fontclass代码：
<script src="./iconfont.css"></script>
第二步：挑选相应图标并获取类名，应用于页面：
<i class="iconfont icon-xxx"></i>

**Comment by purplebamboo** [comment]
sorry 最近忙糊涂了。这就修改。
