### ISSUE TITLE
查询到一个图标，不能按这个图标找到他对应的一组图标

### ISSUE THREAD

**Issue by TomYU6** [thx/iconfont-plus#745]
当查询到一个图标时，我想能找到这一组图标。

**Comment by wuyunjiang** [comment]
对，希望可以找到这个图标所在图标库

**Comment by zhougonglai** [comment]
希望能够溯源

**Comment by yisibl** [comment]
如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)
