### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by wenbofeng** [thx/iconfont-plus#75]
建议有修改尺寸的地方，有时候要的图标不一定是正方形的，而且图标也不是只有填充，建议可以设置图标内容的上下左右边距，最后谢谢分享，辛苦

**Comment by purplebamboo** [comment]
亲 我们不是太想把编辑工具搞的太复杂哈，如果有很复杂的需求，按理说应该是在设计阶段处理好，或者下载下来自己用一些专业工具来处理之后再上传才对。

网页版编辑器不可能做太复杂，做太多功能会不上不下哈。
