### ISSUE TITLE
图标不能排序，图标多了不方便分类查看。

### ISSUE THREAD

**Issue by doocal** [thx/iconfont-plus#754]
图标不能排序，图标多了，同类型太分散不主便查看。

**Comment by ginkosen** [comment]
同样的问题，期待官方增加图标排序功能，让强迫症好一点。

**Comment by doocal** [comment]
简单排序是有的，只是想按照自定义方式再排一次，而不是只能按字段的顺序或是时间。

**Comment by fanrenshijue** [comment]
对，图标不能排序，自己常用项目图标不能分类整理

**Comment by fellow99** [comment]
强烈建议

**Comment by wygkzqa** [comment]
对，尤其是同一类图标想放在一起，否则太分散了

**Comment by shady-xia** [comment]
再催一波~

**Comment by ginkosen** [comment]
再催一波~

**Comment by yisibl** [comment]
如果是项目维度的分类，请关注：Duplicate of #1496 ，如果不是请修改标题具体说明后重新打开该问题。
