### ISSUE TITLE
所谓内测就是，可以把我的帐号上传的图标全清空吗？

### ISSUE THREAD

**Issue by oscar0086** [thx/iconfont-plus#76]
所谓内测就是，可以把我的帐号上传的图标全清空吗？审核通不通过，可以通知一声，已经通过的为什么给清空了，这么个做事方法的团队可见水平也是一般？

**Comment by purplebamboo** [comment]
您的账户id是什么？我看下。

**Comment by purplebamboo** [comment]
是不是叫杂家？ 如果是，请遵守国家法律规范。。不要用我们平台做藏独宣传。😂我们不想被喝茶。
