### ISSUE TITLE
是否添加一个垃圾箱的功能或者按照unicode搜索？

### ISSUE THREAD

**Issue by kluslulu** [thx/iconfont-plus#763]
不小心删掉一个图标后在想要加回来，找不到原来unicode下的那个图标，这样就得找到一个和原来长得一样的图标，然后把删掉的图标的unicode全局替换成刚刚添加的图标的unicode

**Comment by yisibl** [comment]
我的项目中的图标回收站功能已经上线。
Duplicate of #1521
