### ISSUE TITLE
下载字体不显示

### ISSUE THREAD

**Issue by antiantian** [thx/iconfont-plus#77]
下载的图标只有黑黑的一快，没有图标

**Comment by purplebamboo** [comment]
是下载字体  还是下载图标？

如果是字体，字体不支持多色的，如果图标是一层层叠加的图形，那么在字体里就会是黑黑的一块哈，用symbol的方式就不会有问题。

如果是图标，那么麻烦提供下  下载的是哪里的图标哈，给到我们这里我们去排查下。
