### ISSUE TITLE
在Mac上制作的icon上传到 iconfont后，在windows上展示有问题

### ISSUE THREAD

**Issue by wangerniu** [thx/iconfont-plus#776]
我司UI使用Mac进行开发，项目所用Icon都是在Mac上使用AI画好的，传到了iconfont上

技术部使用的电脑是windows的，我从iconfont上下载下来之后会发现 icon高度明显出现错误，

而在Mac上，icon高度显示正常

环境：
os: windows10
浏览器：chrome 版本 63.0.3239.84（正式版本） （64 位）

错误展示：

[查看地址](http://icon.wangerniu.org/)

分别在windows，mac系统上打开就能看到问题所在

**Comment by webMasterMrBin** [comment]
@wangerniu 这个最后解决了么 遇到一样的问题

**Comment by webMasterMrBin** [comment]
@purplebamboo  请问这个如何解决

.iconfont {
font-family: 'iconfont' !important;
  font-size: 13px;
  font-style: normal;
  -webkit-font-smoothing: antialiased;
  -webkit-text-stroke-width: 0.2px;
  -moz-osx-font-smoothing: grayscale;
}



下面是我icon的截图
mac下显示正常
![image](https://user-images.githubusercontent.com/25171709/109264911-a9fb7080-7840-11eb-82f8-fab0d2178a8f.png)

windows下 看到图标高度超出了 20* 20 的size

![image](https://user-images.githubusercontent.com/25171709/109265248-2f7f2080-7841-11eb-9892-cd0a249c0291.png)

**Comment by webMasterMrBin** [comment]
问题解决 是设计资源的问题 删了有问题的icon就ok
