### ISSUE TITLE
希望增加收藏图标库的功能

### ISSUE THREAD

**Issue by QQ595332727** [thx/iconfont-plus#788]
除了收藏单个图标之外，我还想收藏某个图标库，发现做不到，希望能增加这个功能。

![qq 20180112150608](https://user-images.githubusercontent.com/14884229/34863391-21c2cd40-f7aa-11e7-96f8-014af3cdb3df.png)

**Comment by yisibl** [comment]
收藏图标库已经实现，测试完成后发布。
![2018-12-19 15_59_27](https://user-images.githubusercontent.com/2784308/50210071-2d42f100-03b0-11e9-812d-b8eab4497738.gif)
