### ISSUE TITLE
紧急：小屏笔记本下载时完全看不到下载按钮。

### ISSUE THREAD

**Issue by muyoumumumu** [thx/iconfont-plus#79]
win10,屏幕1366*768，底部状态栏完全挡住下载图标按钮害我找了好久，弄到左边才看得到。
如图：
![sp161029_152120](https://cloud.githubusercontent.com/assets/16018568/19827962/1dbd7bd2-9dec-11e6-85f1-5fa1e7cd04e8.png)
![sp161029_152138](https://cloud.githubusercontent.com/assets/16018568/19827963/1df095e4-9dec-11e6-80db-18bd43443faa.png)

**Comment by muyoumumumu** [comment]
对了，重点是弹出的下载对话框是鼠标滚轮下滑不了，右侧也没有滑动条。

**Comment by purplebamboo** [comment]
明白，因为你的可视窗口太小了，书签栏跟下面的bar都占据了空间。这样，我们这里做个处理，在窗口高度不足时，将下载框等比缩放下。

大概明天可以弄完。

**Comment by purplebamboo** [comment]
在这里统一讨论：

https://github.com/thx/iconfont-plus/issues/139
