### ISSUE TITLE
搜索图标结果显示

### ISSUE THREAD

**Issue by 85Ryan** [thx/iconfont-plus#791]
改版后搜索结果默认是显示 “精选” 图标，而且有时候精选图标很少，所以能不能将默认搜索结果改为“全部”

**Comment by yisibl** [comment]
精选的图标质量会更高一些，暂时不会默认为「全部」，需要手动选择。
![image](https://user-images.githubusercontent.com/2784308/44011756-ec8a71a6-9eec-11e8-8c89-b86471840e14.png)
