### ISSUE TITLE
您们是不是程序员跑路了，怎么好多图标都没有了。以前一搜一大把，现在就几个，没得用

### ISSUE THREAD

**Issue by dzzzz123** [thx/iconfont-plus#797]

**Comment by gongeek** [comment]
没跑路 哈哈 
现在是默认只搜精选了，你可以选下全部
![image](https://user-images.githubusercontent.com/3911824/35024562-28a0d2cc-fb7b-11e7-9936-947e5793e194.png)

默认精选的图标来自图标库，点下载，在弹框中像下面一样可以找到图标库 方便选风格一样的图标
![image](https://user-images.githubusercontent.com/3911824/35024620-80a23e98-fb7b-11e7-9c2a-bf968d63ee26.png)

**Comment by PeggyWeb** [comment]
点击作者进去是他的图标库是空白的
