### ISSUE TITLE
建议增加图标纠错或举报功能

### ISSUE THREAD

**Issue by v4125251** [thx/iconfont-plus#8]
目前发现部分图片下载下来后和缩略图不一致的情况，有的路径错位，蒙版错的情况到账无法使用，应该增加纠错或举报功能以便作者修改

**Comment by Muqing1221** [comment]
恩，谢谢亲的建议~这个在我们的优化to-do-list中~~期待在不就的之后上线~

**Comment by purplebamboo** [comment]
这里统一讨论：
https://github.com/thx/iconfont-plus/issues/139
