### ISSUE TITLE
建议增强“我的项目“的协作功能

### ISSUE THREAD

**Issue by FrankGuos** [thx/iconfont-plus#802]
hi
团队协作使用iconfont的我的项目功能时有些疑惑。我建立了一个团队项目，我是管理员，所有人都可以添加和删除图标，这样容易导致混乱，无法维护。但是如果不把团队成员拉进来他们又看不到我项目中的图标，很纠结。

**Comment by PeterRock** [comment]
这儿有解决方案： #698

**Comment by yisibl** [comment]
我们已经上线了项目成员权限管理功能，分为超级管理员、管理员、成员、只读成员四种角色，应该可以满足您的需求。如果还有一些细节问题，欢迎留言。
https://www.yuque.com/u7268/iconfont/vkneb9

**Comment by yisibl** [comment]
后续其他相关问题，请统一关注或回复： Duplicate of #1512
