### ISSUE TITLE
symbol方式引入icon无法设置颜色

### ISSUE THREAD

**Issue by tanyutao** [thx/iconfont-plus#805]
svg的fill-color在js文件中写死了，导致使用symbol方式引用普通单色图标时也无法手动设置颜色。

**Comment by weihomechen** [comment]
我也遇到这个问题，有一个图标的颜色想通过取值来确定的（无法预设），虽然大小可以通过font-size设置，但是怎么设置颜色呢

**Comment by weihomechen** [comment]
#350  这里有解决方案

**Comment by tanyutao** [comment]
解决方案：手动在后台把单色图标批量去色，这样svg就不会自带fill的属性了。
不过这一步在系统生成js文件时自动判断再好不过了，毕竟使用了symbol就不想再引用那堆ttf了。
