### ISSUE TITLE
图标能支持自定义分类和排序

### ISSUE THREAD

**Issue by ycx0317** [thx/iconfont-plus#806]
上传的项目图标越来越多，希望能增加自定义分类和排序的功能，方便查找和使用

**Comment by lorinjens** [comment]
强烈要求此功能！！！！！！！！！！

**Comment by kevinzhaoyp** [comment]
强烈要求此功能！！！！！！！！！！

**Comment by yisibl** [comment]
是指项目里的图标吗？按照什么分类呢？

**Comment by yisibl** [comment]
如果是项目维度的分类，请关注：Duplicate of #1496 ，如果不是请修改标题具体说明后重新打开该问题。
