### ISSUE TITLE
苹果手机Safari，输入小写x变成了打印机符号

### ISSUE THREAD

**Issue by cd2001zxm** [thx/iconfont-plus#808]

**Comment by win7killer** [comment]
https://github.com/thx/iconfont-plus/issues/814
问题同这个
<span class="iconfont">x</span>    
这种情况下的x会变成打印机，避免在使用iconfont的元素内部使用文案

**Comment by cd2001zxm** [comment]
已解决！原因是阿里字符集下载后，自动在前面加了一个打印机字体=x。
