### ISSUE TITLE
紧急：账号登录问题

### ISSUE THREAD

**Issue by Aoiujz** [thx/iconfont-plus#81]
原来的 iconfont是用什么账号登录的？ 我记得好像是用淘宝登录的，但是记不清楚了。 现在不管使用GitHub还是用微博 登录进去账号都是空的，原来收藏的数据全部看不到了，请问有什么方式可以找回？

**Comment by purplebamboo** [comment]
麻烦提供下 以前的昵称 我帮你查一下

**Comment by Aoiujz** [comment]
@purplebamboo  我以前的昵称叫  麦当苗儿  ， 之前的淘宝账号也是这个。 麻烦帮我查查，之前的数据很重要，感谢！

**Comment by purplebamboo** [comment]
好像是有三个项目  是吗？  那么亲  你现在登陆后的昵称又是什么呢？

**Comment by purplebamboo** [comment]
麦当苗儿 这个昵称的我找到了  有三个项目  分别是   vmGuardian webHelper 个性化管理系统

**Comment by EvanYe1990** [comment]
@purplebamboo 同样的问题我遇到了。前几天用淘宝账号登录，现在只能用github或微博，那么我用淘宝账户创建的项目就没了吗？我的昵称叫雨夜星空12345，项目名称是v-sun-estate 还能找回吗？

**Comment by purplebamboo** [comment]
@EvanYe1990   亲  iconfont平台从来没有支持过 淘宝账户登陆哦。

**Comment by purplebamboo** [comment]
雨夜星空12345  这个昵称我没有搜索到啊，是不是记错了

**Comment by EvanYe1990** [comment]
我上周刚创建的项目，期间我记得是用淘宝账号或者昵称验证过。请你再帮我查下“雨夜星空” 查询下

**Comment by purplebamboo** [comment]
@EvanYe1990  也没有啊，或者项目名称再回忆下？  亲 你是不是记错了

**Comment by EvanYe1990** [comment]
@purplebamboo 难道忙得已经记忆错乱了 我自己再重新建一个吧 谢谢你
