### ISSUE TITLE
iconfont对‘x’字符渲染为打印机图标

### ISSUE THREAD

**Issue by win7killer** [thx/iconfont-plus#814]
![1517212081589](https://user-images.githubusercontent.com/6337378/35499106-01aad560-050c-11e8-8626-ba1c4097f935.jpg)

如图，iconfont对字符‘x’的渲染有错误，导致使用iconfont的元素内部的文字中包含‘x’的，都变成了打印机图标。先已通过使用法规避该问题。望尽早修复。

iconmoon的是正常的

![image](https://user-images.githubusercontent.com/6337378/35499287-ae953d06-050c-11e8-8895-f998bf44cda6.png)

**Comment by Muqing1221** [comment]
@cricy

**Comment by cricy** [comment]
这个x是以前为了解决 xp下的safair会蓝屏的bug搞的。你可以重置他就行了。而且abcd 这些是webfont在用，如果要用到就重置他吧。

**Comment by win7killer** [comment]
@cricy   怎么个重置法？求个demo
xp下用safair也是够厉害的人了😭

**Comment by yisibl** [comment]
把小写的「x」字符设置为打印机图标早期我们是为了解决 Windows XP 中的 Safari 蓝屏的问题，随着 XP 已经退出历史的舞台，该问题已经可以忽略不计。

现在决定删除这个 Hack，近期会发布一个新版本，敬请关注。感谢各位对 iconfont 平台的支持，我们会努力做到更好。

**Comment by yisibl** [comment]
已经去掉了
