### ISSUE TITLE
求审核者分辨清楚有没有使用渐变~

### ISSUE THREAD

**Issue by WangLaoZhongYi** [thx/iconfont-plus#816]
我传了1套彩色图标，用了几个纯色填充的色块，做出了有点渐变的感觉，创建图标库的时候竟然就被拒绝了，一堆使用同类手法的图标库通通 通过了，就我的被拒绝。求通过啊。审核大大。

**Comment by Muqing1221** [comment]
抱歉，是我的失误，认错道歉，现在应该已经解决了
