### ISSUE TITLE
Edge无法下载

### ISSUE THREAD

**Issue by jiayu-qiu** [thx/iconfont-plus#82]
希望尽快修正个Edge浏览器下载的问题，旧版本也无法下载~

**Comment by purplebamboo** [comment]
edge暂时不在我们的兼容范围内哎。。好像比较小众。建议先使用chrome访问哈。后续我们去兼容下。

**Comment by jiayu-qiu** [comment]
到底是阿里的，对微软的态度还是一致的。

2016年10月30日 下午12:14于 purplebamboo <notifications@github.com>写道：

edge暂时不在我们的兼容范围内哎。。好像比较小众。建议先使用chrome访问哈。后续我们去兼容下。

**Comment by cricy** [comment]
不好意思，也不是小众，主要是从安全的角度考虑了。因为周末受到攻击，因此能客户端处理的就优先客户端处理。
Edge后面我们后面会想办法处理。

**Comment by gongeek** [comment]
Edge已支持下载

**Comment by jiayu-qiu** [comment]
😃😃👏👏👏非常感谢！

2016年10月31日 14:39于 gongeek <notifications@github.com>写道：

Edge已支持下载

**Comment by jiayu-qiu** [comment]
已清除缓存重试，好像还是不行~

2016年10月31日 14:39于 gongeek <notifications@github.com>写道：

Edge已支持下载

**Comment by gongeek** [comment]
@jiayu-qiu  亲，再试下？

**Comment by jiayu-qiu** [comment]
可以了😃👍

2016年10月31日 下午5:08于 gongeek <notifications@github.com>写道：

@jiayu-qiu<https://github.com/jiayu-qiu> 亲，再试下？
