### ISSUE TITLE
搜索功能失效？

### ISSUE THREAD

**Issue by FrankFang** [thx/iconfont-plus#828]
我之前上传过很多名称包含「饥人谷」的icon，能搜到，但是现在突然搜不到了

http://iconfont.cn/search/index?searchType=icon&q=%E9%A5%A5%E4%BA%BA%E8%B0%B7

可以在我的收藏里看到对应的 icon

http://iconfont.cn/user/detail?userViewType=likes&uid=436625

**Comment by gongeek** [comment]
点下全部
![image](https://user-images.githubusercontent.com/3911824/36624459-88cd323e-194a-11e8-99a0-53eb2308c3ea.png)
