### ISSUE TITLE
下载全屏的Icon的png，例如有外圆框的，会被截掉几个像素点

### ISSUE THREAD

**Issue by wyk111wyk** [thx/iconfont-plus#83]
![2016-10-30 3 19 51](https://cloud.githubusercontent.com/assets/8171481/19835029/53331088-9eb4-11e6-823e-4108b0be25eb.png)

**Comment by Muqing1221** [comment]
一般来说，下载本身是不会对图标做裁剪的；可能是icon本身的问题（即绘制/上传时的缘故）~亲多试几个icon试一下？

**Comment by purplebamboo** [comment]
可能这个 icon本身就超出一点点？ 亲可以试下我们的在线编辑工具，看下是否在框外面。可以做一些简单的缩小再下载就好了。
