### ISSUE TITLE
iconfont历史变更日志

### ISSUE THREAD

**Issue by KangarooZero** [thx/iconfont-plus#831]
首先：缺少权限区分（所有人权限都一样，有人勿删图标，无法管理）
其次：缺少回收站等历史变更管理（不小心删除的图标无法恢复）

**Comment by KangarooZero** [comment]
这个事情实在是有点紧急，请帮一下忙，感激涕零！

**Comment by KangarooZero** [comment]
项目名称是：大象
成员名称：黑白花小牛

**Comment by KangarooZero** [comment]
没有日志功能，无法确定是哪个同学删除的，而且删除了无法恢复，真心需要iconfont团队的人工支持！

**Comment by yisibl** [comment]
我的项目中的角色管理功能已经上线，欢迎试用
