### ISSUE TITLE
关于多个项目uuid重复的建议

### ISSUE THREAD

**Issue by NE-SmallTown** [thx/iconfont-plus#84]
我们知道，无论是原来的unicode，fontclass还是新出的symbol，都只能保证同一项目下图标标识符是确定且唯一的，但是我们经常有这样的需求，就是一个项目下有多个组件，在开发时，我们希望不同组件都拥有自己的图标库，按照现在的功能，我们只能给每一个组件分别建立一个项目，最重要的是，按照现在的情况来看，分开的项目里面每个图标的标识符是很可能冲突的！比如a项目里面有e600,b项目里面也可能有e600，这样当在项目里面引入的时候就会发生冲突，非常不好，我目前的做法是手动改变冲突的图标的标识符，但是这明显不是一个好的方法。

所以基于上述情况，希望能开发一个项目合并与分离的功能方便开发，简要说下自己的想法，不足之处还望指正。

有两种方式可以解决这一问题，第一种是提供多个项目的标识符合并功能，保证合并的项目中标识符唯一。第二种是提供一个项目下建立多个子目录的功能，这样的方式改动应该较小一点，因为还是沿袭了之前的一个项目里标识符唯一的做法。另外就是项目中公共图标的问题，a组件和b组件除了自身的独有图标外，可能还存在公共图标，对于公共图标，我的想法是在a和b各自的项目或者文件夹中都允许引入这些公共图标且这个时候没有标识符唯一的限制，也就是说标识符是相同的，这样可以方便我们单独使用某一组件，最后在开发完毕后，希望能够提供打包或者说合并功能，将这些组件所在的项目或者说文件夹合并起来，这样可以减少引入的静态资源数目，同时要注意下合并时对于公用图标只保留一份，因为之前的建议提到公用图标标识符都是相同的，所以合并是完全没有影响的，同时还减少了文件大小。

暂时大概就想到这么多，欢迎交流～

**Comment by NE-SmallTown** [comment]
@Muqing1221 @purplebamboo 求回复。。。

**Comment by Muqing1221** [comment]
来啦来啦~~那个...其实我是设计狗
因为你说的有些问题我没太看明白，所以我理解可能是要开发同学帮忙解答，所以就...
MR. Purplebamboo 最近忙炸，所以....

现在有两个解决方案：
1、晚点我问下开发同学，然后给你回复哈~
2、晚点等开发同学得闲后一定回复你~

多谢理解~一定会回复的~再给我很多分钟~

**Comment by NE-SmallTown** [comment]
@Muqing1221 漂亮姐姐，@purplebamboo 其他issue都回复了，把我遗漏了吗。。

**Comment by Muqing1221** [comment]
我人肉呼叫他~~你不会被遗漏的~

起码让他给你说下“已阅”~哈哈

**Comment by purplebamboo** [comment]
是这样的亲，你这个问题我看到了，因为要好好回下，是个经典问题。

但是最近双十一太忙了，所以先挑比较简单的issue回了。你这个我想好好说下的。

**Comment by purplebamboo** [comment]
那我简单说下哈。

其实你的核心问题是，多个项目字体公用的问题。

其实你的认知是错误的哦。多个项目里的图标，unicode，symbol虽然有可能重复，但是其实可以混用的，也不会冲突的，我们也一直这么用的。

### 首先说unicode场景：

一个项目里的unicode虽然会重复，但是他们使用时是看你的定义的。

你可以试试编辑项目＝》 改一下`Font Family` => 生成最新代码。

```
@font-face {
  font-family: 'test';  /* project id："170177" */
  src: url('//at.alicdn.com/t/font_xh2zh1lxxhv3g14i.eot');
  src: url('//at.alicdn.com/t/font_xh2zh1lxxhv3g14i.eot') format('embedded-opentype'),
  url('//at.alicdn.com/t/font_xh2zh1lxxhv3g14i.woff') format('woff'),
  url('//at.alicdn.com/t/font_xh2zh1lxxhv3g14i.ttf') format('truetype'),
  url('//at.alicdn.com/t/font_xh2zh1lxxhv3g14i.svg#test') format('svg');
}

```
注意到里面的test了吗？这就是我设置的`Font Family`。

然后我再设置一个独立的样式:

```
.test{
  font-family:"test" !important;
  font-size:16px;
  font-style:normal;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

```

所以你就可以用`test-font`这个class去使用这个项目了。

也就是说，不同的项目，你都使用不同的命名空间，那是肯定不会有冲突的问题的哦。


### 同理fontclass的场景也是的，可以设置`Font Family`。

你可以设置后看一下生成的代码，比如我这个：

```
http://at.alicdn.com/t/font_xh2zh1lxxhv3g14i.css
```
里面我们会帮你把样式什么的做好。


当然其实我们不只是这个`Font Family`可以解决冲突问题。我们还有另一个 `前缀`的概念。你也可以尝试下哦，这个主要是用来修改font-class里面每个icon的  class的前缀的。所以也是可以用来区分的哦。

### 最后就是symbol的方式

symbol因为是svg的用法，本身不会支持 `Font Family`的概念，所以目前只能通过 前缀加以区分了。


以上，不知道有没有解决你的问题。我们其实不希望把项目的功能做的太复杂，越复杂的东西尽管功能强大，但是也带来接受成本。

当然，目前平台的帮助文档还不够，我们会慢慢完善的哈。

**Comment by NE-SmallTown** [comment]
@purplebamboo 感谢回复。针对你的建议我做了测试，发现以前的确有做得不好的地方。

经过测试我发现你们的unicode的content原来是通过font-famlily来唯一标识的，最初我认为这个font-famlily叫做iconfont是你们约定俗成的，所以我一直没改，导致有些图标的content都为比如e600这样，所以会引发冲突。

现在我改了font-famlily之后发现一个为a600,一个为b600了，冲突自然就解决了。

但是还存在一个问题，最后上线的时候，我如何将这些分离的组件的图标合并起来，css自然不必说，有打包工具，但是字体文件怎么办。

比如目录结构如下(以下内容如果看不到图片可以点击一下图片在新窗口中看，不知道是不是github对这方面做了限制):
![](http://p1.bqimg.com/567571/d068cfe784cca365.png)

在test.html中我们引入这两个组件的css，可以正常工作。

但是打包css的时候也存在一个问题，照目前的css来看:

```
@font-face {font-family: "a";
  src: url('component-a.eot?t=1478156540575'); /* IE9*/
  src: url('component-a.eot?t=1478156540575#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('component-a.woff?t=1478156540575') format('woff'), /* chrome, firefox */
  url('component-a.ttf?t=1478156540575') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
  url('component-a.svg?t=1478156540575#ne-formValidate') format('svg'); /* iOS 4.1- */
}

```

**Comment by NE-SmallTown** [comment]
@purplebamboo 感谢回复。针对你的建议我做了测试，发现以前的确有做得不好的地方。

经过测试我发现你们的unicode的content原来是通过font-famlily来唯一标识的，最初我认为这个font-famlily叫做iconfont是你们约定俗成的，所以我一直没改，导致有些图标的content都为比如e600这样，所以会引发冲突。

现在我改了font-famlily之后发现一个为a600,一个为b600了，冲突自然就解决了。

但是还存在一个问题，最后上线的时候，我如何将这些分离的组件的图标合并起来，css自然不必说，有打包工具，但是字体文件怎么办。

比如目录结构如下:
![](http://p1.bqimg.com/567571/d068cfe784cca365.png)

在test.html中我们引入这两个组件的css，可以正常工作。

但是打包css的时候也存在一个问题，照目前的css来看:

在component-a.css中如下:
```
@font-face {font-family: "a";
  src: url('component-a.eot?t=1478156540575'); /* IE9*/
  src: url('component-a.eot?t=1478156540575#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('component-a.woff?t=1478156540575') format('woff'), /* chrome, firefox */
  url('component-a.ttf?t=1478156540575') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
  url('component-a.svg?t=1478156540575#ne-formValidate') format('svg'); /* iOS 4.1- */
}

```

在component-b.css中如下:

```
@font-face {font-family: "b";
  src: url('component-b.eot?t=1478156568585'); /* IE9*/
  src: url('component-b.eot?t=1478156568585#iefix') format('embedded-opentype'), /* IE6-IE8 */
  url('component-b.woff?t=1478156568585') format('woff'), /* chrome, firefox */
  url('component-b.ttf?t=1478156568585') format('truetype'), /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
  url('component-b.svg?t=1478156568585#ne-modal') format('svg'); /* iOS 4.1- */
}
```

那么问题来了，希望能出一个合并字体文件的功能（因为这样能减少很多请求，文件数也能大大减少）。

假如这条建议被采纳了，那么需要考虑的是，字体文件合并后同类型肯定就只剩一个了，比如woff格式最后只有一个all.woff。但是上面这些css合并之后对字体文件的引用并不会发生改变，他还是会引用component-a.woff，component-b.woff，**这样势必会导致404。**

所以如果**提供合并字体文件的功能**，那么这一点也要考虑到，建议是也**提供字体图标的css的合并功能，而不是交给打包工具去做**。

除此之外，建议在合并字体文件的时候进行提示或者判断，不同组件的font-famlily必须不同，否则肯定会出乱子。

其实合并的这个功能你们本身就有，就是我最后把这些分离的组件里的图标一个个再加到购物车里面去，然后放到一个新建的项目里，然后再下载，自然就合并字体文件了。。。所以你们增加这个功能应该不会太麻烦，并不需要额外的业务逻辑。

而且我刚测试了下，这样也不会导致重新分配unicode，也就是说原来a组件里面的叫做a600的图标和b组件里面的叫做b600的图标都添加到购物车里面去，然后添加到一个新建的项目里，他们还是这个unicode，这样是很好的，因为原来未合并之前的css里引用a600和b600的类在合并后还能照常工作。

但是这样有个问题，操作起来实在是太麻烦。。

不知我是否描述清楚了，若有不理解的地方，欢迎继续交流～

**Comment by purplebamboo** [comment]
亲  我大概看了下哈，样式合在一起用其实是没问题的,虽然的确会有两个字体请求。

合并字体我们这里也有方案哦，但是合并字体会有unicode重复的问题的。打个比方：

在a项目里有个图标是e600，在b项目里也有个图标是e600。如果合并字体必然带来unicode重复的问题。

通过不同的font-family 相当于有了命名空间，即使unicode一样，也是可以区分开来的。但是如果你要合并字体，就会遇到问题了。

至于平台上面的你认为的那个功能，其实我们会重排unicode的。还是上面那边例子，如果你把a，b里面的图标都加到购物车，到一个新项目，为了避免冲突，我们会把其中一个图标的unicode往后重新分配的哈。

**Comment by NE-SmallTown** [comment]
@purplebamboo 感谢回复。合并的确是可能会存在重复的问题，所以上面我也提到了
> 建议在合并字体文件的时候进行提示或者判断，不同组件的font-famlily必须不同，否则肯定会出乱子

这里的乱子就是指重复。font-famlily不同则不允许合并，就不存在这个乱子了。

你后面提到的重新分配其实已经解决了这个问题了，只是要实现这个效果，需要人工手动去操作，真的很苦逼v_v，所以才希望你们新增加一个合并功能，让用户选择要合并的项目，你们写个for把这些项目里面图标提取出来，加入购物车，然后create一个新项目，把购物车里面的加入进去，然后就ok了～

这个其实都不是很麻烦，主要是我上面提到的css也要对应更改的问题，如果比较忙的话，可以暂时不考虑这个，我打包的时候不打包原先分离的这些css，只打包最后上面那种方法新建的项目里面的那个css就行了。

**Comment by purplebamboo** [comment]
嗯  合并项目，又是一个新的操作了。

其实我理解亲主要是  生成新项目比较麻烦，需要手动一个个去点。

其实换一种思路，如果项目里提供批量加入购物车，已经全选按钮，应该可以解决这个问题。

如果再做一个合并功能，功能太多有点凌乱。

针对上面两种方式，我们再考虑下哈。

**Comment by luchaoqun123** [comment]
那个追问一下,iOS 使用的ttf怎么办.css文件是有命名空间的,并且可以通过项目前缀来避免,但是iOS 是直接用的myName.ttf.没办法区分啊.myFontFamily.ttf里面的e600和yourFontFamily.ttf里面的e600没办法做到区分啊.求指教,如果我的issue提错了,请放传送门
