### ISSUE TITLE
为什么iconfont在IE8下不显示

### ISSUE THREAD

**Issue by ivyaii** [thx/iconfont-plus#841]
不是装的虚拟机，也不是用的模拟器，就是xp系统下的IE8，不显示。求助！

**Comment by chengmeng1117** [comment]
我也遇到了这个问题 但是好像以前是可以显示的 现在新下载的字体包 ie8下打开demo.html都显示不了
你现在这个问题解决了么

**Comment by x269147836** [comment]
删除base64支持就行了。

**Comment by fukai2952** [comment]
第五行 url('data:application/x-font-woff;charset=utf-8 ... 改成 url('iconfont.woff') format('woff'), 就能兼容IE8

**Comment by yisibl** [comment]
https://github.com/thx/iconfont-plus/issues/678
