### ISSUE TITLE
请问能不能做个彩色图标的IOS版本的DEMO?

### ISSUE THREAD

**Issue by mdjwanghong** [thx/iconfont-plus#849]
我用的是IOS版的，采用unicode引用，现在有彩色版本了，说是使用symbol引用，但是说的太简单了，请问能不能做个完整的DEMO，谢谢！

**Comment by mdjwanghong** [comment]
恳请阿里的工程师将demo做的详细些，这点腾讯的产品做的非常好，毕竟我们不是搞这个专业的，要让外行人，用最短的时间内集成，才有助于项目的发展！

**Comment by WuTengWei** [comment]
请问你知道怎么用了吗？ @mdjwanghong

**Comment by yisibl** [comment]
请关注：https://github.com/thx/iconfont-plus/issues/1938
