### ISSUE TITLE
纯白图标显示问题

### ISSUE THREAD

**Issue by inJonathan** [thx/iconfont-plus#85]
纯白图标会看不到图标，希望修正

**Comment by purplebamboo** [comment]
的确是个问题，但是目前好像没啥好的解决办法？ 我理解如果是纯白的就是单色的，其实单色的无所谓色彩，因为都可以随意改的，不管在下载框里，或者是下载下来的字体，纯色的后期改颜色都比较方便，所以其实纯色图标直接设计成黑色就好了，使用时随意修改颜色。

这个我再去找我们设计师讨论下哈
