### ISSUE TITLE
iOS下，x会显示为打印机

### ISSUE THREAD

**Issue by mydy1987** [thx/iconfont-plus#850]
用的UISegmentedControl这个控件，文字只能设置一种字体，文字里含有x，我是用iconfont作为字体。一用iconfont就会显示打印机，怎么才能把这个打印机去掉呢。

你们说是因为xp下safari会闪退，我是iOS,能不能在网站上设置两个版本呢。你们考虑的xp是极小数情况。我们iOS,Android，前端，目前都会遇到这个问题，也就是规避了极小部分人的问题，但是却影响了极大多数人的使用。我建设把没有打印机的设置为默认下载版本。有打印机的，弄成一个特别版本，供少数人下载。

我看到官方解答里还有一种答案，是把打印机这个x，覆盖掉，请问怎么才能覆盖掉呢。

**Comment by mydy1987** [comment]
排查和处理这个x带来的bug，用了一天的时间，还没有搞定，求官方的攻城狮助攻！

**Comment by win7killer** [comment]
#814 

使用方法上暂时规避一下

**Comment by Muqing1221** [comment]
@cricy
