### ISSUE TITLE
图标的AI格式下载下来都是SVG格式

### ISSUE THREAD

**Issue by xxx369238976** [thx/iconfont-plus#86]
尝试了好几个图标发现AI格式下载下来都是SVG ，但是PNG下载下来是正常的，SVG也是正常的，就是AI格式出现了问题。

**Comment by Muqing1221** [comment]
恩，因为暂时ai格式会出现一丢丢小的问题，我们还在紧张修复，所以暂时仅提供svg格式的下载了

**Comment by purplebamboo** [comment]
这里讨论哈：
https://github.com/thx/iconfont-plus/issues/139
