### ISSUE TITLE
能否添加索引，通过一个图标找到作者创作的其他图标。

### ISSUE THREAD

**Issue by Overyet** [thx/iconfont-plus#862]

**Comment by Muqing1221** [comment]
图标详情浮层可以；但只有图标库中的图标为公开图标

**Comment by mjm13** [comment]
同问, 同一作者的图标更配套一些,但是目前只能通过图标的名称查找十分不方便

**Comment by yisibl** [comment]
点击用户主页或者搜索用户名可以看到当前用户所有公开的图标库：
http://iconfont.cn/search/index?spm=a313x.7781069.1998910419.54&searchType=user&q=Violayiqi
![image](https://user-images.githubusercontent.com/2784308/43768562-3c0d7930-9a6a-11e8-9319-048d51e8a17d.png)
