### ISSUE TITLE
标签数量过多、单个标签过长都会导致溢出

### ISSUE THREAD

**Issue by DiigoXie** [thx/iconfont-plus#869]
![tim 20180402145352](https://user-images.githubusercontent.com/15647681/38186469-bf11f0fc-3685-11e8-98fb-184b26e0b7ea.png)
![tim 20180402145347](https://user-images.githubusercontent.com/15647681/38186472-c4bbb222-3685-11e8-9f7f-85be6495bd9f.png)

就是这样这样。

**Comment by Muqing1221** [comment]
亲，这个问题我们已经优化啦，谢谢反馈
