### ISSUE TITLE
绑定第三方账号

### ISSUE THREAD

**Issue by slimcheng** [thx/iconfont-plus#876]
能否在微博登录的状态下，再为这个账户绑定github账号，现在只能单一的用其中一种方式登录某个账号

**Comment by yisibl** [comment]
Duplicate of #1718

**Comment by yisibl** [comment]
手机注册登录功能已经上线，[点击查看](https://mp.weixin.qq.com/s?__biz=Mzg5OTUzNjQ0Mg==&mid=2247483866&idx=1&sn=e6d02ca84cba8157c8f90d072db66bbf&chksm=c050828ff7270b99b00d784681a47fb4d1063a9139732075dc84d8da4ad77d446df386384acc&token=1155149842&lang=zh_CN#rd) 绑定手机后，可以自由关联其他三方账号。

相关 issue：#1718
