### ISSUE TITLE
iconfont在ie8下不显示

### ISSUE THREAD

**Issue by sylyie** [thx/iconfont-plus#879]
iconfont在ie8下不显示，但是2016年的时候下载下来的iconfont就可以在ie8下显示，为什么，怎么解决

**Comment by fukai2952** [comment]
第五行 url('data:application/x-font-woff;charset=utf-8 ... 改成 url('iconfont.woff') format('woff'), 就能兼容IE8

**Comment by yisibl** [comment]
https://github.com/thx/iconfont-plus/issues/678
