### ISSUE TITLE
建议新增一个   修改图标权限的功能（具体见表述）

### ISSUE THREAD

**Issue by liuwf0314** [thx/iconfont-plus#886]
目前功能：用户新建一个项目，新加的管理员都可以看到这个项目，并且修改；
建议功能：建立项目的管理员可以对其他管理员进行设置权限（是否可以修改项目图标）
应用场景：使用图标的多数后台开发就可以直接获取图标，但是维护者是前端开发工作人员

**Comment by Muqing1221** [comment]
了解，现在有个迂回的解决方法，就是锁定图标，可以暂时解决亲的问题

**Comment by yisibl** [comment]
项目成员多角色管理功能已经上线，后续其他相关问题，请统一关注或回复： Duplicate of #1512
