### ISSUE TITLE
如何上传彩色图标

### ISSUE THREAD

**Issue by gigi13164269** [thx/iconfont-plus#89]
看到首页有彩色图标，我们设计师也想上传彩色图标，选择了【按多色图标处理】但上传以后还是黑白色的，是说多色上传还没开放吗？

**Comment by gigi13164269** [comment]
知道怎么操作了  是说上传图标以后要一个个的去选色哈？看了一下交互形式略麻烦呢   而且老是选不准区域

**Comment by Muqing1221** [comment]
不是啊，亲弄错了吧，是你再绘制的时候，绘制彩色图标，然后在上传的时候选择，这批图标按多色处理
http://www.iconfont.cn/plus/help/detail?helptype=draw
看一下帮助中心的介绍哈

**Comment by gongeek** [comment]
@gigi13164269  是选了按多色处理还是黑白的吗？可以把不行的图标传给我们看下 gongweiqm@qq.com
