### ISSUE TITLE
能不能有一个项目默认的链接永远指向该项目最新的css文件啊？不然每一次修改图片的时候都要重新点下载，接着copy在线css链接，好麻烦啊！望采纳。

### ISSUE THREAD

**Issue by YoungYama** [thx/iconfont-plus#891]

**Comment by cai15255461474** [comment]
OJBK

**Comment by PeterRock** [comment]
css链接如果固定，浏览器是要缓存下来的，用户如果不强刷浏览器，你的新图标是出不来的。

**Comment by lomocc** [comment]
请问一下当在线链接更新后，如何实现我前端构建自动跑脚本去更新地址呢？

**Comment by hfhanfei** [comment]
> css链接如果固定，浏览器是要缓存下来的，用户如果不强刷浏览器，你的新图标是出不来的。

手动更新比强刷麻烦，而且，如果css链接用在了多个项目，更新后还需要挨个修改，如果漏了一个就是一个项目的出问题。

**Comment by numa001** [comment]
> 请问一下当在线链接更新后，如何实现我前端构建自动跑脚本去更新地址呢？

只能手动改。。

**Comment by lomocc** [comment]
我写了一个基于 puppeteer 根据项目编号和 github 自动登陆获取项目 iconfont 的包：，**get-iconfont-svg**

**Comment by jinxiking** [comment]
确实 项目一多  就不敢动了 不然重新生成链接改的地方就太多了  现在得方案是每个项目 都有单独ICON项目  一旦改动不会影响所有项目
