### ISSUE TITLE
搜索优化、单个图标进入图标集

### ISSUE THREAD

**Issue by SophiaHaha** [thx/iconfont-plus#895]
建议搜索的时候可以根据搜索出来的图标进入图标所在的图标集

**Comment by Muqing1221** [comment]
可以的，精选图标在图标详情浮层，可以看到所归属的“图标库”

**Comment by Muqing1221** [comment]
可以的，精选图标在图标详情浮层，可以看到所归属的“图标库”

**Comment by Kirtlo** [comment]
> 可以的，精选图标在图标详情浮层，可以看到所归属的“图标库”

悬浮后只能加入、收藏和下载，并不能看到所属图标库

**Comment by yisibl** [comment]
如果这个 icon有对应的图标库，点击下载按钮，会有所属图标库的链接。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)
