### ISSUE TITLE
支持批量下载图片功能

### ISSUE THREAD

**Issue by tolerance-go** [thx/iconfont-plus#896]
某些场景只可以使用单个图片，但是不支持批量的话真的很痛苦

**Comment by Muqing1221** [comment]
可以批量下载的，先批量加入购物车，然后再批量下载就好

**Comment by tolerance-go** [comment]
@Muqing1221 太棒了，是的，加入购物车内的图标可以批量下载素材；其实我之前说的情况是在我的项目内，点击批量编辑的时候，没有批量下载功能~
