### ISSUE TITLE
建议顶部导航可以跟随页面滚动

### ISSUE THREAD

**Issue by v4125251** [thx/iconfont-plus#9]
可以随时在页面底部使用顶部导航条查询。页面滚动至第二屏时导航条跟随，只显示导航与搜索，当前位置标题隐藏

**Comment by Muqing1221** [comment]
亲可以试试回到顶部？icon在右下角

**Comment by purplebamboo** [comment]
嗯 亲  感谢建议， 这个我们再考虑下，之前是觉得 滚动体验不好，所以做了右下角的三个按钮，亲可以先体验下。
