### ISSUE TITLE
图标移动上去显示下载，收藏等操作层叠在上面的设计思路

### ISSUE THREAD

**Issue by tanxuxu** [thx/iconfont-plus#91]
图标移动上去显示下载，收藏等操作层叠在上面的设计思路不好，有时候交流的时候，鼠标移动上去本来想问同事这个图标怎样，结果就被挡住了视线，还不如以前的方式好

**Comment by Muqing1221** [comment]
恩，点击下载icon出大图浮层，更高清无码哈~~
