### ISSUE TITLE
建议 添加新图标后新生成的css名称/链接不要改变

### ISSUE THREAD

**Issue by 2929** [thx/iconfont-plus#911]
在线生成链接挺好用的，就是每次添加新的图标，生成链接，发现css的名称/链接每次都在变，这样每次都需要去项目中更改css链接，有些项目css不是加到整体布局里面，是分开布局，结果要一一找出来进行替换，你们看下能不能功能优化下，让新生成的css链接地址，这样就不用去更改项目文件了，只要在线添加就可以了，或者多一个按钮，如果需要改变的就改变，不需要改变的就更改原来的css，而不是新生成一个新的另一个名称的css文件。

**Comment by PeterRock** [comment]
Duplicate of #891

**Comment by ziyunfei** [comment]
Duplicate of #1331
