### ISSUE TITLE
打开下载的字体包中的demo页面，字体显示不了

### ISSUE THREAD

**Issue by chenzhe-pro** [thx/iconfont-plus#914]
打开下载的demo_fontClass.html，谷歌浏览器中字体显示不了，查看console，发现报警告：
OTS parsing error: head: Failed to parse table
![image](https://user-images.githubusercontent.com/12438085/40633777-64943c22-6324-11e8-89f6-2119a1729715.png)
然后放到项目中也是报错。另外safari是可以的，没有报警告。所有代码都没有改过，都是打开下载的页面。

**Comment by yisibl** [comment]
字体路径不对，麻烦贴一下 这个 HTML 文件的全部代码。
