### ISSUE TITLE
从iconfont样式设置上出发提出的建议

### ISSUE THREAD

**Issue by asanlu** [thx/iconfont-plus#92]
先上图：

![qa1](https://cloud.githubusercontent.com/assets/17611921/19849566/f7a79f6e-9f8e-11e6-902f-179066c13066.png)

**1、css选择器设置公共的样式名，在项目编辑里能否添加一个自定义取名的（比如：iconfont可以自定义为icon、fa之类的）；**
**2、样式字体默认大小能否去除font-size设定16大小，这样在开发上不能默认继承父级字体大小；**

目前处理两个，都是通过后期进入css里手动设置，如果项目有新图表，又要手动打开文件更改，在开发初期比较麻烦。

其它后续体验再反馈 ![ef tghw vx a3c4 87xl](https://cloud.githubusercontent.com/assets/17611921/19849965/eeef5220-9f90-11e6-9bdf-88ff7c1a89cd.png)

**Comment by NE-SmallTown** [comment]
1.更多操作-》编辑项目里面可以设置

2.我个人暂时没有发现哪里可以设置，不过你可以自己写个正则去替换

**Comment by purplebamboo** [comment]
如上面同学所说  ，可以设置  font-family

至于默认的16px的大小，可以直接覆盖下样式就可以呀。
