### ISSUE TITLE
提供个ttf编辑器吧😄

### ISSUE THREAD

**Issue by Juude** [thx/iconfont-plus#93]
看，百度都做了 
http://fontstore.baidu.com/static/editor/index.html
Fork一下提交也行啊

**Comment by Muqing1221** [comment]
亲，我萌人手不够，要不你帮我萌fork fork~~~哈哈

上句纯讲笑...

认真脸.jpg,我们会在之后的日常优化中，认真考虑亲的建议的，方便的话，你可以留言讲一下你的需求场景，频次和重要性等等~

**Comment by purplebamboo** [comment]
亲  跟我们的需求场景不符呀，我们的场景是增加图标生成ttf。这个是自己编辑ttf操作成本更大呀。

当然我们后面也会考虑的，比如我们做了webfont，后续可能会考虑做这么一个在线的ttf编辑器的。不过目前精力的确有限，先优先保证主要功能哈。

**Comment by Juude** [comment]
现在是希望将一个ttf中所有图标批量导入到自己的仓库里，有这个功能么？
因为之前维护这个ttf文件的人不在了，又没有必要新建个仓库

**Comment by purplebamboo** [comment]
其实是有办法的。
你可以用这个  导出svg： https://github.com/purplebamboo/font-carrier

之后去平台上传就行了。
