### ISSUE TITLE
搜索单个图标不能查看此风格所在库的全部图标吗 

### ISSUE THREAD

**Issue by k810202771** [thx/iconfont-plus#930]
搜索单个图标不能查看此风格所在库的全部图标吗

**Comment by Liu-wenxiang** [comment]
这个因该有，想找一套风格一致的太难了，官方库又不全

**Comment by yisibl** [comment]
近期我们进一步优化了所属图标库的页面样式，更加醒目了。
![image](https://user-images.githubusercontent.com/2784308/72677337-59aace80-3ad6-11ea-9c3c-bc2341a7ad64.png)
