### ISSUE TITLE
建议增加管理员转让功能

### ISSUE THREAD

**Issue by Jack-and-rose** [thx/iconfont-plus#934]
因为只有管理员才能添加团队新成员，管理员离开项目组后 却不能转让图标项目管理员的身份给其他成员  给后期维护管理带来很大不便

**Comment by ashleybitmax** [comment]
是的，现在如何转交管理员呢？管理员离开项目后，很不方便！

**Comment by gongeek** [comment]
有转让功能
![image](https://user-images.githubusercontent.com/3911824/52681051-84f77600-2f75-11e9-815b-99700e5a8d28.png)

**Comment by ashleybitmax** [comment]
Thanks!
