### ISSUE TITLE
在线CSS链接可以保持不变么？比如设置一个 alias

### ISSUE THREAD

**Issue by wensonsmith** [thx/iconfont-plus#94]
首先很感谢你们提供这么好的工具！

然后现在每次改动项目的图标， 项目的在线CSS链接都会变一次，我还得去项目代码里改一次，
十分的麻烦，所以如果技术上允许，可不可以将这个在线CSS链接固定，比如设置一个alias 这样。

**Comment by yisibl** [comment]
如果 CSS 文件的链接不变会有缓存问题。

**Comment by wensonsmith** [comment]
能不能做一个转发代理， 比如： 每次生成的 CSS 可以是随机的名字 iconfont_8x0s9g2dt.css  , 但是我可以访问www. iconfont.cn/username/project_name_id.css 或者 .js  就可以自动关联到这个  iconfont_8x0s9g2dt.css

**Comment by purplebamboo** [comment]
亲  这个问题我们在老版本制作的时候就考虑过。
首先cdn地址不变肯定是不靠谱的：
* 首先缓存问题是个绕不过去的坎。
* 而且万一这个项目已经在线上使用了，你这突然更新下css，线上就出问题了。

所以 每次更新图标肯定得是新地址。

至于转发代理的问题，是这样的，我们不适合做。
* 如果用css，那么还是有缓存的问题
* 如果用js，那么你需要用js动态去请求一个接口返回当前最新的样式。这个接口不是cdn，如果我们开了影响太大。再有就是还得做好，线上线下的版本，得去配置，不能影响线上。总之是个很复杂的事情。

所以综上所属，还是每次更改图标修改下引用比较靠谱。 ＝ ＝。
