### ISSUE TITLE
【建议】不要编码woff字体，这造成样式文件体积过大，且不兼容IE8

### ISSUE THREAD

**Issue by JSoon** [thx/iconfont-plus#942]
如题描述。

**Comment by ivyaii** [comment]
去掉woff，真能解决IE8下不显示的问题吗？

**Comment by ivyaii** [comment]
真机非模拟器浏览器测试过，真的有效耶~
顶上去

**Comment by JSoon** [comment]
@ivyaii 是的，还是要本着负责任的态度来发问的，目前解决方案是覆写@font-face（很low），避免每次都去手动改。

**Comment by yisibl** [comment]
重复 https://github.com/thx/iconfont-plus/issues/678
