### ISSUE TITLE
为什么不支持渐变色

### ISSUE THREAD

**Issue by vand7813** [thx/iconfont-plus#952]
为什么不支持渐变色，渐变色多好看

**Comment by yisibl** [comment]
计划实现中。

**Comment by IDwuqing** [comment]
渐变色我早已代码实现了 需要研究下你们

**Comment by AirJavan** [comment]
> 渐变色我早已代码实现了 需要研究下你们

能不能说下怎么实现的。

**Comment by yisibl** [comment]
支持渐变图标请关注：https://github.com/thx/iconfont-plus/issues/1938
