### ISSUE TITLE
下载不了项目

### ISSUE THREAD

**Issue by enjoyWeb** [thx/iconfont-plus#955]
1、点击下载至本地，提示：
{"code":500,"message":"LOGIN REQUIRED"}
2、确认是已经登陆了的，不然也看不到项目

**Comment by Arpey** [comment]
是啊，不知道怎么搞

**Comment by yisibl** [comment]
之前的 GitHub 等三方登录会偶尔被墙，现在我们支持直接手机登录了。

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
