### ISSUE TITLE
关于搜索图标功能的建议

### ISSUE THREAD

**Issue by SaltedFish999** [thx/iconfont-plus#957]
根据关键字查出的数据，建议添加查看该专辑的功能。

**Comment by yisibl** [comment]
专辑是指「图标库吗」？

**Comment by SaltedFish999** [comment]
嗯，是指图标库。比如我在图标库中搜索某个关键字，查出的图标我感觉设计的很好看，想要看这个图标的所属专辑里的图...  就是这么个意思。

**Comment by yisibl** [comment]
1. 点击下载按钮
![image](https://user-images.githubusercontent.com/2784308/44440512-f4119480-a5fa-11e8-9f27-0650ceecc7e0.png)
2. 点击
![image](https://user-images.githubusercontent.com/2784308/44440524-012e8380-a5fb-11e8-9dfc-cbf0f9851e3a.png)
