### ISSUE TITLE
建议在找到合适的图标时能浏览用户建立的对应的库图标

### ISSUE THREAD

**Issue by kshiw** [thx/iconfont-plus#96]
建议在找到合适的图标时能浏览对应的库图标
因为我们项目在实际开发中的小图标想依赖iconfont建立一套专用的企业库 但是在找到合适的图标时却很难发现 类似模样的图标样式  这样大大的增加了寻找的难度  如果可以浏览该图标的出处 这样用起来也是很愉快的

**Comment by Muqing1221** [comment]
下载浮层左上角，如果该图标隶属于某公共图标库，可以看到归属库的~~亲试下哈

**Comment by purplebamboo** [comment]
目前  可能不大明显，我们后续会考虑优化这个交互的哈。
