### ISSUE TITLE
以前是用新浪微博登录的，现在登录不了，怎么办？为什么不能用淘宝或者支付宝帐号登录啊

### ISSUE THREAD

**Issue by DreamCapriccio** [thx/iconfont-plus#97]
以前是用新浪微博登录的，现在登录不了，怎么办？为什么不能用淘宝或者支付宝帐号登录啊。
用微博登录就提示：抱歉系统繁忙，暂时无法处理你的请求。。。
微博也不知道什么原因给冻结了，按照流程验证手机根本不能解冻，好无语啊。。
怎么办？求管理员支个招，我的用户名是 追梦随想 能不能给我绑定其他帐号，哎，貌似也就剩下Github了，给我绑定这个也好，感谢，不然收藏的那么多图标和项目用的图标都找不到了。

**Comment by maoshu** [comment]
微博我可以用啊

**Comment by Muqing1221** [comment]
别急别急，该是你的一个也不会少呢~
我们开发同学稍后帮你查一下哈~

**Comment by DreamCapriccio** [comment]
感谢美女帮忙，为了登录帐号纠结了好几天啊，新浪微博也无法解冻，坑爹的，坚决不用微博了~~~

**Comment by purplebamboo** [comment]
亲  你把微博账号给我，还有  github账号  给我，这样 我帮你把微博的东西  都挪到github上的账号里。因为微博登陆不稳定，我们也很无奈。

**Comment by DreamCapriccio** [comment]
@purplebamboo 微博帐号要么是手机15876924907 要么是邮箱1397770929@qq.com， github 帐号就是这个邮箱了，多谢多谢

**Comment by purplebamboo** [comment]
@DreamCapriccio  
已经帮你把项目都转过去了。

至于你收藏的图标，你可以看到的。

http://www.iconfont.cn/plus/user/detail?userViewType=likes&uid=113029

这是你之前的账户，哈，你可以去再收藏一次。

**Comment by yunshitech** [comment]
登录的时候，淘宝登录那个选项是黑白色，无法选择 我项目东西都在淘宝账号里啊!怎么再用淘宝号登陆啊？

**Comment by erguotou520** [comment]
你好，现在微博不能用帐号密码登录了，气的我直接废弃该帐号了，能帮忙把之前的帐号信息迁移/复制到Github的帐号下么？
原微博帐号 `erguotou520@126.com` 现在github的帐号id是 `7586479`

**Comment by lightandflower** [comment]
@purplebamboo 您好！账户被冻结了，请问可以解决吗？微博帐号绑定的手机是18705050395，绑定的邮箱是737714251@qq.com；能否将其绑定到github 帐号：franklee19@163.com，十分感谢！
