### ISSUE TITLE
antd.css中antd自带的图标无法用unicode显示

### ISSUE THREAD

**Issue by tiller2008** [thx/iconfont-plus#977]
less文件中使用 `@import '~antd/dist/antd.css';` 导入antd的icon库，并在js文件中引用

查找“保存”的unicode为E669，分别使用font-class和unicode来用
```jsx
<i className="anticon anticon-save">&#xe669;</i>
```
显示font-class，但不显示unicode的，如下图
![save](https://user-images.githubusercontent.com/40765475/43943341-ce506de4-9cad-11e8-942d-74926a7516e7.png)

**Comment by gongeek** [comment]
请反馈到 antd
