### ISSUE TITLE
🙇🙇🙇🙇 图形没有居中！

### ISSUE THREAD

**Issue by wexs** [thx/iconfont-plus#98]
1.  一个120画板里画一个120的圆形，在网站上显示溢出了（有图：

![image](https://cloud.githubusercontent.com/assets/8132880/19881105/e759dcd0-a03d-11e6-893a-0fe1148d1b55.png)

是无法做到完全居中吗？需要手动调整吗？

2.   sketch里字号为20时，文本框的长宽会变成20*21。长宽不一，其他的字号却没有这个问题：

![image](https://cloud.githubusercontent.com/assets/8132880/19881001/0d7978b8-a03d-11e6-9ff6-1bbbc8762025.png)

**Comment by Muqing1221** [comment]
亲，可能是画的时候没有居中，所以上传上来就没有居中
sketch的问题，我们就不解决了哈，你试试手动调节成20*20，然后居中，然后再上传看看

或者在线编辑情况下，你缩小下icon试下，就不会溢出了（但是，还是不是正圆呀）

**Comment by wexs** [comment]
（;￣O￣）我试过所有的字号，都是OK的，方方正正。唯独20号会突出一个单位，我试过好多次了。。。
🙇 🙇 🙇 ，希望你们白忙之中抽空看一下这个小小的BUG～ 🙏 谢谢 🙏

第一个问题我试过了，网站上显示是有点错位，但是导出的iconfont是正常。😏😏😏

**Comment by Muqing1221** [comment]
你是说sketch的bug还是我们产品内的呀

**Comment by wexs** [comment]
= =，嗯。。这个不好说。。
但我试过很多个平台的iconfont，都没有这个问题噢～

**Comment by ruanyufei** [comment]
>
