### ISSUE TITLE
下载不了有大神懂怎么解决的吗？

### ISSUE THREAD

**Issue by ihaveabanana** [thx/iconfont-plus#985]
{"code":500,"message":"LOGIN REQUIRED"}

点击下载项目至本地就是跳转页面显示这串，请问有人知道怎么回事吗？

**Comment by yisibl** [comment]
之前的 GitHub 等三方登录会偶尔被墙，现在我们支持直接手机登录了。

相关 issue：https://github.com/thx/iconfont-plus/issues/2092
