### ISSUE TITLE
希望彩色图标也能关键词筛选

### ISSUE THREAD

**Issue by goblin123dan** [thx/iconfont-plus#99]
关键词搜索时，希望可以选择检索彩色图标或单色图标

**Comment by Muqing1221** [comment]
谢谢亲的建议，因为现在多色图标数量还比较少，所以暂时还并未添加筛选条件，之后在合适的时候，我们会为搜索结果增加筛选条件选项的~~
期待吧~

**Comment by purplebamboo** [comment]
这里统一讨论：
https://github.com/thx/iconfont-plus/issues/139
