### ISSUE TITLE
推荐生成woff2格式

### ISSUE THREAD

**Issue by JuvenRui** [thx/iconfont-plus#993]
现在默认生成的都是eot, tff, svg格式的，都是面对较老的浏览器了。现在除了woff，woff2也开始盛行起来。希望团队可以考虑自动生成woff2格式的文件。

**Comment by yisibl** [comment]
已经在实现了。

**Comment by JuvenRui** [comment]
赞一个！！

可以参考google开源的woff2：https://github.com/google/woff2

**Comment by yisibl** [comment]
已经支持了！
