### ISSUE TITLE
fontclass方式引用,ie8下不显示

### ISSUE THREAD

**Issue by xiaoju-zhang** [thx/iconfont-plus#997]
通过fontclass方式使用图标时,单个项目超过一定数量(不确定,有的时15个,有的时19个)时,ie8下不显示图标;
是单个项目ie8下有数量限制?还是字体图标相互冲突?有知道的大大么

**Comment by yisibl** [comment]
麻烦提供一下链接。

**Comment by xiaoju-zhang** [comment]
http://39.107.81.72:8383/tubiao/index.html

**Comment by yisibl** [comment]
好的，我看看。
