### ISSUE TITLE
两台电脑检索结果不同 

### ISSUE THREAD

**Issue by xuejiao0728** [thx/iconfont-plus#999]
检索关键词 消息 
电脑同是WIN10系统  360安全版本相同
一台 用360安全 兼容模式 检索结果 5000
另一台 360安全 兼容模式 检索结果551 
其他浏览器如chrome检索结果均是551 同是测试了登录账号结果一致

**Comment by gongeek** [comment]
![image](https://user-images.githubusercontent.com/3911824/45525714-c5a46500-b806-11e8-8457-ae6507f43886.png)
可能是一台是全部 一台是精选

**Comment by xuejiao0728** [comment]
> ![image](https://user-images.githubusercontent.com/3911824/45525714-c5a46500-b806-11e8-8457-ae6507f43886.png)
> 可能是一台是全部 一台是精选
感谢指点
